### ISSUE TITLE
Retrieve HostSystem including VMs

### ISSUE THREAD

**Issue by satyababu** [vmware/govmomi#1000]
Hi,

We have examples to understand how we can get datastores, hosts, vms information. Thanks for providing those examples.

I have one quick question in "govmomi/examples/hosts/main.go"
mo.HostSystem type contains Vm ([]types.ManagedObjectReference)

var hss []mo.HostSystem
err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"summary"}, &hss)
        for _, hs := range hss {
		fmt.Fprintf(tw, "%s\t", hs.Vm)   // nil value
		fmt.Fprintf(tw, "\n")
	}

When I try to retrieve Vm, its giving nil, 
Vm is supposed to give array of VMs object references?

Here I am trying to fetch VMs for all hosts, since I see hs.Vm is nil, 
I am looking for a way to do this
Please let me know

Thanks a lot your help

-Sunny

**Comment by dougm** [comment]
The code above only collects the `summary` property, you have to add `vm`:
```
err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"summary", "vm"}, &hss)
```

**Comment by satyababu** [comment]
Sounds good. Thanks Doug
