### ISSUE TITLE
Odd behaviour of object.collect

### ISSUE THREAD

**Issue by philzyk** [vmware/govmomi#1001]
Hello!
I've tried to navigate over MOB via object.collect and find out that:
govc object.collect  VirtualMachine:vm-95824 config.hardware.device[4000].key works fine
But  govc object.collect  VirtualMachine:vm-95824 config.hardware.device[4000].macAddress gives
- /usr/bin/govc_linux_amd64: ServerFaultCode: InvalidProperty
Difference is in data type. I can't read only string properties.
So i can't get exact properties in this way and need to use jq for unneeded JSON transformations.
Same for the govc object.collect  VirtualMachine:vm-95824 config.hardware.device[4000].backing.port and deeper but for all data types.

So, my question is - this is a bug or feature?
Thank you.

**Comment by dougm** [comment]
I think that's because the property collector on the ESX/VC side only supports specific fields for the base type, a VirtualDevice in this case. You can use jq like so:

```console
% govc object.collect -s -json $vm config.hardware.device[4000] | jq -r .[].Val.MacAddress
00:0c:29:a9:67:d2
```

**Comment by philzyk** [comment]
Thank you. Sorry, is it a bug in Property collector of vCenter 6.0 u3, which i'am using, or it's a same in vCenter 6.5?. I've tried to escape not needed JSON operations and transformations via jq.
And same problem for other object. commands?

**Comment by dougm** [comment]
I don't think it's a bug, but a limitation.  I see the same behavior with 6.5.  We could probably do something to workaround this limitation on the client side within the object.collect command.

**Comment by philzyk** [comment]
Very strange limitation. Probably it's a kind of data protection from Vmware side ;-)
Oh it would be great! Less JSON, less operations and errors.
Anyway, you did a GREAT job with this product!
Like it's more then rvc.
Probably someday you will port namespace and TAB-browsing from it?

**Comment by dougm** [comment]
ok, let's leave this open and we can look into working around this limitation.

Thanks, glad you are finding govc useful!  Not sure what you mean by "port namespace" ?
If you are looking for tab-completion, there is [bash completion](https://github.com/vmware/govmomi/blob/master/scripts/govc_bash_completion)
Personally, I use the [Emacs](https://github.com/vmware/govmomi/tree/master/govc/emacs) shortcuts.

**Comment by philzyk** [comment]
Probably better to say console where you can use not only ls, but cd and marks as quick path values. So you can navigate to any depth of properties.
> cd /192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/datastores
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/files
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/host
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/networks
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/resourcePool
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/snapshots
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/vmprofiles
> cd /192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/d
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/datastores
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices
> cd /192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/d
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/datastores
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices
> cd /192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/cdrom-3002
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/disk-1000-0
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/ethernet-0
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/ide-200
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/ide-201
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/keyboard-600
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/pci-100
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/pointing-700
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/ps2-300
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/pvscsi-1000
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/sio-400
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/video-500
/192.168.1.30/DC-LV-01/computers/HA-DRS-01/resourcePool/pools/ZONE_TEST/pools/INFRASTRUCTURE/vms/rds-01/devices/vmci-12000

**Comment by dougm** [comment]
@philzyk gotcha, feel free to open a separate feature request for the cd/mark navigation.
