### ISSUE TITLE
XML bug - "0" omitted from an array of int32

### ISSUE THREAD

**Issue by naphatkrit** [vmware/govmomi#1008]
Simplest repro:

```
type testType struct {
	IntArray []int32 `xml:"intArray,omitempty"`
}

func TestXmlBug(t *testing.T) {
	b, err := xml.Marshal(testType{[]int32{5, 0, 1, 2}})
	if err != nil {
		t.Fatal(err)
	}
	expected := `<testType><intArray>5</intArray><intArray>0</intArray><intArray>1</intArray><intArray>2</intArray></testType>`
	if expected != string(b) {
		t.Fatalf("Mismatch\nExpected %s\nActual   %s", expected, string(b))
	}
}
```

This will result in the error:
```
Mismatch
Expected <testType><intArray>5</intArray><intArray>0</intArray><intArray>1</intArray><intArray>2</intArray></testType>
Actual   <testType><intArray>5</intArray><intArray>1</intArray><intArray>2</intArray></testType>
```
Notice that the encoded array is [5, 1, 2] instead of [5, 0, 1, 2] because 0 got omitted.

**Comment by naphatkrit** [comment]
this seems to be because `omitempty` on an array is being wrongly inherited by its members. so omitempty on `[]int32` should only omit the entry if the array is empty. but it's also passing `omitempty` to each of its children, and 0 is an empty value

**Comment by naphatkrit** [comment]
this seems to be the simplest fix:
```
diff --git a/go/src/github.com/vmware/govmomi/vim25/xml/marshal.go b/go/src/github.com/vmware/govmomi/vim25/xml/marshal.go
index 39bbac1d1719..297fba9d1554 100644
--- a/go/src/github.com/vmware/govmomi/vim25/xml/marshal.go
+++ b/go/src/github.com/vmware/govmomi/vim25/xml/marshal.go
@@ -398,8 +398,15 @@ func (p *printer) marshalValue(val reflect.Value, finfo *fieldInfo, startTemplat

        // Slices and arrays iterate over the elements. They do not have an enclosing tag.
        if (kind == reflect.Slice || kind == reflect.Array) && typ.Elem().Kind() != reflect.Uint8 {
+               var childFinfo *fieldInfo
+               if finfo != nil {
+                       // avoid leaking fOmitEmpty into child elements
+                       childFinfo = &fieldInfo{}
+                       *childFinfo = *finfo
+                       childFinfo.flags &= ^fOmitEmpty
+               }
                for i, n := 0, val.Len(); i < n; i++ {
-                       if err := p.marshalValue(val.Index(i), finfo, startTemplate); err != nil {
+                       if err := p.marshalValue(val.Index(i), childFinfo, startTemplate); err != nil {
                                return err
                        }
                }
```

**Comment by dougm** [comment]
vim25/xml is a fork of Go's encoding/xml package.. ideally we'll remove vim25/xml someday and just use Go's standard package.  The encoding/xml package behaves the same way in this respect, so I'd prefer not to diverge in this case.

Which API(s) need this change?

**Comment by naphatkrit** [comment]
Anywhere we have an array and specify omitempty.

https://raw.githubusercontent.com/vmware/govmomi/master/vim25/types/types.go, example is AffinitySet

**Comment by dougm** [comment]
ok, but this is the expected behavior: https://golang.org/pkg/encoding/xml/#Marshal

> a field with a tag including the "omitempty" option is omitted
>   if the field value is empty. The empty values are false, 0, any
>   nil pointer or interface value, and any array, slice, map, or
>   string of length zero.

There is nothing that applies to array elements.  Why not just remove any 0's from your array before making the method call?

**Comment by naphatkrit** [comment]
then the struct spec is wrong. 0 is a valid value in this array (you can have CPU # 0)

**Comment by dougm** [comment]
I misunderstood, thought you wanted to omit 0's, but it is the opposite.  I'm surprised at Go's behavior in this case.

Since the fields of type `VirtualMachineAffinityInfo` already have the `omitempty` tag, I think we can just change the generator so `AffinitySet` does **not** have the `omitempty` tag.  What do you think?

```diff
modified   vim25/types/types.go
@@ -48188,7 +48188,7 @@ func init() {
 type VirtualMachineAffinityInfo struct {
 	DynamicData
 
-	AffinitySet []int32 `xml:"affinitySet,omitempty"`
+	AffinitySet []int32 `xml:"affinitySet"`
 }
 
 func init() {
```

**Comment by naphatkrit** [comment]
yep! that would work. might also want to be careful wherever else we have a similar array

**Comment by dougm** [comment]
I was tempted to remove `omitempty` for all slice fields, but leaving as just `AffinitySet` for now in PR #1010
