### ISSUE TITLE
Possible to use regex with govc command line

### ISSUE THREAD

**Issue by selvik** [vmware/govmomi#1009]
Hi All,

This is a request for help. Is it possible to use a regex in the command line such as this:

`govc vm.destroy -vm.dns=master.*`

Thanks.

**Comment by dougm** [comment]
The `vm.dns` flag uses the SearchIndex, which does not support wildcard matching:
http://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html

The `vm` flag and commands that take VM arguments use the `Finder` which does support matching:
https://github.com/vmware/govmomi/tree/master/govc#usage
https://godoc.org/github.com/vmware/govmomi/find
