### ISSUE TITLE
`no such VM` finding by UUID

### ISSUE THREAD

**Issue by johnjelinek** [vmware/govmomi#1020]
```
$ govc vm.info db

Name:           db
  Path:         /DC ONE/vm/packer-templates/db
  UUID:         420a16a5-dd7b-8507-b853-159c679ee137
  Guest name:   CentOS 4/5/6 (64-bit)
  Memory:       1024MB
  CPU:          1 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         DC.example.com
```

```
$ govc vm.info -vm.uuid=420a16a5-dd7b-8507-b853-159c679ee137

govc: no such VM
2018/01/28 19:30:06.831219 [ERR] (cli) unexpected exit from subprocess (1)
```

**Comment by johnjelinek** [comment]
ok, so I tried this with another datacenter and it was able to find by UUID. The difference between the datacenter that works and the one that doesn't is a whitespace in the Datacenter name (example `DC ONE`).

**Comment by johnjelinek** [comment]
well, guess it's not related to whitespace in the datacenter name:
```
GOVC_DATACENTER=CIN govc vm.info CINas
Name:           CINas
  Path:         /CIN/vm/packer-templates/CINas
  UUID:         420a77ae-8669-794c-8fae-d4a96d6c7a64
  Guest name:   CentOS 4/5/6 (64-bit)
  Memory:       2048MB
  CPU:          1 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         cinstrvs1.containerstore.com
```
```
GOVC_DATACENTER=CIN govc vm.info -vm.uuid=420a77ae-8669-794c-8fae-d4a96d6c7a64
govc: no such VM
```

**Comment by johnjelinek** [comment]
seems that this version of vCenter may be older than our others -- is there a compatibility issue with this functionality on older vCenters?

**Comment by den-is** [comment]
I'm experiencing same issue
running vSphere 5.5.0.6516310 and my dc has no whitespaces in its name:
```
govc vm.info template-centos-7.4
Name:           template-centos-7.4
  Path:         /mojo/vm/template-centos-7.4
  UUID:         422f44a7-008d-58c4-83b5-ede9f4b89265
  Guest name:   CentOS 4/5/6/7 (64-bit)
  Memory:       2048MB
  CPU:          2 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:   
  Host:         host1.mojo.com
```
```
govc vm.info -vm.uuid=422f44a7-008d-58c4-83b5-ede9f4b89265
govc: no such VM
```

**Comment by johnjelinek** [comment]
Note: I'm on `vCenter Server 5.5.0 | Build 1476327`

**Comment by dougm** [comment]
Sounds like a dup of #848 , which is specific to 5.5 and template VMs.  It includes a workaround:
```
% govc find / -type m -config.uuid 4204883e-484b-8f3c-c33d-126a997a5a4b | xargs govc vm.info
# or
% govc find / -type m -config.instanceUuid 4204883e-484b-8f3c-c33d-126a997a5a4b | xargs govc vm.info
```

**Comment by johnjelinek** [comment]
so, while this command workaround does work, the downstream `terraform-providers/terraform-provider-vsphere` client is using the part of `govmomi` that has this issue via the SearchIndex. Is there a recommended workaround for them to use?

**Comment by dougm** [comment]
It is possible to use ContainerView and RetrieveWithFilter method directly, for [example](https://github.com/vmware/govmomi/blob/master/examples/virtualmachines/main.go):

```diff
modified   examples/virtualmachines/main.go
@@ -23,10 +23,12 @@ package main
 
 import (
 	"context"
+	"flag"
 	"fmt"
 	"log"
 
 	"github.com/vmware/govmomi/examples"
+	"github.com/vmware/govmomi/property"
 	"github.com/vmware/govmomi/view"
 	"github.com/vmware/govmomi/vim25/mo"
 )
@@ -55,7 +57,7 @@ func main() {
 	// Retrieve summary property for all machines
 	// Reference: http://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/vim.VirtualMachine.html
 	var vms []mo.VirtualMachine
-	err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms)
+	err = v.RetrieveWithFilter(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms, property.Filter{"config.uuid": flag.Arg(0)})
 	if err != nil {
 		log.Fatal(err)
 	}
```

**Comment by johnjelinek** [comment]
That's a good idea! I'll pass it along so we can find out.

**Comment by johnjelinek** [comment]
So, to close out this issue -- should there be some documentation that when you're on 5.5, you should use the workaround to find by UUID in `govc` or should there be a fix to make the original command work just like the workaround when it's on 5.5?

**Comment by dougm** [comment]
I don't think we should change the `vm.uuid` flag to workaround the 5.5 limitation, since the `govc find` workaround works with all versions.  We can add some doc before the next govc release at least.

**Comment by johnjelinek** [comment]
@dougm: I'm not getting the output I expect from the workaround now:
```
$ govc find / -type m -config.uuid "420ae87a-bce6-2e1b-f6f6-fc813272ba24"

/DC0/vm/packer-templates/SCHas
/DC0/vm/Discovered virtual machine/avm
```
why is it returning two? The first one is the one I want. If I get details on the second one:
```
$ govc vm.info avm
Name:           avm
  Path:         /DC0/vm/Discovered virtual machine/avm
  UUID:
  Guest name:
  Memory:       0MB
  CPU:          0 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         DC0.example.com
Name:           avm
  Path:         /DC0/vm/avm
  UUID:         420a3f92-c904-04cf-38d1-b1bf886ab491
  Guest name:   Red Hat Enterprise Linux 5 (32-bit)
  Memory:       6144MB
  CPU:          2 vCPU(s)
  Power state:  poweredOn
  Boot time:    2017-01-03 21:16:45.323937 +0000 UTC
  IP address:   172.16.35.5
  Host:         DC0.example.com
```
Any ways to troubleshoot this?

**Comment by johnjelinek** [comment]
`govc find / -type m -config.instanceUuid 420ae87a-bce6-2e1b-f6f6-fc813272ba24` finds the one I'm looking for though.

**Comment by vancluever** [comment]
Hey @johnjelinek, can you tell me exactly how the two VMs were built?

I'm trying to track down an issue with Packer that may be able to explain a bit of this. Currently, with what I'm trying, using the `vmware-iso` builder in remote configuration along with the `vsphere-template` post-processor produces a template that lacks a UUID in vSphere inventory.

**Comment by johnjelinek** [comment]
So, I'm using the packer templates in the open source bento repo, except
I'm building them with a remote esx host and then shipping the templates
with `govc import.ovf`. Need any more details?

**Comment by johnjelinek** [comment]
The second VM was built manually from within ESX, mounting an ISO an
building from scratch on the host it ultimately lives.

**Comment by vancluever** [comment]
@johnjelinek basically I'm trying to reproduce a circumstance where the UUID would be duplicated, or a situation where the UUID would not necessarily be duplicated but `govc` using the UUID filter would match on both.

I'm kind of working off suspicions from this query:

```
$ govc find / -type m -config.uuid "420ae87a-bce6-2e1b-f6f6-fc813272ba24"

/DC0/vm/packer-templates/SCHas
/DC0/vm/Discovered virtual machine/avm
```
And kind of wondering how `/DC0/vm/Discovered virtual machine/avm` and `/DC0/vm/packer-templates/SCHas` were ultimately produced?

**Comment by johnjelinek** [comment]
Well, like I mentioned, SCHas is a template generated from packer and
shipped to the ESX host, and avm is not a template and was manually created
on the esx host. Each have different UUIDs as seen in the detailed view. If
you make the filter look for instanceUuid instead of config.uuid, it finds
exactly the right item.

**Comment by vancluever** [comment]
@johnjelinek can you confirm as mentioned [here](https://github.com/terraform-providers/terraform-provider-vsphere/issues/382#issuecomment-363476094) that the UUIDs on both of these are indeed the same?

Thanks!

**Comment by johnjelinek** [comment]
the UUIDs are definitely not the same.

**Comment by vancluever** [comment]
@dougm @johnjelinek confirmed in terraform-providers/terraform-provider-vsphere/#382 that the VM that's always showing up is an orphaned VM, possibly an artifact from the remote `vmware-iso` Packer builder.

Do you know how this affects searching at all and inventory? It seems to be coming up as a result for a filter using 3 different UUIDs.

This is obviously not optimal and AFAIK there is a TODO in Packer to get a proper vSphere API builder.

**Comment by robwiss** [comment]
> 
> 
> Hey @johnjelinek, can you tell me exactly how the two VMs were built?
> 
> I'm trying to track down an issue with Packer that may be able to explain a bit of this. Currently, with what I'm trying, using the `vmware-iso` builder in remote configuration along with the `vsphere-template` post-processor produces a template that lacks a UUID in vSphere inventory.

@vancluever Did this ever get resolved? I'm building with packer using `vmware-iso` w/ `"skip_export": true` , `"keep_registered": true"`, and the `vsphere-template` post-processor.

When I look in MOB, the resulting template has no uuid:
![mob_no_uuid](https://user-images.githubusercontent.com/495470/45382726-19c90280-b5d7-11e8-90ad-d5be5aedb799.png)

This results in terraform not being able to clone my template.
```
Error: Error refreshing state: 1 error(s) occurred:

* data.vsphere_virtual_machine.template: 1 error(s) occurred:

* data.vsphere_virtual_machine.template: data.vsphere_virtual_machine.template: virtual machine "/datacenter/vm/templates/
packer-template" does not have a UUID
```

**Comment by johnjelinek** [comment]
@robwiss: I can repro this where I'm using `vmware-iso`/`skip-export: true`/`keep_registered: true` and the `vsphere-template` post-processor. The template gets registered and I can make VMs from the template through vCenter, but govc shows no UUID:
```
> govc vm.info /DFW/vm/packer-templates/windows-2019-datacenter
Name:           windows-2019-datacenter
  Path:         /DFW/vm/packer-templates/windows-2019-datacenter
  UUID:
  Guest name:   Microsoft Windows Server 2016 (64-bit)
  Memory:       4096MB
  CPU:          2 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         vm.example.com
```
