### ISSUE TITLE
govc import Post EOF error

### ISSUE THREAD

**Issue by johnjelinek** [vmware/govmomi#1025]
I've been seeing this lately with `govc import.ovf`:

>Error: Post https://dc.example.com/nfc/5252e789-c91b-71f0-3071-e63f989c036a/disk-0.vmdk: EOF

And this happens at different stages of the upload. Any ideas what the issue is here, and whether the import can be resumed rather than restarted?

**Comment by dougm** [comment]
`govc logs` and or `govc tasks` may shed some light.  How much of the vmdk was uploaded?  I don't know of a way to resume the upload.

**Comment by dougm** [comment]
@johnjelinek still having this issue?

**Comment by johnjelinek** [comment]
Ya, it seems to occur when I am sending over a slow connection. It would be
really nice if I could resume the upload of a failed import.

**Comment by dougm** [comment]
Resume isn't an option, since the files are removed if the NFC lease expires or is canceled.
Is this still an issue for you?

**Comment by johnjelinek** [comment]
Yes, happens pretty regularly when transferring over a T1 connection.

**Comment by johnjelinek** [comment]
Yes, it happens pretty regularly over a saturated T1 connection.

**Comment by dougm** [comment]
@johnjelinek I've tried reproducing with no luck so far.  @fanzhangio has run into this recently too.  Can you share:

* Output of `govc logs -n 500 -host dc.example.com`  after the import fails.  Use whichever `-host` you see in the output message `Error: Post https://dc.example.com/nfc/5252e789-c91b-71f0-3071-e63f989c036a/disk-0.vmdk: EOF`

* vCenter/ESX version/build number
