### ISSUE TITLE
Add support for datacenter.PowerOnMultiVM

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#1026]
The 6.0 API doc notes that `PowerOnVM_Task` is deprecated against VC and `datacenter.PowerOnMultiVM_Task` should be used instead.

> When powering on a virtual machine in a cluster, the system might implicitly or due to the host argument, do an implicit relocation of the virtual machine to another host. Hence, errors related to this relocation can be thrown. If the cluster is a DRS cluster, DRS will be invoked if the virtual machine can be automatically placed by DRS (see DrsBehavior). Because this method does not return a DRS ClusterRecommendation, no vmotion nor host power operations will be done as part of a DRS-facilitated power on. To have DRS consider such operations use PowerOnMultiVM_Task. As of vSphere API 5.1, use of this method with vCenter Server is deprecated; use PowerOnMultiVM_Task instead.

http://pubs.vmware.com/vsphere-6-0/topic/com.vmware.wssdk.apiref.doc/vim.Datacenter.html#powerOnVm

This is one of those little gems of knowledge that it's easy to miss or be unaware of. I would prefer if we can find a way to encapsulate calling the appropriate power operation within the `object.VirtualMachine.PowerOn()` implementation if at all viable. This would prefer all callers having to implement the same ESX/VC switch logic the the requisite call.

**Comment by dougm** [comment]
PR: vmware/govmomi#1031

**Comment by dougm** [comment]
Closed via #1031
