### ISSUE TITLE
Windows simulator build is broken.

### ISSUE THREAD

**Issue by rmmh** [vmware/govmomi#1028]
There's currently a compile error since _unix.go isn't a build flag that gets skipped on Windows:

```
$ GOOS=windows go build github.com/vmware/govmomi/simulator
# github.com/vmware/govmomi/simulator
simulator/os_unix.go:23:11: undefined: syscall.Statfs_t
simulator/os_unix.go:25:9: undefined: syscall.Statfs
simulator/os_windows.go:21:6: (*Datastore).stat redeclared in this block
	previous declaration at simulator/os_unix.go:21:6
```

**Comment by dougm** [comment]
I thought the `_unix.go` suffix was already ignored on windows, but now see it is just a convention.  We should also have CI build vcsim with `GOOS=windows` so we can avoid this breakage in the future.
