### ISSUE TITLE
Clone VM example

### ISSUE THREAD

**Issue by alexellis** [vmware/govmomi#1030]
Hi @dougm I've just found this library - it looks really useful as an alternative to the Python version 👍 

@kars7e showed me an example to clone a VM from a template using the Python version. Do you have an example like this for Go or could you put one together?

I'd like to use it to make a function for [OpenFaaS](https://github.com/openfaas) or [Dispatch](https://github.com/vmware/dispatch/) to clone VMs like this: https://github.com/vmware/dispatch/blob/master/examples/python3/clonevm.py

Thanks,

Alex

**Comment by dougm** [comment]
@alexellis yes, there is a simple example here: https://gist.github.com/dougm/c8c14dc029ec831d072e5def093ca92c/b66341e171576e3a359445303403068821979529

The govc command includes more options, such as storage cluster placement, linked clones, etc:
https://github.com/vmware/govmomi/blob/master/govc/vm/clone.go

**Comment by alexellis** [comment]
That looks great - thanks for the example @dougm

Do you also have the ability to do auth here?

**Comment by dougm** [comment]
@alexellis yes, `examples.NewClient` calls `govmomi.NewClient` underneath: 

https://github.com/vmware/govmomi/blob/81743157fb5ccf548d6bd5088c25ee6156a359ee/examples/examples.go#L114-L115

You can call `govmomi.NewClient` directly and it'll call `Login()` if the URL includes username+password:

https://github.com/vmware/govmomi/blob/81743157fb5ccf548d6bd5088c25ee6156a359ee/client.go#L91-L93

If the URL doesn't include credentials, you can just call `Login()` directly after `NewClient`.

**Comment by dougm** [comment]
@alexellis anything else needed to close out this issue?
