### ISSUE TITLE
govc: POST request - Service Unavailable

### ISSUE THREAD

**Issue by brunograz** [vmware/govmomi#1045]
Hi,

I'm just getting started with govc and at the moment I'm facing an issue which is blocking me to execute any command with it. Doesn't matter which command I use, govc always returns `Service Unavailable`.
I tried using the debug mode but that didn't give me any indicators of what could be the issue.

We are using VCenter v6.0 and below is the content the debug files - I enabled _debug, dump_ and _json_ flags:

**1-0001.req.headers:**
`POST /sdk HTTP/1.1
Host: REDACTED
Content-Type: text/xml; charset="utf-8"
Soapaction: urn:vim25/6.5
User-Agent: govc/0.16.0`

**1-001.req.xml:**
_[EMPTY]_

**1-client.log:**
`2018-02-21T17-13-15.992932314 - 0001:  60923ms (*methods.RetrieveServiceContentBody)`

Message returned:
`govc: Post https://REDACTED/sdk: Service Unavailable`

Is there any way I could get more information about the request govc is sending? 
For sake of completeness I'm able to reach vcenter on port 443.

**Comment by dougm** [comment]
Any proxy involved?  Can you post the output of:
```
% curl --verbose -k -X POST https://x.x.x.x/sdk
```

**Comment by brunograz** [comment]
Yep, there is:

> Hostname was NOT found in DNS cache
>     Trying PROXY_IP...
> Connected to PROXY_IP (PROXY_IP) port 8080 (#0)
> Establish HTTP proxy tunnel to REDACTED:443
> CONNECT REDACTED:443 HTTP/1.1
> Host: REDACTED:443
> User-Agent: curl/7.35.0
> Proxy-Connection: Keep-Alive

> HTTP/1.0 503 Service Unavailable
> Server: squid/2.6.STABLE21
> Date: Fri, 23 Feb 2018 08:21:27 GMT
> Content-Type: text/html
> Content-Length: 1061
> Expires: Fri, 23 Feb 2018 08:21:27 GMT
> X-Squid-Error: ERR_CONNECT_FAIL 110

> Received HTTP code 503 from proxy after CONNECT
> Connection #0 to host PROXY_IP left intact
> curl: (56) Received HTTP code 503 from proxy after CONNECT

**Comment by brunograz** [comment]
@dougm thanks for the pointer! after checking our proxy settings and env I was able to connect to vcenter using govc.
