### ISSUE TITLE
VUM operations using api?

### ISSUE THREAD

**Issue by alexbozhenko** [vmware/govmomi#1049]
Does govmomi support any VUM operations?
I was not able to find any VUM methods. Is it because VMWare doesn't expose those APIs?

**Comment by dougm** [comment]
Any doc pointers? I don't know if VUM is part of the vmodl or something separate.

**Comment by alexbozhenko** [comment]
Well, all that I was able to find is:
https://www.vmware.com/support/developer/ps-libs/vumps/
https://www.vmware.com/support/pubs/vum_pubs.html

**Comment by jonathanpittman** [comment]
I am looking for this as well. I can automate a good bit of a process I need to go through to gracefully close up the work that my VMs are doing and then shutdown the guest OS. However, the remediation process for the esx host involves going through the vSphere UI. I would like to do this from govc and the govmomi API to better automate it.

**Comment by dougm** [comment]
From what I've heard the VUM API will not be public and the new Lifecycle Manager in 7.0 is meant to replace VUM: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere-lifecycle-manager.doc/GUID-74295A37-E8BB-4EB9-BFBA-47B78F0C570D.html

I don't know the details of how it works, but closing this issue as we aren't able publish VUM bindings.
