### ISSUE TITLE
Documentation for govc find is missing details on where to get possible KEY VAL pairs

### ISSUE THREAD

**Issue by alexbozhenko** [vmware/govmomi#1050]
Hello.

I am trying to list all hosts that are in maintenance mode.
I guess I need something like:
`govc find  . -type h -SOME.KEY False
`
But it is not clear from [find docs](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#find) where I can get that key from.

When I am executing
`govc host.info -json=true host.company.com  2>&1 | python -m json.tool | less`
I do not see numCpuCores there which is used as example key for host find command.

Could somebody please point me to the right direction?

**Comment by alexbozhenko** [comment]
UPD: oops, looks like that was a case issue.

```
govc host.info -json=true host.company.com  | jq -r 'paths | map(.|tostring)|join(".")' |  grep  -i -e numCpuCores  -e Maintena
HostSystems.0.Runtime.InMaintenanceMode
HostSystems.0.Summary.Hardware.NumCpuCores
HostSystems.0.Summary.Runtime.InMaintenanceMode
HostSystems.0.Hardware.CpuInfo.NumCpuCores
HostSystems.0.Capability.MaintenanceModeSupported
```

So my question now: why it is required to lowercase first letter in each key level to make it work?
```
$ govc find . -type h -Hardware.CpuInfo.NumCpuCores 20
govc: ServerFaultCode: InvalidProperty

$govc find . -type h -hardware.cpuInfo.numCpuCores 20
... long list...
```
or 
```
$ govc find . -type h -Runtime.InMaintenanceMode true                                                                                
govc: ServerFaultCode: InvalidProperty
$ govc find . -type h -runtime.inMaintenanceMode true
... list of hosts...

```
$ govc version
govc 0.16.0
```
```

**Comment by dougm** [comment]
You can use `govc object.collect` to view the valid property paths for an object.  We should include that in the find docs.  The property collector on the VC/ESX side is case sensitive, not much we can do about that.
```console
% host=$(govc find / -type h | head -n 1)
% govc object.collect $host | awk '{print $1}'
availableField
capability
config
configIssue
configManager
configStatus
customValue
datastore
datastoreBrowser
declaredAlarmState
disabledMethod
effectiveRole
hardware
licensableResource
name
network
overallStatus
parent
permission
recentTask
runtime
summary
systemResources
tag
triggeredAlarmState
value
vm
% govc object.collect $host | awk '{print $1}' config
config.host                       types.ManagedObjectReference                HostSystem:ha-host
config.product                    types.AboutInfo                             ...
config.deploymentInfo             *types.HostDeploymentInfo                   ...
config.hyperThread                *types.HostHyperThreadScheduleInfo          ...
config.consoleReservation         *types.ServiceConsoleReservationInfo        
...
```
Also see the property section for managed objects: http://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.wssdk.apiref.doc/vim.HostSystem.html

**Comment by alexbozhenko** [comment]
Ok, thank for the explanation. I have two questions remaining:
1. So see all possible values using object.collect I need to iterate myself? May be it should show all nested levels automatically?
2. Why does host.find returns json where all path have uppercase letter in the beginning of words, but 'property collector' accepts only lowercase first letters?
So for now I generate all possible paths using:
```
host=$(govc find / -type h | head -n 1)
govc  host.info -json=true $host |  jq -r 'paths | map(.|tostring)|join(".")'  | sed -e "s/\b\(.\)/\L\1/g"
```

**Comment by dougm** [comment]
We could add a way to list all possible property paths.  The current interaction is similar to the [MOB](http://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.wssdk.pg.doc%2FPG_Appx_Using_MOB.20.2.html)

The *.info commands output the Go version of managed objects.  The field names in Go start with upper case so they are [exported](https://golang.org/ref/spec#Exported_identifiers).
But the commands use property paths with lower case to query the properties, for example: https://github.com/vmware/govmomi/blob/58d927a6c3241af7f51cff7915920a616b7af3ee/govc/datacenter/info.go#L97-L104

The object.collect command uses the property collector directly, without the Go version of managed objects.  So the input+output are the same case used by the property collector.

**Comment by dougm** [comment]
Doc was added in 1d63da8
