### ISSUE TITLE
Just curious on why govmomi doesn't encapsulate RPC call on MO.

### ISSUE THREAD

**Issue by julykobe** [vmware/govmomi#1051]
Hi,  I have used pyvmomi before, the rpc encapsulation on MO is very convenient. But I found that govmomi doesn't do that, I'm curious why?

**Comment by dougm** [comment]
Are you referring to method calls or property collection?  Maybe some examples that compare the two and how you'd expect the Go version to look?

**Comment by julykobe** [comment]
Say I have a local vmMO, which maps to real MO exists in VC or ESXi Host, each method or property on local vmMO(vmMO.config or vmMO.Destroy()) will cause a RPC call to remote real MO, and will invoke method or retrieve property then return to local vmMO.

ps: Seems you have some encapsulation in govmomi/object/* , but I think it's more efficient to do RPC calls than encapsulate all methods on MOs by hands for you. You can try pyVmomi to make a comparison.
