### ISSUE TITLE
vSAN management API support

### ISSUE THREAD

**Issue by dougm** [vmware/govmomi#1054]
The vSAN management API has its own URL endpoint and vmodl extension.  To access via govmomi, we'll need to generate the managed objects, types and methods similar to the [pbm package](https://github.com/vmware/govmomi/tree/master/pbm) that was added in PR #711

The structure should be similar to that of the pbm package:
```
vsan/client.go
vsan/types/
vsan/methods/
vsan/mo/
```
Unlike the PBM vmodl, the vSAN management vmodl includes the entire vim25 vmodl, so we can't use the existing [code generator](https://github.com/vmware/govmomi/blob/master/gen) as we did with PBM.

**Comment by pnhowe** [comment]
When is vSAN support expected to be added?  I have a monitoring project that could really use this.

**Comment by dougm** [comment]
@shuklanirdesh82 is currently looking into this.

**Comment by pnhowe** [comment]
here is a basic python snippet of the direction I'm trying to go.

`from pyVim.connect import SmartConnect, Disconnect
from pyVmomi import vim, SoapStubAdapter
import vsanmgmtObjects
import ssl
import sys

VSAN_API_VC_SERVICE_ENDPOINT = '/vsanHealth'
VSAN_API_ESXI_SERVICE_ENDPOINT = '/vsan'
VERSION = 'vim.version.version10'

hostname = 'XXXXXX'
user = 'XXXXXX'
password = 'XXXXXX'

context = ssl._create_unverified_context()
si = SmartConnect(host=hostname, user=user, pwd=password, port=443, sslContext=context)

content = si.RetrieveContent()

aboutInfo = content.about

if aboutInfo.apiType == 'VirtualCenter':
  majorApiVersion = aboutInfo.apiVersion.split('.')[0]
  if int(majorApiVersion) < 6:
     print('The Virtual Center with version {0} (lower than 6.0) is not supported.'.format(aboutInfo.apiVersion))
     sys.exit(1)

  vsanStub = SoapStubAdapter(host=hostname, path=VSAN_API_VC_SERVICE_ENDPOINT, version=VERSION, sslContext=context)
  vsanStub.cookie = si._stub.cookie
  
  vpm = vim.cluster.VsanPerformanceManager( 'vsan-performance-manager', vsanStub )
  vhs = vim.cluster.VsanVcClusterHealthSystem( 'vsan-cluster-health-system', vsanStub )

else:
  majorApiVersion = aboutInfo.apiVersion.split('.')[0]
  if int(majorApiVersion) < 6:
     print('The ESXi with version {0} (lower than 6.0) is not supported.', aboutInfo.apiVersion)
     sys.exit(1)

  vsanStub = SoapStubAdapter(host=hostname, path=VSAN_API_ESXI_SERVICE_ENDPOINT, version=VERSION, sslContext=context)
  vsanStub.cookie = si._stub.cookie

  epm = vim.cluster.VsanPerformanceManager( 'vsan-performance-manager', vsanStub )
  ehs = vim.host.VsanHealthSystem( 'ha-vsan-health-system', vsanStub )

print( vhs.QueryClusterHealthSummary(cluster=cluster,includeObjUuids=True, fetchFromCache=True,fields=['overallHealth','clusterStatus']) )

Disconnect(si)`

**Comment by dougm** [comment]
Note that 'mo' types aren't need for vSAN management API as the objects do not have any properties.  The managed object reference can be used directly when invoking methods, for example :

https://github.com/vmware/govmomi/blob/1f0870fcda76974a214b4dd7df54df00d0ba0713/pbm/client.go#L56

**Comment by dougm** [comment]
The existing pbm client can be used as a template for the vsanhealth client.  The `Namespace`, `Path`, `ServiceInstance` vars and `RetrieveServiceContent` method call will need to be replaced with the appropriate values for vsanhealth:

https://github.com/vmware/govmomi/blob/ae91c0ee0a326f320a5458d206fc751f319e1cf9/pbm/client.go#L30-L61

**Comment by Arderos** [comment]
Hey, guys!
Any news on vSAN support?

**Comment by dougm** [comment]
Subset of vSAN types and methods added in #1450

**Comment by gH05tn0Va** [comment]
Do we have full vSAN API support now?
I was hoping to use methods in VsanObjectSystem (VosQueryVsanObjectInformation, VosSetVsanObjectPolicy), etc.

**Comment by bill-rich** [comment]
Hi @dougm! We're looking to add vSAN support on the Terraform provider, so I am planning on doing some work on doing some work on the govmomi side. I wanted to double check first that there isn't any work currently being done on this? I saw a while back you mentioned @shuklanirdesh82 was looking into it.

**Comment by dougm** [comment]
Hey @bill-rich !  Which APIs are you looking to use?
@gh05tn0va @divyenpatel @BaluDontu should be able to provide pointers here.

**Comment by bill-rich** [comment]
Thanks @dougm! 

I believe I'm mainly looking to work with `HostVsanSystem`, `VimClusterVsanVcDiskManagementSystem`, and `VsanVcClusterConfigSystem`. The goal is to be able to enable vSAN on a cluster, set properties, and add disks. I'm not super familiar with the latest implementation of vSAN though (especially via the API), so I may be missing some pieces.

**Comment by dougm** [comment]
Generated types and client wrapper is available: https://github.com/vmware/govmomi/tree/master/vsan

@bill-rich this includes the three types you mentioned.
