### ISSUE TITLE
How to extend the vcsim

### ISSUE THREAD

**Issue by dandunckelman** [vmware/govmomi#1068]
# Summary
I'm trying to use the VCSIM to perform unit testing in a python project using pyvmomi and need help with the workflow to extend the VCSIM.

# Notes
- I'm a total go noob, but I want to add the acquireticket method to the vcsim.
- This looks helpful:  [simulator/example_extend_test.go#L51](https://github.com/vmware/govmomi/blob/master/simulator/example_extend_test.go#L51)
- But I just quite understand what the workflow would be for me to add that so I can use the vcsim to test the AcquireTicket method on a VM.

**Comment by dougm** [comment]
The example is meant for changing existing vcsim behavior, such as fault injection or a workaround for unsupported methods.  The example can be dropped into Go tests, but to use from Python would require a separate binary to be compiled that is similar to vcsim.
However, we are happy to add support for methods that are generally useful for testing.
Can you share more detail on how you'd use `AcquireTicket` in your testing?

**Comment by dandunckelman** [comment]
@dougm right, I was planning on building my own vcsim binary; that's the workflow where I'm looking for help.  I have some thoughts on how to do it, which I intend to try soon, but I was hoping to get some direction from an "expert".

Here's my spec file:

```
from tests.test_helper import TestHelper                  
from tests.factories.vcenter_factory import VCenterFactory
import pytest                                             
from vmware.vcenter import VCenter                        
from pyVmomi import vim                                   
                                                          
my_vcr     = TestHelper.vcr()                             
vcenter    = TestHelper.vcenter()                         
vc_factory = VCenterFactory(vcenter)                      
                                                          
@pytest.fixture                                           
def powered_off_vm():                                     
    return vc_factory.vm(powered_on = False)              
                                                          
@pytest.fixture                                           
def powered_on_vm():                                      
    return vc_factory.vm(powered_on = True)               
                                                          
@my_vcr.use_cassette()                                    
def test_vm_console_ticket_powered_off():                 
    vm = powered_off_vm()                                 
    ticket = vcenter.vm_console_ticket(vm.name)           
    assert ticket == None                                 
                                                          
@my_vcr.use_cassette()                                    
def test_vm_console_ticket_powered_on():                  
    vm = powered_on_vm()                                  
    ticket = vcenter.vm_console_ticket(vm.name)           
    assert ticket.ticket != None                          
    assert ticket.host   != None                          
```

So, as you can see, it's a basic unit test to ensure that we get a ticket from a "ready" VM.

In fact, our code needs more changes because we found that imply looking at the VM's poweron state isn't sufficient to declare that a VM is "ready" for us to fetch a console ticket.

**Comment by dougm** [comment]
Sounds like this could be a built-in we add to the simulator/virtual_machine.go methods, what do you think?

We should also make it easier to extend vcsim/main, I have a few change in mind, will try to open a PR soon.

**Comment by dougm** [comment]
Sure, you can follow these steps: https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md#getting-started

After changing `$GOPATH/src/github.com/vmware/govmomi/simulator/virtual_machine.go`, you can update the `$GOPATH/bin/vcsim` binary with: 

```go install -v github.com/vmware/govmomi/vcsim```

**Comment by dandunckelman** [comment]
Adding for my own notes:
- I just found that the vcsim also doesn't have the `ResetVM_Task` and `SuspendVM_Task` methods on `VirtualMachine`.

**Comment by jumisz** [comment]
I need to write tests that cover `ResetVM_Task` and `RebootGuest`. @dougm what is your recommendation?

**Comment by dougm** [comment]
@jumisz can you review #1187 ?

@dandunckelman are you still needing AcquireTicket support?  We can add that too, will just need to choose a different method for the extending example.

**Comment by dandunckelman** [comment]
> are you still needing AcquireTicket support?

@dougm I don't.  I've moved to using a "lab" VMware environment for automated testing.  I also needed to test NSX, so doing that made it much better.

Thanks anyway.

**Comment by dougm** [comment]
ok closing for now, we can revisit AcquireTicket support if others need it.
