### ISSUE TITLE
When creating a new VM with govc it is not possible to specify "EFI" instead of "BIOS" boot

### ISSUE THREAD

**Issue by omarkohl** [vmware/govmomi#1071]
In the VMWare GUI there is the option "Boot with EFI instead of BIOS".

I was unable to achieve the same thing using **govc**. Neither with `govc vm.create` nor with `govc device.boot` .

Did I miss the option? Otherwise I think it should really be implemented. If you give me some pointer on where/how to do it I will even try myself.

**Comment by omarkohl** [comment]
As a workaround I was able to do this as follows:

```diff
diff --git a/govc/vm/create.go b/govc/vm/create.go
index eceefa5..c5d184b 100644
--- a/govc/vm/create.go
+++ b/govc/vm/create.go
@@ -296,6 +296,7 @@ func (cmd *create) createVM(ctx context.Context) (*object.Task, error) {
         NumCPUs:    int32(cmd.cpus),
         MemoryMB:   int64(cmd.memory),
         Annotation: cmd.annotation,
+        Firmware:   "efi",
     }
 
     devices, err = cmd.addStorage(nil)
```

**Comment by dougm** [comment]
@omarkohl do you want to open a PR to add this feature?  A new `-firmware` flag would be fine to add.

**Comment by omarkohl** [comment]
Yes I'm working on it. I added a `-firmware-efi` boolean flag. Do you think a string parameter with options `efi` or `bios` is better?
