### ISSUE TITLE
property_collector is trying to converts long[] into ArrayOfint64

### ISSUE THREAD

**Issue by MaximGrise** [vmware/govmomi#1077]
If an object containing arrays of longs or shorts (such as VirtualMachineConfigInfo) is fetched in a getProperties query, the property_collector will try to build an ArrayOfint64 instead of an ArrayOfLong.

**Comment by dougm** [comment]
@MaximGrise linked PR should fix this, can you confirm?

**Comment by MaximGrise** [comment]
Yes, confirmed as fixed.
