### ISSUE TITLE
RDM Type of Disk 

### ISSUE THREAD

**Issue by surajsub** [vmware/govmomi#1079]
Is there support for adding RDM disk ?

**Comment by dougm** [comment]
Yes: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmrdmattach

**Comment by surajsub** [comment]
Thanks @dougm for the response . I was not clear with my question , so apologies.
What i want to do is - Create a RDM disk via TF ( i know there is no support yet) and then have the capability to attach this to one or two vm's to support a shared disk scenario for SAP setup. My understanding is that , the govmomi library first needs to support it and then we can work around the tf provider aspect of it.  Is that possible ?

**Comment by dougm** [comment]
Yes, the APIs are supported, see the vm.rdm sources for examples: https://github.com/vmware/govmomi/tree/master/govc/vm/rdm
