### ISSUE TITLE
Help with creating a VM from a template and attaching an iso image to the VM created

### ISSUE THREAD

**Issue by micruzz82** [vmware/govmomi#1083]
Hi All

I needed some help creating a VM from an existing template.

The template name is called VM-base-template, the cluster name is called TEST-CLUSTER_ESXI, the esxi host in this is esxi001 the datastore is VMFS001.

The iso is stored in folder VMFS001/ISO-Images.

I'm new to govc and was not able to understand the format from the usage example.

Usage: govc vm.clone [OPTIONS] NAME

Clone VM to NAME.

Examples:
  govc vm.clone -vm template-vm new-vm

I'm using the following but this obviously is not correct.

govc vm.clone -vm VM-base-template NEW-VM -host=TEST-CLUSTER_ESXI -ds=VMFS001 -folder=FW-01

Can you please advise me how to create a VM from the template.. and also how can I attach the iso image to the VM before power off.

Your help is much appreciated.

**Comment by dougm** [comment]
The `[OPTIONS] NAME` order matters, all options need to specified before the NAME:

```govc vm.clone -vm VM-base-template -host=TEST-CLUSTER_ESXI -ds=VMFS001 -folder=FW-01  NEW-VM```

For cdrom, see:

https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#devicecdrominsert

**Comment by micruzz82** [comment]
@dougm thank you for your response. It works perfectly now and I'm able to add the relevant code to build the VM.
Much appreciated on this useful toolkit.

**Comment by dougm** [comment]
@micruzz82 good to hear it's working well for you.

**Comment by micruzz82** [comment]
@dougm thanks again.. just one more question if I may.. currently I have only 1 host esxi001 on the cluster TEST-CLUSTER_ESXI

when i ran -host=TEST-CLUSTER_ESXI it did not work.. but when i ran -host=esxi001 it ran correctly. 

I'm assuming in this case that -host is the actual host machine that it is looking for and not the Cluster name.. in the production environment it would be better to just reference the cluster so it can spread the VM's across the hosts. Is this expected?

**Comment by dougm** [comment]
To specify a cluster you can use: `-pool=TEST-CLUSTER_ESXI/Resources`
`-pool=TEST-CLUSTER_ESXI` may also work as a short cut, or we could make it work, but it would just expand to the cluster's root ResourcePool as it is above.

**Comment by dougm** [comment]
Added `needs-doc` tag, we should add `-host` and `-pool` to the `Examples:` section https://github.com/vmware/govmomi/blob/1f0870fcda76974a214b4dd7df54df00d0ba0713/govc/vm/clone.go#L117-L122

**Comment by micruzz82** [comment]
thanks @dougm it's worked with using -pool=TEST-CLUSTER_ESXI/Resources and did not work without the/Resources with the error  {resource pool 'TEST-CLUSTER_ESXI' not found} Much appreciated again for the help.
