### ISSUE TITLE
Release tagged as 0.17.1 declares const Version = "0.17.2-dev"

### ISSUE THREAD

**Issue by kremers** [vmware/govmomi#1085]
https://github.com/vmware/govmomi/blob/123ed177021588bac57b5c87c1a84270ddf2eca8/govc/flags/version.go#L24

Since release URI and 'govc version' are not in sync, scripts using this information to update to a certain release fail.

**Comment by dougm** [comment]
I'd say we could create a 0.17.2 release to fix this, but there's a bunch of new stuff in master towards .18 now.  @kremers can you stick with 0.17 for now, or workaround?  Otherwise, I suppose we could release from a branch that doesn't include the new stuff until .18 is ready.

**Comment by kremers** [comment]
Since my script is re-downloading and reinstalling if the version does not match, I can live with it for now.

**Comment by dougm** [comment]
Fixed in the 0.18 release.
