### ISSUE TITLE
Does govmomi(govc) support case Insensitive Search For Vm By Name?

### ISSUE THREAD

**Issue by junkao** [vmware/govmomi#1099]
Does govc support case Insensitive Search For Vm By Name?

**Comment by tthayer** [comment]
The `govc ls -h` command shows an example that involves piping to other unix tools. I'd suggest using something like `govc ls "/DC1/vm/*" | grep -i myvmname`.

**Comment by junkao** [comment]
Yes, it looks ok.  

API calls use govmomi to find vm ,the same problem is case-insensitive

         filter := property.Filter{}
	m := view.NewManager(advancedSearch.Client.Client)
	v, err := m.CreateContainerView(ctx, advancedSearch.ServiceContent.RootFolder, []string{"VirtualMachine"}, true)
	objs, err := v.Find(ctx, []string{"VirtualMachine"}, filter)

**Comment by dougm** [comment]
We use `path.Match` (https://golang.org/pkg/path/#Match), so you can use for example:
`*vm[nN]ame*`.  But we could also add an option for case-insensitive matching.

**Comment by junkao** [comment]
Thank
According to your hint I wrote a piece of code.   the code is not very good, but work for me .


tmpStr := ""
		for _, item := range advancedSearchGet.Name {
			switch {
			case unicode.IsUpper(item):
				tmpStr = tmpStr + "[" + string(item) + strings.ToLower(string(item)) + "]"
			case unicode.IsUpper(item):
				tmpStr = tmpStr + "[" + strings.ToUpper(string(item)) + string(item) + "]"
			default:
				tmpStr = tmpStr + string(item)
			}
		}
		log.Println(tmpStr)
		filter["name"] = "*" + tmpStr + "*"

**Comment by dougm** [comment]
Closing as there are a few options provided here.
