### ISSUE TITLE
sharingMultiWriter flag

### ISSUE THREAD

**Issue by dzegelman** [vmware/govmomi#1102]
Hi all,

Is that any chance that possibility to put sharingMultiWriter on disk will be added, to avoid manipulation of of .vmx files.

Thanks a lot in advance,

Dan Zegelman

**Comment by dougm** [comment]
I assume this would be setting the `VirtualDisk.FlatVer2BackingInfo.sharing` property in the govc `vm.disk` commands?

Reference: http://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.device.VirtualDisk.FlatVer2BackingInfo.html

**Comment by dzegelman** [comment]
Yes it is. Thanks a lot

**Comment by dzegelman** [comment]
Hi all,

Will this enhancement be implemented in the future?

Thanks a lot in advance,

Dan Zegelman

**Comment by dougm** [comment]
For reference: https://kb.vmware.com/s/article/1034165
