### ISSUE TITLE
Add govmomi support for namespaceDB

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#1123]
**Story**
As a user of govmomi I want to be able to perform VM Namespace operations

**Detail**
VM Namespace Manager is found here: ServiceContext->retrieveInternalContent->vm-namespace-manager
Core operations:
* create namespace
* updateData
* retrieveData

Toolbox:
- [ ] support at least the create namespace, and get/set/list keys

vSphere:
- [ ] prevent namespacedb data from being deleted when reverting to a snapshot.

This mirrors vmware/vic#4065 and is being opened to help support the Kubernetes virtual-kubelet work.

**Comment by dougm** [comment]
@hickeng could you add some detail on the advantages of using namespaceDB instead of guestinfo?

**Comment by hickeng** [comment]
@dougm 
1. explicit ability to make a namespace read-only to the guest (instead of key containing `/` character) and conversely make keys read-only to the API (not supported in guest info).
2. setting keys via the API for a powered on VM isn't volatile in any of our (vmware/vic) supported vSphere releases so can be used consistently - which allows us to remove a lot of special case code to prevent accidental overwrite.
3. dynamic ability to create namespaces which can be used for session logging, so a possible replacement for file backed serial ports - something of this type is a requirement to properly support the podVM for virtual-kubelet
4. supports events (both API originated and guest originated) so allows a much simpler model for triggering in guest updates (currently uses fake guest processes) and for waiting on guest events via the API (currently uses properly collector to wait on extraconfig updates).
