### ISSUE TITLE
govc missing info command on some objects

### ISSUE THREAD

**Issue by benjamin-bergia** [vmware/govmomi#1134]
Would it be possible to add the equivalent of the `vm.info` command to cluster, dvs, guest, role, and snapshot?

Being able to retrieve a whole item or list of items in json with the '-json' option is really a huge plus for me.

**Comment by dougm** [comment]
Have you looked at the `object.collect` command?  Some examples..
Cluster:
``` console
% govc find / -type c | xargs -n1 govc object.collect -json | jq .
```
DVS:
``` console
% govc find / -type w | xargs -n1 govc object.collect -json | jq .
```
Guest:
``` console
% govc find / -type m | xargs -I % govc object.collect % guest
```
Snapshot:
``` console
% govc find / -type m | xargs -I % govc object.collect -json % snapshot.rootSnapshotList | jq .
```
The `snapshot.tree` command provides some of that info too.

For roles there is the `roles.ls` and `permissions.ls` commands, and for example:
``` console
% govc object.collect -s -json AuthorizationManager:AuthorizationManager roleList | jq .
```

**Comment by benjamin-bergia** [comment]
@dougm I am currently using the `object.collect' to get the list of networks available. You are right, information are available elsewhere, i just thought that the current `vm.info` does a very good job at returning neatly formatted data. The `object.collect` is still tricky from time to time.

I understand that since most of the information are available with `object.collect` it might not be a priority at the moment but, in the future, it would be a very nice improvement to get more `info` commands.

**Comment by dougm** [comment]
@benjamin-bergia sure, open to adding new info commands.  If you could add more detail on what info would be most useful, examples of input / output, etc., would be great.

**Comment by benjamin-bergia** [comment]
Sorry @dougm, I am still checking how my code looks like with `info` and `object.collect`. I will need a bit more time to come up with more info on this.

**Comment by dougm** [comment]
@benjamin-bergia no problem, take your time.

**Comment by benjamin-bergia** [comment]
@dougm  I spent more time on `find` and `object.collect` and in my case it make more sense that requesting new `info` commands. Sorry about that, I will close this issue.

**Comment by dougm** [comment]
No problem, glad object.collect does what you need.  Feel free to propose new info commands in the future.
