### ISSUE TITLE
Add vCenter Service Control

### ISSUE THREAD

**Issue by pdaigle** [vmware/govmomi#1138]
### Story ####
As a `govmomi` user, I want to be able to control vCenter services such as the `vsphere-ui` and `vsphere-client` services.

### Details ###
The vSphere REST API exposes service control:

[https://vdc-repo.vmware.com/vmwb-repository/dcr-public/423e512d-dda1-496f-9de3-851c28ca0814/0e3f6e0d-8d05-4f0c-887b-3d75d981bae5/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/index.html#PKG_com.vmware.appliance.vmon](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/423e512d-dda1-496f-9de3-851c28ca0814/0e3f6e0d-8d05-4f0c-887b-3d75d981bae5/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/index.html#PKG_com.vmware.appliance.vmon)

This is being opened in support of [https://github.com/vmware/vic-product/issues/1432](https://github.com/vmware/vic-product/issues/1432)

**Comment by ZackaryWelch** [comment]
I'm interested in this too. Is this covered by another library?

**Comment by embano1** [comment]
govmomi has support for the VAPI endpoints. Which REST APIs in particular are you interested in?

**Comment by ZackaryWelch** [comment]
APIs under /api/vcenter/services. I didn't see any mention of the services APIs when looking at vapi source.
