### ISSUE TITLE
Client bindings for the tagging API

### ISSUE THREAD

**Issue by dougm** [vmware/govmomi#1139]
The tagging API is only available via the REST API, it is not available via the SOAP API.  Documentation on the tagging API is available here:

https://www.vmware.com/support/developer/vapi/index.html

https://code.vmware.com/apis/191/vsphere-automation

A sample Go implementation is available in the VIC project: https://github.com/vmware/vic/tree/master/pkg/vsphere/tags

Required for #957 and kubernetes/kubernetes#64021

We need to consider:

* Type structures can be generated from the API swagger spec, but we can also just create the types manually as the VIC package has.

* Integration with govmomi client should be possible to reuse its security features and authentication options

* Simulator implementation for testing

**Comment by jiatongw** [comment]
- [x] Do research on vSphere REST APIs, especially the tagging APIs, and test through terminal cmd
- [x] Refer the Go implementation in the VIC project
- [ ] Auto Login
- [ ] Integrate the rest of categories related APIs into govc
- [ ] Integrate tags related APIs into govc
- [ ] Integrate tags assigning related APIs into govc

**Comment by jiatongw** [comment]
Have done 3 of the categories related APIs into govc (create, list, get), the rest of them will be available soon. 
Doing: 1.Auto login. 2. The rest of categories related APIs

**Comment by jiatongw** [comment]
Waiting categories related APIs to be merged.
Doing: integrate tags related APIs

**Comment by jiatongw** [comment]
we can consider close this issue after the PR is merged? @dougm

**Comment by dougm** [comment]
@jiatongw we still need to add tests and simulator support, but we can create new issues to track those efforts.

**Comment by dougm** [comment]
Issue #1180 tracks the remaining work.
