### ISSUE TITLE
Download format changed from gz to tgz

### ISSUE THREAD

**Issue by angystardust** [vmware/govmomi#1143]
This morning i was upgrading govc to 0.18 using my ansible-playbook but it broke badly 'cause the download format on the release page is now .tgz instead of the previous .gz.
By the way, I can fix my script but I cannot understand why the download format changed from .gz to tar.gz. All in all, govc is just one binary file. Do you plan to distribute any other file inside the tar.gz?

**Comment by angystardust** [comment]
If you choose to stay with tgz format, you should also modify the **Install** instructions:

```
Download the file relevant to your operating system
Decompress (i.e. tar jxvf govc_linux_amd64.tar.gz)
Set the executable bit (i.e. chmod +x govc)
Move the file to a directory in your $PATH (i.e. mv govc /usr/local/bin/govc)
```

**Comment by dougm** [comment]
@angystardust sorry, this wasn't intentional.  We made changes recently to automate the release using goreleaser.

@frapposelli is this a goreleaser config option we can control?  Probably best if we can just go back to gzip only w/o tar and create a 0.18 release to fix.

**Comment by frapposelli** [comment]
I’m going to fix the goreleaser yaml and rerelease 0.18.

**Comment by frapposelli** [comment]
@angystardust the 0.18 release has been amended, please let me know if everything works fine on your end.

Unfortunately having the binaries directly gzipped instead of wrapped inside a tar requires a patch upstream to `goreleaser`, which I'm working on.

**Comment by angystardust** [comment]
Thanks a lot, @frapposelli and @dougm: I can now download the gz release file without issues.
Thanks for for super-fast reply :+1:
