### ISSUE TITLE
govc: open : no such file or directory

### ISSUE THREAD

**Issue by smutel** [vmware/govmomi#1146]
Hello,

I just installed govc and setup the env variables (GOVC_PASSWORD, GOVC_URL, GOVC_USERNAME and GOVC_CERTIFICATE).

When I execute govc about, the result is:
`govc: open : no such file or directory`

What requirement I mess?
Thanks.

**Comment by dougm** [comment]
If you set the `GOVC_CERTIFICATE` variable, the `GOVC_PRIVATE_KEY` variable also needs to be set.  We can fix the error message to indicate that.

No need to set the `GOVC_CERTIFICATE` and `GOVC_PRIVATE_KEY` variables if you have `GOVC_USERNAME` and `GOVC_PASSWORD` set.

**Comment by smutel** [comment]
For now I don't have the time to find the key. I use GOVC_INSECURE=true instead. Thanks for your answer.

**Comment by dougm** [comment]
ok but those options are for client authentication and would not change the need to set `GOVC_INSECURE`.  You can use the `GOVC_TLS_CA_CERTS` and `GOVC_TLS_KNOWN_HOSTS` vars to avoid setting `GOVC_INSECURE`

https://github.com/vmware/govmomi/tree/master/govc#usage
