### ISSUE TITLE
session.login - No error, but unauthenticated session

### ISSUE THREAD

**Issue by mrmodolo** [vmware/govmomi#1149]
Hi!

I try
govc session.login -u my-user:mypasswd@host
No error after the command, but the session is not authentic!
If I do govc session.ls nothing is displayed!

govc version
govc 0.18.0

Thanks

**Comment by dougm** [comment]
We probably need to add doc on this, but you'll need to include username in the govc url: ```govc session.ls -u my-user@host```

The property collection on the SessionManager object does not fail for anonymous user, but the `sessionList` field cannot be collected without a valid session.

**Comment by mrmodolo** [comment]
Hi!

You are 100% correct!

govc session.ls -u modolo@rj2k12vcenter01.globosat.net.br | grep modolo
5273a956-7ab6-6039-96c5-4290fe974371  GLOBOSAT.NET.BR\modolo                                             2018-06-05 01:12    .     10.1.252.21   govc/0.18.0

Thanks,
Marcelo Módolo
