### ISSUE TITLE
WaitForUpdates API not working

### ISSUE THREAD

**Issue by josminantony** [vmware/govmomi#1151]
I am using  WaitForUpdates  to  get the incremental set of events. But in my case it is giving the events from previous fetch + current fetch with the new version.

defcoll := property.DefaultCollector(colCtx.session.Client)
	propColl, err := defcoll.Create(ctx)
	propFilter := types.CreateFilter{}
	propFilter.Spec = propFilterSpec
	propColl.CreateFilter(ctx, propFilter)

res, err := propColl.WaitForUpdates(ctx, version)

This is how I am using it.

Can you please tell me what should needs to be done to get the incremental set of events with each Version increment.Also I am getting events of array size 10.

**Comment by dougm** [comment]
Can you provide a complete example to reproduce?  How is `propFilterSpec` defined?

Have you tried the EventManager helper?  https://github.com/vmware/govmomi/blob/7736cdc786f6d1a3a5110a717c361e65d4d00b16/govc/events/command.go#L172

**Comment by josminantony** [comment]
Hi, 

The below is the complete example: ( Also I have noticed event_manager is created like this (which is causing the constant 10 objects)
func NewManager(c *vim25.Client) *Manager {
	m := Manager{
		Common: object.NewCommon(c, *c.ServiceContent.EventManager),

		eventCategory:   make(map[string]string),
		eventCategoryMu: new(sync.Mutex),
		maxObjects:      10,
	}

	return &m
}


**My Code :**
colCtx := collContext{}
	colCtx.Request = r
	var err error
	colCtx.session, err = client.NewSession(r.Vcenterurl, r.User, r.Password, true)
	if err != nil {
		fmt.Println("Connection to URL " + r.Vcenterurl + ", failed with Error: " + err.Error())
		return err
	}
	fmt.Println("Connected to vcenter: " + r.Vcenterurl)
	serviceContent := colCtx.session.ServiceContent
	var eventsFilter []string = []string{}
	rootFolder := serviceContent.RootFolder
	entityspec := types.EventFilterSpecByEntity{}
	entityspec.Entity = rootFolder
	entityspec.Recursion = types.EventFilterSpecRecursionOptionChildren
	eventFilterSpec := types.EventFilterSpec{}
	eventFilterSpec.EventTypeId = eventsFilter
	eventFilterSpec.Entity = &entityspec
	eventManager := event.NewManager(colCtx.session.Client)
	defcoll := property.DefaultCollector(colCtx.session.Client)
	propColl, err := defcoll.Create(ctx)
	historyColl, err := eventManager.CreateCollectorForEvents(ctx, eventFilterSpec)
	if err != nil {
		fmt.Printf("Error :" + err.Error())
		return err
	}
	//Create Event Property Filter Spec
	var flag bool = false
	propSpec := types.PropertySpec{}
	propSpec.All = &flag
	var path []string = []string{"latestPage"}
	propSpec.PathSet = path
	propSpec.Type = historyColl.Reference().Type
	propSpecAry := []types.PropertySpec{propSpec}
	var skipFlag bool = false
	objSpec := types.ObjectSpec{}
	objSpec.Obj = historyColl.Reference()
	objSpec.Skip = &skipFlag
	objSpecAry := []types.ObjectSpec{objSpec}
	propFilterSpec := types.PropertyFilterSpec{}
	propFilterSpec.PropSet = propSpecAry
	propFilterSpec.ObjectSet = objSpecAry

	propFilter := types.CreateFilter{}
	propFilter.Spec = propFilterSpec
	propColl.CreateFilter(ctx, propFilter)

	var runFlag int = 1
	for runFlag > 0 {

		fmt.Println("Waiting for new updates:\n", 0)
		duration := time.Duration(5) * time.Second
		time.Sleep(duration)
		res, err := propColl.WaitForUpdates(ctx, version)
		collLastEventTime = time.Now().Unix()
		if res != nil && res.FilterSet != nil {
			version = res.Version
			fmt.Println("\nVersion:", version)
			if version != "1" {
				handleUpdate(res, collLastEventTime)
			}
		}

**Comment by dougm** [comment]
Have you tried using the `EventManager.Events` method instead?  The `latestPage` field is an array, there isn't any automatic filtering of events in that array your client has already seen.  The `Events` method does avoid duplicate events on the client side: https://github.com/vmware/govmomi/blob/f5c88d235d8c95f474a481c3bc0418ef1ba31743/event/processor.go#L173-L175

**Comment by josminantony** [comment]
Sure, I will try. Thanks a lot for the info..

**Comment by dougm** [comment]
@josminantony did `EventManager.Events` work for you?

**Comment by josminantony** [comment]
yes , it worked.Thanks a lot.

**Comment by josminantony** [comment]
is there any way to apply filter for the specified events with this api : EventManager.Events ?

**Comment by dougm** [comment]
Yes, there is an optional `kind` param, example use:

https://github.com/vmware/govmomi/blob/bbd99532a768d2fe369079ceda730e30726ae1a6/govc/events/command.go#L79

https://github.com/vmware/govmomi/blob/bbd99532a768d2fe369079ceda730e30726ae1a6/govc/events/command.go#L178
