### ISSUE TITLE
Incomplete list of VMs returned with ls

### ISSUE THREAD

**Issue by sacasumo** [vmware/govmomi#1173]
I'm not sure if this is a case of RTFM (or lack thereof) but it seems that when I try and get a list of all VMs, the number of machines returned is not the total number of machines in the Datacentre.

To reproduce (tried it on different instances / datacentres)
```
[~] govc ls -l '*' | grep "VirtualMachine" |wc -l
     170
```
(should be 228, vcentre 6.5)
```
[~] govc ls -l '*' | grep "VirtualMachine" |wc -l
     96
```
(should be 124, vcentre 5.5)

Is this a govc issue? Or a human error?

Alternatively, 

`[~] govc ls /<DC name>/vm | wc -l` returns 177 (for the first cluster)

**Comment by sacasumo** [comment]
further update, same information is returned from `datacentre.info`
```
[~] govc datacenter.info
Name:                Name
  Path:              Path
  Hosts:             9
  Clusters:          2
  Virtual Machines:  170
  Networks:          13
  Datastores:        18
```

**Comment by dougm** [comment]
`ls` does not recurse into folders by default.  You can use one of:
```
% govc ls -t VirtualMachine /...
% govc find / -type m
```

The `datacenter.info` command does need fixing, let's leave this issue open for that.
