### ISSUE TITLE
govc host.vswitch.add: enhance to allow setting attributes displayed by host.vswitch.info

### ISSUE THREAD

**Issue by ezibode** [vmware/govmomi#1174]
It would be great if host.vswitch.add (or the addition of host.vswitch.change) could set the attributes displayed by host.vswitch.info, specifically:
- Allow promiscuous mode
- Allow forged transmits
- Allow MAC changes
- Pnic (vswitches can have more than one physical NIC, but host.vswitch.add only allows adding one)

**Comment by dougm** [comment]
You can make most of those changes with `host.portgroup.change` https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#hostportgroupchange

We can add support for multiple nics + vswitch.change command.

**Comment by sumitmaggo** [comment]
Hi @dougm, is there any plan to add support for this in govc? We are looking for this option to create/update vswitch with multiple nics.
<quote>We can add support for multiple nics + vswitch.change command. </quote>

**Comment by sumitmaggo** [comment]
Hi @dougm, any update on the above query?
