### ISSUE TITLE
Feature request: vm.disk.detach

### ISSUE THREAD

**Issue by yamamoto-hiroki** [vmware/govmomi#1181]
vm.disk.attach works great for attaching disks, however, it seems that it's currently not possible to detach an attached disk from a VM, keeping the data disk VMDK file intact, but detaching it from the running VM.

A commit dating back to 2014 seems to imply most of the code is already available to trigger a disk detach ? (https://github.com/vmware/govmomi/pull/76/commits/f15c5f0ef629b48c24418778a46991eb39f5383d)

Am I missing the obvious and does this functionality already exist ? If not, are there any plans to support detaching a disk using govc using for example 'vm.disk.detach' ?

If that is the case, a kind request and +1 for this feature.

**Comment by dougm** [comment]
`device.remove -keep` https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#deviceremove

We should mention that in the doc for vm.disk.attach.

**Comment by yamamoto-hiroki** [comment]
This is fan-tastic ! Works like a charmadillo, thank you Doug
