### ISSUE TITLE
Is it possible to query by OS type?

### ISSUE THREAD

**Issue by spitzerdotorg** [vmware/govmomi#1191]
The end goal is to find all the machines that are poweredON and Linux
The examples show the first part:
govc find . -type m -runtime.powerState poweredOn

But as far as I can tell, there is no way to get the second part in the find command.

Right now I am getting list of poweredOn vms and then I am doing a vm.info on each one. I am hoping that I can cut the queries from 1200 to 2.

Thanks!

**Comment by spitzerdotorg** [comment]
Fantastic! '-guest.guestFamily linuxGuest' was what I needed. You are my new BFF! Thanks!

**Comment by dougm** [comment]
:+1:
