### ISSUE TITLE
Is there any method can get compatibility datastore information when migrate vm ?

### ISSUE THREAD

**Issue by junkao** [vmware/govmomi#1193]
Is there any method can get compatibility datastore information when migrate vm , 

setup .1   select a migration typ   (change storage only )  click next

setup.2    show storage Compatibility:  Compatible  (is there any method can do it)

**Comment by dougm** [comment]
There probably is, can you provide more detail on where this happens in the GUI such as screenshots?  And your vCenter version + GUI type (HTML5 or Flash?)
Are you looking to use the API directly or via govc?

**Comment by junkao** [comment]
@dougm Thank you for your reply

I want to develop a custom vcenter tool that can do multiple or single virtual machines migrate by govmomi API

dev env:
vCenter version 6.7
GUI type  HTML5

**migrate single vm** 
The vcenter can show compatibility datastore when i chose 'change store only'.
Also, vcenter can show compatibility host when i chose 'change compute only'.

How can i get compatibility information  by govmomi api ?

I spent a lot of time looking for methods in sdk, but there is no suitable way

![2018-08-13 12 19 38](https://user-images.githubusercontent.com/4975089/44004084-087014c4-9e8f-11e8-92a8-d5b3de29a450.png)
![2018-08-13 12 19 50](https://user-images.githubusercontent.com/4975089/44004085-089fb206-9e8f-11e8-895e-cbecf5ac9267.png)
![2018-08-13 12 20 13](https://user-images.githubusercontent.com/4975089/44004128-a75217a4-9e8f-11e8-9e1b-cce9ca88c3c7.png)
