### ISSUE TITLE
Add snapshot size to snapshot.tree

### ISSUE THREAD

**Issue by Matty9191** [vmware/govmomi#1197]
It would be really cool to be able to retrieve the size of each VM snapshot by passing a size argument to snapshot.tree.

**Comment by dougm** [comment]
Taking a quick look where we can find this data, it would be useful if you could share the output of this command in your environment and let us know if the `Size` field alone looks correct:

```console
% govc vm.info -json '*' | jq '.VirtualMachines[].LayoutEx.File[] | select(.Type == "snapshotData")'
{
  "Key": 6,
  "Name": "[datastore1] foo/foo-Snapshot1.vmsn",
  "Type": "snapshotData",
  "Size": 1120676,
  "UniqueSize": 1120676,
  "BackingObjectId": "",
  "Accessible": true
}
```

**Comment by atc0005** [comment]
@dougm Having this support would likely be useful for other clients of the govmomi package as well. Do you see adding it as a field to the `types.VirtualMachineSnapshotTree` type?

**Comment by dougm** [comment]
@atc0005 agreed it would be generally useful.  We can't add fields to vim25/types however, those are generated from SDK spec (wsdl).  But you can add helper types and methods by using a different type.  A few examples:

https://github.com/vmware/govmomi/blob/c43a1c86c89e6e30e54d4a21b2d95c03c6ed0c4d/object/authorization_manager.go#L40-L60

https://github.com/vmware/govmomi/blob/c43a1c86c89e6e30e54d4a21b2d95c03c6ed0c4d/license/manager.go#L183-L195

https://github.com/vmware/govmomi/blob/c43a1c86c89e6e30e54d4a21b2d95c03c6ed0c4d/object/virtual_device_list.go#L41-L42

**Comment by atc0005** [comment]
> @dougm: Taking a quick look where we can find this data, it would be useful if you could share the output of this command in your environment and let us know if the `Size` field alone looks correct:

FWIW: This isn't from govc, but accessing the `Size` field seems to yield the size of the `vmsn` file itself (e.g., `RHEL7-TEST-Snapshot9.vmsn`) and not the snapshot as "seen" by `Get-Snapshot` PowerCLI cmdlet or the vSphere web client. Your question was from a bit ago, but since I'm working on this I thought I'd offer the feedback, just in case it was useful.

**Comment by dougm** [comment]
#2269 added a `-s` flag to the `snapshot.tree` command.
