### ISSUE TITLE
Certificate and CA management is broken

### ISSUE THREAD

**Issue by prydin** [vmware/govmomi#1200]
It doesn't seem to be possible to set certificates and custom CAs on a Client, since they require an existing client and vim25.NewClient, as well as govmomi.NewClient send traffic through the client.

Here's the smoking gun:

https://github.com/vmware/govmomi/blob/5bb443a197e27d042a541527493529dfa08c1d6e/vim25/client.go#L79

GetServiceContent is called on the connection, which causes traffic to be sent across the transport. If the CA chain is not set up and the server presents a certificate from a private CA, the call will fail and the client never gets connected.

Suggested solution: Remove SetRootCAs et al and allow callers to NewClient to pass a TLSConfig instead. To preserve backward compatibility, we may want to introduce a NewClientWithTLSConfig instead.

**Comment by prydin** [comment]
So I can't use govmomi.NewClient() if I want to specify a custom CA chain? I'd like to avoid having to use the lower level functions if possible. govmomi.NewClient() creates both the vim25 client and the soap client without any chance of intervening.

What do you think of the idea of letting callers pass a TLSConfiguration? It would work as a catch-all for any TLS customization a caller would like to make. I can issue a PR if there's interest.

**Comment by prydin** [comment]
From govmomi.NewClient. After line 80, it's too late to set up any CA chain, since the connection would already have failed. 

https://github.com/vmware/govmomi/blob/5bb443a197e27d042a541527493529dfa08c1d6e/client.go#L80-L85

**Comment by dougm** [comment]
I'd prefer to deprecate `govmomi.Client` than to change it, as it only provides a handful of shortcuts.  We probably should have a long time ago.  If you look at the git history you'll see how it was pruned back and we moved to using vim25.Client instead in govc.  There are a number of other config options, authentication methods, etc., that `govmomi.NewClient` doesn't support.

**Comment by prydin** [comment]
Not that you asked for my opinion, but I'll give it anyway.... :) I think removing ```govmomi.client``` would be a mistake. It's better to hide the implementation details from the caller. But that's just my opinion...

Could we still consider adding a ```soap.NewClientWithTLSConfig()```? There are tons of configurable things, like ciphers, on a TLS connection and adding this function would provide a simple way of configuring the connection without adding tons methods on the client. Just a thought.

**Comment by prydin** [comment]
This behavior seems to be by design and a functioning workaround to my issue has been provided. I'm closing this.

**Comment by dougm** [comment]
Meant to follow up on this.. we could improve the doc at least.  I hesitate to add more methods to govmomi.Client as there are a number of other config options, auth methods, RoundTrip wrappers (retry, keepalive), etc., that need to happen in between `soap.NewClient` and `vim25.NewClient`.
