### ISSUE TITLE
Search for vm by mac address with govc?

### ISSUE THREAD

**Issue by alexbozhenko** [vmware/govmomi#1201]
Hello. I am having trouble searching for a vm by mac address.
I can do something like:
```
$ govc  object.collect  "/path/to/vm" guest.net
guest.net  []types.GuestNicInfo  ...
```
```
govc object.collect -type m / name guest.net
```
But not sure how to specify values under guest.net, since it is an array.
Is it possible at all?

**Comment by dougm** [comment]
Possible if you use `-json` + `jq`, for example:

```console
% govc object.collect -json -type m / config.hardware.device | jq -r '. | select(.ChangeSet[].Val.VirtualDevice[].MacAddress == "00:50:56:bc:5e:3c") | [.Obj.Type, .Obj.Value] | join(":")' | xargs govc ls -L
/dc1/vm/dougm-ubuntu-16.04
```

**Comment by gswallow** [comment]
I had issues with this approach so I finally stumbled on a different way:

```
#!/bin/bash

for vm in $(govc find -i=true / -type m); do
  govc object.collect -json=true $vm config | jq -r '.[] | select(.Val.Hardware.Device[].MacAddress == "00:50:56:b4:0a:1b") | .Val.Name'
  govc object.collect -json=true $vm config | jq -r '.[] | select(.Val.Hardware.Device[].MacAddress == "00:50:56:b7:06:6f") | .Val.Name'
done
```

By using find with the -i=true flag, I can use govc object.collect on each managed object.  And that gave me access to a data structure that contains both the VM's name and its MAC address.

It's not efficient, but it worked for me :)

**Comment by dougm** [comment]
@gswallow thanks, that makes for a simpler example too.  I've updated #1369 to use your example.
