### ISSUE TITLE
Cannot parse GOVC_URL correctly with ? in the password

### ISSUE THREAD

**Issue by wjun** [vmware/govmomi#1203]
If I define GOVC_URL=$VCENTER_USERNAME:$VCENTER_PASSWORD@$VCENTER_TARGET
If $VCENTER_PASSWORD includes '?', govc commands will fail with error:
govc: dial tcp: address tcp/xxxx: unknown port

**Comment by dougm** [comment]
You can use the `GOVC_PASSWORD` env var to workaround this: https://github.com/vmware/govmomi/tree/master/govc#usage
