### ISSUE TITLE
NewFinder's "all" argument and -json || -dump flags

### ISSUE THREAD

**Issue by kayrus** [vmware/govmomi#1208]
Passing the `-json` parameter dumps all the objects from vcenter and ignores filters. Why is it done this way?

https://github.com/vmware/govmomi/blob/badd514933ffc1d67c88e189fe16cb6d525be0d4/govc/flags/datacenter.go#L90

Is it reasonable just to add an `-all` option? In my current use case I'd like to receive the json for specific request, but `-json` just dumps everything.

**Comment by dougm** [comment]
Can you give an example of what you're trying to do, which govc command and arguments?  Results and expected results?

The `all` param to `NewFinder` does not change which objects are printed, but it does collect all properties for matching objects.

**Comment by kayrus** [comment]
I'm just trying to get the filtered output in json format:

```
govc dvs.portgroup.info -json -pg='/DC1/network/uuid' '/DC1/network/hv-bb'
```
However it tries to fetch all the data and debug data shows that 1-0006.res.xml result gets bigger and bigger, then i get a timeout.

When I run this command without `-json`, it works fine:

```
govc dvs.portgroup.info -pg='/DC1/network/uuid' '/DC1/network/hv-bb'
```

and 1-0006.res.xml debug file is only 388595 bytes long.

**Comment by dougm** [comment]
@kayrus can you review PR #1208 ?
