### ISSUE TITLE
vcsim: find managedObj bug?

### ISSUE THREAD

**Issue by jiatongw** [vmware/govmomi#1211]
I am testing the vcsim works against tags commands.
After the following commands:
```
$ govc find . -type n
/DC0/network/VM Network
/DC0/network/DVS0-DVUplinks-9
/DC0/network/DC0_DVPG0
```
Assuming the tag's name is $TAG
```
$ govc tags.attach $TAG /DC0/network/VM Network
```
This will not work, since there is a space between "VM" and "Network".. `I haven't come up with an idea that how to recognize the space in this special case here..

**Comment by jiatongw** [comment]
@dougm

**Comment by dougm** [comment]
Works fine for me @jiatongw , you do need to quote the second argument:

```
$ govc tags.attach $TAG "/DC0/network/VM Network"
```
