### ISSUE TITLE
vcsim: Support restricting API by VI SDK version

### ISSUE THREAD

**Issue by akutz** [vmware/govmomi#1214]
@embano1 suggested that the vCenter Simulator (vcsim) should be able to limit its available API based on a specific version of the VI SDK. For example, a client targeting 6.5 shouldn't be allowed to use 6.7-specific API calls.

One idea is to retroactively tag commits in this repository that are identified as compatible with specific versions of vCenter.

**Comment by briantopping** [comment]
Is there an alternative pattern for strict API version conformance?

/remove-lifecycle stale
