### ISSUE TITLE
Release 0.19 with tag support

### ISSUE THREAD

**Issue by ivan-pacheco** [vmware/govmomi#1223]
Any target date for its release? 

We're block on our template build automation due to not able to interact with tags. We're happy to test a pre-release build if available.

**Comment by dougm** [comment]
We plan to release 0.19 by the end of the month: https://github.com/vmware/govmomi/milestone/4

Would be great to have any feedback from testing the new tags commands, are you able to build from source? https://github.com/vmware/govmomi/tree/master/govc#source

**Comment by dougm** [comment]
0.19 has been released: https://github.com/vmware/govmomi/releases/tag/v0.19.0
