### ISSUE TITLE
Pass boot command to iao booted vm

### ISSUE THREAD

**Issue by videte47** [vmware/govmomi#1224]
I am not sure if this is the right place for this- but here we go.
I am dealing with an iso appliance that does not have a timeout on the boot menu. I leverage govc to build and mount the iso and even boot. But the problem is that the iso does not move forward until the enter key is pressed. In addition the iso brings a "performance" image that we sometimes use. I wanted to know if govc allows me to pass "up/down/enter" control keys.

**Comment by dougm** [comment]
govc doesn't support this, but we could consider adding it if we find the right API.  For example, the generated govmomi bindings include the `PutUsbScanCodes()` method:
https://www.virtuallyghetto.com/2017/09/automating-vm-keystrokes-using-the-vsphere-api-powercli.html

That requires 6.5, what version are you using?  Could you look for other options and include any summary + links here?

**Comment by videte47** [comment]
ya I am use 6.5. Ya I can def add links to what I find thanks @dougm

**Comment by videte47** [comment]
Also thanks for the link

**Comment by videte47** [comment]
cool looks like this project is using it and actually referencing the same post you mentioned https://github.com/jetbrains-infra/packer-builder-vsphere/blob/8754ddc709902e2f9575cc8e6f213542eda44ff8/driver/vm_keyboard.go#L52

**Comment by dougm** [comment]
Nice, that looks like exactly what we'd need.  I wonder if @mkuzmin would be interested in contributing the `TypeOnKeyboard` method to govmomi?  Or ok with us integrating?

**Comment by dougm** [comment]
Fixed by #1322
