### ISSUE TITLE
upload/download file into a VM failing

### ISSUE THREAD

**Issue by ticapix** [vmware/govmomi#1232]
Hi,

I'm trying to use govc to upload/download file into a VM.
The client is correctly sending and receiving a InitiateFileTransferToGuest soap envelope with the URL to use for the GET or PUT operations.

Unfortunately, govc client doesn't seem to follow the spec https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.guest.FileManager.html#initiateFileTransferToGuest and replace the hostname part of the url with the esx host IP, which in our case make the url invalid.

The code is in this function https://github.com/vmware/govmomi/blob/master/guest/file_manager.go#L130

Is there any reason for not changing the url hostname, only when it equals '*' ?

Thanks,

**Comment by dougm** [comment]
Fixed by #1233
