### ISSUE TITLE
[enhancement] Dockerfile CMD

### ISSUE THREAD

**Issue by rockaut** [vmware/govmomi#1234]
What about using CMD instead of Entrypoint so we actively can do:
`docker run --rm -ti vmware/govc bash`

and execute all in the environment/container.

Well then you would also have to use an base image. I tried it with 18.04 Ubuntu it would just be around 60 MB.

**Comment by rockaut** [comment]
`FROM alpine:3.8

ENV GOVC=https://github.com/vmware/govmomi/releases/download/v0.18.0/govc_linux_amd64.gz

RUN apk add curl jq \
&& curl -L $GOVC | gunzip > /usr/bin/govc && chmod +x /usr/bin/govc

CMD [ "sh" ]
`

**Comment by dougm** [comment]
@frapposelli ?

**Comment by erikh** [comment]
```
docker run --it --entrypoint /bin/bash vmware/govc
```

Likely works with the current container!

**Comment by frapposelli** [comment]
The `vmware/govc` is not meant to be a general purpose container.

You can roll your own with a multi-stage build by copying the govc binary from `vmware/govc` Into your build.

**Comment by rockaut** [comment]
Well i know and do that. Was just an idea to easily enhance an already present solution.
