### ISSUE TITLE
All VMs created with Compatibility:	ESXi 6.5 and later (VM version 13) 

### ISSUE THREAD

**Issue by chiccat** [vmware/govmomi#1240]
Hi,
Is there a way to specify ESXi 6.0?

Thanks

**Comment by dougm** [comment]
If you're using the API, yes:

http://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.ConfigSpec.html

> The version string for this virtual machine. This is used only while creating a new virtual machine, and can be updated by invoking UpgradeVM_Task for this virtual machine. 

If you're using `govc vm.create`, we'd need to add a new flag that sets the field.
