### ISSUE TITLE
Listing Hosts, Datastores, VMs by their parent cluster

### ISSUE THREAD

**Issue by BrandonW94** [vmware/govmomi#1242]
Hello,

I'm trying to write a vcenter collector that will pull all Hosts, Datastores and VMs and write to a database. I am able to get all this info but I'm having trouble getting the cluster that each of these objects belong to. Is this something relatively simple to do. (Im new to golang and govmomi)

Regards

**Comment by dougm** [comment]
The `HostSystem.Parent` field is a host's cluster.  For a VM, this would be the same via the `VirtualMachine.Runtime.Host` field.   The `ClusterComputeResource.Datastore` field tells you which datastores a cluster has access to.

**Comment by BrandonW94** [comment]
thanks for getting back to me.

I gave this a go, however when I retrieve "parent" from "HostSystem" I get ClusterComputeResource:domain-xxxx but I'm just looking for a cluster name.

This is what I'm currently doing:
`m := view.NewManager(c.Client)

v, _ := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"HostSystem"}, true)

var hs []mo.HostSystem

err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"summary", "parent"}, &hs)
if err != nil {
	log.Fatal(err)
}

for _, host := range hs {
	fmt.Println(host.Summary.Config.Name)
	fmt.Println(host.Parent)
}
`

**Comment by dougm** [comment]
Right, `HostSystem.Parent` is just a reference, you'll need to collect the `Name` property for example:

```go
	pc := property.DefaultCollector(c.Client)
	for _, host := range hs {
		fmt.Println(host.Summary.Config.Name)
		var cluster mo.ManagedEntity
		err = pc.RetrieveOne(ctx, *host.Parent, []string{"name"}, &cluster)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(cluster.Name)
	}
```

**Comment by BrandonW94** [comment]
Yes thats what I'm after. Thanks for your help.

One more question though, is there a way I can get things like VM Host HBAs and SCSi Luns also? In powercli it would be the equivalent of Get-VMHOSTHBA <vmhost> and Get-SCSILUN <vmhost> against each of these hosts.

**Comment by dougm** [comment]
It looks like the govc host.storage.info command provides some of that info and might be a good reference for example code:  https://github.com/vmware/govmomi/blob/master/govc/host/storage/info.go#L101
