### ISSUE TITLE
`import.ova` and `import.ovf` display no information about the VM in just created

### ISSUE THREAD

**Issue by jtarchie** [vmware/govmomi#1246]
We are using `import.ova` to create our VM.

When it completes, there's no information about the VM that is just created. We would like to pull the `UUID`. As we've learned inferring the `ipath` can be difficult.

It would be great to get the equivalent `vm.info` when created.

This is what we are thinking programmatically:

```diff
diff --git a/govc/importx/ova.go b/govc/importx/ova.go
index 5249f1b..ca30c7b 100644
--- a/govc/importx/ova.go
+++ b/govc/importx/ova.go
@@ -19,6 +19,7 @@ package importx
 import (
 	"context"
 	"flag"
+	"io/ioutil"
 
 	"github.com/vmware/govmomi/govc/cli"
 	"github.com/vmware/govmomi/object"
@@ -54,7 +55,17 @@ func (cmd *ova) Run(ctx context.Context, f *flag.FlagSet) error {
 	}
 
 	vm := object.NewVirtualMachine(cmd.Client, *moref)
-	return cmd.Deploy(vm)
+	err = cmd.Deploy(vm)
+	if err != nil {
+		return err
+	}
+
+	uuid := vm.UUID(context.TODO())
+	fs := flag.NewFlagSet("", flag.ContinueOnError)
+	fs.SetOutput(ioutil.Discard)
+	fs.Parse([]string{"--vm.uuid", uuid})
+
+	return cli.Commands()["vm.info"].Run(context.TODO(), fs)
 }
 
 func (cmd *ova) Import(fpath string) (*types.ManagedObjectReference, error) {
```

Would you accept a PR for this? If so, are there docs on how to run the tests?

**Comment by kcboyle** [comment]
That was the kind of thing we were thinking @clouderati. If we used a flag, we could leave existing functionality of `import.ova` and `import.ovf` the same, but allow those that need more information about the created vm to get it.

**Comment by jtarchie** [comment]
@clouderati: That is something I have previously requested, too. #1124

**Comment by dougm** [comment]
Could we output just the uuid instead?  Then the caller can capture the uuid and choose to pass to `vm.info` or any other command that accepts the `-vm.uuid` flag? 

And/or, similar to the proposed #1163 , add support for an output format, for example:

```
govc import.ova -o "{{ .Config.InstanceUuid }}" ...
```

**Comment by jtarchie** [comment]
@dougm is this meant to be global feature or just command specific?

**Comment by dougm** [comment]
I think #1163 would apply to any command that currently supports `-json` via govc `flags.OutputFlag`, such as *.info commands.  We could extend the idea to apply here and other commands that create new objects, such as `vm.create`.

**Comment by kcboyle** [comment]
Hi there! 👋🏼 We still think this would be a good thing to add, but we do not have the time or resources to commit to a PR at the moment
