### ISSUE TITLE
I am seemingly unable to access the ClusterComputeResourceSummary.UsageSummary Field

### ISSUE THREAD

**Issue by excilsploft** [vmware/govmomi#1247]
The compiler says 	```types.ClusterUsageSummary does not implement types.BaseComputeResourceSummary (missing GetComputeResourceSummary method)```

which makes sense to me (I think because that) method returns `*ComputeResourceSummary` vs `*ClusterUsageSummary` I might be missing something here but that is my take.  Any help is appreciated

**Comment by dougm** [comment]
Can you provide more context here, which method are you calling and a code snippet?

**Comment by excilsploft** [comment]
Yes sorry for the brevity of my prior post.

I can see the UsageSummary object address on the Summary strict but I am unable to retrieve it as the following throws a compiler error 
usage := ccr.Summary.(types.ClusterUsageSummary)` where `ccr` is a ` mo.ClusterComputeResource`

**Comment by dougm** [comment]
ok, I think this is what you're looking for:
```go
usage := ccr.Summary.(*types.ClusterComputeResourceSummary).UsageSummary
```

**Comment by excilsploft** [comment]
Ah ah I see thank you
