### ISSUE TITLE
Feature request: Simulate delays in vcsim

### ISSUE THREAD

**Issue by prydin** [vmware/govmomi#1250]
Implement a ```-delay``` flag that simulates a poorly performing vCenter. The flag should allow either a delay for all function calls or just for certain calls. The syntax could be something like this:
```
-delay 500  # All functions get 500ms delay
-delay "PerfQuery:1000,GetAvailableMetrics:2000" # List of specific functions to delay
```

Additionally, a ```-delay-jitter``` flag would be useful to add random (Gaussian?) jitter to the delays.

**Comment by dougm** [comment]
Fixed by #1253
