### ISSUE TITLE
sdk url and user:password

### ISSUE THREAD

**Issue by rockaut** [vmware/govmomi#1252]
If you use some characters in password ( which you have to according to the default password rules ;-) ) you have to use environment variables instead of the -u switches. All good.

It just would be nice if you could override the GOVC_USERNAME and GOVC_URL with `-u user@host` and govc is still using GOVC_PASSWORD env instead trying to login without password.
That would be helpfull if you want to login in to vcenter as well as hosts directly because in vcenter you most like have to use a domain user notation and on host that won't be possible.

**Comment by dougm** [comment]
Yes, I think we can do that.  The method that needs changing is here, if you or anyone wants to work on it: https://github.com/vmware/govmomi/blob/master/govc/flags/client.go#L234

**Comment by rockaut** [comment]
Shure will have a look at it.

**Comment by rockaut** [comment]
I had a look at it and now i'm confused. It seems that even if you provide username and password with commands -u switch govc still is using the GOVC_ env variables instead.

inf client.go/Process it extracts the password from -u and set it to flag.url.User but in the next if flag.url.User.Username() doesn't extract the Username given in the -u switch instead keeping the GOVC_USERNAME.

For me that process is completely of the rails because it doesn't use one or the other, no it mixes it?!

**Comment by rockaut** [comment]
`
GOVC_URL=vc1.ad.local
GOVC_USERNAME=userA@ad.local
GOVC_PASSWORD=passwordA
`
`
govc about -u userB:passwordB@esxHostname
`
govc tries to connect to esxHostname with passwordB and userA@ad.local

**Comment by dougm** [comment]
Both `GOVC_USERNAME` and `GOVC_PASSWORD` were added to workaround the case(s) where they aren't properly parsed from `GOVC_URL` by Go's `url.Parse`.  The code just doesn't bother to check the parsed user/pass from `-u` or `GOVC_URL` if they have been set in `GOVC_USERNAME` or `GOVC_PASSWORD`.  For example:
```console
% GOVC_PASSWORD=passwordA govc env -u userB@esxHostname                                                                                                                                                           
GOVC_USERNAME=userB
GOVC_PASSWORD=passwordA
GOVC_URL=esxHostname
```
So the above behaves as your use case is described, provided `GOVC_USERNAME` isn't set.

We could change the code so user/pass given in `-u` would override the env vars, is that something you need?

**Comment by rockaut** [comment]
Yes that is exactly what i meant. I already tried to code that in the mentioned file but it didn't worked as i expected so I've missed something.
