### ISSUE TITLE
Need a provision to set Host IP address

### ISSUE THREAD

**Issue by rdhamale** [vmware/govmomi#1256]
Currently the default ip address of all the hosts is 127.0.0.1. This ip address is hardcoded in https://github.com/vmware/govmomi/blob/master/simulator/esx/host_config_info.go. We need to have a different IP for the hosts other than 127.0.0.1. Currently we can do it for VC but not for esxi host.

**Comment by dougm** [comment]
Can you share your use case?  Such as which fields, there are several.

"we can do it for VC".. I assume you mean the `httptest.serve` flag, are you looking to have that value propagate to the ESX host fields too?

**Comment by rdhamale** [comment]
My http server is running on the ip other than localhost where I am am simulating the host behaviour. I want all the esxi hosts to have that ip and not the localhost one. Also I need the provision to specify port number.

**Comment by dougm** [comment]
@rdhamale #1279 should take care of the IP address.

Not sure what you mean by "Also I need the provision to specify port number"?

**Comment by rdhamale** [comment]
Sorry for incorrect statement. I only need ip provision.

**Comment by rdhamale** [comment]
Have you done a fix ? Because still vc is returning 127.0.0.1 ip only when I am retrieving hosts from vc simulator

**Comment by dougm** [comment]
@rdhamale the PR was still open.  It is merged now if you want to try again.

**Comment by rdhamale** [comment]
Yea it is working now...
