### ISSUE TITLE
"govc vm.ip -v4" returns IPv6 address

### ISSUE THREAD

**Issue by omarkohl** [vmware/govmomi#1259]
```bash
govc vm.ip -v4 -wait 15s test1.example.com
```
The above command sometimes returns an IPv6 IP address. I suspect this happens when the server does not yet have a IPv4 address because after waiting a while it works correctly.

Expected behaviour would be that the command returns an empty string.

**Comment by amandahla** [comment]
@omarkohl Please, can you tell what IPv6 IP address is?
I suspect something around here:
https://github.com/vmware/govmomi/blob/ee4fd8204d68f5faa65db4d2f7410a81a163c52a/object/virtual_machine.go#L316

**Comment by omarkohl** [comment]
For example `fe80::250:56ff:fe97:2458`

**Comment by alex-vmw** [comment]
Any plans to fix this anytime soon? I am also constantly getting "fe80::" ipv6 link-local addresses while specifying the -v4 option for vm.ip. :(

**Comment by dougm** [comment]
I see the issue now, you can workaround using the `-a` or `-n` flag, from the examples:
```
  govc vm.ip -a -v4 $vm
  govc vm.ip -n 00:0c:29:57:7b:c3 $vm
  govc vm.ip -n ethernet-0 $vm
```
We'll get a fix in soon so `-v4` works as expected w/o those flags.
