### ISSUE TITLE
Sometimes VM.WaitForIP returns invalid IP

### ISSUE THREAD

**Issue by segator** [vmware/govmomi#1262]
Sometimes (30% of times) returns 172.18.42.1 this ip is the ip of docker bridge

```bash
docker-sys Link encap:Ethernet  HWaddr 02:42:33:0E:AD:9A
          inet addr:172.18.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:33ff:fe0e:ad9a/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:180 (180.0 B)

```
If i check from vsphere UI always return valid IP(DHCP ip 192.168.. that is the ip expected to be return by waitForIp) the wrong IP is not  show on the UI.

![image](https://user-images.githubusercontent.com/2348131/46883999-e981b780-ce53-11e8-8eb4-5bc0eca6c896.png)

**Comment by dougm** [comment]
`WaitForIP` just returns the `guest.ipAddress` property as reported by guest tools.  Have you tried `WaitForNetIP` instead? https://godoc.org/github.com/vmware/govmomi/object#VirtualMachine.WaitForNetIP

**Comment by segator** [comment]
Thanks!
