### ISSUE TITLE
How to use DVSNameArrayUplinkPortPolicy correctly

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1274]
I am creating a DVSwitch and I need to set the uplink portnames to a unique value. The struct DVSNameArrayUplinkPortPolicy is the correct one to use (and works correctly in Java). However, when I try to use the code below, the switch gets created without any uplink ports and I see an error from vCenter [Not Initialized].  Here is the simple code I am using.
// Build the unique link names like abc1, abc2, etc.
var portList []string = make([]string, args.NumPorts)
		for i := 0; i < args.NumPorts; i++ {
			portList[i] = args.UplinkPortPrefix + strconv.Itoa(i+1)
			Logger.Sugar().Infof("Prefix[%d]: %s\n", i, portList[i])
		}

		var dvsUplinkPorts types.DVSNameArrayUplinkPortPolicy
		dvsUplinkPorts.UplinkPortName = portList
		// Set the potrt policy
		spec.ConfigSpec.GetDVSConfigSpec().UplinkPortPolicy = &types.DVSUplinkPortPolicy{} // need to set the real struct because UplinkPortPolicy
		// (which is BaseUplinkPortPolicy ) is just an interface
		//spec.ConfigSpec.GetDVSConfigSpec().UplinkPortPolicy.GetDVSUplinkPortPolicy().DynamicData = dvsUplinkPorts.DynamicData

		dtask, err := folders.NetworkFolder.CreateDVS(ctx, spec)
_, err = dtask.WaitForResult(ctx, nil)
The WaitForResult errors out with the "Not Initialized" message and I can no longer delete the switch from vCenter either. 
What is the correct way to use the UplinkPortPolicy?

**Comment by kayshavd** [comment]
I tried adding
spec.ConfigSpec.GetDVSConfigSpec().UplinkPortPolicy.GetDVSUplinkPortPolicy().DynamicData = dvsUplinkPorts.DynamicData
but still the same error. 

If I comment out the code that sets the DVSNameArrrayUplinkPortPolicy, then the DWSwitch is created correctly, which leads me to believe that there is something unique in the way that DVSNameArrayUplinkPortPolicy is used.

**Comment by dougm** [comment]
You need to initialize the fields with the concrete types.  The `Get*` methods only return the embedded base type.  Try for example:

```go
	spec := types.DVSCreateSpec{
		ConfigSpec: &types.DVSConfigSpec{
			UplinkPortPolicy: &types.DVSNameArrayUplinkPortPolicy{},
		},
	}
```

Or:

```go
	spec := types.DVSCreateSpec{
		ConfigSpec: &types.VMwareDVSConfigSpec{
			DVSConfigSpec: types.DVSConfigSpec{
				UplinkPortPolicy: &types.DVSNameArrayUplinkPortPolicy{},
			},
		},
	}
```

**Comment by kayshavd** [comment]
Thanks Doug

I realized a few hours ago what I was overlooking and then I fixed it. Appreciate your comments

-kayshav
[Platinum-Volunteer]

**Comment by dougm** [comment]
ok, closing then.

**Comment by kayshavd** [comment]
Hello Doug,

What is the go equivalent of the Java’s InventoryNavigator class?  I was thinking finder would be it, but finder only works when the datacenter is set. InventoryNavigator does not need a datacenter to be set and it can find any object that is in the vCenter.

Appreciate all your help
-kayshav
[Platinum-Volunteer]
