### ISSUE TITLE
govc + jenkins network issues

### ISSUE THREAD

**Issue by kotyara85** [vmware/govmomi#1277]
Hello,
I'm facing a weird issue When I try to create a new vm.

/var/lib/jenkins/bin/govc: network '"v10 192.168.56.0/24"' not found

This happens only in jenkins, from the shell works just fine.

Here's what jenkins generates:

govc vm.create  -net="v10 192.168.56.0/24"  -m=2048  -c=2  -pool=/DC1/host/CL1/Resources  -dc DC1  -ds=DS01  -disk=5\GB  -disk.controller=pvscsi  -folder=Templates  -g=ubuntu64Guest  -on=false  -iso=templates/ubuntu-18.04.1-server-amd64.iso  -iso-datastore=Images ubuntu18

Any help is appreciated.

Thank you

**Comment by dougm** [comment]
`/var/lib/jenkins/bin/govc version` ?

This was an issue in older versions of govc, fixed in #734
