### ISSUE TITLE
vcsim: ReconfigVM unexpected behavior when using partial DynamicData object

### ISSUE THREAD

**Issue by ausevj** [vmware/govmomi#1286]
Having a VirtualMachine with parameter (default):
```
"CpuAllocation": {
    "Reservation": 0,
    "ExpandableReservation": true,
    "Limit": -1,
    "Shares": {
        "Shares": 0,
        "Level": "normal"
    },
    "OverheadLimit": null
},
```

And trying to update `CpuAllocation.Reservation`:

**SOAP request:**
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <ReconfigVM_Task xmlns="urn:vim25">
            <_this type="VirtualMachine">vm-14</_this>
            <spec>
                <cpuAllocation>
                    <reservation>4</reservation>
                </cpuAllocation>
            </spec>
        </ReconfigVM_Task>
    </soap:Body>
</soap:Envelope>
```

**Expected result:**
```
"CpuAllocation": {
    "Reservation": 4,
    "ExpandableReservation": true,
    "Limit": -1,
    "Shares": {
        "Shares": 0,
        "Level": "normal"
    },
    "OverheadLimit": null
},
```

**Actual result:**
```
"CpuAllocation": {
    "Reservation": 4,
    "ExpandableReservation": null,
    "Limit": null,
    "Shares": null,
    "OverheadLimit": null
},
```

**Comment by ausevj** [comment]
**The cause:**

This:
https://github.com/vmware/govmomi/blob/3dbd67fafa902dfb94f571ff7f9fc8948197787a/simulator/virtual_machine.go#L231-L233

Happens before this:
https://github.com/vmware/govmomi/blob/3dbd67fafa902dfb94f571ff7f9fc8948197787a/simulator/virtual_machine.go#L276-L289

The object passed in the request is assigned to the entity, when it should only be updating the properties that are defined in the request.

The behavior is probably the same for all DynamicData objects that are used as updates. For VM: `cpuAllocation`, `memoryAllocation`, `latencySensitivity`, `tools`, `repConfig`, `bootOptions`... And might need to be updated for other `ManagedObject`s that can be reconfigured.

Suggesting to create a common method that takes 2 `DynamicData` type objects, iterates over properties of the 2nd one and assigns them to the 1st object - this could be used for all reconfigure methods of `ManagedObject`s.

**Comment by dougm** [comment]
@ausevj your solution sounds good to me, do you want to submit a PR?
