### ISSUE TITLE
vcsim: Map.Update on objects that have not been added to the registry yet

### ISSUE THREAD

**Issue by ausevj** [vmware/govmomi#1288]
Was going to update `VirtualMachine` methods where properties are set directly to use the new method `Map.Update` instead. Trying to update a property VCSIM fails due to VM not being created yet.

Example:
```diff
govmomi/simulator/virtual_machine.go
@@ -694,7 +707,15 @@ func (vm *VirtualMachine) configureDevices(spec *types.VirtualMachineConfigSpec)
                }
        }

-       vm.Config.Hardware.Device = []types.BaseVirtualDevice(devices)
+       Map.Update(vm, []types.PropertyChange{
+               {Name: "config.hardware.device", Val: []types.BaseVirtualDevice(devices)},
+       })

        return nil
 }
```
always fails when creating VM, because VM is not added to the registry yet. The type in this line is empty string:
https://github.com/vmware/govmomi/blob/ef8efd52a8412f4f30c4c1e99c93e8128141ebef/vim25/mo/retrieve.go#L71

I can check if VM is created, setting property directly if it's not and updating if it is (first time configuring devices - creating VM - it sets properties, when adding additional device - it sends update), but this is not a clean solution when many properties need updating:
```diff
govmomi/simulator/virtual_machine.go
@@ -694,7 +707,15 @@ func (vm *VirtualMachine) configureDevices(spec *types.VirtualMachineConfigSpec)
                }
        }

-       vm.Config.Hardware.Device = []types.BaseVirtualDevice(devices)
+       if vm.Self.Value != "" { // moid isn't set until CreateVM is done
+               Map.Update(vm, []types.PropertyChange{
+                       {Name: "config.hardware.device", Val: []types.BaseVirtualDevice(devices)},
+               })
+       } else {
+               vm.Config.Hardware.Device = []types.BaseVirtualDevice(devices)
+       }

        return nil
 }
```

Wondering if there is a way to rework `Map.Update` (and/or any method it uses) to set properties if object has not been created yet and do not send the updates, or is there any better solution?

**Comment by dougm** [comment]
We could put the vm earlier, such as the diff below.  Or have the configure methods return a `[]types.PropertyChange` and leave it to the caller to call `Map.Update`.  Creating the vm earlier would probably be the simplest path.  What do you think?

```diff
modified   simulator/folder.go
@@ -310,13 +310,14 @@ func (c *createVM) Run(task *Task) (types.AnyType, types.BaseMethodFault) {
 	vm.Summary.Config.VmPathName = vm.Config.Files.VmPathName
 	vm.Summary.Runtime.Host = vm.Runtime.Host
 
+	c.Folder.putChild(vm)
+
 	err = vm.create(&c.req.Config, c.register)
 	if err != nil {
+		c.Folder.removeChild(vm)
 		return nil, err
 	}
 
-	c.Folder.putChild(vm)
-
 	host := Map.Get(*vm.Runtime.Host).(*HostSystem)
 	Map.AppendReference(host, &host.Vm, vm.Self)
```

**Comment by dougm** [comment]
I see, `configure` is called even earlier within `NewVirtualMachine`, with the default set of devices.  So we'd need to putChild even sooner, or skip the `Map.Update` call if the reference hasn't been set`.  
```go
if vm.Self.Type != "" {
    Map.Update(...)
}
```
In that case, there will still be a `Map.Update` triggered with the complete set of devices when the 2nd call to `configure` happens.  Would that work for you?

**Comment by ausevj** [comment]
That's what I'm using right now and it works, but I also added more properties to update, which fall into `configureDevices` method and each take up at least 6 lines:
`vm.summary.config.numEthernetCards` increment+decrement
`vm.summary.config.numVirtualDisks` increment+decrement
`vm.Network`
And there might be more that should be added, so I was looking for a cleaner way to do this. 

If it's possible to use putChild even sooner (maybe with empty object, and work on its properties later) that would be great, for now I'm good with this. Thanks for looking into this

**Comment by dougm** [comment]
Agreed, let's keep it clean.  Calling putChild sooner is probably best, we just have to take care to removeChild in the cases of an error/fault.  Do you want to give that a try?

**Comment by ausevj** [comment]
Okay, I will
