### ISSUE TITLE
Search network or host

### ISSUE THREAD

**Issue by kotyara85** [vmware/govmomi#1291]
Hello,
I'm pulling json config for a VM.
It provides only IDs for networks & hosts.
Is there a way to use govc to find them in the cluster after?
Examples:

    "Host": {
      "Type": "HostSystem",
      "Value": "host-10673"
    },

  "Network": [
    {
      "Type": "Network",
      "Value": "network-10727"
    }
  ],

Thanks

**Comment by dougm** [comment]
You can convert a moref to inventory path with `govc ls -L`, example below.

```console
% ref=$(govc object.collect -s vm/foo summary.runtime.host)
% path=$(govc ls -L $ref)
% govc host.info $path
Name:              10.143.2.201
  Path:            /dc1/host/cluster1/10.143.2.201
  Manufacturer:    VMware, Inc.
  Logical CPUs:    2 CPUs @ 2594MHz
  Processor type:  Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
  CPU usage:       352 MHz (6.8%)
  Memory:          16383MB
  Memory usage:    8405 MB (51.3%)
  Boot time:       2018-10-23 17:42:54.898244 +0000 UTC
  State:           connected
```

The object.collect output format is simpler to use, but if you want to use vm.info -json:

```console
% govc vm.info -json foo | jq -r '.VirtualMachines[].Summary.Runtime.Host | .Type, .Value' | xargs printf "%s:%s\n"
HostSystem:host-14
```
