### ISSUE TITLE
govc: 404 and no additional debug info with vSphere 7.3.0 (build 5604410)

### ISSUE THREAD

**Issue by majusmisiak** [vmware/govmomi#1295]
I am trying to connect VMware vRealize Automation 7.3 server using `govc`. Server is administered by different Team in my organization, but I have user privileges there. With web UI `https://vcloudpar/vcac` I can do just about any action I need (create/destroy VM, generate report, edit Templates).   

Regardless, just about any command ends with 404 error (I would expect at least 403, since I am not an admin on this server):

```
$ govc about.cert
Certificate Status:          good
Issued To: 
...
$ govc about -debug=true -dump=true
govc: 404 
```

Looking at the `~/.govmomi/debug/2018-11-05T12-24-30.868966266/` does not provide any helpful information:

1-client.log
```
2018-11-05T12-24-31.073671605 - 0001:    185ms (*methods.RetrieveServiceContentBody)
```
1-0001-res.xml : empty file

1-0001-res.headers
```
HTTP/1.1 404 
Content-Length: 796
Content-Language: en
Content-Type: text/html;charset=utf-8
Date: Mon, 05 Nov 2018 11:20:46 GMT
X-Frame-Options: SAMEORIGIN
```

1-0001.req.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><RetrieveServiceContent xmlns="urn:vim25"><_this type="ServiceInstance">ServiceInstance</_this></RetrieveServiceContent></Body></Envelope>
```

1-00001.req.headers
```
POST /sdk HTTP/1.1
Host: vcloudpar
Content-Type: text/xml; charset="utf-8"
Soapaction: urn:vim25/6.7
User-Agent: govc/0.19.0
```

Adding `-json` or using different API enpoint, _e.g._ `GOVC_URL=vcloudpar` or `GOVC_URL=vcloudpar/sdk` does not change anything

Otherwise, I can normally connect to API, _e.g._ with curl:
```bash
curl -X POST -H 'Content-Type: application/json' -H 'Accept: application/json'  -d '{"username": "<username>", "password": "<password>", "tenant": "vsphere.local"}' https://vcloudpar/identity/api/tokens
# response:
# {"expires":"2018-11-05T19:45:41.000Z","id":"MTU...==","tenant":"vsphere.local"}
```

Tool versions:

```
$ govc version
govc 0.19.0
```
VMware vRealize Automation version 7.3.0 (build 5604410)

Any idea what is happening / how can I enable additional debug or check whether API calls? How can I check if the API version I have is supported?

**Comment by dougm** [comment]
I haven't used vRealize, is there some documentation that it exposes vCenter's SOAP endpoint?

**Comment by dougm** [comment]
Were you able to find the SOAP endpoint?

**Comment by Pluggi** [comment]
I am having the same issue.

@dougm would this doc reply to your question and help you fix this issue? https://kb.vmware.com/s/article/1003218
