### ISSUE TITLE
Need a provision of getting host port attached with ip 

### ISSUE THREAD

**Issue by rdhamale** [vmware/govmomi#1311]
Hi,
My use case is, I have multiple http servers, serving as an esxi hosts. They have same IP but different ports. So when I am asking for host details, it should give me IP in the format of HostIP:HostPort (127.0.0.1:11000) instead of only host IP.

**Comment by dougm** [comment]
When you say "multiple http servers", do you mean multiple vcsim processes or something else?
How are you asking for host details, where are you expecting to find the port(s)?

**Comment by rdhamale** [comment]
I am simulating the esxi host behaviour. For that I have one http server corresponding to each host. So, through vcsim, in my project I am getting number of hosts and host details in which host IP is also there. Using this IP, my module is trying to connect to host. The issue is my hosts have same IP but are running on the same machine but different ports. Hence vcsim should return Port along with IP. Currently all hosts have same IP but I want to set different port also.

**Comment by dougm** [comment]
Which API / managed object fields are you expecting to get the IP and port values from?
How would a vcsim process know about the ports of another process?

**Comment by rdhamale** [comment]
We are using "mo.HostSystem" object from github.com/vmware/govmomi/vim25/mo. 
Regarding ports number, while running the vcsim "GOPATH/bin/vcsim" command, the flag should be there to provide initial port. Host should be assigned the port in the incremental manner. Like if I have 4 hosts and initial port is 11000, then 4 hosts should have ports as 11000,11001,11002,11003. Please see if you can provide a custom behaviour like this with some flag, so that it will not touch the current behaviour.

**Comment by dougm** [comment]
Which field of `mo.HostSystem` are you expecting to find the port?

vcsim only has 1 port, are you expecting vcsim to listen on a different port for each host?

It isn't clear what your expectations are here.  Maybe you can add a diagram and/or examples.

**Comment by rdhamale** [comment]
Current implementation of govmomi : 
consider vcsim is running on 127.0.0.1:2222 and has 10 hosts in the inventory. Now when I am getting the list of hosts from this vc, all the hosts have the ip 127.0.0.1 .
Expectation  : 
vcsim will run on 127.0.0.1:2222 only. but while returning hosts, the ip's for 10 hosts should be (127.0.0.1:11000, 127.0.0.1:11001, 127.0.0.1:11002, 127.0.0.1:11003, ...................., 127.0.0.1:11009). It is not related to vc ip or vc port. The govmomi is returning static host objects, and for our use case, we are having http server running on those ports (ip-127.0.0.1 and ports- 11000,11001 .......). Hence we want a provision of giving initial port, let say 10000, then all hosts should have ports like 10000, 10001 .....

**Comment by rdhamale** [comment]
Any update on this issue ? Please let me know if you need more clarification.

**Comment by rdhamale** [comment]
I think, the changes are not there in the main.

**Comment by dougm** [comment]
@rdhamale right, PR #1339 has not been merged yet, was asking for review on those changes first.

**Comment by rdhamale** [comment]
Just a small question : If I provide VCSIM_HOST_PORT_UNIQUE=true and vcport=8989, then the ports will start from 8990. Is that correct ?
Everything else is fine.

**Comment by dougm** [comment]
@rdhamale yes, that's correct, I'll go ahead and merge.
