### ISSUE TITLE
Read NSX security tags/groups

### ISSUE THREAD

**Issue by ajruckman** [vmware/govmomi#1312]
How can I read NSX Security Tags and Security Group Membership information for a VM with govmomi? You can see them from the Summary tab for a VM in vSphere. It looks like the tags come from this URL:

```
https://[vCenter hostname]/ui/nsxvhtml/rest/security-tags/[some UUID]/tagsonvm?vmMoid=vm-[VM ID]
```

I can access that URL in the browser just fine as long as I have a valid `JSESSIONID` cookie, but I can't figure out how to get that information from the Go client.

I would like to either get the tags/groups using a govmomi function, or by a GET request to the tag URL with a JSESSIONID created by govmomi. For the latter option I tried using the generated HTTP client returned by `govmomi.NewClient` to GET the URL but I guess it doesn't have the right cookies.

**Comment by ajruckman** [comment]
`govc tags.attached.ls` doesn't seem to work. I think this is for regular tags rather than security tags. 

Unfortunately, we have NSX-V, not NSX-T, so those APIs won't work for us.

Does govmomi login to vSphere like a regular user would? Does it get its own session ID and cookies that could be used to access the nsxvhtml URL?

**Comment by dougm** [comment]
There are several supported authentication methods: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#sessionlogin

Don't know if the cookie can be used with the nsxvhtml URL.

**Comment by ajruckman** [comment]
No luck with those either, it looks like the NSX view is in an iframe and that the session ID is gotten by JavaScript. I guess that's outside the scope of this project. I can do what I need through the NSX web APIs, but I wanted to make sure there wasn't a way to do it in Go. Thanks for your help!
