### ISSUE TITLE
vm.create - Throws multiple instances error

### ISSUE THREAD

**Issue by gsexton** [vmware/govmomi#1317]
I'm running into an error trying to create a host. If I run the command:

`govc vm.create -on=false -ds=datastore1 -m 1024 foo`

I get the error:

"default resource pool resolves to multiple instances, please specify"

If I run:

`govc ls /Datacenter/host/Cluster/Resources`

no entries are returned. Similarly, if I run "govc find" no sub-keys are listed under resources

If I run govc about, I get:

```
Name: VMware vCenter Server
Version: 6.5.0
Build: 807201
OS type: Linux-x64
API type: VirtualCenter
API version: 6.5
Product ID: vpx
```
I ran into something similar when using ovftool where on this cluster, you have specify a cluster name "Cluster". I've looked through the documentation, including the source and I'm just not seeing this.

I tried specifying "-host x.x.x.x" but I got various errors referencing invalid device config.

Can anyone give me some ideas on how to move through this?

**Comment by dougm** [comment]
If you have another cluster or standalone host, you need to specify `-pool Cluster/Resources` or a `-host`.  Not sure about the invalid device issue, could be the `-host` doesn't have access to `datastore1`?

To see the full list of resource pools:
```console
% govc find / -type p
```

**Comment by gsexton** [comment]
@dougm Thank so much for your help. That was the secret.
