### ISSUE TITLE
govc: import.ovf create vm that vmtools not installed

### ISSUE THREAD

**Issue by pytimer** [vmware/govmomi#1323]
I use `govc import.ovf` to create new vm, vm create sucessfully, but i login web and found this vm not install vmtools.

But if i import ovf and create vm through web, vmtools is installed. I want to know where i operate wrong?

And is there a document that description `-options` spec parameters?

Below is my options spec file:
```json
{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "fixedPolicy",
    "IPProtocol": "IPv4",
    "NetworkMapping": [
        {
            "Name": "VM Network",
            "Network": "VM Network"
        }
    ],
    "MarkAsTemplate": false,
    "PowerOn": true,
    "InjectOvfEnv": true,
    "WaitForIP": true,
    "PropertyMapping": [
        {
            "Key": "guestinfo.cis.appliance.net.mode",
            "Value": "static"
        },
        {
            "Key": "guestinfo.cis.appliance.net.addr",
            "Value": "my ip"
        },
        {
            "Key": "guestinfo.cis.appliance.net.prefix",
            "Value": "24"
        },
        {
            "Key": "guestinfo.cis.appliance.net.gateway",
            "Value": "gateway"
        },
        {
            "Key": "guestinfo.cis.appliance.root.passwd",
            "Value": "123456"
        },
        {
            "Key": "guestinfo.cis.appliance.ssh.enabled",
            "Value": "True"
        }
    ]
}
```

**Comment by dougm** [comment]
Before running `vm.power -on`, try this:
 ```
govc vm.guest.tools -mount $VM
```

**Comment by dkirrane** [comment]
I've hit this issue too `govc v0.19.0`, but workaround didn't seem work for me.
```
# options.json spec "PowerOn": false
govc import.ova -name $VM -options=options.json -debug=true file.ova
govc vm.power -on $VM
govc vm.guest.tools -mount $VM
```
open-vm-tools never gets picked up.

`govc import.spec -verbose file.ovf` doesn't give me the possible `PropertyMappings`.
Where can I find all the possible keys for `PropertyMapping` for using Centos 7 64-bit?

**Comment by dougm** [comment]
You'd need to mount tools **before** power on:
```
...
govc vm.guest.tools -mount $VM
govc vm.power -on $VM
```
Note that I haven't tried myself, but I assume tools install in this case is part of the boot process and expects the tools iso to be mounted.

**Comment by dkirrane** [comment]
@dougm is there anyway to use `open-vm-tools` i.e 
I have VM installed with `open-vm-tools` already installed and running.
I exported it `govc export.ovf` and converted to ova.
I then want to import it again on a different vCenter and use `open-vm-tools` on disk

**Comment by dougm** [comment]
If open-vm-tools is installed prior to `export.ovf`, yes it'll still be installed in the VM when you import and no need for calling `vm.guest.tools -mount` in that case.

**Comment by dkirrane** [comment]
@dougm yip tried still doesn't pick it up when importing.

**Comment by pytimer** [comment]
@dkirrane If vmtools is installed in the VM, when you import it, you should power off this VM. And power on after the VM created success.

```sh
# options.json spec "PowerOn": false
govc import.ovf -name $VM -options=ovf.json -ds=datastore1 -host=xxx centos-govc-template/centos-govc-template.ovf
govc vm.power -on $VM
```

It works OK, and the vSphere web show the vmtools has already installed in the VM.

**Comment by dougm** [comment]
@pytimer ok, glad you have it working now.

**Comment by dkirrane** [comment]
@pytimer @dougm Just getting back to this. 
Looks like my issue was Open-VM-Tools wasn't there after import because I had `"InjectOvfEnv": false` set in my options. 
Setting this to true solved my issue. Thanks
