### ISSUE TITLE
Simultor fails to start on 32-bit Intel CPUs

### ISSUE THREAD

**Issue by prydin** [vmware/govmomi#1330]
The simulator crashes with a segmentation fault on startup. This is because the Registry.counter struct member is not on an even 64-bit address. Go (somewhat annoyingly) relies on the programmer to manually align struct members used in atomic operations. A simple workaround is to put them first in the struct. Refer to this article: https://github.com/google/gopacket/issues/512

### Reproduction
Simply run the following on any x86 machine:
```bash
GOARCH=386 go test -v -timeout 30s ./...
```

### Sample log output
=== RUN   TestAuthorizationManager
--- FAIL: TestAuthorizationManager (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e9c]

goroutine 6 [running]:
testing.tRunner.func1(0x1246e280)
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:792 +0x2f6
panic(0x7e97c0, 0x122d240)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x15e
runtime/internal/atomic.Xadd64(0x125c2014, 0x1, 0x0, 0x18, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/internal/atomic/asm_386.s:102 +0xc
github.com/vmware/govmomi/simulator.(*Registry).newReference(0x125c2000, 0xa4f640, 0x125d0060, 0x0, 0x0, 0x4f0, 0xc)
	/Users/prydin/go/src/github.com/vmware/govmomi/simulator/registry.go:117 +0x7c
github.com/vmware/govmomi/simulator.(*Registry).Put(0x125c2000, 0xa4f640, 0x125d0060, 0xb0b6, 0x10)
	/Users/prydin/go/src/github.com/vmware/govmomi/simulator/registry.go:200 +0x65
github.com/vmware/govmomi/simulator.NewLicenseManager(0x9171ba, 0xe, 0x9171ba, 0xe, 0xa4f700, 0x125d4000)
	/Users/prydin/go/src/github.com/vmware/govmomi/simulator/license_manager.go:73 +0x119
github.com/vmware/govmomi/simulator.NewServiceInstance(0x910f8b, 0x6, 0x912184, 0x8, 0x91c059, 0x11, 0x91cb5f, 0x11, 0x122e970, 0x925284, ...)
	/Users/prydin/go/src/github.com/vmware/govmomi/simulator/service_instance.go:65 +0x48b
github.com/vmware/govmomi/simulator.TestAuthorizationManager(0x1246e280)
	/Users/prydin/go/src/github.com/vmware/govmomi/simulator/authorization_manager_test.go:30 +0x194
testing.tRunner(0x1246e280, 0x968950)
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:827 +0x9d
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:878 +0x29b
FAIL	github.com/vmware/govmomi/simulator	0.791s

**Comment by dougm** [comment]
Fixed by #1331
