### ISSUE TITLE
Finding parent Datacenter that a VM is associated with

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1334]
I have ManagedObjectReferencea for a set of VMs and I can fetch the details of the VMa using the PropertyCollector.  But, I can't find any easy way to find the parent Datacenter that each VM belongs to.  

Appreciate if someone could point me to an example.

Thanks
-k

**Comment by dougm** [comment]
You can collect the `Parent` field until you hit the Datacenter or use `mo.Ancestors` for example:

```go
	path, err := mo.Ancestors(ctx, c, c.ServiceContent.PropertyCollector, vm.Reference())
	if err != nil {
		return err
	}
	for i := range path {
		if path[i].Reference().Type == "Datacenter" {
			log.Printf("VM=%s DC=%s\n", vm.Reference(), path[i].Name)
		}
	}
```

**Comment by dougm** [comment]
:+1:
