### ISSUE TITLE
Bug: goroutine leak caused by soap.Client.Upload

### ISSUE THREAD

**Issue by tamaseger81** [vmware/govmomi#1335]
Hi,

The soap.Client is leaving http response bodies behind, which causes the reader goroutine and its fd to stick around. As the result of this behaviour the given process is leaking memory and eventually getting killed by the OS. 

The pprof yields lots goroutines stuck on the select loop, e.g.:
```goroutine 887 [select, 14 minutes]:
net/http.(*persistConn).readLoop(0xc4208a65a0)
    /usr/local/go/src/net/http/transport.go:1717 +0x743
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:1237 +0x95a
```

It's appear to be that each of them are waiting on a https connection to be closed.
```
$ lsof -p ... | wc -l
...
cluster 29817 root    9u     IPv4 0x4a4f6ef1c985a6c1        0t0     TCP 172.16.0.53:63808->10.88.167.126:https (CLOSE_WAIT)
cluster 29817 root   10u     IPv4 0x4a4f6ef1c96a7399        0t0     TCP 172.16.0.53:63703->10.88.167.145:https (CLOSE_WAIT)
cluster 29817 root   13u     IPv4 0x4a4f6ef1ca796399        0t0     TCP 172.16.0.53:63773->10.88.167.137:https (CLOSE_WAIT)
cluster 29817 root   15u     IPv4 0x4a4f6ef1c7f171a9        0t0     TCP 172.16.0.53:63800->10.88.167.142:https (CLOSE_WAIT)
```

Scanning through the codebase I've managed to identify the problematic bits:
- https://github.com/vmware/govmomi/blob/cabbae55b35b107d34dd40d48195488882ed2988/vim25/soap/client.go#L490
- https://github.com/vmware/govmomi/blob/cabbae55b35b107d34dd40d48195488882ed2988/vim25/soap/client.go#L654

In order to fix the problem as part of our codebase the following patch was applied on the codepaths mentioned above:
```
defer func() {
	if res == nil || res.Body == nil {
		return
	}
	_, _ = io.Copy(ioutil.Discard, res.Body)
	_ = res.Body.Close()
}()
```
This makes that sure the http body is being drained and closed unconditionally.

In our use-case the client library is being used to create and configure vm utilising quest operations functionality. 
Each higher level operation (vm create / delete ) has its own client and executes a sequences of commands against the vCenter endpoint including vm cloning, guest power on, guest login, file upload and even remote process exec.

The initial working theory was that the leak is caused by the underlying http transport leaking its keep alive connections. As a mitigation attempt, a single client have been shared across concurrent operations obviously it weren't able to fix the leak.

**Comment by dougm** [comment]
Which version of Go are you using?  Do you have a test case I can use to reproduce?

The `res.Body.Close()` impl already takes care to consume the body if needed afaict: https://github.com/golang/go/blob/84066f1b0b68761a75ce9064f4c412f751ee2168/src/net/http/transfer.go#L966-L968

**Comment by tamaseger81** [comment]
Hi,

Go versions in use:
- go1.10.3 darwin/amd64
- go1.11.2 linux/amd64

I think, the problem may have been caused by exclusively by https://github.com/vmware/govmomi/blob/cabbae55b35b107d34dd40d48195488882ed2988/vim25/soap/client.go#L654. The http response letting left behind without explicitly closing it.

**Comment by dougm** [comment]
I see, yes, we do need to add `defer res.Body.Close()` there, following the err != nil check.  But no need for the io.Copy to ioutil.Discard.  Do you want to open a PR with the change since you found the bug?  Thanks @tamaseger81

**Comment by tamaseger81** [comment]
@dougm: I'll raise a PR tmrw.
Thx :)
