### ISSUE TITLE
vcsim: "missing an Environment Browser"

### ISSUE THREAD

**Issue by zpratt** [vmware/govmomi#1345]
I'm experimenting with using the vsphere terraform provider with vcsim. I can create trivial resources like folders, however, I cannot define VMs when targeting a locally running vcsim with terraform.

I get the following error:

```
* vsphere_virtual_machine.test-node.1: error loading default device list: compute resource "ComputeResource:computeresource-21 @ /DC0/host/DC0_H0" is missing an Environment Browser. Check host, cluster, and vSphere license health of all associated resources and try again
```

I tinkered with assigning a license with govc as I was grasping at straws, but it appears you cannot assign a license to vcsim. That yields this error:

```
govc: ServerFaultCode: LicenseAssignmentManager:licenseassignmentmanager-1 does not implement: UpdateAssignedLicense
```

Which I don't even know if that's the right thing, I was just guessing at possible solutions. I'm curious if anyone has a working example of using the terraform vsphere provider with vcsim.

**Comment by conorcasey** [comment]
Hey folks, what was the resolution here? I am encountering the exact same issue. Thanks in advance for your help.

**Comment by dougm** [comment]
@conorcasey PR #1358 linked above resolved the issue, is you vcsim up-to-date?  https://github.com/vmware/govmomi/blob/master/vcsim/README.md#installation

**Comment by conorcasey** [comment]
Thanks Doug,

I think I figured it out. Thank you for getting back to me though.

Conor


________________________________
