### ISSUE TITLE
govc export and import disk name issue

### ISSUE THREAD

**Issue by dkirrane** [vmware/govmomi#1348]
I'm using `govc 0.19.0`

When I export I get a disk named *mycentosvm-disk-0.vmdk*
```
root@46562987d841:/ova# govc export.ovf -vm=mycentosvm ./
[10-01-19 17:55:57] Downloading mycentosvm-disk-0.vmdk... OK
```

When I try import it expects the disk name to be *disk-0.vmdk*
```
root@46562987d841:/ova# govc import.ovf -name mycentosvm2 mycentosvm/mycentosvm.ovf
govc: open mycentosvm/disk-0.vmdk: no such file or directory
```

If I manually rename this disk vmdk file to `disk-0.vmdk` it govc import.ovf works

**Comment by dougm** [comment]
Don't recall why we added a prefix, but we could remove it or at least add a flag to omit: https://github.com/vmware/govmomi/blob/a4c80cf0ff12d4d88de4c3d955c96db2529328bf/govc/export/ovf.go#L152-L154

**Comment by jorgelon** [comment]
same problem here in govc v0.24.0

/usr/local/bin/govc import.ovf -name=myvm myvm.ovf

govc: open disk-0.vmdk: no such file or directory
