### ISSUE TITLE
How to create CoreOS VMs using cloud-init

### ISSUE THREAD

**Issue by afritzler** [vmware/govmomi#1349]
Hi,

from looking at the vSphere go sdk, there seems to be no easy way to provide `userdata` (e.g. a `cloud-init` configuration file) when creating a virtual machine.

The only way to achive that seems to be using an ISO and attaching a CDROM device to your VM [0].
Thanks to the `terraform` community I found this one here as well [1].

Can somebody point me to a conclusive example on how to do that using the Go SDK?

Regards,
Andreas

[0] https://cloudinit.readthedocs.io/en/latest/topics/datasources/altcloud.html#vsphere
[1] https://github.com/akutz/cloud-init-vmware-guestinfo

**Comment by dougm** [comment]
There are examples using govc, CoreOS iso based cloud-init:
 
https://github.com/vmware/govmomi/blob/master/toolbox/toolbox-test.sh#L70-L121

You'll find guestinfo examples in https://github.com/vmware/simple-k8s-test-env (cc @akutz)

**Comment by afritzler** [comment]
Thanks @dougm for the links! Any examples on how to do this in `golang` instead of `bash`?

**Comment by dougm** [comment]
Closing as stale, feel free to re-open with any specific questions.
