### ISSUE TITLE
Release single Docker image with govc and vcsim

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#1356]
The current build pipeline for the Docker image is limited:

- It seems to lack behind the official release (e.g. Docker Hub states latest `vmware/govc` image is based on v0.18.0, built 8 month ago)
- Only an image for `govc` is built, but it's not uncommon to also require `vcsim` when using `govc`

Suggestion: automated image builds with `goreleaser` when there's a new govmomi release. `goreleaser` is already in use here for both, `vcsim` and `govc` in one Docker image. The good news: `goreleaser` just recently gained support for building multiple binaries and combine them in one (or distinct) Docker images (https://github.com/goreleaser/goreleaser/issues/918).

**Comment by dougm** [comment]
Fixed by #1503
