### ISSUE TITLE
Build govc/vcsim for ARM64 

### ISSUE THREAD

**Issue by lamw** [vmware/govmomi#1363]
There is now PhotonOS for ARM64 running on rPI3, it would be really cool to have govc/vcsim built for ARM64 (running as Docker Container)

```
root@photon-arm [ ~ ]# hostnamectl
   Static hostname: photon-arm.primp-industries.com
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 23c4b92818eb4ddd9f92c304206c5292
           Boot ID: 7c8961109fba41189daded2d1d03600d
  Operating System: VMware Photon OS/Linux
            Kernel: Linux 4.19.6-1.ph3
      Architecture: arm64
```

Reference: https://www.virtuallyghetto.com/2019/01/powershell-for-photonos-on-raspberry-pi-3.html

**Comment by dougm** [comment]
I didn't want to mess with the goreleaser config before getting 0.20 released.  @frapposelli any interest in figuring out the goreleaser magic?

**Comment by frapposelli** [comment]
Looking into it

**Comment by frapposelli** [comment]
Working on having a change done upstream in goreleaser, maintainers are super responsive 👍 

ref. issue: goreleaser/goreleaser#958 PR: goreleaser/goreleaser#959
