### ISSUE TITLE
vm.network change doesn't seem to work as documented.

### ISSUE THREAD

**Issue by grahamnicholls** [vmware/govmomi#1366]
The docs [here:](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md) say that this ought to work:
 `govc vm.network.change -vm /blah/vm/AGL/Templates/Unix/RHEL7.6_NTT_0.1 -net.address 00:50:56:93:b6:66 ethernet-0`
to change the mac address of the network interface attached to a VM.

But it produces this error:

`govc: default network resolves to multiple instances, please specify`

(I'm trying to change the mac address of the interface to match that of another, short-lived instance, so that I can release the dhcp lease which it took)

Manually changing the mac address and rebooting works, but I'm trying to do this through a shellscript.

Debugging output (and set -x) below:
```
 DEBUG: Powering off existing VM
Powering off VirtualMachine:vm-2515... OK
Name:               ethernet-0
  Type:             VirtualVmxnet3
  Label:            Network adapter 1
  Summary:          DVSwitch: 58 7b 13 50 ba 92 53 55-34 f9 8f cd 10 8e f0 03
  Key:              4000
  Controller:       pci-100
  Unit number:      7
  Connected:        false
  Start connected:  true
  Guest control:    true
  Status:           untried
  MAC Address:      00:50:56:93:23:bb
  Address type:     assigned
++ govc ls vm/AGL/Templates/Unix/RHEL7.6_NTT_0.1
++ jq -r .mac_addr config/NTT.json
+ govc vm.network.change -vm /blah/vm/AGL/Templates/Unix/RHEL7.6_NTT_0.1 -net.address 00:50:56:93:b6:66 ethernet-0
govc: default network resolves to multiple instances, please specify
```

Apologies - is there a more appropriate place to ask?

**Comment by dougm** [comment]
The `-net` flag is required in this case, unless the VC/ESX environment only has 1 network.
We can either fix the doc or make `-net` optional if the VM only has 1 nic.

**Comment by grahamnicholls** [comment]
Thanks - works as advertised; just a documentation thing, then.
