### ISSUE TITLE
guest.start fails to run

### ISSUE THREAD

**Issue by grahamnicholls** [vmware/govmomi#1367]
Might be a documentation issue:
govc.start attempting to run as root persistently fails:

vm_path="vm/AGL/Templates/Unix/RHEL7.6_NTT_0.1"
`govc guest.start  -l "${GOVC_GUEST_LOGIN}" -vm $(govc ls "${vm_path}")`

with exported GOVC_GUEST_LOGIN="root:password" always returns:

`govc: ServerFaultCode: Permission to perform this operation was denied.`

The password is correct - I've tried with it set to "password" (yes, I'm embarrassed!) - with no joy.

Might the issue be that the govmomi/toolbox needs to be installed?

> This command depends on govmomi/toolbox running in the VM guest and does not work with standard VMware tools.

Which is in the documentation for govc.run, but not for govc.start ? 

govc.ps also fails:
```
 #echo $GOVC_GUEST_LOGIN ; govc guest.ps -l "${GOVC_GUEST_LOGIN}" -vm $(govc ls "${vm_path}")
root:password
govc: ServerFaultCode: Permission to perform this operation was denied.
```
I get the same behaviour if I don't pass the -l option and rely on the exported variable.

Thanks

**Comment by dougm** [comment]
Only the `guest.run` command requires govmomi/toolbox, all the other `guest.*` work with either tools flavor.  Looks like vCenter level permissions won't allow it.  When in-guest login fails, the error would be:
`Failed to authenticate with the guest operating system using the supplied credentials.`

Check that your role has these permissions:

```console
% govc role.ls Admin | grep GuestOp
VirtualMachine.GuestOperations.Execute
VirtualMachine.GuestOperations.Modify
VirtualMachine.GuestOperations.ModifyAliases
VirtualMachine.GuestOperations.Query
VirtualMachine.GuestOperations.QueryAliases
```

**Comment by grahamnicholls** [comment]
Thank you - will do. As an aside, raising an issue seems the wrong way to ask a question like this - in the other case I raised it was actually a (documentation) issue - is there a preferred medium for asking questions? Thanks.

**Comment by dougm** [comment]
Using GH is fine, we also have a slack channel: https://github.com/vmware/govmomi#discussion

**Comment by Cospotato** [comment]
@dougm how can i install govmomi/toolbox, any document ?

**Comment by dougm** [comment]
Assuming this has been resolved, feel free to reopen if not.
