### ISSUE TITLE
No command to delete datacenter ??

### ISSUE THREAD

**Issue by collabnix** [vmware/govmomi#1373]
I don't see any command to destroy or remove datacenter. I can create the datacenter running the below command:

```
govc datacenter.create demo1
```
But no such command like govc datacenter.destroy.
Can anyone suggest?

**Comment by dougm** [comment]
We should improve the doc on this.. you can use `object.destroy`: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectdestroy

**Comment by collabnix** [comment]
@dougm Yes, I am planning to come up with cheatsheet as well as blog post around it.
https://github.com/collabnix/govc is the link I am working and soon will be raising PR for the same.

**Comment by dougm** [comment]
@collabnix nice work, that looks great so far!
