### ISSUE TITLE
VirtualMachine IsToolRunning panic due nil pointer

### ISSUE THREAD

**Issue by Fred78290** [vmware/govmomi#1376]
### Panic due nil pointer usage

In file govmomi/object/virtual_machine.go line 640.

The asked property is wrong. Must be "**guest.toolsStatus**" instead "**guest.toolsRunningStatus**"

**Original code**
err := v.Properties(ctx, v.Reference(), []string{"guest.toolsRunningStatus"}, &o)

**Fixed code**
err := v.Properties(ctx, v.Reference(), []string{"guest.toolsStatus"}, &o)

**Comment by dougm** [comment]
From https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.GuestInfo.html
> Deprecated. As of vSphere API 4.0 use toolsVersionStatus and toolsRunningStatus.

However, it looks like we should check that `Guest != nil`, as that would be the case if the VM isn't powered on.

**Comment by Fred78290** [comment]
The error occurs only when I use vcsim but not with vSphere 6.5

govc vm.info -json /DC0/vm/DC0_H0_VM0 | jq

To avoid the bug I replaced **guest.toolsRunningStatus** by **guest** to get all guest infos and fill the variable.

So my test phase failed with vcsim but was successfully on vSphere.

**Comment by dougm** [comment]
I see, we can fix vcsim to behave as vSphere does in this case.

**Comment by Fred78290** [comment]
Maybe the error is in err := **v.Properties**(...) because this call

```bash
govc vm.info -json /DC0/vm/DC0_H0_VM0 | jq .VirtualMachines[0].Guest
```
returns

```json
{
  "ToolsStatus": "toolsNotInstalled",
  "ToolsVersionStatus": "",
  "ToolsVersionStatus2": "",
  "ToolsRunningStatus": "",
  "ToolsVersion": "0",
  "ToolsInstallType": "",
  "GuestId": "",
  "GuestFamily": "",
  "GuestFullName": "",
  "HostName": "",
  "IpAddress": "",
  "Net": [
    {
      "Network": "",
      "IpAddress": null,
      "MacAddress": "00:0c:29:95:e3:e2",
      "Connected": true,
      "DeviceConfigId": 4000,
      "DnsConfig": null,
      "IpConfig": null,
      "NetBIOSConfig": null
    }
  ],
  "IpStack": null,
  "Disk": null,
  "Screen": null,
  "GuestState": "",
  "AppHeartbeatStatus": "",
  "GuestKernelCrashed": null,
  "AppState": "",
  "GuestOperationsReady": null,
  "InteractiveGuestOperationsReady": null,
  "GuestStateChangeSupported": null,
  "GenerationInfo": null
}
```
guest.toolsRunningStatus is just an empty string interpreted as null by the property parser and in this case, the call v.Property return null object instead the empty string.

to avoid the problem I replaced the call by

```
err := v.Properties(ctx, v.Reference(), []string{"guest"}, &o)
``` 
And work fine.
