### ISSUE TITLE
Can't use package in third party program to create DRS rules

### ISSUE THREAD

**Issue by integrii** [vmware/govmomi#1386]
Just leaving a note here after a few hours of frustration.

It looks like the path to simply create a DRS rule in a cluster using the code in this govmomi repo as a package used in my own program is nearly impossible.  Every time I try to do this, I realize that the flag sets have been built into the code so deeply that I would have to refactor or rebuild the entire thing.

Basically, I can't find a way in less than 250 lines to simply create a DRS anti-affinity rule. 

I have been able to use the finder part of the package to great success, but it appears the functionality to manage DRS rules in your own program is missing entirely.

Anyone have a code snippet that I somehow completely missed that would let someone make a DRS rule much like the PowerShell commandlets let you?

Similar issue: #535

**Comment by dougm** [comment]
In general, most of govc is mapping command line flags to struct fields and API methods calls, along with formatting the method output.  If you're trying to import a govc package into a program that isn't govc, that will be painful.  Calling the API directly can also be frustrating, but we do try to ease these pains in govmomi when possible - we have often extracted helper code from govc into govmomi packages that can be used without any govc package dependency.

In this case, the main challenge is getting the `ClusterRuleSpec` right, there are some examples outside of govmomi: https://github.com/search?l=&p=1&q=ClusterRuleSpec+language%3AGo&type=Code

Example spec from `cluster.rule.create` (from the cluster.bats tests):
```console
% govc cluster.rule.create -cluster DC0_C0 -name pod1 -affinity DC0_C0_RP0_VM{0,1}
spec := &types.ClusterConfigSpecEx{
    RulesSpec: []types.ClusterRuleSpec{
        {
            ArrayUpdateSpec: types.ArrayUpdateSpec{
                Operation: "add",
            },
            Info: &types.ClusterAffinityRuleSpec{
                ClusterRuleInfo: types.ClusterRuleInfo{
                    Enabled:      types.NewBool(false),
                    Name:         "pod1",
                    UserCreated:  types.NewBool(true),
                },
                Vm: []types.ManagedObjectReference{
                    // ... add your VM refs here
                },
            },
        },
    },
}
```

I captured the spec with the quick hack below.  Thinking we could add a govc flag to enable a Go version of the request trace, making it easy to see the raw Go version of govc calls.  The `-debug` option provides an xml trace, but cumbersome to convert that back to Go.

```diff
modified   govc/cluster/rule/info_flag.go
@@ -20,7 +20,9 @@ import (
 	"context"
 	"flag"
 	"fmt"
+	"os"
 
+	"github.com/kr/pretty"
 	"github.com/vmware/govmomi/govc/flags"
 	"github.com/vmware/govmomi/vim25/types"
 )
@@ -143,7 +145,7 @@ func (f *InfoFlag) Apply(ctx context.Context, update types.ArrayUpdateSpec, info
 			},
 		},
 	}
-
+	pretty.Fprintf(os.Stderr, "spec := %# v\n", spec)
 	return f.Reconfigure(ctx, spec)
 }
```

**Comment by integrii** [comment]
Thanks for your reply @dougm.  I will see if I can keep banging on this code in the week with your help here.
