### ISSUE TITLE
datastore.disk.create permission error

### ISSUE THREAD

**Issue by remoe** [vmware/govmomi#1391]
After run the following on VCenter:

```
govc datastore.disk.create -debug=1 -dump=1 -ds ds -size 1G test.vmdk 
```

It throws the following error:

```govc: ServerFaultCode: Permission to perform this operation was denied.```

Debug xml dump:

```xml
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>ServerFaultCode</faultcode>
            <faultstring>Permission to perform this operation was denied.</faultstring>
            <detail>
                <NoPermissionFault xmlns="urn:vim25" xsi:type="NoPermission">
                    <object type="Datacenter">datacenter-45939</object>
                    <privilegeId>System.Read</privilegeId>
                </NoPermissionFault>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
```

I setup a lot of other resources without any error. But I can't create a disk even though with administration permissions on the registered vcenter datastore.

**Comment by dougm** [comment]
This fault is for type `Datacenter`, are there multiple Datacenters?  If so, you may need to specify `-dc`.

**Comment by remoe** [comment]
Only one DC, defined with GOVC_DATACENTER.

**Comment by dougm** [comment]
What does the request xml dump look like, is it the `CreateVirtualDisk_Task` request?
Any useful info from `govc logs` after the command fails?
Does the `govc disk.create` command work for you?  The top-level disk.* commands require vSphere 6.5 or higher.

**Comment by remoe** [comment]
Yes it was ```CreateVirtualDisk_Task```. govc logs dumps the following:

```
govc: ServerFaultCode: Permission to perform this operation was denied.
```

```
> govc about:

*** VSphere Info
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.5.0
Build:        7515524
OS type:      win32-x64
API type:     VirtualCenter
API version:  6.5
Product ID:   vpx
```

govc 0.19 does not have disk.create. So I try to use 0.20:

```
[22-02-19 09:15:44] Creating test/test.vmdk...
```

This operation hangs without an error.

**Comment by dougm** [comment]
If you have an Admin role, you shouldn't have a permissions issue with `govc logs` either.
Can you double check your role permissions?

**Comment by remoe** [comment]
I've only Admin role on this datastore and on a cluster with ESX-Hosts. But not on VCenter.

**Comment by dougm** [comment]
ok, I don't know what permissions are required for CreateVirtualDisk, but if you can add the output of `govc role.ls Your-Role-Name` we can try to figure out what permission is missing.

**Comment by remoe** [comment]
Can I send this with PM?

**Comment by remoe** [comment]
I think I don't have an attached global role. Sorry I'm not the administrator of VCenter. Here is my anonymised output:

```
# govc permissions.ls /DC
govc: ServerFaultCode: Permission to perform this operation was denied.
# govc permissions.ls /DC/host/cluster
Role   Entity              Principal  Propagate
Admin  /DC/host/cluster    user       Yes
# govc permissions.ls /DC/datastore/ds
Role   Entity                    Principal  Propagate
Admin  /DC/datastore/ds          user       Yes
```

**Comment by dougm** [comment]
ok, sounds like your role has `System.View` permission for DC - that's enough for inventory navigation / the majority of govc `-dc` flag usage.  But back to the original fault, `CreateVirtualDisk_Task` requires `System.Read` permission for the Datacenter param and it sounds like you don't have that.  The only suggestion I have is that you request that permission from your administrator.

**Comment by remoe** [comment]
Thanks!
But I can create with the current permissions a new VM with a new Disk. I didn't understand why ```datastore.disk.create``` / ```disk.create``` need more permissions then this.

**Comment by dougm** [comment]
I don't know why the methods require different permissions, but it isn't something that govmomi can avoid as this is on the vCenter side.  Have you been granted the permission?

**Comment by remoe** [comment]
Sorry, I don't manage the vCenter. Currently I can't get and test this permission.

**Comment by remoe** [comment]
I have now the "System.Read" permission on our DC. And I can call this:
```govc permissions.ls /DC```

without any error. But ```govc datastore.disk.create``` and ```disk.create``` doesn't work. It hangs. I see this in the debug output:

```xml
                        <kind>modify</kind>
                        <obj type="Task">task-5325112</obj>
                        <missingSet>
                            <path>info</path>
                            <fault>
                                <fault xsi:type="NoPermission">
                                    <object type="Folder">group-d1</object>
                                    <privilegeId>System.Read</privilegeId>
                                </fault>
                                <localizedMessage></localizedMessage>
                            </fault>
                        </missingSet>
```
 
When I create a vm with terraform / vsphere_virtual_machine I need to use "folder" to create a VM:
https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#folder

But i can't set this folder on govc disk.create. Could this be an issue?

**Comment by dougm** [comment]
The "folder" for creating a VM is an inventory folder.  VMs, hosts, datastores, etc., objects all live inside inventory folders.  A virtual disk does not live in an inventory folder, so the disk.create commands don't have a folder option.

Looks like the same permissions issue as before, only this time for the root inventory folder instead of the `/DC` Datacenter:

```console
% govc ls -L Folder:group-d1
/
```

The disk.create commands should error out instead of hang in this case, I'll look into that.  But sounds like you'll need to get the same `System.Read` permission granted for `/`

**Comment by khauser** [comment]
Our misconfiguration  was:
```
govc permissions.ls /
Role      Entity  Principal                                                             Propagate
ReadOnly  /       VSPHERE.LOCAL\kubernetes-sc                                           No
```

Setting Propagate->Yes solved the problem.

**Comment by dougm** [comment]
ok @khauser , good to hear you have it working now.
