### ISSUE TITLE
Can I use instant clone functionality with govmomi/govc?

### ISSUE THREAD

**Issue by ghaabor** [vmware/govmomi#1392]
Hey,

I'd tried to figure out if the govmomi library is capable of doing instant clones and I've came to the conclusion that it's not possible at the moment - but I'm not 100% sure this is the right answer. If it's not available yet then this is kind of a feature request as well. :)

**Comment by dougm** [comment]
It is possible with govmomi, all the 6.7 generated API types are there: https://godoc.org/github.com/vmware/govmomi/vim25/methods#InstantClone_Task

But there isn't any higher level govmomi wrapper or govc command yet, so we can consider this a feature request :)  If you can find some good instant clone docs, examples in another language, etc., adding pointers in this issue would be a great start.

**Comment by ghaabor** [comment]
Thanks for the answer! Once I'll have some time I'll do in some investigation and put here any resources which could be useful. :)

**Comment by lamw** [comment]
@dougm Check out https://www.virtuallyghetto.com/2018/04/new-instant-clone-architecture-in-vsphere-6-7-part-2.html for code samples exercising the new Instant Clone API in 6.7

**Comment by dmmarkham** [comment]
I was also coming here to make this feature request as this is possible in pyvmomi. So consider this a very enthusiastic +1 on the feature!

**Comment by vfiftyfive** [comment]
+1

**Comment by slarimore02** [comment]
+1
