### ISSUE TITLE
permissions.remove does not apply to multiple VMs

### ISSUE THREAD

**Issue by josephinemho** [vmware/govmomi#1401]
I ran this command `govc permissions.remove -principal 'USER' SERVER1 SERVER2 SERVER3` and expected the user to be removed from all three VMs, however he was only removed from the first VM. Yet adding users to all VMs worked: `govc permissions.set -principal 'USER' -role 'VM User + Settings + Snapshot' SERVER1 SERVER2 SERVER3` was successfully applied to all VMs. 

Need a way to remove users from multiple VMs please :) 

P.S. removing permissions always generates the following output: `govc: ServerFaultCode: The object or item referred to could not be found.` even though the permission was there and the removal was successful, so that could be a bit misleading.

**Comment by dougm** [comment]
The not found error is causing the loop to break.  A NotFound fault can also be thrown if the user or group does not exist at all.  So rather than doing this by default, #1408 adds a `-f` flag to ignore these errors.  Sound ok?
