### ISSUE TITLE
golang roundTrip函数里有个for循环，为什么看不到终止条件

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1404]
func (r *retry) RoundTrip(ctx context.Context, req, res soap.HasFault) error {
	var err error

	for {
		err = r.roundTripper.RoundTrip(ctx, req, res)
		if err == nil {
			break
		}

		// Invoke retry function to see if another attempt should be made.
		if retry, delay := r.fn(err); retry {
			time.Sleep(delay)
			continue
		}

		break
	}

	return err
}

**Comment by sirzhanghai** [comment]
func (r *retry) RoundTrip(ctx context.Context, req, res soap.HasFault) error {
	var err error

	for {
		err = r.roundTripper.RoundTrip(ctx, req, res)
		if err == nil {
			break
		}

		// Invoke retry function to see if another attempt should be made.
		if retry, delay := r.fn(err); retry {
			time.Sleep(delay)
			continue
		}

		break
	}

	return err
}

**Comment by dougm** [comment]
The loop terminates when `retry` is false.

**Comment by cuishuang** [comment]
这哥们中文都看得懂啊....厉害
