### ISSUE TITLE
Something is wrong with the way govc handles nested resource pools I think

### ISSUE THREAD

**Issue by rlewkowicz** [vmware/govmomi#1413]
In most other applications, docker-machine for example, I cannot use the pool path that govc returns. I think I ran into this as well trying to use govc to upload an options.json. 

govc find -type p
...
./host/SQAQF01/Resources/PCF-AZ2
...

So I take this and try to use it anywhere, it doesn't work. Even if I replace `.` with the absolute base. 

Things are deployed to this though. 

I go grab the vm info:

```
      "ResourcePool": {
        "Type": "ResourcePool",
        "Value": "resgroup-5973"
      },
```

And if I use the absolute path or the I think it's called MOID, I get nothing:

```
govc pool.info --json 'ResourcePool:resgroup-5973'
{"ResourcePools":null}
```

Something is just weird here

**Comment by dougm** [comment]
If the path is relative, the pool.info command (via Finder) assumes it is relative to the host folder.  We could probably handle the case where the path is relative to the Datacenter.  But in the meantime you can use the absolute path:
```console
% govc find / -type p
```
Or relative to host folder:
```console
% govc pool.info SQAQF01/Resources/PCF-AZ2
```

You can also get the pool path from the vm `resourcePool` property like so:
```console
% govc object.collect -s vm/$name resourcePool | xargs govc ls -L
/dc1/host/cluster1/Resources
```

**Comment by rlewkowicz** [comment]
I had tried setting the absolute path. Anywho, I'll close this. I think something is still weird there, but I've moved on
