### ISSUE TITLE
Quickstart guide for go client

### ISSUE THREAD

**Issue by Jodazo** [vmware/govmomi#1415]
Hi, 

I would like to write a simple go application the uses govmomi to read out vm information including custom attributes. With govc I would call govc vm.info -json <path-to-vm> . Would you mind giving some hints where to start?

Also I would like to write a unit test. But how do I populate a simulator with a vm that has CustomAttributes?

Thanks in advance!

Jodazo

**Comment by dougm** [comment]
Most of the `vm.info` data are managed object properties: https://github.com/vmware/govmomi/blob/b573c09e4e0e7936d2946f6c5e19bfaee5a7e253/govc/vm/info.go#L138-L140

You'll find CustomAttributes (aka CustomFields) examples in the govc fields commands code: https://github.com/vmware/govmomi/blob/b573c09e4e0e7936d2946f6c5e19bfaee5a7e253/govc/fields/info.go#L125

The simulator supports the CustomFieldsManager, you'd use the same client API methods to populate the data.  See for example the simulator's own unit test: https://github.com/vmware/govmomi/blob/b573c09e4e0e7936d2946f6c5e19bfaee5a7e253/simulator/custom_fields_manager_test.go#L32-L47
