### ISSUE TITLE
Creating CustomizationSpec via Package

### ISSUE THREAD

**Issue by donwlewis** [vmware/govmomi#1418]
I am trying to leverage the govmomi package in my own go app, and trying to chase down how I would build out the struct to create a non persistent customization spec.  I think have most of what I need to create the struct, but I get to this part:

```golang
type CustomizationIPSettings struct {
	DynamicData

	Ip            BaseCustomizationIpGenerator            `xml:"ip,typeattr"`
	SubnetMask    string                                  `xml:"subnetMask,omitempty"`
	Gateway       []string                                `xml:"gateway,omitempty"`
	IpV6Spec      *CustomizationIPSettingsIpV6AddressSpec `xml:"ipV6Spec,omitempty"`
	DnsServerList []string                                `xml:"dnsServerList,omitempty"`
	DnsDomain     string                                  `xml:"dnsDomain,omitempty"`
	PrimaryWINS   string                                  `xml:"primaryWINS,omitempty"`
	SecondaryWINS string                                  `xml:"secondaryWINS,omitempty"`
	NetBIOS       CustomizationNetBIOSMode                `xml:"netBIOS,omitempty"`
}
```

At this point I need to get the IP info into the struct.  When I chase down `BaseCustomizationIPGenerator` type, I find this:

```golang
type BaseCustomizationIpGenerator interface {
	GetCustomizationIpGenerator() *CustomizationIpGenerator
}
```

Which lead me to this function:

```golang
func (b *CustomizationIpGenerator) GetCustomizationIpGenerator() *CustomizationIpGenerator { return b }
```

At this point this doesn't appear to really do anything.  Am I just not seeing it, or is this functionality not fully fleshed out?  How do I create a `BaseCustomizationIpGenerator` type?

**Comment by dougm** [comment]
This type, along with everything in the `types` package is generated from the vSphere SDK wsdl.  Since Go is not object oriented, the govmomi generator includes `Base` interface types in the cases where a type is extended by other types.  In this case, `CustomizationIpGenerator` is documented here:
https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.customization.IpGenerator.html

> Extended by CustomizationCustomIpGenerator, CustomizationDhcpIpGenerator, CustomizationFixedIp, CustomizationUnknownIpGenerator

So the `Ip` field would be one of those types at runtime.

**Comment by donwlewis** [comment]
We we ended up building the struct in this way:

```golang
custSpec := &types.CustomizationSpecItem{
		Info: types.CustomizationSpecInfo{
			Name: "Name",
			Type: "Type",
		},
		Spec: types.CustomizationSpec{
			NicSettingMap: []types.CustomizationAdapterMapping{
				types.CustomizationAdapterMapping{
					Adapter: types.CustomizationIPSettings{
						Ip: &types.CustomizationFixedIp{
							IpAddress: "192.168.1.100",
						},
						SubnetMask:    "255.255.255.0",
						Gateway:       []string{"192.168.1.1"},
						DnsServerList: []string{"192.168.1.1"},
						DnsDomain:     "ad.domain",
					},
				},
			},
			Identity: &types.CustomizationLinuxPrep{
				HostName: &types.CustomizationFixedName{
					Name: "hostname",
				},
				Domain:     "ad.dmomain",
				TimeZone:   "Etc/UTC",
				HwClockUTC: &bol,
			},
			GlobalIPSettings: types.CustomizationGlobalIPSettings{
				DnsSuffixList: []string{"ad.domain"},
				DnsServerList: []string{"192.168.1.1"},
			},
		},
	}
```

We build out this struct within our own go package, and then apply it with the Clone() function, and it seems to work.  My question is whether this is the proper way to leverage this or not?

**Comment by dougm** [comment]
I haven't used this part of the API myself, but the use of `types.CustomizationFixedIp` looks right to me.

**Comment by donwlewis** [comment]
Thanks @dougm.  This appears to work just fine so we will go with it.  Appreciate you marking this for documentation.

**Comment by dougm** [comment]
@donwlewis used your spec in PR #1731 , can you review?

**Comment by donwlewis** [comment]
@dougm looks good to me.  Thanks!
