### ISSUE TITLE
vcsim propertycollector invalid namespace value

### ISSUE THREAD

**Issue by fergalkeating** [vmware/govmomi#1423]
We have a sample SoapUI project for testing commands against the vsphere SDK. When i point it at VCSIM it gives out about namespace incorrectly used in the response in the following instance. 

[response.log](https://github.com/vmware/govmomi/files/3017794/response.log)
[request.log](https://github.com/vmware/govmomi/files/3017796/request.log)

where it returns "XMLSchema-instance:type" instead of "xsi:type" where the namespace has been defined as xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance

**Comment by dougm** [comment]
Haven't had a chance yet to look at this.  Is there something I can use to reproduce the issue?

**Comment by fergalkeating** [comment]
This error seems to be due to SOAP UI incorrectly reporting a namespace issue. I can confirm it works correctly with our application. Closing issue.
