### ISSUE TITLE
The request refers to an unexpected or unknown type. when trying to change Security.AccountLockFailures

### ISSUE THREAD

**Issue by rmawhinnie** [vmware/govmomi#1424]
➜  govc govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.5.0
Build:        7515524
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.5
Product ID:   vpx
UUID:         []
➜  govc govc host.option.ls -host.dns=${ESXi} Security.AccountLockFailures
Security.AccountLockFailures:  5
➜  govc govc host.option.set -host.dns=${ESXi} Security.AccountLockFailures 3
govc: ServerFaultCode: The request refers to an unexpected or unknown type.

**Comment by dougm** [comment]
@rmawhinnie #1425 fixes this
