### ISSUE TITLE
Using govc to deploy OVA Image

### ISSUE THREAD

**Issue by gsexton** [vmware/govmomi#1426]
We're running into problems using ovftool to deploy iso images and I was wondering if I could have better luck using govc. The issue we're hitting with ovftool is network timeouts. We have a jenkins server running in the US, trying to deploy an OVA Image to a VCenter in Europe. The OVA is roughly 2.5GB. OVFTool is erroring out transferring the image to the VCenter server.

Right now the data-flow seems to be:  1) ovftool reads image from HTTP server, 2) ovftool pushes image to VCENTER server. Caching the image in Europe would just add another leg.

If I use govc, can the dataflow be: 1) govc tells vcenter to deploy the image, 2) vcenter pulls the image from http server. If I can do this, then I could cache my image in Europe and a lot of my problems (and bandwidth usage) would go away.

Any ideas or information is appreciated. Thanks.

**Comment by dougm** [comment]
Is the iso image generated by the CI build or just used to test build artifacts?

Have you looked at using a Content Library?  Not sure it would help this case, depends if the OVA image needs to be updated with every Jenkins build or not.

**Comment by gsexton** [comment]
I would be willing to try that. Are there any examples that show creating the command line for ovftool?

**Comment by gsexton** [comment]
@dougm I've created a content library and put a .ova image into it. I tried using 

govc datastore.ls -ds=storename | grep -ie content

it finds "contentlib<someguid>".

I tried doing:

govc datastore.ls -ds=storename /contentlib<someguid>/*

but it doesn't show any files.

Can you give me an idea of how I would reference the stored images? Also, I notice that in the vcenter web gui, my files don't show in "templates", but show as "other files".

Can you give me any hints on how to construct my ovftool source that references this content library?
