### ISSUE TITLE
Setting VIrtualMachine NIC PortGroup

### ISSUE THREAD

**Issue by donwlewis** [vmware/govmomi#1427]
I can't seem to find out how you would configure a VM to use a specific port group.  I have been able to create the `VirtualMachineCloneSpec{}` struct that will configure the cloned virtual machine properly, minus the portgroup.  How can this be accomplished?  Thanks.

**Comment by dougm** [comment]
You'll need to create or edit a `VirtualEthernetCard` device.  For example, `govc vm.network.change`: https://github.com/vmware/govmomi/blob/d3ffbeb9b353264f565a7169f667ac15c49e9855/govc/vm/network/change.go#L106-L113

Using `Finder` to lookup the PG will return type `object.NetworkReference`, where you can use its `EthernetCardBackingInfo` method to construct the device backing:
https://github.com/vmware/govmomi/blob/d3ffbeb9b353264f565a7169f667ac15c49e9855/govc/flags/network.go#L109-L119

**Comment by donwlewis** [comment]
Thanks @dougm for point me in the right direction.
