### ISSUE TITLE
govc vm.info response - add cluster,network and storage info

### ISSUE THREAD

**Issue by hlima** [vmware/govmomi#1428]
When looking at a VM using the vcenter web client there are a couple of additional info  listed under a section named "Related Object". They are:
  - cluster
  - networks
  - storage
I could not find an easy way to get that vm information using govc.
PowerCLI does have an easy way to find the additional information:
   cluster : Get-Cluster -VM $name
   storage : Get-DataStoreCluster -VM $name
   nework : Get-NetworkAdapter -VM $name
So, this is a request to either add the related objects to the json vm.info response or provide an easy command to retrieve it (like we have using powercli)

**Comment by dougm** [comment]
The vm.info `-r` flag includes network and storage info.  We could add cluster info.  You can also get the cluster inventory path for a VM using:

```console
% govc object.collect -s $(govc object.collect -s $vm resourcePool) owner | xargs govc ls -L                                                                                                                                       
/DC0/host/DC0_C0
```
