### ISSUE TITLE
Expand Finder to leverage tags to search for Objects

### ISSUE THREAD

**Issue by donwlewis** [vmware/govmomi#1429]
Maybe the functionality is there, but combing through the code, I can't see how it would be done.  Could `finder` be leveraged to find objects based on tags?  Thinking this would be helpful so that you could find cluster/network/datastore resources based on a given set of tags.

**Comment by dougm** [comment]
You can use this method to get object references with a tagID: https://godoc.org/github.com/vmware/govmomi/vapi/tags#Manager.ListAttachedObjects

Then use `object.NewReference` or one of the type specific methods (e.g. `object.NewDatastore`) to use the same types that Finder returns.

**Comment by donwlewis** [comment]
This seems to work pretty nicely.  The only thing is that it seems the function only takes in a string at this time.  At some point, would it make sense to pass in a slice for strings?  If you want to filter based on multiple tags.

**Comment by dougm** [comment]
Yes, we can adjust it to use this API instead: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/cis/tagging/tag_association.list_attached_objects_on_tags-operation.html
