### ISSUE TITLE
Writing metadata to template

### ISSUE THREAD

**Issue by grahamnicholls** [vmware/govmomi#1430]
I'm using packer (with the jetbrains vmware-iso plugin) to create a VM, then turn it into a template.
Once packer is finished, I have a template; I'm trying to use govc to write to the "notes" field, using vm.change as so:

```
 govc vm.change -annotation="Created by Bamboo/packer on $(date)" -vm="${existing_vm}"
```

The command  produces the error:

`govc: The operation is not supported on the object.`

Yet you can add a note to a template through the GUI.  Is this not supported by govc?
I can convert the template to a VM, apply the change, and convert back to a template, which I believe is working (I need to check), but that seems unclean, TBH.

**Comment by grahamnicholls** [comment]
Another example:
```
govc vm.change -annotation="test message" -vm=$(govc ls  vm/XGP/Templates/Unix/RHEL7.6_ADC_0.1)
govc: The operation is not supported on the object.
```
and to show the context:
```
#govc ls -l vm/XGP/Templates/Unix/RHEL7.6_KDC_0.1
/aabbcc003/vm/XGP/Templates/Unix/RHEL7.6_KDC_0.1 (VirtualMachine)
```

**Comment by dougm** [comment]
@grahamnicholls thanks for the report, that's a bug, see #1431 for the fix.
