### ISSUE TITLE
govc: "host.vnic.info -json" doesn't output JSON

### ISSUE THREAD

**Issue by radeksimko** [vmware/govmomi#1434]
Version: v0.20.0

```
# ./govc host.vnic.info -json
```
```
Device:            vmk0
Network label:     Management Network
Switch:            vSwitch0
IP address:        <REDACTED>
TCP/IP stack:      defaultTcpipStack
Enabled services:  management
Device:            vmk1
Network label:     Private Network
Switch:            vSwitch0
IP address:        <REDACTED>
TCP/IP stack:      defaultTcpipStack
Enabled services:
```

**Comment by aanderse** [comment]
Further to this `snapshot.tree` does not list json output either:

```
govc snapshot.tree -vm VMNAME -json
5-14-2019, 7:58:59 AM
.
```

Also running version 0.20.0.

**Comment by dougm** [comment]
The `-json` flag ends up getting added to any command that has a `-dc` flag, since it's included here: https://github.com/vmware/govmomi/blob/8a6c353b0a381d997d6567d88749d28a57d56061/govc/flags/datacenter.go#L34

We can add the support to json commands for these commands, it just isn't implemented at the moment.

**Comment by aanderse** [comment]
Thanks for following up @dougm. I appreciate your time and effort.

I've just started using `govc` so I'm not exactly sure what to expect from output when specifying `-json`, but using the `-dc` flag still doesn't seem to give me any json:

```
~> govc snapshot.create -vm=aradev9 -m=false -q=true -d="test snapshot" test1
~> govc snapshot.tree -vm=aradev9 -dc Stiller
test1
.
~> govc snapshot.tree -vm=aradev9 -dc Stiller -json
test1
.
```

Anything obvious jump out as wrong in what I'm doing?

**Comment by dougm** [comment]
Specifying `-dc` won't help.  The problem is the `DatacenterFlag` that defines `-dc` also includes `OutputFlag` which defines `-json`, so it shows up in the help text.  But not all commands pay attention if json is set and always output the same format.

**Comment by aanderse** [comment]
@dougm Ah I'm sorry i misunderstood your original reply. Reading it again I understand now. Is there a roadmap on which might include when json output might be implemented for commands which it currently isn't... or just as people get around to it?

**Comment by dougm** [comment]
@aanderse can you open a separate issue for vm.snapshot json support?
