### ISSUE TITLE
VirtualDeviceList.CreateSerialPort fails

### ISSUE THREAD

**Issue by sflxn** [vmware/govmomi#1435]
VirtualDeviceList.CreateSerialPort() fails because VirtualDeviceList.PickController() returns nil for types.VirtualSIOController.

**Comment by dougm** [comment]
Should just need to add an SIO controller like so:

```go
c := &types.VirtualSIOController{}
c.Key = list.NewKey()
devices = append(devices, c)
```

Similar to:

https://github.com/vmware/govmomi/blob/606c1536dd62299ff2bec378e08ecf4dfdc6bf22/object/virtual_device_list.go#L200-L201
