### ISSUE TITLE
Issue Setting ComputerName in types.CustomizationUserData

### ISSUE THREAD

**Issue by donwlewis** [vmware/govmomi#1436]
I am trying to figure out how to build out the struct for a windows customization struct.  I have gotten to this point:

```go
Identity: &types.CustomizationSysprep{
	GuiUnattended: types.CustomizationGuiUnattended{
		AutoLogon:      true,
		AutoLogonCount: 1,
		TimeZone:       -2147483568,
	},
	Identification: types.CustomizationIdentification{
		JoinWorkgroup: "WORKGROUP",
	},
	UserData: types.CustomizationUserData{
		FullName:     "Company",
		OrgName:      "Org",
		ComputerName: (types.BaseCustomizationName).GetCustomizationName(),
	},
},
```

I am getting the following error message when trying this for the ComputerName:

```
not enough arguments in call to method expression types.BaseCustomizationName.GetCustomizationName
	have ()
	want (types.BaseCustomizationName)
```

I am not understanding how the dynamic data is generated here.  Looking for some guidance on how this would be done.  Thanks.

**Comment by dougm** [comment]
Looks like `ComputerName` needs to be one of:

> CustomizationCustomName, CustomizationFixedName, CustomizationPrefixName, CustomizationUnknownName, CustomizationVirtualMachineName

https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.customization.NameGenerator.html

For example:
```go
&types.CustomizationFixedName{Name: "foo"}
```

**Comment by donwlewis** [comment]
Ah thanks!  That was the information that I needed!
