### ISSUE TITLE
Is it possible to mockup vSan service using simulator

### ISSUE THREAD

**Issue by YuxinZhou** [vmware/govmomi#1440]
I would like to use the simulator to write some testing codes. In my code, I was creating a vSAN client:
```go
	vsanNamespace           = "vsan"
	vsanPath                = "/vsanHealth"
	// 'client' is a vim client. Creating a soap client from a vim client.
        vsanClient := client.NewServiceClient(vsanPath, vsanNamespace)
	vsanClient.RoundTrip(ctx, &req, &res)
```
My question is, are there any ways to create a vSAN service using the simulator so that I can test the above code?  Thank you in advance.

**Comment by dougm** [comment]
It is possible, for example see the pbm simulator that lives in its own package: https://github.com/vmware/govmomi/blob/master/pbm/simulator/simulator.go

Then plugs in like so: https://github.com/vmware/govmomi/blob/088b8fb881648af161312ad70dffd09145d3b7a9/vcsim/main.go#L188-L189

**Comment by YuxinZhou** [comment]
Thank you. It helps a lot.
