### ISSUE TITLE
Any API delete datastores in host or datacentre 

### ISSUE THREAD

**Issue by safeerthink** [vmware/govmomi#1443]

**Comment by dougm** [comment]
`Destroy_Task` https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.ManagedEntity.html#destroy

**Comment by safeerthink** [comment]
Thank you for response. Any Golan sample code to implementing this

**Comment by dougm** [comment]
If you're using Finder to lookup inventory objects, just call the `Destroy` method.  Or if you just have a `types.ManagedObjectReference`: https://github.com/vmware/govmomi/blob/fc3f0e9d2275df0e497a80917807a7c72d3c35bc/govc/object/destroy.go#L76-L86
