### ISSUE TITLE
how to get vmdisk size which assigned to Virtual Machine

### ISSUE THREAD

**Issue by happyalexkg** [vmware/govmomi#1446]
Hello
Can please tell .. how to get size of VirtualDisk which assigned to VirtualMachine ?

Thx

**Comment by dougm** [comment]
```console
% govc device.info -vm $vm disk-*
Name:           disk-200-0
  Type:         VirtualDisk
  Label:        Hard disk 1
  Summary:      30,720 KB
  ...

% govc device.info -json -vm $vm disk-* | jq .Devices[].CapacityInKB
30720
```

**Comment by happyalexkg** [comment]
Thx.. and can you tell how to do this from golang

**Comment by dougm** [comment]
```go
	devices, err := vm.Device(ctx) // vm is type *object.VirtualMachine
	if err != nil {
		return err
	}

	for _, device := range devices {
		if disk, ok := device.(*types.VirtualDisk); ok {
			log.Printf("size=%d", disk.CapacityInKB)
		}
	}
```

**Comment by happyalexkg** [comment]
Thx you 
Big Thx

**Comment by happyalexkg** [comment]
is it correct

type VirtualDeviceList []types.BaseVirtualDevice

func (v *Vmware) ListVDisk(c *govmomi.Client)  {
	ctx := context.Background()

    var vmvd object.VirtualMachine

	devices, err := vmvd.Device(ctx) // vm is type *object.VirtualMachine
	if err != nil {
		fmt.Println("opsss wotj vmvd")
		os.Exit(3)
	}
	for _, device := range devices {
		if disk, ok := device.(*types.VirtualDisk); ok {
			log.Printf("size=%d", disk.CapacityInKB)
		}
	}
}
