### ISSUE TITLE
Grab Events for an Object

### ISSUE THREAD

**Issue by donwlewis** [vmware/govmomi#1451]
I am looking for a way of grabbing the events for an object.  Specifically, we want to be able to get a newly cloned virtual machine, and get the status of the customization spec process (whether it passes or fails).  I am looking at the [Events](https://godoc.org/github.com/vmware/govmomi/event#Manager.Events) function, but it doesn't really seem to work as I expected, and the documentation is a little lacking on how to use it.  Also [the following line](https://github.com/vmware/govmomi/blob/445ddf569fe7c9f37530279041a950b16b7e38f0/event/manager.go#L175) indicates that it is probably not something that is ready to be used.  Is there another way of trying to accomplish this task?  Thanks.

**Comment by dougm** [comment]
Do you see the data you're looking for with `govc events` or `govc tasks`?  The Events function get heavy use in other projects and works well.  The comment is just referring to the method signature itself - where it would be cleaner to use a single config struct instead of N params.

**Comment by donwlewis** [comment]
Here is the code that I setup to test this out:

```go
tmplt, err := finder.VirtualMachine(ctx, "name")
if err != nil {
	log.Fatalln(err)
}
var vmRefs []types.ManagedObjectReference
vmRef := tmplt.Reference()
vmRefs = append(vmRefs, vmRef)
em := event.NewManager(vmc.Client)
fmt.Println(vmRefs)
f := func(mo types.ManagedObjectReference, be []types.BaseEvent) error {
	fmt.Printf("Events for %v\n", mo)
    for _, e := range be {
		fmt.Println(e)
	}
	return nil
}

em.Events(ctx, vmRefs, 10, false, false, f, "info")
```

I would expect something to spit out in the console, but nothing seems to pop out.  It's probably just lack of understanding how the function works, so any guidance would be appreciated.

**Comment by dougm** [comment]
Omit the `"info"` param:
```go
em.Events(ctx, vmRefs, 10, false, false, f)
```

If you did want to filter, the kind params need to be event types (e.g. `VmPoweredOnEvent`): https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.event.Event.html

And what about:
> Do you see the data you're looking for with govc events or govc tasks

**Comment by donwlewis** [comment]
I was able to get this to work.  I am not leveraging the `govc` command, but just leveraging the method in my own code.  One thing I have noticed though is if my function that I pass to the `Event()` method returns an error, the whole thing just seems to hang.  The function seems to be able to return an error but is that not actually implemented?  I looked at the function that is called from within, ` newEventProcesso()`, don't see that that actually returns anything.

**Comment by donwlewis** [comment]
Nvm.  I figured out a way to handle it.

**Comment by dougm** [comment]
@donwlewis right, I was just asking about govc events/tasks as the data you were looking for may have been the related tasks (which have progress you can track) or events (which do not have a progress field).

As for `Events` not returned when your callback returns an error, I see that's because of this: https://github.com/vmware/govmomi/blob/8a6c353b0a381d997d6567d88749d28a57d56061/event/processor.go#L127-L129

The error is not propagated, and by returning false the loop goes back into the Wait call.
Not sure if this is something that was by design or we should change to propagate error.
Maybe @cgtexmex or @hmahmood can recall.
