### ISSUE TITLE
Virtual machine hardware devices all have fixed keys, right? For example, virtual hard disk, the key of the first hard disk is 2000, the key of the second hard disk is 2001, and so on

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1454]
Virtual machine hardware devices all have fixed keys, right? For example, virtual hard disk, the key of the first hard disk is 2000, the key of the second hard disk is 2001, and so on

**Comment by dougm** [comment]
They are only documented to be unique.  The order and offset may differ.
 
https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.device.VirtualDevice.html
