### ISSUE TITLE
Performance Metrics Get Number of Queries

### ISSUE THREAD

**Issue by fdmsantos** [vmware/govmomi#1456]
I'm retrieving performance metrics via govmomi.

For some resource pools, clusters and datastores i'm getting the following error:
```
ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'. Contact your system administrator.
```
It is not possible for us, increase vpxd.stats.maxQueryMetrics more than 254.

So the idea is instead one query with all metrics, divide in several queries.
Is possible know how many queries will result the method QueryPerf before execute?

This is my code:
```
startTime := time.Now().Add(-30*time.Minute)  
perfReq := types.QueryAvailablePerfMetric{
    This:       *v.Client().ServiceContent.PerfManager,
    Entity:     object.Reference(),
    BeginTime:  &startTime,
    IntervalId: 300,
}
perfRes, err := methods.QueryAvailablePerfMetric(ctx, v.Client().RoundTripper, &perfReq )
if err != nil {
    fmt.Println(err)
}
metricsSpec := []types.PerfQuerySpec{{
    Entity: object.Reference(),
    MetricId: perfRes.Returnval,
    StartTime: &startTime,
    IntervalId: 300,
},
}
perfQueryReq := types.QueryPerf{
    This: *v.Client().ServiceContent.PerfManager,
    QuerySpec: metricsSpec,
}
perfQueryRes, err := methods.QueryPerf(ctx, v.Client().RoundTripper, &perfQueryReq )
if err != nil {
    fmt.Println(err)
}
```

**Comment by dougm** [comment]
I don't know, but you may want to try using `maxSample` https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.PerformanceManager.QuerySpec.html

You may also be interested in using govmomi's `performance.Manager` helpers https://github.com/vmware/govmomi/blob/master/performance/manager.go#L58
Examples: https://github.com/vmware/govmomi/tree/master/govc/metric

**Comment by fdmsantos** [comment]
Hi @dougm ,

Thanks for the answer.

I have identified one perfcounter in the resource pools which i get the error.

```
$ /govc metric.sample -n=1 "/LAB/host/Test/Resources" mem.overhead.average
/govc: ServerFaultCode: This operation is restricted by the administrator - 'vpxd.stats.maxQueryMetrics'. Contact your system administrator.`
```

I tried with only one sample, but whitout success. Any ideas? There is a way to solve this whitout change vpxd.stats.maxQueryMetrics config setting?
