### ISSUE TITLE
Relate Virtual Disk with SCSI Devices

### ISSUE THREAD

**Issue by fdmsantos** [vmware/govmomi#1457]
I need relate the virtual disk with SCSI controller.

Something like:

![screenshot 1](https://user-images.githubusercontent.com/25988026/57935017-bf481a80-78b8-11e9-836b-88fb8c56cd01.jpg)

This is my code to get the Virtual Disks:

```
for _, vm := range vms {
  for _, device := range vm.Config.Hardware.Device {

    switch device.(type) {
    case *types.VirtualDisk:
      fmt.Println(device.GetVirtualDevice().DeviceInfo.GetDescription().Label)
    }

  }
}
```

**Comment by dougm** [comment]
```go
	devices, err := vm.Device(ctx)
	if err != nil {
		return err
	}
	for _, device := range devices {
		disk, ok := device.(*types.VirtualDisk)
		if !ok {
			continue
		}
		c := devices.FindByKey(disk.ControllerKey)
		if scsi, ok := c.(types.BaseVirtualSCSIController); ok {
			log.Printf("scsi%d:%d", scsi.GetVirtualSCSIController().BusNumber, *disk.UnitNumber)
		}
	}
```

**Comment by fdmsantos** [comment]
Hi @dougm ,

Tks for the reply.
I need a little help.
Your code use object.Virtualmachine, but all my code use vim25/mo.VirtualMachine

```go
m := view.NewManager(client.Client)
v, err := m.CreateContainerView(ctx, client.ServiceContent.RootFolder, []string{"VirtualMachine"}, true)
if err != nil {
	log.Fatal(err)
}
defer v.Destroy(ctx)
var vms []mo.VirtualMachine
err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"config"}, &vms)
```
Is possible get object.Virtualmachine through mo.Virtualmachine?
Or other way to get VirtualDeviceList struct with mo.VirtualMacinhe to call FindByKey method?

We have a lots code written with mo.VirtualMachine in production, and we want add this relantionship beetween disks and SCSI Devices. So is really better for us, find a solution where mo.VirtualMachine is the starting point.

Thanks for your help.

**Comment by dougm** [comment]
Have a look at the `Device` method, it uses `mo.VirtualMachine` underneath, the last line is all you need: https://github.com/vmware/govmomi/blob/8a6c353b0a381d997d6567d88749d28a57d56061/object/virtual_machine.go#L363

**Comment by fdmsantos** [comment]
Many Thanks @dougm
