### ISSUE TITLE
Override portgroup failover order

### ISSUE THREAD

**Issue by vfiftyfive** [vmware/govmomi#1459]
Hi,

I couldn't manage to find a way with govc to set the failover order for a particular portgroup (override), for example when using multiple LAGs.
If it is not currently possible, could we add it as an enhancement?

N.

**Comment by dougm** [comment]
We can add it.  Can you provide some input/output examples, such as pointers to UI screenshot and/or PowerCLI commands that do what you need?

**Comment by vfiftyfive** [comment]
Example of overriding portgroup configuration:
![image](https://user-images.githubusercontent.com/7715763/58361471-e4520580-7e43-11e9-84c2-c6dc6a86c675.png)

The screenshot shows a lag uplink as active, some other uplinks as standby and others as unused.
This is what should be configurable using Govc.

Nicolas

**Comment by dougm** [comment]
I started on this, along with a `dvs.portgroup.summary` command that shows the data in your screenshot.  I'll come back to it, still want to add vcsim support and tests.  Branch is here if you want to try it out: https://github.com/vmware/govmomi/compare/master...dougm:pg-settings
