### ISSUE TITLE
近期任务怎么看进度条     What do you think of the progress bar for recent tasks

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1460]
![image](https://user-images.githubusercontent.com/38032852/58010174-7c897b00-7b22-11e9-9dd5-029552f96a96.png)

**Comment by dougm** [comment]
The vim25/progress package only supports a single item.  But there are third-party progress bars that support multiple.  It would be a nice feature for tasks.

**Comment by dougm** [comment]
Not planning to implement this or take on a console UI dependency.  The text output of `govc tasks` command will suffice.
