### ISSUE TITLE
Unable to change mac address for an interface

### ISSUE THREAD

**Issue by grahamnicholls** [vmware/govmomi#1468]
govc vm.network.change -net.address 00:50:56:a4:2f:99 -vm=$(govc ls vm/Templates/Unix/rhel7.6_0.1_20191441304) -net vxw-InfraS-Unix1_10.2.50.0%2f24 ethernet-0

returns:
govc: The operation is not supported on the object.

I understand that I have to specify the network with "-net ...", from an earlier issue, but I'm unable to get this to work; it's necessary so that spoofguard will not notice that we're reusing the IP address - we fool it by reusing the same mac address as well.

**Comment by grahamnicholls** [comment]
#govc device.info -vm=$(govc ls vm/Templates/Unix/rhel7.6_0.1_20191441304) ethernet-0
Name:               ethernet-0
  Type:             VirtualVmxnet3
  Label:            Network adapter 1
  Summary:          DVSwitch: 50 24 34 11 b3 ec 4f 73-8f 40 51 1b 89 e1 78 ad
  Key:              4000
  Controller:       pci-100
  Unit number:      7
  Connected:        false
  Start connected:  true
  Guest control:    true
  Status:           untried
  MAC Address:      00:50:56:a4:2f:86
  Address type:     assigned
#

**Comment by grahamnicholls** [comment]
And some more info (stripped of any identifying info):
#govc vm.info  -r $(govc ls vm/Templates/Unix/rhel7.6_0.1_20191441304)
Name:                   rhel7.6_0.1_20191441304
  Path:                 /path011/vm/Templates/Unix/rhel7.6_0.1_20191441304
  UUID:                 4224e883-5fcf-afc6-f0c8-329b17f41d19
  Guest name:           Red Hat Enterprise Linux 7 (64-bit)
  Memory:               4096MB
  CPU:                  2 vCPU(s)
  Power state:          poweredOff
  Boot time:            2019-05-24 13:11:50.776257 +0000 UTC
  IP address:
  Host:                 hostname.mqg.hpe
  CPU usage:            0MHz
  Host memory usage:    0MB
  Guest memory usage:   0MB
  Storage uncommitted:  64.2GB
  Storage committed:    10.3KB
  Storage unshared:     0B
  Storage:              datadtore_info
  Network:              vxw-InfraS-Unix1_10.252.150.0%2f24

**Comment by dougm** [comment]
@grahamnicholls `.../Templates`, is this VM marked as a template?  If so, vCenter will not let you change the MAC address.  However, you could `vm.markasvm`, change the MAC, then `vm.markastemplate`.

**Comment by grahamnicholls** [comment]
Thanks, I'll give that a try and update.  I suspect that my error may be that the VM is still powered on.

**Comment by dougm** [comment]
@grahamnicholls any update?

**Comment by dougm** [comment]
Feel free to re-open if this is still an issue.

**Comment by grahamnicholls** [comment]
Thanks, and apologies for not responding sooner.  If I recall correctly, it _was_ a template.  Thanks again.
