### ISSUE TITLE
Unable to clone VM with cm.clone

### ISSUE THREAD

**Issue by maxspb89** [vmware/govmomi#1469]
I have ESXI 6.7 (evaluation mode license) installed and a virtual machine "freebsd12" that I want to clone. I'm getting "operation is not supported" error.
```
./govc vm.clone -u user:password@192.168.0.110 -debug -k -vm freebsd12 freebsd12_clone 
[26-05-19 16:41:21] Cloning /ha-datacenter/vm/freebsd12 to freebsd12_clone...Error: The operation is not supported on the object.
./govc: The operation is not supported on the object.
```

What are the possible paths for solving the problem?

**Comment by dougm** [comment]
ESXi does not support the `CloneVM` method, regardless of license.  Only supported by vCenter.

**Comment by dougm** [comment]
Assuming you moved to vCenter based on #1478
