### ISSUE TITLE
vcsim creates only Local datastore by default

### ISSUE THREAD

**Issue by suhassankyaan** [vmware/govmomi#1471]
vcsim creates only local datastore by default and it hard codes the individual object path as LocalDS_0 while creating the model object. I could see there is a remote datastore support (createNasDataStore) , then why not allow user an option to create a Remote data store when he starts the simulator?

**Comment by dougm** [comment]
You can use the API to create a remote datastore against vcsim.  We could also add an option to vcsim.. what is the use case?

**Comment by dougm** [comment]
vcsim supports creating a remote datastore type, but it does not connect (e.g. nfs mount), it just uses the given local path.  Is that enough for your case?

**Comment by suhassankyaan** [comment]
Yes that should be enough. I see we have remote path and remote host options for a remote datastore that
is just used as a string but doesn't connect, as long as the responses are similar to the ones in real vCenter we are good.

**Comment by suhassankyaan** [comment]
@dougm can we see this in next release?
Do suggest me quick workaround if any.

**Comment by dougm** [comment]
If you just need a remote datastore type in the mix, you can create them against vcsim using govc or the API from any language.

**Comment by dougm** [comment]
Another option is to use the Record+Playback feature: https://github.com/vmware/govmomi/wiki/vcsim-features#record-and-playback
