### ISSUE TITLE
govc: invalid URL escape when including special charactor in password 

### ISSUE THREAD

**Issue by jiajliu** [vmware/govmomi#1475]
Run "govc about -u user:pass@server" with special charator in passwd. It can not connect to server.
govc: invalid value "user:pass@server" for flag -u: parse https://user:pass@server: invalid URL escape "%Ah"
How to deal with it?

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/blob/master/govc/README.md#usage

**Comment by jiajliu** [comment]
yeah, it works, thx
