### ISSUE TITLE
x509: certificate signed by unknown authority (even with "-k=false")

### ISSUE THREAD

**Issue by pillarsdotnet** [vmware/govmomi#1476]
Operating-system: Centos Linux 7 (core)
Environment: VMware vSphere 6.5.0 build 10964411
govc version: 0.20.0
release: 0.20.0 and source (both behave identically)

What I did:  `govc datastore.ls -u=https://CUSPVMWCEN01.INTERNAL.CNNGAD.COM/ -k=false`

What I expected: A list of datastore objects

What happened: `govc: Post https://CUSPVMWCEN01.INTERNAL.CNNGAD.COM/: x509: certificate signed by unknown authority`

**Comment by dougm** [comment]
`-k=false` is the default.  Sounds like you want to use `-k` or `-k=true`

**Comment by pillarsdotnet** [comment]
Thanks; the [USAGE.md](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md) says:
> `-k=false                  Skip verification of server certificate [GOVC_INSECURE]`
which I naively took to mean that the `-k=false` option means `Skip verification of server certificate`.

I now understand that the left column describes the defaults, while the right column describes the effect of deviating from the defaults.

I may submit a PR to clarify the wording once I understand the intent.

I have also discovered by trial-and-error, that:

* I must include the vmware username and password in the url.
* I must specify the datastore name.
* The url must include a trailing `/sdk`

So my corrected command would be `govc datastore.ls -k -ds=DatastoreName -u=https://username:password@servername/sdk`

Again, I will submit documentation clarifications when I have sufficient time and expertise to do so.

**Comment by dougm** [comment]
Right, that's the generated help output from Go's flag package.  PRs to add clarity are welcome, in this case you'd need to add it to this section in the script that generates USAGE.md: https://github.com/vmware/govmomi/blob/161c00c4e1b075c0986991eb5085109d2a5f6baf/govc/usage.sh#L34-L40

USAGE.md could also point to the README section with info on URL, username, password, etc: https://github.com/vmware/govmomi/tree/master/govc#usage
