### ISSUE TITLE
datastore.disk.info does not give uuid even with -uuid=true

### ISSUE THREAD

**Issue by jsirianni** [vmware/govmomi#1477]
edit: This was mysteriously solved overnight. I believe my environment was at fault. 

Hi, I need to programmatically retrieve the UUID of a disk. I have set my environment:
```
GOVC_INSECURE=1
GOVC_USERNAME=<redacted>
GOVC_PASSWORD=<redacted>
GOVC_DATACENTER=<redacted>
GOVC_URL=<redacted>
```

My command: 
```
govc datastore.disk.info -ds=emc-prod-4 -uuid=true packer-rhel-8-template/packer-rhel-8-template.vmdk
```
```
Name:      packer-rhel-8-template/packer-rhel-8-template.vmdk
  UUID:
  Type:    thin
  Parent:
```

As you can see, UUID is blank even though the `vmtx` file contains a UUID. 

Other commands work, such as ```govc vm.info -vm.ipath=<redacted>/packer-rhel-8-template```
```
Name:           packer-rhel-8-template
  Path:        <redacted>/packer-rhel-8-template
  UUID:         421f1c79-83cd-e598-121e-f4cf341e09dc
  Guest name:   Other Linux (64-bit)
  Memory:       1024MB
  CPU:          1 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         <redacted>
```

I have tried release 0.20 and 0.19. Is this expected behavior?

**Comment by jsirianni** [comment]
I have tried this, and it does not appear to change the behavior.

**Comment by dougm** [comment]
I think the other catch is the vm needs to be powered off before setting the property, or at least power cycled after setting it.

**Comment by jsirianni** [comment]
Powering on / off and moving to other datastores does not appear to help.

**Comment by dougm** [comment]
Not sure what the issue is, but the uuid displayed by `govc datastore.disk.info` would be the same as the `ddb.uuid` in the vmdk descriptor.  For example:

```console
% govc datastore.download dougm-vcsa/dougm-vcsa_1.vmdk - | grep ddb.uuid
ddb.uuid = "60 00 C2 9a d0 42 9b 04-8b cc ca 3b 53 2e dd 09"

% govc datastore.disk.info -uuid dougm-vcsa/dougm-vcsa_1.vmdk
Name:      dougm-vcsa/dougm-vcsa_1.vmdk
  UUID:    60 00 C2 9a d0 42 9b 04-8b cc ca 3b 53 2e dd 09
  Type:    thin
  Parent:
```

Can you share `govc vm.info -json` for this vm?

**Comment by jsirianni** [comment]
I am not sure what the problem is either, but I am not confident that it is an environment issue on my end. This morning, everything is suddenly working. 

I will edit my original post.
