### ISSUE TITLE
Add support to create/list sso groups and add sso users to the existing groups

### ISSUE THREAD

**Issue by apalcloud** [vmware/govmomi#1483]
To use govc to manage sso user/groups, we want something like this:
sso.group.ls
sso.group.create
sso.group.rm
sso.group.update  //which will add user to the existing groups
sso.group.permission.set //this may be already available by sso.permission.set, just double check

cc @dougm and thanks a lot!

**Comment by dougm** [comment]
You mentioned using dir-cli for these, could you include some examples of the dir-cli usage?  Haven't used them myself for groups, so it'd help with getting the govc commands going.

**Comment by apalcloud** [comment]
@dougm You can do something like this in dir-cli, which is running from the vCenter server:
dir-cli group modify --name Administrators --add %s --login %s --password %s

**Comment by apalcloud** [comment]
Could you please estimate a time frame to add the group mgmt cli? @dougm 
We'll determine if we choose other tools or not for the vCenter groups case.
Thanks a lot!

**Comment by dougm** [comment]
I'd still like to understand why roles can't be used instead of groups.  For example, adding a user to a role: `govc permissions.set -principal username -role Admin`

Can you explain the use case of using groups vs roles?

**Comment by AndrewDi** [comment]
Here is our usage，We create a group with ten person account, and assign this group to a role, after that I just need to mantance user-group mapping.

**Comment by dougm** [comment]
ok, makes sense.  Sure, we can add this to govc.  Still would help to have the complete set of dir-cli examples that would map to ls, create, rm, etc., above only has the update example.

**Comment by apalcloud** [comment]
@dougm what @AndrewDi mentioned is exactly the case we're working on too. Some system is designed to perform RBAC through group/role mapping. Here're the dir-cli examples:
https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.security.doc/GUID-4FBEA58E-9492-409B-B584-C18477F041D8.html
- dir-cli ssogroup create
- dir-cli group modify
- dir-cli group list
