### ISSUE TITLE
Changing hotplug for vcpu or memory does not work

### ISSUE THREAD

**Issue by henrik-farre** [vmware/govmomi#1485]
`govc version`: 0.20.0
vSphere Client version 6.7.0.20000
Hypervisor: VMware ESXi, 6.7.0, 10302608

I want to disable vcpu and memory hotplug in a vm using:

`govc vm.change -vm myvm -e vcpu.hotadd=false -e mem.hotadd=true` (tried different combinations, i.e. only changing mem, only changing vcpu)

But nothing changes:

`govc object.collect -s /myfolder/myvm config.cpuHotAddEnabled` returns true (also for mem).

I can change the setting using the vSphere GUI, or using Ansible.

This screenshot shows the events in vSphere when using `govc`:
![govc](https://user-images.githubusercontent.com/718278/59020383-29b20200-884a-11e9-9c57-ed1f4be88883.png)

*Note*: "Modified" is blank

This screenshot shows the events in vSphere when using Ansible:
![ansible](https://user-images.githubusercontent.com/718278/59020412-3f272c00-884a-11e9-8a1f-7c727e636e88.png)

Here "Modified" shows: "config.cpuHotAddEnabled: true -> false;"

**Comment by dougm** [comment]
@angystardust do you know of any caveats with using these properties?

@henrik-farre any pointers to the ansible code?  Wondering if its using the same properties or something else.

**Comment by angystardust** [comment]
Hi @henrik-farre is the vm turned on when you're changing those settings?

**Comment by henrik-farre** [comment]
> @henrik-farre any pointers to the ansible code? Wondering if its using the same properties or something else.

I think it is done somewhere around here: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1012 but I'm not sure that will help you :)

**Comment by henrik-farre** [comment]
> Hi @henrik-farre is the vm turned on when you're changing those settings?

@angystardust : It is powered off

**Comment by angystardust** [comment]
Ah ok...that's right: sorry for asking you a confirmation about it. 
I've used the _vm.change_ function to turn on the cpu and memory hotplug without issues but sincerely I haven't tried to turn those settings off

**Comment by henrik-farre** [comment]
@angystardust no problem :)

Btw ansible use https://github.com/vmware/pyvmomi to do its thing, not that I understand how that code works.

**Comment by dougm** [comment]
Thanks guys, PR #1486 should as expected.. using the vm config fields as Ansible does, instead of extra_config.  @henrik-farre does this work for you?
