### ISSUE TITLE
govc sso.ls do not support VCSA with external PSC

### ISSUE THREAD

**Issue by AndrewDi** [vmware/govmomi#1490]
When use govc sso.ls on VCSA with external PSC, error 404 will return.

**Comment by AndrewDi** [comment]
@dougm PTAL

**Comment by dougm** [comment]
I don't have an environment setup that way.  Is there anything in your vCenter options that points to a lookup service?
```console
% govc env GOVC_URL
10.0.0.69

% govc option.ls | grep https://
config.vpxd.sso.sts.uri:                                    https://10.0.0.69/sts/STSService/vsphere.local
config.vpxd.sso.groupcheck.uri:                      https://10.0.0.69/sso-adminserver/sdk/vsphere.local
config.vpxd.sso.admin.uri:                               https://10.0.0.69/sso-adminserver/sdk/vsphere.local
VirtualCenter.VimApiUrl:                                  https://10.0.0.69:443/sdk
```

**Comment by AndrewDi** [comment]
@dougm I will take a look at it, and is there any way to change single option in govc? such as change config.vpxd.sso.sts.uri to 10.0.0.70?

**Comment by dougm** [comment]
There is: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#optionset

But I was looking for an option that'll be there by default.  We could also add a flag to the `sso.service.ls` command that lets you specify the lookup service uri.

**Comment by AndrewDi** [comment]
Here is the output and error, please ignore chinese charset mixed.
VMware vCenter Server Appliance 6.5.0.23000

Type: vCenter Server with an external Platform Services Controller

PS C:\vmware> .\govc_windows_386.exe option.ls|findstr https
config.vpxd.sso.sts.uri:                                    https://10.10.9.25/sts/STSService/vsphere.local
config.vpxd.sso.groupcheck.uri:                             https://10.10.9.25/sso-adminserver/sdk/vsphere.local
config.vpxd.sso.admin.uri:                                  https://10.10.9.25/sso-adminserver/sdk/vsphere.local
config.vpxd.rhttpproxy.httpsport:                           443
VirtualCenter.VimApiUrl:                                                    https://vCenterM-APP:443/sdk
WebService.Ports.https:                                                     443
PS C:\vmware> ping vCenterM-APP

ÕýÔÚ Ping vcenterm-app [10.10.9.20] ŸßÓÐ 32 ×ÖœÚµÄÊýŸÝ:
ÀŽ×Ô 10.10.9.20 µÄ»ØžŽ: ×ÖœÚ=32 Ê±Œä<1ms TTL=63
ÀŽ×Ô 10.10.9.20 µÄ»ØžŽ: ×ÖœÚ=32 Ê±Œä<1ms TTL=63

PS C:\vmware> .\govc_windows_386.exe sso.user.ls
C:\vmware\govc_windows_386.exe: 400 Bad Request

**Comment by AndrewDi** [comment]
@dougm It works good.
