### ISSUE TITLE
govc: does not pick up -u option

### ISSUE THREAD

**Issue by AndrewDi** [vmware/govmomi#1493]
Command with `-u` option, it seems like govc will ignore `an ESX or vCenter URL`
./govc_linux_amd64 ls /*/host/* -u https://user:pass@127.0.0.1:8989/sdk -k
./govc_linux_amd64: specify an ESX or vCenter URL

But if I use `export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk `, govc works fine.

**Comment by dougm** [comment]
The flags need to be first: `./govc_linux_amd64 -u https://user:pass@127.0.0.1:8989/sdk -k ls //host/ `

**Comment by AndrewDi** [comment]
Thanks，it‘s gracefully to have a document for govmomi。。。
