### ISSUE TITLE
How can I create a new Host Certificate Manager?

### ISSUE THREAD

**Issue by MarcusTan** [vmware/govmomi#1494]
I am trying to write some go code to install an ssl cert.
I think I should probably be using `InstallServerCertificate` from `host_certificate_manager.go`
In order to call this, I need to create a HostCertificateManager, but I am confused as to how to create it

https://github.com/vmware/govmomi/blob/629af053522fccb5325ae42fb355dc5e10ed47d3/object/host_certificate_manager.go#L35-L41

What should I be putting for `ref` and `host` ? I can't seem to find examples anywhere.

**Comment by dougm** [comment]
You can use https://github.com/vmware/govmomi/blob/629af053522fccb5325ae42fb355dc5e10ed47d3/object/host_config_manager.go#L171

Example in govc's `host.cert.install` command: https://github.com/vmware/govmomi/blob/629af053522fccb5325ae42fb355dc5e10ed47d3/govc/host/cert/install.go#L68

**Comment by dougm** [comment]
Assuming this is enough info, feel free to re-open or discuss on slack.
