### ISSUE TITLE
Is there a plan to create community samples?

### ISSUE THREAD

**Issue by arnmishra** [vmware/govmomi#1497]
Pyvmomi feels much more consumable because of https://github.com/vmware/pyvmomi-community-samples - is there any plan to create something similar to govmomi (or does it already exist somewhere)

**Comment by dougm** [comment]
There are some examples here: https://github.com/vmware/govmomi/tree/master/examples

The govc CLI is another source of examples: https://github.com/vmware/govmomi/tree/master/govc

There are also a few embedded within the godoc, such as for the simulator package: https://godoc.org/github.com/vmware/govmomi/simulator#pkg-examples

**Comment by arnmishra** [comment]
got it, thanks. looks like https://github.com/vmware/govmomi/pull/1498 fixed the issue I was looking for an example for.
