### ISSUE TITLE
Datastore.upload on persistent memory gives 500 internal error when uploading new file

### ISSUE THREAD

**Issue by roland-x83** [vmware/govmomi#1504]
Hi guys, 

On the newest version of Esxi 6.7 I cant upload file biggest than couple of MB's using datastore.upload command on datastore located on persistent memory. Response is 

[21-06-19 12:26:12] Uploading... Error: 500 Internal Server Error
govc: 500 Internal Server Error

Datastore on ssd drive works like a charm.    

Thanks for any suggestion

**Comment by dougm** [comment]
Newest as in the patch that was released yesterday?

Either way, I doubt this is something we can solve on the client side.  Can you reproduce with the H5 UI datastore browser?

**Comment by roland-x83** [comment]
thanks for reply. 

Yes, esxi patched to the last version. PMem datastore is represented in diffrent way in UI. There is no option to browse it, upload file etc. Config file of VM (.vmx etc) still need to be located on standard datastore. Access to this mem is by creating new hard drive, then there is option to select space on persistent memory. I will mention only that datastore.cp work fine, and I can copy files between datastores. Unfortunately-f parameter seems to be not working, and failure on overwriting file.

**Comment by sirzhanghai** [comment]
roland-x83，看得懂中文吗
