### ISSUE TITLE
create vmfs datastore using govc 

### ISSUE THREAD

**Issue by suhassankyaan** [vmware/govmomi#1511]

**Comment by suhassankyaan** [comment]
This is a question rather than a issue.

I wanted to created a vmfs datastore using govc API, and i am facing the below error:

govc datastore.create -type vmfs -name vmfsDatastore -disk=mpx.vmhba1:C0:T0:L0 /DC0/host/DC0_H0

**govc: ServerFaultCode: HostDatastoreSystem:hostdatastoresystem-15 does not implement: QueryAvailableDisksForVmfs**

I understand we need to create a disk/lun prior to this that supports vmfs and then use it to create a datastore. Can you please let me know, what are the steps we need to do before running datastore.create
and how to use the details to create a datastore

**Comment by dougm** [comment]
`/DC0/host/DC0_H0` - are you running this against vcsim?  vcsim indeed does not support that method.

Against a real ESXi host, you can get disk info using: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#hoststorageinfo

**Comment by suhassankyaan** [comment]
Thanks for the info . Yes, i am running against vcsim.

**Comment by dougm** [comment]
Closing as #1525 requests vcsim support
