### ISSUE TITLE
Virtual machine console. I spliced the route, but it didn't work

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1512]
Virtual machine console. I spliced the route, but it didn't work
[401] This request requires HTTP authentication.
Back to login screen
https://192.168.201.211/ui/webconsole.html?vmId=vm-1296&vmName=123&serverGuid=c9b7b2fd-b96a-4972-a460-479bcdd0af79&host=192.168.201.218&sessionTicket=cst-VCT-524c001b-98d0-1e58-d56b-475cc2190e39--tp-2A-30-C3-F9-6D-2B-D2-75-40-AF-CD-54-4C-E9-E5-14-BB-52-7D-23&thumbprint=2A:30:C3:F9:6D:2B:D2:75:40:AF:CD:54:4C:E9:E5:14:BB:52:7D:23&locale=zh-CN

**Comment by dougm** [comment]
You need to login to https://192.168.201.211/ui before using the console link.

**Comment by dougm** [comment]
Did it work for you after logging in?

**Comment by sirzhanghai** [comment]
After logging in, you can use it, because after logging in the browser, it will save the cookie after logging in the browser;What if you don't log in

**Comment by sirzhanghai** [comment]
The actual environment is to consider didn't go to https://192.168.201.211/ui;

**Comment by sirzhanghai** [comment]
The company will develop its own private cloud management platform, and I am responsible for writing background interfaces of vmware.
The secondary packaging is mainly based on govmomi, the official golang interface of vmware.
Html5's console interface for virtual machines
Presentation of html5's virtual machine console
Only applicable to vc, 5. X does not apply to 6. X,6. X has changed the login verification method temporarily not done
The process, which receives the front-end request, finds the corresponding virtual machine, generates the sessionTicket and thumbprint,
Splice the corresponding url and return it as an HttpResponseRedirect
However, accessing the virtual machine console site requires verification
[401] HTTP authentication is required for this request.

**Comment by sirzhanghai** [comment]
I need your help;Thank you very much
https://blog.csdn.net/u012687769/article/details/78594024

**Comment by dougm** [comment]
You may want to research articles to find a method that will work for you, such as: https://www.virtuallyghetto.com/2013/09/how-to-generate-pre-authenticated-html5.html
