### ISSUE TITLE
Reflect values of 'Custom fields' to a Go-like structure. Is it possible?

### ISSUE THREAD

**Issue by sttyru** [vmware/govmomi#1513]
Hello!

How I can to reflect values from 'Custom fields' to the Go-like structure? I mean that I need to get values from 'Custom fields' via keys and put them to prepared Go-like structure for future manipulations.
For an every virtual machine I have next records:
```
Customer: User1
Production: true
Monitoring: false
```
And I want to create an easy Go-like structure (see below) and operate with values from that.
```
type CustomFieldsVM struct {
Customer anonymous_type...
Production bool
Monitoring bool
}
```
Is it possible? Can I ask about a little code? :)

Thank you so much!

**Comment by dougm** [comment]
CustomFieldValue can only be a string: https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.CustomFieldsManager.StringValue.html

However, you could use json encoding for example.

**Comment by sttyru** [comment]
Thank you!

I found the soultion in 'finder.go', but after I'd added some procedures to mine sources **a performance has been degraded.** My solution:
```
   finder := find.NewFinder(ce.Client,false)
    var elements []list.Element
    spew.Dump(elements)
    for _, arg := range vms {
        elements, err := finder.ManagedObjectList(ctx, arg.Summary.Config.Name)
        if err != nil {
            log.Fatal("Finder error")
        }
        spew.Dump(elements)
    }
    for _, e := range elements {
                ref := e.Object.Reference()
                refz = append(refz, ref)
        fmt.Println(ref)
        }
    err = property.DefaultCollector(ce.Client).Retrieve(ctx, refz, []string{"name", "customValue"}, refz)
    if err != nil {
        log.Fatal("Couldn't get custom values")
    }
    for _, obj := range objs {
                for i := range obj.CustomValue {
                        val := obj.CustomValue[i].(*types.CustomFieldStringValue)
            spew.Dump(val)
                        rescf.Info = append(rescf.Info, Info{
                                Object: obj.Self,
                                Path:   paths[obj.Self],
                                Name:   obj.Name,
                                Key:    field.ByKey(val.Key).Name,
                                Value:  val.Value,
                        })
                }
        }
    os.Exit(0)
```
I'd detected that a performance downgrade linked with the call: 'elements, err := finder.ManagedObjectList(ctx, arg.Summary.Config.Name)'. Mine vSphere instance isn't large is an above two hundreds virtual machines and two dozen datastores. A native `govc finder` has been run instantly. Can you help me?
Thank you so much!

**Comment by dougm** [comment]
With `ManagedObjectList` you're searching the entire inventory for every vm in the `vms` list.  Then calling `Retrieve` for each.

Where does `vms` come from?  Do you need `customValue` for just the VirtualMachine type, or other types (such as Datastore) too?

**Comment by sttyru** [comment]
I got a list of virtual machines via the next construction:
```
v, err := m.CreateContainerView(ctx, ce.ServiceContent.RootFolder, []string{"VirtualMachine"}, true)
var vms []mo.VirtualMachine
...
err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms)
```
In a perfect world, I want to collect `customValue` for all types of objects :) (if possible and doesn't decrease performance).

Thanks!

**Comment by dougm** [comment]
@sttyru have a look at the example in #1520 , you can use ContainerView with type `ManagedEntity` to query `customValue` for all types.

**Comment by sttyru** [comment]
Can I ask you to re-open this subject?
I faced with an unpredictable `panic` at execution of mine app at step when I trying to use the `key` (for search/filter) containts more than one `word`. E.g. I have the `custom field` with name 'Monitoring (true/false)' and follow your example I got an error.

**Comment by dougm** [comment]
@sttyru sure, do you have some code we can use to reproduce?

**Comment by sttyru** [comment]
My sorry. It's my stupid mistake.
