### ISSUE TITLE
List of Guest OS Customizations?

### ISSUE THREAD

**Issue by dominicgunn** [vmware/govmomi#1518]
Hey,

I was wondering how I used this library to list out all of the available customizations available to my VM? I've really tried to scower the code, but I think I must be missing something.

I know that the web ui (vsphere) will make a call with the `customizeGosSpecData` property, and get a json response containing all the available data, but I can't find an equivalent here.

**Comment by dougm** [comment]
I think you're looking for these: https://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.CustomizationSpecManager.html

And the Go wrappers: https://godoc.org/github.com/vmware/govmomi/object#CustomizationSpecManager

**Comment by dominicgunn** [comment]
So I found that, but the methods available are typical crud `get`, `overwrite` (update), `delete`, `exists`. There's no `list`.

**Comment by dougm** [comment]
There is the `info` property:

> Gets a list of information on available specifications. 

Looks like you can use the `CustomizationSpecInfo.Name` field to call `GetCustomizationSpec`

**Comment by dominicgunn** [comment]
So, sorry to be commenting on this again so long after the initial discussion. I was never actually able to find a way to access the `Info` property, and actually have it not be null. In the meantime we approached the issue with this block of code after querying the API from our browser and storing the response on disk, but that doesn't work long term as we touch the customizations semi-frequently. 

```
func (c *VSphereClient) DoesCustomizationExist(customization string) (bool, error) {
	customizationSpecManager := object.NewCustomizationSpecManager(c.Client.Client)
	return customizationSpecManager.DoesCustomizationSpecExist(c.ctx, customization)
}
```

I hate to bother you with it, as it doesn't feel like this should be massively complicated, but would you be able to put together an example of how we might construct the `customizationSpecManager` in a way that lets us access the `Info` so we can iterate over the customizations?

We've tried all manner of View creations, but it seems to stump us as the SpecManager lives above the root folder, so when we try and go things like.CreateContainerView(c.ctx, client.ServiceContent.RootFolder, []string{"CustomizationSpecManager"}, true)` for example, it bombs out.

**Comment by dougm** [comment]
@dominicgunn no problem, I meant to add #1722 to address this, can you review?
