### ISSUE TITLE
Handling events of type types.EventEx

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1527]
Hi Gurus,
I am handling events coming from vSphere and I am easily able to handle events like
- types.HostRemovedEvent:
- types.DatastoreRemovedOnHostEvent:
- types.ExitMaintenanceModeEvent

These events are defined clearly in the vmware types and I can easily check if the event type is one of them and cast them accordingly.
However, when a datastore is put into maintenance mode or taken out of maintenance mode, I receive a EventEx object. For example,
&{Event:{DynamicData:{} Key:314720 ChainId:314719 CreatedTime:2019-07-18 08:44:45.229522 +0000 UTC UserName:VSPHERE.LOCAL\Administrator Datacenter:0xc00018d230 ComputeResource:<nil> Host:<nil> Vm:<nil> Ds:0xc00018d260 Net:<nil> Dvs:<nil> FullFormattedMessage:Datastore KayshavJul1-11G has exited maintenance mode ChangeTag:} EventTypeId:com.vmware.vc.sdrs.DatastoreExitedMaintenanceModeEvent Severity: Message: Arguments:[] ObjectId:datastore-1413 ObjectType:Datastore ObjectName:KayshavJul1-11G Fault:<nil>} dc=&{{{{}} demo-dc} Datacenter:datacenter-773} msg=Datastore KayshavJul1-11G has exited maintenance mode key=314720

The DatastoreEnteredMaintenanceMode or DatastoreExitedMaintenancemode are not normal events in defined in the types.
Therefore, I am wondering how I can determine 
a. If the event is DatastoreExitedMaintenceMode or DatastoreEnteredMainteanceMode 
b. After (a), how do I typcast the received object and access the components?
Thanks
-k

**Comment by dougm** [comment]
From https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.event.EventEx.html

> EventEx is a dynamically typed Event class, whose type is indicated by its eventTypeId property.

There isn't anything that govmomi provides beyond the fields in the doc above for `EventEx`.

**Comment by embano1** [comment]
@kayshavd see this PR where we deal with all vC events (incl ex and extended) using the event manager:
https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/29/files#diff-54941f8545e37d27408214ae7c9ddd33
