### ISSUE TITLE
Using tags to search for content libraries

### ISSUE THREAD

**Issue by sreyasn** [vmware/govmomi#1529]
vapi finder for libraries currently seems to support search by Name, ID, Type. 

This is a feature request to add tags as well if it doesn't exist

**Comment by dougm** [comment]
@sreyasn you can use the `tags.Manager.ListAttachedObjects` method, the reference(s) returned will be in the form of:
```go
&types.ManagedObjectReference{
   Type: "com.vmware.content.Library",
   Value: "57957ac6-edc0-4815-9730-7a8177c66c6e",
}
&types.ManagedObjectReference{
   Type: "com.vmware.content.library.Item",
   Value: "5e16fc4d-ecc6-4a9b-9984-b88f268b8668",
}
```

Where `Value` is the Library or Item ID.

**Comment by sreyasn** [comment]
Thanks for working on this Doug 👍
