### ISSUE TITLE
govc guest.start Windows7 strange behaviour

### ISSUE THREAD

**Issue by maxspb89** [vmware/govmomi#1531]
I'm trying to start any application from govc CLI on Windows7. For example notepad: 
` govc guest.start -u administrator@vsphere.local:vsphere-pass@192.168.88.155 -k -l user:password -vm "win7x64" "C:\Windows\System32\notepad.exe" `

It raises "Interactive services detection" message box, so the program doesn't start normally. I can see notepad window only if I press the "See the message" button in "Interactive services detection" message box. 

The application starts under vmware service, not under explorer.exe.
Any way I can remote start applications normally?

**Comment by dougm** [comment]
I don't think govmomi/govc can help with avoiding this issue, seems like either a VMware tools issue or something you need to configure in windows.  For example (I only skimmed the article): https://blogs.msdn.microsoft.com/patricka/2010/04/27/what-is-interactive-services-detection-and-why-is-it-blinking-at-me/

**Comment by dougm** [comment]
@gressd is this what you needed the new `-i` flag for ?

**Comment by gressd** [comment]
Not exactly my use case but Yes it works, I've only tested on Win2016.     
<img width="1208" alt="With" src="https://user-images.githubusercontent.com/21316842/65845347-e6ebcc80-e307-11e9-9253-1bfa0f0887ee.png">
![Uploading without.png…]()

**Comment by dougm** [comment]
Thanks @gressd , closing as the `-i` flag is included with the upcoming 0.22 release via #1602
