### ISSUE TITLE
Feature request - Add vnic on host

### ISSUE THREAD

**Issue by li-kai-yuan** [vmware/govmomi#1532]
Hi,

I'm trying to create vnic on host via govc, but failed to find relevant command. At the end, I can create vnic in virtual standard portgroup using govc host.esxcli.

Is it possible for govc to support feature to add vnic on host without go through esxcli, and support add vnic on both virtual standard portgroup and distributed virtual portgroup?

Thanks.

**Comment by dougm** [comment]
Can you share the esxcli command you're using?
