### ISSUE TITLE
Still cannot use Powercli greater than 5.5 with VCSIM

### ISSUE THREAD

**Issue by vamp911** [vmware/govmomi#1533]
Hello

I'm aware of the earlier fix for users of Powershell greater than 5.5 which involved the lookupservice but i am still encountering the exact same issue with the latest code in the master branch. I've shown the error i'm receiving below, but this does work perfectly when I use Powercli 5.5. I need to be able to use Powercli > version 10 to test my functions with.

PS C:\> Connect-VIServer vcsim.tse.int
Connect-VIServer : There was no endpoint listening at https://192.168.4.27/lookupservice/sdk that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
At line:1 char:1
+ Connect-VIServer vcsim.tse.int
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-VIServer], EndpointNotFoundException
    + FullyQualifiedErrorId : System.ServiceModel.EndpointNotFoundException,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer

**Comment by dougm** [comment]
Is vcsim running on port 443?  Not sure if PowerCLI has added an option to specify a different port for the lookup service.  cc @jakerobinson

**Comment by vamp911** [comment]
@dougm 
Hi Doug, thanks for responding.
Yes, I have vcsim running on port 443.

**Comment by jakerobinson** [comment]
The actual LookupService does not allow changing the port, so PowerCLI has not implemented that. That being said, everything should work if you're using port 443. Following this guide from @brianbunke will get you going, at least... http://www.brianbunke.com/blog/2018/12/31/vcenter-simulator-ci/

**Comment by brianbunke** [comment]
Can confirm those instructions ☝️ still work for me on Win10 w/ local Docker.

`VMware.VimAutomation.Core` version `11.3.0.13964826`
PowerShell versions `5.1.17763.316` & `6.2.2`

**Comment by vamp911** [comment]
No still not working for me. I've deployed containers from lamw/docker-vcsim and  nimmis/docker-vcsim which compile the latest vcsim code. I've also used vcsim as a regular service (no containerization) and still have the same results in that powercli < 5.5 does not work at all. Here are the versions I'm using:

VMware.Vim                    6.7.0.8343295
VMware.VimAutomation.Cis.Core 10.1.0.8377811
VMware.VimAutomation.Common   10.1.0.8342134
VMware.VimAutomation.Core     10.1.0.8344055
VMware.VimAutomation.Sdk      10.1.0.8342078

I'm using these because I need to test my functions before using them in a production environment. Mainly the parts involving datastore creation and manipulation. I don't have an environment I can potentially mess with (not the datastores anyway). Does it only work if vcsim server and the powercli client are on the same server i.e. local Docker?

**Comment by vamp911** [comment]
Hi Guys,

Thanks for your comments and helping with this. I'm able to close this issue because upgrading the VMware.VimAutomation.Core to 11.3.0.13964826 works like a charm as suggested by Brian above. Sorry for wasting your time, my only excuse is i'm not very good with Powershell and didn't know anything about importing or upgrading modules until now. :-)

**Comment by dougm** [comment]
@vamp911 ok, glad to hear it's working for you now.
