### ISSUE TITLE
Guest filesystem(s) information

### ISSUE THREAD

**Issue by sttyru** [vmware/govmomi#1537]
Hello!

How I can to get an information about a persistent guest filesystem(s) ? I want to see a total space at partition und used space (in Kilobytes, in a struct). I found only the one note about `vm.Guest` ( [by there](https://github.com/vmware/govmomi/issues/1186), but have no idea how I can to use that. 

Thanks for help!

**Comment by sttyru** [comment]
I was talking about [this feature](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/423e512d-dda1-496f-9de3-851c28ca0814/0e3f6e0d-8d05-4f0c-887b-3d75d981bae5/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/operations/com/vmware/vcenter/vm/guest/local_filesystem.get-operation.html)
_I can to return an info for each VM, but isn't acceptable for a production's usage (my software fetch a data about all objects every 15-30 seconds and a high number of HTTP requests to vSphere increasing of a system load)._

**Comment by dougm** [comment]
```json
% govc object.collect -json /dc1/vm/dougm-ubuntu-16.04 guest.disk | jq .
[
  {
    "Name": "guest.disk",
    "Op": "assign",
    "Val": {
      "GuestDiskInfo": [
        {
          "DiskPath": "/",
          "Capacity": 40576331776,
          "FreeSpace": 38497316864
        },
        {
          "DiskPath": "/boot",
          "Capacity": 494512128,
          "FreeSpace": 434487296
        }
      ]
    }
  }
]
```

**Comment by sttyru** [comment]
Dougm, at first thank you so much for the answer at previous question (about custom fields)! I faced with a little bug and I'll write in the appropriate issue.
Yes, I was looking for that! Would it be too much trouble for you to have an show me how to parse of 'object.collection' output for searching of disks usage statistics?

**Comment by dougm** [comment]
Are you using govc for this or govmomi?  For the latter you can just use the property collector, see this example: https://github.com/dougm/govmomi/commit/3fb02b520d8b3efe2ddbab2cd820987ebf385589#diff-f97cd509b891fe51f36eb9e818b205bdR73-R74

**Comment by sttyru** [comment]
> Are you using govc for this or govmomi? For the latter you can just use the property collector, see this example: [dougm@3fb02b5#diff-f97cd509b891fe51f36eb9e818b205bdR73-R74](https://github.com/dougm/govmomi/commit/3fb02b520d8b3efe2ddbab2cd820987ebf385589#diff-f97cd509b891fe51f36eb9e818b205bdR73-R74)

I'm using `govmomi`. I got an success result! :)
