### ISSUE TITLE
guest.run hangs, guest.ls returns nothing

### ISSUE THREAD

**Issue by w0de** [vmware/govmomi#1539]
Hello!

```
~ govc version
govc 0.20.0
```

```
~ govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        11727113
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.1
Product ID:   vpx
UUID:         aaac7a35-f521-4441-9803-4afacc8ec582
```

I am running the toolbox, compiled for amd64, on the VM. The VM is:

```
Darwin macbook 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

Running: `~ govc guest.run -vm=$VM -d - bash -c whoami` results in the govc command hanging. I do see the the string "whoami" in the toolbox.trace output. By "hanging", I mean the command does not complete and nothing is printed to stdout/stderr.

Further, running `~ govc guest.ls -vm=$VM /Users/` (or any path) returns an empty output. 

Interestingly, running `~ govc guest.ps -vm=$VM`, even after CTRL+C has been successfully sent to `~ govc guest.run -vm=$VM -d - bash -c whoami`, returns:

```
UID        PID  STIME  CMD
penny.pig  964  08:45  bash -c whoami
```

(`GOVC_GUEST_LOGIN=penny.pig:password`)

I suspect this is something entirely amateur in configuration or the syntax of the command I pass to `guest.run`. Any guidance to offer?

**Comment by dougm** [comment]
Hi @w0de , `-d` is for input, so the hang is govc waiting on stdin.  For example:
```console
% whoami | govc guest.run -d - cat                                                            
dougm
```
You can just omit the `-d` flag in this case:
```console
% govc guest.run bash -c whoami
core
```

btw you are the first I know of to run toolbox in a Darwin VM, interested to hear how well its working.

**Comment by w0de** [comment]
Not well, presently - though user error has not been ruled out. Dropping the `-d` flag, this occurs:

```
~ govc guest.run -C=/Users/penny.pig -vm=$VM /usr/bin/whoami
govc: ServerFaultCode: File /proc/3145/stdout was not found
```

The `./toolbox` output is:

```
2019/07/26 18:17:54 [vix] op=188 error stat /proc/782/stdout: no such file or directory
```

I expect this is because [Darwin does not have a procfs](http://osxbook.com/book/bonus/ancient/procfs/). 

Also, as an aside, I'm passing the full path because:

 ```
~govc guest.run -C=/Users/penny.pig -vm=$VM whoami
govc: ServerFaultCode: A specified parameter was not correct: No file data?
```

**Comment by dougm** [comment]
Relative path is required for guest.run, so it does need to be `whoami` rather than `/usr/bin/whoami`: https://github.com/vmware/govmomi/blob/9afb1a8d18384e17a098684d42734067823fb1da/toolbox/command.go#L241-L244

It's ok that Darwin doesn't have /proc, the `/proc/$pid/std{err,out,in}` paths are pseudo files that only toolbox recognizes. 

I haven't see the `No file data?` error before.  Anything useful in the VM's vmware.log file?
(e.g. from `govc datastore.download $VM/vmware.log -`)

Also, if standard vmware-tools is an option for you instead of toolbox, you can get guest.run functionality with a few more steps: https://github.com/vmware/govmomi/issues/1514#issuecomment-508149851

**Comment by w0de** [comment]
```
2019-07-29T17:24:08.858Z| vmx| I125: VigorTransportProcessClientPayload: opID=10ee9812-fc-6d4d seq=622: Receiving GuestOps.StartProgram request.
2019-07-29T17:24:08.898Z| vcpu-0| I125: VigorTransport_ServerSendResponse opID=10ee9812-fc-6d4d seq=622: Completed GuestOps request with messages.
2019-07-29T17:24:08.905Z| vmx| I125: VigorTransportProcessClientPayload: opID=2041ce6d-a4-6d53 seq=633: Receiving GuestOps.InitiateFileTransferFromGuest request.
2019-07-29T17:24:08.911Z| vcpu-0| I125: VigorTransport_ServerSendResponse opID=2041ce6d-a4-6d53 seq=633: Completed GuestOps request with messages.
```

This is the relevant section in vmware.log. Nothing exciting to me. Is it possible that `InitiateFileTransferFromGuest` is being called incorrectly?

I'll give vmware tools + extra steps a go on a VM, but I'll keep trying toolbox on at least one.

Would you like full logs/toolbox --trace output?

**Comment by dougm** [comment]
#1752 removes the toolbox deps, feedback welcome.
