### ISSUE TITLE
ManagedObjectNotFound on RoundTrip

### ISSUE THREAD

**Issue by Psych0cat** [vmware/govmomi#1540]
Hi! Have an error and could not find out what happened. Trying to edit VM using Reconfigure, but failed. Began to dig and found out that client.Roundtrip() returns` ServerFaultCode: ManagedObjectNotFound` My code: 
```
    ctx, cancel := context.WithCancel(context.Background())    
     //trying to edit single param
    spec := types.VirtualMachineConfigSpec{
	NumCPUs := int32(2)
    }
    req := types.ReconfigVM_Task{
	//reference is tested
        This: vmReference,
	Spec: spec,
	}
    var reqBody, resBody methods.ReconfigVM_TaskBody
    reqBody.Req = &req
    //client is tested, vm.Client().Valid() returns true
    vm := object.NewVirtualMachine(client, vmReference)
    err = vm.Client().RoundTrip(ctx, &reqBody, &resBody)
    if err != nil {
	fmt.Println(, err)
}
```
Prints `ServerFaultCode: ManagedObjectNotFound`

Any ideas?
Thanks!

**Comment by Psych0cat** [comment]
Found mistake in my code, sorry for that.
Thanks for your work!

**Comment by dougm** [comment]
@Psych0cat glad you found the problem.  No need to use RoundTrip directly, added an example in #1541
