### ISSUE TITLE
govc library.ls inventory path to subscribed inventory

### ISSUE THREAD

**Issue by excilsploft** [vmware/govmomi#1542]
Using govc to interrogate a subscribed library via an inventory path without a wildcard, fails this is due to the hardcoded "LOCAL" type in `govmomi/vapi/library/finder/finder.go`

`    // If the token does not contain any wildcard characters then perform
    // a lookup by name using a server side call.
    if !strings.ContainsAny(token, "*?") {
        libIDs, err := f.M.FindLibrary(
            ctx, library.Find{Name: token, Type: "LOCAL"})
        if err != nil {
            return nil, err
        }
        for _, id := range libIDs {
            lib, err := f.M.GetLibraryByID(ctx, id)
            if err != nil {
                return nil, err
            }
            result = append(result, findResult{result: *lib})
        }
        return result, nil
    }`

Unfortunately, outside of two calls with "SUBSCRIBED" and "LOCAL"  I can't think of a better way to do that as the underlying REST api looks flawed otherwise I would submit a PR

**Comment by dougm** [comment]
@excilsploft #1545 fixes this just by omitting the type.  We have focused on local libraries, so there are likely other fixes/improvements we can make for subscription libraries.. feedback/issues/PRs welcome.
