### ISSUE TITLE
govc vm.clone Host not found [IP?]

### ISSUE THREAD

**Issue by rafamiga** [vmware/govmomi#1543]
I'm getting this strange behavior with vm.clone.

$ govc env
GOVC_USERNAME=root
GOVC_PASSWORD=password
GOVC_URL=10.0.0.1
GOVC_INSECURE=1
$ export GOVC_URL=https://root:password@10.0.0.1
$ govc vm.clone -vm=Fudo-3.9-template -ds=ds01 -pool=FUDO_Klienci_PoC Fudo-3.9-temp
govc: host '10.0.0.1' not found
$ GOVC_URL=https://root:password@10.0.0.1 govc vm.clone -vm=Fudo-3.9-template -ds=ds01 -pool=FUDO_Klienci_PoC Fudo-3.9-temp
govc: host '10.0.0.1' not found

But I have no problems managing VMs. This works, takes credentials from GOVC_URL...

if [ "$2" == "-f" ]; then
        govc device.remove -vm=$1 -keep=true disk-200-0
        govc device.remove -vm=$1 cdrom-3002
        govc device.remove -vm=$1 floppy-8000
else
        govc device.ls -vm=$1
fi

Does clone require some kind of "special" parameters?

Here is some extra info:

$ govc about
Name:         VMware ESXi
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        9919047
OS type:      vmnix-x86
API type:     HostAgent
API version:  5.5
Product ID:   embeddedEsx
UUID:

$ govc version
govc 0.21.0

**Comment by dougm** [comment]
Sounds like you have env `GOVC_HOST` set?  If so: `unset GOVC_HOST`
That env var would be the default value for the `-host` flag, but that's your vCenter host so it won't be found in the inventory.

**Comment by rafamiga** [comment]
You're right, unsetting GOVC_HOST solved the issue. But then again, why is IP address treated as FQHN?...

**Comment by dougm** [comment]
The message `govc: host '10.0.0.1' not found` comes from the inventory Finder, unrelated to the vSphere connection itself.  Don't know what you mean by "treated as FQDN" ?
