### ISSUE TITLE
Feature request: vm.create support for vmx-8 (5.0)

### ISSUE THREAD

**Issue by rafamiga** [vmware/govmomi#1544]
I'd be nice to support vmx-8 VMs. Here's the rationale: we're creating lots of demo VMs for customers and Fudosecurity partners. [This year 300+ VMs so far]. Vmx-8 is the ONLY VM version that is working on virtually every VMware/KVM/Virtualbox environment our clients/partners run. Since our appliance is self-contained and requires simple OVA import to deploy, this is the way we do it.

I'd imagine it's just adding a line at govc/vm/create.go:

var hardwareVersions = []struct {
	esx, vmx string
}{
	**{"5.0", "vmx-8"},**
	{"5.5", "vmx-10"},
	{"6.0", "vmx-11"},
	{"6.5", "vmx-13"},
	{"6.7", "vmx-14"},
}
but the world isn't perfect, is it?

[Yes, I know, I can clone a template a VM, but there's an issue with vm.clone I reported earlier.]
[And I'm aware of the _config.version = "8"_ method.]

**Comment by dougm** [comment]
@rafamiga sure, and that looks right to me, can you open a pull request with that change?
