### ISSUE TITLE
Managing and monitoring event handlers

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1547]
I am using the event package to subscribe to events from vCenter, using

Events(ctx context.Context, objects []types.ManagedObjectReference, pageSize int32, tail bool, force bool, f func(types.ManagedObjectReference, []types.BaseEvent) error, kind ...string) error {

The function specified gets called by the event manager in vCenter and all that works fine. However, how do I know if/when the event subscription has been terminated or has died. Is there a way to query periodically to find out if the event subscription is still alive? Internally, the above method creates an eventProcessor but there is no way to access it. 
Just need a way to monitor the event subscription and recreate it if it disappears for any reason.
-k

**Comment by dougm** [comment]
Just a for loop will do, for example: https://github.com/vmware/vic/blob/19d8a93a99953a74012fadee23187c221a71deef/lib/portlayer/event/collector/vsphere/collector.go#L176-L189

**Comment by kayshavd** [comment]
Thanks much for the pointer.  Somehow, I overlooked the fact that the eventManager.Events() is a blocking call ☹

-kayshav
[Platinum-Volunteer]
