### ISSUE TITLE
How can I terminate the govmomi service.

### ISSUE THREAD

**Issue by BoysAndGirls** [vmware/govmomi#1549]
I started multiple  govmomi  services through goroutines.  At some point, I need to close one of the services that are already open. Others keep up and running. I want to use channel,  But failed to achieve. How can I do. Thank you!

![image](https://user-images.githubusercontent.com/25577689/62618833-d5a9c380-b947-11e9-8e1a-5ad3be804325.png)

**Comment by dougm** [comment]
Have a look at govc's method: https://github.com/vmware/govmomi/blob/b16d17160b3c9c4d6cd11b0cd44476d35c8bfb48/govc/flags/client.go#L687-L711

Used by `govc events` for example: https://github.com/vmware/govmomi/blob/b16d17160b3c9c4d6cd11b0cd44476d35c8bfb48/govc/events/command.go#L169

**Comment by BoysAndGirls** [comment]
Thank you for your answer. Maybe I am a newbie, I still don't know how to terminate the service by the above method. My code is based on this link, without using **"logrus, cli"**

https://github.com/pdellaert/gesxmon/blob/4e4288f443feffd2d973d5e57b9ff20bd2b8563b/main.go

I want to start multiple and different services, so, like this
```
go ListenAction(.......)

func  ListenAction(in chan string ... ...){
    ............
     err = esxiEventListener.Run(in)
     ........
}

```
Under certain conditions, I want to terminate one of the services. But I never found a good way. I stumbled upon the fact that calling method **“client.SessionManager.Logout(e.ctx)”** could trigger an error and end a service. So, like this

```
func (e *ESXiEventListener) Run(in chan string) (err error) {
	go func() {
		select {
		case <-in:
			e.client.SessionManager.Logout(e.ctx)
			e.client.CloseIdleConnections()
			e.ctx.Done()
			close(in)
			return
		}
	}()
	logs.Logger.Info("Connecting to the ESXi host")
	e.client, err = govmomi.NewClient(e.ctx, e.url, e.insecure)
        .................................
        .................
        err = e.eventManager.Events(e.ctx, refs, 1, true, false, e.handleEvent)
        ........
```
Whenever I want to end a service, I send a signal through **Chan**. I don't know if this is a good way, but it can meet my needs.

**Comment by dougm** [comment]
The first param to all API methods is `context.Context`, you can use `context.WithCancel`: https://github.com/vmware/govmomi/blob/7b40d3e162becb69c99f2b71a26e1966adb34384/govc/flags/client.go#L692

And call the returned `cancel()` func at any time to break out of the `Events` func: https://github.com/vmware/govmomi/blob/7b40d3e162becb69c99f2b71a26e1966adb34384/govc/flags/client.go#L705

**Comment by BoysAndGirls** [comment]
It works, and it's so simple. Haha, it seems that I need to study **"golang context"** well. Thank you, thank you very much. @dougm
