### ISSUE TITLE
How to get the disk size at the time a snapshot was taken?

### ISSUE THREAD

**Issue by MarcusTan** [vmware/govmomi#1552]
Given a snapshot moid, how can I get the disk size at the time the snapshot was taken?

From `vim25/mo/mo.go` I see type `VirtualMachineSnapshot` which seems to be what I want. Given a `VirtualMachineSnapshot` I would do:

```
vms := GetVirtualMachineSnapshot() // how do I do this?
devices := vms.Config.Hardware.Device
for _, d := range devices {
    if (d is a VirtualDisk) {
        // since VirtualDisk embeds VirtualDevice
        b := d.GetVirtualDevice().CapacityInBytes()
    }
}
```

However, how do I get a virtual machine snapshot? Or is there some other way of doing this?

**Comment by dougm** [comment]
@MarcusTan is this what you're looking for? https://github.com/vmware/govmomi/issues/1197#issuecomment-412248687

**Comment by MarcusTan** [comment]
@dougm 

I saw that Issue, but I don't think it's what I'm looking for. The size there seems to refer to the size of the snapshot. However, I'm looking for more like a map of underlying disk names to disk sizes, for the given snapshot, at the time the snapshot was taken.

**Comment by MarcusTan** [comment]
@dougm I was wondering if you had any thoughts on the above?

**Comment by dougm** [comment]
@MarcusTan I don't know, but if you can find the solution in any other language I can help with porting it to Go.

**Comment by sachu** [comment]
I'd also be interested in learning how to port from another language.

**Comment by MarcusTan** [comment]
@dougm Sorry for the late reply. Here is a snippet which uses pyvmomi. Would really love an equivalent Govmomi solution.

```
snapshot_disk_sizes = {}
snapshot = vim.vm.Snapshot(snapshot_moid)
snapshot._stub = service_instance._stub
devices = snapshot.config.hardware.device
for device in devices:
    if isinstance(device, vim.vm.device.VirtualDisk):
        snapshot_disk_sizes[device.key] = device.capacityInBytes
return snapshot_disk_sizes
```

**Comment by dougm** [comment]
Ah, you can use the property collector to get snapshot.config.hardware.device, see the example in #1596
