### ISSUE TITLE
When the number of virtual machines is large, the request to pull the virtual machine list takes longer

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1554]
When the number of virtual machines is large, the request time to pull the list of virtual machines is long. What is the solution

**Comment by MarcusTan** [comment]
Wait

**Comment by dougm** [comment]
There are several ways to list VMs, please provide more details.

**Comment by yusufozturk** [comment]
Any update on this issue? Thanks.

**Comment by yusufozturk** [comment]
I think this might be the workaround for this issue:
https://github.com/vmware/govmomi/issues/2409
