### ISSUE TITLE
Are I/O filtering (VAIO) / Storage Policy APIs supported by govmomi?

### ISSUE THREAD

**Issue by MarcusTan** [vmware/govmomi#1555]
I saw #1396 which leads me to believe that storage policies aren't supported (yet.) Is this true? If so, I was wondering what the timeline is on implementing this.

Also, if these APIs aren't supported, are there other existing go alternatives to manipulate i/o filters and storage policies?

**Comment by dougm** [comment]
We do have the API bindings: https://github.com/vmware/govmomi/tree/master/pbm

We just don't have any govc related commands yet.

**Comment by dougm** [comment]
Closing as this is tracked in #1396
