### ISSUE TITLE
How can I use the version string with property.WaitForUpdates()?

### ISSUE THREAD

**Issue by davidflanagan** [vmware/govmomi#1556]
The WaitForUpdatesEx method takes a version argument, but as far as I can tell property.WaitForUpdates in property/wait.go does not support it.

Is the version identifier not actually needed in practice, or is this a shortcoming of golang bindings?

**Comment by dougm** [comment]
The `Version` param is supported/used here: https://github.com/vmware/govmomi/blob/7b40d3e162becb69c99f2b71a26e1966adb34384/property/wait.go#L125

**Comment by davidflanagan** [comment]
Yes, I see that at line 125. What I was concerned about is that there is no way to pass an initial version into the WaitForUpdates() function. But after thinking about this some more, I believe that passing in a version does not make sense because WaitForUpdates() is creating its own private PropertyCollector object, and presumably the version number is relative to the property collector rather than a global value?

I'm looking for a way to use the underlying API that is robust even if the client crashes and has to be restarted, and want to use the version number to resume waiting for updates in that scenario. Maybe the underlying API does not actually support that, but in any case, I can see that the code in wait.go cannot support it.

In any case, I'll close this issue, since I think it was basically a feature request for an impossible feature.

**Comment by dougm** [comment]
Right, Version only applies to PropertyCollector instance created (and destroyed) by WaitForUpdates.

`property.WaitForUpdates()` handles the most common use cases, but you can always call `methods.WaitForUpdatesEx()` directly if needed.
