### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1557]
Pull virtual machine list data, too much data will be time-consuming, but I did not see any pagination fields;
![image](https://user-images.githubusercontent.com/38032852/62844834-7efd0a80-bcf6-11e9-80fb-79c54a028610.png)
![image](https://user-images.githubusercontent.com/38032852/62844848-90461700-bcf6-11e9-82dd-af3470cf6bd5.png)

**Comment by dougm** [comment]
Why open another issue again @sirzhanghai ?  Can you collapse this with #1554 ?
