### ISSUE TITLE
Finding the drive type behind a Datastore

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1559]
Given a Datastore object backed by some storage, I would like to find out if the storage is an SSD drive or a vanilla HDD. Looked deep into the Datastore attributes but came up empty.

Appreciate any pointers.
-k

**Comment by dougm** [comment]
I don't think the Datastore type provides that info, but you can get it for host local storage:

```console
% govc host.storage.info -host /dc1/host/cluster1/10.143.2.228
Name                                     Type   Capacity  Model  
/vmfs/devices/cdrom/mpx.vmhba1:C0:T0:L0  cdrom  -         VMware IDE CDR00
/vmfs/devices/disks/mpx.vmhba0:C0:T1:L0  disk   48.0GB    Virtual disk     (local)
/vmfs/devices/disks/mpx.vmhba0:C0:T0:L0  disk   24.0GB    Virtual disk     (local,ssd)
```

**Comment by kayshavd** [comment]
Thanks for the info. Would have been nice to get that info from a datastore so that one can decide which datastore to place a vm on (fast vs slow).

**Comment by dougm** [comment]
The vSphere API doesn't expose that info for a Datastore, so govmomi can't either.  Not sure how it'd be possible in certain cases, such as NFS, for vSphere to get that detail.

**Comment by kayshavd** [comment]
Yes, I totally get that vSphere APIs don’t provide that piece of info. And this could have been a piece of optional information in vSphere, made available when it is deterministic and left undefined otherwise.

-kayshav
[Platinum-Volunteer]

**Comment by dougm** [comment]
Closing as this is out of scope for govmomi, until such an API is added to vSphere.
