### ISSUE TITLE
govc: Host did not have any virtual network defined

### ISSUE THREAD

**Issue by nealhhicks** [vmware/govmomi#1561]
Hi everyone,

I'm following [(this document](https://blog.openshift.com/deploying-a-user-provisioned-infrastructure-environment-for-openshift-4-1-on-vsphere/)) to deploy OCP 4.1 UPI on VMware vSphere, but I've run into an issue that I haven't been able to figure out for a couple weeks now, and I have exhausted all options that I can think of (and all options I've been able to research).

The problem I'm running into is, every time I try to run:
govc import.ova -name=rhcos-latest TerraformTest/rhcos-4.1.0-x86_64-vmware.ova

I receive the error:
govc: Host did not have any virtual network defined.

I've tried a variety of things to get past this issue. I tried out the solution listed [here](https://github.com/vmware/govmomi/issues/460).

Unfortunately, that did not work, and generated the exact same error message. 

I also tried connecting directly to a Host instead of the vCenter and I modified the variables appropriately, commenting out any references to the Cluster to Datacenter. I also verified that my credentials used for authentication to both vCenter as well as the individual Host worked without issue.

I've also made sure that I'm inputting the correct variables, as I've used the govc ls and govc ls network commands to verify that. I truly am at a loss for how to proceed. I'd really appreciate any help that anyone can offer, and I'd be happy to provide more information as needed. 

Thanks in advance everyone!

**Comment by dougm** [comment]
Can you share the NetworkMapping from your options.json file?  The `Name` there should be that of the ova's network name and `Network` should be that of the vCenter network you want to use.

**Comment by dantran** [comment]
I run into same issue.  where i have to correct NetworkMapping

However,  govc always deploys to the first 'standard network' available for my cluster.  My wanted network is a 'distributed port group'

if I remove all of my host 'standard network', govc bails with the same error in the title

does this ring any bell?

**Comment by koteswara-kelam** [comment]
I am also facing same issue. Even if i specify "myNetwork" which is DVS portgroup, the VM always is getting deployed on "VM Network".
$ cat options.json
{
"DiskProvisioning": "flat",
"IPAllocationPolicy": "dhcpPolicy",
"IPProtocol": "IPv4",
"InjectOvfEnv": false,
"MarkAsTemplate": false,
"Name": null,
"NetworkMapping": [
{
"Name": "myNetwork",
"Network": "myNetwork"
}
],
"PowerOn": false,
"WaitForIP": false
}
$ govc import.ova --options=options.json centos-7-7-1579580585.ova
[21-01-20 11:28:57] Warning: Line 72: Invalid value 'bridged' for element 'Connection'.
[21-01-20 11:30:01] Uploading greenlake-centos-7-7-disk1.vmdk... OK

**Comment by koteswara-kelam** [comment]
it is working after changeing "Name" to ova's network. Thanks @dougm  I didn't read your comment carefully.

**Comment by dougm** [comment]
We need to capture this in the docs, and see if we might be able to help automate or at least sanity check with govc.  In the meantime, for others running into this:

Save the ovf options:

```console
% govc import.spec example.ova | jq . > options.json
```

Edit options.json, leaving the `Name` value as-is and changing the `Network` value:

Before:
```json
  "NetworkMapping": [
    {
      "Name": "ovf-defined-network",
      "Network": ""
    }
  ],
```

After:
```json
  "NetworkMapping": [
    {
      "Name": "ovf-defined-network",
      "Network": "name-of-vsphere-network-to-use"
    }
  ],
```
Use the saved options to import:
```console
% govc import.ova -options options.json ... example.ova
```
