### ISSUE TITLE
ability to add PCI device to a vm

### ISSUE THREAD

**Issue by warroyo** [vmware/govmomi#1563]
it doesn't look like govc supports adding PCI devices to a vm today. Is this something that is already being considered? 

Happy to work on a PR for this if it is not already being looked at

**Comment by dougm** [comment]
@warroyo happy to accept PRs that add to the govc device.* family of commands.  Not aware of any work underway in that area currently.

**Comment by saedalavinia** [comment]
Hey all! 
We also have the need for this use case. 
@warroyo  have you worked on this sissue at all ?

**Comment by ading007** [comment]
@warroyo we need to integrate it for cluster api, when will it be ready?

**Comment by leslie-qiwa** [comment]
@dougm I'm exploring the effort for that. Can you please share the potential APIs to do the operation? Also includes listing available PCI devices?

**Comment by dougm** [comment]
@leslie-qiwa great, have a look at the existing device commands, in particular the add commands:

```console
% ls -1 govc/device/*/add.go
govc/device/cdrom/add.go
govc/device/floppy/add.go
govc/device/scsi/add.go
govc/device/serial/add.go
govc/device/usb/add.go
```

Docs for the complete list of device types are here (follow the "Extended by" links):
https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.device.VirtualDevice.html

The `device.ls` and `device.info` commands should be able to list PCI devices.

**Comment by leslie-qiwa** [comment]
wonderful! 

I'm going to work on some side subcommands firstly:

- govc host.hardware.ls: list all hardwares. --passthough option will only list passthrough capable devices
- govc host.hardware.passthrough enable <hardware ID>: enable passthrough on one device
- govc host.hardware.passthrough disable <hardware ID>: disable passthrough on one device

After that, I'll add support to add / delete one device for one VM.

**Comment by dougm** [comment]
Added in #2092
