### ISSUE TITLE
Most efficient way to get a count of VMs and Hosts in a Datacenter

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1564]
What is the most efficient way to count the number of VMs and Hosts under a Datacenter?  One can get the VMFolder and HostFolder elements within a Datacenter and then recursively look into all the folders within those two folders and count all elements of type VirtualMachine and ComputeResource.  This can become expensive if the folder structure is deep.

Or, instead of counting, is there any entity that keeps the current count of VMs and Hosts in a Datacenter that one can query? 
Woderning if there is a better way to accomplish this?

-k

**Comment by dougm** [comment]
`ContainerView` is probably your best bet.  For example:
```go
		m := view.NewManager(c)
		kinds := []string{"HostSystem", "VirtualMachine"}
		v, err := m.CreateContainerView(ctx, dc, kinds, true)
		if err != nil {
			return err
		}
		defer v.Destroy(ctx)

		var content []types.ObjectContent
		err = v.Retrieve(ctx, kinds, []string{"name"}, &content)
		if err != nil {
			return err
		}
		log.Printf("%d objects", len(content))
```

**Comment by kayshavd** [comment]
Thanks. The advantage with the ContainerView is that it retrieves everything in one shot.

-kayshav
[Platinum-Volunteer]
