### ISSUE TITLE
Incorrect vm network caused generic error

### ISSUE THREAD

**Issue by nitrocode** [vmware/govmomi#1568]
Originally created the ticket with the jetbrains packer provider https://github.com/jetbrains-infra/packer-builder-vsphere/issues/261 .

> product/version specific feature not supported by target

https://github.com/vmware/govmomi/blob/master/object/common.go#L33

The error was caused by choosing an incorrect network to attach to the new VM but the error is vague. It would be nice to be able to catch this and say that the network chosen does not exist.

**Comment by dougm** [comment]
Normally the message would be `network 'preprod' not found`.  But maybe in this case your DVS is named `preprod`?  Which results in the error being returned here:

https://github.com/vmware/govmomi/blob/7bdc20293f88555fafa0dcea88b7bc50831bf44b/object/distributed_virtual_switch.go#L38

We can certainly change that message there to make the problem more clear.

**Comment by nitrocode** [comment]
Thank you!
