### ISSUE TITLE
Why VirtualMachine has no reference to a cluster where it deployed  

### ISSUE THREAD

**Issue by spyroot** [vmware/govmomi#1591]
I was trying to figure out how I can find a cluster based on VM.   I checked VirtualMachine and I don't see any way to do that.  VM InventoryPath also doesn't hold the path to a cluster. 

The only way I found I can find co-relation.   Use finder to get cluster and it resource pool ID
and then take the VM resource pool ID. That will work only if a cluster has no resource pools.

Is there any way to put a filter on cluster

Where I can get all the filter values that I can use?

RetrieveWithFilter(ctx, kind, []string{"name"}, &vms, property.Filter{"name": "*_VM1"})

**Comment by dougm** [comment]
The ResourcePool.Owner field of the VM is the Cluster (or ComputeResource if standalone-host).
Been meaning to add a helper for this, does #1592 provide what you need?

**Comment by spyroot** [comment]
Yes, that perfect.
