### ISSUE TITLE
duplicate vm name semantics for (f *Finder) VirtualMachine

### ISSUE THREAD

**Issue by spyroot** [vmware/govmomi#1593]
Hi Folks,

I think you want to revise a case when you have a duplicate name for VM in the inventory.

For example, if you create folder X put VM with name test
Create another folder take test VM, clone and set name test.
(note I refer that when you do it via API) in UI you can't do that

So now you have two objects with the same name. ( i know it not important if you track the object by UUID etc)

but when you call it and you have duplicate name error not always return errors.  I guess it vCenter API and order depended. i.e MultipleFoundError not always returned for f.VirtualMachineList

I think semantically it should return a slice or always return an error if you have a duplicate. 
vCenter UI doesn't' allow you do that via UI but API looks like doesn't enforce duplicate name.
 and therefore I guess that check needs to be done by client and method return slice

```
if len(vms) > 1 {
	return nil, &MultipleFoundError{"vm", path}
}

```

```
func (f *Finder) VirtualMachine(ctx context.Context, path string) (*object.VirtualMachine, error) {
	vms, err := f.VirtualMachineList(ctx, path)
	if err != nil {
		return nil, err
	}
	if len(vms) > 1 {
		return nil, &MultipleFoundError{"vm", path}
	}
	return vms[0], nil
}
```

**Comment by dougm** [comment]
`VirtualMachineList` never returns `MultipleFoundError`.  Seems like it should work as you'd expect in this case if you want both VMs.

If you're only looking for 1 of the VMs with the same name, you can specify the folder: `VirtualMachine("my-folder-name/my-vm-name")`

**Comment by spyroot** [comment]
Xmm strange. I'll try to re-create it again.

**Comment by spyroot** [comment]
couldn't replicate.  ill reopen if I hit same issue
