### ISSUE TITLE
Cross vCenter clone example

### ISSUE THREAD

**Issue by ghaabor** [vmware/govmomi#1600]
Hey,

I wanted to put together a cross vCenter clone code based on a PowerShell example but I can't make it work - the task fails with `Error: A general system error occurred: Invalid argument`.
I tried to base my solution on this example: https://github.com/lamw/vghetto-scripts/blob/master/powershell/xNew-VM.ps1

Do you, by any chance, have a working code snippet using govmomi for cross vCenter clone?

**Comment by ghaabor** [comment]
Here's the VM clone spec I'm trying to use for some context:

```golang
	spec := types.VirtualMachineCloneSpec{
		PowerOn:  false,
		Template: false,
		Location: types.VirtualMachineRelocateSpec{
			Service: &types.ServiceLocator{
				InstanceUuid: destClient.ServiceContent.About.InstanceUuid,
				Url:          destURL.String(),
				Credential: &types.ServiceLocatorNamePassword{
					Username: userInfo.Username(),
					Password: func() string { p, _ := userInfo.Password(); return p }(),
				},
			},
			Pool:      &destPoolRef,
			Folder:    &destFolderRef,
			Datastore: &destDatastoreRef,
			Host:      &destHostRef,
		},

		Config: &types.VirtualMachineConfigSpec{
			NumCPUs:           sourceVMDetails.Config.Hardware.NumCPU,
			NumCoresPerSocket: sourceVMDetails.Config.Hardware.NumCoresPerSocket,
			CpuAllocation: &types.ResourceAllocationInfo{
				Reservation: sourceVMDetails.Config.CpuAllocation.Reservation,
				Limit:       sourceVMDetails.Config.CpuAllocation.Limit,
			},
			MemoryMB: int64(sourceVMDetails.Config.Hardware.MemoryMB),
			MemoryAllocation: &types.ResourceAllocationInfo{
				Reservation: sourceVMDetails.Config.MemoryAllocation.Reservation,
				Limit:       sourceVMDetails.Config.MemoryAllocation.Limit,
			},
			Name: vmName,
			Tools: &types.ToolsConfigInfo{
				AfterPowerOn: &(&struct{ b bool }{true}).b,
				ToolsVersion: sourceVMDetails.Config.Tools.ToolsVersion,
			},
		},
	}
```

**Comment by ghaabor** [comment]
Okay, I've solved this issue, `destURL.String()` includes login data as well and the client didn't like it - now ran into other issues. The example would be still appreciated sometimes.

**Comment by dougm** [comment]
What are the other issues?  I'm not aware of anyone else having tried cross vCenter clone using govmomi, so I don't know of any examples in Go.

**Comment by ghaabor** [comment]
@dougm Sorry we ditched this solution in the end because the vSphere reported an empty, cryptic error message. It was the same error for my Go implementation and with a theoretically working PowerShell example. I gave up because I suspect a vCenter version mismatch (or something similarily hard to debug) but nothing useful information was included in the actual vSphere error message. I could not find any resources in relation of the cross-vCenter clone and the error message being empty.

**Comment by dougm** [comment]
There are cases where the vSphere Fault message doesn't help, but there could be more info deeper in the Fault structure.  You can see the full structure using govc with `-debug` or even just dropping this into your code:
```go
pretty.Printf("err=%# v\n", err)
```
If you're able to share the PowerShell script, maybe someone can help with getting it to work from Go.
