### ISSUE TITLE
Simulator fails if RemoveSnapshot with no parent

### ISSUE THREAD

**Issue by Shuang-Wang** [vmware/govmomi#1601]
https://github.com/vmware/govmomi/blob/11e0fe163a8ad549eb553a0e6fac5852685f9480/simulator/snapshot.go#L119
If the current snapshot does not have a parent, parent becomes (*types.ManagedObjectReference)(nil). This causes Update to fail.

I think this test case https://github.com/vmware/govmomi/blob/11e0fe163a8ad549eb553a0e6fac5852685f9480/vim25/mo/type_info_test.go#L34 try to capture this issue, but in reality this would fail.

**Comment by dougm** [comment]
@Shuang-Wang can you expand on what you mean by "fail" in this case?
