### ISSUE TITLE
Login vc failed when password contains "*" on Windows

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1612]
![Uploading 11.png…]()

Using govc with a vCenter on VMC, which commonly has special characters in its password. Error shown as the screenshot.

**Comment by nanw1103** [comment]
The error says:
govc_windows_amd64.exe: open <my-password-with-*>: The filename, directory name, or volume label syntax is incorrect.

**Comment by dougm** [comment]
@nanw1103 your screenshot didn't render, but I can see the issue.  #1613 should fix that.
