### ISSUE TITLE
Convert 'performance.EntityMetric' to 'GetVirtualDevice' (device id).

### ISSUE THREAD

**Issue by sttyru** [vmware/govmomi#1614]
Hello!

How I can convert a result of 'GetVirtualDevice' to a name 'performance.EntityMetric'? I need convert 'deviceid' numeric (e.g. '2000' for disk) to 'deviceid' words (e.g. 'scsi0:0').

Thanks!

**Comment by dougm** [comment]
LIke this? https://github.com/vmware/govmomi/issues/1457#issuecomment-493550917

**Comment by sttyru** [comment]
> LIke this? [#1457 (comment)](https://github.com/vmware/govmomi/issues/1457#issuecomment-493550917)

Yeah. I found early that comment (and I use that :) ). But I need more universal function - for ethernet card, fc controllers and another devices. Is this possible?
