### ISSUE TITLE
library empty when using a subscription library

### ISSUE THREAD

**Issue by nORKy54** [vmware/govmomi#1615]
Hi
I have one VCenter with 2 contents library on différents Datacenter/Datastore
1 library is subscribing to the other
In Web client, all libraries are sync and I can see my templates in my subscribing library
```
$ govc library.ls /                    
/library-dc-srv-a01
/library-dc-srv-b01
$ govc library.ls /library-dc-srv-a01/ 
/library-dc-srv-a01/ISO#Win_Server_STD_CORE_2019_1809.1_64Bit_English
/library-dc-srv-a01/ISO#MSSQL STD 2012 SP2
[...]
$ govc library.ls /library-dc-srv-b01/
$
```

GOVC return an empty library. Where is the bug ?

**Comment by dougm** [comment]
Which version of govc?  This is fixed in #1542 , which was after the 0.21 release, but there is a pre-release version available: https://github.com/vmware/govmomi/releases/tag/prerelease-v0.21.0-58-g8d28646

**Comment by nORKy54** [comment]
```
govc version
govc 0.21.0
```
I will try the pre-release

**Comment by nORKy54** [comment]
I tested and you are right, it works now. Sorry for this ticket, you can close it

**Comment by dougm** [comment]
ok, good to hear it works for you now.
