### ISSUE TITLE
import.ovf will always try to find nvram file even the exported vm does not have a disk

### ISSUE THREAD

**Issue by bbdsxl** [vmware/govmomi#1616]
As govc does not support SATA controller, so I created an empty VM with needed controller and cdrom while does not have any hard disk and network adapter, then I tried to import the ovf while always got below error:
govc: open test1/disk-0.nvram: no such file or directory

If the VM does not have any disk, I think govc also should not look for the nvram file, right?

**Comment by dougm** [comment]
Not sure I understand how to reproduce, do you have a small test case you can share?

In any case we ought to implement #1219
