### ISSUE TITLE
Seeking help: how can I specify OVF property with import.ovf command?

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1617]
My OVA has mandatory OVF properties (vApp property), how can I specify that during deployment?

My command looks like: 
govc import.ovf --options=ova-spec.json ./photon-ova.ovf
[20-09-19 18:04:09] Warning: Line 85: Invalid value 'None' for element 'Connection'.
[K[20-09-19 18:04:19] Uploading photon-ova-disk1.vmdk... OK00%, 14.8MiB/s)
[20-09-19 18:04:19] Powering on VM...
govc: Property 'Activation_Key' must be configured for the VM to power on.

**Comment by dougm** [comment]
Not sure, but maybe adding that to the `PropertyMapping` section of photon-ova.ovf?

**Comment by nanw1103** [comment]
It's a property that needs to be specified by the user during OVA deployment. For example, if we deploy the OVA using vCenter UI, then it asks for that property. Normally such properties are for network configuration, security pairing keys, etc., for bootstrapping purpose.

Did not find a way with govc to specify that. Some old issue ticket shows that a proposal to use "-prop=key:value", but that's not recognized by the latest released govc.

Need help here. This is a key blocker for automation.

**Comment by dougm** [comment]
If you see it in the UI, then you should see it the output of `govc import.spec photon-ova.ovf`, used as your `--options ova-spec.json`

If not, can you share your photon-ova.ovf descriptor?

**Comment by nanw1103** [comment]
ova-spec.json works. Thanks. 

Close ticket.
