### ISSUE TITLE
Upload a file with 0 size to guest results 500 error

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1618]
D:\avatar>govc guest.upload -perm=777 -l=user:pass -vm=my-vm ./bootstrap.sh /deployer/bootstrap.sh
[K[20-09-19 18:32:48] Uploading... Error: 500 Internal Server Error
govc: 500 Internal Server Error

**Comment by dougm** [comment]
I don't think the vSphere API used by `guest.upload` supports empty files, but you can use `guest.touch` to create an empty file.
