### ISSUE TITLE
mac address

### ISSUE THREAD

**Issue by spyroot** [vmware/govmomi#1624]
Hi Folks,

If I add an adapter to existing VM

```
device, err := object.EthernetCardTypes().CreateEthernetCard("vmxnet3", backing)
newCard, ok := device.(types.BaseVirtualEthernetCard)
log.Print(newCard.GetVirtualEthernetCard().MacAddress)

```
Why mac address field is empty?  I assume mac allocate automatically and it probably in respond no?

Kind Regards,
MB>

**Comment by dougm** [comment]
MacAddress isn't generated until you've called Reconfigure and the VM is powered on.
