### ISSUE TITLE
GOVC_USERNAME and GOVC_PASSWORD works on Windows but failed on Linux

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1626]
I have two scripts with the same logic for both Windows and Linux. The Windows script worked well but the Linux not.

The error on Linux is "govc: NotAuthenticated"

For Linux, the script looks like the following, which does NOT work for me:
set GOVC_INSECURE=1
set GOVC_URL=https://%VC_HOST%/sdk
set GOVC_USERNAME=%VC_USERNAME%
set GOVC_PASSWORD=%VC_PASSWORD%
govc ls

I had to change it to the following to work:
set GOVC_INSECURE=1
set GOVC_URL=https://%VC_USERNAME%:%VC_PASSWORD%@%VC_HOST%/sdk
govc ls

While at the same time using GOVC_USERNAME and GOVC_PASSWORD worked on Windows.

**Comment by dougm** [comment]
The `set` command won't work.  You need to use `export`.  Maybe GOVC_URL was already exported.

https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html

**Comment by nanw1103** [comment]
Sorry that I copied the Windows script out, which leads to some confusion. 

Created tiny test script to show the failure:

`
asdf@hlcm-deployer-builder:~/avatar$ cat failure.sh
#!/bin/bash
export GOVC_INSECURE=1
export GOVC_URL=https://10.117.160.100/sdk
export GOVC_USERNAME=asdf
export GOVC_PASSWORD=asdf
govc ls

asdf@hlcm-deployer-builder:~/avatar$ ./failure.sh
govc: NotAuthenticated

asdf@hlcm-deployer-builder:~/avatar$ cat success.sh
#!/bin/bash
export GOVC_INSECURE=1
export GOVC_URL=https://asdf:asdf@10.117.160.100/sdk
govc ls
govc version
govc about

asdf@hlcm-deployer-builder:~/avatar$ ./success.sh
/nanw/vm
/nanw/network
/nanw/host
/nanw/datastore
govc 0.21.0
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        13007421
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.2
Product ID:   vpx
UUID:         05a06dd2-edef-4ba6-877e-4490b43201f8

asdf@hlcm-deployer-builder:~/avatar$ uname -a
Linux hlcm-deployer-builder 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by dougm** [comment]
I can't reproduce.  Does this work for you..

Start vcsim and specify the username/password to require for auth:

```console
% vcsim -username asdf -password asdf
export GOVC_URL=https://asdf:asdf@127.0.0.1:8989/sdk GOVC_SIM_PID=19898
```

Client test:

```console
% export GOVC_INSECURE=true

% GOVC_URL=https://asdf:asdf@127.0.0.1:8989/sdk govc ls | wc -l
4

% GOVC_URL=https://127.0.0.1:8989/sdk GOVC_USERNAME=asdf GOVC_PASSWORD=asdf govc ls | wc -l
4
```

**Comment by dougm** [comment]
One way I can force reproduce:
```console
% touch ./asdf # govc will treat as a file containing username or password
% GOVC_URL=https://127.0.0.1:8989/sdk GOVC_USERNAME=asdf GOVC_PASSWORD=asdf govc ls | wc -l
govc: NotAuthenticated
0
```

**Comment by nanw1103** [comment]
It results that my directory contains a name exactly named asdf, which matches the password (or username?)... That leads to failure.

Suggest to have a better error messaging for this. 
Thanks for the help. Close ticket.
