### ISSUE TITLE
object.QueryChangedDiskAreas() not work, which params should I give?

### ISSUE THREAD

**Issue by Qliphort** [vmware/govmomi#1630]
`	u := &url.URL{
		Scheme: "https",
		Host:	ip,
		Path:	"/sdk",
	}
	ctx := context.Background()
	u.User = url.UserPassword(user, password)
	client, err := govmomi.NewClient(ctx, u, true)
	if err != nil {
		panic(err)
	}
	//fmt.Println(client)
	vm, err := get_obj(ctx, *client, "VirtualMachine", vmname)
	if err != nil {
		panic(err)
	}
	obj_vm = object.NewVirtualMachine(client.Client, vm.Reference())

	devicelist, err := obj_vm.Device(ctx)

	disks := devicelist.SelectByType((*types.VirtualDisk)(nil))

	disk, _ := FindDisk(ctx, disks)

	println("---------------------------------------------------------")

	DCinfo, _ := obj_vm.QueryChangedDiskAreas(ctx, nil, vm.Snapshot.CurrentSnapshot, disk, 0)

	println(DCinfo.ChangedArea)`
I want to get the changeblock info by using this methods,but it doesn't work, what params should I give? Is there any problem in using?

**Comment by Qliphort** [comment]
@dominiquelefevre Hello?Could you please tell me how to use it?

**Comment by dominiquelefevre** [comment]
Hi Qliphort,

changes are tracked between *two snapshots*, not between the "initial state of a VM" (whatever that may be) and a snapshot.

> obj_vm.QueryChangedDiskAreas(ctx, nil, vm.Snapshot.CurrentSnapshot, disk, 0)

Instead of nil and vm.Snapshot.CurrentSnapshot there must be two snapshots to compute diff between.

Also make sure that CBT is enabled on a VM before you create snapshots of it.

**Comment by Qliphort** [comment]
> Hi Qliphort,
> 
> changes are tracked between _two snapshots_, not between the "initial state of a VM" (whatever that may be) and a snapshot.
> 
> > obj_vm.QueryChangedDiskAreas(ctx, nil, vm.Snapshot.CurrentSnapshot, disk, 0)
> 
> Instead of nil and vm.Snapshot.CurrentSnapshot there must be two snapshots to compute diff between.
> 
> Also make sure that CBT is enabled on a VM before you create snapshots of it.

Got it, thank you very much！
