### ISSUE TITLE
Create 6.7 ESXi hosts

### ISSUE THREAD

**Issue by vamp911** [vmware/govmomi#1637]
Is it possible to be able to create 6.7 esxi hosts in vcsim? The vcsim hosts we are testing our powershell deployment code on seem to be 6.5 but our deployments are keep failing in production because our production hosts are 6.7.

**Comment by dougm** [comment]
Are there specific 6.7 fields your powershell code needs?  Or is it just a version check?

When #1623 gets merged, you'll be able to record a real vCenter environment and load it into vcsim.

**Comment by dougm** [comment]
Feature docs are here: https://github.com/vmware/govmomi/wiki/vcsim-features#record-and-playback

Feedback welcome.
