### ISSUE TITLE
Weird 404 behavior with tags.GetCategory() when no category exists

### ISSUE THREAD

**Issue by jh125486** [vmware/govmomi#1639]
Currently if there is no named category during a `tags.GetCategory()` call, it defaults to assuming that is must be a category ID, and attempts to retrieve it directly from the API (`https://github.com/vmware/govmomi/blob/master/vapi/tags/categories.go#L132`).

So if a tag category doesn't exist this results in an error (404 not found), when it should probably just return a nil ptr and no error (since there was no actual error produced from the API).

Should I just put a PR in for this?

**Comment by dougm** [comment]
I see what you mean, but not sure about changing the behavior at this point as it could introduce panic() in existing code.  How about if we make the behavior optional?  For example, add a field to `tags.Manager` and if that field is `true`, return `nil, nil` when not found by name.

Another option would be to pull out the `if isName()` conditionals into their own `Find*` methods.

What do you think?

**Comment by jh125486** [comment]
Another method entirely might be better, since the underlying HTTP status codes aren’t being returned and therefore can only be string checked.

V/r
Jacob Hochstetler

________________________________

**Comment by dougm** [comment]
There are other cases where returning the status code as part of the `error` would be useful. Thinking of something like:
```go
err := client.Foo(...)
if err != nil {
    if status, ok := err.(*rest.StatusError); ok {
        if status.Code == http.NotFound {
           ...
        }
    }
}
```

What do you think?

In the meantime, there is an option of using:
```go
if strings.HasSuffix(err.Error(), http.StatusText(http.StatusNotFound)) {
```

Where `Error()` in that case is: https://github.com/vmware/govmomi/blob/master/vapi/rest/client.go#L86-L88

**Comment by rikatz** [comment]
We are now exposing the error check via https://github.com/vmware/govmomi/pull/3310

basically `rest.IsStatusError(err error, code int)` can be used to see if the underlying error is 404, 503, etc.

I will close this issue, let me know if this covers your case!
