### ISSUE TITLE
GetResourceUsage returns different storage capacity values 

### ISSUE THREAD

**Issue by vamshinannuta** [vmware/govmomi#1645]
I am interested in cluster resources summary. So I am using GetResourceUsage method from methods package. StorageCapacityMB is one of the field returned by this method. According to VMWare documentation StorageCapacityMB is total storage capacity of all the accessible data stores in that cluster. The storage capacity values returned by this method keeps changing. Shouldn't these values remain same for a given cluster? 

```go
resourcesSummary, err := methods.GetResourceUsage(ctx, vcc.client.Client.RoundTripper, &types.GetResourceUsage{This: cluster.Reference()})
    if err != nil {
        log.Error(err)
        return nil, err
    }
fmt.Println(resourcesSummary.Returnval.StorageCapacityMB)
```

This part of the code is returning different values.
Can you lets us know if there is any issue from your side ?

**Comment by dougm** [comment]
I haven't looked into it yet, but govmomi is just calling the vCenter method directly, I don't think this is an issue on the govmomi side.

**Comment by dougm** [comment]
Can you take a look at the new govc cluster.usage command?  It doesn't use the GetResourceUsage method, and I still haven't looked into it myself, but curious how the numbers compare: https://github.com/vmware/govmomi/blob/998e586d0682d5b3b23610b870993e6c6a993b33/govc/cluster/usage.go#L104-L112
