### ISSUE TITLE
virtual machine rename operation is failing through Ansible

### ISSUE THREAD

**Issue by ngp-star** [vmware/govmomi#1650]
HI,
we are trying rename vm operation from Ansible playbook, as part of Ansible integration test process.
while running Ansible integration test on vmware_guest module, we are getting following error when the task of renaming the vm operation comes.
 
followoing is the playbook used.
- name: Rename a virtual machine
  vmware_guest:
    validate_certs: False
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    state: present
    use_instance_uuid: True
    uuid: "{{ vm1_instance_uuid }}"
    name: test_vm2
  register: rename_vm

- debug: var=rename_vm

- name: assert that changes were made
  assert:
    that:
      - rename_vm is changed

following is the error trace.

fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/ngp/.ansible/tmp/ansible-tmp-1570180354.8751879-281010951710795/AnsiballZ_vmware_guest.py\", line 116, in <module>\n    _ansiballz_main()\n  File \"/Users/ngp/.ansible/tmp/ansible-tmp-1570180354.8751879-281010951710795/AnsiballZ_vmware_guest.py\", line 108, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/ngp/.ansible/tmp/ansible-tmp-1570180354.8751879-281010951710795/AnsiballZ_vmware_guest.py\", line 54, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vmware_guest', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware_guest_payload_3p0pz0lo/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2849, in <module>\n  File \"/tmp/ansible_vmware_guest_payload_3p0pz0lo/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2801, in main\n  File \"/tmp/ansible_vmware_guest_payload_3p0pz0lo/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2559, in reconfigure_vm\n  File \"/Users/ngp/vmwareansible/ansible/venv-ansible-python3/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py\", line 706, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/Users/ngp/vmwareansible/ansible/venv-ansible-python3/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py\", line 512, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/Users/ngp/vmwareansible/ansible/venv-ansible-python3/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py\", line 1397, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.MethodNotFound: (vmodl.fault.MethodNotFound) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'VirtualMachine:vm-80 does not implement: Rename_Task',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   receiver = 'vim.VirtualMachine:vm-80',\n   method = 'Rename_Task'\n}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

affected components of go-vmomi:- "govcsim"--https://github.com/vmware/govmomi/blob/master/vcsim.

this issue is observed while running against with go-vcsim component, it works fine with actual vcenter.

**Comment by dougm** [comment]
@ngp-star fixed in #1653

**Comment by ngp-star** [comment]
hi @dougm 
thanks for the update and the fix.

As part of Ansible Integration  test its using quay.io/ansible/vcenter-test-container docker  image, as of now this rename fix is not there with this image so to have rename vm fix into this image when we can get the docker image for this govmomi.

regards
naveen

**Comment by dougm** [comment]
@ngp-star you'll have to ask the Ansible folks that maintain that image

**Comment by ngp-star** [comment]
@dougm sure
