### ISSUE TITLE
guest.run, stdio error and expect

### ISSUE THREAD

**Issue by rbucker** [vmware/govmomi#1657]
I'm trying to expand my drive

```
govc guest.run -vm photon4 /bin/echo 1 \> /sys/class/block/sda/device/rescan
govc vm.disk.change -vm photon4 -disk.name disk-1000-0 -size 32G
govc guest.run -vm photon4 /usr/bin/expect -c "spawn /usr/sbin/parted /dev/sda -l; expect -re \"Fix/Ignore?\"; send \"f\r\n\"; set timeout -1; expect -re \"Complete\!\"; "
govc guest.run -vm photon4 /usr/sbin/parted /dev/sda resizepart 2 100%
govc guest.run -vm photon4 /usr/sbin/resize2fs /dev/sda2
```

I call  ```parted```  and it seems that ```guest.run``` and ```guest.start``` do not work. I'm not sure but it could be related to the response ```govc: ServerFaultCode: File /proc/1232/stdout was not found``` or it could be the construction.

Don't get too wrapped up in this ```expect``` as in I tried a number of different quoting but still nothing worked. I assume there is a better way!

```
govc guest.run -vm photon4 /usr/bin/expect -c "spawn /usr/sbin/parted /dev/sda -l; expect -re \"Fix/Ignore?\"; send \"f\r\n\"; set timeout -1; expect -re \"Complete\!\"; "
```

**Comment by dougm** [comment]
See: 

https://github.com/vmware/govmomi/issues/1514#issuecomment-507666230

https://github.com/vmware/govmomi/issues/1514#issuecomment-508149851

https://github.com/vmware/govmomi/issues/1514#issuecomment-525120784

**Comment by rbucker** [comment]
@dougm that solves part of the question... Now will those changes and which in particular fix my ```expect``` issue?

**Comment by dougm** [comment]
I suggest testing your expect command locally using `bash -c` as https://github.com/vmware/govmomi/issues/1514#issuecomment-525120784 suggests.

Or, just write a script and use `guest.upload` to copy the script file into the guest.

**Comment by dougm** [comment]
#1752 removes the toolbox deps, feedback welcome.
