### ISSUE TITLE
govc: flag provided by not defined: -prop

### ISSUE THREAD

**Issue by rinat-vmware** [vmware/govmomi#1659]
Based on https://github.com/vmware/govmomi/issues/288#issuecomment-129637911 ```-prop``` should be available with ```import.ova```.

Tried it many different ways and consistently getting problem with it:

```
$ govc import.ova -options=/tmp/my_json.json -prop="NTP":"10.217.31.2" /ovas/my_ova.ova
govc: flag provided but not defined: -prop
```

rather older version of govc is used in this case (from March, 2017 https://github.com/vmware/govmomi/releases/tag/v0.13.0)

```
$ govc version
govc 0.13.0
```

so fix for https://github.com/vmware/govmomi/issues/288 should be included in it. 
For some reason though  there is no ```-prop``` option in output:

```
$ govc import.ova --help
Usage: govc import.ova [OPTIONS] PATH_TO_OVA

Options:
  -cert=                                  Certificate [GOVC_CERTIFICATE]
  -dc=DC-TEST                             Datacenter [GOVC_DATACENTER]
  -debug=false                            Store debug logs [GOVC_DEBUG]
  -ds=datastore-esxi3                     Datastore [GOVC_DATASTORE]
  -dump=false                             Enable output dump
  -folder=                                Path to folder to add the VM to
  -host=                                  Host system [GOVC_HOST]
  -host.dns=                              Find host by FQDN
  -host.ip=                               Find host by IP address
  -host.ipath=                            Find host by inventory path
  -host.uuid=                             Find host by UUID
  -json=false                             Enable JSON output
  -k=true                                 Skip verification of server certificate [GOVC_INSECURE]
  -key=                                   Private key [GOVC_PRIVATE_KEY]
  -name=                                  Name to use for new entity
  -options=                               Options spec file path for VM deployment
  -persist-session=true                   Persist session to disk [GOVC_PERSIST_SESSION]
  -pool=/DC-TEST/host/CL-TESTS/Resources  Resource pool [GOVC_RESOURCE_POOL]
  -tls-ca-certs=                          TLS CA certificates file [GOVC_TLS_CA_CERTS]
  -tls-known-hosts=                       TLS known hosts file [GOVC_TLS_KNOWN_HOSTS]
  -u=https://@10.115.70.12/sdk            ESX or vCenter URL [GOVC_URL]
  -vim-namespace=urn:vim25                Vim namespace [GOVC_VIM_NAMESPACE]
  -vim-version=6.5                        Vim version [GOVC_VIM_VERSION]
```

**Comment by dougm** [comment]
That comment says "proposal", the flag was never actually added to govc.  Maybe the proposal to add such a flag could still be considered, but `-options` is still the current mechanism to set properties when importing.

cc @bruceadowns

**Comment by rinat-vmware** [comment]
ah, I see, thank you for clarification @dougm, that helps.
It would be great if support for this flag will be added.

BTW, also tried with ```-options=``` by updating information in ```PropertyMapping``` section in JSON file obtained by ```govc import spec ...``` command, but those are now hitting error like this one: ```govc: Property IP_Address is not user configurable.```. Looking into this, so if you happen to have any suggestion please feel free to let me know.

**Comment by dougm** [comment]
Sounds like that has to do with the .ovf you're using.  In there you'll see `ovf:userConfigurable="false"`

From https://www.dmtf.org/sites/default/files/standards/documents/DSP2017_2.0.0a.pdf :
> The ovf:userConfigurable attribute determines if the value provided is a default value and  changeable at deployment or is not changeable

**Comment by rinat-vmware** [comment]
Right, just extracted ```ova``` file and sure enough in ```ovf``` file and see parameters are set to ```ovf:userConfigurable="false"```  :(
Something to keep in mind In case ```-prop``` gets implemented down the road.
