### ISSUE TITLE
KEY_ENTER generating parse error

### ISSUE THREAD

**Issue by rbucker** [vmware/govmomi#1664]
in version v0.21.0-58-g8d28646

```
govc: strconv.ParseInt: parsing "KEY_ENTER": invalid syntax
```

**Comment by dougm** [comment]
The tag `v0.21.0-58-g8d28646` does not include #1649
You need to build from source to use it currently: https://github.com/vmware/govmomi/blob/master/govc/README.md#source

**Comment by rbucker** [comment]
Thanks
