### ISSUE TITLE
does not like spaces

### ISSUE THREAD

**Issue by rbucker** [vmware/govmomi#1665]
in version v0.21.0-58-g8d28646

```
govc vm.keystrokes -vm $vm -s "sudo passwd rancher"  
```

returns

```
govc: invalid Character   in String: sudo passwd rancher
```

**Comment by dougm** [comment]
The tag v0.21.0-58-g8d28646 does not include #1649
You need to build from source to use it currently: https://github.com/vmware/govmomi/blob/master/govc/README.md#source

**Comment by rbucker** [comment]
Thanks
