### ISSUE TITLE
Unable to update individual port under a DVS portgroup

### ISSUE THREAD

**Issue by jingyizPensando** [vmware/govmomi#1667]
Hi VMware team,

We are able to create a DVS and add portgroup to it. We set "VlanOverrideAllowed" to be true when formalizing "types.DVPortgroupConfigSpec.Policy". 

We can see that portgroup is being created with Vlan override enabled. Then we want to config individual port under this portgroup(for example, we want to change a vlan of one port, all other ports remain the same vlan with the portgroup).

We use "FetchDVPorts" to get all the ports which meet the criteria. "FetchDVPorts" returns an array of DistributedVirtualPort.

For example:
`ports, err := dvs.FetchDVPorts(ctx, &criteria)`

This one completed successfully. We are able to dump information of each port.

Our goal is to update individual port under a DVS portgroup. We were not able to find any API to reconfigure individual port(Reconfigure(ctx context.Context, spec types.DVPortgroupConfigSpec) is only for updating portgroup).

We add our own API to update individual port under portgroup by calling ReconfigureDVPort_Task: 

```
func (p DistributedVirtualPortgroup) ReconfigureDvsPort(ctx context.Context, spec []types.DVPortConfigSpec) (*Task, error) {
    req := types.ReconfigureDVPort_Task{
        This: p.Reference(),
        Port: spec,
    }
​
    res, err := methods.ReconfigureDVPort_Task(ctx, p.Client(), &req)
    if err != nil {
        return nil, err
    }
​
    return NewTask(p.Client(), res.Returnval), nil
}

```

Below is our way to update the port[0](first port in the array) by leveraging our own API above:

```
ports, err := myDVS.ObjDvs.FetchDVPorts(ctx, &criteria)

portVlan := new(types.VmwareDistributedVirtualSwitchVlanIdSpec)
portVlan.VlanId = vlanId

portSpec := types.DVPortConfigSpec{
    ConfigVersion: ports[0].Config.ConfigVersion,
    //Description:   ports[0].Config.Description,
    Key: ports[0].Key,
    //Name:          ports[0].Config.Name,
    Operation: string("edit"),
    Scope:     ports[0].Config.Scope,
    Setting: &types.VMwareDVSPortSetting{
        Vlan: portVlan,
    },  
} 

task, err := myPG.ObjPg.ReconfigureDvsPort(ctx, []types.DVPortConfigSpec{portSpec})
```

We can see an error after calling this "ReconfigureDvsPort"
"ServerFaultCode: The request refers to an unexpected or unknown type"

By looking at govmomi struct and APIs, I feel we should support updating individual port under a DVS portgroup. But I am not able to make it work. Can you please help me with it?

All the best
Jingyi

**Comment by dougm** [comment]
I haven't used this API myself, but it looks like `This` should be a switch, rather than a portgroup:

https://code.vmware.com/apis/196/vsphere/doc/vim.DistributedVirtualSwitch.html#reconfigurePort

> A reference to the DistributedVirtualSwitch ...

**Comment by jingyizPensando** [comment]
Thanks Doug. After changing to DistributedVirtualSwitch, it works. 
Should we add API similar like this to object/distributed_virtual_switch.go? There is a need for developers to update individual port within a DVS domain.

```
func (s DistributedVirtualSwitch) ReconfigureDvsPort(ctx context.Context, spec []types.DVPortConfigSpec) (*Task, error) {
    req := types.ReconfigureDVPort_Task{
        This: s.Reference(),
        Port: spec,
    }

    res, err := methods.ReconfigureDVPort_Task(ctx, s.Client(), &req)
    if err != nil {
        return nil, err
    }

    return NewTask(s.Client(), res.Returnval), nil
}
```

**Comment by dougm** [comment]
@jingyizPensando glad its working for you.  Yes, can you submit Pull Request to add that method?

**Comment by jingyizPensando** [comment]
Sure.
