### ISSUE TITLE
event   and  task api

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1673]

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67058339-021f5e80-f187-11e9-9e43-0e3602940611.png)

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67058572-fa13ee80-f187-11e9-8548-4b2037118f6b.png)
The task name has Chinese, the library interface is returned in English;Some data is also missing

**Comment by dougm** [comment]
Maybe you want to set `session.Locale` ?
https://github.com/vmware/govmomi/blob/a9b0a80589c6b412b139f2cec86efff6a40b7ddc/session/manager.go#L34-L35

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67083889-8c3ee580-f1ce-11e9-9a90-676183171490.png)
The task name is still in English, and the event description has changed to Chinese.Can change the task name to Chinese?Thank you very much

**Comment by dougm** [comment]
Not that I know of: https://code.vmware.com/apis/196/vsphere/doc/vim.TaskInfo.html
Note that `entityName`, `description` and `error` are documented as being locale-specific, but `name` is not.

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67172180-dbfaf800-f3ec-11e9-885f-76a5d1008a33.png)
How to set the task name to Chinese? Thank you very much

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67172416-d7830f00-f3ed-11e9-83ff-29257e67696e.png)
状态信息不对，或者没有更新；还有些数据为空

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67172540-4bbdb280-f3ee-11e9-9bd8-b12b088f03ee.png)

**Comment by sirzhanghai** [comment]
> ![image](https://user-images.githubusercontent.com/38032852/67172416-d7830f00-f3ed-11e9-83ff-29257e67696e.png)
> 状态信息不对，或者没有更新；还有些数据为空

Incorrect status information or no update;Some of the data is empty

**Comment by sirzhanghai** [comment]
![image](https://user-images.githubusercontent.com/38032852/67172902-b8857c80-f3ef-11e9-8ff3-ed55f3f6556d.png)

**Comment by dougm** [comment]
If a task is in the queued state, it is expected that `StartTime` and `CompleteTime` are nil.

I believe the questions here are answered, feel free to re-open if not.

**Comment by liqinshan** [comment]
> ![image](https://user-images.githubusercontent.com/38032852/67172180-dbfaf800-f3ec-11e9-885f-76a5d1008a33.png)
> How to set the task name to Chinese? Thank you very much
有邮箱或者其它联系方式么？想请教下task历史记录的一些问题

**Comment by liqinshan** [comment]
@sirzhanghai 有邮箱或者其它的联系方式么？想请教下关于task历史记录的一些问题
