### ISSUE TITLE
library commands does not work with subscribed content libraries

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1675]
I can use govc library.ls to list contents of a local content library, however, all the library commands do not work with subscribed content libraries.
E.g. It seems impossible to deploy an OVF template from a subscribed content library.

This is a blocker for some automation scenarios. Please advise. Workaround appreciated.

**Comment by nanw1103** [comment]
# govc version
govc 0.21.0

# govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.9.1
Build:        14621801
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.9.1
Product ID:   vpx
UUID:         ffa49bc9-996c-44b3-bb55-8d22286ad2a3

**Comment by dougm** [comment]
library.ls fixed in #1542 and rm fixed in #1635

You can build from source to get the fixes: https://github.com/vmware/govmomi/blob/master/govc/README.md#source

If you still have issues, please include the specific commands that are not working.
