### ISSUE TITLE
pool.destroy fails silently, which is inconsistent with other commands.

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1679]
For example, object.destroy will fail (exit 1) when the object is not found.
However pool.destroy fails silently, always returns 0.

I see such inconsistency is a bug. Please advise.

**Comment by federico-pellegatta** [comment]
Given that `pool.destroy` accepts a list of resource pools, is it fair to fail if at least one pool does not exist? @dougm

*(example)* Someone may relay on `pool.destroy` to succeed on already deleted pools.

**Comment by dougm** [comment]
Not sure why this was done, but I think we can just remove this: https://github.com/vmware/govmomi/blob/5cc9f67181417bb4e7fa466e14e5daff0be2075f/govc/pool/destroy.go#L73-L76

That was part of this change way back: https://github.com/vmware/govmomi/commit/f10480af79902f7f1581aedb0e90425c79c41414
