### ISSUE TITLE
Do we have a reliable way of listening vCenter side of event

### ISSUE THREAD

**Issue by jingyizPensando** [vmware/govmomi#1681]
Hi VMware team,

Let's say we have a routine listening on vCenter side of events(could be VM bootup, portgroup modifications, etc), can current library guarantees that we will receive all the events that we are trying to listen and all of them will arrive in order and in time?

**Comment by embano1** [comment]
@jingyizPensando see this code where we leveraging event streaming: https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/29/files#diff-86464a10eae28c2fb1e70bd9e2a63765

Ordered delivery, at-least-once delivery guarantees etc are highly dependent on what you want to do and how your overall architecture looks like. We have an issue in our code where we are also thinking about at-least-once and ordered delivery: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/38
