### ISSUE TITLE
govc vm.clone not persisting disk uuids

### ISSUE THREAD

**Issue by jacobweinstock** [vmware/govmomi#1682]
Hi there. I am seeing an issue in govc `0.21.0`. When doing a `govc vm.clone`. The newly created VM disks do not have the same UUIDs as the original. If I do a manual clone in the vSphere Web UI of the same VM, the disks UUIDs are the same as the original VM. Maybe, I'm doing something incorrect on the clone or something else? Any help would be greatly appreciated.

clone command:
`govc vm.clone -vm storage-template1 -host x.x.x.x -ds my-ds-1 -folder=001 -on=false STORAGE01`
inspect disk UUID of original and clone:
```
# original
govc datastore.disk.info -uuid=true -ds=my-ds-2 storage-template1/storage-template1_4.vmdk
# clone
govc datastore.disk.info -uuid=true -ds=my-ds-1 STORAGE01/STORAGE01_4.vmdk
```

**Comment by dougm** [comment]
I think you just need to use the `-link` flag with `vm.clone`, have you tried that?

**Comment by dougm** [comment]
Confirmed with this above.
