### ISSUE TITLE
ResourceReductionToToleratePercent should not be omitempty

### ISSUE THREAD

**Issue by aeremenk0** [vmware/govmomi#1686]
ResourceReductionToToleratePercent could be between 0 and 100.
if ResourceReductionToToleratePercent set to 0 marshaller will consider it as empty and do not include it into the payload.

**Comment by dougm** [comment]
@aeremenk0 does #1687 work for you?

**Comment by aeremenk0** [comment]
@dougm: it is better to leave `ResourceReductionToToleratePercent` to be `int32` (remove pointer), if you just remove `omitempty` it will do. If you change type to `*int32` it will have implication for vshpere terraform provider.

**Comment by aeremenk0** [comment]
and I'm using the library from https://github.com/terraform-providers/terraform-provider-vsphere
