### ISSUE TITLE
Many metrics collection missing through govmomi.

### ISSUE THREAD

**Issue by anrav** [vmware/govmomi#1689]
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/METRICS.md

Many metrics are not collected even we enable to collect all metrics.
For E.g: 

show field keys from vsphere_host_cpu
name: vsphere_host_cpu
fieldKey                 fieldType
--------                 ---------
coreUtilization_average  float
costop_summation         integer
demand_average           integer
idle_summation           integer
latency_average          float
readiness_average        float
ready_summation          integer
reservedCapacity_average integer
swapwait_summation       integer
totalCapacity_average    integer
usage_average            float
usagemhz_average         integer
used_summation           integer
utilization_average      float
wait_summation           integer

**Comment by dougm** [comment]
Please provide more details.  "enable to collect all metrics", are you referring to telegraf or vCenter?  Some of those metrics may require a higher vCenter collection level: https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.monitoring.doc_50%2FGUID-25800DE4-68E5-41CC-82D9-8811E27924BC.html

**Comment by dougm** [comment]
Closing as stale. Feel free to reopen if this is still an issue.
