### ISSUE TITLE
Few of the metrics are not being collected by govmomi.

### ISSUE THREAD

**Issue by anrav** [vmware/govmomi#1690]
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/METRICS.md

Many metrics are not collected even we enable to collect all metrics.
For E.g: 

show field keys from vsphere_host_cpu
name: vsphere_host_cpu
fieldKey                 fieldType
--------                 ---------
coreUtilization_average  float
costop_summation         integer
demand_average           integer
idle_summation           integer
latency_average          float
readiness_average        float
ready_summation          integer
reservedCapacity_average integer
swapwait_summation       integer
totalCapacity_average    integer
usage_average            float
usagemhz_average         integer
used_summation           integer
utilization_average      float
wait_summation           integer

We are using telegraf to collect vcenter metrics.

**Comment by dougm** [comment]
dup of #1689
