### ISSUE TITLE
vm.clone is likely to fail due to conflict of vm name

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1694]
When using govc vm.clone, if another VM has the same name as the target VM that I'm cloning to, then an error message says: "...vmx already exists"
Example:
_govc vm.clone -vm $GOVC_FOLDER/$TMPL_WINSVR -on=false HzE-tmpl-workaround
govc: file [WorkloadDatastore] HzE-tmpl-workaround/HzE-tmpl-workaround.vmx already exists_

This happens even if the conflict VMs are in different resource pool and VM folder. It's the folder on datastore that conflicts.

Some may treat this as not an issue, but from a user's perspective, vCenter UI, and vCenter REST API works in such scenario, by renaming the datastore VM folder to things like "vm_1", "vm_2", etc.

In addition, I did not find any govc vm.clone parameter that can override this behavior. So my automation is totally blocked in such a scenario. 

This is a scenario that govc as a library should consider.

Please advise.

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmclone

>   -force=false           Create VM if vmx already exists

**Comment by nanw1103** [comment]
I use -force=true and VMs with the same name can be cloned (in different vm folders).
Thanks dougm. Closing ticket.
