### ISSUE TITLE
NewClient error "expected element type <Envelope> but have <html>"

### ISSUE THREAD

**Issue by manivannanpk** [vmware/govmomi#1695]
NewClient throws this error when I try to connect to a VSphere device like this:

	_url, err := url.Parse("http://192.168.1.100")
	if err != nil {
		return err
	}

	_url.User = url.UserPassword("username", "password")

	ctx, cancel := context.WithCancel(context.Background())
        defer cancel()

	client, cerr := govmomi.NewClient(ctx, _url, true)

Please let me know what is going wrong.

Thanks,
Mani

**Comment by dougm** [comment]
You need to include the path (/sdk) and probably want https for the scheme: `https://192.168.1.100/sdk`
Note that using `soap.ParseURL` adds the path by default.

**Comment by manivannanpk** [comment]
That works. Thanks.
