### ISSUE TITLE
Feature Request: Provide a govc way to "insert Content Lib IOS into VM"

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1697]
I'm using 
`govc device.cdrom.insert <abs-datastore-path.iso>`
and it works.
However it's pretty tricky to find that datastore path of an ISO file in a content library. It requires me to do something like: 
`POST /com/vmware/content/library/item/storage/id:<item_id>?~action=get, request_body={file_name}`
and then parse a JSON like:
`[ { size: 380928,
    storage_uris:
     [ 'ds:///vmfs/volumes/vsan:87e07c59c1b44113-aaa0fd3c9e7e27e5//contentlib-42724dd7-6162-4df2-967f-b407f0cbc3d1/7f0c0e82-8c60-4675-913b-08618a3efa35/tiny_db643b7a-f1fd-4508-9928-dae03aff48cc.iso?serverId=4efd9d2a-4c8d-44e6-ae50-2d38c4848ad5' ],
    cached: true,
    name: 'tiny.iso',
    storage_backing: { datastore_id: 'datastore-42', type: 'DATASTORE' },
    version: '1' } ]`

to get a MAGIC path in datastore for govc to use: 
`contentlib-42724dd7-6162-4df2-967f-b407f0cbc3d1/7f0c0e82-8c60-4675-913b-08618a3efa35/tiny_db643b7a-f1fd-4508-9928-dae03aff48cc.iso`
Note that the above path does not match that returned by "govc datastore.ls", which has a long id string replacing the "contentlib-" part. Both the above magic path, or a path composed with return value from govc datastore.ls works.

I think there should be an easy way:
1. Pure govc solution
2. Easy approach to reference content lib ISO file.

Please advise.

(BTW, the content library is a subscribed content library. due to https://github.com/vmware/govmomi/issues/1675 subscribed content lib does not work with the released version).

**Comment by nanw1103** [comment]
With vCenter UI, you can insert one content lib ISO into a CDROM of a VM, though sometimes that function is buggy with 500 server error, it's a user-friendly feature.

Not sure how govc could do this. Some draft ideas:

_suggestion 1_:

Extend the govc device.cdrom.insert command, to support an additional parameter:
`-library=<library-name>`
besides the existing
`-datastore=<ds-name>`

If -library is specified, the datastore is overrided (must not be explicitly specified). In this mode the last path parameter becomes the item path in the content library. The command could look like:

`govc device.cdroom.insert -library=myContentLib abc.iso`

_suggestion 2_:
Define a special path format to indicate a content lib resource. E.g.
`govc device.cdroom.insert library:///myContentLib/abc.iso`

**Comment by mtthlm** [comment]
Using `library.info -L` with `device.cdrom.insert` or `vm.create --iso` isn't exactly sufficient when the Content Library item exists on a different datastore than the VM you're creating/modifying. You have to make a separate call to get the Content Library datastore which is annoying.

**Comment by dougm** [comment]
See: https://github.com/vmware/govmomi/issues/3213#issuecomment-2148334914
