### ISSUE TITLE
"snapshot.remove *" fails

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1699]
The following command works:
`govc snapshot.remove <a-specific-snapshot-name>`
The following command does NOT work, which is different from the help text:
`govc snapshot.remove *`
Expect remove all snapshots but actually it dumps usage. This happens no matter the VM has snapshots, or without snapshots.

govc version: 0.21 (released)
govc version: 0.22 (master)
vCenter: Version:      6.9.1  Build:        14621801

**Comment by dougm** [comment]
Did you quote the `*` when running the command?
```console
% govc snapshot.remove '*'
```

**Comment by nanw1103** [comment]
Thanks for the update. Adding quote resolves the issue.
Per my test:
On Linux, the quote is required to use govc snapshot.remove '*'
On Windows, the quote is NOT required: "govc snapshot.remove *" works. However adding quote also works.

Suggest to update help text to always include quote.
