### ISSUE TITLE
Create Subscribed Content Library

### ISSUE THREAD

**Issue by serokles** [vmware/govmomi#1700]
Am having an issue deploying a subscribed content library using govc:

`govc library.create -sub=https://download3.vmware.com/software/vmw-tools/lib.json -ds=General1 -dc=HomeLab vGhettoLib`

Returns:
`govc: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.resource_inaccessible","value":{"messages":[{"args":["https://download3.vmware.com/software/vmw-tools/lib.json"],"default_message":"Connection to VCSP server https://download3.vmware.com/software/vmw-tools/lib.json failed.","id":"com.vmware.vdcs.cls-main.connection_to_vcsp_server_failed"}]}}
`
I can add this using the GUI with no issue and using curl I can get the json returned form the machine.
Am using govc version 0.22.0 built from using:
`go get -u github.com/vmware/govmomi/govc`
`go install github.com/vmware/govmomi/govc`

I can see issues with ls and rm have been resolved but cannot find anything on this issue

**Comment by serokles** [comment]
In fact got the same error in Postman using the API if I did not specify an ssl thumbprint.  Added the following line to create.go:
`f.StringVar(&cmd.sub.SslThumbprint, "ssl-thumbprint", "", "SSL Tumbprint")`

and there is now an option to add a thumbprint.  This then allows the library to be created.  If I knew how to go about a pull request I would...

**Comment by dougm** [comment]
Fixed by #1702
