### ISSUE TITLE
Get a VM's portgroup name?

### ISSUE THREAD

**Issue by nmonday** [vmware/govmomi#1703]
In PowerCLI, one can do:

get-virtualportgroup -vm my-vm

... to retrieve the current port group setting on a VM. I find myself in the middle of a massive migration project, and we've already decided to employ govc for it, but I'm not finding a way to:

1. Get a VM's current port group and save to variable
2. Migrate the VM to a new vCenter using our working script
3. Use regex to find a similarly named port group on the new vCenter and then set the migrated VM's port group to the new name so that it comes up cleanly in the new vCenter without the need for user interaction

If this functionality were added, it would make our lives far easier. Any plans to do so?

**Comment by dougm** [comment]
You can get that for VMs using: `govc vm.info -r $vm_name | grep Network`

To list networks you can use `govc ls network` and narrow with the `-t` flag.

There are a few other ways to do both and narrow results, but let us know if that's along the lines of what you're looking for.

**Comment by nmonday** [comment]
Yes, that works! It was the "-r" flag on `vm.info` I was looking for. I think making the docs a bit more robust would be really helpful. Something like "show extra info such as current portgroup assignment" would've made all the difference: I could have just searched the doc for "portgroup", and that would've come up. Anyway, thanks! That will make this project a lot less hassle.
