### ISSUE TITLE
vC Sim should bind mount BIOS UUID to DMI files when simulating lifecycle with containers

### ISSUE THREAD

**Issue by akutz** [vmware/govmomi#1709]
# Overview

This issue tracks a feature request for vC Simulator when it is simulating a VM's lifecycle with a container.

## Use case

The request is for vC Simulator to take the VM's BIOS UUID, ex. `04F419FE-8688-4066-A16D-CBC4193D5B93` and bind mount it to two files inside of the container:

1. `/sys/class/dmi/id/product_uuid`

    This file's content should mirror the value of the BIOS UUID

    ```shell
    $ cat /sys/class/dmi/id/product_uuid
    04F419FE-8688-4066-A16D-CBC4193D5B93
    ```

2. `/sys/class/dmi/id/product_serial`

    This file's content is a transformed version of the BIOS UUID.

    ```shell
    $ cat /sys/class/dmi/id/product_serial
    VMware-fe 19 f4 04 88 86 66 40-a1 6d cb c4 19 3d 5b 93
    ```

    * The UUID is prefixed with `VMware-`
    * The 32-character hexadecimal UUID string is formatted into distinct pairs of characters, each pair representing a byte value (`2^8`).
    * The [UUID should be encoded](https://en.wikipedia.org/wiki/Universally_unique_identifier#Encoding) where the first three components are little-endian, and the final two components are big-endian.
    * The 32 characters are separated by a `-` character after eight bytes (16 characters).
      * Please note that all characters before the `-` separator are little-endian, and all characters after the `-` separator are big-endian.

## Requirements

This feature is needed for the following reasons:

* The aforementioned files are read-only and cannot be modified once the guest is running. The only way to supply the correct data to these files when the guest is a container is to bind mount the data into the container (there is a similar feature for [setting these specific values when running a VM with VirtualBox or Fusion](https://github.com/vmware/simple-k8s-test-env/blob/1d251afbabbc27f9eab01cb70d9060e017734fc4/vagrant/Vagrantfile#L289-L302)).
* The VM lifecycle simulation feature of vC Sim is useful for performing integration or end-to-end (e2e) testing with Kubernetes because of the aforementioned files' relationship with the discovery of the _node ID_.
  * The node ID is used as the basis for the provider ID for:
    * The [Kubernetes cloud provider for vSphere](https://github.com/kubernetes/cloud-provider-vsphere)
    * The [Kubernetes cluster API provider for vSphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere)
  * Unless specified as a flag when starting the kubelet, Kubernetes determines a node's initial ID by reading the DMI information.
    1. The kubelet attempts to gather information about the node's status, [including the node's SystemUUID](https://github.com/kubernetes/kubernetes/blob/0599ca2bcfcae7d702f95284f3c2e2c2978c7772/pkg/kubelet/nodestatus/setters.go#L263). The method used to obtain this information depends on the cAdvisor `Interface`.
    1. The cAdvisor `Interface` [is initialized with a real system filesystem implementation](https://github.com/kubernetes/kubernetes/blob/9488fbef64afd580d053347e57819817e51ac0f9/pkg/kubelet/cadvisor/cadvisor_linux.go#L87) (`SysFs`).
    1. The cAdvisor `Interface` initializes a new `Manager` [with the `SysFs` instance](https://github.com/kubernetes/kubernetes/blob/9488fbef64afd580d053347e57819817e51ac0f9/pkg/kubelet/cadvisor/cadvisor_linux.go#L104).
    1. The cAdvisor `Manager` [gathers information about the machine](https://github.com/kubernetes/kubernetes/blob/3b440dfd5550b13278e40975a7cba13a3f129475/vendor/github.com/google/cadvisor/manager/manager.go#L188) with `machine.Info(SysFs,...)`.
    1. The `machine.Info` call uses the `SysFs` instance to [get the system's UUID via `sysinfo.GetSystemUUID`](https://github.com/kubernetes/kubernetes/blob/3b440dfd5550b13278e40975a7cba13a3f129475/vendor/github.com/google/cadvisor/machine/info.go#L138).
    1. The `sysinfo.GetSystemUUID` function is simply [a wrapper](https://github.com/kubernetes/kubernetes/blob/d1e8702d36947ccc23ad820eaae7f4afbaf0b058/vendor/github.com/google/cadvisor/utils/sysinfo/sysinfo.go#L201-L203) for the `SysFs` instance's `GetSystemUUID` function.
    1. And the real `SysFs` implementation of the `GetSystemUUID` function reads the system UUID via several methods, [starting with the DMI information](https://github.com/kubernetes/kubernetes/blob/c466fd9eaf31a6a12f901369d13129f6a8853da4/vendor/github.com/google/cadvisor/utils/sysfs/sysfs.go#L237-L249).

## Notes

* The Kubernetes cloud provider for vSphere [implements this feature with Kind for doing integration testing](https://github.com/kubernetes/cloud-provider-vsphere/tree/master/test/integration).

cc @dougm @imikushin @corrieb

**Comment by imikushin** [comment]
Weirdly, the vsphere cloud-provider reads from `/sys/class/dmi/id/product_serial`, strips the `VMware-` prefix, and **does not** rearrange the bytes back into their original UUID sequence.

https://github.com/kubernetes/kubernetes/blob/a3718d765343bc80aaaa8c95af96070b69bd7e19/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go#L661

**Comment by dougm** [comment]
Thanks for the detailed info @akutz .  I'm starting to implement this, just wanted to verify what I see with an Ubuntu VM.  The VM's config.uuid and `product_serial` have the same byte order (just different string format) and `product_uuid` has the different byte order (and uppercase):

```console
% govc object.collect -s vm/dougm-ubuntu-16.04 config.uuid
423e36c8-723d-2b24-8590-0eb1d9180aa2

% ssh vagrant@$(govc vm.ip dougm-ubuntu-16.04) sudo cat /sys/class/dmi/id/product_serial
VMware-42 3e 36 c8 72 3d 2b 24-85 90 0e b1 d9 18 0a a2

% ssh vagrant@$(govc vm.ip dougm-ubuntu-16.04) sudo cat /sys/class/dmi/id/product_uuid
C8363E42-3D72-242B-8590-0EB1D9180AA2
```

**Comment by akutz** [comment]
Hmm, I also only saw the issue in Photon 2. Perhaps it was fixed in Photon 3 and other distros? The upstream, external cloud provider still has [`ConvertK8sUUIDtoNormal`](
https://github.com/kubernetes/cloud-provider-vsphere/blob/fca2949a1e66c9e4c9e17f9b78237c37fa9862d8/pkg/cloudprovider/vsphere/util.go#L43-L62) for handling the byte order difference, and the function is still called in [`nodemanager.go`](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/nodemanager.go).
