### ISSUE TITLE
make it build in OPENBSD

### ISSUE THREAD

**Issue by rbucker** [vmware/govmomi#1710]
The openbsd team has been able to package this app, however, they made some changes to the build that I just do not understand... Since they got it to work, maybe, someone should verse engineer it?

**Comment by dougm** [comment]
How about asking the openbsd team to contribute the changes here?

**Comment by rbucker** [comment]
I'm hoping someone will blink. But in the meantime they have a public makefile. That's just not my expertise.

**Comment by dougm** [comment]
Maybe if you provide pointers to the public Makefile someone will take a look.

**Comment by dougm** [comment]
Closing this as OpenBSD does maintain a govc port. PRs are still welcome that would simplify the build process on the govmomi.
