### ISSUE TITLE
cloud-init.iso doesn't work after running govc device.cdrom.insert and device.connect

### ISSUE THREAD

**Issue by chuanchang** [vmware/govmomi#1713]
Environment:

- govc version is 0.12.1
- fedora31/rhel7.6

Steps:

- govc device.cdrom.insert -vm Atomic-001 -device cdrom-3000 datastore1/atomic4109-cidata.iso
- govc device.connect -vm Atomic-001 cdrom-3000
- govc vm.power -on Atomic-001
- check whether Atomic-001 is booted from cloud-init.iso in WebUI

Results:
please see the following picture , the item "Datastore ISO file [] Connect" isn't selected.

I'm not sure whether I missed some important steps, or is it a bug? thanks in advance!  

![Screenshot from 2019-11-15 16-59-02](https://user-images.githubusercontent.com/1122023/68930742-006aaa00-07ca-11ea-905b-f6912fa1cfa0.png)

**Comment by dougm** [comment]
Was the ISO connected before power on?  I think if the guest ejects the cdrom, it'll also get disconnected on the vSphere side.

**Comment by chuanchang** [comment]
> Was the ISO connected before
Yeah, please see description of issue, any workaround for this? thanks.
