### ISSUE TITLE
PropertyMapping field doesn't work in library.deploy options

### ISSUE THREAD

**Issue by yeah007** [vmware/govmomi#1720]
I just use library.deploy to deploy one ovf from content library. It seems that the vm has been created successfully but the vApp option values were not assigned as expected. These properties are still using default values.

But other items in spec json file such as NetworkingMapping , Name are well.

govc library.deploy -options=test-spec.json -dump=true -dc=SDDC-Datacenter -ds=WorkloadDatastore -debug=true -folder="vm/Workloads/test" -pool=test  /test/deployer

The test-spec.json file is:

{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "PropertyMapping": [
        {
            "Key": "DNS",
            "Value": "1.1.1.1"
        },
        {
            "Key": "ip0",
            "Value": ""
        },
        {
            "Key": "netmask0",
            "Value": ""
        },
        {
            "Key": "gateway",
            "Value": ""
        }
    ],
    "NetworkMapping": [
        {
            "Name": "VM Network",
            "Network": ""
        }
    ],
    "Annotation": "ceployer",
    "MarkAsTemplate": false,
    "PowerOn": true,
    "InjectOvfEnv": true,
    "WaitForIP": true,
    "Name": "deployer2"
}

 Any ideas?

**Comment by yeah007** [comment]
govc version is 0.21.0

**Comment by dougm** [comment]
Fixed by #1755
