### ISSUE TITLE
Doubt on setting the PageSize in Events function.

### ISSUE THREAD

**Issue by akankshadokania** [vmware/govmomi#1725]
Hi, 
func (m Manager) Events(ctx context.Context, objects []types.ManagedObjectReference, pageSize int32, tail bool, force bool, f func(types.ManagedObjectReference, []types.BaseEvent) error, kind ...string) error {
What is the pageSize generally preferred? And, suppose if I set it to 25 and from vCenter I receive 35 events, is there a way to fetch the older events than those 25 events...the previous 10 events to these 25 events?

**Comment by dougm** [comment]
You'll get the updates, but can't go back in history.  However, you can use HistoryCollector for that:
https://code.vmware.com/apis/704/vsphere/vim.HistoryCollector.html

There are wrappers in the govmomi 'event' package.  The Events() method has the advantage of also working directly against ESX, but HistoryCollector is vCenter only.

As for the page size, it's mainly tuning for memory use and network transfer.

**Comment by dougm** [comment]
We need some examples for EventHistoryCollector, but there's a test that'll do for the moment: https://github.com/vmware/govmomi/blob/deff37c279fe783a0ea565cd572565d37bbedafd/simulator/event_manager_test.go#L160

**Comment by dougm** [comment]
I was thinking ReadNextEvents would block until there were more events, but looks like that's not the case.  Sorry for the confusion, the Events() method actually does use EventHistoryCollector: https://github.com/vmware/govmomi/blob/deff37c279fe783a0ea565cd572565d37bbedafd/event/processor.go#L61

It must have been TaskHistoryCollector that is vCenter only.

**Comment by embano1** [comment]
In the upcoming release, this method will be marked deprecated (see https://github.com/vmware/govmomi/issues/1775)
