### ISSUE TITLE
govc vm.change network connected / start connected state 

### ISSUE THREAD

**Issue by uutest74** [vmware/govmomi#1726]
Hi.
For using in terraform need very important feature - change network adapter connected / start connected state
It can be get by
govc device.info -vm $vmname ethernet-*
Name:               ethernet-0
  Type:             VirtualVmxnet3
  Label:            Network adapter 1
  Summary:          DVSwitch: 50 3a e9 45 7f 3c 90 5c-73 ae 85 fc ef 27 6b 2c
  Key:              4000
  Controller:       pci-100
  Unit number:      7
  Connected:        false
  Start connected:  false
  Guest control:    true
  Status:           ok
  MAC Address:      00:50:56:ba:49:5a
  Address type:     assigned

but cant be changed by  vm.network.change
This changes may be usefull:
https://github.com/vmware/govmomi/commit/a9b0a80589c6b412b139f2cec86efff6a40b7ddc

**Comment by dougm** [comment]
Sounds like `device.connect` is what you're looking for: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#deviceconnect

**Comment by uutest74** [comment]
@dougm 
thx a lot! device.connect / device.disconnect works fine. Some issue that for poweron VM it switches connected and start connected checkboxes simultaneously, but client can switch separate checkbox.
