### ISSUE TITLE
Add support for enabling Secure Boot

### ISSUE THREAD

**Issue by sw25481** [vmware/govmomi#1727]
I see you added support for "-firmware=efi" in #1071

Would it also be possible to add "-secure-boot=enabled"?

**Comment by dougm** [comment]
@sw25481 does #1729 do what you need?  All the other boot options are in that command, rather than `vm.create`.  But you can do:
```console
% govc vm.create -on=false ... my-vm
% govc device.boot -secure -vm my-vm
% govc vm.power -on -vm my-vm
```
