### ISSUE TITLE
Feature Request: clone to content library

### ISSUE THREAD

**Issue by nORKy54** [vmware/govmomi#1728]
Hi,

I have some automated scripts (with Ansible) to power on, update, sysprep and stop VM. But this result VM must be cloned to content library. There is no way to do this with govc (nor Ansible module).

This is a feature request: clone to content libray

Thanks you

**Comment by dougm** [comment]
#1701 includes a new `library.clone` command, feedback welcome there.

**Comment by dougm** [comment]
#1701 is merged, let us know how it works for you @nORKy54

**Comment by nORKy54** [comment]
@dougm  I get this error:
govc library.clone -vm vm-tpl-2016 library-a01 tpl-w2k16-auto-1
govc: POST https://my-vcenter/rest/vcenter/vm-template/library-items: 404 not Found

tpl-w2k16-auto-1 already exist, I want update this item

**Comment by dougm** [comment]
What is your vCenter version?

> This operation was added in vSphere API 6.7 U1.

http://vmware.github.io/vsphere-automation-sdk-rest/6.7.1/operations/com/vmware/vcenter/vm_template/library_items.create-operation.html

**Comment by nORKy54** [comment]
My VCenter is 6.5 U3

**Comment by dougm** [comment]
Afraid we can't do much in that case, except have the command warn that 6.7U1+ is required.

**Comment by dougm** [comment]
I'll include the version requirement in the upcoming docs update.

**Comment by dougm** [comment]
@nORKy54 did you want the resulting content library item to be a VM template or OVF item? I had assumed VM template as that was the use case when we had added `library.clone`.
See also: https://github.com/vmware/govmomi/issues/1814#issuecomment-579527808
