### ISSUE TITLE
Clarifying task.WaitForResult semantics

### ISSUE THREAD

**Issue by akutz** [vmware/govmomi#1735]
The [`Wait`](https://github.com/vmware/govmomi/blob/55ecaf54bb2b1bfd7a0fdc9e9eb749792a5cb897/task/wait.go#L117) function in the `task` package returns an error if:

* The `WaitForUpdates` function [returns an error](https://github.com/vmware/govmomi/blob/55ecaf54bb2b1bfd7a0fdc9e9eb749792a5cb897/task/wait.go#L139)
* Or if the task [finished in an error state](https://github.com/vmware/govmomi/blob/55ecaf54bb2b1bfd7a0fdc9e9eb749792a5cb897/task/wait.go#L142)

This creates a problem where the `Wait` function does not behave in a manner that seems to be indicated by its function signature, i.e. both a `*TaskInfo` **and** `error` are returned if a task's completed state is in error. I'd like to suggest one of the following:

1. Do not return an `error` from `Wait` if the task failed. Instead `Wait` should only return an error if the process of **waiting** for a task fails.
2. Check if `err != nil && taskInfo == nil` to determine if the issue was waiting for the task. My issue with this is that it is a little anti-pattern since if `err` is non-nil then all other return values are supposed to be treated as their empty value.

FWIW, It looks like a task failure will cause an error to be returned wrapped by `task.Error`. I suppose that's pretty straight-forward, but I still prefer option one.

What do you think? While I don't personally care for the current approach, I'm worried any changes could have long-reaching impact given how many places this code may already be used. If `Wait` no longer returns an error when the task fails, that may result in a lot of bugs in code that uses GoVmomi.

**Comment by dougm** [comment]
Right, can't change the behavior of `task.Wait`, that would break way too many things.  Another option is to use the property collector directly, task.Wait doesn't do much when you take away the progress stuff.  Example:
```go
		pc := property.DefaultCollector(c)
		err = property.Wait(ctx, pc, task.Reference(), []string{"info"}, func(changes []types.PropertyChange) bool {
			for _, change := range changes {
				if info, ok := change.Val.(types.TaskInfo); ok {
					switch info.State {
					case types.TaskInfoStateSuccess:
						log.Printf("SUCCESS")
						return true
					case types.TaskInfoStateError:
						log.Printf("ERROR=%s", info.Error.LocalizedMessage)
						return true
					}
				}
			}
			return false
		})
```

**Comment by akutz** [comment]
Thanks @dougm. I'm closing this issue as there's not much more to say. Thank you again.
