### ISSUE TITLE
Do we have an API to modify the name of a given datacenter?

### ISSUE THREAD

**Issue by MartinZJY** [vmware/govmomi#1736]
Hi VMware team,

I am looking for a way to modify the name of existing datacenter. But there doesn't seem to have such API. I only found ReconfigureDatacenterRequestType that can be used by ReconfigureDatacenter_Task. However, there's no field as datacenter name in the request. Can we add support for this?

**Comment by dougm** [comment]
The method is `Rename_Task`: https://code.vmware.com/apis/196/vsphere/doc/vim.ManagedEntity.html#rename

There is a helper: https://godoc.org/github.com/vmware/govmomi/object#Common.Rename

Added an example in #1737
