### ISSUE TITLE
Some host.esxcli commands do not return correct data

### ISSUE THREAD

**Issue by guyse-michael** [vmware/govmomi#1739]
I've trying running the following command on linux and windows, and both return the same output.  I am using v0.21.0 with linux using govc_linux_amd64.gz, and windows is using govc_windows_amd64.exe.zip.
The command that I am using is "govc host.esxcli system visorfs ramdisk list", I have tried other host.esxcli commands to verify that they work and they are working as expected.  I've only noticed this command not working as expected.
The output that I am getting on linux is:
![image](https://user-images.githubusercontent.com/53884168/70734187-5f401800-1cd1-11ea-8f4d-0189d8551748.png)
The output that I am getting on Windows is:
![image](https://user-images.githubusercontent.com/53884168/70734387-c52c9f80-1cd1-11ea-8da9-896bdc8233f8.png)
And finally the expected output that I am getting when running the command on the Esxi Host is:
![image](https://user-images.githubusercontent.com/53884168/70734451-e2fa0480-1cd1-11ea-9e69-9413e843c9dd.png)

**Comment by dougm** [comment]
Hadn't seen that before, but I see the same here and #1739 will fix.  You can also workaround by using `-hints=false`.
