### ISSUE TITLE
How do I find the host name by tag?

### ISSUE THREAD

**Issue by fangfuhaomin** [vmware/govmomi#1742]
The information is currently retrieved through the perfManager method:

VirtualMachine:vm-1711	4002	net.received.average	0	[%!s(int64=0)]	KBps
VirtualMachine:vm-1711	4001	net.received.average	875	[%!s(int64=875)]	KBps
VirtualMachine:vm-1711	-	net.received.average	876	[%!s(int64=876)]	KBps
VirtualMachine:vm-1525	vmnic2	net.received.average	0	[%!s(int64=0)]	KBps
VirtualMachine:vm-1525	vmnic3	net.received.average	0	[%!s(int64=0)]	KBps

How do I find the VirtualMachine name with VirtualMachine:vm-1711 ?

I hope I can guide you. Thank you!

**Comment by dougm** [comment]
Updated the example in #1747
