### ISSUE TITLE
Create a readme for the find package that explains path patterns

### ISSUE THREAD

**Issue by akutz** [vmware/govmomi#1750]
It would be useful to include a `README` in the `find` package that explains how the finder treats search tokens, when `*` works in a token, when it doesn't, implicit objects, etc.

This request stems from the thread https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/403#issuecomment-510276822.

**Comment by tkrausjr** [comment]
I can take this @akutz,  You are referring to the govmomi find package correct ?

**Comment by akutz** [comment]
Yes, sir! Thanks. And I haven't forgotten about your other issue. I've just been backlogged with v1a3 work.

**Comment by dougm** [comment]
@tkrausjr great, I'm happy to help and review.  Current docs are here:

https://github.com/vmware/govmomi/tree/master/govc#usage

https://godoc.org/github.com/vmware/govmomi/find (via https://github.com/vmware/govmomi/blob/master/find/doc.go)

Bonus if we could add a find/example_test.go similar to other packages such as:
https://github.com/vmware/govmomi/blob/master/view/example_test.go
https://github.com/vmware/govmomi/blob/master/event/example_test.go
https://github.com/vmware/govmomi/blob/master/property/example_test.go

There are finder tests here: https://github.com/vmware/govmomi/blob/master/simulator/finder_test.go#L23

That should be in the `find` package, but I didn't realize at the time how to break the import cycle.. find/find_test.go just needs `package find_test` for that.

**Comment by tkrausjr** [comment]
@akutz - Thanks so much. I think the other issue is GTG so would be great to put that PR to bed.  So you are just looking for a Readme for "find" inside govmomi project that can be referenced by other projects or users of CAPV or others ?

@dougm  I will take a stab at this.  

/assign @tkrausjr
