### ISSUE TITLE
Updating own user password works in vCenter ui, fails using govc

### ISSUE THREAD

**Issue by hoskeri** [vmware/govmomi#1756]
I am able to update my own password using the vCenter HTML5 Interfaces's change password menu item, but what I think is the equivalent command on govc fails:

```
govc sso.user.update -p NewPassword111 username@vsphere.local
govc: ServerFaultCode: NoPermission
```

**Comment by dougm** [comment]
Works for me as `Administrator`, might require such permissions even to change your own password with this API.  Not sure though.  How did you create the user, assign roles, etc?

```console
% govc sso.user.id
person=Administrator@vsphere.local groups=LicenseService.Administrators,Administrators,Everyone,CAAdmins,SystemConfiguration.Administrators,SystemConfiguration.BashShellAdministrators,Users
```

**Comment by LinAnt** [comment]
Has anyone managed to figure this one out? Quite weird that changing password through the UI works, but for some reason it is blocked when using govc.
