### ISSUE TITLE
Host.esxcli shell cmd not returning anything

### ISSUE THREAD

**Issue by guyse-michael** [vmware/govmomi#1759]
Esxi version : 6.5.0 Update 2
govc version: 0.21.0
Issue: When running any esxi shell command even simple esxcli shell commands nothing is returned when using govc.  I am using govc to try and retrieve this data because ssh is disabled in our esxi hosts.
This is what I get when I run the following command on the esxi host
esxcli shell cmd -c 'echo hi'
![image](https://user-images.githubusercontent.com/53884168/71180875-adf13300-2238-11ea-9dca-1e4652cd4bd2.png)
When I run the following govc command on one of the vms on the host there is nothing returned
govc host.esxcli -u='https://username:password@esxi_host_ip/sdk' -k=true shell cmd -c 'echo hi'
![image](https://user-images.githubusercontent.com/53884168/71181435-c3b32800-2239-11ea-9c40-817687e6e704.png)
Note: I've also added another govc command to show that I was able to connect and retrieve info from the esxi host

**Comment by dougm** [comment]
The esxcli xml decoder is a bit clunky, but #1762 fixes that.
