### ISSUE TITLE
govc datastore.upload folder option?

### ISSUE THREAD

**Issue by driftavalli** [vmware/govmomi#1764]
It seems there's no method available to upload to a specific folder? `govc datastore.upload disk.iso datastore` works but trying to specify a folder in the datastore returns an `Uploading... Error: 405 Method Not Allowed`

**Comment by dougm** [comment]
Path can be specified as part of the DEST param:

```console
% govc datastore.mkdir files
% date | govc datastore.upload - files/date.txt
% govc datastore.download files/date.txt -
Fri Dec 27 08:40:27 PST 2019
```
