### ISSUE TITLE
ServerFaultCode: Invalid or unknown locale provided

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1766]
ServerFaultCode: Invalid or unknown locale provided
Is 5.5 not supported?

**Comment by dougm** [comment]
Assuming you changed `session.Locale` or env `GOVMOMI_LOCALE`, what did you set it to?

You can set the supported list for your system using:

`govc object.collect -s SessionManager:SessionManager supportedLocaleList`

or

`govc object.collect -json -s SessionManager:SessionManager supportedLocaleList | jq .`
