### ISSUE TITLE
what is on the console?

### ISSUE THREAD

**Issue by rbucker** [vmware/govmomi#1782]
I'm using govc to deploy/orchestrate any OS installation. Right now I'm focused on OpenBSD. It has a bootloader with a timeout and it installs using the terminal console (not to be confused with a graphical UI). The challenge is that there are many steps to install OpenBSD and while I can predict a path through the installation with keystrokes and delays... it would be great to know what the current prompt is so I could use something like expect to guide the keystrokes.

Is there a way to get a string representing what is on the console?

**Comment by dougm** [comment]
Not that I know of. `vm.console` can take a screenshot, but nothing in string form.

**Comment by rbucker** [comment]
Thank you
