### ISSUE TITLE
Unable to Import OVA

### ISSUE THREAD

**Issue by driftavalli** [vmware/govmomi#1783]
I have clusters in two datacenters; for one cluster, I have used standard vswitches and for the other, a distributed vswitch. I can successfully import the ova to the standard vswitch cluster using: `govc import.ova -options vm.json vm.ova`. However this fails with `govc: Host did not have any virtual network defined` for the cluster with using dvs. I am using the exact same options and ova.
```
 # govc version
govc 0.22.0
```

**Comment by dougm** [comment]
You might need to provide a `NetworkMapping`
https://github.com/vmware/govmomi/issues/460#issuecomment-240685913

Another option might be to use Content Library instead, `library.import` and `library.deploy`

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/issues/1561#issuecomment-582092466
