### ISSUE TITLE
Holder-of-Key: govc: ns0:FailedCheck: Signature is invalid

### ISSUE THREAD

**Issue by matthewmfrost** [vmware/govmomi#1785]
When issuing a Holder-of-Key token, with delegated Bearer token identity via govc the following error occurs:
```
govc: ns0:FailedCheck: Signature is invalid
```
The command that is causing the error is as follows:
```
hokToken=$(govc session.login -cert user.crt -key user.key -issue -token "$bearerToken")
```
This error has started to occur since updating to _vCenter Appliance 6.7 Update 3b (6.7.0.42000)_, but continues to work on _vCenter Appliance 6.7 U2 6.7.0.30000_.

**Versions**
- govc v0.22.0 (also tested with a few older versions with the same issue)
- vCenter Appliance 6.7 Update 3b 6.7.0.42000 (The one with the issue)
- vCenter Appliance 6.7 U2 6.7.0.30000 (The one without the issues)

**Replicating the Issue**
See below a set of scripts for testing this issue:
[govc-tests.zip](https://github.com/vmware/govmomi/files/4048750/govc-tests.zip)
- **create-user.sh** - creates a solution user
- **token-test.sh** - gets a bearer token for a user, followed by a HOK token with the delegated bearer token identity and then tries to login with the HOK token and use it.
- **logs** - folder containg the outputs of the scripts for the two versions of vCenter listed above

**Findings**
At present I am a bit lost, as the release notes for VCSA lack the details needed. One difference I can see is a change of XML prefix for bearer tokens, changing from xs in 6.7 U2 to xsd in 6.7 U3b.

**Comment by matthewmfrost** [comment]
For anyone needing an immediate fix and doesn’t require the use of bearer tokens, a potential workaround for issuing a Holder-of-Key token, with delegated identity, is to use a new feature as of govc 0.22.0 (thanks @dougm!) ..."Support HoK tokens with Interactive Users" (CHANGELOG.md L25).

As there are no docs for this yet it took a bit of digging around to find the following comment in _signer.go L145_:
````
When requesting HoK token for interactive user, request will have both priv. key and username/password
````
Note it makes no reference to a certificate needing to be provided. With that in mind the following seems to work on both _vCenter Appliance 6.7 Update 3b 6.7.0.42000 _ and _vCenter Appliance 6.7 Update 3b 6.7.0.42000_:
````
export GOVC_URL="https://<host>"
export GOVC_INSECURE=true
export GOVC_USERNAME="<user>"
export GOVC_PASSWORD="<pass>"
hokToken=$(govc session.login -key user.key -issue)

# Hard Logout
govc session.logout
rm -r ~/.govmomi/sessions/*
unset GOVC_USERNAME
unset GOVC_PASSWORD

# Certificate is still needed here!
govc session.login -l -cert user.crt -key user.key -token "$hokToken"
govc ls
````

**Comment by dougm** [comment]
@matthewmfrost thank you for the details and scripts to reproduce. I will take a closer look early this week and at the very least we can start by adding some docs for the workaround you found.

**Comment by matthewmfrost** [comment]
Apologies, I had to delete my previous comment. The "workaround" @dougm was referring to was in-fact still retrieving a bearer token, not a holder-of-key token.

...back to the drawing board

**Comment by matthewmfrost** [comment]
After performing a diff of the JARs located at:
````
/usr/lib/vmware-sso/vmware-sts/webapps/ROOT/WEB-INF/lib
````
on vCenter Appliance 6.7 U2 6.7.0.30000 and vCenter Appliance 6.7 Update 3b 6.7.0.42000 it looks like there has been a major version increase in _opensaml_ which _govmomi_ may not support yet....maybe:
````
70e20154abc9a94e230b5679e3603e5a  opensaml-2.6.4.jar	      |	edaa80c9478f5e09c327fdb796d0481c  opensaml-core-3.2.0.jar
c2555a4e6e3447de78bb56308624a276  openws-1.5.6.jar	      |	3b30e1f98e193a206b051c53791cf03b  opensaml-messaging-api-3.2.
							      >	5d0068566e2e1024f8d74c70093aa3d2  opensaml-messaging-impl-3.2
							      >	3d0e85abed39e4be45fc2b846075f424  opensaml-profile-api-3.2.0.
							      >	391de2dbd7901ff1011f71f64d37e491  opensaml-saml-api-3.2.0.jar
							      >	d59a5ce48c89d7f2b6ee2cff0abad364  opensaml-saml-impl-3.2.0.ja
							      >	d091cd42b113bcb8b747825f737e6ba1  opensaml-security-api-3.2.0
							      >	de9b8f23b04e2ab5a937571710d02685  opensaml-security-impl-3.2.
							      >	2af9b4f467be220c039edb79e595c1dc  opensaml-soap-api-3.2.0.jar
							      >	9428fb82efed3b48a452be53774daac4  opensaml-soap-impl-3.2.0.ja
							      >	6a9f615f21106033e6fc36ecf6763c84  opensaml-storage-api-3.2.0.
							      >	d1428637a4aac62208f87ddb8b8895f7  opensaml-xmlsec-api-3.2.0.j
							      >	55260da8c511025e9854cffa70d89fbd  opensaml-xmlsec-impl-3.2.0.
3a6de4346bf03756550451d5b48674e3  samlauthority-7.0.0.jar     |	35e617c5ed519918dc43d6ca57ca4401  samlauthority-7.0.0.jar
3baa343753a7fed1cabec1760ea3a1f2  samltoken-7.0.0.jar	      |	0374b9f66c4bc2ebb65d4618da809a6a  samltoken-7.0.0.jar

````

**Comment by dougm** [comment]
Indeed, OpenSAML update is the culprit, and something we'll have to fix on the govmomi side. I'm looking at this now.

**Comment by dougm** [comment]
Temporary workaround below removes the `ActAs` flag, but I'm still looking into the proper fix.  iirc ActAs is only required to use SAML token auth with vAPI (tags.*, library.*), are you using those currently?

```diff
modified   govc/session/login.go
@@ -153,7 +153,6 @@ func (cmd *login) issueToken(ctx context.Context, vc *vim25.Client) (string, err
 		Userinfo:    cmd.Userinfo(),
 		Renewable:   true,
 		Delegatable: true,
-		ActAs:       cmd.token != "",
 		Token:       cmd.token,
 		Lifetime:    cmd.life,
 	}
```

**Comment by matthewmfrost** [comment]
I am afraid so. I make use of the holder-of-key token in conjunction with Terraform which requires govmomi's rest_sesisons whenever it clones a VM in order to check for tags and some other bits.

**Comment by dougm** [comment]
I was mistaken, the vAPI endpoint only requires the `Delegatable` flag, not `ActAs`.  Can you try the workaround above?  I can also change govc so we can disable `ActAs` with a flag instead of using the patch.

**Comment by dougm** [comment]
The workaround in PR form: #1791

**Comment by matthewmfrost** [comment]
Okay. So the workaround suggested does indeed get me a holder-of-key token, but it fails to login using:
````
govc session.login -l -cert user.crt -key user.key -token "$hokToken"
````
Where user.crt and user.key is that of the solution users. The following error is given:
````
govc: ServerFaultCode: Permission to perform this operation was denied.
````
Did you make any further changes to the command above?

**Comment by dougm** [comment]
I didn't make further changes, the bearer token in my case was that of Administrator@vsphere.local
Didn't realize you needed ActAs, in that case disregard the workaround attempt and I'll continue to pursue the proper fix.

**Comment by dougm** [comment]
@matthewmfrost the type prefix change you called out was indeed the problem. That was clear after I figured out the related logging (with debug enabled for dsig) is in a different location.

#1792 should work for you against 6.7u3 - but I also need to go back and adjust so it'll work with older versions of vCenter too.

**Comment by dougm** [comment]
Updated #1792 to work with all versions. I'll go ahead and merge when you're able to confirm @matthewmfrost

**Comment by matthewmfrost** [comment]
I can confirm that #1792 works against _Update 3b 6.7.0.42000_ and _vCenter Appliance 6.7 U2 6.7.0.30000_. Thanks for the speedy work @dougm! 🥇 

Happy for you to merge.

**Comment by dougm** [comment]
Great @matthewmfrost , thanks for all your debugging, and spotting the 1-char issue inside all that xml!

I’ll also create a 0.22.1 release later tonight that includes the fix.

**Comment by matthewmfrost** [comment]
No worries, diffing tools (Fork) did most of the brunt.

Keep up the hard work! The team and I are big fans of govmomi and govc!
