### ISSUE TITLE
Setting user-data of the VM

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#1798]
I wanted to ask if there's a way set the user-data metadata of a VM using govmomi. In terraform, I'd use this in the terraform config to setup my VM with the user-data key populated.
```
data "template_file" "user_data" {
  template =...
```

In vCenter, this is under VM -> configure -> settings -> vApp options -> properties -> user-data

**Comment by dougm** [comment]
I haven't used the API to do that myself, but yes you can with govmomi. Looks like those properties are set here by terraform: https://github.com/terraform-providers/terraform-provider-vsphere/blob/c8ab7edab77355863b75adb78992e8e59ab5d8a6/vsphere/virtual_machine_config_structure.go#L783
