### ISSUE TITLE
Server side filtering for VM list (query template vms)

### ISSUE THREAD

**Issue by siddharth-kulshrestha** [vmware/govmomi#1803]
There is no way for client/customer to filter out template VMs without getting all the VMs on client side.

My use case is to query all template VMs but it doesn't seem that filter API provides any filter to pass config.template==true without filtering it on client.

How can we filter template VMs on server side and get the final result?

**Comment by dougm** [comment]
There's no server side property based filtering that I know of.  You could keep the templates within their own inventory folder or use Content Library to manage the templates.
