### ISSUE TITLE
govc guest.upload not working in windows

### ISSUE THREAD

**Issue by koteswara-kelam** [vmware/govmomi#1805]
I tried to upload a file to vm from my windows machine using:
>govc guest.upload -l 'user':'Password' -vm=my_node -dc=my-dc -perm=0755 -f=true ./scripts/ip-configuration.sh /tmp/ip-configuration.sh
[K[18-01-20 06:47:17] Uploading... govc: ServerFaultCode: Failed to authenticate with the guest operating system using the supplied credentials.

But credentials are correct working fine when I tried same command from Linux machine. Do I need to do something extra in windows?

Note: All GOVC env variables are set. Deploying ova and starting vm is working fine using govc from windows.

**Comment by dougm** [comment]
Problem might be the single quotes: https://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q

**Comment by SergeyMuha** [comment]
I provided guest credentials with 
`export GOVC_GUEST_LOGIN=username:password`, but -l username:password also works
and used
`govc guest.upload  -vm=vm-name ./local_file "C:\Users\usrname\Downloads\file.msi"
[date 10:51:18] Uploading... OK`
