### ISSUE TITLE
optimize `govmomi` library for monitoring solutions

### ISSUE THREAD

**Issue by ilyam8** [vmware/govmomi#1806]
Hi there 👋

I used `govmomi` library to write the plugin to monitor virtual machines/hosts performance metrics.

> https://github.com/netdata/go.d.plugin/tree/master/modules/vsphere

I faced two problems (probably i missed something, sorry if it is the case):

- it is very hard to use to scrape metrics.

The task seems trivial in theory, but in practice it took me a lot of time to understand what and how i need to use (and i am not sure i did it right 😅).

I ended up using following packages

```
	"github.com/vmware/govmomi/performance"
	"github.com/vmware/govmomi/session"
	"github.com/vmware/govmomi/simulator"
	"github.com/vmware/govmomi/view"
	"github.com/vmware/govmomi/vim25"
	"github.com/vmware/govmomi/vim25/methods"
	"github.com/vmware/govmomi/vim25/mo"
	"github.com/vmware/govmomi/vim25/soap"
	"github.com/vmware/govmomi/vim25/types"
```

- it adds ~ `14 MB` to binary size, which is a lot imo.

It would be nice to make the library more user friendly.

My main concern is binary size.

I've read the readme

> The code in the govmomi package is a wrapper for the code that is generated from the vSphere API description. It primarily provides convenience functions for working with the vSphere API.

I understand that it is generated and all, but `+14MB` just for gathering metrics doesnt feel good.

**Comment by dougm** [comment]
Regarding the generated code / binary size, see #1186 

Regarding metric collection, yes, the vSphere API is complex regardless of programming language.  We have tried to make it simpler in Go with higher level helpers, such as those used by the govc metric commands.  Can you share more details as to which methods you're using and suggestions you have to make things simpler?

**Comment by ilyam8** [comment]
rel issue https://github.com/kubernetes/kubernetes/issues/66321

> Regarding the generated code / binary size, see #1186

Yeap, this is it. What is state of the #1186? Are you going to implement it? If so could i ask when?


My main concern is binary size, if it is known issue this one can be closed

**Comment by dougm** [comment]
I'd like to get it implemented, but still don't know when that'll happen yet.  ok, I'll go ahead and close this, since 1186 tracks the binary size concern.
