### ISSUE TITLE
How to upload a directory using govc guest.upload?

### ISSUE THREAD

**Issue by koteswara-kelam** [vmware/govmomi#1809]
Currently we can upload only a file using govc guest.upload. Is there any option in govc to upload complete directory to the remote vm?
Error:
Uploading... Error: Put https://IP_ADDR:443/guestFile?id=430&token=52abf097-12a0-5969-4cd3-901f1107a18e430: read my-repo: is a directory

**Comment by dougm** [comment]
The vSphere API behind guest.upload only supports 1 file at a time.  But you can use tar with `guest.run` for example:
```console
% tar -cf- foo/ | govc guest.run -d - tar -C /tmp -xf-  
```
