### ISSUE TITLE
Use existing REST session

### ISSUE THREAD

**Issue by bill-rich** [vmware/govmomi#1810]
Is there a way to save and re-use an existing session with the REST client? The vic library, and I'd like to use that same functionality with govmomi, but I can't find how its done (or if it can be).

**Comment by bill-rich** [comment]
Found a solution to this. I am saving the value of the `vmware-api-session-id` cookie and then recreating that cookie when setting up the rest client.

**Comment by dougm** [comment]
govc doesn't persist REST sessions yet.. we should probably move the session persistence to a common place for use by govc, TF, and others. Couple of TODOs here: https://github.com/vmware/govmomi/blob/ca6409320dcdd91f065e14c8a41d09cdae96bf33/govc/flags/client.go#L592-L598
