### ISSUE TITLE
Clone from VM Template to content library

### ISSUE THREAD

**Issue by rhockenbury** [vmware/govmomi#1814]
I'm trying to clone a vm template to a content library through govc:
```
$ govc library.clone -vm windows-1909-core-uu-jan2020 packer_templates windows-1909-core-uu-jan2020-2
govc: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.invalid_argument","value":{"messages":[{"args":["vm-1836"],"default_message":"The provided source virtual machine ID vm-1836 is from a virtual machine template, which is not supported.","id":"com.vmware.vdcs.vmtx-main.invalid_source_vm_template_not_supported"}]}}
```

If I first convert the vm to a template, the operation is allowed.  A direct "Clone to library" for a vm template is supported through the vCenter UI. 

It looks like there was some work done here to support the `library.clone` (https://github.com/vmware/govmomi/pull/1701) but only includes cloning from a vm to a content library.  

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vm_admin.doc/GUID-AC1545F0-F8BA-4CD2-96EB-21B3DFAA1DC1.html

**Comment by dougm** [comment]
Hadn't looked at that case, guessing we'd just have to toggle the vm template flag before/after the clone.  We had only looked at converting a subscription library to local library of templates (for use as linked clones): https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarysync

That command does a `library.deploy` of an OVF item, then `library.clone` the deployed vm, then deletes the deployed vm (its no longer needed after the clone). But never sets the vm template flag on the deployed vm.

**Comment by dougm** [comment]
@rhockenbury btw if you want to test that theory, you can try:
```console
% govc vm.markasvm ...
% govc library.clone ...
% govc vm.markastemplate ...
```

**Comment by rhockenbury** [comment]
If I mark it as a vm first, and do the library.clone the item in the content library shows up as a VM template type.  The functionality I'm after would be the "Clone to Library" operation on a vm template (which is accessed in the vsphere UI by right-clicking a vm template and selecting "Clone to Library...") - which converts it to OVF Template type in the content library.

**Comment by dougm** [comment]
Ah, haven't looked at doing that in govc either, but now recall the UI version I had looked at supports both clone as template and clone as ovf.  We could look at baking the ovf option into `library.clone`. In the meantime, you could use `govc export.ovf` of the vm, then use `library.import` to get an ovf item. I'm guessing the UI does similar behind the scenes.

**Comment by rhockenbury** [comment]
Thanks.  An export followed by the library import does get the job done.  Unfortunately, with 8GB windows templates it does take some time.

**Comment by rhockenbury** [comment]
Sorta a separate question, but would `library.clone` be able to support also publishing the vm template to subscribers?  VM template types require a publish, unlike ova templates which can be automatically synced.

**Comment by dougm** [comment]
Here's the API we can use to import an existing VM as an OVF: http://vmware.github.io/vsphere-automation-sdk-rest/6.7.1/operations/com/vmware/vcenter/ovf/library_item.create-operation.html

Haven't found the API to publish, but can try to find out.

**Comment by dougm** [comment]
@rhockenbury the subscriptions API turned out to also be useful for the LinkedClone related work I mentioned.  PR #1853 includes a `library.publish` command which I believe is what you were looking for, can you review?
