### ISSUE TITLE
Passwordless authentication

### ISSUE THREAD

**Issue by driftavalii** [vmware/govmomi#1824]
Is it possible to authenticate without using password credentials? `govc session.login` seems to indicate several options to do so (`clone ticket`, `vcenter Extension certificate`). The examples show a `user.crt` and `user.key`, where would one generate these certificates? I have looked at [Managing Certificates with the vSphere Certificate Manager Utility](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.psc.doc/GUID-B98DF9C2-FE7D-483F-9521-C17C138B59D8.html) and [Generate CSR with vSphere Certificate Manager and Prepare Root Certificate (Intermediate CA)](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.psc.doc/GUID-75008746-C902-4C42-8F5C-6602D6E4EC8B.html) but there's no facility to create certificates. Do I need to generate a CSR and create certificates external to vcenter or can I create a "vCenter Extension certificate" from the Certificate Management gui interface.

**Comment by dougm** [comment]
You can use token auth with a solution user: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#ssousercreate

Or TLS client auth with an extension: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#extensionsetcert

In both cases, you generate the key pair locally, using openssl or tool of choice. The input to the APIs (and govc commands above) is just the public key.

**Comment by dougm** [comment]
Some more info on the auth methods here: https://github.com/kubernetes/kubernetes/issues/63209

We should put some of that in the govmomi docs.
