### ISSUE TITLE
recieve tags of virtual machine

### ISSUE THREAD

**Issue by Bambie07** [vmware/govmomi#1825]
Hi,

I try to recieve a list of tags associated with a virtual machine. Can someone give me a hint, where to find these tags or how to recieve them? This is my current code:

```
var vms []mo.VirtualMachine
err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"name", "customValue", "summary", "guest", "config", "snapshot", "resourcePool", "tag"}, &vms)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

	for _, vm := range vms {
             ???
}
```
I json dumped the output of an vm but was unable to find them

Thank you in advance

**Comment by dougm** [comment]
Tags are stored in a different model by vCenter and you need to use a different API to access them. Try the `govc tags.attached.ls -r` command:
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#tagsattachedls

If you see what you need there, the API used is here: https://github.com/vmware/govmomi/blob/74b8e4edb99eba116c872affda0360dddcea7850/govc/tags/association/ls.go#L117

**Comment by Bambie07** [comment]
Thanks for the quick response. I solved it with the following code:



`
func getTags(ctx context.Context, c *vim25.Client, userinfo *url.Userinfo) (map[string][]*tags.Tag, error) {

	re := rest.NewClient(c)
	_, err := re.Session(ctx)
	if err != nil {
		log.Print(err)
		return nil, err
	}
	re.Login(ctx, userinfo)

	m := tags.NewManager(re)

	tagList, err := m.ListTags(ctx)
	if err != nil {
		log.Print(err)
		return nil, err
	}

	r := make(map[string][]*tags.Tag)
	for _, tag := range tagList {
		obj, err := m.GetAttachedObjectsOnTags(ctx, []string{tag})

		if err != nil {
			log.Print(err)
			return nil, err
		}
		tag2, err := m.GetTag(ctx, tag)

		for _, elem := range obj[0].ObjectIDs {
			r[elem.Reference().Value] = append(r[elem.Reference().Value], tag2)
		}

	}
	return r, nil
}
`
