### ISSUE TITLE
Error is not in log.Fatal

### ISSUE THREAD

**Issue by tshihad** [vmware/govmomi#1826]
https://github.com/vmware/govmomi/blob/74b8e4edb99eba116c872affda0360dddcea7850/examples/examples.go#L129

This error will never logged in https://github.com/vmware/govmomi/blob/74b8e4edb99eba116c872affda0360dddcea7850/examples/examples.go#L135
It can be solved by following code
```ctx := context.Background()
var c *govmomi.Client
c, err = NewClient(ctx)
```

**Comment by dougm** [comment]
Thanks @tshihad , can you open a Pull Request with your change?

**Comment by tshihad** [comment]
@dougm Sure

**Comment by dougm** [comment]
Fixed by #1828
