### ISSUE TITLE
soap.Client.SetRootCAs works only with files

### ISSUE THREAD

**Issue by unclejack** [vmware/govmomi#1827]
The way the soap.Client.SetRootCAs is implemented makes it possible to load this file only from the file system.

It'd be great to be able to load the CAs from a slice of bytes or something similar.

**Comment by dougm** [comment]
You can load the CAs from anywhere by using the field directly:
 ```go
soap.Client.Transport.(*http.Transport).TLSClientConfig.RootCAs
```

See also #1820

**Comment by unclejack** [comment]
@dougm: I've missed those search results. Thanks!
