### ISSUE TITLE
govc library.import failure with 401 Unauthorized

### ISSUE THREAD

**Issue by mkmrah** [vmware/govmomi#1832]
govc library import command fails with 401 Unauthorized error

`govc library.import bitnami-abantecart-1.2.15-9-linux-centos bitnami-abantecart-1.2.15-9-linux-centos-7-x86_64.ova`

log
```
[03-02-20 18:56:16] Uploading bitnami-abantecart-1.2.15-9-linux-centos-7-x86_64.ovf... OK
[03-02-20 22:54:11] Uploading bitnami-abantecart-1.2.15-9-linux-centos-7-x86_64-disk1.vmdk... OK
2020/02/03 22:54:12 user logout error: DELETE https://vcentersvr-vc.xx.xxxx.xxx/rest/com/vmware/cis/session:401 Unauthorized
govc: POST https://vcentersvr-vc.xx.xxxx.xxx/rest/com/vmware/content/library/item/update-session/id:815994e5-2828-4a88-86ed-4575f9e964e2:9c7e16e9-9b8c-4c5a-a67b-a66a08b7d71c?~action=complete:401 Unauthorized
```

Any clue why?

**Comment by dougm** [comment]
Looks like it took a few hours to upload the .vmdk? Possible the API session expired during that time. I had assumed the file uploads would keep the session alive.

**Comment by mkmrah** [comment]
@dougm that's right.. upload took long time around 4-5 hours and in the end i got the above error.

**Comment by mkmrah** [comment]
Any local workaround to overcome this? if not any timeline when this issue will be addressed?

Thanks
