### ISSUE TITLE
mode overwritten in vm.disk.attach

### ISSUE THREAD

**Issue by krzymach** [vmware/govmomi#1833]
Hi,

I have spotted a bug in govc. When attaching disk to vm, I want to choose mode with -mode parameter. Unfortunately it is being overwritten by either cmd.link or cmd.persist parameters.

I have fixed it for my own by moving 

```
if len(cmd.mode) != 0 {
	backing.DiskMode = cmd.mode
}

```
just before last line 

`return vm.AddDevice(ctx, disk)`

I cannot push any commits so please fix it or give me rights to push the commit.

Thank you,
Krzysztof Machnicki

**Comment by dougm** [comment]
Thanks @krzymach , the fix sounds right to me. We don't push directly to the repo however, can you open a Pull Request? https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md#getting-started
