### ISSUE TITLE
Support remote OVAs for govc import.spec / import.ova

### ISSUE THREAD

**Issue by cloudmaniac** [vmware/govmomi#1836]
Currently, only local OVAs are supported by `govc import.spec` and `govc import.ova`.
It would be fantastic if govc could support the import from a remote location (such as from a S3 bucket).

Example: `govc import.ova https://<fantastic-bucket>.s3-us-east-1.amazonaws.com/template.ova`

**Comment by tsugliani** [comment]
this would be very useful indeed !

**Comment by dougm** [comment]
Which version of govc are you using?  `import.ova` has supported remote URL for quite a while, since 1c1291c

We did just add support for remote `import.spec` in #1885

**Comment by tsugliani** [comment]
Hi @dougm.

I've tested on govc 0.22.1 (latest available release)

Yes indeed import.ova works with remote URL, but not import.spec (so right now I have a intermediate step to download/fetch spec and then reuse import.ova with the remote URL for various remote target deployments).

Hopefully a 0.22.2 release will fix that ;-)

Thanks for great work around this !

**Comment by dougm** [comment]
ok, thanks @tsugliani .  I'll close this then as the master branch has remote `import.spec` support and plan to release 0.23 soon-ish.

**Comment by reubenur-rahman** [comment]
@dougm Not available even in `0.24` ! Any chance in `0.25` ?

**Comment by dougm** [comment]
@reubenur-rahman remote import.spec support is there since 0.23.  If you're having an issue with that or import.ova, please provide more details.
