### ISSUE TITLE
Can I use this with Workstation Pro?

### ISSUE THREAD

**Issue by brad-jones** [vmware/govmomi#1838]
> When using govc against VMware Workstation, GOVC_URL can be set to "localhost" without a user or pass, in which case local ticket based authentication is used. https://github.com/vmware/govmomi/blob/master/govc/README.md

This suggests I can use govmomi with Workstation.  I can run `govc about -u localhost -k` and get the following:

```
Name:         VMware Workstation
Vendor:       VMware, Inc.
Version:      15.5.1
Build:        15018445
OS type:      win32-x86
API type:     HostAgent
API version:  6.9.2
Product ID:   ws
UUID:
```

But do not seem to be able to execute anything else, always failing with NotAuthenticated.

`govc ls -u localhost -k`

```
C:\Users\brad.jones\scoop\apps\govc\current\govc_windows_amd64.exe: NotAuthenticated
```

Does Workstation really support the vSphere API? I didn't think it did... should I be looking at https://code.vmware.com/apis/412/vmware-workstation-pro-api instead? What about VIX, I have read articles that suggest that has been/is being merged into vSphere?

**Comment by dougm** [comment]
It does work that way on Linux, but we may need to change to support Windows here: https://github.com/vmware/govmomi/blob/e024d19c58ae4f6ad51b0a493b88caee60753588/govc/flags/client.go#L491

Likely the following, but I haven't tested on Windows yet:

```diff
modified   govc/flags/client.go
@@ -30,6 +30,7 @@ import (
 	"net/url"
 	"os"
 	"os/signal"
+	"os/user"
 	"path/filepath"
 	"strings"
 	"syscall"
@@ -488,7 +489,11 @@ func (flag *ClientFlag) newClient() (*vim25.Client, error) {
 }
 
 func (flag *ClientFlag) localTicket(ctx context.Context, m *session.Manager) (*url.Userinfo, error) {
-	ticket, err := m.AcquireLocalTicket(ctx, os.Getenv("USER"))
+	u, err := user.Current()
+	if err != nil {
+		return nil, err
+	}
+	ticket, err := m.AcquireLocalTicket(ctx, u.Username)
 	if err != nil {
 		return nil, err
 	}
```

**Comment by brad-jones** [comment]
I just tried with `$env:USER="$env:USERNAME"; govc ls -u localhost -k` and I still get:
```
C:\Users\brad.jones\scoop\apps\govc\current\govc_windows_amd64.exe: NotAuthenticated
```

**Comment by joeg-pro** [comment]
I see the same symptoms using govc on Windows 10 with Workstation Pro 15.  Looking forward to a fix soon I hope.
