### ISSUE TITLE
NotAuthenticated: timeout ??

### ISSUE THREAD

**Issue by nORKy54** [vmware/govmomi#1839]
Hi,

I stared 3 govc library.deploy at the same time. It takes 50min. At the end of each clone (100% done), I get this error : NoAuthenticated.

Perhaps it's a timeout ? How can I remove this error ?
I don't find any 'keep alive' settings on govc

Thanks you

**Comment by dougm** [comment]
I think we need to change govc to use KeepAlive for the SOAP endpoint here.
#1832 is related, but we need to add KeepAlive for the REST endpoint.
