### ISSUE TITLE
govc: Add ability to create and destroy a snapshot.

### ISSUE THREAD

**Issue by bitwisekaizen** [vmware/govmomi#184]
I'd be happy to work on the implementation for this request.

**Comment by mkuzmin** [comment]
Any change to have a snapshot API?

Actually my usecase is even simpler than creating and deleting snapshots: I need to create linked VM clones, and just need to pass a referencу to `VM.snapshot.currentSnapshot` object. Any suggestions how can it be done?

**Comment by dougm** [comment]
In general, all the APIs are available in govmomi as they are generated from the wsdl.  For example, looking at the docs here:
http://pubs.vmware.com/vsphere-55/topic/com.vmware.wssdk.apiref.doc/vim.VirtualMachine.html#createSnapshot

git grep CreateSnapshot_Task and you'll see generated methods and types under vim25/

We have been adding simple wrappers for such methods, for example have a look at the govmomi/virtual_machine.go Power* methods.  We have a generator for these wrappers in the works, but in the meantime have also been creating some of the wrappers by hand.

**Comment by mkuzmin** [comment]
Thank you for the explanation, I've made this work.

**Comment by dougm** [comment]
#354 #499 #506
