### ISSUE TITLE
Add Pronunciation to readme

### ISSUE THREAD

**Issue by therevoman** [vmware/govmomi#1840]
is govc pronounced "gov-c" or "go-vc" or something else?
same goes for the other tools.

**Comment by dougm** [comment]
Good idea, will do.
It is "go-v-c", as in "Go(lang) vCenter CLI".

"v-c-sim", as in "vCenter Simulator"

And "go-v-mom-ie", following pyvmomi and rbvmomi. Lang prefix + the old/original acronym "VM Object Management Infrastructure"
