### ISSUE TITLE
simulator extension pattern doesn't work for singletons

### ISSUE THREAD

**Issue by sigma** [vmware/govmomi#1841]
The approach to simulator extension as described in `simulator/example_extend_test.go` doesn't work for a number of singletons in the system.
If nothing else, because the registry exposes convenience accessors for these that look like:
```
func (r *Registry) VirtualDiskManager() *VirtualDiskManager {
	return r.Get(r.content().VirtualDiskManager.Reference()).(*VirtualDiskManager)
}
```
so putting a wrapper object is doomed to fail.

I'm curious to know if:
- there's something I'm missing that would allow customizing, let's say, responses to calls such as `CreateVirtualDiskTask`
- there's an agreeable way of plugging that gap. In order not to break the API compatibility, I was thinking of adding for example a `CreateVirtualDiskTaskFunc` field to `VirtualDiskManager`, that would preempt the default implementation. It doesn't fit that well with the existing model tough.

**Comment by dougm** [comment]
It'll work with singletons, provided you re-use the same moref from `ServiceContent`.  For example:
https://github.com/vmware/govmomi/blob/e024d19c58ae4f6ad51b0a493b88caee60753588/property/wait_test.go#L94-L96

Can also use ServiceContent via vim25.Client:
```diff
modified   property/wait_test.go
@@ -92,7 +92,7 @@ func TestWaitPermissionFault(t *testing.T) {
 	c, _ := govmomi.NewClient(ctx, s.URL, true)
 
 	pc := new(PropertyCollector)
-	pc.Self = model.ServiceContent.PropertyCollector
+	pc.Self = c.ServiceContent.PropertyCollector
 	simulator.Map.Put(pc)
 
 	dm := object.NewVirtualDiskManager(c.Client)
```

Would that work for you?  Open to improving this of course, but the pattern above should work fine for `VirtualDiskManager` and others.

**Comment by sigma** [comment]
@dougm unless I'm missing something, this allows to replace the singleton instance, but not to use a different implementation type. In `simulator/example_extend_test.go` what makes the whole thing work is being able to register an instance of a custom type `BusyVM` using an existing moref so that its own implementation of `PowerOffVMTask` can be used for example.

So while I could create a new instance of a singleton, I don't think there's really a way to make it behave differently from the original (for example to make `CreateVirtualDiskTask` fail unconditionally). Does that make sense?

**Comment by dougm** [comment]
@sigma not sure what you mean, it is possible currently to make `CreateVirtualDiskTask` fail unconditionally.
Although there are cases where `VirtualDiskManager` methods are called internally (e.g. `createVirtualDisk`)
Either way, I'd be ok with adding a `CreateVirtualDiskTaskFunc` field to `VirtualDiskManager` as you suggest.

**Comment by dougm** [comment]
@sigma sorry, I see, the registry convenience accessors are indeed the issue here. I'm open to adding Func fields as needed or changing the convenience accessors to return an interface instead of a pointer to a concrete type.

**Comment by sigma** [comment]
@dougm do you have a preference between the 2 approaches? returning an interface would be less "noisy", but it's also an incompatible change.
Either way I'm happy to work on that.

**Comment by dougm** [comment]
@sigma I don't think these helpers are used much or at all externally. Incompatible change here is ok with me either way, sounds like returning an interface is the way to go for the long term. Thanks!

**Comment by dougm** [comment]
Closing as you've addressed this with your PRs, thanks again @sigma
