### ISSUE TITLE
docker: container images are outdated

### ISSUE THREAD

**Issue by lucab** [vmware/govmomi#1844]
According to https://hub.docker.com/r/vmware/govc/tags, last built release is v0.18 and the `latest` tag was last updated two years ago.

I see there is a GoReleaser config in this repository, but possibly something is missing in its plumbing.

/cc @frapposelli @dougm

**Comment by lucab** [comment]
While at it, GoReleaser config seems to be also missing a stanza to publish a container for `toolbox`.

**Comment by dougm** [comment]
@lucab indeed, #1375 was intended to fix this but it still wip.  Ideally someone could complete the GoReleaser work, but we could also consider manually publishing govc and vcsim images.

Not sure about toolbox though, as it designed to be embedded (e.g. VIC). The toolbox/main.go is functional, but meant more for example and test. Do you have a use case for toolbox?

**Comment by lucab** [comment]
> we could also consider manually publishing govc and vcsim images

As a stopgap solution, that would be appreciated. My direct usecase is https://github.com/coreos/fedora-coreos-docs/issues/50 (tldr: revamping CoreOS docs to be more devops- and container-friendly).

> Do you have a use case for toolbox?

I'm not fully sure `toolbox` is correct target for this, but I'm looking for an easy to containerize subset of open-vm-tools features. That is, mostly the introspection and reporting logic. Exploration still ongoing, the discussion comes from https://github.com/coreos/fedora-coreos-tracker/issues/70#issuecomment-505217264.

**Comment by lucab** [comment]
One additional thing. It would be nice to have a minimal shell environment (e.g. `FROM` busybox or alpine, instead of `scratch`).
Rationale is that most of the time you want to batch multiple commands (either manually or via a simple script), and invoking a separate container run for each becomes tedious fairly soon.
