### ISSUE TITLE
Add API to detach and attach disks using FCD id for virtual machine object

### ISSUE THREAD

**Issue by yashdesai93** [vmware/govmomi#1846]
Currently, there are methods to perform attach-disk[1] and detach-disk[2] tasks using the FCD id on a VM, but it would be useful to have API for the VirtualMachine object itself of the form:
```
func (v VirtualMachine) DetachDisk(ctx context.Context, id string) (error) 
func (v VirtualMachine) AttachDisk(ctx context.Context, id string, datastore ...) (error) 
```
For my usage this is how I implemented DetachDisk:
```
// DetachDisk detaches the disk from the vm.
func DetachDisk(ctx context.Context, vm *object.VirtualMachine, client *vim25.Client, id string) error {
	req := types.DetachDisk_Task{
		This:   vm.Reference(),
		DiskId: types.ID{Id: id},
	}

	res, err := methods.DetachDisk_Task(ctx, client, &req)
	if err != nil {
		return err
	}

	task := object.NewTask(client, res.Returnval)
	return task.Wait(ctx)
}
```

[1] https://github.com/vmware/govmomi/blob/master/vim25/methods/methods.go#L874
[2] https://github.com/vmware/govmomi/blob/master/vim25/methods/methods.go#L4334

**Comment by dougm** [comment]
@yashdesai93 sure, can you submit a Pull Request to add them?
