### ISSUE TITLE
govc: POST /api: 406 Not Acceptable for vCloud Director 9.7 (Tenant Portal)

### ISSUE THREAD

**Issue by eg15** [vmware/govmomi#1847]
Hi,

_govc about_ immediately returns **406 Not Acceptable** when trying to access vCloud Director Tenant Portal.

The environment variables:
```
export GOVC_INSECURE=true
export GOVC_URL="https://tenant.portal.example.com/api"
export GOVC_USERNAME='admin@ORG'
export GOVC_PASSWORD='password'
```

The request headers:
```
POST /api HTTP/1.1
Host: tenant.portal.example.com
Content-Type: text/xml; charset="utf-8"
Soapaction: urn:vim25/6.7
User-Agent: govc/0.22.1
```

The response headers:
```
HTTP/1.1 406 Not Acceptable
Content-Length: 899
Content-Type: application/vnd.vmware.vcloud.error+xml;version=32.0
Date: Tue, 25 Feb 2020 21:50:08 GMT
X-Vmware-Vcloud-Request-Execution-Time: 1
X-Vmware-Vcloud-Request-Id: d230f579-cab6-4ea0-b652-b04f4d233991
```

What can be wrong? Can _govc_ be used with a vCloud DIrector Tenant Portal at all?
[vcd-cli](https://github.com/vmware/vcd-cli) works fine with it.
Thank you.

Regards,
Eugene

**Comment by dougm** [comment]
I don't have any experience with VCD, but according to https://github.com/vmware/vcd-cli#documentation

> `vcd-cli` uses pyvcloud, the Python SDK for VMware vCloud Director.

That says `pyvcloud`, not `pyvmomi`. So I wouldn't expect `govmomi` (or govc) to work with this API endpoint either.
