### ISSUE TITLE
vCenter UI ova import stuck at 0%

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#1848]
Hi, I was using the govmomi and govc API with the progress logger and ran into an issue of the vcenter UI showing that the deploy OVF template task is at progress 0%, whereas I can see progress on my stdout. Is there something extra needed to configure the vcenter UI progress tracker?

**Comment by dougm** [comment]
The govc progress in this case is for each file uploaded, rather than the task progress displayed by the UI.  You can use `govc tasks` to display the task status.

**Comment by chardch** [comment]
So if I understand correctly, the progress of the ova import, which is called from [here](https://github.com/vmware/govmomi/blob/master/govc/importx/ovf.go#L323) is separate from the progress of the task displayed in vCenter?

Could you point me to the relevant code that tracks the progress of the task vCenter? Really appreciate your help!

**Comment by dougm** [comment]
Right.  The `tasks` command outputs the TaskInfo.Progress field here: https://github.com/vmware/govmomi/blob/1f52ede5c89479e36b5edd310740b649cb574e66/govc/task/recent.go#L197

**Comment by chardch** [comment]
Thanks! So if I'm calling lease.Upload from my own code, instead of using the govc CLI, is there a way I can make the task progress displayed in vCenter correctly? My current usage is that I use soap.Upload{} with the size of the upload and a progress logger. However, my vCenter task always shows 0%.

**Comment by dougm** [comment]
Are you calling this from your code? https://github.com/vmware/govmomi/blob/1f52ede5c89479e36b5edd310740b649cb574e66/govc/importx/ovf.go#L293-L294

iirc, that should update the task progress, via this: https://github.com/vmware/govmomi/blob/1f52ede5c89479e36b5edd310740b649cb574e66/nfc/lease_updater.go#L129-L134

**Comment by chardch** [comment]
Yea, I am calling StartUpdater

**Comment by chardch** [comment]
From what I've read, the lease only uses the size of the fileItems to compute the progress. Is that correct? Also, are there any params for creating the import spec that are necessary for this? https://github.com/vmware/govmomi/blob/master/govc/importx/ovf.go#L227:L236

**Comment by dougm** [comment]
I thought the lease progress was reflected in the task progress, but trying it now I see the same `0%` in the task progress.

I did notice when importing from the UI there are 2 tasks running: "Import OVF package" and
"Deploy OVF template".  But with govc, there's just the one "Deploy OVF template".

I wonder if something changed in recent-ish vCenter versions to support OVF import for the HTML5 UI.  iirc that feature wasn't available for the first while when the new UI was being introduced.  Either way, I'll try to find out what we're missing. I swear it used to work, but I also can't remember the last time I was looking at the UI (or govc tasks) when using govc import.

**Comment by chardch** [comment]
Thanks for checking Doug! It'd be awesome to understand out what's going on with that.
