### ISSUE TITLE
vcsim - RelocateVM_Task does not change folder

### ISSUE THREAD

**Issue by seandilda** [vmware/govmomi#1849]
I've recently starting using vcsim to test some of my code and it has been a huge help.  Unfortunately, I recently ran into a case where valid code is failing tests against vcsim.

I have code that uses RelocateVM_Task to change the resource pool and folder at the same time.  The task succeeds, but vcsim is only reporting the change in the resource pool.  If I query the folder of the VM, its still reporting the original folder.   This same code works properly (changes resource pool and folder) when used against vCenter.

Would it be possible to get the folder change working in vcsim as well?

Thanks!

**Comment by dougm** [comment]
@seandilda glad to hear vcsim has been helpful.  Can you review #1851 for the fix?

**Comment by seandilda** [comment]
@dougm  Thanks for the quick response!

I'd be happy to test it out, but I'm not a go developer, so I'm not sure how best to pull down and build the test branch.  I've been using 'go get -u' to install vcsim, but I don't see a way to point it to a different branch.

**Comment by dougm** [comment]
@seandilda that'd be great if you can try it out. There's a couple of ways with git, but here's one:

```console
% cd $GOPATH/src/github.com/vmware/govmomi
% git remote add dougm https://github.com/dougm/govmomi.git
% git fetch dougm
% git checkout dougm/issue-1849
% go install -v github.com/vmware/govmomi/vcsim
```

Then you can switch back to the vmware master branch using:
```console
% git checkout master
% go install -v github.com/vmware/govmomi/vcsim
```

**Comment by seandilda** [comment]
Thank you!  Those instructions are great.

I just tested your change and its working perfectly.

**Comment by dougm** [comment]
Great, thanks for testing it @seandilda
