### ISSUE TITLE
Unable to set the config attribute of mo.VirtualMachine in simulator

### ISSUE THREAD

**Issue by ShriVanitha** [vmware/govmomi#1858]
In one of my function, I am making use of the Device function provided by virtual_machine.go to return the hardware property of the VM. For the UT of the same I am using ESX and VPX. In one of the case, the config value under VirtualMachine struct should be nil.
But there is no variable provided by the simulator where the config value can be assigned nil.

**Comment by dougm** [comment]
You can use `simulator.Map` to access the objects and change any fields directly. Example:
https://github.com/vmware/govmomi/blob/09f40b1a69c0e05c59e78b5af4614b8cbe8a95ee/object/vm_guest_test.go#L39-L40

**Comment by dougm** [comment]
Closing as stale. Feel free to reopen if this is still an issue.
