### ISSUE TITLE
Have govc sso.group.update handle group in group 

### ISSUE THREAD

**Issue by dongursli** [vmware/govmomi#1861]
Like this 'govc sso.group.update -a $ADM_GRP_SUPERADMIN $ADM_GRP_GLB_VCENTER' where is '$ADM_GRP_SUPERADMIN' is a Active Directory group and '$ADM_GRP_GLB_VCENTER' is a local vCenter group. 

Ex: 'govc sso.group.update -a adgroup@ad-domain.tld Administrators'

Fails with error message:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd78be4]

goroutine 1 [running]:
github.com/vmware/govmomi/govc/sso/group.(*update).Run.func1(0xc0000c1d40, 0x12c59e0, 0xc0000c1d40)
        /root/go/pkg/mod/github.com/vmware/govmomi@v0.22.0/govc/sso/group/update.go:79 +0x254
github.com/vmware/govmomi/govc/sso.WithClient(0x143c260, 0xc0000a2010, 0xc00009d1e0, 0xc0002b1e30, 0x0, 0x0)
        /root/go/pkg/mod/github.com/vmware/govmomi@v0.22.0/govc/sso/client.go:79 +0x364
github.com/vmware/govmomi/govc/sso/group.(*update).Run(0xc0000aa7c0, 0x143c260, 0xc0000a2010, 0xc0000a8780, 0x0, 0x0)
        /root/go/pkg/mod/github.com/vmware/govmomi@v0.22.0/govc/sso/group/update.go:66 +0xce
github.com/vmware/govmomi/govc/cli.Run(0xc0000ac010, 0x4, 0x4, 0xc000088058)
        /root/go/pkg/mod/github.com/vmware/govmomi@v0.22.0/govc/cli/command.go:165 +0x56e
main.main()
        /root/go/pkg/mod/github.com/vmware/govmomi@v0.22.0/govc/main.go:97 +0x62
`

**Comment by dougm** [comment]
@dongursli can you review #1862 ?
