### ISSUE TITLE
Using RetriveWithFilter correctly

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1863]
I am trying to find VMs (not VM templates) using a view with  RetrieveWithFilter call, as follows.

m := view.NewManager(client.Client)
var kinds []string = make([]string, 1)
kinds[0] = objectType
v, err := m.CreateContainerView(ctx, *dc, kinds, true)
var vms []mo.VirtualMachine
err = v.RetrieveWithFilter(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms, property.Filter{"config.template": false})
// Also tried: err = v.RetrieveWithFilter(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms, property.Filter{"config.template": "false"})

In my setup there are 32 ordinary VMs and 1 vm template.  From the call above, I receive a total of 32 objects, which is correct.

However, when the "config.template": true option is used, I receive a total of 33 object, and not 1 object as I expected. Basically, the call returns all VMs and all VM templates.

What am I missing?
-k

**Comment by dougm** [comment]
The list is not cleared when calling `RetrieveWithFilter`, you'll need to set it to `nil` otherwise the existing list is appended to:

```go
vms = nil
err = v.RetrieveWithFilter(...)
```

**Comment by kayshavd** [comment]
Thanks Doug. Much appreciated.
