### ISSUE TITLE
Is there a method to get OS and Power State of a VM directly?

### ISSUE THREAD

**Issue by iamjhamukesh** [vmware/govmomi#1864]
Just like we have `govc vm.ip vm_name`, don't we have commands to get powerState and guestName directly of a VM. I know we can get them using these commands but I don't want to use grep: `govc vm.info vm_name | grep "Power State" ` and `govc vm.info vm_name | grep "Guest name"` . There is a method in which we can get the runtime of a vm if it is off or on but what if I need Power State of every vm. Is grep the only solution via govc for Guest name(OS) and Power State ? Json gives too much data, not able to segregate that

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectcollect

Example:
`govc object.collect -type m / name runtime.powerState guest.hostName`
