### ISSUE TITLE
Safe approach to vCenter login 

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#1865]
When connecting to vCenter using username/password, most common approach is to encode the username and password as part of the URL. But, the following caveat applies, per RFC 2396

// RFC 2396 warns that interpreting Userinfo this way
// ``is NOT RECOMMENDED, because the passing of authentication
// information in clear text (such as URI) has proven to be a
// security risk in almost every case where it has been used.''
func UserPassword(username, password string) *Userinfo {
------
Is there any other, safer way to login using username and password without using the URL encoded user/pass?

Thanks
-k

**Comment by dougm** [comment]
You can call `Login` directly instead of including `Userinfo` in the URL:
https://github.com/vmware/govmomi/blob/5cc9f67181417bb4e7fa466e14e5daff0be2075f/client.go#L90

**Comment by kayshavd** [comment]
Yes, I know I can call Login() directly, with a UserInfo object. I was wondering more about any other secure way (encrypted somehow) of sending credentials. I guess short of using tokens, there is no other way to login using username and password.

Thanks for the confirmation.
-k
