### ISSUE TITLE
RetrieveWithFilter does not fetch all properties of managed object

### ISSUE THREAD

**Issue by dnyaneshgate** [vmware/govmomi#1872]
Hi,
Using `ContainerView.RetrieveWithFilter` does not fetch all specs of querying object.
e.g. if called this method
```
var dst []mo.Datastore
v.RetrieveWithFilter(ctx, []string{"Datastore"}, []string{}, dst, property.Filter{"name": "datastore_test"})
```
Then dst doen't contain all specs like `name`, `summary`, `info` etc. except it only has `ManagedObjectReference`

`ContainerView.Retrieve` works as expected.

After hours of code walk through found issue in `Collector.Retrieve` in `collector.go`.
After applying following patch, getting result as expected. 

```
diff --git a/property/collector.go b/property/collector.go
index 3c35b1d..2c74bc6 100644
--- a/property/collector.go
+++ b/property/collector.go
@@ -143,7 +143,7 @@ func (p *Collector) Retrieve(ctx context.Context, objs []types.ManagedObjectRefe
                        spec := types.PropertySpec{
                                Type: obj.Type,
                        }
-                       if ps == nil {
+                       if len(ps) == 0 {
                                spec.All = types.NewBool(true)
                        } else {
                                spec.PathSet = ps
```

Please check if this patch can be applied in upstream.

If want, I can raise a pull request.

**Comment by dougm** [comment]
@dnyaneshgate please do open a PR, your change looks good. Normally to collect all properties you would use `nil` instead of `[]string{}`, but we should do the right thing in either case.

**Comment by dnyaneshgate** [comment]
@dougm I have opened a PR  #1875.

Also, as suggested will use `nil` instead of `[]string{}` 

Thanks!
