### ISSUE TITLE
vcsim: REST API 404 page not found / Session Id

### ISSUE THREAD

**Issue by Satak** [vmware/govmomi#1890]
Does vcsim support REST API routest like `https://localhost/rest/vcenter/vm`? I can authenticate by using this route: `https://localhost/rest/com/vmware/cis/session` and get the session ID but when I'm using that in the header I will always get 404 no matter what GET route I try to fetch. My vcsim runs locally in a container at port 443.

Here is Powershell 7 example, same thing with Python.

```powershell
# Authentication POST method works!
Invoke-RestMethod -Uri 'https://localhost/rest/com/vmware/cis/session' -SkipCertificateCheck -Authentication Basic -Credential (Get-Credential) -Method Post

<#
# getting this back from the post
PowerShell credential request
Enter your credentials.
User: username
Password for user username: *****

value
-----
c4ab10e9-2dfa-4ae3-bfb1-54cad209364d
#>

# This doesn't work :(
Invoke-WebRequest -Uri 'https://localhost/rest/vcenter/vm' -Headers @{'vmware-api-session-id' = 'c4ab10e9-2dfa-4ae3-bfb1-54cad209364d'} -SkipCertificateCheck
# Invoke-WebRequest: 404 page not found
```

**Comment by dougm** [comment]
Currently the REST simulator in vcsim just supports what govmomi does on the client side, mainly Content Library and Tagging.

**Comment by Satak** [comment]
> Tagging

Oh got it. Documentation should list all possible REST routes that are supported. Here is the wiki https://github.com/vmware/govmomi/wiki/vcsim-features
that says:

> Interacting with vcsim using the vSphere SOAP and **REST APIs covers the majority of use cases**

**Comment by Satak** [comment]
Any plans to implement simple VM rest api in vcsim? Start, stop, get would be nice

**Comment by dougm** [comment]
Don't have any plans to, but would welcome contributions.
