### ISSUE TITLE
Is it support NSX-T 2.5 API?

### ISSUE THREAD

**Issue by sober-wang** [vmware/govmomi#1892]
In my product environmental , we use VMware NSX-T for our kubernetes 
When I want monitor NSX-T events and will it into my prometheus cluster ,I feel so difficute. 
I want to know is the govmomi  support NSX-T 2.5 API and how to use it.
If govmomi support NSX-T 2.5 , Who can give me a example? 

Thanks.

**Comment by dougm** [comment]
govmomi does not support NSX-T.  You may want to look at: https://github.com/vmware/go-vmware-nsxt
