### ISSUE TITLE
govc object.collect -json -type m / name runtime.bootTime returns only 100 VMS

### ISSUE THREAD

**Issue by sithglan** [vmware/govmomi#1893]
Hello,
I have several vcenter with 10000 VMs each. I would like to collect the uptime of all VMs quickly (e.g. by not dumping all information about every VM). The following command only returns 100 VMs:

govc object.collect -json -type m / name runtime.bootTime

Cheers,
      Thomas

**Comment by dougm** [comment]
I can reproduce this, vCenter truncating the results.  Will try to get a fix in soon.

**Comment by sithglan** [comment]
Hello Dougm,
thank you for providing a quick fix. And also thank you for govc. It makes my life a lot easier. I'll provision tomorrow several thousand VMs with it. I compiled your fix and tested it. Works for me:

> (ba) [~] ./govc object.collect -type m / name runtime.bootTime | wc -l
7765

Before:

> (ba) [~] govc object.collect -type m / name runtime.bootTime | wc -l
175

Cheers,
       Thomas

**Comment by dougm** [comment]
Good to hear @sithglan and thanks for testing it out

**Comment by lukasluecke** [comment]
@dougm Do you know when this fix will be available as a prebuilt release?

**Comment by dougm** [comment]
Hoping to release 0.23 within the next week.
