### ISSUE TITLE
govc lists IP addresses for templates.

### ISSUE THREAD

**Issue by jayunit100** [vmware/govmomi#1894]
My first issue ! I love this tool .  Tiny issue I found today that id like to workaround for some automation I'm building.

Seems like `govc ls vm` should only list 'real' vms, not template vms, right? 

In my case I have only one VM on my machine, but govc lists the IP address of ESXi host  , I think, for my vms that I converted to VMTemplates.

```
➜  programs for i in `govc ls vm` ; do govc vm.info $i | grep Host | cut -d':' -f 2 | sed 's/  //g' >> IPS ; done
➜  programs cat IPS
 10.186.20.19
 10.186.20.19
 10.186.28.41
 10.186.20.19
 10.186.20.19
➜  programs rm IPS
➜  programs govc ls vm
/k8sdc/vm/photon-3-capv-haproxy-v0.6.2+vmware.1
/k8sdc/vm/bionic-server-cloudimg-amd64
/k8sdc/vm/photon-3-v1.17.3+vmware.1
/k8sdc/vm/ubuntu-18.10-server-cloudimg-amd64
/k8sdc/vm/devbox2
/k8sdc/vm/Discovered virtual machine
```

**Comment by dougm** [comment]
Hi @jayunit100 , great to see you here!

You can use `govc find` instead and filter based on any property, for example:
```console
# 5 total VMs in this env
% govc find -type m / | wc -l
5

# 4 VMs that are not templates
% govc find -type m / -config.template false | wc -l
4

# 1 VM that is a template
% govc find -type m / -config.template true
/dc1/vm/template-vm
```

**Comment by dougm** [comment]
Regarding the vm.info Host, right that is the ESX host.  Could be an IP or FQDN, but can also be an arbitrary name.  Either way the Host field is just the inventory name.  If you need the actual ESX host IP(s) that you can connect to, there are other fields to get that info.  Lemme know what you need there.

**Comment by dougm** [comment]
@jayunit100 does `govc find` do the trick for you?

**Comment by jayunit100** [comment]
ahhh yessss

**Comment by jayunit100** [comment]
would be nice if `govc find -type --help` gave a list of types ? but not sure if thats easy to do.

**Comment by dougm** [comment]
You can list the types like so:

```console
% govc find -h
Usage: govc find [OPTIONS] [ROOT] [KEY VAL]...

Find managed objects.

ROOT can be an inventory path or ManagedObjectReference.
ROOT defaults to '.', an alias for the root folder or DC if set.

Optional KEY VAL pairs can be used to filter results against object instance properties.
Use the govc 'object.collect' command to view possible object property keys.

The '-type' flag value can be a managed entity type or one of the following aliases:

  a    VirtualApp
  c    ClusterComputeResource
  d    Datacenter
  f    Folder
  g    DistributedVirtualPortgroup
  h    HostSystem
  m    VirtualMachine
  n    Network
  o    OpaqueNetwork
  p    ResourcePool
  r    ComputeResource
  s    Datastore
  w    DistributedVirtualSwitch
...
```

There's also a generated .md with all the help: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#find
