### ISSUE TITLE
govc vm.customize unable to change IP or setup DHCP

### ISSUE THREAD

**Issue by genadypuzis** [vmware/govmomi#1897]
Hi,
Just desperate to set DHCP for windows machine :)
when running latest (0.22.1 ) govc version for Linux ( govc_linux_amd64.gz) 
it's impossible to change IP ( or set up DHCP)

The outcome is:  govc vm.customize -vm mo-5220ad54d -ip 10.20.30.40 -type Windows
**govc: A specified parameter was not correct: spec.identity.userData.fullName**

**Comment by genadypuzis** [comment]
Same :) 
Just pasting full list of commands for sake of clarification:
a) govc object.collect -s /vms/mo-5220ad54d  guest.ipAddress guest.hostName
**WINHOST1234.kuku.corp
10.20.30.40**
b) govc vm.customize -vm mo-5220ad54d -type Windows -name WINHOST1234.kuku.corp  -ip dhcp
**govc: A specified parameter was not correct: spec.identity.userData.fullName**

**Comment by dougm** [comment]
ok, one option is to create a Customization Specification in the vCenter UI, then use that by name:
`govc vm.customize -vm mo-5220ad54d SPEC-NAME`

The UI will ensure that all required fields are set in the spec, then vm.customize use the spec and just changes fields based on the flags given.

**Comment by genadypuzis** [comment]
Thanks a lot!  
Is any other option? I need to run the scripts against many machines, so creating a spec for each of them almost impossible   in my case

**Comment by dougm** [comment]
You should only need 1 spec per-vCenter, not per machine.  The spec is just the defaults, and vm.customize flags can override the fields you need.

**Comment by dougm** [comment]
Any luck with this @genadypuzis ?

**Comment by dougm** [comment]
Closing as stale. Feel free to reopen if this is still an issue.
