### ISSUE TITLE
finder.VirtualMachine and VC

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#190]
When switching from a single ESX host to VC, the finder.VirtualMachine() function doesn't always find existing VMs. I'm currently using SearchIndex().FindChild() as a work around with "ha-datacenter/vm/" as the root folder.

When connected to VC, the finder mechanism seems to only be able to find VMs that appear under "Discovered virtual machine" which is rarely a comprehensive list.

**Comment by mkuzmin** [comment]
any progress on this?
Or maybe there is some other method to find a VM by name without knowing its full path?

**Comment by dougm** [comment]
The path given to finder.VirtualMachine is relative to the datacenter vmFolder.  You can use "folderName/vmName" or "*/vmName".  But we should probably add an option to recurse folders so we can find by name without a folder path.

**Comment by hickeng** [comment]
I've just been using FindChildByName in the interim. Not quite as concise and you need to process the reference returned,  but viable.
Please excuse me if I've got the function name slightly wrong, phone isn't good at browsing source.

George Hicken - mobile
ghicken@vmware.com


-------- Original message --------
From: Doug MacEachern
Date:20/01/2015 09:37 (GMT-08:00)
To: vmware/govmomi
Cc: George Hicken
Subject: Re: [govmomi] finder.VirtualMachine and VC (#190)


The path given to finder.VirtualMachine is relative to the datacenter vmFolder. You can use "folderName/vmName" or "*/vmName". But we should probably add an option to recurse folders so we can find by name without a folder path.

-

**Comment by dougm** [comment]
I had looked into that and tested it out, but doesn't look like it recurses into sub folders:

http://pubs.vmware.com/vsphere-55/topic/com.vmware.wssdk.apiref.doc/vim.SearchIndex.html#findChild

"This only searches the immediate children of a managed entity"

**Comment by mkuzmin** [comment]
VM name is an unique property, and enumerating all the folders on the a client side doesn't look as effective solution. `SearchIndex` doesn't provide such lookup methods, but there is alternate API. Here is how I currently do that in Groovy:
`def vm = new InventoryNavigator(client.getRootFolder()).searchManagedEntity("VirtualMachine", "name")`
It would be great to have the same API here.

**Comment by dougm** [comment]
Agreed, I'll try to look into this over the weekend or early next week.

**Comment by mkuzmin** [comment]
Any update on this?

**Comment by aashishparikh** [comment]
Hey guys.. Any updates?
