### ISSUE TITLE
govc template.clone action wanted

### ISSUE THREAD

**Issue by weakcamel** [vmware/govmomi#1900]
vSphere 6.7 supports cloning a template to template, which is useful for example when you want to move templates around.

I tested `vm.clone` action as a replacement, however it didn't work - at first vSphere proceeded with cloning, hower later GOVC tried to power this template up and it failed.

```
govc vm.clone -pool=packer-templates \
  -ds=new-datastore -template=true -cluster=cluster1 \
  -vm templates/ubuntu-18.04-264490 templates/cloned-ubuntu-18.04-264490 
```

As a user, I'd love to have gcov support 'template.clone' action with similar syntax to 'vm.clone' so I can safely copy files across with CLI.

**Comment by dougm** [comment]
I think you can do that already using `govc vm.clone -template -on=false ...`
We should default on=false if the `-template` flag is given though.

**Comment by weakcamel** [comment]
Hi @dougm 

Many thanks for your suggestion. It did indeed work, with the following combination:

```
govc vm.clone -pool=packer-templates \
  -ds=new-datastore -cluster=cluster1 \
  -template=true -on=false \
  -vm templates/ubuntu-18.04-264490 \
  -folder /<ROOT>/vm/templates/ \
  cloned-ubuntu-18.04-264490 
```

I wonder, would a MR with similar example in https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmclone make sense?

**Comment by dougm** [comment]
@weakcamel yes, an MR with example would be great.  Note that USAGE.md is generated, you can add the example here:

https://github.com/vmware/govmomi/blob/38815aeff0440965aa574fbcf3b030d2ee2e3ab0/govc/vm/clone.go#L122

We use `make doc` to regenerate USAGE.md at release time.

**Comment by dougm** [comment]
And if you want to default `on=false` when `template=true`, that'd be great too.  I think something like this (untested) would do the trick:
```diff
modified   govc/vm/clone.go
@@ -261,6 +261,10 @@ func (cmd *clone) Run(ctx context.Context, f *flag.FlagSet) error {
 		}
 	}
 
+	if cmd.template {
+		return nil
+	}
+
 	if cmd.on {
 		task, err := vm.PowerOn(ctx)
 		if err != nil {
```
