### ISSUE TITLE
govc: ServerFaultCode: The object 'vim.VirtualMachine:vm-2284' has already been deleted or has not been completely created

### ISSUE THREAD

**Issue by sithglan** [vmware/govmomi#1908]
Hello,
I have a vCenter with several thousand VMs. When I run the following command:

> (ba) [~] govc find . -type m
govc: ServerFaultCode: The object 'vim.VirtualMachine:vm-2284' has already been deleted or has not been completely created

How to idenitfy the offending VM? Can govc just ignore the error and give me a list VMs it has?

Cheers,
        Thomas

**Comment by sithglan** [comment]
Hello,
I found out that the vm-xxxx number changes constanly, because I have another govc instance which is currently destoying 1400 machines.

Cheers,
    Thoams

**Comment by dougm** [comment]
hmm, not sure if we can gracefully handle this on the govc side.  If this error is being returned by the PropertyCollector on a ContainerView.

**Comment by sithglan** [comment]
Hello,
I see my use case is: I have 40.000 Citrix VDIs. When I rollout a new master image, I need to delete all the vms and recreate them. While I do that, other scripts which use govc choke on the above error. The other scripts for example see if there is a virtual desktop which should be poewered off or one that should be powered on. So when I run the vm.destroy options, inventory collection for example fails.

Reproduce:
destroy 1400 VMs.
While doing so try to run
govc find . -type m

Cheers,
      Thomas

**Comment by dougm** [comment]
@sithglan I was thinking of `object.collect` when I commented.  The fix for `find` in this case is straight forward, see #1916

**Comment by sithglan** [comment]
Hello @dougm thank you for fixing it, I rolled the new version out into production. Let you know if I see any more issues. Thank you again for govc. It has become a crutial tool for maintaining 300 ESX servers and several ten thousand VMs. Due to corona we have 30 additional ESX Servers coming in every day. I use govc to deploy citrix linked clones. It really, really scales. For example last night I rebooted 7000 VMs within an hour using govc. One thing bugs me: Is it possible with govc to do a cross vcenter clone (copy of static VM state) without using ovf export/import? At the moment, when I rollout a new master image (which ends up being on 300 hosts) I copy one in each vCenter and than I have perl script which looks where the image is located and where it needs to be going. Than for each image I have, i copy to another server.Once finished I rinse and repeat doing twice as many copys. So I can rollout a 50GB master image within 2 hours all our current and future hosts. However I would like to do the cross vcenter using govc as well. OVF import/export i dislike because it is several times slower. Cheers, Thomas

**Comment by sithglan** [comment]
Hello @dougm the code solved my issue, thanks a lot. Cheers, Thomas

**Comment by dougm** [comment]
@sithglan great to hear govc is working well for you at such large scale.  Regarding cross vCenter clone, can you open a separate issue for that?  I don't have any experience with linked vCenters myself, but have been meaning to get some.  There is a bit of code in #1600 that can get us started. But at the moment, we don't have that functionality in govc.
