### ISSUE TITLE
vcsim: CreateImportSpec panic for PCF OpsManager ova in relation to ovfDiskCapacity

### ISSUE THREAD

**Issue by matthewcosgrove** [vmware/govmomi#1909]
Using `ops-manager-vsphere-2.7.14-build.284.ova` I have observed

- `govc import.ova` successful on an actual vcenter lab
- `govc import.ova` fails on vcsim using defaults (See error below)
- `govc import.ova` fails on vcsim after loading the vcenter objects obtained from `object.save` against the lab mentioned above (See error below)

Both failures result in the same error..

```bash
2020/04/05 17:47:10 http: panic serving 127.0.0.1:48594: runtime error: invalid memory address or nil pointer dereference
goroutine 111 [running]:
net/http.(*conn).serve.func1(0xc001402820)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xdc3640, 0x19695a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/vmware/govmomi/simulator.ovfDiskCapacity(0xc0014fc140, 0x5)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/ovf_manager.go:86 +0x61
github.com/vmware/govmomi/simulator.(*OvfManager).CreateImportSpec(0xc0000decd0, 0xc001ffe000, 0xc001fd8160, 0x0, 0x0)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/ovf_manager.go:265
```
I don't have time to dig deeper right now, but hoping to at some point in the near future

**Comment by dougm** [comment]
I can also take a look if you can share the .ovf and/or where to download the .ova

**Comment by matthewcosgrove** [comment]
Thanks Doug. A Pivotal Network account is required. Exact binary I tested can be found via either of these

- GUI: https://network.pivotal.io/products/ops-manager#/releases/602506
- API: https://network.pivotal.io/api/v2/products/ops-manager/releases/602506/product_files/637920/download
- CLI: pivnet download-product-files --product-slug='ops-manager' --release-version='2.7.14' --product-file-id=637920
