### ISSUE TITLE
govc: Add capability to add and remove standalone host to/from datacenter.

### ISSUE THREAD

**Issue by bitwisekaizen** [vmware/govmomi#191]
Doesn't look like we have the ability to add or remove a host to a datacenter from govc or from datacenter.go.  Perhaps we could have something like this:

     $ govc datacenter.addhost -dc=somedatacenter -hostname=somehost -hostuser=root -hostpassword=password
     $ govc datacenter.removehost -dc=somedatacenter -hostname=somehost

I'm working on this now to support my work on the  Terraform vSphere plugin.  Would be happy to contribute it back upstream if the usage above looks reasonable to you guys.

**Comment by pietern** [comment]
@bitwisekaizen Hi Gavin, did you end up working on this? If not, somebody else can pick it up.

**Comment by bitwisekaizen** [comment]
I actually have a changed shelved for this.  I got sidetracked for a while, but I should be able to put it up in the next couple of days.  Hoping to get more active in the next few weeks.

**Comment by pietern** [comment]
Thanks for the update.

**Comment by dougm** [comment]
We have added both 'host.add' (e01555f) and 'cluster.add' (5154339) commands to govc.
