### ISSUE TITLE
govc built on Windows 10 - govc import.ova fails with "invalid character 'ÿ' looking for beginning of value"

### ISSUE THREAD

**Issue by ferdinandosimonetti** [vmware/govmomi#1911]
**OS:** Windows 10 1909
**Go version**: go version go1.14.1 windows/amd64
**GOVC build command**: 
`go get -u github.com/vmware/govmomi/govc`

**GOVC-related environment variables**:
```
PS C:\Users\ferdi\Downloads> $env:GOVC_INSECURE
1
PS C:\Users\ferdi\Downloads> $env:GOVC_DATASTORE
datastore1
PS C:\Users\ferdi\Downloads> $env:GOVC_NETWORK
VM Network
PS C:\Users\ferdi\Downloads> $env:GOVC_RESOURCE_POOL
CL01/Resources
PS C:\Users\ferdi\Downloads> $env:GOVC_DATACENTER
DC01
```

I have set **GOVC_URL**, **GOVC_USERNAME** and **GOVC_PASSWORD** too.

**GOVC import.ova Powershell command line and output**:
```
PS C:\Users\ferdi\Downloads> govc import.ova -options=c:\users\ferdi\Downloads\ubuntu.json c:\users\ferdi\Downloads\ubuntu-18.04-server-cloudimg-amd64.ova
C:\Users\ferdi\go\bin\govc.exe: invalid character 'ÿ' looking for beginning of value
PS C:\Users\ferdi\Downloads> govc import.ova -options c:\users\ferdi\Downloads\ubuntu.json c:\users\ferdi\Downloads\ubuntu-18.04-server-cloudimg-amd64.ova
C:\Users\ferdi\go\bin\govc.exe: invalid character 'ÿ' looking for beginning of value
```
**GOVC import.ova cmd.exe command line and output**:
```
C:\Users\ferdi\Downloads>govc import.ova -options=c:\users\ferdi\Downloads\ubuntu.json c:\users\ferdi\Downloads\ubuntu-18.04-server-cloudimg-amd64.ova
govc: invalid character 'ÿ' looking for beginning of value

C:\Users\ferdi\Downloads>govc import.ova -options c:\users\ferdi\Downloads\ubuntu.json c:\users\ferdi\Downloads\ubuntu-18.04-server-cloudimg-amd64.ova
govc: invalid character 'ÿ' looking for beginning of value
```
**GOVC command with debug enabled**:
```
PS C:\Users\ferdi\Downloads> govc import.ova -debug=true -dump=true -options=c:\users\ferdi\Downloads\ubuntu.json c:\users\ferdi\Downloads\ubuntu-18.04-server-cloudimg-amd64.ova
flags.errorOutput{
    error: &json.SyntaxError{msg:"invalid character 'ÿ' looking for beginning of value", Offset:1},
}
```

Attached, you can find a zipped version of my ubuntu.json file.

[ubuntu.zip](https://github.com/vmware/govmomi/files/4437656/ubuntu.zip)

**Comment by dougm** [comment]
What did you use to edit ubuntu.json?  Sounds like something windows related, for example found this googling: https://forum.ethereum.org/discussion/2585/can-t-load-genesis-block-fatal-invalid-character-y-looking-for-beginning-of-value

**Comment by ferdinandosimonetti** [comment]
Hello, I was using Visual Studio Code, and I’ve aleeady found (again) the answer... Ubuntu.json needs to be converted via dos2unix utility.
Actually, I was certain to have already closed the question... but it seems that it’s still open.
Thanks anyway, you would have pointed me to the right direction.


Ing. Ferdinando Simonetti - UNIX Sysadmin / Cloud Architect
Mobile phone: +39 3479878174<tel:+39%203479878174>
E-mail: info@fsimonetti.eu<mailto:info@fsimonetti.eu>
Skype ID: ferdinando.simonetti@outlook.com<mailto:ferdinando.simonetti@outlook.com>

Il giorno 7 apr 2020, alle ore 00:10, Doug MacEachern <notifications@github.com> ha scritto:

﻿

What did you use to edit ubuntu.json? Sounds like something windows related, for example found this googling: https://forum.ethereum.org/discussion/2585/can-t-load-genesis-block-fatal-invalid-character-y-looking-for-beginning-of-value<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforum.ethereum.org%2Fdiscussion%2F2585%2Fcan-t-load-genesis-block-fatal-invalid-character-y-looking-for-beginning-of-value&data=02%7C01%7C%7C8c978984c1754661193008d7da774aca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637218078190339967&sdata=LW0TTeIMPIL7H78O8ZPah2rv%2B%2BBj7pyvZsHujoQKYys%3D&reserved=0>

**Comment by ferdinandosimonetti** [comment]
I was able to find the answer (again, I just forgot) here [](https://vmsysadmin.wordpress.com/2019/09/14/getting-started-with-govc-on-windows/)
I can confirm that applying [dos2unix.exe](https://waterlan.home.xs4all.nl/dos2unix.html) to my ubuntu.json fixed the issue, and that [b64.exe](https://sourceforge.net/projects/base64/) was more than adequate to encode my user-data in Base64.
