### ISSUE TITLE
NSX support?

### ISSUE THREAD

**Issue by jayunit100** [vmware/govmomi#1923]
Since govmomi provides a unified idiom for accessing both ESXi and VSphere APIs , it seems natural to also support NSX as well.  Just a thought, curious if any plans to do this. 

I do know there is https://github.com/vmware/go-vmware-nsxt, so , maybe there isn't too much need for specific implementation of this in govmomi, maybe should just reference the official go client recommendation for NSX-T in the README (i.e. vmware/go-vmw-nsxt)

**Comment by dougm** [comment]
Not planning to, but this has come up a few times (recently in #1892), good idea adding a link in the README.
