### ISSUE TITLE
Trying to find more detailed documents

### ISSUE THREAD

**Issue by lunakoa** [vmware/govmomi#1925]
I am trying to find where there are more detailed documents on using govc.  

There is the README.md and various examples, but they are not centralized.  Maybe it is and I just dont know about it.

I looked at https://code.vmware.com/docs/5502/cmdlets-reference-guide/doc/ScsiControllerType.html hoping to set the scsi controller type but ParaVirtual is actually pvsci, other parameters like net.adapter would be nice.

Is there a central documentation where all this is held?

**Comment by dougm** [comment]
We have USAGE.md: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#devicescsiadd

**Comment by lunakoa** [comment]
dougm thank you for the response, but I was hoping for something a little but more detailed that is tied in with the vmware API, for example, vm.create in that link you send has a -disk.controller=scsi and -net.adapter=e1000.

Sometimes I would like to use an lsi adapter, other times I would like to use a paravirtual adapter, I would like to know what names to use, in the link from vmware I posted above, a paravirtual adapter is listed as ParaVirtual, but to specify it in govc, you have to use pvscsi for example

govc vm.create -on=false -m 4096 -c 2 -net.adapter vmxnet3 -net black8 -disk.controller pvscsi -ds datastore -disk=60G -g centosGuest mylinuxserver

Honestly I forget where I got that Information from, for the -net.adapter option I know I can use e1000 pcnet vmxnet2 or vmxnet3 but I am not sure what parameters to use with govc

For the guest os type, the -g function I was hoping to find out where I can specify Windows 2008R2, CentOS 6, or CentOS 7 etc

Hoping to find the magic location where all these parameters are documented for govc because they do not accurately line up with vmware documentation

Here is the link again for the SCSI types
https://code.vmware.com/docs/5502/cmdlets-reference-guide/doc/ScsiControllerType.html

Here is the link for the NIC types
https://code.vmware.com/docs/5502/cmdlets-reference-guide/doc/VirtualNetworkAdapterType.html

Here is the link for the OS Types, this link seems to be accurate and works with govc
https://www.vmware.com/support/orchestrator/doc/vro-vsphere65-api/html/VcVirtualMachineGuestOsIdentifier.html

Thanks Again

**Comment by dougm** [comment]
Understood, we need to add docs.. other than the help options, the mapping from govc short name to full type name only lives in the code currently: https://github.com/vmware/govmomi/blob/4966fff513584f0d4b454036a8435b6eba468936/object/virtual_device_list.go#L842-L870

We could also change govc to accept the full type name as input.
