### ISSUE TITLE
simulator: IP allocation for import.ova

### ISSUE THREAD

**Issue by matthewcosgrove** [vmware/govmomi#1928]
I'm not seeing an IP allocated for an ova deployed to vcsim through `govc import.ova`. It's a PropertyMapping field so appreciate this is non-standard with wider design implications

```json
  "PropertyMapping": [
    {
      "Key": "ip0",
      "Value": "10.0.2.2",

```

Just wondering what it would take to get something like this working?

I can see that it's possible programmatically

```go
    spec := types.VirtualMachineConfigSpec{
        ExtraConfig: []types.BaseOptionValue{
            &types.OptionValue{Key: "SET.guest.ipAddress", Value: "10.0.0.42"},
        },
    }
```
according to the example in https://godoc.org/github.com/vmware/govmomi/simulator

**Comment by dougm** [comment]
@matthewcosgrove possible with #1929 , using `SET.guest.ipAddress`.  If the key needs to be `ip0` for your use case, we can look at adding something for that too.

**Comment by matthewcosgrove** [comment]
Thanks @dougm, yes the ova I'm using (Pivotal OpManager) uses `ip0` for the key as shown in the PropertyMapping excerpt above. Would be fantastic if you could add support for that in
