### ISSUE TITLE
Templates return as empty VirtualMachine objects

### ISSUE THREAD

**Issue by jmmcatee** [vmware/govmomi#193]
Currently templates show up as virtual machines, but nothing is populated for this type, so it isn't really possible (that I have found yet, big caveat) to tell if a virtual machine is a template besides just guessing based on the blank status.

**Comment by dougm** [comment]
@jmmcatee can you give more context here, govc command or api you're using?  There is no managed object for templates, so the api will return the VirtualMachine type for templates.  But you can check the VirtualMachineConfigInfo.Template flag.  For example:

% govc vm.info -json foo | jq .VirtualMachines[].Config.Template
false

**Comment by jmmcatee** [comment]
Here is a gist of what I am experiencing. 

https://gist.github.com/jmmcatee/f2f77184d20cc86e96b3

Templates show up as empty VirtualMachine structs. Let me know if this helps identify the problem at all.

**Comment by mkuzmin** [comment]
I also work with templates and don't experience such issues. Can it be a problem in thу 3rd-party library you're using?

**Comment by jmmcatee** [comment]
I'm only using govmomi. If you run my code do you get different results?

**Comment by jmmcatee** [comment]
Ultimately I'd like to create a VirtualMachine from a template via the API. How might I got about doing that? Does the API or govc support that at this time?

**Comment by jmmcatee** [comment]
I have created another Gist that includes all code that is not pulled from govmomi. This returns false for all VirtualMachines, but panics in the event a template is hit. I really am not sure what I'm doing wrong here.

https://gist.github.com/jmmcatee/eba0f808275301eae802

**Comment by daniellockard** [comment]
What type does it say the Template is? It should be a VirtualMachine. A template is still a VirtualMachine that has just been registered as a template (or marked as one).  They way I'm accomplishing this right now is just knowing my templates name and then using some (slightly simplified) code like this:

```go

finder := find.NewFinder(client, false)
vm, _ := finder.VirtualMachine("TemplateName")
resourcePool, _ := finder.DefaultResourcePool()
rpRef := resourcePool.Reference()
clonespec := types.VirtualMachineCloneSpec{
    Location: types.VirtualMachineRelocateSpec{
        Pool: &rpRef,
    }
}

task, _ := vm.Clone(folders.VmFolder, "New VM Name", clonespec)
task.WaitForResult(nil)


```

Are you wanting to iterate through your VM list and pick out just the templates? I'm not sure if you can do that as it stands right now, you may consider putting them all in a specific folder so that you can just list a folder and pick a template from there.

**Comment by jmmcatee** [comment]
I'd like to be able to iteration so I can provide a selection menu. They do show up as VirtualMachines in the Reference, but any attempt to pull up the name or anything else about them either panics or is nil. Could this be a problem with how VirtualMachines that are marked as templates change in the XML response?

**Comment by daniellockard** [comment]
I think you were just constructing the VM objects incorrectly. This should loop over your VMs and output "vmname,template". Essentially I believe you were constructing an empty VirtualMachine object and never pulling the Properties into it.

https://gist.github.com/daniellockard/b9ae34e270333f0887bb

**Comment by jmmcatee** [comment]
Your version works for me. I guess i don't understand why this is required for Templates, but not Virtual Machines as those load the whole structure just fine without the "Summary" addition.

**Comment by daniellockard** [comment]
I didn't see it work with your version, for VMs or Templates. Glad I could help. I think this can be closed @dougm @pietern.

**Comment by pietern** [comment]
Perfect, thanks for your help @daniellockard!
