### ISSUE TITLE
In Record-playback not able to get host.configManager.networkSystem.networkInfo populated

### ISSUE THREAD

**Issue by akulkarnivnera** [vmware/govmomi#1935]
Record playback feature used. 
While reading from VCSim not able to get host.configManager.networkSystem.networkInfo.
Is it because below attribs are not pointed properly :

types.go =>
type HostConfigManager struct {
	DynamicData

	CpuScheduler              *ManagedObjectReference `xml:"cpuScheduler,omitempty"`
	DatastoreSystem           *ManagedObjectReference `xml:"datastoreSystem,omitempty"`
	MemoryManager             *ManagedObjectReference `xml:"memoryManager,omitempty"`
	StorageSystem             *ManagedObjectReference `xml:"storageSystem,omitempty"`
	NetworkSystem             *ManagedObjectReference `xml:"networkSystem,omitempty"`
	VmotionSystem             *ManagedObjectReference `xml:"vmotionSystem,omitempty"`

**Comment by dougm** [comment]
@akulkarnivnera #1939 should fix that, can you try it out?

**Comment by akulkarnivnera** [comment]
Thanks !!!
It worked!

**Comment by dougm** [comment]
@akulkarnivnera ok great, merged!
