### ISSUE TITLE
Permission denied when creating or cloning vm

### ISSUE THREAD

**Issue by maximgrigorov** [vmware/govmomi#1936]
Hello.

I cannot clone or create VM with govc or terraform in our environment.

```
[mgrigorov@ ~]$ govc version
govc 0.22.1
```

```
[mgrigorov@ ~]$ govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        15129973
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.3
Product ID:   vpx
```

When I try to clone vm with govc, I'm getting the following error:

```
[mgrigorov@ ~]$ export | grep GO
declare -x GOVC_CLUSTER="Cluster"
declare -x GOVC_DATASTORE="/dc/datastore/vmstore-di1"
declare -x GOVC_FOLDER="/dc/vm/RnD/NoBackup"
declare -x GOVC_INSECURE="true"
declare -x GOVC_PASSWORD="***"
declare -x GOVC_RESOURCE_POOL="rpDI1"
declare -x GOVC_URL="***"
declare -x GOVC_USERNAME="***"

[mgrigorov@ ~]$ govc vm.clone -dump=true -debug=true -cluster=Cluster -vm source_vm destination_vm
&soap.Fault{
    XMLName: xml.Name{Space:"http://schemas.xmlsoap.org/soap/envelope/", Local:"Fault"},
    Code:    "ServerFaultCode",
    String:  "Permission to perform this operation was denied.",
    Detail:  struct { Fault types.AnyType "xml:\",any,typeattr\"" }{
        Fault: types.NoPermission{
            SecurityError: types.SecurityError{},
            Object:        types.ManagedObjectReference{Type:"ResourcePool", Value:"resgroup-27"},
            PrivilegeId:   "Resource.AssignVMToPool",
        },
    },
}
```

Our hierarchy of objects:
Cluster (Type:"ClusterComputeResource", Value:"domain-c26") -> Resource (Type:"ResourcePool", Value:"resgroup-27") -> rpDI1 (Type:"ResourcePool", Value:"resgroup-6474")

Regarding privileges, my user has ReadOnly permissions (propogated) on Cluster and the service resource pool named "Resource", but it also has Resource.AssignVMToPool permission for the pool rpDI1, which is explicitly provided by our Technical Support (this team manages vCenter).

```
[mgrigorov@ ~]$ govc permissions.ls /dc/host/Cluster/Resources
Role                          Entity   Principal                                                                       Propagate
ReadOnly                      /dc  DOMAIN\vSphere DI Service Users                                   Yes

[mgrigorov@ ~]$ govc permissions.ls /dc/host/Cluster/Resources/rpDI1
Role                          Entity                               Principal                                                                       Propagate
vSphere DI Service Role       /dc/host/Cluster/Resources/rpDI1  DOMAIN\vSphere DI Service Users                                   Yes

[mgrigorov@ ~]$ govc role.ls "vSphere DI Service Role" | grep "Resource.AssignVMToPool"
Resource.AssignVMToPool
```

I'm able to create/clone VM directly in vSphere UI and using some other clients, like yavijava (a fork of vijava) with same parameters, but stuck with govc.

If this is the expected behavior, please provide a workaround, because our team does not have admin permissions on our vSphere installation.

Thanks!

**Comment by dougm** [comment]
@maximgrigorov I haven't created a setup to reproduce the NoPermission error, but I think #1938 may solve the problem.  Can you try it?

**Comment by maximgrigorov** [comment]
@dougm, I confirm. When I unset the GOVC_CLUSTER environment variable, cloning started. Also, when I removed the cluster definition from terraform sources, cloning also started.
Thanks!

**Comment by dougm** [comment]
Great, thanks for testing it out @maximgrigorov
