### ISSUE TITLE
how to add/share the RDM(Raw Device Mapping) across vm by govc

### ISSUE THREAD

**Issue by raghavanv90** [vmware/govmomi#1944]
I am trying to find a way to add rdm's across vm present in two ESXi box.

So i used the commands below:

govc device.scsi.add -vm test-1 -type pvscsi -sharing=ParaVirtualSCSIController
govc device.scsi.add -vm test-2 -type pvscsi -sharing=ParaVirtualSCSIController

- datastore was created and shared between hosts vm
govc vm.rdm.attach -vm test-1 -device /vmfs/devices/disks/naa.624a937069a95a671d794e820425233c

govc vm.disk.attach -vm test-vm2 -disk test-vm1/shared.vmdk -link=false -sharing sharingNone
 and I am getting the error as "govc: Incompatible device backing specified for device '0'."

Any idea ?

**Comment by dougm** [comment]
Did the VMs already have an existing scsi controller?  Check using:
```console
% govc device.ls -vm test-1 pvscsi-*
pvscsi-1000  ParaVirtualSCSIController  VMware paravirtual SCSI
```

If so, `vm.rdm.attach` may have chosen to use the 1st one.  We should probably add a `-controller` flag so you can choose.

**Comment by raghavanv90** [comment]
Did the VMs already have an existing scsi controller? Check using:
>> Yes. Added a new scsi controller to both the vms.

// test-1 
lsilogic-1000  VirtualLsiLogicController  LSI Logic
ethernet-0     VirtualE1000               VM Network
disk-1000-0    VirtualDisk                20,971,520 KB
pvscsi-1001    ParaVirtualSCSIController  VMware paravirtual SCSI

// test-2 
lsilogic-1000  VirtualLsiLogicController  LSI Logic
ethernet-0     VirtualE1000               VM Network
disk-1000-0    VirtualDisk                20,971,520 KB
pvscsi-1001    ParaVirtualSCSIController  VMware paravirtual SCSI

// RDM attach on test-1
govc vm.rdm.attach -vm test-1 -device /vmfs/devices/disks/naa.624a937069a95a671d794e820425233c

// use existing disk (here rdm disk attached on test-1 vm. From test-2 , use existing disk and point to the rdm disk attahced on test-1 vm)
govc vm.disk.attach -vm test-2 -disk  test-1/test-1_1.vmdk -controller=pvscsi-1001
govc: Invalid configuration for device '0'.

govc vm.disk.attach -vm test-2 -disk  test-1/test-1_1.vmdk -controller=pvscsi-1001 -link=true
govc: Invalid configuration for device '0'.

govc vm.disk.attach -vm test-2 -disk  test-1/test-1_1.vmdk -controller=pvscsi-1001 -link=false
govc: Incompatible device backing specified for device '0'.

**Comment by dougm** [comment]
Maybe @bastienbc (author of vm.rdm.attach) can provide some pointers?

**Comment by bastienbc** [comment]
I'll look at it quickly but I cannot test anything.
But please refresh my memory: is test-1/test-1_1.vmdk a valid disk name in that situation?
Have you tried finding it's ID through another command?
I haven't used this in like 4 years :-)

**Comment by bastienbc** [comment]
So sorry, I have been a lot more busy than I thought during the lockdown.
Ok tell me if I'm wrong but the rdm.attach command throw no error right?

Did you refresh the available devices in the VM, and tried to mount it?
I think (correct me if I'm wrong) that the disk.attach fails because the device you provide is not a "disk", and has in fact already been attached.

So refresh the scsi volumes in the VM first. Device should appear after that in /dev.
