### ISSUE TITLE
AuthorizationManager:AuthorizationManager does not implement: HasPrivilegeOnEntities 

### ISSUE THREAD

**Issue by akulkarnivnera** [vmware/govmomi#1945]
Hey Doug,
Thanks for you timely help.
We have moved ahead now - but got stuck here - Need your help again !!

Below snippet in vRNI's code base is causing this issue - 

            ManagedEntity[] managedEntities = ArrayUtils.addAll(dataCenters, new ManagedEntity[]{si.getRootFolder()});
            AuthorizationManager authorizationManager = si.getAuthorizationManager();
            SessionManager sessionManager = si.getSessionManager();
            com.vmware.vim25.EntityPrivilege[] authPriv = authorizationManager.hasPrivilegeOnEntities(managedEntities, sessionManager.getCurrentSession().getKey(), priv);

**Comment by dougm** [comment]
@akulkarnivnera I haven't used that API before or tested this code.. it may work fine as-is or at least be enough to get you started #1946

**Comment by akulkarnivnera** [comment]
Done !!!
Am able to get govcsim added into vRNI ... Hope it learns all entities now !!!
Thanks a ton !!!!
