### ISSUE TITLE
Support for multi-environment

### ISSUE THREAD

**Issue by Bulat-Gumerov** [vmware/govmomi#1948]
Govc is great tool, thank you very much. But I need to connect to different vspheres that are located in different datacenters and cities.
Can you implement multiple environment support in govc?
For example add profile for each vsphere and then switch them using additional flag `--profile`. If no profile specified it can use default one.

**Comment by dougm** [comment]
You can do this with shell+env vars, for example with this script: https://github.com/vmware/govmomi/blob/a1cb8daa6f12c03b52f1a2bd4409ffa530f85fd0/scripts/govc-env.bash#L21-L25

**Comment by Bulat-Gumerov** [comment]
Doesn't work for me:
```
~ » source .govc                                                                                                                                                                  user@pc

~ » govc-env                                                                                                                                                                      user@pc
govc-env:4: bad substitution

~ » govc-env --save test                                                                                                                                                      1 ↵ user@pc
govc-env:11: = not found
```

**Comment by dougm** [comment]
What is your bash version?
```console
% bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
...
```

**Comment by Bulat-Gumerov** [comment]
zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by dougm** [comment]
ok, it doesn't work with zsh. But look at the code, it's just saving environment variables to a file. And source a file to switch environments.  This can be done without that script. You can also `govc env` to help generate a file with the vars.
