### ISSUE TITLE
option to choose vmfs version(VMFS 5/6)

### ISSUE THREAD

**Issue by raghavanv90** [vmware/govmomi#1950]
I am trying to create a datastore of type vmfs...It had created by default with vmfs 5 datastore (esxi version is 6.5.0). Is there a way to create a datastore with vmfs6..Any idea ?

govc datastore.create -type vmfs -name test-datastore -path /msys-dc/datastore/ -disk="naa.624a937069a95a671d794e820425233d"

**Comment by dougm** [comment]
@raghavanv90 can you try #1954 , e.g. `govc datastore.create -version 6 ...`
