### ISSUE TITLE
No output for `vm.info` if path contains spaces

### ISSUE THREAD

**Issue by lukurde** [vmware/govmomi#1953]
![obraz](https://user-images.githubusercontent.com/47138492/80244802-e3d07900-8669-11ea-95f7-29066bae092c.png)

**Comment by dougm** [comment]
The path in your screenshot has a leading `.`, in which case vm.info treats the path as relative to the vm/ folder.  So, use `/Datacenter/vm/...` instead of `./Datacenter/vm/...`

**Comment by lukurde** [comment]
I know but without the dot it doesn't work for at all.

./works/for/paths/with/no/spaces
works/for/paths/with/no/spaces

/doesnt/work/for/any/path

Also checked quoting.

Maybe git-bash terminal has something to do with it?

**Comment by dougm** [comment]
Any luck with this? I'd expect git-bash to work fine.

**Comment by dougm** [comment]
Closing as govc itself does not have an issue with spaces in the inventory path. Also just realized we have this noted: https://github.com/vmware/govmomi/blob/master/govc/README.md#msys2-windows
