### ISSUE TITLE
Changing boot order making BIOS boot menu to user mode.

### ISSUE THREAD

**Issue by shafeequeaslam** [vmware/govmomi#1955]
govc device.boot -vm $VM_NAME -delay 100 -order cdrom,disk,ethernet

![image](https://user-images.githubusercontent.com/24353385/80368754-d950f200-88aa-11ea-97e9-ec2347084b6d.png)

**Comment by dougm** [comment]
What is the issue here?

**Comment by dougm** [comment]
Closing as stale, feel free to re-open with more details.
