### ISSUE TITLE
Iterate over datastores and find datastores with specific field value

### ISSUE THREAD

**Issue by lukibahr** [vmware/govmomi#1959]
Hey guys, 

is it possible to get a list of all datastores (yes it is, I know) and iterate over the datastores and find / filter on datastores which have a specific value of a custom field? 

Thanks in advance

**Comment by dougm** [comment]
You can do it with `jq`, something like:
```console
% govc datastore.info -json '*' | jq -r '.Datastores[] | select(.CustomValue[]?.Value == "xyz") | .Name'
```
Could make it work with `find`, something like:
```console
% govc find -type s / -customValue xyz
```
But that requires a change to the code and would need more if you want to specify the Key:
```diff
modified   property/filter.go
@@ -95,6 +95,8 @@ func (f Filter) MatchProperty(prop types.DynamicProperty) bool {
 			match, _ = strconv.ParseFloat(s, 64)
 		case fmt.Stringer:
 			prop.Val = prop.Val.(fmt.Stringer).String()
+		case *types.CustomFieldStringValue:
+			prop.Val = prop.Val.(*types.CustomFieldStringValue).Value
 		default:
 			if ptype.Kind() != reflect.String {
 				return false
```
Have you looked at using tags instead of custom fields?

**Comment by lukibahr** [comment]
Thanks @dougm. Yeah but tags have predefined values - we're trying to assign individual values to custom fields, for example to assign a datastore to customerA and datastoreB to customer B and iterate afterwards over all datastores, who belong to customer B for example. 

Does it work with tags?

**Comment by dougm** [comment]
@lukibahr ok, sounds useful, can you review #1962 ?

tags don't work with `find`, as tags are not part of the managed object. But `tags.attached.ls` can be used to list objects with tags attached.
