### ISSUE TITLE
Provide the Md5 and sha256 checksum of this repo

### ISSUE THREAD

**Issue by PradeepJigalur** [vmware/govmomi#1960]
Hi, 

Am building go using bazel and bazel needs check sum please provide the same for this

https://github.com/vmware/govmomi/tree/master/vim25

**Comment by dougm** [comment]
Details please, no bazel experience here.

**Comment by PradeepJigalur** [comment]
i want to have sha256 for the repo https://github.com/vmware/govmomi/tree/master/vim25

i wanted to use like this


http_archive(
    name = "bazel_gazelle",
    url = "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.11.0/bazel-gazelle-0.11.0.tar.gz",
    sha256 = "92a3c59734dad2ef85dc731dbcb2bc23c4568cded79d4b87ebccd787eb89e8d0",
)

**Comment by dougm** [comment]
I don't understand, that example is a release tarball.  Why does bazel need a tarball and what would the expected layout be?  Can't bazel just use git directly and a release tag / commit sha?
