### ISSUE TITLE
Do removed devices (other than disks) get deleted after removal?

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#1966]
I have tested removing a virtual NIC device from a VM and have noticed that it has failed to get reattached to my VM on two occassions after removing the device, but not doing any explicit deleting of the device.

Do removed devices get deleted automatically?

**Comment by dougm** [comment]
How did you remove the NIC device?

**Comment by chardch** [comment]
I am directly calling govmomi by first creating the device config spec to remove a nic, after finding it in the VM's device list. Then reconfiguring the VM with the removal. When adding the nic back, I just change the operation to add.

Here is a sample code to describe what I mentioned.

`
removeSpec := &types.VirtualDeviceConfigSpec{
                        Device:    nic,
			Operation: types.VirtualDeviceConfigSpecOperationRemove,
                }

vmUpdateSpec.DeviceChange = append(vmUpdateSpec.DeviceChange, nicSpec)
vm.ReconfigureVM(ctx, vmUpdateSpec)
`

**Comment by chardch** [comment]
I actually found this isn't due to the device not being available, but rather the device being reported as in use.
