### ISSUE TITLE
Hostsystem SerialNumber Empty

### ISSUE THREAD

**Issue by pressplay21** [vmware/govmomi#1968]
var hss []mo.HostSystem
	err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"hardware"}, &hss)
	if err != nil {
		return err
	}

	for _, hs := range hss {
		fmt.Printf("%s\n", hs.Hardware.SystemInfo.SerialNumber)

	}

**Comment by dougm** [comment]
What version are your ESX host(s)? The field was added in 6.7: https://code.vmware.com/apis/704/vsphere/vim.host.SystemInfo.html

**Comment by pressplay21** [comment]
thank you. yes my vmware TAM was able to answer my question. I'm still on 6.5 and I was able to locate it in Hostsystem.Hardware.SystemInfo.OtherIdentifyingInfo[1].IdentifierValue

**Comment by dougm** [comment]
@pressplay21 ok great, I'll go ahead and close the issue then.
