### ISSUE TITLE
vm.migrate

### ISSUE THREAD

**Issue by tigerdice** [vmware/govmomi#1975]
can i use vm.migrate to another datacenter.  When i do that i need to switch the virutal wire.  I can do that in a powercli script with vmotion how can achieve this without detaching and reattaching the network with govc?

**Comment by tigerdice** [comment]
This is the powercli but i am not able to do it in govc without detaching the network.
Import-Module VMware.VimAutomation.Core -ErrorAction SilentlyContinue
Import-Module vmware.vimautomation.vds -ErrorAction SilentlyContinue

$vCenter = 'bics-vc.bicsdev.local'
$UserName = 'administrator@vsphere.local'
$Password = 'VMware1!'

Connect-VIServer -Server $vCenter -user $UserName -password $Password

$vmtomigrate = Get-VM Testing
$networkAdapter = Get-NetworkAdapter -VM $vmtomigrate
$destination = Get-VMHost -Location BICSDev-Cluster-01 | Select-Object -First 1
$destinationPortGroup = Get-VDPortgroup -VDSwitch DvSwitch-01 -Name DvPortGroup-01
$destinationDatastore = Get-Datastore BICSDev-Cluster-01_S_001

$vmtomigrate | Move-VM -Destination $destination -NetworkAdapter $networkAdapter -PortGroup $destinationPortGroup -Datastore $destinationDatastore | out-null
Disconnect-VIServer -Server * -Force -Confirm:$false

**Comment by tigerdice** [comment]
So the vm is on dc1 and when i move to dc2 i have to switch to a new virtual wire.
 govc device.remove -dc=${dc1} -vm ${vm} "ethernet-0"
 govc vm.migrate -dc=${dc1} -pool /${dc2}/host/$cluster/Resources ${vm}
govc vm.network.add -dc=${dc2} -vm ${vm} -net "${vmnet}"
 govc device.connect -dc=${dc2} -vm ${vm} "ethernet-0"

This will cause an small downtime that is not acceptable for the application.  I can do it with the above powercli but i would like to achieve the same with powercli.  The vm.migrate does not seem to have an option for the virtual wire... maybe i have a mistake or could vm.migrate also support migration to another datacenter?

**Comment by dougm** [comment]
govc doesn't support this currently, will need to think about how we could do so, but seems doable.

**Comment by john275** [comment]
would like this functionality
