### ISSUE TITLE
FindByIp fails for replayed data

### ISSUE THREAD

**Issue by Abhijeet94** [vmware/govmomi#1981]
Using govc, vcsim and real vcenter.

Now suppose I connect govc to a real vcenter and do a host.ip search for instance - 
`govc host.info -dc=xxxxx -host.ip=x.x.x.x`
it passes and returns a host.

But now I record the same vcenter and load it in vcsim (`object.save` and `vcsim -load`), and then I issue the same command, it fails giving error -
 

> `"https://<IP:port>/sdk": EOF`

 and there is a panic on line https://github.com/vmware/govmomi/blob/master/simulator/search_index.go#L247
(a separate testing code using FindByIp using govmomi client also fails similarly)

although `govc host.info  -dc=xxxxx `
passes (there is only one host in that DC).

Does anyone know what is going on?

**Comment by dougm** [comment]
Works for me, which govmomi git revision are you using? Do you see the IP you're looking for with the command below against vcsim?

```console
govc object.collect -json -type h / config.network.vnic | \
 jq -r .ChangeSet[].Val.HostVirtualNic[].Spec.Ip.IpAddress
```

**Comment by Abhijeet94** [comment]
Thanks for your response!

We downloaded from here - `https://github.com/vmware/govmomi/releases/download/v0.22.1/govc_linux_amd64.gz` so the version is probably `v0.22.1`.

The response to your command is something like - 
```
10.46.129.50
192.168.5.1
....
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
....
```

We get a similar response when govc is connected to real vcenter.

That said, our initial intent was to have a vcsim setup where FindByIp works for hosts added through govc. Since the `cluster.add` govc command only has hostname option (and when we specify IP as hostname, FindByIp doesn't work), we couldn't add vnic/ip information to the hosts we added. We are currently using a workaround for this objective - we record and save the vcsim vcenter as xml files, insert vnic information manually to HostSystem-host-xx.xml file, and then load these xml files into vcsim. In this scenario, FindByIp works. Is there a better way to achieve this using govc or otherwise?

**Comment by dougm** [comment]
Is this HostSystem ip somewhere other than config.network.vnic in the real vCenter? If so, maybe vcsim could also look there. If you could share one of your HostSystem.xml where vnic is empty I could also take a look.

**Comment by Abhijeet94** [comment]
I think it's not somewhere other than `config.network.vnic`. 
(In my previous message, I should have said, "... ~insert~ update vnic information manually to HostSystem...")

These are the steps we follow to get our use case working -
- vcsim -l 127.0.0.1:8989 -username user -password pass &
- govc datacenter.create my_dc
- govc cluster.create -dc=my_dc my_cluster
- govc cluster.add -dc=my_dc -hostname 10.53.27.165 -username user -password pass -noverify
- govc object.save -u user:pass@127.0.0.1:8989 -d ./my-vcenter

This generates several files like `0054-HostSystem-host-21.xml` where vnic is indeed present, but is set to 127.0.0.1. We want it to be set to 10.53.27.165 (as in command above), so that this command works - `govc host.info -dc=my_dc -host.ip=10.53.27.165`.

To get that working, we manually update the above xml file and replace the address with what we want. If we somehow had a way to specify IP when adding host through cluster.add, we wouldn't have required to save and replay vcenter data.

Thanks for your time!

**Comment by dougm** [comment]
@Abhijeet94 I see. I think we can do that, though after submitting #2017 I realized that changes every host IP.  I'll need to update it so we make a copy of the template structure, probably not till tomorrow though.

**Comment by Abhijeet94** [comment]
Thanks Doug - thanks for your quick response and action!
As we mentioned earlier, we have a workaround so we are not blocked as such :)

**Comment by dougm** [comment]
@Abhijeet94 updated the PR and merged, let me know if that works for you.
