### ISSUE TITLE
How to remove *-flat.vmdk file

### ISSUE THREAD

**Issue by huawenli** [vmware/govmomi#1995]
In our SAN storage (not local vSAN) there are quite some uuid.vmdk and vmfd file, which are not used by any VM anymore. I used datastore.rm command to delete them and after deletion command uuid.vmdk change to uuid-flat.vmdk.
 
Then another datastore.rm to remobe flat.vmdk file will return failure. However deletion from vCenter WebUI worked fine.
 
Can you let me know which command can use to delete it? Thanks.
`
vmdk file:  [G370-Datastore] fcd//18ce965db98145b798fbb035307b1dc4.vmdk
vmfd file:  [G370-Datastore] fcd//18ce965db98145b798fbb035307b1dc4-4686b60be34dc512.vmfd
 
After deletion, as showed , *.vmdk  is changed to *flat.vmdk
[root@vmdk4 ~]# govc datastore.ls -dc=Edge-SantaClara -ds=G370-Datastore fcd/18ce965db98145b798fbb035307b1dc4*
18ce965db98145b798fbb035307b1dc4-4686b60be34dc512.vmfd
18ce965db98145b798fbb035307b1dc4-flat.vmdk
 
[root@vmdk4 ~]# govc datastore.rm -f -dc=Edge-SantaClara -ds=G370-Datastore fcd/18ce965db98145b798fbb035307b1dc4-flat.vmdk
govc: Error caused by file /vmfs/volumes/5d7060ff-867ad89c-8cfa-d8c49764fe06/fcd/18ce965db98145b798fbb035307b1dc4-flat.vmdk
`

**Comment by dougm** [comment]
`fcd/` is the First Class Disk directory, I think you'll need to use the [disk.rm](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#diskrm) to properly remove those disks.
