### ISSUE TITLE
Renaming VM with govmomi common.Rename results in name with appended "-v0"

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#1999]
I have a VM with name "X", and a new vm with name "Y".
I'm deleting the old VM "X" and then renaming vm "Y" to "X". 
The VM is correctly renamed when inspected in vCenter, however, I see the hostname of the vm is "X-v0". Why there is the "-v0" suffix.

I am directly calling Rename (https://github.com/vmware/govmomi/blob/ca6409320dcdd91f065e14c8a41d09cdae96bf33/object/common.go#L113),

**Comment by dougm** [comment]
I can't reproduce that and haven't seen a "-v0" suffix before.  I have seen " ($n)" suffix when VMs are created with the same name, but not "-v0".  Can you reproduce this using govc `vm.create`, `vm.destroy` and `object.rename` ?

**Comment by chardch** [comment]
I haven't been able to reproduce using govc object.rename thus far. When I use object.rename, the hostname of the VM stays the same

**Comment by dougm** [comment]
`Rename` and `object.rename` only change the vSphere inventory name, the VM hostname is not changed by `Rename`.

**Comment by chardch** [comment]
Got it. Thanks
