### ISSUE TITLE
How to change hostname of existing VM?

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2003]
I am trying to update the hostname of an existing VM that's powered on.

I'm reconfiguring the VM with a VirtualMachineConfigSpec where the VAppConfig is set with a property spec where the key and ID("hostname") are the same as the original hostname key and ID, but the value is a different name

I'm using [ArrayUpdateSpec](https://godoc.org/github.com/vmware/govmomi/vim25/types#ArrayUpdateSpec) with ArrayUpdateOperationEdit, where the info

However, when I log into the VM, I see the hostname hasn't changed. Am I going about this correctly?

**Comment by dougm** [comment]
I'm not too familiar with VAppConfig, can provide more details?

You can use Customize() to change the hostname, but the VM needs to be powered off: https://github.com/vmware/govmomi/blob/bf72e9fb3618af1f7fc4e794b0fdd4b7454df22d/govc/vm/customize.go#L188

Another option is using GuestOperationsManager to run a command in the guest, but requires guest login credentials (e.g. `govc guest.run`).

There's also [cloud-init](https://github.com/vmware/cloud-init-vmware-guestinfo)

**Comment by chardch** [comment]
Thanks, I saw that VAppConfig changes the properties in the vApp options of the VM, such as hostname, but won't necessarily change the actual hostname when logged into the VM itself.

**Comment by chardch** [comment]
Thanks, resolved.
