### ISSUE TITLE
How to remove distributed portgroups with govc?

### ISSUE THREAD

**Issue by brlbil** [vmware/govmomi#2005]
Hi,

I could not find a way to remove distributed portgroups with govc, I search the issues and documentation maybe I am missing something. Is removing distributed portgroups implemented? If not please, add this future to govc. 
 
Regards
Birol

**Comment by dougm** [comment]
We can add this in the next release.

**Comment by brlbil** [comment]
Updating the so it would not be closed automatically

**Comment by dougm** [comment]
Sorry, when I commented on this, I was thinking of `govc dvs.remove`, as in the opposite of `dvs.add`.. those deal with host membership.  It is already possible to remove a dvpg itself, using:
```console
% govc object.destroy /dc-name/network/dvpg-name
```

Leaving this open so we add to the `dvs.portgroup.add` docs.

**Comment by dougm** [comment]
Added in #2364
