### ISSUE TITLE
govc vm.destory not work in Vsphere70

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/govmomi#2011]
govc vm.destory not work in vsphere70. I both tried the govc 0.22.1 and govc 0.23.0, neither work. I remember this cmd worked within vsphere67u3. Would you please help on it?

govc vm.power -off -force /pks-dc/vm/pks_vms/vm-9d373f90-ac9f-4d86-94b7-c219849037ba
Powering off VirtualMachine:vm-6546... OK
 govc vm.destory /pks-dc/vm/pks_vms/vm-9d373f90-ac9f-4d86-94b7-c219849037ba
Usage of govc:

**Comment by dougm** [comment]
The command works with vSphere 7, but is called `vm.destroy`, not `vm.destory`

https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmdestroy

**Comment by luwang-vmware** [comment]
Oops.  I did not realized it is typo in my command line. Sorry for it.
