### ISSUE TITLE
Vcsim load and unable to add portgroup 

### ISSUE THREAD

**Issue by gabriele-g-els** [vmware/govmomi#2016]
Hi,
when I use **load** flag to import previously saved inventory and I try to add a portgroup to the host I'll receive the following error:

```
root@4c0cb4482587:/go# govc host.portgroup.add -vlan=1520 -vswitch=vSwitch1 1-1520
govc: ServerFaultCode: HostNetworkSystem:networkSystem-183 does not implement: AddPortGroup
```
Is this an expected behavior? Can you help me on this issue?
Thanks

**Comment by dougm** [comment]
#2026 will fix that, can you review?

**Comment by gabriele-g-els** [comment]
I confirm that I'm able to add the portgroup to the host.
