### ISSUE TITLE
Read UUID of VirtualMachine object

### ISSUE THREAD

**Issue by mkuzmin** [vmware/govmomi#202]
Is there a way to access UUID value of a virtual machine object?
Now I have to persist a vm name, this is an unique property, but it can be easily changed and become outdated.

**Comment by pietern** [comment]
Yes, this is possible by using the JSON output of vm.info. This flag returns all the properties of the VM's managed object, so chances are you can find what you're looking for.

For example:
```sh
$ govc vm.info -json myvm | jq -r .VirtualMachines[].Config.Uuid
564d7d2d-d9fb-373b-0248-069ca24a68b5
```

**Comment by mkuzmin** [comment]
You talks about the command line tool, but I don't use it, I develop my own.
The question was about API govmomi library provides. Don't you think this kind of data should be accessed easier?

**Comment by dougm** [comment]
You can access this data using the mo.VirtualMachine type and the property collector, for example:

var o mo.VirtualMachine
err = c.Properties(vm.Reference(), []string{"config.uuid"}, &o)
fmt.Printf("uuid=%s\n", o.Config.Uuid)
