### ISSUE TITLE
SOCKS support please

### ISSUE THREAD

**Issue by strobelight** [vmware/govmomi#2022]
I have a machine in-between the machine with govc and the machine with vCenter. 

I have a SOCKS proxy on the machine in the middle. A curl command with the --proxy option set to socks5://middleman:9999 (socks proxy set up with ssh using port 9999) looks like it works, although not directly with the /sdk (perhaps the example troubleshooting step could be beefed up with an example) in your example, but it will download the /certs/download.zip file using GET. Apparently ours does some redirects too, so a -L option to the curl was also necessary.

**Comment by dougm** [comment]
govc supports SOCKS via Go's built-in support: `export HTTP_PROXY=socks5://middleman:9999`

**Comment by strobelight** [comment]
beautiful!  I'm unfamiliar with Go.
