### ISSUE TITLE
Missing methods to retrieve AlarmInfo

### ISSUE THREAD

**Issue by paologallinaharbur** [vmware/govmomi#2023]
I am currently trying to fetch alarmStatus, displayedName and description with the following code:

```
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	var alarmManager mo.AlarmManager
	err = config.VMWareClient.RetrieveOne(ctx, *config.VMWareClient.ServiceContent.AlarmManager, nil, &alarmManager)

	alarmSlice, err := methods.GetAlarmState(ctx, config.VMWareClient, &types.GetAlarmState{
		Entity: config.Datacenters[0].Datacenter.Self,
		This:   alarmManager.Self,
	})
```

I am able to fetch  data, but it is almost useless since I do not know how to understand what is `alarm-1` and to link it to alarms set in the dashboard:
```
Key: alarm-1.datacenter-7
AlarmValue: alarm-1
AlarmType: Alarm
OveralStatus: gray
```

In the code I noticed that there are some data structure having more info, es: `Alarm, AlarmInfo, AlarmSpec` L928 types.go 
Unfortunately these data structures are not exposed by any method, I tried to use them anyway, but I failed.

Is there a way to retrieve the name displayed in the UI and the description of alarms?
Am I trying to fetch data regarding alarms in the correct way?

**Comment by dougm** [comment]
I haven't used the AlarmManager much myself, but you can use the PropertyCollector get details on the alarm objects. For example:
```go
	for _, s := range alarmSlice.Returnval {
		var alarm mo.Alarm
		err = c.RetrieveOne(ctx, s.Alarm, nil, &alarm)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%s\n", alarm.Info.Name)
	}
```
