### ISSUE TITLE
govc: failed to create EthernetCardBackingInfo for /X/network/dvSwitch-Y/Z: System.Read privilege required for config.distributedVirtualSwitch

### ISSUE THREAD

**Issue by macau23** [vmware/govmomi#2024]
I can create a VM within vSphere, but not with govc:

```
$ govc vm.create \
-c=1 \
...
-net=dvSwitch-Y/Z \
-net.adapter=vmxnet3
..
govc: failed to create EthernetCardBackingInfo for /X/network/dvSwitch-Y/Z: System.Read privilege required for config.distributedVirtualSwitch
```

https://github.com/vmware/govmomi/blob/master/object/distributed_virtual_portgroup.go says:

```
	// From the docs at https://code.vmware.com/apis/196/vsphere/doc/vim.dvs.DistributedVirtualPortgroup.ConfigInfo.html:
	// "This property should always be set unless the user's setting does not have System.Read privilege on the object referred to by this property."
	// Note that "the object" refers to the Switch, not the PortGroup.
```

I guess I don't have this privilege, but I think the comment says that the property does not need to be set if I do not have it.

**Comment by dougm** [comment]
We do need to have that property set to create the backing.  I don't know how the GUI gets around this. More details in #1517 

And: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/710#issuecomment-572590652

**Comment by macau23** [comment]
Is there a way to supply whatever information govc needs instead of it discovering it?

**Comment by punsoong** [comment]
hi @macau23, did you ever find out the list of require permissions in vSphere?
I'm experiencing the same error you raised in hashicorp/terraform-provider-vsphere/issues/1109
I can create VMs using govc -vm.create

**Comment by macau23** [comment]
@punsoong no, but it will be something to do with querying the virtual switch.

**Comment by bnii** [comment]
@macau23, did you manage to workaround this eventually, or you just got the permission?
We are renting from a provider and unsure whether it is reasonable to ask them to grant this.
Thank you!
