### ISSUE TITLE
ability to ignore or detect when "DeleteVirtualDisk" fails due to vmdk already deleted

### ISSUE THREAD

**Issue by breunigs** [vmware/govmomi#2025]
Currently, when attempting to delete a VMDK that has been deleted already using `VirtualDiskManager.DeleteVirtualDisk`, you get an error message similar to
```
File /vmfs/volumes/<uuid>/kubevols/kubernetes-dynamic-pvc-<uuid>.vmdk was not found
```
This is fine, but there's no way to check if this kind of error has occurred except asserting on the error message itself, which is brittle. Is there a way to check the error class through `errors.Is()`, an alternative API, etc?
The background for this is that Kubernetes can issue a VMDK delete call, but never learn its response, e.g. when being interrupted at the right moment. If the call was successful, the VMDK is already gone but Kubernetes will retry the delete – and get an error message back. At this point manual intervention is required, because the delete call will never succeed.

**Comment by dougm** [comment]
You can use this helper: https://github.com/vmware/govmomi/blob/7650349cbb310500918819d5e29708ef17fca8ee/govc/datastore/rm.go#L110

Or directly:
```go
		if f, ok := err.(types.HasFault); ok {
			switch f.Fault().(type) {
			case *types.FileNotFound:
				return nil
			}
		}
```

**Comment by breunigs** [comment]
Thank you, this is exactly what I was looking for. I've submitted a PR to Kubernetes to potentially handle this scenario automatically in the future: https://github.com/kubernetes/kubernetes/pull/92372
