### ISSUE TITLE
[vRNI] QueryNetworkHint - Method not found

### ISSUE THREAD

**Issue by akulkarnivnera** [vmware/govmomi#2027]
Hi Doug,
Getting below error - I believe vRNI is calling new methods :)
Thanks in advance, Appreciate your help !!!

<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>HostNetworkSystem:networkSystem-10 does not implement: QueryNetworkHint</faultstring><detail><MethodNotFoundFault xmlns="urn:vim25" xsi:type="MethodNotFound"><receiver type="HostNetworkSystem">networkSystem-10</receiver><method>QueryNetworkHint</method></MethodNotFoundFault></detail></soapenv:Fault></soapenv:Body></soapenv:Envelope>

Let me know if you want any more information ...

Regards,
Ashutosh

**Comment by akulkarnivnera** [comment]
Hey 
Forgot to mention this is for vcsim.

Regards,
Ashutosh

**Comment by dougm** [comment]
#2032 adds the method, doesn't include any details though. Do you need anything specific from PhysicalNicHintInfo ?

**Comment by akulkarnivnera** [comment]
Hey
I am not sure what exactly it needs to return 
will revert on it.
Thanks
Ashutosh

**Comment by akulkarnivnera** [comment]
Hi
I am still getting this error on client side 
        at com.vmware.vim25.mo.HostNetworkSystem.queryNetworkHint(HostNetworkSystem.java:93)

<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>HostNetworkSystem:networkSystem-16 does not implement: QueryNetworkHint</faultstring><detail><MethodNotFoundFault xmlns="urn:vim25" xsi:type="MethodNotFound"><receiver type="HostNetworkSystem">networkSystem-16</receiver><method>QueryNetworkHint</method></MethodNotFoundFault></detail></soapenv:Fault></soapenv:Body></soapenv:Envelope>
WARN [2020-06-26 05:08:11,123] vim25.ws.WSClient:[WSClient:invoke:140] - [VCENTER_10.79.65.247_Config_OpMgr-1] - Exception caught while invoking method: QueryNetworkHint

Did we miss any entry anywhere ?

Thanks 
Ashutosh

**Comment by dougm** [comment]
If you're using `govc object.save` + `vcsim -load`, you'll need this change in your branch: #2026
