### ISSUE TITLE
Can Govc commands be run concurrently

### ISSUE THREAD

**Issue by ShivalikRanaut** [vmware/govmomi#2030]
Hi @dougm ,

I am thinking of a use case to execute govc commands concurrently.
I tried to test some scenario(s) , it appears the context.Background() is a shared resource(returns same instance var background) hence a point of contention.

I think using a new ctx.Context should solve it , Wanted to know your thoughts on same.

**Comment by dougm** [comment]
Not sure what you mean.  See https://golang.org/pkg/context/

> The same Context may be passed to functions running in different goroutines; Contexts are safe for simultaneous use by multiple goroutines.
