### ISSUE TITLE
govc: please specify a datacenter even when one is specified 

### ISSUE THREAD

**Issue by atodorov** [vmware/govmomi#2033]
I am specifying the datacenter via the `-dc` command line option but the cli still isn't happy about it.

```
# govc vm.info -u=vcenter.example.com -k true -dc=Engineering atodorov-test-vm
govc: please specify a datacenter
```

Version:
golang-github-vmware-govmomi-0.21.0-3.fc32.x86_64

**Comment by dougm** [comment]
Looks like this is caused by Go's flag parsing package: https://golang.org/pkg/flag/#hdr-Command_line_flag_syntax

> -flag x  // non-boolean flags only

Which means everything that follows `-k` in your command are treated as arguments, not parsed as flags. Try:
`-k=true` or just `-k`
