### ISSUE TITLE
Documentation URL for -g (guest IDs) results in 404

### ISSUE THREAD

**Issue by atodorov** [vmware/govmomi#2034]
I am trying to use `govc vm.create` with a guest ID I see in the vCenter web interface and that isn't accepted by the cli:

```
For a list of possible '-g' IDs, see:
http://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html
```

The URL points to a missing page.

FTR The values for `-g` I tried are:

```
-g rhel8_64Guest
-g rhel8_64Guest-vbsEnabled-false
```

where the last one is what I see in the HTML <option> tag in the UI.

**Comment by dougm** [comment]
There is a working link in the govc 0.23 release: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmcreate
