### ISSUE TITLE
cannot use (type mo.Datastore) as type *object.Datastore in argument to srm.QueryDatastorePerformanceSummary

### ISSUE THREAD

**Issue by JohnMatthewRobertson** [vmware/govmomi#2036]
I have the following code for retrieving data store information, which i am trying to use **QueryDatastorePerformanceSummary** with, but receive an error that it expects a **type \*object.Datastore**, i understand am using **type mo.Datastore** but am unclear what the following type is **type \*object.Datastore** and how i can pass the data store to **QueryDatastorePerformanceSummary** ?
  
```
c := client.Client

mgr := view.NewManager(c)

v, err := mgr.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"Datastore"}, true)

if err != nil {
	return errors.Wrap(err, "error in CreateContainerView")
}

defer func() {
	if err := v.Destroy(ctx); err != nil {
		m.Logger().Debug(errors.Wrap(err, "error trying to destroy view from vshphere"))
	}
}()

var dst []mo.Datastore

if err = v.Retrieve(ctx, []string{"Datastore"}, []string{"summary", "parent", "host", "vm", "info", "capability", "iormConfiguration"}, &dst); err != nil {
	return errors.Wrap(err, "error in Retrieve")
}

for _, ds := range dst {
	srm := object.NewStorageResourceManager(c)
	s, err := srm.QueryDatastorePerformanceSummary(ctx, ds)
	
	...
```

Trying to retrieve Data Object Storage Performance Summary, which is detail in the following link 

https://code.vmware.com/apis/42/vspherehttps://vdc-repo.vmware.com/vmwb-repository/dcr-public/98d63b35-d822-47fe-a87a-ddefd469df06/2e3c7b58-f2bd-486e-8bb1-a75eb0640bee/doc/vim.StorageResourceManager.StoragePerformanceSummary.html

This is mentioned in the following govmomi issue "Is it possible to retrieve real-time (or any) datastore metrics via govmomi"

https://github.com/vmware/govmomi/issues/702, from which i got the **QueryDatastorePerformanceSummary**.

**Comment by dougm** [comment]
You can convert the types like so:
```go
s, err := srm.QueryDatastorePerformanceSummary(ctx, object.NewDatastore(c, ds.Reference()))
```

**Comment by JohnMatthewRobertson** [comment]
Thank you for the help, that solved my issue
