### ISSUE TITLE
Option to silent govc command output

### ISSUE THREAD

**Issue by mkmrah** [vmware/govmomi#2037]
Please provide option to silent the govc command stdout / output. While executing the long running commands like `govc library.import` emits lots of log which is annoying.  Provide option like -q to suppress the output.

**Comment by dougm** [comment]
Can you redirect in the meantime? `govc library.import ... >/dev/null`

**Comment by mkmrah** [comment]
Thanks.. yes.. that's how we are managing in our shell script.
