### ISSUE TITLE
No way to get hash of a file in a datastore

### ISSUE THREAD

**Issue by jhawk28** [vmware/govmomi#2038]
There doesn't seem to be a way to get the hash of a file in the datastore. It could be useful to verify that a file was uploaded correctly.

Linked Issue: https://github.com/hashicorp/packer/issues/9494

**Comment by dougm** [comment]
The vSphere API doesn't provide that with the Datastore API.  But I think it's possible using Content Library, if that's an option?http://vmware.github.io/vsphere-automation-sdk-rest/6.5/operations/com/vmware/content/library/item/updatesession/file.add-operation.html

**Comment by dougm** [comment]
Closing since the vSphere API doesn't provide this functionality.  And the Content Library option is available in govmomi.
