### ISSUE TITLE
govc: Unable to access file [NFS-Node1] atodorov-test.vmdk since it is locked via cli but works fine via webUI

### ISSUE THREAD

**Issue by atodorov** [vmware/govmomi#2039]
So I am using the following command:

```
govc vm.create -u=$GOVMOMI_USERNAME:$GOVMOMI_PASSWORD@$GOVMOMI_URL -dc=RH_Engineering -folder=Composer -ds=NFS-Node1 -net=vMotion-Network -disk=atodorov-test.vmdk  -m=2048 -g=rhel8_64Guest -on=true -k=true -firmware=bios osbuild-composer-test-3
govc: Unable to access file [NFS-Node1] atodorov-test.vmdk since it is locked
```

trying to create a VM from an existing vmdk disk image and get the above error. If I try to create a VM from the webUI and select the same file as existing disk image the VM is created just fine and also boots to a login prompt. There are no other VMs using this file so it's unlikely the file to be locked. More likely I am missing something the the error message is doing a poor job at telling me what it is.

Any hints ?

**Comment by dougm** [comment]
How did you create `atodorov-test.vmdk`? Was it attached to another VM at some point?

Maybe some hints in this KB: https://kb.vmware.com/s/article/2107795

**Comment by atodorov** [comment]
> How did you create `atodorov-test.vmdk`? 

Created via specialized image building software

> Was it attached to another VM at some point?

No


I tried a brand new vmdk image (the image has a different name - atodorov-test-2.vmdk):
1) Uploaded it via the webUI
2) Tried the cli - same error
3) Then tried the webUI - VM is created and boots fine.

**Comment by dougm** [comment]
> Uploaded it via the webUI

This gives a clue, sounds like .vmdk was created outside of vCenter, with some desktop software?
If so, you'll need to use `govc import.vmdk`, for example this script shows to use a Vagrant box (built on the desktop) with vCenter: https://github.com/vmware/govmomi/blob/a411671fde1b6ac482ef96e0ae4f22d415cbf256/scripts/devbox/create.sh#L38-L39

Part of the import process converts the desktop vmdk format to a format that ESX can use. Maybe the webUI does that conversion during VM create, but govc does not.
