### ISSUE TITLE
[vRNI] Unable to get dvPort info in record - playback mode

### ISSUE THREAD

**Issue by akulkarnivnera** [vmware/govmomi#2042]
In case of actual VC - 
sre@Sre-Core-0:~/vcenter_simulator$ govc dvs.portgroup.info -dc=/washington-dc-delta-2 /washington-dc-delta-2/network/DSwitch-2
PortgroupKey: dvportgroup-41
DvsUuid:      50 2d b0 68 1d 5d 0a cf-92 83 e1 6e c3 e5 b9 57
VlanId:       0
PortKey:      0
PortgroupKey: dvportgroup-41
DvsUuid:      50 2d b0 68 1d 5d 0a cf-92 83 e1 6e c3 e5 b9 57
VlanId:       0
PortKey:      3

In case of vcsim where we have recorded from actual VC we are getting no output for ports info

Thanks
Ashutosh

**Comment by dougm** [comment]
`govc object.save` only saves objects and properties that can be collected via the PropertyCollector.  In this case, the info is behind a method (`FetchDVPorts`) rather than PropertyCollector: https://github.com/vmware/govmomi/blob/cfbe1d59b449be9b5378251bc6e52c65bc5e1cbd/govc/dvs/portgroup/info.go#L326

We'll need to add a mechanism to save/load data from such methods.

**Comment by akulkarnivnera** [comment]
Hey Doug,
After talking internally within the team it appears that we get this info from vc in context of dvs 

  "connectee" : {
      "@class" : "com.vnera.model.vmware.vcenter.DistributedVirtualSwitchPortConnectee",
      "connectedEntity" : {
        "@class" : "com.vnera.model.vmware.vcenter.ManagedObjectReference",
        "value" : "vm-45",
        "type" : "VirtualMachine"
      },
      "nicKey" : "4000",
      "type" : "vmVnic",
      "addressHint" : null,
      "dynamicType" : null,
      "dynamicProperty" : null
    },

"connectee" : {
      "@class" : "com.vnera.model.vmware.vcenter.DistributedVirtualSwitchPortConnectee",
      "connectedEntity" : {
        "@class" : "com.vnera.model.vmware.vcenter.ManagedObjectReference",
        "value" : "host-10",
        "type" : "HostSystem"
      },
      "nicKey" : "vmnic1",
      "type" : "pnic",
      "addressHint" : null,
      "dynamicType" : null,
      "dynamicProperty" : null
    },

I am not so sure if this is exactly what we get from vc. But this is the issue right now.
vRNI uses this information to stitch the VM-VM path. And currently this is stopping us from using VC Sim for these vm-vm path things.

Thanks in advance
Ashutosh

**Comment by dougm** [comment]
@akulkarnivnera can you try #2056 ?

**Comment by akulkarnivnera** [comment]
Hi Doug,
I havent yet received 'DistributedVirtualSwitchPortConnectee' tag anywhere in the files generated by govc object.save.

I should be now getting this tag right ?

Thanks,
Ashutosh

**Comment by dougm** [comment]
I don't know what `DistributedVirtualSwitchPortConnectee` is.  Do you see it somewhere with `govc dvs.portgroup.info -dump ...` or elsewhere against a real vCenter?  Any pointers to the SDK doc where you expect to see this?

**Comment by dougm** [comment]
@akagalkararkin added a commit to #2056 , this adds `FetchDVPorts` data to `govc object.save` and `vcsim -load`
