### ISSUE TITLE
How to list the content library items?

### ISSUE THREAD

**Issue by mkmrah** [vmware/govmomi#2043]
We import the OVA item into content library using `govc library.import ` command. Is there any way to list the items that are part of the given library ID?

`govc library.import` is not returning the library item details like library ID and other info.  I am trying to import multiple OVA images into same content library and later i want to delete the individual OVA items by their ID from the content library.

**Comment by dougm** [comment]
`library.info` https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#libraryinfo

**Comment by mkmrah** [comment]
@dougm thanks for the quick response. I am using `govc 0.22.1`

When i do govc library.info with library id i see only library details not about the library item details

```
govc library.info ova-ds-b6-7302-44

Name:               ova-ds-b6-7302-44
  ID:               323232-4b70-a50b-23232323
  Path:             /ova-ds-b6-7302-44
  Description:      
  Version:          2
  Created:          Thu Jul  2 08:06:28 2020
  StorageBackings:  
    DatastoreID:    datastore-1
    Type:           DATASTORE

```

**Comment by dougm** [comment]
`govc library.info ova-ds-b6-7302-44/` or `govc library.info ova-ds-b6-7302-44/*` will list the item details

**Comment by mkmrah** [comment]
Thanks @dougm that worked.
