### ISSUE TITLE
VMs only populate RP0, never additional pools

### ISSUE THREAD

**Issue by jnovack** [vmware/govmomi#2047]
VMs only populate RP0, never additional pools.

From the documentation:

```
  -vm int
        Number of virtual machines per resource pool (default 2)
```

This reads as if there will be `-vm` number of virtual machines *PER* resource pool for a total of `(Resource Pools) x (-vm int)` VMs.

```
❯ vcsim -dc 1 -pool 2 -cluster 2 -vm 2
```

I'm expecting to see:

* 1x DataCenter
* 2x Clusters (2x Clusters PER 1x DataCenter)
* 4x Pools (2x Pools PER 2x Clusters)
* 8x VMs (2x VMs PER (2x Pools PER 2x Clusters))

This is not the case.

I indeed have 1x DataCenter, 2x Clusters, and 4x Pools, 

```
❯ govc find . -type p
...
/DC0/host/DC0_C0/Resources/DC0_C0_RP1
/DC0/host/DC0_C0/Resources/DC0_C0_RP2
/DC0/host/DC0_C1/Resources/DC0_C1_RP1
/DC0/host/DC0_C1/Resources/DC0_C1_RP2
```

However, I only have 4x VMs, and only on `RP0`

```
❯ govc find . -type m
...
/DC0/vm/DC0_C0_RP0_VM0
/DC0/vm/DC0_C0_RP0_VM1
/DC0/vm/DC0_C1_RP0_VM0
/DC0/vm/DC0_C1_RP0_VM1
```

**Comment by jnovack** [comment]
I feel duped!

In fact, the VMs are not actually IN the resource pools. When retrieving a `"resourcePool"` of a VM, it does not appear to be one of the Resource Pools that are created.

The sentence `Number of virtual machines per resource pool (default 2)` imply that the VMs would be *IN* the resource pool it was created for.

```
ResourcePool:resgroup-31 @ /F0/DC0/host/F0/DC0_C0/Resources
ResourcePool:resgroup-49 @ /F0/DC0/host/F0/DC0_C0/Resources/DC0_C0_RP1
ResourcePool:resgroup-50 @ /F0/DC0/host/F0/DC0_C0/Resources/DC0_C0_RP2
ResourcePool:resgroup-52 @ /F0/DC0/host/F0/DC0_C1/Resources
ResourcePool:resgroup-70 @ /F0/DC0/host/F0/DC0_C1/Resources/DC0_C1_RP1
ResourcePool:resgroup-71 @ /F0/DC0/host/F0/DC0_C1/Resources/DC0_C1_RP2
```
```
DC0_C0_RP0_VM0 ResourcePool:resgroup-31
DC0_C0_RP0_VM1 ResourcePool:resgroup-31
DC0_C1_RP0_VM0 ResourcePool:resgroup-52
DC0_C1_RP0_VM1 ResourcePool:resgroup-52
```

**Comment by dougm** [comment]
Looks like we either need to fix the help text or change the code to do what the help text says.. at the moment, child pools are indeed created without any VMs: https://github.com/vmware/govmomi/blob/443e10768ccfb7bc03f85e4eab8cc619cfef784c/simulator/model.go#L667-L676

**Comment by jnovack** [comment]
I think the documentation is correct, just the code needs to be corrected. ;)

Along these same lines, the VMs are named `DC0_C0_RP0_VM0`, but there is no `RP0`.  For consistency sake, should the VM be created with as `DC0_C0_VM0`?

Just like stand-alone hosts are not created with a cluster (`C0`), I believe non-pooled VMs should not contain an invalid pool in their name.

**Comment by embano1** [comment]
Did a quick prototype and just to make sure I understand the desired behavior correctly, here are some test results with a patched `vcsim`:

## Defaults: `./vcsim`

### Resource Pool Layout

```json
govc ls -json '/DC0/host/*/Resources' | jq '.elements[].Object|.Name,.Self,.ResourcePool
"Resources"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
null
"Resources"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
null
```

### VM Distribution

```json
govc ls -json /DC0/vm | jq '.elements[].Object|.Name,.ResourcePool'
"DC0_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_C0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
"DC0_C0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
```

## Custom: `./vcsim -dc 1 -pool 2 -cluster 2 -vm 2`

### Resource Pool Layout

```json
govc ls -json '/DC0/host/*/Resources' | jq '.elements[].Object|.Name,.Self,.ResourcePool'
"Resources"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
null
"Resources"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
[
  {
    "Type": "ResourcePool",
    "Value": "resgroup-52"
  },
  {
    "Type": "ResourcePool",
    "Value": "resgroup-53"
  }
]
"Resources"
{
  "Type": "ResourcePool",
  "Value": "resgroup-55"
}
[
  {
    "Type": "ResourcePool",
    "Value": "resgroup-81"
  },
  {
    "Type": "ResourcePool",
    "Value": "resgroup-82"
  }
]
```

### VM Distribution

```json
govc ls -json /DC0/vm | jq '.elements[].Object|.Name,.ResourcePool'
"DC0_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_C0_RP1_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-52"
}
"DC0_C0_RP1_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-52"
}
"DC0_C0_RP2_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-53"
}
"DC0_C0_RP2_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-53"
}
"DC0_C1_RP1_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-81"
}
"DC0_C1_RP1_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-81"
}
"DC0_C1_RP2_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-82"
}
"DC0_C1_RP2_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-82"
}
```

**Comment by embano1** [comment]
@jnovack if you have a handy CLI one-liner to easily print VM to host/cluster/RP mappings that makes it easier for you to review, please share :)

**Comment by embano1** [comment]
@jnovack could you please take a look on the patched behavior above and let me know if this aligns with your expectations from the docs? If so I can file a PR.

**Comment by jnovack** [comment]
Yes, with one exception.  The numbering.

`DC`, `C`, and `VM` are all 0-based (the true basline) but `RP` seems to be 1-based (the false god).

I would expect `RP`s to be numbered `RP0` and `RP1`.

**Comment by embano1** [comment]
True observation, thx for the feedback. Let me see how much this would break in tests and whether we need to keep that oddity for now or if I can align it with the baseline numbering starting at `0`.

**Comment by embano1** [comment]
Example outputs:

## `vcsim` (defaults)
```json
"DC0_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_C0_RP0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
"DC0_C0_RP0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
```

## `vcsim -dc 1 -pool 1 -cluster 1 -vm 2`

```json
"DC0_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_C0_RP1_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-52"
}
"DC0_C0_RP1_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-52"
}
```

## `vcsim -dc 2 -cluster 1 -vm 2`

```json
"DC0_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_C0_RP0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
"DC0_C0_RP0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-26"
}
"DC1_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-72"
}
"DC1_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-72"
}
"DC1_C0_RP0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-76"
}
"DC1_C0_RP0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-76"
}
```

## `vcsim -dc 1 -pool 2 -cluster 2 -vm 2`

```json
"DC0_H0_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_H0_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-22"
}
"DC0_C0_RP1_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-52"
}
"DC0_C0_RP1_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-52"
}
"DC0_C0_RP2_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-53"
}
"DC0_C0_RP2_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-53"
}
"DC0_C1_RP1_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-81"
}
"DC0_C1_RP1_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-81"
}
"DC0_C1_RP2_VM0"
{
  "Type": "ResourcePool",
  "Value": "resgroup-82"
}
"DC0_C1_RP2_VM1"
{
  "Type": "ResourcePool",
  "Value": "resgroup-82"
}
```

**Comment by dougm** [comment]
> Yes, with one exception. The numbering.
> 
> `DC`, `C`, and `VM` are all 0-based (the true basline) but `RP` seems to be 1-based (the false god).
> 
> I would expect `RP`s to be numbered `RP0` and `RP1`. I believe this is an outstanding issue and not related.

iirc, this was intentional as each cluster has a root ResourcePool named `Resources` and we considered that `RP0`. In real vCenter `Resources` cannot be renamed or deleted.

**Comment by embano1** [comment]
I honored this in the vm naming and included the correct RP prefix and number depending on whether child pools are created or not.
