### ISSUE TITLE
vim25: Fault errors do not support go 1.13 unwrapping

### ISSUE THREAD

**Issue by jmpfar** [vmware/govmomi#2048]
Hey,
In [vim25/soap/error.go](https://github.com/vmware/govmomi/blob/cfbe1d59b449be9b5378251bc6e52c65bc5e1cbd/vim25/soap/error.go) the Is* and To* functions do not support go 1.13 error unwrapping, which makes it difficult to handle wrapped errors. Especially because these are errors that are not exported by the package.

e.g. https://github.com/vmware/govmomi/blob/cfbe1d59b449be9b5378251bc6e52c65bc5e1cbd/vim25/soap/error.go#L104-L106

When a user wraps one of these errors with their own error (e.g. `fmt.Errorf("%w", err)`), they cannot use `IsSoapFault` or `ToSoapFault` to check for the error cause, without writing custom error unwrapping code.

Using `errors.As` instead of a direct cast might allow the library user to wrap the error and then use these utility functions

**Comment by dougm** [comment]
Haven't looked at using the stdlib `errors` package yet myself, but would be ok with me to export `soapFaultError`. Either as `soap.Error` or `soap.FaultError`, any preference?
As for using `errors.As` within `ToSoapFault`, I suppose that's ok too at this point, as most folks are on Go 1.13+ at this point.
Do you want to submit a PR for this? Otherwise, I can take a closer look in a few days.

**Comment by jmpfar** [comment]
Hey,
I started writing a commit for `IsSoapFault` and it got me thinking whether that's the behavior you want. This means that any wrapped `soapFaultError` will return true on `IsSoapFault`, and `ToSoapFault` will unwrap all errors until reaching a `soapFaultError` and then it will extract the fault from that error.
I'm trying to think if that is expected behavior for the user and from the library. Maybe someone expects that it will only return true if it's actually a `soapFaultError`, not containing a `soapFaultError`. What do you think?

Maybe exporting the errors is enough for the user to make their own distinction, e.g. unwrapping using `errors.As` and then using `ToSoapFault`

**Comment by dougm** [comment]
That sounds good to me, keeping the current `IsSoapFault` behavior as-is makes sense.

Looks like there are a few other cobwebs we could cleanup:

- `soap.Wrap` isn't used anywhere, could just remove it

- And `soap.WrapRegularError` along with it

- Maybe `type regularError` can be removed too

These changes could be done separately, but wanted to make a note at least.
