### ISSUE TITLE
object: FindSnapshot and RemoveSnapshot return untyped errors

### ISSUE THREAD

**Issue by jmpfar** [vmware/govmomi#2049]
When using `VirtualMachine.FindSnapshot` and consequently `VirtualMachine.RemoveSnapshot` the returned errors are untyped. 
This happens when the vm doesn't contain any snapshots, no snapshot is found or multiple snapshots are found. This leaves the user in a situation where they need to compare error message strings in order to differentiate between the situations.

See here: https://github.com/vmware/govmomi/blob/cfbe1d59b449be9b5378251bc6e52c65bc5e1cbd/object/virtual_machine.go#L594-L608

Objects similar to `find.NotFoundError` and `find.MultipleFoundError` could improve usage considerably.

**Comment by dougm** [comment]
I'd suggest we reuse the existing `find` error types, but that's not possible as it'd create an import cycle. We could add new error types, but would they be useful outside of this method?  Other option would be to add some exported error vars, such as:
```go
var (
    ErrSnapshotNotFound = errors.New("vm snapshot not found")
    ErrSnapshotMultipleFound = errors.New("name resolves to multiple snapshots")
)
```

What do you think?

**Comment by jmpfar** [comment]
I think that's a good solution

About reusing the `find` error types, there's one thing you can do which is a bit more complex:
I think you can move the find errors to a common package, let's say `errors`, and use type aliasing to redirect the deprecated finder errors to the new errors e.g.

```go
// Deprecated: Use errors.NotFoundError instead
type NotFoundError = errors.NotFoundError
```

If I'm not mistaken this should keep the API backwards compatibility, while still allowing you to share the same errors

**Comment by dougm** [comment]
Ah yes, we could do that.  The hard part is choosing a package name, probably don't want to collide with Go's `errors` package.
Maybe a `fault` package or just moving to a `vim25/errors.go` would be good enough.
