### ISSUE TITLE
Migrate a powered-on vm to a resource pool without mentioning host

### ISSUE THREAD

**Issue by akankshadokania** [vmware/govmomi#2050]
I am trying to migrate a powered-on VM using govmomi where I specify the destination resource Pool(root resource pool of a cluster with DRS enabled) and destination datastore. I am not specifying any host. I get an error stating "A specified parameter was not correct: spec.pool". Surprisingly, it works fine when the VM is powered off or the resource pool is in the same host where the VM currently resides. I want to know if it is mandatory to specify host in relocate spec if we want to migrate a powered-on VM to another compute resource. why specifying just resource pool doesn't work as the description of relocate spec in vmware says: 
The target host for the virtual machine. If not specified,
if resource pool is not specified, current host is used.
if resource pool is specified, and the target pool represents a stand-alone host, the host is used.
if resource pool is specified, and the target pool represents a DRS-enabled cluster, a host selected by DRS is used.
if resource pool is specified and the target pool represents a cluster without DRS enabled, an InvalidArgument exception be thrown.
if the virtual machine is relocated to a different vCenter service, both the destination host has to be specified and cannot be unset.

**Comment by dougm** [comment]
I'm not sure, but if the VM is powered on, I assume live migration would require that all hosts in the target resource pool have access to the current datastore and target datastore. Is that the case here?

**Comment by akankshadokania** [comment]
Thanks, Doug. It works when I try to migrate a powered-on VM to a resource pool where all the hosts in that resource pool have access to the current datastore and the current datastore is the same as the target datastore. But, when I try to migrate it to a resource pool with a different target datastore(the target datastore is accessible by all hosts in the target resource pool and current host), the migration fails and throws the same error(spec.pool is not correct). The same operation works from vCenter. 
I have another query about the recommendations provided by vCenter when the VM after the migration is powered on and DRS is set to manual mode. Can I put a restriction that the VM should continue to be in the target host when I power on a VM using govc. As of now, when I execute a power-on command the first recommendation is considered by default.
