### ISSUE TITLE
Add govc cns.* commands to manage CNS volumes

### ISSUE THREAD

**Issue by bburky** [vmware/govmomi#2051]
While working with CAPV I ran into this issue: https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/251. If you delete your cluster before deleting your volumes you get a ton of orphaned CNS volumes.

There is no way to delete these volumes from the vCenter console. @chethanv28 suggested using VSAN Managed Object Browser (MOB) to delete the volumes: https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/251#issuecomment-654395041. But didn't want to enable a debugging tool on my cluster, and I would have had to delete each volume manually.

Please consider adding all the [CNS client methods](https://github.com/vmware/govmomi/blob/master/cns/client.go) as `govc cns.*` command line tools. It would be nice to script together simple things like `govc cns.ls | govc cns.rm` to delete batches of volumes at once. It might be nice to query by metadata from the command line too.

I ended up writing a simple go program using govmomi to do delete all CNS volumes:
https://gist.github.com/bburky/7047be4866881aa22030ba4a74b89538

**Comment by dougm** [comment]
Thanks @bburky , can see how this'd be useful, I think we should consider it.

**Comment by SandeepPissay** [comment]
@dougm This keeps coming up more often. When do you think CNS support will be added to govc?

**Comment by dougm** [comment]
We could start with ls + rm at least, I could also use this as part of some upcoming work.

Would folks prefer a `cns.*` prefix for these commands or `volume.*` ?

cc @vmwiz @dxlsunshine @dimatha
