### ISSUE TITLE
"govc" outputs help text to STDERR - this breaks CLI tooling/use case

### ISSUE THREAD

**Issue by sygibson** [vmware/govmomi#2058]
Version: v0.22.0

Today, the "govc" tool will output help information if no command option is specified.  This is very useful to help understand how the tool works.

However, this output is sent to `STDERR`, which makes it extremely unfriendly to work with in shell pipelines.  Some examples that should work ... **_but don't_**:

```govc | grep tags
govc | more
govc > /tmp/help-output.txt
```

(yes, `govc 2> /tmp/help-output.txt` works - but an operator shouldn't have to resort to this).

I would like to propose at a minimum that help output be redirected to `STDOUT` and not `STDERR` sor standard shell constructs work without extra contortions.

Additionally, it would be useful to have a further help output that shows the argument switches available, and  not just the top-level command options.

This would include things like the `-options`, `--debug`, or any other relevant flags available to an operator.

**Comment by dougm** [comment]
Using the `-h` flag will output to stdout instead of stderr, for example:

`govc -h | more`

`govc -h vm.info | more``

**Comment by dougm** [comment]
The `govc -h` flag is also used to generate this doc: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md
