### ISSUE TITLE
IPv6 govc: connect: cannot assign requested address

### ISSUE THREAD

**Issue by wdec** [vmware/govmomi#2059]
govc 0.22.1
vCentre Version 6.5.0.23000 Build 11347054

When running govc import.ova against a vcentre host (https://robot-vcentre2, accessed via IPv4 from an ipv4 only client) whose ESXi host (robot-126-6) is IPv6 enabled I'm seeing the following error:

govc: Post https://robot-126-6.xxx.com/nfc/5246b6ba-638e-9645-8a9a-5daf690f5d2c/disk-0.vmdk: dial tcp [2001:xxx:28f:2008:145::f]:443: connect: cannot assign requested address

The API call does actully manage to create an empty folder, but clearly the data upload fails.

Uploading the OVA through the vsphere GUI works ok.

Any suggestions on govc workarounds would be welcome.

**Comment by dougm** [comment]
The ESX URL is returned by the vCenter API, not sure we can do anything to change that. Is the ESX host also IPv4 enabled or v6 only?  One option is to use Content Library instead:

[library.create](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarycreate)

[library.import](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#libraryimport)

[library.deploy](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarydeploy)

**Comment by wdec** [comment]
> The ESX URL is returned by the vCenter API, not sure we can do anything to change that. Is the ESX host also IPv4 enabled or v6 only? One option is to use Content Library instead:
> 
> [library.create](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarycreate)
> 
> [library.import](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#libraryimport)
> 
> [library.deploy](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarydeploy)

Indeed the library.create and .import did work and I see it uploaded the data ok. Why couldn't the govc import use the same mechanism for uploading an image?
Unfortunately as things are the names and format of the library is a dynamically generated UUID and not a template. We're using the govc to upload a VM template and then launch a terraform configuration on it and other pieces. 
Any ideas how could one refer to library in the a create-from-template scheme?

**Comment by dougm** [comment]
Different APIs, different workflows. The import.ova command (API) also works against standalone ESX, but content library APIs do not. You'll see the vCenter UI also offers both options.

`govc import.ova` creates a VM, which can be marked as a template (using `-options`). Likewise for `library.deploy`.
After `library.deploy` you can refer to the vm template the same way had it been deployed using `import.ova`.

Libraries and Items have UUIDs, but can also be referred to by name in govc commands, but I don't know about Terraform.
