### ISSUE TITLE
Help understanding UnitNumber assignment for VirtualDevices

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [vmware/govmomi#2060]
I am trying to add SR-IOV network-adapter support to the terraform vSphere provider and have hit an issue with the UnitNumber the Virtual Device

The VirtualDevice type has unitNumber (see [the API docs](https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.device.VirtualDevice.html). VirtualDevice is extended by VirtualEthernetCard, which can be extended by either a VirtualVmxnet (which can be extended by [VirtualVmxnet3](https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.device.VirtualVmxnet3.html)) or a [VirtualSriovEthernetCard](https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.device.VirtualSriovEthernetCard.html)

Usually UnitNumber is not specified at create-time and known after apply, but because terraform seeks to keep a history of NICs, we seek to specify the UnitNumber at runtime (see @vancluever's [issue explaining this]( https://github.com/vmware/govmomi/issues/907))

Because of the logic in the the terraform vSphere provider's `AssignEthernetCard` function in [virtual_machine_network_interface_subresource](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go#L931) we are creating NICs with UnitNumbers 7,8,9...

I am creating a VM with four network adapters, the first three are vmxnet3 vNICs,, and the fourth is an SR-IOV NIC, terraform therefore gets a UnitNumber of 10. The VM gets setup by during the Post-Create Read we fail to find the SR-IOV NIC with VirtualDevice UnitNubmer 10.

Using pyvmomi I have inspected the VM created with terraform and found the three vmxnet3 network-adapters with virtualDevices having Unit Numbers 7,8,9 as expected however the SR-IOV Device had a VirtualDevice with unitNumber 45. I have no idea how this got assigned. Adding additional SR-IOV NICs, they get assigned unitNumbers of 44, then 43. 

It feels uttterly random to encode 45, 44 ,43 as the unitNumbers for SR-IOV ports. Is the unitNumber allocation documented anywhere? 

Unclear if this is the right repo to post this in, but this doesn't feel like a terraform issue, or a govmomi issue. 

Any help greatly appreciated.

**Comment by bill-rich** [comment]
@andrew-lee-metaswitch I didn't look much into how the unitNumber is assigned on the vSphere side, but I believe the reason we're not picking up the SR-IOV device on the Terraform side is because we purposefully ignore interfaces that we don't know how to manage. @dougm may have more input here, but I believe support for SR-IOV devices can be added from the Terraform side with things as they are.
