### ISSUE TITLE
EthernetCardBackingInfo() in object/network.go creates the VirtualDeviceBackingInfo without assigning the network.

### ISSUE THREAD

**Issue by seema-emc** [vmware/govmomi#2061]
EthernetCardBackingInfo() in object/network.go creates the VirtualDeviceBackingInfo without assigning the network to it. It just sets the DeviceName.  It should also assign the network object itself something like this?

	network := n.Reference()
	backing.Network = &network

**Comment by dougm** [comment]
From https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.device.VirtualEthernetCard.NetworkBackingInfo.html

> This is not used during configuration.

Also note that there are multiple implementations of EthernetCardBackingInfo.  DistributedVirtualPortgroup and OpaqueNetwork, both use backing that doesn't include the name.
