### ISSUE TITLE
[Question] How can we set the disk provisioning type during VM cloning?

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2070]
How can we set the vm's disk provisioning type to be different from the template it's being cloned from? I see there's VAppCloneSpecProvisioningType, but not sure where this should be used in the virtualmachine clone spec.

The behavior I'd like to achieve is the same as that of going to a vm template in vCenter -> create VM from template -> at the "Select Storage" section clicking "configure per disk" and setting the disk provisioning type for each disk (which defaulted to "Same format as source")

For information, I'm trying to do this with the govmomi api, not through govc.

**Comment by dougm** [comment]
I think you can do this in `VirtualMachineCloneSpec.Location.DeviceChange`
For example, in govc `vm.clone`, see how the network backing is changed via `VirtualDeviceConfigSpecOperationEdit` and added to the DeviceChange list: https://github.com/vmware/govmomi/blob/6bae3aca4aa86025133660208b643785515e3e40/govc/vm/clone.go#L303-L317

But in this case, you'd want to change the Backing.DiskMode of each `VirtualDisk`, similar to how `vm.disk.change` does: https://github.com/vmware/govmomi/blob/6bae3aca4aa86025133660208b643785515e3e40/govc/vm/disk/change.go#L149-L154

**Comment by chardch** [comment]
Thanks for the information Doug.

So to clarify, this should be done using `VirtualMachineCloneSpec.Location.DeviceChange`? I was trying to do this using `VirtualMachineCloneSpec.Config.DeviceChange` with the disk added with `Backing.(*types.VirtualDiskFlatVer2BackingInfo).ThinProvisioned: types.NewBool(false)` and tried using `VirtualDeviceConfigSpecOperationAdd` and `VirtualDeviceConfigSpecOperationAdd` operations, but neither worked.

**Comment by chardch** [comment]
I tried this and it also did not work

**Comment by dougm** [comment]
Still haven't tried the above myself, but looking around, maybe this is how-to: https://kb.vmware.com/s/article/1026146
