### ISSUE TITLE
VSAN disk claiming fails to add all but last Capacity disk

### ISSUE THREAD

**Issue by sygibson** [vmware/govmomi#2071]
SUMMARY:  **Multiple "`-d device -d device -d device`" flags are ignored, only 1 Capacity disk is built by govc**

Hi All - I've been working fairly extensively with `govc` over the last few weeks to automate vCenter deployment and VSAN stroage cluster creation.  I'm having a heck of a time with VSAN.  When I run the appropriate commands from the ESXi host itself to `claim` disks - I can properly tag and claim and define Cache/Capacity disks.  Here's an example on the ESXi host:

```
esxcli vsan storage tag add -d naa.55cd2e4152138838 -t capacityFlash
esxcli vsan storage tag add -d naa.55cd2e4151c605c5 -t capacityFlash
esxcli vsan storage tag add -d naa.55cd2e414e326509 -t capacityFlash
esxcli vsan storage add -s naa.55cd2e414e3264b0 -d naa.55cd2e4152138838 -d naa.55cd2e4151c605c5 -d naa.55cd2e414e326509
```

Checking the cluster membership - it shows this working.
```
# esxcli vsan storage list | egrep "^naa|Group UUID"
naa.55cd2e414e3264b0
   VSAN Disk Group UUID: 521d74b2-c4fb-37b0-1171-ea0099e9cbf8
naa.55cd2e4152138838
   VSAN Disk Group UUID: 521d74b2-c4fb-37b0-1171-ea0099e9cbf8
naa.55cd2e414e326509
   VSAN Disk Group UUID: 521d74b2-c4fb-37b0-1171-ea0099e9cbf8
naa.55cd2e4151c605c5
   VSAN Disk Group UUID: 521d74b2-c4fb-37b0-1171-ea0099e9cbf8
```

Now I remove the disks from VSAN, and clear the capacityFlash tag.

Running the EXACT equivalent `govc` commands, from a remote system:
```
govc host.esxcli vsan storage tag add -d naa.55cd2e4152138838 -t capacityFlash
govc host.esxcli vsan storage tag add -d naa.55cd2e4151c605c5 -t capacityFlash
govc host.esxcli vsan storage tag add -d naa.55cd2e414e326509 -t capacityFlash
govc host.esxcli vsan storage add -s naa.55cd2e414e3264b0 -d naa.55cd2e4152138838 -d naa.55cd2e4151c605c5 -d naa.55cd2e414e326509
```

Nets **_only 2 of the disks added_** to the VSAN cluster - the Cache, and very last Capacity disk:

```
# govc host.esxcli vsan storage list | egrep "^Device|^VSANDiskGroupUUID"
Device:                        naa.55cd2e414e326509
VSANDiskGroupUUID:             523346d8-7e21-35d8-5d3b-e463b167d8ff
Device:                        naa.55cd2e414e3264b0
VSANDiskGroupUUID:             523346d8-7e21-35d8-5d3b-e463b167d8ff
```

If I switch the ordering up - it appears that the Cache disk (`-s naa...`) and the very last Capacity disk (`-d naa...`) are the only two disks that govc is operating on.

**_The first and second listed Capacity disks are not properly operated on and being added to the VSAN cluster._**

It would (on the surface) appear that the command line flag parsing is not correctly picking up all 3 of the Capacity disks that I am specifying.  Is there something different in how I'm supposed to pass the multiple `-d device -d device -d device` flags for GoVC to correctly handle them ?? 

NOTE - the `esxcli vsan storage add ...` command appears to only be capable of being run once - as it MUST include a Cache and Capacity disks - so you can not (as far as I have figured out) add new disks to an existing VSAN cluster via that command path ... 

Added the `debug` directory from the `govc host.esxcli vsan storage add ....` command - in case the request/response/headers are helpful?

[govc-vsan-capacity-claim-failure-debug.zip](https://github.com/vmware/govmomi/files/5011583/govc-vsan-capacity-claim-failure-debug.zip)

**Comment by dougm** [comment]
The `host.esxcli` command was using a single string var for each flag value. #2072 supports multiple values, can you give it a try?

**Comment by sygibson** [comment]
Doug - thanks for the quick turn around.  I've built the govc binary and will test now.

**Comment by sygibson** [comment]
(sorry - didn't mean to comment on the PR - copy my comments here to track in the issue)

@dougm - got a chance to run through a test with the updated version. Unfortunately, no dice. Here's what govc returns at the command line:

```
CMD TO RUN: 'govc host.esxcli -debug vsan storage add -s naa.55cd2e414e3264cb -d naa.55cd2e415213a6b5 -d naa.55cd2e414e32652f -d naa.55cd2e4152138b5e'
govc: ServerFaultCode: A specified parameter was not correct: method
```

I also turned on `-debug` and captured the results. They're attached as govc.zip - and unzip to a Date/Directory name path in CWD. (Why can't github support tar file types for attachment ... sigh ... )

[govc.zip](https://github.com/vmware/govmomi/files/5017225/govc.zip)

**Comment by dougm** [comment]
@sygibson thanks for trying it out. I just force pushed another change that should work properly for this case, can you try again?

**Comment by sygibson** [comment]
@dougm - thank you - much appreciated that you're working on this - truly !   Unfortunately, I can't get a clean build of the `govc` binary.  I did a clean check out of `dougm/govmomi`, _git checkout_ the `issues-2071` branch, and ran make ... which results in fails in `tests`:

```
...snip...
?   	github.com/vmware/govmomi/vslm/methods	[no test files]
?   	github.com/vmware/govmomi/vslm/types	[no test files]
FAIL
make: *** [go-test] Error 1
```

I'm not very familiar with the project code/build layout ... though do have some (very minor) experience with building Golang projects and managing them (digitalrebar/provision)...  My apologies on the extra overhead on this - but if you have any pointers on how to get a Linux amd65 govc binary built out of this ... I'm all ears...

**Comment by dougm** [comment]
Hey @sygibson , no worries, you can follow this: https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md#getting-started

The steps with `$USER`, change `$USER` to `dougm`, then:
```console
% git checkout dougm/issue-2071
```
And use the `install` command in the doc above.

**Comment by dougm** [comment]
@sygibson I went ahead and merged the PR, you can try it out now using `go get ...`: https://github.com/vmware/govmomi/tree/master/govc#source

Free free to re-open if still an issue.

**Comment by sygibson** [comment]
@dougm  - apologies on the delays - we only recently got a chance to fully test this out - I can confirm that with 4x disk ESXi hosts, the disk claiming process now works fine to claim all disks with this patched version.

The primary delay was ... oddly ... due to the fact that I'm using an Alpine Linux container in my automation framework.  The complied `govc` binary would not run on Alpine Linux - previous versions that I've compiled have.   I switched my container to a Debian 10 Buster base - and it works fine there.

**Comment by dougm** [comment]
@sygibson ok glad it works for you. How did you compile govc btw?  If you include `GCO_ENABLED=0`, then govc is a static binary that'll run on any Linux distro, otherwise it depends on glibc version.
Both `make install` and `(cd govc && make govc)` set `CGO_ENABLED=0`: https://github.com/vmware/govmomi/blob/21708bc0a4d244eeabb1f54347087d3306700826/program.mk#L33

**Comment by sygibson** [comment]
@dougm - thx for the quick reply - that's likely the source of the problem.  The only way I could get that branch to build was with the following:

```
export CGO_ENABLED=0       # now using this, wasn't previously
export GOPATH=$HOME/go
go get github.com/vmware/govmomi
cd $GOPATH/src/github.com/vmware/govmomi
git config push.default nothing
git remote rename origin vmware
git fetch vmware pull/2072/head:sygibson
git checkout sygibson
GOOS=linux go install -v github.com/vmware/govmomi/govc
```
