### ISSUE TITLE
govc: how can I clone a VM with customized vApp properties

### ISSUE THREAD

**Issue by piyushkv1** [vmware/govmomi#2073]
I want to clone a VM to different storage/network along with customized vApp properties comes while cloning. How can I do this using govc command?

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmclone

But there aren't options for vApp properties.  Can you provide an example and/or which API fields you'd want to set?

https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.CloneSpec.html

**Comment by piyushkv1** [comment]
![image](https://user-images.githubusercontent.com/9156164/89401885-a0d77480-d733-11ea-8713-75a356f420ed.png)
I'm not sure about which vApp properties, but I'm getting it from UI. Could you please find respective vApp property? I'm attaching image where I'm cloning rhcos VM.

**Comment by mooperd** [comment]
I am also trying to work out how I do a vm.clone from a template and then change the vApp properties. This is how I expect to be able to set the hostname and inject an ssh key for example.

**Comment by wupeng606** [comment]
Is there answer for this question?
During Openshift/OKD deployment, it is required to deploy RHCOS/FCOS VM as bootstrap/master/worker node.

/remove-lifecycle stale

**Comment by matteoipri** [comment]
Hi there, I want to add my +1 on this issue or documentation request. I found that [vm.instantclone](https://github.com/vmware/govmomi/blob/main/govc/USAGE.md#vminstantclone) has an option (-e) for ExtraConfig, but I do not find documentation on the list of keys and their valid values. Thanks
