### ISSUE TITLE
Command for VM's and it's datastore

### ISSUE THREAD

**Issue by san4ever** [vmware/govmomi#2074]
Hi 
I have a set of VM's which moved to New Datastore
Was wondering if there any govc command to check VM's and it's associated datastore 
Instead of going and checking from vcenter 

Thanks 
Sandeep

**Comment by san4ever** [comment]
Hi @dougm , Can you help on this pls

**Comment by dougm** [comment]
`vm.info -r` ?
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vminfo

**Comment by san4ever** [comment]
It helped Thank you
Can you help me to find tags associated with VM

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#tagsattachedls
