### ISSUE TITLE
Acquire webmks ticket

### ISSUE THREAD

**Issue by lukasluecke** [vmware/govmomi#2083]
It would be great to add this as an option to the govc `vm.console` command.

**Comment by dougm** [comment]
Any doc pointers on how that works?

**Comment by lukasluecke** [comment]
Well the official docs are severely lacking on this topic, but here's what we're using at the moment (using the SOAP API):

- Send `AcquireTicket` request (https://code.vmware.com/apis/196/vsphere/doc/vim.VirtualMachine.html#acquireTicket) with `ticketType` (https://code.vmware.com/apis/196/vsphere/doc/vim.VirtualMachine.html#/doc/vim.VirtualMachine.TicketType.html) set to `webmks`
- Build WebSocket URL with return value
```php
sprintf(
    'wss://%s:%s/ticket/%s',
    $ticketResponse->getHost(),
    $ticketResponse->getPort(),
    $ticketResponse->getTicket(),
)
```
- Use this together with the not at all documented wmks JS library (loaded from `https://vcenter/vsphere-client/js/wmks.min.js`) / https://code.vmware.com/web/sdk/2.1.0/html-console
```js
const url = 'wss://...';
const wmks = WMKS.createWMKS('container', {});
wmks.connect(url);
```

**Comment by dougm** [comment]
govc could certainly output the ticket URL, is that all you need? I don't have any experience with the JS library.

**Comment by lukasluecke** [comment]
Yes, returning the final URL (preferred), or the individual parts required to construct it, would be all that's needed 👍
