### ISSUE TITLE
undefined: sync.Map when cloning repo

### ISSUE THREAD

**Issue by piyushkv1** [vmware/govmomi#2090]
$ go get github.com/vmware/govmomi
\#github.com/vmware/govmomi/vim25/xml
govmomi/src/github.com/vmware/govmomi/vim25/xml/typeinfo.go:48: undefined: sync.Map

I'm hitting issue of undefined sync.Map while cloning.

**Comment by dougm** [comment]
Closing assuming go version is the issue here.
