### ISSUE TITLE
vcsim Packer support

### ISSUE THREAD

**Issue by sylviamoss** [vmware/govmomi#2093]
Hello govmomi team!

I'm a maintainer of Packer and I'm really interested in using `vcsim` to build some acceptance tests to our vsphere builders.
I tried running a build against the default mock but some methods are not available, like PutUsbScanCodes, and I need some help to better understand how to fit vcsim to our flow. 

Our flow for a simple build is: 
1. Upload file 
2. Delete any existing VM or VM template
3. Create/Clone VM
4. Mount CD-ROM drives
5. Add configuration parameters
6. Create and upload floppy disk
7. Set boot order
8. Power on VM
9. Type boot command _(here missing PutUsbScanCodes method)_
10. Wait for IP _(VM never gets the IP)_
11. Wait shh to become available and connect
12. Run commands to provision the VM
13. Shut down VM
14. Delete floppy drives and image
15. Eject CD-ROM drives
16. Import VM to the content library

<details>
<summary>Logs with real server</summary>

```
==> vsphere-iso.this: Uploading a11d109b36f5213372534d3627dfef0824ae8a2e.iso to packer_cache/a11d109b36f5213372534d3627dfef0824ae8a2e.iso
==> vsphere-iso.this: File already uploaded; continuing
==> vsphere-iso.this: the vm/template example-ubuntu already exists, but deleting it due to -force flag
==> vsphere-iso.this: Creating VM...
==> vsphere-iso.this: Customizing hardware...
==> vsphere-iso.this: Mounting ISO images...
==> vsphere-iso.this: Adding configuration parameters...
==> vsphere-iso.this: Creating floppy disk...
    vsphere-iso.this: Copying files flatly from floppy_files
    vsphere-iso.this: Copying file: ./preseed_hardcoded_ip.cfg
    vsphere-iso.this: Done copying files from floppy_files
    vsphere-iso.this: Collecting paths from floppy_dirs
    vsphere-iso.this: Resulting paths from floppy_dirs : []
    vsphere-iso.this: Done copying paths from floppy_dirs
==> vsphere-iso.this: Uploading created floppy image
==> vsphere-iso.this: Adding generated Floppy...
==> vsphere-iso.this: Set boot order temporary...
==> vsphere-iso.this: Power on VM...
==> vsphere-iso.this: Waiting 10s for boot...
==> vsphere-iso.this: Typing boot command...
==> vsphere-iso.this: Waiting for IP...
==> vsphere-iso.this: IP address: 147.75.91.158
==> vsphere-iso.this: Using ssh communicator to connect: 147.75.91.158
==> vsphere-iso.this: Waiting for SSH to become available...
==> vsphere-iso.this: Connected to SSH!
==> vsphere-iso.this: Running local shell script: /var/folders/2b/xs01fttd7cbdwpzbgnd1k7380000gp/T/packer-shell713236302
    vsphere-iso.this: the address is: 192.168.1.159:0 and build name is: this
==> vsphere-iso.this: Shutting down VM...
==> vsphere-iso.this: Deleting Floppy drives...
==> vsphere-iso.this: Deleting Floppy image...
==> vsphere-iso.this: Eject CD-ROM drives...
==> vsphere-iso.this: Importing VM OVF template example-ubuntu to Content Library...
==> vsphere-iso.this: Clear boot order...
Build 'vsphere-iso.this' finished after 6 minutes 41 seconds.
```

</details>

<details>
<summary>Logs with vcsim mock</summary>

```
==> vsphere-iso.this: Uploading a11d109b36f5213372534d3627dfef0824ae8a2e.iso to packer_cache/a11d109b36f5213372534d3627dfef0824ae8a2e.iso
==> vsphere-iso.this: File already uploaded; continuing
==> vsphere-iso.this: the vm/template example-ubuntu already exists, but deleting it due to -force flag
==> vsphere-iso.this: Creating VM...
==> vsphere-iso.this: Customizing hardware...
==> vsphere-iso.this: Mounting ISO images...
==> vsphere-iso.this: Adding configuration parameters...
==> vsphere-iso.this: Creating floppy disk...
    vsphere-iso.this: Copying files flatly from floppy_files
    vsphere-iso.this: Copying file: ./preseed_hardcoded_ip.cfg
    vsphere-iso.this: Done copying files from floppy_files
    vsphere-iso.this: Collecting paths from floppy_dirs
    vsphere-iso.this: Resulting paths from floppy_dirs : []
    vsphere-iso.this: Done copying paths from floppy_dirs
==> vsphere-iso.this: Uploading created floppy image
==> vsphere-iso.this: Adding generated Floppy...
==> vsphere-iso.this: Set boot order temporary...
==> vsphere-iso.this: Power on VM...
==> vsphere-iso.this: Waiting 10s for boot...
==> vsphere-iso.this: Typing boot command...
==> vsphere-iso.this: Error running boot command: error typing a boot command (code, down) `40, false`: ServerFaultCode: VirtualMachine:vm-106 does not implement: PutUsbScanCodes
```

</details>

For the IP I thought of adding an extra step to the flow only for acceptance tests to add the IP using the available vcsim features. I haven't tried this yet and I'm open to trying any other better idea. 
It would be super good if vcsim add the PutUsbScanCodes method or if I can work around this. I can work on this with your guidance.

Thanks!

**Comment by dougm** [comment]
Hi @sylviamoss , glad to hear you're looking at using vcsim with packer.  To get an IP for a vcsim VM, there are a few options in the wiki, container might be the right fit for this case: https://github.com/vmware/govmomi/wiki/vcsim-features#containers-as-vms

We can add a `PutUsbScanCodes` method, but where should we send the input? Or can the input just be ignored? I suppose we could actually use the input to decide which container to run. Open to suggestions here.

I haven't done anything with ssh + vcsim, but should be possible using containers.

We might also be able to mount any iso or floppy image within a container (if you need to read data from them), but haven't look into doing that before.

Everything else in the list should be possible without changes to vcsim.

**Comment by sylviamoss** [comment]
Hey @dougm, thanks for help! I think the container should fit great to us and I'll definitely try it out.

We use PutUsbScanCodes to type the command for the boot configuration. What could be done is to save all scan codes that were sent and make them available later, so we could validate if they were sent correctly. We had problems in the past with typing correctly commands with alt, ctrl and shift pressed, and this would be a great test case. 🤔 

Mounting iso and floppy image withing the container is useful to us as well. If this is already possible I can give a look at it and understand how it would work. 

Thanks for supporting us with this!
