### ISSUE TITLE
device.disconnect and vm.question are mutually exclusive preventing removing .iso from VM

### ISSUE THREAD

**Issue by justin-davisibm** [vmware/govmomi#2094]
Running 
`govc device.disconnect -vm [vmname] cdrom-3000`

Starts the process of removing the mounted .iso from the machine. However it hangs until the question is answered, resulting in "Connection control operation failed for disk 'ide0:0'." if the question is not answered.

`govc vm.question -vm=[vmname] -answer=0`

Works fine to answer the question, but has to be run under a second shell instance (The other options being to use '&' to execute the disconnect command in the background or to cancel the hanging device.disconnect)

It seems there should be a -force flag, or drop back to shell as soon as the device.disconnect command is executed.

Occurs on most recent v0.23.0 release

**Comment by dougm** [comment]
I suppose we could auto-answer these questions, but haven't seen it come up here before. Was the cdrom ejected first from inside the guest OS?  I would think that'd avoid the problem. How is the cdrom being used in the case, an OS install or ?

**Comment by justin-davisibm** [comment]
In our case we're using a cloud-init iso on an extremely locked down appliance. 

It is Linux based, but without generating an internal-use-only password, I don't have a option to unmount from within the OS.

It's 100% a niche request, but having that -force option would be great. If not, the workaround above works if you put a wait in for 15 seconds between the two commands as the question lags behind quite a bit.

**Comment by dougm** [comment]
You could use `object.collect -n 1` to wait for the question in the background without sleeping, something like:
```bash
(
  # wait for question in the background. $vm must be inventory path relative to DC or absolute
  govc object.collect -n 1 "$vm" runtime.question
  govc vm.question -vm "$vm" -answer 0
) &
pid=$!

govc device.disconnect -vm "$vm" cdrom-3000

kill $pid # Just in case. The background process will be gone already if the question was asked.
```

I think if we implement this in govc, might prefer to have the logic in the vm.question command, so it could be used with commands other than `device.disconnect`.  For example:

```bash
# -A    Exit process after N questions are automatically answered
# -wait Duration, exit process when time is up regardless of how may questions are asked
govc vm.question -A 1 -wait 30m &
```
