### ISSUE TITLE
GOVC : How to define global permissions ?

### ISSUE THREAD

**Issue by melck** [vmware/govmomi#2107]
I want to define global permissions for a Terraform user and Terraform Group.

I have generated user and permissions with this commands : 
```
govc role.create Terraform $(cat files/vmware-terraform-permissions.txt |tr '\n' ' ')
govc sso.group.create 'TerraformUsers'
govc sso.user.create -p 'mypassword!' -d 'Terraform user' terraform
govc sso.group.update -a 'terraform' 'TerraformUsers'
govc permissions.set -group -principal 'TerraformUsers@vsphere.local' -role 'Terraform'
```

When i want to read content library with Terraform, i have a 403 response. From there i delete permissions :
```
govc permissions.remove -group -principal TerraformUsers@vsphere.local
```
Then i go to vsphere ui > Administration > Global permissions, and create global permissions for my group TerraformUsers with role Terraform. When i doing that i can read content librairies with terraform.

How can i setup global permissions only with govc ?

**Comment by dougm** [comment]
govc doesn't support global permissions currently, seems the API is internal only: https://www.virtuallyghetto.com/2017/03/automating-vsphere-global-permissions-with-powercli.html

I poked around but didn't see a public API for this is recently releases either.  Maybe @lamw or @jakerobinson would know?

**Comment by melck** [comment]
Any news on this subject, i'm still interested for this :)

**Comment by Tzvetelin88** [comment]
Global Permissions done via MOB API - Managed Object Browser 
https://github.com/lamw/vmware-scripts/blob/master/powershell/GlobalPermissions.ps1
