### ISSUE TITLE
Folder type is returned as ManagedObjectReference

### ISSUE THREAD

**Issue by akulkarnivnera** [vmware/govmomi#2114]
Hi Doug,

![image](https://user-images.githubusercontent.com/14287179/93053224-229cb500-f685-11ea-8289-13dd3a94b56b.png)
It is for com.vmware.vim25.ws.VimStub#retrieveProperties, where managed object reference can be HostSystem, DataStore or VirtualMachine. And the property is parent.

Is this info sufficient ?

**Comment by dougm** [comment]
Which git revision of govmomi are you using?

**Comment by akulkarnivnera** [comment]
Its an old one - that I had branched out for vRNI limitations.
Is this no loner an issue ? I'll try getting the latest then.

**Comment by dougm** [comment]
It was an issue at one point, but it may have only been within a Pull Request (#1800), not in the master branch.

**Comment by pambekararkin** [comment]
Hi Doug, 

We tried with master branch as well, but with master branch govc sim, **type** property is still incorrectly coming as **ManagedObjectReference**.
Can you please check and let us know?

cc @akulkarnivnera 

Thank you.

Regards,
Priyanka

**Comment by dougm** [comment]
When running `vcsim -trace` and the following command:
```console
% govc object.collect /DC0/host/DC0_H0/DC0_H0 parent
```

The vcsim response is:
```xml
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <soapenv:Body>
  <WaitForUpdatesExResponse xmlns="urn:vim25">
   <returnval>
    <version>-</version>
    <filterSet>
     <filter type="PropertyFilter">session[ca3e82fd-fa9a-46ee-b4cb-939c1b4f904a]5d919f35-5bd7-4d1e-987a-1c20593e5e04</filter>
     <objectSet>
      <kind>enter</kind>
      <obj type="HostSystem">host-21</obj>
      <changeSet>
       <name>parent</name>
       <op>assign</op>
       <val xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="ManagedObjectReference" type="ComputeResource">computeresource-23</val>
      </changeSet>
     </objectSet>
    </filterSet>
   </returnval>
  </WaitForUpdatesExResponse>
 </soapenv:Body>
</soapenv:Envelope>
```

Sounds like it could be a client-side issue, handling `XMLSchema-instance:type="ManagedObjectReference"` vs `type="ComputeResource"`. 

iirc that was the issue in #1800, on the Go client side.

**Comment by kalitanick** [comment]
Hi Doug,

Are there any plans to update vcsim's xml response to only return `type="ComputerResource"` without  `XMLSchema-instance:type="ManagedObjectReference"`? I am trying to use the Java library YaviJava with vcsim and the client incorrectly reads the type as "ManagedObjectReference" when calling .getParent() on a ManagedEntity, causing the program to error out.

Thank you,
Nick

**Comment by dougm** [comment]
The differences I see there are:
- namespace declared as "XMLSchema-instance" vs "xsi"
- the order of the two`type` attributes

I don't have any Java test case to reproduce what you're seeing, if you can provide that I can take a closer look.  Or, if you want to try this patch, it swaps the order of the type attributes:
```diff
diff --git a/vim25/xml/marshal.go b/vim25/xml/marshal.go
index c0c0a588..2efdb7a4 100644
--- a/vim25/xml/marshal.go
+++ b/vim25/xml/marshal.go
@@ -497,11 +497,6 @@ func (p *printer) marshalValue(val reflect.Value, finfo *fieldInfo, startTemplat
 		start.Name.Local = name
 	}
 
-	// Add type attribute if necessary
-	if finfo != nil && finfo.flags&fTypeAttr != 0 {
-		start.Attr = append(start.Attr, Attr{xmlSchemaInstance, typeToString(typ)})
-	}
-
 	// Attributes
 	for i := range tinfo.fields {
 		finfo := &tinfo.fields[i]
@@ -524,6 +519,11 @@ func (p *printer) marshalValue(val reflect.Value, finfo *fieldInfo, startTemplat
 		}
 	}
 
+	// Add type attribute if necessary
+	if finfo != nil && finfo.flags&fTypeAttr != 0 {
+		start.Attr = append(start.Attr, Attr{xmlSchemaInstance, typeToString(typ)})
+	}
+
 	if err := p.writeStart(&start); err != nil {
 		return err
 	}
```
