### ISSUE TITLE
The criteria of connectable ethernet device?

### ISSUE THREAD

**Issue by Yraid** [vmware/govmomi#2115]
Hi, I'd like to create a VM with a connectable network interface.
```
govc vm.network.add -vm MyVM -net "VM Network"

govc device.ls -vm MyVM ethernet*
ethernet--1   VirtualE1000               VM Network

govc device.connect -vm MyVM ethernet--1
```
However, I always encounter "not connectable" message like this:
```
govc: ethernet--1 is not connectable
```
I also tried different adapter types or create DistributedVirtualSwitch, but still can't have a connectable network interface.
I noticed that the VMs can have connectable interface under this command:
```
./vcsim -l 192.168.100.1:443 -dc 1 -cluster 1 -ds 1 -vm 100

/root/go/bin/govc device.info -vm DC0_C0_RP0_VM99 ethernet*
Name:               ethernet-0
  Type:             VirtualE1000
  Label:            ethernet-0
  Summary:          DVSwitch: fea97929-4b2d-5972-b146-930c6d0b4014
  Key:              4000
  Controller:       pci-100
  Unit number:      7
  Connected:        false
  Start connected:  true
  Guest control:    true
  Status:           untried
  MAC Address:      00:0c:29:33:34:38
  Address type:     generated
```
But I need to do more customizations for guest VMs.
I was wondering if there is some criteria I missed to have a connected interface?

Thanks for your helps,
Ethan

**Comment by dougm** [comment]
The error message is from the client side: https://github.com/vmware/govmomi/blob/b553bfc0072836cdbdbac5b3454fec980eefc2fe/object/virtual_device_list.go#L488-L491

Haven't tested it out yet, but we probably need to change vcsim along the lines of:

```diff
diff --git a/simulator/virtual_machine.go b/simulator/virtual_machine.go
index 532bfe4e..f9ed2254 100644
--- a/simulator/virtual_machine.go
+++ b/simulator/virtual_machine.go
@@ -1142,6 +1142,10 @@ func (vm *VirtualMachine) configureDevice(devices object.VirtualDeviceList, spec
                }
        }
 
+       if d.Connectable == nil {
+               d.Connectable = &types.VirtualDeviceConnectInfo{StartConnected: true, Connected: true}
+       }
+
        return nil
 }
```

**Comment by Yraid** [comment]
Thanks! I tried to add this change and it works.
