### ISSUE TITLE
DVS create for 7.0.0 version missing configuration settings

### ISSUE THREAD

**Issue by sygibson** [vmware/govmomi#2119]
I'm working with DVS version 7.0.0 switches - and finding that it appears there are missing options/values for configuring this version of DVS.  For DVS 6.6.0 switches, I'm able to build correcty, and add hosts.  For DVS 7.0.0 - the following values seem to be missing from the `govc` options capabilities:

```
Port Binding = "Static binding"
Port Allocation = "Elastic"
```

The following is a set of create/add operations for DVS, with 7.0.0 DVS product-version, and the failure:

```
Starting DVS configuration based on 'esxi/dvs-mappings' Param.

Finding ESXi node members to operate on in cluster 'foo.mgt.cl' with 'dvs01' DVS.
      DRP Names:  sc2-hs2-b1722 sc2-hs2-b1724 sc2-hs2-b1723
ESXi Node Names:  sc2-hs2-b1723.foo.example.com sc2-hs2-b1724.foo.example.com sc2-hs2-b1722.foo.example.com

govc dvs.create -dc foo.mgt.dc -product-version 7.0.0 -mtu 9000 -folder /foo.mgt.dc/network dvs01
adding dvs01 to folder /foo.mgt.dc/network... OK

govc dvs.portgroup.add -dvs /foo.mgt.dc/network/dvs01 -type lateBinding -nports 32 pg_external
adding pg_external portgroup to dvs /foo.mgt.dc/network/dvs01... OK

govc dvs.portgroup.add -dvs /foo.mgt.dc/network/dvs01 -type ephemeral -nports 16 -vlan 10 pg_internal
adding pg_internal portgroup to dvs /foo.mgt.dc/network/dvs01... OK

govc dvs.add -dvs /foo.mgt.dc/network/dvs01 -pnic vmnic2 sc2-hs2-b1723.foo.example.com sc2-hs2-b1724.foo.example.com sc2-hs2-b1722.foo.example.com

adding 3 hosts to dvs /foo.mgt.dc/network/dvs01... (78%)
adding 3 hosts to dvs /foo.mgt.dc/network/dvs01... (78%)
adding 3 hosts to dvs /foo.mgt.dc/network/dvs01... Error: Cannot complete a vSphere Distributed Switch operation for one or more host members.
govc: Cannot complete a vSphere Distributed Switch operation for one or more host members.
```

in vCenter, the host with the failed DVS01 switch add, shows the following error:

```
The host proxy switch associated with sc2-hs2-b1722.foo.example.com no longer exists in vCenter Server. vCenter Server is not able to automatically remove the host proxy switch because it is still in use. To resolve the issue, disconnect any VMs and VMkernel network adapters that might be connected to the switch and remove the switch.
```

**Comment by dougm** [comment]
@sygibson is this what you were referring to in slack? If so, could you include the PowerCLI examples, doc links, etc., here?

**Comment by sygibson** [comment]
@dougm - no, this is different.  When creating the DVS - you have the following options exposed in the `dvs.portgroup.add` defines the following settings/options:

```
  -nports=128            Number of ports
  -type=earlyBinding     Portgroup type (earlyBinding|lateBinding|ephemeral)
  -vlan=0                VLAN ID
```

However, it appears from the GUI when creating DVS Portgroups, a version 7.0.0 DVS only supports "Ephemeral" and a new "Static Binding" option.  In addition, it specifies "Port Allocation" of "elastic". 

I have found that if you set the DVS settings as follows:

`govc dvs.portgroup.add -dvs /foo.mgt.dc/network/dvs01 pg_external`

(remove the `-type` and `-nports` options), the default settings for a version 7.0.0 DVS Portgroup will be set to Static Binding / Elastic port allocation.  

However, the lateBinding and earlyBinding options appear to cause an error.

**Comment by dougm** [comment]
@sygibson can you review #2163 ?  That'll answer some of the questions, but I don't know about the host proxy switch error.
