### ISSUE TITLE
Data not preserved inside vmdk when disk removed and attached again using govc

### ISSUE THREAD

**Issue by yash-nigam** [vmware/govmomi#2120]
Hello,

Our use case is:
1) Create a disk for a Linux vm

`govc vm.disk.create -vm name -size 2G -name vm Datasupport/persistentdisk.vmdk -sharing=sharingNone -mode=persistent`

2) once vm is up, create pv, vg, and lv , format partition using ext4 and mount it and add data

3) once data is written unmount the volume and shutdown the vm.

4) remove the attached disk by `govc device.remove -vm vm -keep disk-1000-1`

5) attach this disk to another Linux vm by : `govc vm.disk.attach -vm vm -disk Datasupport/persistentdisk.vmdk -persist=true -mode=persistent -sharing=sharingNone`

6) Start vm

7) When vm boots up and we check via fdisk, lsblk, or df -h, the partition created in step 2 is not found and we have an empty /dev/sdb disk containing no data.

How can we preserve data using govc commands while detaching and attaching disk to different vms.

**Comment by dougm** [comment]
Have you tried `vm.disk.attach -link=false` ?

**Comment by yash-nigam** [comment]
I will try this and update back.

**Comment by yash-nigam** [comment]
Thanks @dougm 
-link=false enabled us to save the data.

**Comment by dougm** [comment]
@yash-nigam ok, added some docs in #2140
