### ISSUE TITLE
ClusterComputeResourceList:can't get cluster info

### ISSUE THREAD

**Issue by wangchuanxiaolu** [vmware/govmomi#2121]
s := &spec{
		Relative: f.hostFolder,
		Contents: true,
	}
can get cluster info after add param "Contents"

**Comment by dougm** [comment]
The Content flag is only useful for `ManagedObjectList` though, right?  Have you looked at using ContainerView instead for this case?  Added an example here: https://github.com/vmware/govmomi/pull/2138
