### ISSUE TITLE
govc: add multiple retries for temporary connection lost

### ISSUE THREAD

**Issue by piyushkv1** [vmware/govmomi#2123]
GOVC_USERNAME=administrator@vsphere.local GOVC_PASSWORD=Admin\!23 govc ls -k -u=10.203.24.16 -t ClusterComputeResource host | grep -i compute failed on 10.203.28.197: govc: Post https://10.203.24.16/sdk: dial tcp 10.203.24.16:443: connect: no route to host

Above is because of temporary connection lost for some seconds.

Could we add retry mechanism on govc?

**Comment by dougm** [comment]
We could look at doing that and/or a mapping of connection errors to exit codes.  Could you take a look the options `curl` provides and curl's exit code mapping, then post it here?  That would help with the UX part.
