### ISSUE TITLE
govc host.autostart.configure does not work

### ISSUE THREAD

**Issue by domenico-piol** [vmware/govmomi#2125]
Try to set any option with host.autostart.configure... nothing happens. E.g.:

>  govc host.autostart.configure -start-delay=20 $vm

Where $vm is the name of a VM... No error is returned but no changes applied.

**Comment by dougm** [comment]
Haven't used the host.autostart commands myself, but it looks like `host.autostart.add` should be used to configure VMs and  `host.autostart.configure` is settings for the host itself.

**Comment by domenico-piol** [comment]
@dougm You are right.... one doesn't see that from the docs but apparently its like you say, just tested it. ..add does indeed autostart a VM, however it is apparently not possible then to configure the autostart (delay etc). Never mind, this is what I was looking for for a start. thx!!
