### ISSUE TITLE
govc: device.boot misses an option to set EFI/BIOS boot

### ISSUE THREAD

**Issue by lucab** [vmware/govmomi#2126]
As a `govc` user, I'd like to have a way to set EFI or BIOS firmware setting via `device.boot` on an existing VM, so that I can switch between BIOS / plain-EFI / EFI with Secure Boot modes.

Right now trying to set Secure Boot mode on a machine configured with BIOS firmware fails with:
```
$ govc device.boot -vm "${MACHINE}" -secure
govc: Invalid virtual machine configuration.
```

After manually changing to EFI boot in the machine settings in the webUI, the command above succeeds. However, I'm missing a way to perform this BIOS<->EFI switch through `govc device.boot`.

https://github.com/vmware/govmomi/pull/1072 added this to `govc vm.create`, but as I'm deploying via `library.deploy` I cannot go through that. Also, IMHO it would be good anyway to have a way to flip the value after machine creation.

**Comment by dougm** [comment]
Sounds good to me.  Do you want to take a look at implementing this?  Otherwise I can take look soonish.

**Comment by lucab** [comment]
@dougm thanks for the feedback. Right now I don't have much bandwidth for this myself (and I think most of the time would be spent on learning the codebase structure and client->backend API). I'm not in a hurry and can wait for your patch; missing CLI support is a bit of an inconvenience but the webUI is a working escape hatch while still at small-scale.

**Comment by dougm** [comment]
@lucab can you review #2172 ?

**Comment by lucab** [comment]
@dougm done, also manually validated that it works. Thanks for the enhancement!
