### ISSUE TITLE
Getting 'RetrieveManagedMethodExecuter' error for Hosts

### ISSUE THREAD

**Issue by pambekararkin** [vmware/govmomi#2128]
Hi Doug,

I'm from vRNI team working with @akulkarnivnera.
We are using govmomi latest master branch, and are seeing '**RetrieveManagedMethodExecuter**' error for Hosts.

Here's the response  from VC simulator:
```
govc host.esxcli -dc=washington-dc-delta-1 -host.ip=10.196.167.13 network ip route ipv4 list -N vxlan
govc: ServerFaultCode: no vmomi type defined for 'RetrieveManagedMethodExecuter'
```
Response from actual VC:
```
govc host.esxcli -dc=washington-dc-delta-1 -host.ip=10.196.167.13 network ip route ipv4 list -N vxlan
Network       Netmask        Gateway         Interface  Source
-------       -------        -------         ---------  ------
default       0.0.0.0        10.196.167.253  vmk1       MANUAL
10.196.167.0  255.255.255.0  0.0.0.0         vmk1       MANUAL
```

Please let me know if you need more details.
cc @akulkarnivnera 

Thank you.

Regards,
Priyanka

**Comment by dougm** [comment]
We just haven't implemented this in vcsim yet.  Is this the only esxcli related API/command you need or are there more?

**Comment by pambekararkin** [comment]
Hi Doug, 

These are the other two esxcli that we use, along with the one provided earlier:
 
**govc host.esxcli -dc=Pod2 -host.ip=10.16.128.65 software vib list**
**govc host.esxcli -dc=Pod2 -host.ip=10.16.128.65 system module list**

cc @akulkarnivnera

Thank you.

Regards,
Priyanka

**Comment by dhananjaysarkin** [comment]
with the latest govc binary (https://github.com/vmware/govmomi/releases/download/v0.30.4/govc_Linux_x86_64.tar.gz)
still facing the above issue.
