### ISSUE TITLE
govc: Is there any govc command which can list the Subnet Mask/prefix/Gateway related info available on a network.

### ISSUE THREAD

**Issue by yash-nigam** [vmware/govmomi#2130]
Our use case is to:
1) Deploy an vm using ova file using govc import.ova command.
2) Set a static IP to the to the vm via automation.
3) This step requires us to know in advance the interfaces, Subnetmask's/Gateway's available  on the Network.
4) But we are not able to to see any info related to this using dvs.portgroup.info 
5) Using vm.info method we can see these details in path Guest-Ipstack-IProuteconfig, but that is only after we have manually assigned the ip/subnet/gateway.
6) We are using a NSX based setup.

**Comment by manadart** [comment]
I am also trying to get this information, and have not yet been able to work out how.

**Comment by dougm** [comment]
I don't know of an API that provides that info for a portgroup. Do you see that info in the UI anywhere?

However, it is possible to get it from an ESX host, for example:
https://github.com/vmware/govmomi/blob/9a4f1f95eafd9f18b77919731a6e9f5b423d75b3/scripts/vcsa/create-vcsa-vm.sh#L90-L96
