### ISSUE TITLE
Retrieve all IPs for VMs using vmware/govmomi/vim25 

### ISSUE THREAD

**Issue by paologallinaharbur** [vmware/govmomi#2131]
[We are currently](https://github.com/newrelic/nri-vsphere/blob/cdcefc6ccd28a18213a8ec93c8d74387a3e7cb48/internal/process/vms.go) trying to fetch all IPs connected to a VM, the issue is that we are capable to retrieve some, but not all IPs.

The code is more or less the following:

 - Fetching all the data regarding VMs
```go
propertiesToRetrieve := []string{"name", "summary", "network", "config", "guest", "runtime", "resourcePool", "datastore", "overallStatus"}

err = cv.Retrieve(ctx, []string{VIRTUAL_MACHINE}, propertiesToRetrieve, &vms)
```

 - Checking ipAddresses in the Guest.net object
``` go
for _, nic := range vm.Guest.Net {
	// available in api v5
	if nic.IpConfig != nil {
		for _, addr := range nic.IpConfig.IpAddress {
			ipAddresses.WriteString(addr.IpAddress)
			ipAddresses.WriteRune('|')
		}
	} else {
		for _, ip := range nic.IpAddress {
			ipAddresses.WriteString(ip)
			ipAddresses.WriteRune('|')
		}
	}
}
```

 - Are we taking some wrong assumptions? 
 - Is there a better way to fetch all IPs for a vm?

The documentation for **ipAddress** states  "Zero, one or more manual (static) assigned IP addresses to be configured on a given interface"
 - All IPs assigned to a VM are included, or for example DHPC ones are not? 

We should be using the very [same logic of the client](https://github.com/vmware/govmomi/blob/0614f98752bbc46dc2c46516d96898922a5898ff/object/virtual_machine.go#L273) if I am not wrong.

**Comment by dougm** [comment]
That's the right place to get the data, but requires: VM is powered on, NICs are up, IPs are assigned and vmware-toolsd has sent the data.  It will include all IPs, static + DHCP.

Which IPs are not being reported?  Newer versions of vmware-tools has a filtering feature (e.g. to exclude the docker bridge), but not sure if does any filtering by default.

**Comment by paologallinaharbur** [comment]
Thanks for the clarification!
We double checked and it was an issue with vmware-tools not installed. I'll close the issue!
