### ISSUE TITLE
govc: Get device names in object.collect JSON

### ISSUE THREAD

**Issue by lukasluecke** [vmware/govmomi#2135]
I am using `govc object.collect -json [...] config.hardware.device` to get a list of the devices, but the result does not contain the device names (e.g. `ethernet-0`), which I need for further calls.

Using `govc device.ls` or `govc device.info` I get what I need, but need to run this once per VM, which is not optimal.

Is there any way to get the data I want, or is this just not part of the properties that are exposed to `object.collect`?

**Comment by dougm** [comment]
We added `Name` and `Type` fields to `device.info` in a1a96c8f and e805389e
The `object.collect` command doesn't inject any fields, it just uses the API structures as-is.  Can you describe the use case? Maybe we can find or add another way.
