### ISSUE TITLE
Is there a way to get more comprehensive error reason from esxcli command

### ISSUE THREAD

**Issue by li-kai-yuan** [vmware/govmomi#2148]
When run govc host.esxcli command, if esxcli command itself fails, the govc command return message is always EsxCLI.CLIFault.summary, which leads to troubleshooting difficulty. 

Is there a way to inspect more error message via govc commands? Thanks

```
/ # govc host.esxcli -dump=1 -debug=1 software profile update -depot a -profile b
flags.errorOutput{
    error: &errors.errorString{s:"EsxCLI.CLIFault.summary"},
}
```

**Comment by dougm** [comment]
Have you looked at the debug output? It is written to file(s) by default, but you can change it to stderr: https://github.com/vmware/govmomi/blob/master/govc/README.md#usage

**Comment by li-kai-yuan** [comment]
Thank you! This is exactly what I'd like to get
