### ISSUE TITLE
rename library objects

### ISSUE THREAD

**Issue by nathharp** [vmware/govmomi#2149]
I don't know if I'm missing something, but is there a way to rename templates in a content library with govc?   rename.object cannot find something that can be listed via library.ls

**Comment by dougm** [comment]
We need to add a `library.change` command, similar to other govc `*.change` commands.. that would let you update the name and other attributes of the library.

**Comment by nathharp** [comment]
That would be ideal.   It also confirms that I wasn't missing something!
