### ISSUE TITLE
can there any examples here?

### ISSUE THREAD

**Issue by lengxugz** [vmware/govmomi#215]
i'm very interesting about this project and wants do some projects with it, can there any examples here?

**Comment by pietern** [comment]
What kind of examples are you looking for? You can take a look at the govc code, as consumes the govmomi API extensively. Also read up on the vSphere API documentation itself. This library is a straight mapping of that API to Go.

**Comment by rogierlommers** [comment]
Well, I also would love some examples of how to use the library. F.e. how can we create / clone virtual machines without using the command line tool (govc)?
