### ISSUE TITLE
QueryEvents can not get event level

### ISSUE THREAD

**Issue by wangchuanxiaolu** [vmware/govmomi#2152]
QueryEvents function can not get event level, like info、error、warning. and FullFormattedMessage is english, No Chinese field

**Comment by dougm** [comment]
For messages, you can change the Locale: https://github.com/vmware/govmomi/blob/02cb7d70c47436e951b9a17993010c2e3759a195/session/manager.go#L33-L35

For level, you can use the `EventCategory` method, for example: https://github.com/vmware/govmomi/blob/02cb7d70c47436e951b9a17993010c2e3759a195/govc/events/command.go#L98

**Comment by dougm** [comment]
Closing as stale. Feel free to reopen if this is still an issue.
