### ISSUE TITLE
govc import.ova gives error dial tcp IP:443: i/o timeout

### ISSUE THREAD

**Issue by yash-nigam** [vmware/govmomi#2157]
Hello,

While executing command 
govc import.ova --options=test.spec -ds=datastore1 -pool=/datacenter-1/host/cluster1/Resources test.ova

And we get the following error

Uploading supportvm-disk1.vmdk... Error: govc Post "https://<esx hostname>/nfc/5228093a-041d-0b66-1bb8-2dcea977e1c7/disk-0.vmdk": dial tcp IP:443: i/o timeout

The esx hostname is pingable from where govc command is run.
Other govc commands such as govc about, govc ls / work fine.
We are not able to determine where is the issue.

**Comment by dougm** [comment]
One option is to use Content Library instead, which only connects to vCenter, not to ESX directly:

[library.create](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarycreate)

[library.import](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#libraryimport)

[library.deploy](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#librarydeploy)
