### ISSUE TITLE
Hitting user-data size limit. How can we increase user-data size of VM?

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2158]
I'm currently running into the following error [1] after adding more write files to my user-data.
Is there a way to configure this with govmomi?

[1] `Cloud init user data exceeds the vSphere size limit 64000`

**Comment by dougm** [comment]
Where does the message `Cloud init user data exceeds the vSphere size limit 64000` come from ?  It isn't from govmomi or vSphere. And the limit is much larger than that iirc: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-91BF834E-CB92-4014-8CF7-29CE40F3E8A3.html

**Comment by dougm** [comment]
Any more details on this @chardch ?

**Comment by chardch** [comment]
I realized that error message was coming from our side from an assumption that the vapp user-data property could only be 64k. Is there no actual limit for any vapp property, but rather just that the final vmx file is less than 1MB? Does the ovf-env.xml file have any similar limitation?

**Comment by dougm** [comment]
I don't know of any vapp property limits, just the final vmx file size.  What is the ovf-env.xml file?  I don't know of any ovf file size limitations either.
