### ISSUE TITLE
Why I get the CPUCorePerSocket is 2 when CPUS=1

### ISSUE THREAD

**Issue by Kotodian** [vmware/govmomi#2159]
![image](https://user-images.githubusercontent.com/22030659/96681633-30430a00-13aa-11eb-9393-0c17f71cd4ed.png)

**Comment by dougm** [comment]
How was the VM created?

`numCPUs` and `numCoresPerSocket` are part of the spec used to create (or configure) the VM:

https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.ConfigSpec.html

**Comment by Kotodian** [comment]
> How was the VM created?
> 
> `numCPUs` and `numCoresPerSocket` are part of the spec used to create (or configure) the VM:
> 
> https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.ConfigSpec.html

I cloned the other vm and I want to get the parameter to display

**Comment by dougm** [comment]
> I cloned the other vm

Then the vm you cloned from was configured with `numCoresPerSocket = 2`

> I want to get the parameter to display

What do you mean?

**Comment by Kotodian** [comment]
> > I cloned the other vm
> 
> Then the vm you cloned from was configured with `numCoresPerSocket = 2`
> 
> > I want to get the parameter to display
> 
> What do you mean?

the numCoresPerSocket is different from what I saw in vmware client

**Comment by Kotodian** [comment]
> > I cloned the other vm
> 
> Then the vm you cloned from was configured with `numCoresPerSocket = 2`
> 
> > I want to get the parameter to display
> 
> What do you mean?

I reconfigured with `numCoresPerSocket=1`,but when I got the vm, `numCoresPerSocket` turned to 2,then I checked the vmware client,the `numCoresPerSocket = 1`.Do you know what I mean? I'm Chinese.My English is not good.

**Comment by dougm** [comment]
Did you reconfigure numCoresPerSocket with the UI or govmomi?

**Comment by Kotodian** [comment]
> Did you reconfigure numCoresPerSocket with the UI or govmomi?
oh I know the problem.thx
