### ISSUE TITLE
Is there a way to disable DRS /HA via govc

### ISSUE THREAD

**Issue by li-kai-yuan** [vmware/govmomi#2161]
Hi,

I'm able to enable DRS / HA via govc, is govc also support feature to disable DRS / HA?

Thanks.

**Comment by dougm** [comment]
Yes, [cluster.change](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#clusterchange)

**Comment by li-kai-yuan** [comment]
Thanks! Just realized that cluster.change has already support disable option
