### ISSUE TITLE
Execute shell script on target VM without providing guest credentials

### ISSUE THREAD

**Issue by gaetano-fichera** [vmware/govmomi#2164]
Hi all,

What I do now, after I retrieve `vm *VirtualMachine`, is:

```
opMan := guest.NewOperationsManager(client, vm.Reference())
procMan, err := opMan.ProcessManager(*ctx)
auth := vmGuest.AuthFlag{}
auth.Set("guestUser:guestPassword")
guestProgSpec := types.GuestProgramSpec{
	ProgramPath:      "/bin/bash",
	Arguments:        "-c <shell commands>",
	WorkingDirectory: "/",
	EnvVariables:     []string{},
}
pid, err := procMan.StartProgram(*ctx, auth.Auth(), &guestProgSpec)
```

In this way I have to provide different guest credentials for each target vm. Is there any way to do it without providing credentials and using a default one, maybe with elevated privilegies, also as VMware tools is installed as root? Unfortunately I have not found any documentation on this and I would pleased if someone else can help to understand it. Thanks in advance for your help.

**Comment by dougm** [comment]
AFAIK VMware tools requires credentials for all guest operations and there isn't such a default user. 

There is a [token authentication](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.guest.SAMLTokenAuthentication.html) option, but `AddGuestAlias` would still require a 1-time username:password auth for each VM.

It is possible if you use [govmomi/toolbox](https://github.com/vmware/govmomi/tree/master/toolbox) instead of the standard VMware tools.

**Comment by GaetanoFichera** [comment]
@dougm Thanks for your reply. I forgot to mention I retrieve the *VirtualMachine through my vCenter (my app doesn't run on the target vms) calling https://github.com/vmware/govmomi/blob/15d36b27b1375b9f85a86cb67902cb41645e168c/view/container_view.go#L116
filtering on the _VirtualMachine_ type with a specific **instanceUUID**, and I would do it on a set of **instanceUUIDs** without, as I said, providing guest credentials for each of them. How could your suggestion be integrate with my scenario? Or there is something else I can implemet?

**Comment by gaetano-fichera** [comment]
Hi @dougm, could you please share your opinion about my last comment? Thanks.

**Comment by dougm** [comment]
You'd have to have guest vm credentials that would work against that set of VMs if running vmware-tools.  What is your use case?  Have you considered other options such as ssh or cloud-init?

**Comment by gaetano-fichera** [comment]
As I said, I would know if it is possible to run a script on a remote VM through vCenter login without supplying the guest credentials and using this SDK. An example of what I mean is the AWS SDK, it lets to do it leveraging on the API of the SSM Agent installed on the VM deployed in the AWS Cloud (https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html).

**Comment by dougm** [comment]
I was asking about the use case for example if you just need to run a script on a VM's first boot, cloud-init does not require any guest credentials.  If there's a way to skip guest authentication with vmware-tools, it would have to be an option in https://github.com/vmware/open-vm-tools , but I don't know of one.

**Comment by gaetano-fichera** [comment]
Thanks for the support, I'm going to look for an other approach 👍
