### ISSUE TITLE
How to get the disk uuid

### ISSUE THREAD

**Issue by surajsub** [vmware/govmomi#2165]
TIA - Is there a way to get the list of disks attached to a vm ( device.info) and also get the uuid of the disks that are attached to it ?

**Comment by dougm** [comment]
Sure, you can do something like:
```bash
#!/bin/bash

IFS=$'\n'

for vmdk in $(govc device.info -vm "$vm" -json disk-* | jq -r .Devices[].Backing.FileName); do
  govc datastore.disk.info -uuid "$vmdk"
done
```

**Comment by surajsub** [comment]
Thanks @dougm  - I was looking more of getting this information via one single call like device.info -vm <vmname>

I don't think that's possible or is this an enhancement that needs to be made.

**Comment by dougm** [comment]
There is a single call you can use:
```console
% govc device.info -vm $name -json disk-* | jq -r .Devices[].Backing.Uuid
```
