### ISSUE TITLE
govc: NoPermission error during create disk

### ISSUE THREAD

**Issue by yash-nigam** [vmware/govmomi#2166]
Our use case is :
create a dir: `govc datastore.mkdir -p=true -ds=<dsname> <folder name>`
create disk: `govc datastore.disk.create  -size 512G -ds=<dsname> <folder name>/persistent_disk.vmdk`

The disk gets created, but we also get this error.
[27-10-20 11:20:49] Creating persistent_disk.vmdk...OK
/tmp/gztmpKRJ/govc: NoPermission

Some answers have been given here [](https://github.com/vmware/govmomi/issues/251)
as: 
```
rm -rf ~/.govmomi/sessions
GOVC_PERSIST_SESSION=0
```

we tried them, but it didnt work, and we get same error again

**Comment by dougm** [comment]
I don't think the issue is related to the session cache, but if you want to turn that off make sure you `export` that variable.
You can use the `-debug` flag to get more details on what request is returning `NoPermission`:
https://github.com/vmware/govmomi/tree/master/govc#troubleshooting

**Comment by dougm** [comment]
Closing as stale. Feel free to reopen with debug info if this is still an issue.
