### ISSUE TITLE
Get vms by host

### ISSUE THREAD

**Issue by BennyEarl** [vmware/govmomi#2167]
I'm currently writing an API with one of it's functions being to find out how much memory has been provisioned to VMs on a single host.

When I'm getting the properties of a host I can get a list of VMs on that host but they're in the format of {"vm-12","vm-128",...} and the virtual machine list function uses the path. Is there a way I can get VM properties from the above format? or a pre cooked function that gets mo.VirtualMachines by host that i haven't been able to find?

**Comment by dougm** [comment]
There's an example here: https://godoc.org/github.com/vmware/govmomi/property#example-Collector-Retrieve

Just added to the list of properties (`[]string{"name"}`) you want to collect.
