### ISSUE TITLE
RetrieveWithFilter not working as expected

### ISSUE THREAD

**Issue by ToxicSamN** [vmware/govmomi#2168]
I am struggling with using the ContainerView method RetrieveWithFilter. My code is below. I am attempting to retrieve the VirtualMachines from a cluster that are powered on. I am trying to use the RetrieveWithFilter method and use `property.Filter{"runtime.powerstate": "poweredon"}`. Instead I keep getting an error `ServerFaultCode: InvalidProperty` at the below line `err = cv.RetrieveWithFilter(ctx, []string{"VirtualMachine"}, []string{"name"}, &vms, property.Filter{"runtime.powerstate": "poweredon"})`
I have also tried `property.Filter{"runtime.powerstate": types.VirtualMachinePowerStatePoweredOn}` with the same result.

Am I missing something here or is "runtime.powerstate" not a property I can filter on? I'm trying to avoid having to loop through every object and checking this property and instead get all powered on VMs in a single call.

``` Go
// obtain user/pass data
u.User = c.getSoapUserInfo()

// Connect and log in to the vsphere system
c, err := govmomi.NewClient(ctx, u, insecure)
if err != nil {
	log.Fatal(err)
}

mgr := view.NewManager(c.Client)

// create the container view for all ClusterComputeResources starting at the RootFolder
cv, err := mgr.CreateContainerView(ctx, c.Client.ServiceContent.RootFolder, []string{"ClusterComputeResource"}, true)
if err != nil {
	log.Fatal(err)
}
defer cv.Destroy(ctx)

var cl mo.ClusterComputeResource
// Retrieve cluster named mycluster and store in cl
err = cv.RetrieveWithFilter(ctx, []string{"ClusterComputeResource"}, nil, &cl, property.Filter{"name": "mycluster"})

// FIXME: BEGIN this is only a dev debug section testing runtime.powerstate filter
// recreate the container view for all VirtualMachine types starting at the ClusterComputeResource
cv, err = mgr.CreateContainerView(ctx, cl.Reference(), []string{VirtualMachine}, true)
if err != nil {
	log.Fatal(err)
}

vms := []mo.VirtualMachine // empty literal declaration
err = cv.RetrieveWithFilter(ctx, []string{"VirtualMachine"}, []string{"name"}, &vms, property.Filter{"runtime.powerstate": "poweredon"})
if err != nil {
	log.Fatal(err)
}
// FIXME: END Debug section
```

Output: >> ServerFaultCode: InvalidProperty

**Comment by dougm** [comment]
The property names are case-sensitive I believe, should be `powerState`: https://github.com/vmware/govmomi/blob/ec4c12afffc4285938a23fd7f8b9daafbe8a93d5/object/virtual_machine.go#L35

**Comment by ToxicSamN** [comment]
Perfect, thank you. Plugging this line in is what I needed. 
`property.Filter{object.PropRuntimePowerState: types.VirtualMachinePowerStatePoweredOn})`
