### ISSUE TITLE
WaitForIP() to exit immediately on powered off machines

### ISSUE THREAD

**Issue by mkuzmin** [vmware/govmomi#218]
When I call vm.WaitForIP() method on suspended or powered off machines, it waits for 15 minute timeout.
It would be helpful if the method detect VM power state by its own, and wait for powered on machines only.

**Comment by caglar10ur** [comment]
I personally prefer the current way as it allows you to do the initial work first and then power on the VM later. Also you can always check VM's power state before calling WaitForIP() :) 

What do you think @dougm?

**Comment by dougm** [comment]
I suppose both are useful.  How about if we keep the default behavior as-is and add a '-on' flag that only waits for VMs with powerState == on ?  It'd be a nice shortcut, esp. if checking multiple VMs.  

We should probably add a '-timeout' flag too.

**Comment by dougm** [comment]
Yes, you use `context.WithDeadline` to shorten the timeout.  The govc vm.ip command has a new `-wait` flag that uses this too.  You can also just collect the "guest.ipAddress" property directly without using WaitForIP, if you're only interested in VMs that are powered on.
