### ISSUE TITLE
Unable to import ova of size 6GB using govc 

### ISSUE THREAD

**Issue by hbilling** [vmware/govmomi#2180]
While trying to import an OVA of size 6GB to deploy the same on a VM on vSphere, I am getting the following error:
 
Command Used: 
govc import.ova --options=file.json /tmp/test.ova

where test.ova is a 6GB File

stderr:
**/usr/local/bin/govc: failed to parse ovf: failed to parse ovf: strconv.ParseUint: parsing "6605098496": value out of range**

I believe the size assumed is of Unsigned int which might go to a max of 4294967295 ie 4GB. Is my understanding correct? 
Any pointers towards fixing the same would help please.

**Comment by hbilling** [comment]
can someone help pleasE?

**Comment by dougm** [comment]
I think you're right, but it isn't clear which field is causing the problem. Do you see the same problem using `govc import.spec /tmp/test.ova` ?  If so and you could share just the .ovf file, I could use that to reproduce and fix.

**Comment by hbilling** [comment]
Hi dougm,

What i can confirm is that **_govc import.spec /tmp/test.ova_** also shows the same problem. Unfortunately I am not in a position to share the proprietary 6GB file if that is what you requested for. I may be mistaken but i dont think the content of the file would matter. I think the problem should appear with any file which is bigger than 4GB. 
To quickly generate a file of a large size as we need we can refer to https://www.cyberciti.biz/faq/howto-create-lage-files-with-dd-command/ 

Thanks

**Comment by dougm** [comment]
@hbilling understood, I wasn't asking for the entire `.ova`, only the `.ovf`.  Just the xml spec, not the data disk.  Since `import.spec` fails the same way, that confirms the issue is with parsing the `.ovf` spec, rather than the vmdk/disk itself.  You can use `tar -xf test.ova` to extract the `.ovf` descriptor.

**Comment by XudongLiuHarold** [comment]
Met the same problem when I try to use `govc import.ovf` a more than 4 GB ovf with `govc` version `0.23.0`.

But I switched back to `0.21.0`, which can workaround this problem.

**Comment by dougm** [comment]
Anyone able to provide a `.ovf` (not `.ova`) to reproduce?  I cannot reproduce using a 16GB image.
And which OS/arch govc release are you using?

**Comment by XudongLiuHarold** [comment]
Hi @dougm , I think you can use this one from dbc account: http://sc-dbc1105.eng.vmware.com/fangyuanl/images/controller-20.1.3-9053.ovf to test it.

I am running `govc` on a Linux machine.

**Comment by dougm** [comment]
ok, I can reproduce using 0.23 govc_linux_386.gz ... but the 32-bit binaries are no longer supported, can you use the 64-bit linux binary instead? https://github.com/vmware/govmomi/releases/download/v0.24.0/govc_linux_amd64.gz

**Comment by XudongLiuHarold** [comment]
Sure, thanks 👍

**Comment by dougm** [comment]
Please re-open if the issue persists using 64-bit govc.
