### ISSUE TITLE
govc should print the fill error stack when commands fail

### ISSUE THREAD

**Issue by jpeach** [vmware/govmomi#2181]
I ran the following command:

```
$ govc vm.clone -template=true -dc=/remote-site-1 -ds=/remote-site-1/datastore/vsanDatastore -vm=/datacenter/vm/photon-3-kube-v1.19.1 -pool=/remote-site-1/host/cluster/Resources -on=false  photon-3-kube-v1.19.1
[16-11-20 15:39:20] Cloning /datacenter/vm/photon-3-kube-v1.19.1 to photon-3-kube-v1.19.1...Error: Cannot complete file creation operation.
govc: Cannot complete file creation operation.
```

The full error as shown in the vCenter UI is:
```
Clone virtual machine
Status: Cannot complete file creation operation.
Initiator: VSPHERE.LOCAL\Administrator
Target: photon-3-kube-v1.19.1
Server: foo.example.com
Error stack:
    -> There are currently 2 usable fault domains. The operation requires 1 more usable fault domains.
    -> Failed to create object.
```

It would be pretty informative for govc to show the full error stack when an operation fails.

**Comment by dougm** [comment]
We should output more than just the message by default.
In the meantime, you can see the entire fault structure using `-debug`: https://github.com/vmware/govmomi/tree/master/govc#debug-flag

The format flags also output the entire fault struct. `-xml`, `-json` and `-dump`

If you're still able to reproduce that error and capture with `-xml`, can you paste that here?  Just want to see if the 'Error stack' is included in the fault.

**Comment by embano1** [comment]
Related: #2278

**Comment by dougm** [comment]
My vCenter testbed was in the same state today.. with PR #2333 the error output looks like:
```
govc: Failed to create object. (vob.vsanprovider.object.creation.failed)
govc: There are currently 2 usable fault domains. The operation requires 1 more usable fault domains. (vob.vsan.clomd.needMoreFaultDomains2)
govc: Cannot complete file creation operation. (Reserving folder on host)
```
