### ISSUE TITLE
Best way to create a VM on a cluster in a datacenter?

### ISSUE THREAD

**Issue by Borkason** [vmware/govmomi#2182]
I'm trying to create a new VM on a vSphere cluster. I read in the [Web services SDKProgramming Guide](https://vdc-download.vmware.com/vmwb-repository/dcr-public/cdbbd51c-4824-4a1b-ad43-45df55a76a76/8cb3ed93-cac2-46aa-b329-db5a096af5bc/vsphere-web-services-sdk-67-programming-guide.pdf) that I need to run the CreateVM_Task method on a folder and that I need to specify either a resource pool or a host.

I'd like to specify a resource pool and let vSphere figure out where to place the VM.

At the moment I use the finder to search for the folder, so I can then use `CreateVM()` on the folder. But `CreateVM()` needs host and pool. What is the recommended approach for this? What I have right now, looks odd. Beside that, I can't find the resource pool (returns an error).

To me it seems that folders are cluster and resourcepool agnostic and always live on the datacenter. Should I even use the Finder, or is there a better way?

```go
datacenterName := "MyDatacenter"
clusterName := "MyCluster"
folderName := "MyTestFolder"

finder := find.NewFinder(c.Client)

// Find Datacenter
datacenter, err := finder.DatacenterOrDefault(ctx, datacenterName)
if err != nil {
	fmt.Println(err)
}
fmt.Println(datacenter)

// Set Datacenter as root for Finder
finder.SetDatacenter(datacenter)

// Find Cluster
cluster, err := finder.DatastoreClusterOrDefault(ctx, clusterName) // returns error "datastore cluster 'MyCluster' not found
"
if err != nil {
	fmt.Println(err)
}
fmt.Println(cluster)

finder.FolderOrDefault(ctx, folderName)
// folder path is /MyDatacenter/vm/MyTestFolder

// folder.CreateVM(...)
```

**Comment by dougm** [comment]
@Borkason added an example in #2206 , can you review?

`ResourcePool` is required, but `HostSystem` is optional.

`DatastoreCluster` is for storage, you need to use a `ResourcePool` from a `ClusterComputeResource`.
