### ISSUE TITLE
What is the difference between govmomi and vsphere-automation-sdk-go?

### ISSUE THREAD

**Issue by Borkason** [vmware/govmomi#2183]
What is the difference between the govmomi sdk and the vsphere-automation-sdk-go sdk? The latter states that vSphere services will be added soon. Will that replace govmomi? Or is that an entirely different thing?

**Comment by dougm** [comment]
govmomi as a project is SOAP API client, REST API client, govc CLI, vcsim API simulator and toolbox guest tools framework.  vsphere-automation-sdk-go is only a REST API client, for VMC only as I understand.  Maybe it could replace or be an alternative to govmomi's REST API client someday, but I'm not aware of any plans for that.
