### ISSUE TITLE
How to search all vm machine for attached vmdk 

### ISSUE THREAD

**Issue by guylevran** [vmware/govmomi#2185]
What is the correct command to search all vm's on datacenter for attached vmdk and filter (grep) for specific vmdk object.
From reading user guide can i user **device.info** and maybe coorperate with **govc find**.
Thanks

**Comment by dougm** [comment]
Yes, you can do something like the following:

```bash
#!/bin/bash

IFS=$'\n'

for vm in $(govc find / -type m) ; do
  for vmdk in $(govc device.info -vm "$vm" -json 'disk-*' | jq -r .Devices[].Backing.FileName); do
    echo "$vm: $vmdk"
  done
done
```
