### ISSUE TITLE
How to find events and tasks associated with a VM still being created

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#2186]
When a VM is being created (few mins to hours), I would like to get  handle to the task that is creating/cloning the VM. I have the name of the VM (and it's datacenter, folder, etc.) and therefore I can find the ManagedObjectReference (MOR) to the VM. However, from the VM MOR, how do I locate the task that is cloning the VM?  Fundamentally, I want to check if the VM creation is still in progress or if it has completed. 

If the above is not possible, is it possible to get the events associated with a VM still being created and find out if the VM creation is complete? 

On a related note, how can one find out the state of the VM creation?  I know the powerstate is available but I don't see any info about the vm creation state itself. Is it possible to determine if the VM creation is still in progress or if it was completed (success or failure)?

Thanks
-k

**Comment by embano1** [comment]
Are you asking about `govc` or programmatically through the SDK? For example `func (v VirtualMachine) Clone(ctx context.Context, folder *Folder, name string, config types.VirtualMachineCloneSpec) (*Task, error) {...}` would give you a task you can track, e.g. via `func (t *Task) WaitForResult()`
