### ISSUE TITLE
not implemented for type mo.StoragePod

### ISSUE THREAD

**Issue by tomfuie** [vmware/govmomi#219]
What did I miss?

server> govc datastore.import kube.vmdk
panic: not implemented for type mo.StoragePod

goroutine 16 [running]:
runtime.panic(0xaa14c0, 0xc208001030)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
github.com/vmware/govmomi/list.ToElement(0x7fd7d1cfe880, 0xc208152540,
0xc208056520, 0x11, 0x0, 0x0, 0x0, 0x0)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/list/lister.go:59
+0x3a5
github.com/vmware/govmomi/list.Lister.ListFolder(0xc20811a000, 0xc208165288,
0x6, 0xc2081652b0, 0x9, 0xc208056520, 0x11, 0x0, 0x0, 0x0, ...)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/list/lister.go:173
+0x7a5
github.com/vmware/govmomi/list.Lister.List(0xc20811a000, 0xc208165288, 0x6,
0xc2081652b0, 0x9, 0xc208056520, 0x11, 0x0, 0x0, 0x0, ...)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/list/lister.go:94
+0x332
github.com/vmware/govmomi/list.Recurser.Recurse(0xc20811a000, 0x0,
0xc208056520, 0x11, 0x7fd7d1cfe768, 0xc20813aff0, 0xc2081618f0, 0x1, 0x1, 0x0,
...)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/list/recurser.go:63
+0x1d7
github.com/vmware/govmomi/find.(*Finder).list(0xc208160bc0, 0xc208179a48, 0x0,
0x7fff1b82adc1, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/find/finder.go:103
+0x44e
github.com/vmware/govmomi/find.(*Finder).find(0xc208160bc0, 0xc208179a48, 0x0,
0xc208179be8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/find/finder.go:55
+0x13c
github.com/vmware/govmomi/find.(*Finder).DatastoreList(0xc208160bc0,
0xc208179be8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/find/finder.go:246
+0xbb
github.com/vmware/govmomi/find.(*Finder).Datastore(0xc208160bc0,
0x7fff1b82adc1, 0xe, 0x0, 0x0, 0x0)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/find/finder.go:266
+0xb3
github.com/vmware/govmomi/govc/flags.(*DatastoreFlag).Datastore(0xc20800f2f0,
0xc20813aba0, 0x0, 0x0)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/govc/flags/datastore.
go:71
+0x103
github.com/vmware/govmomi/govc/importx.(*vmdk).Run(0xc2080ecec0, 0xc2080048a0,
0x0, 0x0)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/govc/importx/vmdk.go:
95
+0x33a
github.com/vmware/govmomi/govc/cli.Run(0xc20800e010, 0x2, 0x2, 0x7fd7d1cfc6e8)
	/home/tomtest/src/go/src/github.com/vmware/govmomi/govc/cli/command.go:1
60
+0x73f
main.main()
	/home/tomtest/src/go/src/github.com/vmware/govmomi/govc/main.go:48
+0x69

goroutine 19 [finalizer wait]:
runtime.park(0x412f10, 0x17d1fd8, 0x17d0209)
	/usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x17d1fd8, 0x17d0209)
	/usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 22 [runnable]:
net/http.(*persistConn).readLoop(0xc208048790)
	/usr/lib/golang/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/pkg/net/http/transport.go:600 +0x93f

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc208048790)
	/usr/lib/golang/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/pkg/net/http/transport.go:601 +0x957

**Comment by dougm** [comment]
I believe the fix for this is in PR #133 - but I think we were still waiting on a CLA from @mrbobbytables ?

**Comment by mrbobbytables** [comment]
I sent it off on 1/6/2015. I can resend if desired.

**Comment by dougm** [comment]
PR #133 has been merged, @tomfuie can you confirm this fixes for you?

**Comment by tomfuie** [comment]
Yes! Thank you.
