### ISSUE TITLE
govc.migrate error: ./govc: The operation is not supported on the object.

### ISSUE THREAD

**Issue by gxu12345** [vmware/govmomi#2192]
When trying to migrate a vm using govc vm.migrate, I got this error:
./govc: The operation is not supported on the object.
I am using Vsphere 7.

**Comment by dougm** [comment]
Can you capture the `-debug` output, is it may have more details: https://github.com/vmware/govmomi/tree/master/govc#troubleshooting

Or using `govc vm.migrate -xml ...`, output should be the vSphere  fault structure with any other details.

**Comment by gxu12345** [comment]
The -debug and -xml flag did nothing to output

./govc vm.migrate -xml=true -debug=true -ds 3B3_2EB test1
./govc: The operation is not supported on the object.

**Comment by dougm** [comment]
Please follow the doc link above, `-debug` saves to files by default.
