### ISSUE TITLE
govc guest.run execute fails with 'The operation is not allowed in the current state' and no other output

### ISSUE THREAD

**Issue by electrofelix** [vmware/govmomi#2193]
I'm currently trying to use `govc guest.run -vm=<vm> <script-file>` to execute a script after uploading it to the VM to perform some additional configuration after creating the VM from a clone using terraform. To do this I'm defining a couple of `local-exec` provisioner blocks to run after the resource is provisioned.

However I'm noticing that there are frequent failures when guest.run is used:
```
module.infra_vm.vsphere_virtual_machine.vm[0] (local-exec): Executing: ["/bin/sh" "-c" "govc guest.run -vm=my-test-vm /tmp/configuration.bash"]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [5m10s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [5m20s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [5m30s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [5m40s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [5m50s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [6m0s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [6m10s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [6m20s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [6m30s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [6m40s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [6m50s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [7m0s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [7m10s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [7m20s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [7m30s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [7m40s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [7m50s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [8m0s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [8m10s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [8m20s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [8m30s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [8m40s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [8m50s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [9m0s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [9m10s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0]: Still creating... [9m20s elapsed]
module.infra_vm.vsphere_virtual_machine.vm[0] (local-exec): 2020/11/30 17:04:37 rm "/tmp/vmware-<my-user>_432-1777711188/govmomi-vmware107": ServerFaultCode: The operation is not allowed in the current state.
```

I've had to sanitize some information here as this is occurring using systems for my employer.

I suspect the error message is coming from https://github.com/vmware/govmomi/blob/master/guest/toolbox/client.go#L72 or https://github.com/vmware/govmomi/blob/master/guest/toolbox/client.go#L111 when they execute on returning from that function, but as they don't impact the exit code and there isn't any of the expected output from the `guest.run` displayed I'm left a bit confused as to what is actually happening. It's almost like there is some small instability, and when it goes wrong, the stdout/stderr is lost.

Is the only option here to enable GOVC_DEBUG and try to reproduce?

**Comment by dougm** [comment]
Sounds like the VM has been created, but maybe vmware-tools isn't running yet?  You can wait for tools to be running with the following:

```console
% govc object.collect -s "$vm_path" -guest.toolsStatus toolsOk
```

We could also add this wait to `guest.run`.

**Comment by electrofelix** [comment]
@dougm sorry, off work for most of December, so only following up now. Would the vmware-tools not need to be running for the `govc guest.run ...` to have started successfully? It appears the error I saw appeared only at the end of the script that was executed had completed and `govc guest.run ...` was performing it's clean up after having completed execution.

Previously the code was simply sleeping before attempting this, I've since switched it to attempt `govc guest.run ... 'echo hello'` and checking the return code looking for >1 successful response before continuing. Might be able to switch to `-guest.toolsStatus` but it does seem a little odd to me that it's at the end of what was run by `guest.run` the issue was seen, but not at the start.

**Comment by dougm** [comment]
@electrofelix sorry I skimmed too quickly and didn't realize guest.run had started and the failure is at the end when cleaning up the tmp files.  If you can get the GOVC_DEBUG logs, it may shed more light on the "The operation is not allowed in the current state" error.  And/or the VM's vmware.log, you can get this using: `govc datastore.download vm-name/vmware.log -`

Anything else happening with the VM at the time?  Such as another guest operation, vmotion, etc. ?
You can check using `govc tasks vm/vm-name`
