### ISSUE TITLE
Get all Distributed Virtual Switch from a Datacenter

### ISSUE THREAD

**Issue by cjain85** [vmware/govmomi#2200]
I would like to get all the distributed virtual switches that exist in Datacenter and enable network I/O control on all of these  

Any examples/leads would be helpful

**Comment by dougm** [comment]
Using govc or API?

Sounds like [EnableNetworkResourceManagement](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.DistributedVirtualSwitch.html#enableNetworkResourceManagement) is the method you're looking for.

We have the generated API binding for that, but govc does not support it currently.
