### ISSUE TITLE
Unable to sso.user.* unless the user is "Administrator"

### ISSUE THREAD

**Issue by sh1dow3r** [vmware/govmomi#2202]
Only the user "Administrator" has the ability to do sso.user.* (list, create, id,... etc) 

I have a user with "administrator" privilege permission but get the error `govc: ServerFaultCode: NoPermission`  

Here is the output from the "administrator@vsphere.local"
`root$ govc sso.user.id`
`person=Administrator@vsphere.local groups=LicenseService.Administrators,SystemConfiguration.ReadOnly,SystemConfiguration.SupportUsers,Administrators,Everyone,CAAdmins,SystemConfiguration.Administrators,SystemConfiguration.BashShellAdministrators,Users`

Here is the output from the "DevOps@vsphere.local" which has the same privilege as an administrator
`root$ govc sso.user.id`
`govc: ServerFaultCode: NoPermission`

Here's a screenshot of the permission I have set for both users. 
![image](https://user-images.githubusercontent.com/29131514/101275232-1ac74b00-3772-11eb-9ea4-6e09512d820e.png)

**Comment by sh1dow3r** [comment]
This might be relevant to #1756  issue.

**Comment by sh1dow3r** [comment]
@vmwghbot /reopen

**Comment by sh1dow3r** [comment]
> This issue is stale because it has been open for 90 days with no
> activity. It will automatically close after 30 more days of
> inactivity. Reopen the issue with `/reopen`. Mark the issue as
> fresh by adding the comment `/remove-lifecycle stale`.

**Comment by ricardo-rod** [comment]
The same issue even on the latest version is still alive.

**Comment by sudeepms** [comment]
Hi ,
is there any solution for this issue ,am facing this issue with user have "administrator" privilege permission.

host-vm:~ # govc sso.user.ls -s -json
{
  "Fault": {
    "XMLName": {
      "Space": "http://schemas.xmlsoap.org/soap/envelope/",
      "Local": "Fault"
    },
    "Code": "ServerFaultCode",
    "String": "",
    "Detail": {
      "Fault": {
        "FaultCause": null,
        "FaultMessage": null,
        "Object": {
          "Type": "",
          "Value": ""
        },
        "PrivilegeId": ""
      }
    }
  }
}

**Comment by ak-hpe** [comment]
in my case , user was having admin role but it was not part of Administrator group , after the user  administrator group issue resolved

**Comment by mkohalli** [comment]
In my case , i see that the it gives the error ServerFaultCode: NoPermission for ent_admin@vsphere.local user who is part of the EnterpriseAdmins group for the FindParentGroups API

**Comment by mkohalli** [comment]
@dougm : Is this a known issue or the expected behaviour ?. bascially i was trying to get the groups for the user [ent_admin@vsphere.local] user who is part of the EnterpriseAdmins group.Can you please answer this ?
