### ISSUE TITLE
ISO is not connected at startup

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2203]
I created a cdrom and inserted an ISO into it then, added a VirtualDeviceConfigSpec with Add operation to my vm template clone, however I see that the ISO is not connected after starting up. I saw the below code for CreateCdrom shows it should be connected at startup. Is there some condition under which this changes?

When I tried to manually connect the cd drive, I got a `connection control operation failed for ide0:0` error
```
// CreateCdrom creates a new VirtualCdrom device which can be added to a VM.                                                                                                       
func (l VirtualDeviceList) CreateCdrom(c *types.VirtualIDEController) (*types.VirtualCdrom, error) {
        device := &types.VirtualCdrom{}

        l.AssignController(device, c)

        l.setDefaultCdromBacking(device)

	device.Connectable = &types.VirtualDeviceConnectInfo{
                AllowGuestControl: true,
                Connected:         true,
                StartConnected:    true,
        }

        return device, nil
}
```

**Comment by dougm** [comment]
Not sure, but sounds similar to #2094 , are there any pending questions for the vm?

**Comment by chardch** [comment]
Found that the issue was due to a missing file extension in the iso file name. Was thrown off by the error message.
