### ISSUE TITLE
Unable to Increase Datastore Capacity

### ISSUE THREAD

**Issue by merttokgozoglu** [vmware/govmomi#2204]
There is not method for increasing datastore capacity.
Govmomi allows us to create, attach datastores to clusters or hosts but there is no method for increasing datastore capacity.
VMware does that with the following screens:
![image](https://user-images.githubusercontent.com/9316417/101883222-033ff600-3ba8-11eb-9ff7-66b80df0e651.png)

**Comment by dougm** [comment]
I don't know what method the UI uses for this, are you able to find the API here? https://code.vmware.com/apis/968/vsphere

It might be [ExtendVmfsDatastore](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.host.DatastoreSystem.html#extendVmfsDatastore), but I haven't looked into it yet
