### ISSUE TITLE
Can not attach dependant disk to VM

### ISSUE THREAD

**Issue by tjguthrie4600** [vmware/govmomi#2209]
When I use this command
vm.disk.attach -ds $VOLUME -vm $VM -disk $DISK

The disk always gets attached as an Independent Persistent disk, I can not find an option to attach a disk in Dependent mode. When the disk gets attached two new vmdks are created  _1-sesparse.vmdk and _1.vmdk are created. Please add an option to attach a disk in dependent mode without creating these two additional VMDKs.

**Comment by dougm** [comment]
Have you tried the `-mode` flag? https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmdiskattach

**Comment by tjguthrie4600** [comment]
I tried these modes:
persistent
nonpersistent
undoable
independent_persistent
independent_nonpersistent
append

The mode flag seems to be ignored, every attach results in the sesparse disks getting created and the mode in VMware 6.5 shows "Independant-Persistant". I am trying to get the disk attached as Dependent and without the sesparse disks being created.

**Comment by dougm** [comment]
How was your $DISK created, before attaching to the VM?

Note from `govc vm.disk.attach -help`:

> A delta disk is created by default, where changes are persisted. Specifying '-link=false' will persist to the same disk.

The delta disk(s) appear as separate vmdk files, so you may want to use `-link=false`.

Can you reproduce the sesparse behavior when creating the disk using `datastore.disk.create` ?  For example:

```console
% govc vm.create -on=false vm1

% govc datastore.disk.create -size 10M vm1/disk1.vmdk

% govc datastore.ls vm1/*.vmdk
disk1.vmdk

% govc vm.disk.attach -link=false -vm vm1 -disk vm1/disk1.vmdk

% govc device.info -json -vm vm1 disk-* | jq -r .Devices[].Backing.DiskMode
persistent

% govc vm.disk.change -vm vm1 -mode nonpersistent disk-*

% govc device.info -json -vm vm1 disk-* | jq -r .Devices[].Backing.DiskMode
nonpersistent
```

sesparse is also a disk backing type, rather than mode.  So if the disk was originally in sesparse format, I don't think the attach mode will change that.   What does the device backing look like for your $DISK?  In the case above:
```console
% govc device.info -xml -vm vm1 disk-*
...
    <backing xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="VirtualDiskFlatVer2BackingInfo">
      <fileName>[vsanDatastore] c0850c60-a85c-ab8a-423f-0200afa6daa7/disk1.vmdk</fileName>
      <datastore type="Datastore">datastore-35</datastore>
      <backingObjectId>ca850c60-66ad-1684-0fef-0200afffda4e</backingObjectId>
      <diskMode>nonpersistent</diskMode>
      <split>false</split>
      <writeThrough>false</writeThrough>
      <thinProvisioned>true</thinProvisioned>
      <uuid>6000C291-a4c9-2225-082e-3d0a8bb97bac</uuid>
      <contentId>67fa488d1a7f26a3cf8fbb55fffffffe</contentId>
      <digestEnabled>false</digestEnabled>
      <sharing>sharingNone</sharing>
    </backing>
...
```

**Comment by mrambossek** [comment]
sorry to re-heat old topics but i have the exact same problem now

i tried following the suggested steps, but when i do
`./govc vm.disk.attach -vm "MY VM"  -link=false -mode dependent -disk /_persistent_disks/MY_VM.data.vmdk`
i get
`/govc: Incompatible device backing specified for device '0'.`

if i remove the link=false, it works - but the disk will be independent_persistent, as confirmed via device.info, ie the -mode is ignored.

**Comment by mrambossek** [comment]
... aaand i think i found the solution.
if you specify -link=false, you MUST NOT also use -mode. as soon as i removed it, it worked fine:
```
# ./govc vm.disk.attach -vm "MY VM"  -link=false -disk /_persistent_disks/MY_VM.data.vmdk

#./govc device.info -json -vm "MY VM" disk-* |jq -r '.devices[].backing.diskMode'
persistent
persistent
persistent
persistent
```
