### ISSUE TITLE
device.info generates massive amount of requests

### ISSUE THREAD

**Issue by lukasluecke** [vmware/govmomi#2212]
A single `device.info` call (with the VM name as the `-vm` parameter) seems to generate 1653 requests, which take about 2-3 minutes to complete. We have a pretty big cluster with 5 nodes and about 3500 VMs, but this still seems excessive.

Any ideas what causes this, and if there's a way around it? 😅 I can provide the detailed logs if required.

**Comment by lukasluecke** [comment]
Using `find` first and then passing the full path to `device.info` seems to bypass this.

**Comment by lukasluecke** [comment]
Same behaviour for `vm.clone` and possibly other commands.

**Comment by lukasluecke** [comment]
Is this something that could be caused on the vCenter side of things? We upgraded to 7.0 not too long ago, maybe that's related?

**Comment by dougm** [comment]
1653 requests, wow, how did you determine that?  Using an absolute inventory path will be faster, as it avoids recursing into folders.  Are the 3500 VMs in different sub-folders?

**Comment by lukasluecke** [comment]
Running the command with `--debug` generated 1653 req/res dumps 😅

Yes, most of them are in separate sub-folders (mostly in sets of 1-5 VMs). What I don't get is why `find` doesn't have the same problem, I assumed the lookup logic would be identical or similar.

**Comment by dougm** [comment]
Most of the govc commands use the [Finder](https://godoc.org/github.com/vmware/govmomi/find), see the doc on "ls" and "find" modes.  The latter will generate more requests when recursing into subfolders.

The govc `find` command does not actually use Finder, it uses a [ContainerView](https://godoc.org/github.com/vmware/govmomi/view).

ContainerView is less requests, but generates more response data.  I think we could change Finder to use ContainerView for "find" mode to speed things up.
