### ISSUE TITLE
Cannot remove expiring eval license

### ISSUE THREAD

**Issue by aram535** [vmware/govmomi#2213]
ESXi 7.0.1.1
govc machine (External to ESXi) CentOS 8.2 [64-bit]
go version go1.13.15 linux/amd64
```
$ govc version 
govc 0.23.0
$ govc license.ls
Key:                           Edition:                                  Used:  Total:
00000-00000-00000-00000-00000  eval                                      0      0   
99999-99999-99999-99999-99999  vc.standard.instance                      0      2   
99999-99999-99999-99999-99998   esx.enterprisePlus.cpuPackageCoreLimited  2      16 
$ govc license.remove -key=00000-00000-00000-00000-00000
$ govc license.ls
Key:                           Edition:                                  Used:  Total:
00000-00000-00000-00000-00000  eval                                      0      0   
99999-99999-99999-99999-99999  vc.standard.instance                      0      2   
99999-99999-99999-99999-99998   esx.enterprisePlus.cpuPackageCoreLimited  2      16 
```

**Comment by dougm** [comment]
Might be that vCenter only allows you to replace, not remove the eval license. Are you able to remove it using the web UI?

**Comment by aram535** [comment]
No, doesn't even give me the option to remove it via the GUI.  I'm ok with the answer that you can't remove the only eval license, but the catch is that the "actual" license has been applied, yet the system continues to give me a header warning on each browser session that I have a license that is about to expire.

**Comment by dougm** [comment]
Sounds like that's the case, eval license can't be removed.  Your `vc.standard.instance` license doesn't look like it's being used?  Have you assigned that license?  For example, this script assigns licenses to ESX hosts and vCenter itself: https://github.com/vmware/govmomi/blob/master/scripts/vcsa/assign-licenses.sh#L22

**Comment by aram535** [comment]
Yes, the real license is assigned.  Very odd.  I guess I'll wait until mid-Jan to see what happens when the temp one expires.
I guess my issue note here is that if the license can't be removed govc should return an error rather than a success, right now the return code is 0 and no STDOUT/ERR is produced.  I guess I expected one or the other to show that the task couldn't be completed.

**Comment by dougm** [comment]
govc is just using the API, which does not return an error when attempting to remove the eval license.  I don't know why the API behaves this way.  Sure, we could hardcode something into govc, but not sure how useful that'd be.
What is the GUI's behavior when trying to remove the eval license?

**Comment by aram535** [comment]
Odd. An error saying license cannot be removed.
