### ISSUE TITLE
Arranging CI for gollvm

### ISSUE THREAD

**Issue by advancedwebdeveloper** [vmware/govmomi#2218]
Merry Christmas, everybody.

Opening the issue for discussing support for https://go.googlesource.com/gollvm/

**Comment by dougm** [comment]
Merry Christmas Ivan.  Can you expand on this?  Is it just testing that govc compiles with gollvm in CI or are you suggesting the release binaries should be build with gollvm?

**Comment by advancedwebdeveloper** [comment]
@dougm , I am suggesting both.
Pinged you on Slack.

**Comment by dougm** [comment]
I've only heard of gollvm, but have never used it or read about it in detail.
What are the benefits of using gollvm instead of the standard Go compiler for govc?  And downsides?

**Comment by advancedwebdeveloper** [comment]
I only see an obvious advantage in a clear way to offer cross-platform support, via LLVM's back-ends.
You can consider security improvements via LLVM's sanitizers and Clang's support, from the side of hardware vendors.

**Comment by dougm** [comment]
Which platforms that aren't already supported where folks would run govc?
Any specific security improvements that would benefit govc?
