### ISSUE TITLE
NSX-T Opaque Network caveats 

### ISSUE THREAD

**Issue by mooperd** [vmware/govmomi#2221]
Hello,

From an API perspective - what are the differences between vSphere managed networks and nsx-t managed "Opaque Networks". From the govmomi perspective can we attach VMs to Opaque Networks or is there some funny business required? I'm struggling to find concrete information.

Cheers,

Andrew

**Comment by dougm** [comment]
govmomi provides a [NetworkReference](https://godoc.org/github.com/vmware/govmomi/object#NetworkReference) abstraction, with an `EthernetCardBackingInfo` method that can be used to attach VM NICs to any type of network. Adding a new example in #2223 , can you take a look?
