### ISSUE TITLE
PowerCLI fails to create new/clone VM with vcsim - Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by lamw** [vmware/govmomi#2228]
> Description

When attempting to create a new or clone VM using vcsim and the following recording https://github.com/lamw/govc-recordings/tree/master/vcsim-vcsa.primp-industries.local using PowerCLI, the following error is thrown:

_New-VM		Value cannot be null. (Parameter 'source')_

Here is the exact PowerCLI command used:

```code
Connect-VIServer -Server localhost -Port 8989 -User Foo -Password Bar
New-VM -Name Test -VMHost (Get-VMhost 192.168.30.5)
```

I was not able to see anything in particular when looking at the stack trace but I suspect some default value must not be working with vcsim

```code
> $Error[0].Exception.InnerException
Message        : Value cannot be null. (Parameter 'source')
ParamName      : source
TargetSite     : Void ThrowArgumentNullException(System.Linq.ExceptionArgument)
StackTrace     :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
                    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
                    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
                    at VMware.VimAutomation.ViCore.Impl.V1.Service.VmServiceImpl.NewVM(VMHostInterop vmHost, String name, VIContainerInterop resourceContainer, FolderInterop location,
                 StorageResourceInterop datastore, Int64[] diskSizes, String[] diskPaths, Nullable`1 diskStorageFormat, Int64 memorySize, Int32 cpuCount, Int32 coresPerSocket, Boolean
                 hasFloppy, Boolean hasCD, String guestId, String alternateGuestName, String[] networks, OSCustomizationSpecInterop customization, Boolean allowNested, Boolean
                 isRequestedAsync, String description, Nullable`1 haRestartPriority, Nullable`1 haIsolationResponse, Nullable`1 drsAutomationLevel, Nullable`1 vmSwapfilePolicy, String
                 hardwareVersion, AdvancedOption[] options, IList`1 portgroups, StoragePolicyInterop storagePolicy, ReplicationGroupInterop replicationGroup, KmsClusterInterop kmsCluster,
                 SwitchParameter skipHardDisks, Nullable`1 sevEnabled)
                    at VMware.VimAutomation.ViCore.Impl.V1.Service.VmServiceImpl.NewVM(NewVmParameters parameters)
                    at VMware.VimAutomation.ViCore.Cmdlets.Commands.NewVM.DoWork(VIAutomation client, List`1 moList)
                    at VMware.VimAutomation.ViCore.Util10Ps.BaseCmdlet.BaseCmdlet.DoWork(VIConnection connection, List`1 moList)
                    at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.BaseCmdlet.DoWorkEx(VIConnection connection, List`1 moList)
                    at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ConnectionDispatchHelper.ExecuteRunlist(Dictionary`2 runlist, DoWorkDelegate doWorkDelegate, UidDispatchHelper
                 uidDispatchHelper, List`1 result)
Data           : {ConnectionId}
InnerException :
HelpLink       :
Source         : System.Linq
HResult        : -2147467261
```

The above command works fine with the real environment in which the recording was captured from

**Comment by dougm** [comment]
vcsim records/replays the inventory and all object properties, but here the missing data was the return of a method call, `EnvironmentBrowser.QueryConfigOption`

We have to take an extra step to record such data.. with #2229 you'll see the following after running `govc object.save`:

```console
% ls EnvironmentBrowser-envbrowser-*/
QueryConfigOption.xml
```

`vcsim -load` will use that to respond to `EnvironmentBrowser.QueryConfigOption` and the `New-VM` command above will succeed.

**Comment by lamw** [comment]
I'm having some trouble verifying this, I cloned the branch `issue-2228` and ran `go install github.com/vmware/govmomi/govc` but  I don't see the EnvironmentalBrowser-* directory after running object.save

**Comment by dougm** [comment]
What git commands did you use?  Can you verify the source change is there?
```console
% grep EnvironmentBrowser govc/object/save.go 
func saveEnvironmentBrowser(ctx context.Context, c *vim25.Client, ref types.ManagedObjectReference) ([]saveMethod, error) {
        "EnvironmentBrowser":             saveEnvironmentBrowser,
                        {Type: "EnvironmentBrowser", All: all},
```

And `make install` will build/install both govc and vcsim to `$GOPATH/bin`.

You may also need to either remove the existing recording directory or use the `govc object.save -f` flag.

**Comment by dougm** [comment]
Just noticed:
> I don't see the EnvironmentalBrowser-* directory 

s/Environmental/Environment/

If that isn't it, note that for `go install github.com/vmware/govmomi/govc` to work, you'd have to have the branch checked out in `$GOPATH/src/github.com/vmware/govmomi`.
But if you happened to clone the repo elsewhere, you'd need to use `make install` or `(cd govc && go install)`
