### ISSUE TITLE
Proposal: finder.ThisVM

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#223]
Return a govmomi.VirtualMachine for the machine making the call, if a VM.

This presumably either has a dependency on vmtools (open or otherwise) being available, or on govmomi integrating sufficient of the rpc backdoor code to inspect the VMX details for the VM.

**Comment by dougm** [comment]
The guestinfo mechanism can be used for this, but something needs to set a guestinfo.key=val pair that has the info you want to see from inside the guest.  This can be done by setting VirtualMachine.Config.ExtraConfig via govmomi.  Inside the VM guest you can use vmware-rpctool or this package: https://github.com/sigma/vmw-guestinfo

So I think everything you need for this is already in place.

**Comment by dougm** [comment]
Talked to @hickeng - agreed not much else we can do here.
