### ISSUE TITLE
Unable to run vcsim on Windows

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/govmomi#2231]
When attempting to run vcsim on Windows, the OS throws an error stating that the directory name is invalid. It is attempting to create a temp folder C:\Users\username\AppData\Local\Temp\govsim-_vmfs_volumes-vsan:{UUID}: 

Windows does not allow folder names to contain a colon.

I thought maybe this was just related to running this in MINGW64 but the error persists in PowerShell and a plain command window.

![image](https://user-images.githubusercontent.com/29929717/103950620-d1687380-5102-11eb-9e94-1b3cffc30547.png)

**Comment by dougm** [comment]
#2232 should fix that
