### ISSUE TITLE
vcsim has support for vsan endpoints

### ISSUE THREAD

**Issue by agllno** [vmware/govmomi#2235]
Does the vcsim have support for vsan endpoints like VsanHelthPort, Pbmport and VsanPerfQuery?

If yes, then we can use replay capabilities to capture these data?

**Comment by agllno** [comment]
Any update on this?

**Comment by dougm** [comment]
vcsim does not have support for vsan endpoints currently, other than cns:
https://github.com/vmware/govmomi/blob/master/cns/simulator/simulator.go

Not sure if anyone's looked at implementing it yet, cc @gh05tn0va @divyenpatel @SandeepPissay

**Comment by dougm** [comment]
We don't support those currently, and I don't any experience with them.  If you could provide more details such as API doc links, client usage examples (in any language), etc., that may help.
