### ISSUE TITLE
Find the group to which the user belongs

### ISSUE THREAD

**Issue by santoshbalaraj** [vmware/govmomi#2238]
We have a use case wherein we need to check if the logged in user belong to an administrator group within the vCenter. 
If there any API which can return the information of user, the information is mainly on the group, roles etc. 

I have checked the retrieveUserGroups API but that does not tell whether user belongs to a particular group.

Can I please get some pointers in getting the information of the logged in users.

**Comment by dougm** [comment]
[retrieveUserGroups](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.UserDirectory.html#retrieveUserGroups) is only for ESX, not vCenter.

This might be what you're looking for, from the govc `sso.user.id` command: https://github.com/vmware/govmomi/blob/master/govc/sso/user/id.go#L108
