### ISSUE TITLE
Unable to delete some CNS volumes

### ISSUE THREAD

**Issue by tgelter** [vmware/govmomi#2239]
Firstly, thanks for the addition of the `volume` commands!

We have a couple of left-over CNS volumes from testing which we're unable to delete using `govc volume.rm` as shown below:
```
❯ govc volume.ls
5b9a0106-b0d2-48f7-9d8e-3dda1a880744	pvc-9b91d025-02ef-49d3-b210-dc55c7375999
463c34d9-888f-496f-ae1d-208b8103cadd	pvc-d9bb3136-381f-43fd-abed-640319354ca2
3159f356-5bbd-45cb-a2cf-361ffc11edc2	pvc-76642aff-ee40-479b-ae4b-1157f2144a48

❯ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                   STORAGECLASS    REASON   AGE
pvc-9b91d025-02ef-49d3-b210-dc55c7375999   1Gi        RWO            Delete           Bound    menagerie/vsphere-block-storage-class   vsphere-block            28m

❯ govc volume.rm pvc-d9bb3136-381f-43fd-abed-640319354ca2 
govc: ServerFaultCode: Received SOAP response fault from [<cs p:00007fb178007c60, TCP:localhost:443>]: retrieveVStorageObject
InvalidArgument: pvc-d9bb3136-381f-43fd-abed-640319354ca2 is incorrectly formatted.

❯ govc volume.rm pvc-76642aff-ee40-479b-ae4b-1157f2144a48
govc: ServerFaultCode: Received SOAP response fault from [<cs p:00007fb178007c60, TCP:localhost:443>]: retrieveVStorageObject
InvalidArgument: pvc-76642aff-ee40-479b-ae4b-1157f2144a48 is incorrectly formatted.
```

`govc` version: v0.24.0
vCenter version: 6.7 U3
vSphere version: 6.7 U3
Datastore type: FC SAN
vSphere CSI Version: v2.1.0 (previous clusters deleted before volumes cleaned up)

Please let me know if there's any additional information I can provide. Thanks!

**Comment by dougm** [comment]
Hi @tgelter , you just need to use the volume ID instead of the NAME:
```console
% govc volume.rm -h
Usage: govc volume.rm [OPTIONS] ID

Remove CNS volume.

Examples:
  govc volume.rm f75989dc-95b9-4db7-af96-8583f24bc59d
  govc volume.rm $(govc volume.ls -i pvc-de368f19-a997-4d5d-9eae-4496f10f429a)
```

In your case for example:
```console
  govc volume.rm 5b9a0106-b0d2-48f7-9d8e-3dda1a880744
  # or
  govc volume.rm $(govc volume.ls -i pvc-9b91d025-02ef-49d3-b210-dc55c7375999)
```

**Comment by tgelter** [comment]
@dougm thanks for the response, and apologies for providing the wrong output, but it actually doesn't matter whether I use the volume ID or NAME, the result is the same:
```
❯ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                   STORAGECLASS    REASON   AGE
pvc-9b91d025-02ef-49d3-b210-dc55c7375999   1Gi        RWO            Delete           Bound    menagerie/vsphere-block-storage-class   vsphere-block            16h

❯ govc volume.ls
5b9a0106-b0d2-48f7-9d8e-3dda1a880744	pvc-9b91d025-02ef-49d3-b210-dc55c7375999
463c34d9-888f-496f-ae1d-208b8103cadd	pvc-d9bb3136-381f-43fd-abed-640319354ca2
3159f356-5bbd-45cb-a2cf-361ffc11edc2	pvc-76642aff-ee40-479b-ae4b-1157f2144a48

❯ for volume_id in 463c34d9-888f-496f-ae1d-208b8103cadd 3159f356-5bbd-45cb-a2cf-361ffc11edc2; do govc volume.rm $volume_id; done
govc: ServerFaultCode: Received SOAP response fault from [<cs p:00007fb178007c60, TCP:localhost:443>]: retrieveVStorageObject
The object or item referred to could not be found.
govc: ServerFaultCode: Received SOAP response fault from [<cs p:00007fb178007c60, TCP:localhost:443>]: retrieveVStorageObject
The object or item referred to could not be found.
```
Here's the vSphere view:
![image](https://user-images.githubusercontent.com/2048618/104480751-20d6f580-5582-11eb-8ad1-6011907ae712.png)

Please let me know if I can provide any other useful information.
Thanks again!

**Comment by dougm** [comment]
I haven't seen that before, maybe @divyenpatel or @SandeepPissay has some ideas?

The command using the `DeleteVolume` method: https://github.com/vmware/govmomi/blob/50c576d6470e7ab9803ceb466ac34f936971dfc1/govc/volume/rm.go#L68-L70

**Comment by dougm** [comment]
Maybe the disk backing has been removed already, wonder if it would work for you with changing the `deleteDisk` param:
```diff
modified   govc/volume/rm.go
@@ -67,7 +67,7 @@ func (cmd *rm) Run(ctx context.Context, f *flag.FlagSet) error {
 
 	ids := []types.CnsVolumeId{{Id: f.Arg(0)}}
 
-	task, err := c.DeleteVolume(ctx, ids, true)
+	task, err := c.DeleteVolume(ctx, ids, false)
 	if err != nil {
 		return err
 	}
```

We could make `deleteDisk` a command option at least.  Might also be able to query for the disk backing within the command and toggle deleteDisk if the disk doesn't exist.

**Comment by SandeepPissay** [comment]
This sounds like the volume either is not present on the datastore or the FCD is not aware of it's presence.  @tgelter are you sure if those volumes are there on the datastore? You may want to use govc command that invokes FCD API on vpxd service to know that. @dougm does `govc disk.*` invoke FCD APIs on vpxd or FCD APIs on vmware-sps service?

**Comment by tgelter** [comment]
@dougm I've attempted the change you requested with no success:
```
❯ git diff
diff --git a/govc/volume/rm.go b/govc/volume/rm.go
index d5e9b607..0e62f7a9 100644
--- a/govc/volume/rm.go
+++ b/govc/volume/rm.go
@@ -20,6 +20,7 @@ import (
        "context"
        "errors"
        "flag"
+       "fmt"
 
        "github.com/vmware/govmomi/cns"
        "github.com/vmware/govmomi/cns/types"
@@ -67,7 +68,8 @@ func (cmd *rm) Run(ctx context.Context, f *flag.FlagSet) error {
 
        ids := []types.CnsVolumeId{{Id: f.Arg(0)}}
 
-       task, err := c.DeleteVolume(ctx, ids, true)
+       fmt.Println("Running c.DeleteVolume() with args: ctx, ids, false...")
+       task, err := c.DeleteVolume(ctx, ids, false)
        if err != nil {
                return err
        }

❯ ~/go/bin/govc volume.rm 463c34d9-888f-496f-ae1d-208b8103cadd
Running c.DeleteVolume() with args: ctx, ids, false...
/home/tgelter/go/bin/govc: ServerFaultCode: Received SOAP response fault from [<cs p:00007fb178007c60, TCP:localhost:443>]: retrieveVStorageObject
The object or item referred to could not be found.
```

@SandeepPissay would you please provide clarification as to what you'd like me to try? FYI, the deletion worked OK with other orphaned volumes, so I don't think there's any issue with the FCD APIs, but I suspect you're correct that there's some sort of issue with what's expected to be present when attempting a volume deletion, versus the state of my storage, a case which in my opinion should be accounted for by `govc`. To that end, I'm happy to be your tester since I'm the first one to find this edge case. :-)

**Comment by dougm** [comment]
`govc disk.*` talks to vpxd. Don't think I've heard of the vmware-sps service.

You can use the volume.ls `-L` flag to output the disk backing and use that as input to `disk.ls` to check for the FCD:
```
govc disk.ls -l $(govc volume.ls -L pvc-9744a4ff-07f4-43c4-b8ed-48ea7a528734)
```

**Comment by tgelter** [comment]
The issue was resolved on my side.
Note the output below:
```
❯ for ds_name in $(govc datastore.info | awk '/Name/ {print $2}'); do govc disk.ls -ds=$ds_name | egrep "(463c34d9-888f-496f-ae1d-208b8103cadd|3159f356-5bbd-45cb-a2cf-361ffc11edc2)"; done
govc: 463c34d9-888f-496f-ae1d-208b8103cadd not found: use 'disk.ls -R' to reconcile datastore inventory
govc: 0e73c61b-d635-4096-ab6f-65ab469e4a5f not found: use 'disk.ls -R' to reconcile datastore inventory
govc: 45751104-7fb0-43a1-9207-541a3be984a1 not found: use 'disk.ls -R' to reconcile datastore inventory
```
I followed up that command with the following:
```
❯ for ds_name in $(govc datastore.info | awk '/Name/ {print $2}'); do govc disk.ls -ds=$ds_name -R; done
```
Afterward, only the expected volume is present when I run `govc volume.ls`:
```
❯ govc volume.ls
5b9a0106-b0d2-48f7-9d8e-3dda1a880744	pvc-9b91d025-02ef-49d3-b210-dc55c7375999
```
Likewise, only the expected volume is present in the vSphere UI.

Would you agree that rather than outputting a raw SOAP error as shown in the issue description, the case should be caught and a recommendation to run datastore inventory reconciliation?

Thanks again!

**Comment by macgaver** [comment]
Same here. Success ! One command fixed all of them.

k8s@IPSvc:~> ./govc_linux_amd64 disk.ls -ds=NFS-Bronze
./govc_linux_amd64: 11dcd80d-ef1d-4f59-b3b4-aa73ce79e57b not found: use 'disk.ls -R' to reconcile datastore inventory

k8s@IPSvc:~> **./govc_linux_amd64 disk.ls -ds=NFS-Bronze -R**

**Comment by dougm** [comment]
Good to hear `disk.ls -R` solved the problem. I wasn't able to reproduce the same error.  I created a PVC and removed the backing disk with `govc disk.rm`, and also ssh'd into an ESX host and rm'd. But both resulted in different errors from what you saw.  Let's just add a mention `disk.ls -R` in the volume.rm doc for now.
