### ISSUE TITLE
govc object.save missing tags, categories, storage policies

### ISSUE THREAD

**Issue by Satak** [vmware/govmomi#2244]
I saved my vCenter (7.0.1) config with govc (v0.24.0) object.save and I'm running it in vcsim (latest) but it seems it didn't save:

- **tags**
- **tag categories**
- **storage policies**

Terraform is complaining that those are missing and I can't seem to find any XML for tags, categories or storage policies

```
Error: no pbm profile found with name: "A-S1_A"
  on main.tf line 12, in data "vsphere_storage_policy" "policy":
  12: data "vsphere_storage_policy" "policy" {
```

```
Error: category name "VM_FLAVOR" not found
  on main.tf line 38, in data "vsphere_tag_category" "category":
  38: data "vsphere_tag_category" "category" {
```

Also run to this problem again with Terraform though the VirtualMachine-vm XML has it `<guestId>windows9Server64Guest</guestId>`:

```
Error: cannot find OS family for guest ID "windows9Server64Guest": ServerFaultCode: The object has already been deleted or has not been completely created
```

I wonder if govc object.save supports saving those resources or if I am missing access rights to pull that data. object.save got a lot of xml files like port groups, resource pools, vms, datastores, folders, etc.

**Comment by dougm** [comment]
Currently, `object.save` only includes the vim25 API endpoint (`/sdk`).  We need to add code specific to the other APIs to save that data, such as `/pbm` and `/rest`.. which is possible, but just hasn't been implemented yet.

**Comment by Satak** [comment]
> Currently, `object.save` only includes the vim25 API endpoint (`/sdk`). We need to add code specific to the other APIs to save that data, such as `/pbm` and `/rest`.. which is possible, but just hasn't been implemented yet.

Got it. Why this error though `Error: cannot find OS family for guest ID "windows9Server64Guest": ServerFaultCode: The object has already been deleted or has not been completely created`? Though that was fixed in the latest vcsim? TF provisioning worked for the default vCenter config that comes with the vcsim but not to my vCenter clone.

**Comment by dougm** [comment]
Any chance you could provide a way to reproduce this one too?  Sounds like a TF call to EnvironmentBrowser `QueryConfigOption` or `QueryConfigOptionEx`, which object.save does support, but we could be missing something here.

**Comment by Satak** [comment]
I saved the vCenter config with govc which had vm templates in it. Then I referenced my guest_id to those templates that were discovered by it from Terraform like before.
