### ISSUE TITLE
govc cli command to set CPU affinity for VM on ESXI?

### ISSUE THREAD

**Issue by kbrv37** [vmware/govmomi#2246]
Is there a govc command to set the CPU affinity (i.e. cpus 4 through 8) for a specific VM on the ESXI? I looked through the usage API but could not find it:
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md

![image](https://user-images.githubusercontent.com/63459738/104998613-26549580-59f1-11eb-9def-3be077e43b15.png)

**Comment by dougm** [comment]
There isn't but we could add a `-cpu-affinity` flag to `vm.change`

**Comment by ciroiriarte** [comment]
Can we reopen this?. A "get" and "set" action would be very much appreciated.

/remove-lifecycle stale
