### ISSUE TITLE
govc markasvm command fails when you input the data as per the help

### ISSUE THREAD

**Issue by chris-milsted** [vmware/govmomi#2247]
When trying to mark a template as a VM it fails unless the vmname is at the end of the command as below:

$ govc vm.markasvm cluster-api-vm-1 -host (hostname-redacted)
govc: vm '(hostname-redacted)' not found

Swap the arguments around and put -host first and vmname last and it works

$ govc vm.markasvm -host (hostname-redacted) cluster-api-vm-1

Compare that to the help page:

govc vm.markasvm cluster-api-vm-1
Usage: govc vm.markasvm [OPTIONS] VM...

Mark VM template as a virtual machine.

Examples:
  **govc vm.markasvm $name -host host1**
  govc vm.markasvm $name -pool cluster1/Resources

The example has $name first and then the -host argument which as above fails.

$ govc version
govc v0.24.0

Running on Linux.

**Comment by dougm** [comment]
We need to fix those examples.  With Go's flag parser, the flags must be specified before the non-flag arguments. For example:
```
govc vm.markasvm  -host (hostname-redacted) cluster-api-vm-1
```
