### ISSUE TITLE
how to get the VM list of ESXI

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2252]
can anyone give me some hint

**Comment by atc0005** [comment]
@leoxucn822 

This was the first (unofficial) example I started with:

https://github.com/chrisgreene/govmomi-examples/blob/master/list-vms.go

In addition to the finder, you can also use a view to fetch properties for objects.

Here are some official examples:

https://github.com/vmware/govmomi/tree/master/examples

The `virtualmachines` example uses a view. This makes for a good contrast against the unofficial example's use of the finder approach. In short (from a newcomer's perspective), the view tends to give easy access to read-only properties, the finder gives objects with actionable methods to affect change.

---

While going through the examples, you'll likely want to have several references at hand:

- [vSphere Web Services API](https://code.vmware.com/apis/1067/vsphere) (select your version of ESXi / vSphere from the drop-down)
- https://pkg.go.dev/github.com/vmware/govmomi
- https://github.com/vmware/govmomi/tree/master/examples (repeat of earlier link)
-  [vSphere Management SDK](https://code.vmware.com/web/sdk/7.0/vsphere-management)
    - [vSphere Web Services SDK Programming Guide](https://code.vmware.com/docs/12643/vsphere-web-services-sdk-programming-guide--7-0-update-1-) (a PDF is always available)

**Comment by leoxucn822** [comment]
@atc0005 I tried to get read the source code, but no more comments in the code which makes me read difficult. I tried to use the view to get the containerview object, but I failed to output the VM. the official is the datacenter which isn't ok, because maybe in the same datacenter, there maybe multiple clusters with different ESXI,

**Comment by leoxucn822** [comment]
here is my code:

package gethosts

import (
	"context"
	"fmt"
	"github.com/vmware/govmomi/examples"
	"github.com/vmware/govmomi/find"
	"github.com/vmware/govmomi/property"
	"github.com/vmware/govmomi/vim25"
	"github.com/vmware/govmomi/vim25/mo"

)

func Vmlist(c *vim25.Client, hostname string)  {
	examples.Run(func(ctx context.Context, c *vim25.Client) error {
		pc := property.DefaultCollector(c)
		obj, err := find.NewFinder(c).HostSystem(ctx, hostname)
		if err != nil {
			return err
		}

		var host mo.HostSystem
		err = pc.RetrieveOne(ctx, obj.Reference(), []string{"vm"}, &host)
		if err != nil {
			return err
		}
		var vms []mo.VirtualMachine
		err = pc.Retrieve(ctx, host.Vm, []string{"name"}, &vms)
		if err != nil {
			return err
		}

		fmt.Printf("host has %d vms:", len(vms))
		for i := range vms {
			fmt.Print(" ", vms[i].Name)
		}
		return nil
	})
}

then in the main.go. I call this function. but the result is that host not found

**Comment by atc0005** [comment]
> @atc0005 I tried to get read the source code, but no more comments in the code which makes me read difficult. 

Understood. I can't speak for the maintainers of this project, but they may be willing to accept a Pull Request that adds documentation comments to the examples. Having those details could help future users of this package.

I'm out of time today, but take a look at this example:

https://github.com/chrisgreene/govmomi-examples/blob/master/list-vms.go

It is based on the official examples, but bundles all needed functionality so that it stands alone. You should be able to use it with a standalone ESXi host, though I no longer have access to a standalone host to confirm.

**Comment by dougm** [comment]
You can use the host name or path.  To see the list of host paths:
```console
% govc find / -type h
```

And names:
```console
% govc object.collect -s -type h / name
```

There's also an example in the godoc, but in the property package: https://github.com/vmware/govmomi/blob/4a7a0b457f709dea7b397a6701d2dbd19e413914/property/example_test.go#L54-L76

**Comment by leoxucn822** [comment]
@dougm, yeah I use this method to try to get the vm list, but when I run my code, it shows, the host can't be found, but I am sure that the host is exist here.

**Comment by dougm** [comment]
If your vCenter has multiple Datacenters, yes, you need to specify one.  For example:
```go
		finder := find.NewFinder(c)
		dc, err := finder.Datacenter(ctx, "DC0")
		if err != nil {
			return err
		}

		finder.SetDatacenter(dc)

		obj, err := finder.HostSystem(ctx, "DC0_H0")
                 ...
```

**Comment by leoxucn822** [comment]
@dougm thanks for your hint, actually I should set the DC first, then change the pointer to the DC layer, then I can get the VM list, many thanks for your help. you can archive this case
