### ISSUE TITLE
Ensure there are no duplicate bindings for cns in vsan package

### ISSUE THREAD

**Issue by chethanv28** [vmware/govmomi#2258]
Creating this issue to track the changes and follow-up on the below discussion:
https://github.com/vmware/govmomi/pull/2256#pullrequestreview-576781220

We need to decide upon one of the below considerations:
1. Cns package use the vsan generated types
2. The san generator filter out cns bindings

**Comment by gh05tn0va** [comment]
> Creating this issue to track the changes and follow-up on the below discussion:
> [#2256 (review)](https://github.com/vmware/govmomi/pull/2256#pullrequestreview-576781220)
> 
> We need to decide upon one of the below considerations:
> 
> 1. Cns package use the vsan generated types
> 2. The san generator filter out cns bindings

Hi @chethanv28 , sorry for the late response.
This is definitely an issue if we add any vsan api in future release -- the newly generated bindings overwrites your change.
I'm OK with your second solution to filter out cns codes in first place. However, I need more information here:

Could cns team provide and maintain a list of APIs (or MOs) name, so we can use them in our script?

For reference, you can find our script here: //depot/bora/main/vsan/scripts/asyncVmodlEmitter.py
