### ISSUE TITLE
how to get the ESXI host inventory path

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2259]

**Comment by dougm** [comment]
You can use `find.InventoryPath` with a `ManagedObjectReference` of any type: https://github.com/vmware/govmomi/blob/854ba4efe87ecd9bf34d4bc466119c1748e8b7ef/object/example_test.go#L211-L213

**Comment by leoxucn822** [comment]
@dougm, there is one question from myside, the obj types.ManagedObjectReference as parameter, I can find ManagedObjectReference is a struct, but how should I get the ESXI hostname?
func InventoryPath(ctx context.Context, client *vim25.Client, obj types.ManagedObjectReference) (string, error) {
	entities, err := mo.Ancestors(ctx, client, client.ServiceContent.PropertyCollector, obj)
	if err != nil {
		return "", err
	}
	return internal.InventoryPath(entities), nil
}

**Comment by dougm** [comment]
You can simply use `path.Base()` on the path returned by `find.InventoryPath()`

Or you can use `object.NewHostSystem(client, ref).ObjectName(ctx)`

**Comment by leoxucn822** [comment]
@dougm, thanks for your hint, I get the inventory successfully
