### ISSUE TITLE
govc: network  not found

### ISSUE THREAD

**Issue by dingziyang** [vmware/govmomi#2260]
- ENV： vSphere client 6.7.0

- I clone a vm from a template.
`
govc vm.clone -k=true -u https://test:******@10.37.16.17/sdk -vm win2008_1disk -on=false -m=1024 -c=1 -ds LF_H5K01_VIEW01 -host 10.37.17.207  dcm_win2008r2_clone_1
`

- Then I try change network , I got an error : govc: **network '10.10.12.0/24' not found!**
`
govc vm.network.change -k=true -u https://test:******@10.37.16.17/sdk -json=true -vm dcm_win2008r2_clone_1 -net 10.10.12.0/24 -net.adapter e1000  ethernet-0
`

- Help, Please. I executed some orders, hoping to provide useful information:
`
govc find -k=true -u https://test:VMware1234@10.37.16.17/sdk -json=true -type g /
[
  "/view/network/10.10.8.0%2f24",
  "/view/network/DSwitch-DVUplinks-41",
  "/view/network/10.10.11.0%2f24",
  "/view/network/10.10.10.0%2f24",
  "/view/network/10.10.14.0%2f24",
  "/view/network/10.10.9.0%2f24",
  "/view/network/10.10.12.0%2f24",
  "/view/network/10.10.13.0%2f24"
]
`
`
govc host.vswitch.info -k=true -u https://test:VMware1234@10.37.16.17/sdk -host=10.37.17.207 -json=true | jq '.Vswitch[]'
{
  "Name": "vSwitch0",
  "Key": "key-vim.host.VirtualSwitch-vSwitch0",
  "NumPorts": 11776,
  "NumPortsAvailable": 11719,
  "Mtu": 1500,
  "Portgroup": [
    "key-vim.host.PortGroup-10.37.16.0/24",
    "key-vim.host.PortGroup-10.37.17.0/24",
    "key-vim.host.PortGroup-vMotion",
    "key-vim.host.PortGroup-Management Network"
  ],
  "Pnic": [
    "key-vim.host.PhysicalNic-vmnic4",
    "key-vim.host.PhysicalNic-vmnic2"
  ],
  "Spec": {
    "NumPorts": 128,
    "Bridge": {
      "NicDevice": [
        "vmnic4",
        "vmnic2"
      ],
      "Beacon": {
        "Interval": 1
      },
      "LinkDiscoveryProtocolConfig": {
        "Protocol": "cdp",
        "Operation": "listen"
      }
    },
    "Policy": {
      "Security": {
        "AllowPromiscuous": false,
        "MacChanges": true,
        "ForgedTransmits": true
      },
      "NicTeaming": {
        "Policy": "loadbalance_srcid",
        "ReversePolicy": true,
        "NotifySwitches": true,
        "RollingOrder": false,
        "FailureCriteria": {
          "CheckSpeed": "minimum",
          "Speed": 10,
          "CheckDuplex": false,
          "FullDuplex": false,
          "CheckErrorPercent": false,
          "Percentage": 0,
          "CheckBeacon": false
        },
        "NicOrder": {
          "ActiveNic": [
            "vmnic2",
            "vmnic4"
          ],
          "StandbyNic": null
        }
      },
      "OffloadPolicy": {
        "CsumOffload": true,
        "TcpSegmentation": true,
        "ZeroCopyXmit": true
      },
      "ShapingPolicy": {
        "Enabled": false,
        "AverageBandwidth": 0,
        "PeakBandwidth": 0,
        "BurstSize": 0
      }
    },
    "Mtu": 0
  }
}
`

**Comment by dougm** [comment]
Based on the output, the network name is `10.10.12.0%2f24`, where `/` is escaped as `%2f` (iirc, done by the vCenter web UI)  
So try using `govc vm.clone -net 10.10.12.0%2f24 ...`.

**Comment by dingziyang** [comment]
You are right, Thanks!

**Comment by dingziyang** [comment]
You are right, It is worked. Thanks.
