### ISSUE TITLE
Modify vApp Options

### ISSUE THREAD

**Issue by matteoiacovitti** [vmware/govmomi#2261]
How do you modify vApp Options using GOVC?

![image](https://user-images.githubusercontent.com/25353683/106202402-deb7d180-6187-11eb-9899-a6543c358f75.png)

**Comment by dougm** [comment]
For guestinfo properties, you can use `vm.change` with the `-e` flag:  https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmchange

See also #991

**Comment by matteoiacovitti** [comment]
the `-e` flag adds to the advanced configuration. I need to add to the vApp options

**Comment by mooperd** [comment]
I also need to add to the vApp properties so I can set a custom SSH key for a cloned machine.

**Comment by matteoiacovitti** [comment]
@mooperd I found a way to do this. 

There are a couple of steps involved.

1. First, you need to get the OVF specs which have all of the vApp option settings
`govc import.spec name_of_ovf.ovf `
You will get an output similar to this

```
{
  "DiskProvisioning": "flat",
  "IPAllocationPolicy": "dhcpPolicy",
  "IPProtocol": "IPv4",
  "PropertyMapping": [
    {
      "Key": "guestinfo.hostname",
      "Value": ""
    },
    {
      "Key": "guestinfo.interface.0.ip.0.address",
      "Value": ""
    },
    {
      "Key": "guestinfo.interface.0.route.0.gateway",
      "Value": ""
    },
    {
      "Key": "guestinfo.dns.server.0",
      "Value": ""
    },
    {
      "Key": "agent_key",
      "Value": ""
    }
  ],
  "NetworkMapping": [
    {
      "Name": "Network",
      "Network": ""
    }
  ],
  "Annotation": "This OVA provides a UEFI secure boot enabled minimal installed profile of PhotonOS.\n\n   Default password for root user is changeme. However user will be prompted to change the password during first login.",
  "MarkAsTemplate": false,
  "PowerOn": false,
  "InjectOvfEnv": false,
  "WaitForIP": false,
  "Name": null
}

```
2. Save this file as a JSON and modify the vApp option Values to your specifications. Whether it's using a script with variables or just hardcoded
3. When you run your deploy command, make sure to include `options=name_of_jason.json` in the command to include the JSON file. This will deploy the VM using the vApp options in the JSON

This has worked for me many times and, at least for now, the best way to deploy or create a VM with vApp options.

**Comment by mooperd** [comment]
Hey @matteoiacovitti, That seems to only work for `import.ova` but not `vm.create` or `vm.clone`. If I understand correctly this means that you have to re-upload the image everytime you want to adjust the vApp properties. This is slow to start new VMs and gets expensive in storage as you cant use copy on write.

**Comment by matteoiacovitti** [comment]
Unfortunately, that is the only way I found.

I would love it if GOVC had a way to just inject vApp Options, but I have not found a way yet....or if there is even a way to do it

**Comment by koznov** [comment]
Still no possibility to add vApp properties in case of cloning or creating new VM (not from OVF)?
