### ISSUE TITLE
Support for ovfManager in govmomi?

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#2262]
We have used the ServiceInstance.getOvfManager().parseDescriptor() in Java and find it to be very useful and efficient. Is there support in govmomi (or some other library) for OvfManager interaction?

**Comment by atc0005** [comment]
@kayshavd 

This may be what you're after:

https://pkg.go.dev/github.com/vmware/govmomi@v0.24.0/ovf#Manager.ParseDescriptor
