### ISSUE TITLE
Update govc usage.md file to be correct and/or integrate with existing readme.md

### ISSUE THREAD

**Issue by abrownoip** [vmware/govmomi#2264]
I've made a fork of the govmomi repo to resolve this issue myself. Wondering what the best route would be.
My ideas:
- The govc readme should have all of the usage information as I feel that is the point of the readme in general. The usage.md file seemed to be generated by the usage.sh script. This could be updated to have the readme.md file be generated by a readme.sh script that contains the static data but will still have the usage information generated.
OR
- Update just the incorrect static data in the usage.md file

For reference in the govc usage.md file there is static data containing common options which contains:

-host.dns=                Find host by FQDN
  -host.ip=                 Find host by IP address
  -host.ipath=              Find host by inventory path
  -host.uuid=               Find host by UUID
  -vm.dns=                  Find VM by FQDN
  -vm.ip=                   Find VM by IP address
  -vm.ipath=                Find VM by inventory path
  -vm.path=                 Find VM by path to .vmx file
  -vm.uuid=                 Find VM by UUID

These are incorrect to the point of the command not existing and/or the description being incorrect.

**Comment by dougm** [comment]
Documentation improvements are certainly welcome.  There is doc in README.md that we could push into the govc command help and in turn end up in the generated USAGE.md. But some of the readme doc is is how-to install a binary, build from source, license, links to other projects, etc.  The usage is meant for post-intro/install.

Not sure what you mean by the common `-host.*` and `-vm.*` flags being incorrect?  They are common the the majority of `host.*` and `vm.*` commands. For example:

```console
% govc host.info -h | grep Find
  -host.dns=                                                 Find host by FQDN
  -host.ip=                                                  Find host by IP address
  -host.ipath=                                               Find host by inventory path
  -host.uuid=                                                Find host by UUID
```
```console
% govc vm.info -h | grep Find
  -vm.dns=                                                   Find VM by FQDN
  -vm.ip=                                                    Find VM by IP address
  -vm.ipath=                                                 Find VM by inventory path
  -vm.path=                                                  Find VM by path to .vmx file
  -vm.uuid=                                                  Find VM by UUID
```

**Comment by abrownoip** [comment]
In terms of the common flags being incorrect - this was my bad ( I misunderstood the documentation on this). I tried govc host.info -host.ip <ip> in my environment and it worked without issue. In this case - while the documentation was correct I think it would be useful to show these kinds of examples.

**Comment by abrownoip** [comment]
Closing issue - will open new issue for additional examples.
