### ISSUE TITLE
how to check if DRS is enabled on the cluster

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2267]

**Comment by leoxucn822** [comment]
for example, in the simulator package and in the object package, there are two methods to set maintenance mode for ESXI.
I don't know what is the difference of these two methods.

**Comment by dougm** [comment]
See [DrsConfigInfo](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.cluster.DrsConfigInfo.html)

```console
% govc find / -type c | xargs -I% -n1 govc object.collect % name configuration.drsConfig.enabled
configuration.drsConfig.enabled  bool    false
name                             string  edge-cluster
configuration.drsConfig.enabled  bool    true
name                             string  compute-cluster
```
