### ISSUE TITLE
support for StoragePod

### ISSUE THREAD

**Issue by munkyboy** [vmware/govmomi#227]
currently, it seems that govc is unable to perform any actions on datastores within StoragePods (datastore clusters). For example:

    govc datastore.ls -ds='/MyDatacenter/datastore/MyStoragePod/MyDatastore'

returns with `Error: cannot traverse type StoragePod`

**Comment by pietern** [comment]
When did you build your version of govc? 22 days ago we merged a patch that fixed something related to the StoragePod type, but I can't tell if it would solve your issue: https://github.com/vmware/govmomi/commit/9c4a9202e330f5452ad6330da5b54d32fb6d66bf

**Comment by munkyboy** [comment]
I built it yesterday. b0356fa

**Comment by schneidexe** [comment]
+1 Same issue here. Cannot use SDRS datastores...
