### ISSUE TITLE
Receiving panic upon deleting snapshot, that is currently being run on while newer snapshots exist

### ISSUE THREAD

**Issue by ChaoJJ** [vmware/govmomi#2275]
Hello there,

while using govc to create and delete snapshots, I've tried an unusual order of operations, which ended in a panic.

The govc version I'm using is 0.23.0, vsphere version in use is 6.5.

So how to recreate the panic:
1. create 2 snapshots via
```snapshot.create -u=vcenter -dc=datacenter -vm=name -m=false -q=false -d=description snapshotname```
2. we are currently running on snapshot2, revert to snapshot1
```snapshot.revert -u=vcenter -dc=datacenter -vm=name moRef```
3. Delete snapshot1, which we are currently running on, do not delete snapshot2 beforehand
`snapshot.remove -u=vcenter -dc=datacenter -vm=name -c=true -r=false moRef`
4. Now I end up in a state in which I cannot call snapshot.tree, but receive a panic
`snapshot.tree  -u=vcenter -dc=datacenter -vm=name -i=true -d=true -D=true`

The panic code is the following:
```"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdc45af]\n\ngoroutine 1 [running]:\ngithub.com/vmware/govmomi/govc/vm/snapshot.(*tree).write(0xc0000b0d00, 0x0, 0x0, 0x0, 0xc00008a270, 0x1, 0x1)\n\t/home/vmware/src/github.com/vmware/govmomi/govc/vm/snapshot/tree.go:95 +0x42f\ngithub.com/vmware/govmomi/govc/vm/snapshot.(*tree).Run(0xc0000b0d00, 0x13ae500, 0xc000098010, 0xc00009e780, 0x0, 0x0)\n\t/home/vmware/src/github.com/vmware/govmomi/govc/vm/snapshot/tree.go:165 +0x2cd\ngithub.com/vmware/govmomi/govc/cli.Run(0xc0000a4010, 0x7, 0x7, 0xc000082058)\n\t/home/vmware/src/github.com/vmware/govmomi/govc/cli/command.go:165 +0x5de\nmain.main()\n\t/home/vmware/src/github.com/vmware/govmomi/govc/main.go:99 +0x64\n"```

Can you look into this problem?

Thanks in advance

**Comment by embano1** [comment]
@ChaoJJ did you resolve this issue in the meantime? If not, can you please reproduce with the latest release?

**Comment by ChaoJJ** [comment]
Yes, this is still an issue on govc 0.25.0.
We've not handled the issue ourselves, but rather just forbid this sequence of events.
