### ISSUE TITLE
govmomi vs vijava with vSphere SDK 7.0

### ISSUE THREAD

**Issue by HelloWorld3031** [vmware/govmomi#2279]
Hello,

We are trying to build a solution with vSphere and we're still at the initial stages of planning. It would really help us if we can resolve some of our doubts before we proceed further.

Could you please let us know the hurdles that may face when we use govmomi instead of vijava?

I have been hearing excellent stories on the vijava's support for vSphere SDK.

We want to run the remote plug in servers on a k8s cluster, which provides a performance gain if we go with golang.

Is the vSphere SDK 7.0 fully supported in govmomi?

 

Thanks!

**Comment by dougm** [comment]
Yes, 7.0 is supported in govmomi.  vSphere 7 itself uses govmomi for the built-in Kubernetes integrations.
