### ISSUE TITLE
Is there a way to change the MAC address of a VM

### ISSUE THREAD

**Issue by abb-wcheung** [vmware/govmomi#228]
It looks like the vm.create or vm.network.[add|change] do not support specifying the MAC address of the VM.  We use a DHCP server here to have fixed assignment of IP address based on MAC address so this feature is important.

**Comment by dougm** [comment]
It's not supported in govc.  I haven't fully tested this yet, but it should look something like this if you want to give a try: https://github.com/dougm/govmomi/commit/9cd4022665f1b217e889e16a51870b525accf4c6

**Comment by dougm** [comment]
Added in ad39adb
