### ISSUE TITLE
get value for Custom Attribute VM

### ISSUE THREAD

**Issue by rodolphewachter** [vmware/govmomi#2283]
Hi,

I have a problem to retrieve the value of Custom Attribute VM.
I loop with : `vm.Summary.CustomValue` but how to get the value of the Custom Attribute ?

I get the key name with that and it's ok : 

	l, _ := object.GetCustomFieldsManager(c)
	s, _ := l.Field(ctx)
	t := s.ByKey(key)
	return t.Name

Thank you in advance for your help

**Comment by rodolphewachter** [comment]
@dougm Could you help me please ?

**Comment by atc0005** [comment]
@rodolphewachter This is probably not the best way to handle it, but this is how I was able to query custom attribute values:

https://github.com/atc0005/check-vmware/blob/5d0d19510197dc68dbc39e4fe934c233216fda24/internal/vsphere/attributes.go#L119-L134

When I wrote that I'm not sure I knew about `object.GetCustomFieldsManager` (I'm still very much learning my way around govmomi).

**Comment by rodolphewachter** [comment]
@atc0005 thx for your example, i test it tomorrow !

**Comment by rodolphewachter** [comment]
Hi @atc0005, It's perfect, thx for your help !!!

**Comment by atc0005** [comment]
> Hi @atc0005, It's perfect, thx for your help !!!

You're welcome, glad I could help.

**Comment by embano1** [comment]
Is it ok to close this issue then?

**Comment by embano1** [comment]
Closing this issue.
