### ISSUE TITLE
The VM Cloning Process Has Some Unexpected Issues

### ISSUE THREAD

**Issue by serversci** [vmware/govmomi#2293]
I'm able to clone a VM by the following means:

```
#!/bin/bash

main()
{
   export GOVC_INSECURE=true
   export GOVC_PASSWORD='password'
   export GOVC_URL='https://vcenter.company.com'
   export GOVC_USERNAME='username@domain'
   export GOVC_DATACENTER='datacenter'
   export GOVC_FOLDER='/datacenter/vm/folder/subfolder'
   export GOVC_DATASTORE_CLUSTER='datastorecluster'

   local SrcVM="$1"
   local DstVMName="$2"
   local DstVMIP="$3"
   local DstVMGateway="$4"
   local DstVMMask="$5"
   local DstVMTZ="$6"
   local DstVMDNSServers="$7"

   govc vm.clone -cluster=datacentercluster -vm="$SrcVM" -on=false "$DstVMName"

   local DstVMMAC
   DstVMMAC="$(
      govc vm.info -json "$DstVMName" |
      jq -r '.VirtualMachines[].Config.Hardware.Device[] | select(.MacAddress != null) | .MacAddress'
   )"

   local -a CustomizationOptions=(
      "-vm=$DstVMName"
      "-mac=$DstVMMAC"
      "-ip=$DstVMIP"
      "-netmask=$DstVMMask"
      "-DstVMGateway=$DstVMGateway"
      "-dns-server=$DstVMDNSServers"
   )

   govc vm.customize "${CustomizationOptions[@]}"
   govc vm.power -on "$DstVMName"
}

main "$@"; exit
```

Here are the outstanding issues:

1. The **/etc/resolv.conf** is being populated with `nameserver` entries only.

- How is **/etc/resolv.conf** populated with `search` entries?

2. The **/etc/hosts** has an entry with dots in the hostname removed. For example: `10.20.30.40 vm1mycompanycom` where I would have expected `10.20.30.40 vm1.mycompany.com`. Similarly, the **/etc/sysconfig/network** file has the line `HOSTNAME=vm1mycompanycom` where I would have expected `HOSTNAME=vm1.mycompany.com`.

- How do I prevent the dots from being removed from hostname entries as shown above?

3. The **/etc/hosts** file has an IPv6 line entered: `::1 vm1mycompanycom`. However, the VM has IPv6 disabled.

- How do I prevent IPv6 entries from being added to the **/etc/hosts** file?

4. Help `govc vm.customize -h` shows entries of the form `-option=[]`. I have not found the documentation that explains exactly what the `[]` is meant to convey. I found that **-dns-server** can take a comma-separated list of IP addresses.

- Can the delimiter be specified, especially where comma might be a valid part of the value?
- Are other forms permissible? Examples: `-option=(value1 value2)` or `-option=[value1,value2]`, etc.
- Does this apply to all cases where this is used in help across all govc help items?
- Is there clear and comprehensive documentation available?

5. The **/etc/sysconfig/network-scripts/ifcfg-eth1** file is created. This is unexpected and **ifcfg-eth0** is commonly used as the WAN-side NIC. The `$SrcVM` had only **ifcfg-eth0**. The `$DstVM` has only **ifcfg-eth1**.

- Can the NIC name be specified so that the expected filename is created?

**Comment by dougm** [comment]
> * How is **/etc/resolv.conf** populated with `search` entries?

Added an option for that in #2293

> The **/etc/hosts** has an entry with dots in the hostname removed. For example: `10.20.30.40 vm1mycompanycom` where I would have expected `10.20.30.40 vm1.mycompany.com`. Similarly, the **/etc/sysconfig/network** file has the line `HOSTNAME=vm1mycompanycom` where I would have expected `HOSTNAME=vm1.mycompany.com`.

I don't see `-name vm1.mycompany.com` in your `CustomizationOptions`?  Otherwise I think vCenter defaults to the VM's name, don't know how it ended up as `vm1mycompanycom`.  You can check with [-debug](https://github.com/vmware/govmomi/tree/master/govc#debug-flag) to see if govc is sending that value.

> The **/etc/hosts** file has an IPv6 line entered: `::1 vm1mycompanycom`. However, the VM has IPv6 disabled.
>
> * How do I prevent IPv6 entries from being added to the **/etc/hosts** file?

govc shouldn't include anything IPv6 in the spec by default, anything in the debug logs?

> Help `govc vm.customize -h` shows entries of the form `-option=[]`. I have not found the documentation that explains exactly what the `[]` is meant to convey. I found that **-dns-server** can take a comma-separated list of IP addresses.

`[]` just means you can specify the `-option` multiple times.  See `govc vm.customize -h` Examples where `-ip`, `-netmask`, etc., are specified multiple times.

> * Is there clear and comprehensive documentation available?

govc leans pretty heavily on the examples section in the docs.  Some of the doc is generated by Go's flag package (such as the `[]`), which agree isn't obvious
and we can improve the doc.

> The **/etc/sysconfig/network-scripts/ifcfg-eth1** file is created. This is unexpected and **ifcfg-eth0** is commonly used as the WAN-side NIC. The `$SrcVM` had only **ifcfg-eth0**. The `$DstVM` has only **ifcfg-eth1**.
>
> * Can the NIC name be specified so that the expected filename is created?

govc just calls the `CustomizeVM` API and doesn't touch any files directly inside the VM, that's done by vmware-tools. How many NICs does the VM have?
