### ISSUE TITLE
arm64 govc binaries

### ISSUE THREAD

**Issue by dlampa** [vmware/govmomi#2295]
It would be great if you could provide govc binaries for the arm64 architecture.

Thanks

**Comment by embano1** [comment]
Should be doable, @dougm any concerns using `ko` to do this? We use it in Knative and it's awesome (beyond just ARM builds): https://github.com/google/ko

**Comment by embano1** [comment]
// Update

`goreleaser` has beta support for multi-platform images, so we can use this approach as well: https://goreleaser.com/customization/docker_manifest/

**Comment by dlampa** [comment]
Thank you for the effort!
