### ISSUE TITLE
Unable to attach network as it resolves to multiple networks

### ISSUE THREAD

**Issue by anupugalavat** [vmware/govmomi#2298]
Hello,

While cloning using below syntax with details of Datastore, Pool, folder and network. The cloning process fails due the error. where in network resolves to Multiple network.

tfuser@tfuser-virtual-machine:~$ govc vm.clone -ds /wld1-DC/datastore/wld1-sfo-w01-vc01-cluster2-vsan01 -pool /wld1-DC/host/cluster2/Resources -folder apm -net /wld1-DC/network/apm-segment-rotlab -vm test-tf1 newclonevm-7

**Error:
govc: path '/wld1-DC/network/apm-segment-rotlab' resolves to multiple networks**

Also i got the network details using 

**tfuser@tfuser-virtual-machine:~$ govc ls /wld1-DC/network**
/wld1-DC/network/apm-segment-rotlab
/wld1-DC/network/gardener-dev--shoot--vmware-rot--perf1-rp64hhb4
/wld1-DC/network/seg-domain-c71:458eb290-beff-49fe-a9e1-3421ae647bf7-kube-public-0
/wld1-DC/network/seg-domain-c71:458eb290-beff-49fe-a9e1-3421ae647bf7-vmware-system-cert-manager-0
/wld1-DC/network/Nested-Esxi-trunk

can you please check what is the issue here.

**Comment by dougm** [comment]
What is the output with the `-l` switch?  `govc ls -l /wld1-DC/network`
Sounds like it could be that `apm-segment-rotlab` is a `DistributedVirtualSwitch`, but you need to select 1 of the `DistributedVirtualPortgroup` within.

**Comment by anupugalavat** [comment]
@dougm below is the output of `govc ls -l /wld1-DC/network`

/wld1-DC/network/apm-segment-rotlab (DistributedVirtualPortgroup)
/wld1-DC/network/Nested-Esxi-trunk (DistributedVirtualPortgroup)
/wld1-DC/network/wld1-sfo-w01-vc01--vds01-vmotion (DistributedVirtualPortgroup)
/wld1-DC/network/apm-segment-demo2 (DistributedVirtualPortgroup)
/wld1-DC/network/wld1-sfo-w01-vc01-cluster1-vds01 (VmwareDistributedVirtualSwitch)
/wld1-DC/network/wld1-sfo-w01-vc01-cluster2-vds01 (VmwareDistributedVirtualSwitch)

as per the output i think i am using `/wld1-DC/network/apm-segment-rotlab (DistributedVirtualPortgroup)` which is `DistributedVirtualPortgroup`.

**Comment by dougm** [comment]
Yes, looks like `/wld1-DC/network/apm-segment-rotlab` should work, I don't know what's causing the error.

If you could provide debug logs we might be able to figure it out: https://github.com/vmware/govmomi/tree/master/govc#debug-flag

**Comment by anupugalavat** [comment]
@dougm looks like adding `-debug` flag is just generating few `.req.headers` and `.req.xml` files. Below is the optput of what i have performed.

tfuser@tfuser-virtual-machine:~$ govc vm.clone -ds /wld1-DC/datastore/wld1-sfo-w01-vc01-cluster2-vsan01 -pool /wld1-DC/host/cluster2/Resources -folder apm -net /wld1-DC/network/apm-segment-rotlab -debug -vm test-tf1 newclonevm-9
govc: path '/wld1-DC/network/apm-segment-rotlab' resolves to multiple networks
tfuser@tfuser-virtual-machine:~/.govmomi/debug$ ll
drwx------ 2 tfuser tfuser 12288 Mär  1 08:19 2021-03-01T08-19-34.391180261/
drwx------ 2 tfuser tfuser 12288 Mär  1 11:09 2021-03-01T11-09-10.660785479/
tfuser@tfuser-virtual-machine:~/.govmomi/debug/2021-03-01T11-09-10.660785479$ ll
total 1312
drwx------ 2 tfuser tfuser 12288 Mär  1 11:09 ./
drwx------ 9 tfuser tfuser  4096 Mär  1 11:09 ../
-rw-rw-r-- 1 tfuser tfuser   148 Mär  1 11:09 1-0001.req.headers
-rw-rw-r-- 1 tfuser tfuser   425 Mär  1 11:09 1-0001.req.xml
-rw-rw-r-- 1 tfuser tfuser   231 Mär  1 11:09 1-0001.res.headers

Could you also let me know what should be done next as well as confirm that above steps are correct.

**Comment by anupugalavat** [comment]
@dougm can you please investigate further?
