### ISSUE TITLE
unmarshal xml to types.VirtualMachineConfigSpec

### ISSUE THREAD

**Issue by jackalensu** [vmware/govmomi#2299]
Hi,

I am now working on backup/restore VMs on vsphere using govmomi.
So I try to save VM configs (types.VirtualMachineConfigSpec)  as xml using vim25/xml for creating new VM on restore.
But when I call xml.Unmarshal trying to read xml, it turns out that all the elements in VirtualMachineConfigSpec.DeviceChange of type []BaseVirtualDeviceConfigSpec  become nil while other attributes unmarshaled successfully.

The first solution came up to me (though it sounds really stupid) is to save all the DeviceChange into individual types.VirtualDeviceConfigSpec. It seem to work at first but it finally failed when I try to use it for creating new VM cause the attribute Device of type BaseVirtualDevice within types.VirtualDeviceConfigSpec also became nil as the same problem  above. (and some other attributes within Device also match the case )

After surveying  related issues, some suggest to implement own unmarshalxml / unmarshalxmlattr function but I'm not sure if it's proper or not and if there are other solution better dealing with this problem.

Thank you.

**Comment by dougm** [comment]
You'll need to use govmomi's vim25/xml package instead of Go's:
https://github.com/vmware/govmomi/blob/ee5d4c3f398dbd307c06cb092361268ee4afc60c/simulator/model.go#L40

And set `TypeFunc` for example here:
https://github.com/vmware/govmomi/blob/ee5d4c3f398dbd307c06cb092361268ee4afc60c/simulator/model.go#L344-L355

**Comment by jackalensu** [comment]
It works perfectly!! Thanks a lot!!
