### ISSUE TITLE
Authenticating with Vmware-Api-Session-Token

### ISSUE THREAD

**Issue by HelloWorld3031** [vmware/govmomi#2301]
Hi,

I was following this guide to authenticate with the vcenter, 
https://code.vmware.com/docs/11915/developing-remote-plug-ins-with-the-vsphere-client-sdk/GUID-ED253BD0-E9B1-4588-958D-577A667F5AD9.html
We are able to retrieve the Vmware-Api-Session-Token mentioned in step 1.
However, we are unable to acquire a clone ticket(step 4) which is needed to clone a session(step 6) on the remote plugin server.
could you please outline the flow in govmomi to clone a session from the Vmware-Api-Session-Token?

Thanks

**Comment by dougm** [comment]
I have no experience with UI plugins.. what did you try exactly for step 4 and how did it fail?

**Comment by HelloWorld3031** [comment]
Hi @dougm .. Thanks for replying.
As mentioned in that page, every time the UI makes a request to the backend, it sends the session token corresponding to the logged in user. The backend then uses that session token to obtain a clone ticket and clone a user session with the help of the clone ticket. The backend only receives this session token, so it doesn't have user credentials to make a `SessionManager.Login()` call. We need to obtain a clone ticket to clone a user session.
if we use `AcquireCloneTicket` method of `SessionManager` without a call to `Login()` it rightly fails saying that the session is not authenticated. However, if we manually construct the REST request mentioned in step 4, and then call `SessionManager.CloneSession` by passing in the response received in the above request, it succeeds.
is there a way to eliminate the manual construction of REST request (step 4) to the vcenter?
I have also tried to use `SessionManager.LoginByToken` by passing in the header received from the UI, it says `ServerFaultCode: Cannot complete login due to an incorrect user name or password.`

**Comment by dougm** [comment]
It doesn't sound like you can avoid the REST request, but maybe using govmomi's rest client will simplify things?  Something like (untested):
```go
		c := rest.NewClient(vc)

		c.SessionID("12345678")

		var clone = struct {
			GUID   string `json:"vc_guid,omitempty"`
			Ticket string `json:"session_clone_ticket,omitempty"`
		}{
			vc.ServiceContent.About.InstanceUuid, "",
		}

		url := c.Resource("/api/ui/vcenter/session/clone-ticket")

		err := c.Do(ctx, url.Request(http.MethodPost, clone), &clone)
		if err != nil {
			return err
		}

		err = session.NewManager(vc).CloneSession(ctx, clone.Ticket)
```

**Comment by HelloWorld3031** [comment]
Sure, Doug. Will try this out.

**Comment by pranaypareek** [comment]
@HelloWorld3031 were you able to make use of govmomi's REST client as Doug suggested? Or did you stick with manually constructing the REST request (to then call `SessionManager.CloneSession`) as you mentioned in your previous comment? 

Thanks!
