### ISSUE TITLE
Use Github Actions

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2302]
For a faster and more streamlined developer experience, I suggest migrating the current CI and release process to Github actions.

Main benefits:

- faster builds (current PR tests sometimes take up to an hour to complete)
- huge community and pre-defined actions to chose from (goreleaser, linting, etc.)
- Matrix builds (Windows, Linux, MacOS)

**Comment by dougm** [comment]
Sounds great @embano1 !
