### ISSUE TITLE
EFI firmware switching to BIOS when govmomi created Contentlibrary item is deployed

### ISSUE THREAD

**Issue by vantmet** [vmware/govmomi#2304]
Hi,

  I'm hitting the problem described on this Packer Issue: [EFI firmware switching to BIOS when destination is vSphere content library](https://github.com/hashicorp/packer/issues/9898).

  When an EFI-Secure VM is converted to a ContentLibrary Item by govmomi, a section of code is added to the OVF file which isn't if the vSphere GUI is used, or if PowerCLI is used (tested both on vSphere 7.0.1 (VCF 4.1).

 The Code is: 
`<vmw:BootOrderSection vmw:instanceId="5" vmw:type="disk">
    <Info>Virtual Hardware device boot order</Info>
</vmw:BootOrderSection>`

Could this be fixed please, as this code causes the deployed VM to be converted to BIOS firmware, breaking boot.

**Comment by dougm** [comment]
@Wav3 could you share the python script you [mentioned](https://github.com/hashicorp/packer/issues/9898#issuecomment-758752272) ?

And/or if someone can provide more details on how to reproduce, such as packer script, commands, etc.

govmomi does not modify the ovf directly, but maybe there's an API flag we're missing that would avoid `BootOrderSection` from getting added.

**Comment by Wav3** [comment]
Hi,

the python script, as well as a minimal configuration for packer can be found in [my](https://gist.github.com/Wav3/142c462bebfb92dca9eb2e3dc45c2343) gist.  

To reproduce this issue with Packer v1.6.6 follow these steps:  

1. Download [Packer v1.6.6](https://releases.hashicorp.com/packer/1.6.6/)
2. Download the files provided in the gist.
3. Fill [`vars.json`](https://gist.github.com/Wav3/142c462bebfb92dca9eb2e3dc45c2343#file-vars-json) with the required values.
4. Run `packer build -var-file=vars.json -on-error=ask build.json` and wait for the process to finish.
5. Download the OVF file from the content library after the packer build has finished.

**Comment by dougm** [comment]
Thanks @Wav3 , I can reproduce the `BootOrderSection` being added using your packer build.  I haven't tried the python script, but using `govc library.clone -ovf`, there is no `BootOrderSection` added either:

```console
% govc vm.create -g windows9Server64Guest -version vmx-13 -disk 10M -net.adapter vmxnet3 -net "VM Network" -ds vsanDatastore -on=false vm1

% govc device.boot -vm vm1 -firmware efi

% govc library.clone -ovf -vm vm1 govc test-vm

% govc library.export govc/test-vm/test-vm.ovf - | grep -i -E 'BootOrder|efi'
      <vmw:Config ovf:required="false" vmw:key="bootOptions.efiSecureBootEnabled" vmw:value="false"/>
      <vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="efi"/>
```

I compared the vm configs with a diff of `govc vm.info -json vm1` and `govc vm.info -json packer-test`, and don't yet see anything obvious that would cause this section to be added for the packer vm.

**Comment by dougm** [comment]
Looks like the issue is that packer sets the VM boot order here: https://github.com/hashicorp/packer/blob/755395faf8d0eb1ad79bb7227cbadecf0a7a0a5c/builder/vsphere/common/step_run.go#L39

But doesn't clear the boot order until the cleanup here: https://github.com/hashicorp/packer/blob/755395faf8d0eb1ad79bb7227cbadecf0a7a0a5c/builder/vsphere/common/step_run.go#L62

Which means boot order is set while the VM is being imported.

I can reproduce this with govc by setting the boot order before library import:
```console
% govc vm.create -g windows9Server64Guest -version vmx-13 -disk 10M -net.adapter vmxnet3 -net "VM Network" -ds vsanDatastore -on=false vm1
% govc device.boot -vm vm1 -firmware efi -order disk,crdom # SetBootOrder
% govc library.clone -ovf -vm vm1 govc test-vm
% govc library.export govc/test-vm/test-vm.ovf - | grep -i -E 'BootOrder|efi'
      <vmw:Config ovf:required="false" vmw:key="bootOptions.efiSecureBootEnabled" vmw:value="false"/>
      <vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="efi"/>
    <vmw:BootOrderSection vmw:instanceId="4" vmw:type="disk">
    </vmw:BootOrderSection>
```

So the fix would be in packer, clearing the boot order after shutdown step instead of waiting till cleanup should do the trick.

**Comment by vantmet** [comment]
Thanks Doug, I'll take that back to Packer!

**Comment by vantmet** [comment]
Fixed by https://github.com/hashicorp/packer-plugin-vsphere/pull/68#event-4843103991

Thanks for the pointers @dougm much appreciated!
