### ISSUE TITLE
VASA Provider registration with vCenter

### ISSUE THREAD

**Issue by ngaj2005** [vmware/govmomi#2305]
sms package was added in govmomi release 0.24.0 but  I am unable to use it to register provider.
registerProvider_Task parameters are smsStorageManager and VasaProviderSpec. 
Do not know how to get smsStorageManager  managedobject ref.
I think this package is incomplete. Need to create sms client for this.

**Comment by ngaj2005** [comment]
Any suggestion on how to register VASA provider will help.

req := smsTypes.RegisterProvider_Task{
       This:         storageManager.Self,
       ProviderSpec: &providerSpec,
}
resp, err := methods.RegisterProvider_Task(ctx, c, &req)

Fails with this error. 
Unsupported version URI "urn:vim25/7.0"

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request before method was determined
at line 1, column 0

fault
  XMLName : Code="VersionMismatchFaultCode", String="Unsuperted version URI "urn:vim25/7.0\"" while paring SOAP body

**Comment by dougm** [comment]
Right, we only added the generated sms types.  There were other folks who were planning to implement the client, but it hasn't happened yet.

Following pbm/client.go is a good example.
Looking at sms.wsdl, the Namespace needs to be `urn:sms`

**Comment by tangxr** [comment]
How to fix this issue?
Registration/unregistration of third-party IO filter storage providers fails on a host
