### ISSUE TITLE
Users cannot be added to windows VM immediately after cloning from the template

### ISSUE THREAD

**Issue by dingziyang** [vmware/govmomi#2306]
Env: vSphere 6.7.0
Question: I cloned a virtual machine from the windows template, then started it immediately, and started it for 10 seconds guest.run Add a new windows user, but it is not successful and get an error message.

```
govc vm.clone -k=true -u https://test:******@10.37.16.17/sdk -vm WIN2K8R2_Template_Prod -on=false -m=1024 -c=1 -ds LF_H5K01_VIEW01 -host 10.37.17.207  dcm_WIN2K8R2_clone_3

govc vm.network.change -k=true -u https://test:******@10.37.16.17/sdk -json=true -vm dcm_WIN2K8R2_clone_3 -net 10.10.8.0%2f24 -net.adapter e1000  ethernet-0

govc vm.customize -k=true -u https://test:******@10.37.16.17/sdk -json=true -vm dcm_WIN2K8R2_clone_3 -ip 10.10.8.100 -gateway 10.10.8.1 -netmask 255.255.255.0  cmp-policy-windows

govc vm.power -k=true -u https://test:******@10.37.16.17/sdk -on   dcm_WIN2K8R2_clone_3
//  sleep 10s

//  (Administrator is valid)get an error： govc: ServerFaultCode: The guest operations agent could not be contacted.
govc guest.run -k=true -u https://test:******@10.37.16.17/sdk -l administrator:ABcd+12#$ -vm dcm_WIN2K8R2_clone_3  cmd /c net user appadmin ABcd+12#$ /add
```
Clue: After 10 seconds, I execute guest.run Report an error, but after a few minutes, execute again guest.run It's worked. Why?

**Comment by dougm** [comment]
Sounds like vmware-tools is not running yet, see: https://github.com/vmware/govmomi/issues/2193#issuecomment-747078133

**Comment by dingziyang** [comment]
Now, I understand that 'guest.run' is responsible for interacting with 'vmtools', and it takes a little time for 'vmtools' to fully load, especially when VM has just been cloned.
