### ISSUE TITLE
Login failure if password includes "!" 

### ISSUE THREAD

**Issue by leslie-qiwa** [vmware/govmomi#2316]
Seems like login will fail if password includes "!". 

```
$ govc about -u 'root:extra123!@10.11.1.37' -k
govc: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
$ export GOVC_PASSWORD='extra123!'
$ export GOVC_USERNAME=root
$ export GOVC_INSECURE=1
$ export GOVC_URL=10.11.1.37
$ govc about
govc: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

Seems like similar issue as https://github.com/vmware/govmomi/issues/450.

**Comment by dougm** [comment]
Are you sure username `root` is correct?  The password I use daily in my env has an `!`, but username is an SSO user, rather than local user (such as root).
```console
% govc about -u 'Administrator@vsphere.local:Xxxxx!23@10.78.204.138' -k
FullName:     VMware vCenter Server 7.0.2 build-44403568
...
```

The url in your example parses as expected:
```console
% govc env -x -u 'root:extra123!@10.11.1.37' -k
GOVC_USERNAME=root
GOVC_PASSWORD=extra123!
GOVC_URL=10.11.1.37
GOVC_INSECURE=true
GOVC_URL_SCHEME=https
GOVC_URL_HOST=10.11.1.37
GOVC_URL_PATH=/sdk
```

**Comment by leslie-qiwa** [comment]
Seems like the ESX host locked the user because of many failure attempt. After re-enable, it went through, and I can not reproduce now with different approaches. Maybe one bug at our side and will close it. Thanks for promptly reply!

**Comment by subashcs** [comment]
I encountered a similar issue with a password added in  `.zshrc` like this:
```
 export GOVC_PASSWORD=B9F$4amBq^jqnr
```
I fixed the issue by just placing the password inside quotes.
```
 export GOVC_PASSWORD='B9F$4amBq^jqnr'
```
