### ISSUE TITLE
[Not a bug] vm.info permissions ?

### ISSUE THREAD

**Issue by W73** [vmware/govmomi#2317]
Hi, 

I am wondering it here is some easy/complicated/any way to get know what privileges  are required for which API call. 
For example what i need for govc vm.info 

Is there any Doc for this ? I tried to get this info from audit log, but no success. 

And recursively went through  
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.fault.NoPermission.html

**Comment by RyanMillerC** [comment]
i was looking for the same thing. I ran the command with `-verbose` flag to get more info. Looks like System.View is showing as no permission in my case.
