### ISSUE TITLE
Unable to find DistributedVirtualPortgroup by vlanid

### ISSUE THREAD

**Issue by SerDroide** [vmware/govmomi#2318]
Hi,

I'm not sure it is a bug or not but I need to find Distributed Virtual PortGroup searching by vlanid, this is the command that I'm using:
`$ govc find . -type g -config.defaultPortConfig.vlan.vlanid 3064
govc: ServerFaultCode: InvalidProperty`

or in json format:
`$ govc find -json . -type g -config.defaultPortConfig.vlan.vlanid 3064 
{}`

It seems to me that there are some problem with the **vlan** property. I have similar problem also using _object.collect_:

`$ govc object.collect /STO02-DEV/network/vDS-STO02-DEV/PROD3064-10.99.121.0%2f24-Vmware config.defaultPortConfig
config.defaultPortConfig.blocked                  *types.BoolPolicy                                 ...
config.defaultPortConfig.vmDirectPathGen2Allowed  *types.BoolPolicy                                 ...
config.defaultPortConfig.inShapingPolicy          *types.DVSTrafficShapingPolicy                    ...
config.defaultPortConfig.outShapingPolicy         *types.DVSTrafficShapingPolicy                    ...
config.defaultPortConfig.vendorSpecificConfig     *types.DVSVendorSpecificConfig                    ...
config.defaultPortConfig.networkResourcePoolKey   *types.StringPolicy                               ...
config.defaultPortConfig.filterPolicy             *types.DvsFilterPolicy                            ...
config.defaultPortConfig.vlan                     types.BaseVmwareDistributedVirtualSwitchVlanSpec  ...
config.defaultPortConfig.qosTag                   *types.IntPolicy                                  ...
config.defaultPortConfig.uplinkTeamingPolicy      *types.VmwareUplinkPortTeamingPolicy              ...
config.defaultPortConfig.securityPolicy           *types.DVSSecurityPolicy                          ...
config.defaultPortConfig.ipfixEnabled             *types.BoolPolicy                                 ...
config.defaultPortConfig.txUplink                 *types.BoolPolicy                                 ...
config.defaultPortConfig.lacpPolicy               *types.VMwareUplinkLacpPolicy                     ...
config.defaultPortConfig.macManagementPolicy      *types.DVSMacManagementPolicy                     ...
config.defaultPortConfig.vNI`

but with vlan I got InvalidProperty:
`$ govc object.collect /STO02-DEV/network/vDS-STO02-DEV/PROD3064-10.99.121.0%2f24-Vmware config.defaultPortConfig.vlan
govc: ServerFaultCode: InvalidProperty`

I got same errors also with qosTag, uplinkTeamingPolicy, securityPolicy, ipfixEnabled, txUplink, lacpPolicy, macManagementPolicy, vNI but not with the others. It seems that the problem appear starting from vlan property. Could it depends on the fact that _types.BaseVmwareDistributedVirtualSwitchVlanSpec_ doesn't have * prepended like the others properties (_*types.BaseVmwareDistributedVirtualSwitchVlanSpec_)?

I tried with govc version 0.23.0 and 0.24.0

`$ govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      7.0.1
Build:        17327586
OS type:      linux-x64
API type:     VirtualCenter
API version:  7.0.1.1
Product ID:   vpx`

Thanks

**Comment by dougm** [comment]
Some info on this here: https://github.com/vmware/govmomi/issues/1001#issue-288822160

In this case `defaultPortConfig` is base type [DVPortSetting](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.dvs.DistributedVirtualPort.Setting.html) which is extended by [VMwareDVSPortSetting](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy.html)

You'll see govc includes the `Base` in such types:
```console
% govc object.collect ./network/dvpg-vmotion-1 config | grep Base
config.defaultPortConfig             types.BaseDVPortSetting                          ...
config.policy                        types.BaseDVPortgroupPolicy                      ...
```

vCenter allows collection of specific properties in the base type:

```console
% govc object.collect ./network/dvpg-vmotion-1 config.defaultPortConfig.blocked
config.defaultPortConfig.blocked.inherited  bool   true
config.defaultPortConfig.blocked.value      *bool  false
```

But `VMwareDVSPortSetting` specific fields result in `InvalidProperty` from vCenter.  The jq workaround is one option, but haven't looked into how we might workaround this limitation within the object.collect command itself.

**Comment by SerDroide** [comment]
Thanks for the tip, I'll take a look on jq workaround
