### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference while login failed

### ISSUE THREAD

**Issue by runner-mei** [vmware/govmomi#232]
[panic]runtime error: invalid memory address or nil pointer dereference    c:/go/src/pkg/runtime/panic.c:248 runtime.panic
    c:/go/src/pkg/runtime/panic.c:552 runtime.panicstring
    c:/go/src/pkg/runtime/os_windows.c:359 runtime.sigpanic
    C:/tpt_programs/go_3td/src/github.com/vmware/govmomi/session_manager.go:56 github.com/vmware/govmomi.(*SessionManager).Login
    C:/tpt_programs/go_3td/src/github.com/vmware/govmomi/client.go:68 github.com/vmware/govmomi.NewClient

**Comment by pietern** [comment]
This was fixed in ea8d5d112003de2229000c5b57e24c112b6a5bfd.
