### ISSUE TITLE
Unable to use packer vsphere-iso which is based on this project

### ISSUE THREAD

**Issue by juliostanley** [vmware/govmomi#2320]
Hi

Sorry if this is not the proper location for the question, but I have an issue with vsphere-iso as describe here. The gist is that I am unable to upload files other than through the Vcenter HTML 5 GUI.
https://github.com/jetbrains-infra/packer-builder-vsphere/issues/121#issuecomment-802431989

The request used for file uploads when granular datastore permissions are applied on a vcenter cluster, are different when comparing vcenter HTML 5 Client request and the request done by this library (triggered by vsphere-iso)

I am not sure if that is the root cause. Here is an example:

HTML 5 Client: `PUT https://<host>/folder/<foldername>/<somefilename>.flp?dcPath=ha-datacenter&dsName=DataStoreNameAsSeenOnVcenter`

govmomi (via vsphere-iso): `PUT https://<host>/folder/<foldername>/<somefilename>.flp?dcPath=%2FDatacenterNameAsSeenOnVcenter&dsName=DataStoreNameAsSeenOnVcenter`

The situation can be reproduced with `govc datastore.upload`, simply assign a user only privileges to a single datastore in a datastore cluster. The user can upload via HTML 5 GUI but not through cli
```
Datastore -> Low level file operations
Host -> Configuration -> System Management
```

Notice that the vcenter html 5 client uses `dcPath=ha-datacenter` instead of `dcPath=%2FDatacenterNameAsSeenOnVcenter` not sure if that could be related. 

### Edit
Found a more precise difference.

The HTML 5 Upload process obtains a url and ticket before a `PUT`. The `PUT` is done directly to the esxi host (in the url) with a header that contains the ticket number, the dcPath is `ha-datacenter`. This process is not performed by this library, and the `PUT` is attempted directly to vcenter with the dcPath matching the datacenter.
```
ui/actionsService/actions/evaluations?actionUids=vsphere.core.datastore.actions.uploadToDatastore
ui/data/propertiesWithParameters/urn:vmomi:Datastore:datastore-<id>:<guid>?properties=fileTransferEndpoints
----Response like: fileTransferEndpoints [{url,ticket}]   Note url is esxi cluster and dcPath=ha-datacenter
OPTIONS (preflight check)
PUT file transfer url (esxi cluster hostname) with ticket
----Request like: vmware-cgi-ticket: <ticket>
```

Any thoughts?

**Comment by dougm** [comment]
It is possible to use a service ticket to upload directly to an ESX host.  With govc you can for example:
```console
% date | GOVMOMI_USE_SERVICE_TICKET=true govc datastore.upload -ds datastore1 - date.txt
```

That env var should work with packer too, see: https://github.com/vmware/govmomi/blob/a170181dcba758ffe8467b8ccf0520462d926002/object/datastore.go#L120-L125

**Comment by juliostanley** [comment]
Thank you. It does work, and also verified that packer respects the environment variable (since it uses that object directly)
