### ISSUE TITLE
vm.register -template with a cluster

### ISSUE THREAD

**Issue by quulah** [vmware/govmomi#2324]
It seems that `vm.register` currently needs `GOVC_HOST` or `-host` specified for templates. #872

Would it be possible to add support for pointing it towards the cluster? This seems to be possible from the vSphere web UI.

**Comment by dougm** [comment]
The [RegisterVM method](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.Folder.html#registerVm) requires a host to register a template.

We could add something to govc that chooses a random host from a cluster to use for the host param.  In the meantime, something like the following would workaround:
```console
% host=$(govc find /dc1/host/ClusterA -type h | sort -R | head -1)
% govc vm.register -template -host $host path/name.vmx
```
