### ISSUE TITLE
Question about how to use toolbox.Client to run commands on a VM

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2326]
I was trying to use [toolbox.Client](https://github.com/vmware/govmomi/blob/487ce16e3ee3f68da40882f32d42bb175e2646ad/guest/toolbox/client.go#L37) to run commands on a Windows VM, however when executing `toolbox.Client.Run()` I got the following error `ServerFaultCode: The operation is not supported on the object`. I cannot figure out what is the issue with my setup from this error. Could I get some help on this?

I'm not sure if it's an issue with my client, username/password authentication or something else. I don't suspect it's my client, because I can create VMs in vCenter using the same client. I'm using `guest.NewOperationsManager` to create the VM's operations manager to get the process and file managers and setting `toolbox.Client.GuestFamily` to `types.VirtualMachineGuestOsFamilyWindowsGuest`

**Comment by dougm** [comment]
Do you have the same issue against the VM using `govc guest.run ...` ?

If so, we recently added `-trace` and `-verbose` flags to govc that may help shed some light:
https://github.com/vmware/govmomi/tree/master/govc#troubleshooting

**Comment by chardch** [comment]
Thanks for noting the -trace and -verbose options! I realized it was because I was using a VM name that didn't exist. However, I wasn't able to figure this out based on the error code. I'll close this though since the issue in question has been resolved
