### ISSUE TITLE
add guest.ipaddress into metrics

### ISSUE THREAD

**Issue by bubbleatgit** [vmware/govmomi#2338]
Is there have a plan , add guest.ipaddress into metrics `vm/*`？

**Comment by dougm** [comment]
What do you mean by "metrics"?

With govc, you can get guest.ipAddress using:

- `govc vm.info $name`
- `govc vm.ip $name`
- `govc object.collect -s vm/$name guest.ipAddress`

Elsewhere, you can use the same API as the govc commands.
