### ISSUE TITLE
Events generated on creating/updating/deleting a virtual switch

### ISSUE THREAD

**Issue by akankshadokania** [vmware/govmomi#2344]
On creating/updating/deleting a virtual switch, the event received from vCenter is on the host entity. Is there a way to extract the information about the virtual switch from the event?

**Comment by dougm** [comment]
Run `govc events -dump` and you'll see events as Go code.  What does it look like for the event(s) you're interested in?

**Comment by embano1** [comment]
@akankshadokania are you referring to a virtual switch (port group for standard virtual switch) or distributed switch? In case of the former, is a `TaskEvent` what you're seeing, e.g.:

```xml
<TaskEvent>
  <key>4990</key>
  <chainId>4990</chainId>
  <createdTime>2021-04-04T20:17:16.551999Z</createdTime>
  <userName>VSPHERE.LOCAL\Administrator</userName>
  <datacenter>
    <name>vcqaDC</name>
    <datacenter type="Datacenter">datacenter-2</datacenter>
  </datacenter>
  <computeResource>
    <name>cls</name>
    <computeResource type="ClusterComputeResource">domain-c7</computeResource>
  </computeResource>
  <host>
    <name>10.192.193.184</name>
    <host type="HostSystem">host-27</host>
  </host>
  <fullFormattedMessage>Task: Update network configuration</fullFormattedMessage>
  <info>
    <key>task-359</key>
    <task type="Task">task-359</task>
    <name>UpdateNetworkConfig</name>
    <descriptionId>host.NetworkSystem.updateNetworkConfig</descriptionId>
    <entity type="HostSystem">host-27</entity>
    <entityName>10.192.193.184</entityName>
    <state>queued</state>
    <cancelled>false</cancelled>
    <cancelable>true</cancelable>
    <reason>
      <userName>VSPHERE.LOCAL\Administrator</userName>
    </reason>
    <queueTime>2021-04-04T20:17:16.552615Z</queueTime>
    <eventChainId>0</eventChainId>
  </info>
</TaskEvent>
```

For DVS related events, there's proper event notifications. Please let us know which switch/network type and related event you're referring to.

**Comment by akankshadokania** [comment]
@embano1 I was referring to the virtual switch event. As you mentioned, we get a task event that has host information but doesn't tell which virtual switch was impacted.

**Comment by akankshadokania** [comment]
> Run `govc events -dump` and you'll see events as Go code. What does it look like for the event(s) you're interested in?

@dougm It is a task event and the response is as shared by @embano1

**Comment by embano1** [comment]
Thx for clarification. There's nothing govmomi can do about here I think as it seems no proper event is emitted for a standard virtual switch. I have a similar situation with alarms and created a small project for it which can serve as inspiration: https://github.com/embano1/vsphere-alarm-server
