### ISSUE TITLE
Transparent reauthentication of vim25 (soap) client

### ISSUE THREAD

**Issue by ArnoSen** [vmware/govmomi#2347]
I am running a service that makes calls to a vCenter. I want to limit the connection to the vCenter as much as possible. 
Previously I created a new govomi client for each request and now I am making the govmomi client stateful and thereby I expect to save a call that is needed for authentication.

The issue I run into now is that after some time of inactivity (meaning no calls being made to the vCenter), my service is receiving a 'NotAuthenticated' error from the vCenter. I learned that when my session has expired there is no automatic reauthentication. Can you confirm that this is actually the case?

I see 3 options to deal with this:
- implement keepalive: I saw that govc uses this. I can solve my problem accept that when the keepalive call failes for whatever issue (like a restart of vCenter), there is still the risk of ending up in the situation of "NotAuthenticated". I consider this not a real solution
- when i call a govmomi/vim25 method, I check if I get an error and if so I will perform a fresh login. This however requires that I must never forget to add this errorhandling and also when others of my team works on this code, they need to remind themselves also to add the described errorhandling
- the third option I see is what I call transparent reauthentication: this means a roundtripper will intercept 'NotAuthenticated' errors and gets a new session token.

I prefer to use the third method.  At https://github.com/vmware/govmomi/blob/96178d92a41916455c07312013ec6156b47b4717/vim25/client.go#L55 I read it is possible to stick in a custom (soap.) RoundTripper  that can have the capability to reauthenticate. on session timeout. When going through the source code though, I cannot find a pre configured roundtripper that does this. If such a roundtripper exists, can you show me where it is located?

Do you have any other advice/tips how to solve the NonAuthenticated problem after some time on inactivity with consuming a mimimal amount of vCenter connections/resources?

Many thanks in advance.

**Comment by embano1** [comment]
Good assessment of options IMHO. I'm usually ok with keepalive, ie option 1. Whenever I hit NotAuth error I mostly fail-crash (restart with K8s) or handle the error via custom re-auth logic (depending on biz requirements). Keep it simple is what I recommend in general. Example: https://github.com/vmware-tanzu/sources-for-knative/blob/c53036a6200a94450404cbc16902ad245ed821d4/pkg/vsphere/client.go#L88

**Comment by chaneyzorn** [comment]
RoundTripper is a good place to catch error requests, but there are still some requests not be treated as error, such as `find.NewFinder.DatacenterList`.

request response returns as success, and the error included in response body, which unwrapped (by `LoadRetrievePropertiesResponse`, I guess) after RoundTrip.

RoundTripper can't detect those errors wrapped into nornal success response body.

So, keepalive is the only simple way I can think of.
