### ISSUE TITLE
VMware Tools minimum version

### ISSUE THREAD

**Issue by Aishwarya2** [vmware/govmomi#2348]
Hi,

To use VMware Guest authentication, what is the minimum version of VMware tools that is needed?

Thanks

**Comment by dougm** [comment]
Not sure exactly, but the ttylinux image we still use for some testing was built with a tools version from forever ago and still works with all guest operations:

```console
% govc guest.run -vm ttylinux -l root:password /usr/lib/vmware-tools/sbin32/vmtoolsd -v             
VMware Tools daemon, version 9.8.3.37963 (build-2075148)
```

**Comment by Aishwarya2** [comment]
Thank you. I have a follow-up question. What is the minimum vCenter version that govmomi supports ?

**Comment by dougm** [comment]
6.5 , see: https://github.com/vmware/govmomi/blob/master/README.md#compatibility

**Comment by embano1** [comment]
@Aishwarya2 can this issue be closed then?

**Comment by Aishwarya2** [comment]
Yes. Thank you
