### ISSUE TITLE
Automate CHANGELOG

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2369]
Incl guidance on PR naming to easily filter for BUG, GOVC, etc

**Comment by embano1** [comment]
@dougm 

I found a way to generate a `CHANGELOG.md` based on commit message patterns. What do you think about the following?


<a name="v0.25.0"></a>
## [Release v0.25.0](https://github.com/vmware/govmomi/compare/v0.24.1...v0.25.0)

> Release Date: 2021-04-16

### 💫 Simulator (vcsim)

- put verbose logging behind '-trace' flag
- add moid value mapping mappings
- add vsan simulator

### 💫  govc (CLI)

- add vm.customize -dns-suffix flag
- update test images URL
- log invalid NetworkMapping.Name with import.ova command
- revert pretty print pruning optimization
- add library.update command
- add session.ls -S flag
- add tree command
- include sub task fault messages on failure
- remove device.boot -firmware default
- add '-trace' and '-verbose' flags

### Commits

- 6fe8d60a Fix folder write for govc container
- e18b601f docs: update for 0.25 release
- 1ac314c3 govc: add vm.customize -dns-suffix flag
- `[...]`

**Comment by dougm** [comment]
That looks great @embano1 !

**Comment by embano1** [comment]
Note that the (commit) links automatically rendered by Github won't render in the final `CHANGELOG.md`.
Also, the current convention is to use "govc: <message>" or  "vcsim: <message>" in the commit to create the actual grouping. We can define more sub-groups. All other commits (incl. those from groups) would still be listed under the Commits section.
