### ISSUE TITLE
Release tarball contains extraneous Go sources

### ISSUE THREAD

**Issue by jpeach** [vmware/govmomi#2370]
Looking at the 0.25.0 release tarball:

```
$ tar -xvzf govc_Linux_x86_64.tar.gz
CHANGELOG.md
LICENSE.txt
README.md
license/assignment_manager.go
license/manager.go
govc
```

I think that the Go source code under `license/` should be omitted?

**Comment by embano1** [comment]
Good catch! `goreleaser` defaults were a bit too aggressive here :)
