### ISSUE TITLE
guest.run with change password

### ISSUE THREAD

**Issue by dingziyang** [vmware/govmomi#2374]
## env
- vshpere: 6.7
- govc version: govc 0.23.0
- local os: Darwin Kernel Version 18.5.0
- guest os: Centos 7.7-x64

## describe

1. The appadmin account is a preset user in the OVF template. The password policy is as follows. Now, when I use this OVF template to create a VM, the password of appadmin has expired. When I log in for the first time, I need to change my password to execute some commands
2. I use non interactive methods to change the password, such as' chpasswd 'or' - stdin ', but I get an authentication failure error, without exception.
3. When the password must be changed for the first login, how to deal with it with govc, or does govc support interactive command execution ?

## some info
```
  [ local terminal ] govc guest.run -k=true -u https://test:VMware1234@10.37.16.17/sdk -l appadmin:ABcd+12#$ -vm dcm_cmp_test_zabbix_2  'sudo su - && sudo echo appadmin:ABcd+12#$ | chpasswd && su appadmin'
  
  govc: ServerFaultCode: Failed to authenticate with the guest operating system using the supplied credentials.
```

Hope for help，thanks.

**Comment by dougm** [comment]
vmware-tools requires a valid `-l username:password` before it can run any command and doesn't have a way to handle expired password that I know of.

You could try using [vm.keystrokes](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmkeystrokes) to change the password.

**Comment by dingziyang** [comment]
I use it :
```
govc vm.keystrokes -k=true -u  https://test:VMware1234@10.37.16.17/sdk -vm dcm_cent7_clone_1 -s 'touch a.txt'
govc vm.keystrokes -k=true -u  https://test:VMware1234@10.37.16.17/sdk -vm dcm_cent7_clone_1 -c KEY_ENTER
```
but the file 'a.txt' does not found.

**Comment by dingziyang** [comment]
I want to execute some scripts automatically in this way. When I deliver the virtual machine, it seems that if the password fails, I can't do automation, because I can't get around this place.
That's a pity.   =.=

**Comment by lihuawei321** [comment]
> I want to execute some scripts automatically in this way. When I deliver the virtual machine, it seems that if the password fails, I can't do automation, because I can't get around this place.
> That's a pity. =.=

老哥，想问下你是通过代码实现了govc修改密码的操作吗？
