### ISSUE TITLE
Error: expected element type <Envelope> but have <html>

### ISSUE THREAD

**Issue by mijit** [vmware/govmomi#239]
I installed govmomi and set my environment as follows:

    $ env | grep GO
    GOVC_INSECURE=1
    GOVC_URL=https://MYUSER:MYPASSWORD@MYSERVER:9443/sdk
    GOPATH=/usr/local/opt/go/

But "govc about" gives the following:

    $ govc about
    Error: expected element type <Envelope> but have <html>

That error is because my vSphere 5.5 server is returning a 404 on that /sdk endpoint. Same error on ports 8443 and 443.

I know my user, password, and server are working. But am I missing a particular VMware SDK on the server that should be listed as a prerequisite for govmomi? How do I confirm what port on the server is the correct endpoint for govc to talk to?

**Comment by pietern** [comment]
It returns a 404 if you issue a GET. You can see if it is the right one by issuing a dummy POST, like so:

```
$ curl -XPOST -k https://172.16.196.134:443/sdk
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault>
  <faultcode>ClientFaultCode</faultcode>
  <faultstring>
Error returned by expat parser: no element found

while parsing HTTP request before method was determined
at line 1, column 0</faultstring>
</soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>
```

If you can't figure it out, please run govc in debug mode (either by setting `GOVC_DEBUG=1` or by passing the `-debug` flag to `govc about`) and check out `~/.govmomi/debug`. This will contain the request and response traces and maybe contains a clue as to what is going on here.

**Comment by mijit** [comment]
Thanks Pieter, I didn't know about that POST vs GET behavior; that's exactly what I needed to confirm the port and eliminate that from my troubleshooting. I can POST and elicit the same response from my server as you got, but now I'm getting an SSL error:

    Error: Post https://myserver.mydomain.com/sdk/: tls: failed to parse certificate from server: x509: negative serial number

That probably has to do with a self- or internally-signed certificate on my end, so I will close this issue and investigate further, presumably in my system CA bundle or Go certificate path. FWIW, I'm using Mac OS X for this. I'll also try in Linux and will follow up here if I make progress.

Thanks again,
Michael

**Comment by pietern** [comment]
Closing this issue.
