### ISSUE TITLE
vcsim should provide a way to set the initial capacity for a datastore

### ISSUE THREAD

**Issue by protochron** [vmware/govmomi#2390]
When running `vcsim`, I've noticed that when you're looking at cluster-level usage, the amount of free space can vary depending on where you're running `vcsim`! Doing some digging, it looks like `vcsim` makes a syscall to the host system to get the amount of available disk space and uses that as the amount of unused capacity for the underlying datastore. Normally this isn't an issue, but if you happen to run `vcsim` on a machine without a lot of free disk space then it limits what you can do with the simulator.

One way around the issue is to add more datastores, but that isn't really representative of the environment we're trying to simulate. It would be better if there was a way to set the amount of initial capacity in the datastore as either a parameter on the `vcsim` command or as an exposed parameter in `simulator.Model`.

**Comment by embano1** [comment]
Good point as this might also come up when running inside container (namespace isolations), right?

**Comment by dougm** [comment]
@protochron can you review #2428 ?
