### ISSUE TITLE
vm.Runtime.Host nil cast

### ISSUE THREAD

**Issue by yelly** [vmware/govmomi#2392]
Since v0.25.0, I have been getting the following panic pretty often (but not always) when running a simulator in tests:
```
panic: interface conversion: mo.Reference is nil, not *simulator.HostSystem

goroutine 363 [running]:
github.com/vmware/govmomi/simulator.(*VirtualMachine).findDatastore(0xc00082d800, 0xc00048cb41, 0x9, 0x10)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:807 +0x12e
github.com/vmware/govmomi/simulator.(*VirtualMachine).useDatastore(0xc00082d800, 0xc00048cb41, 0x9, 0x23be301)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:813 +0x5a
github.com/vmware/govmomi/simulator.(*VirtualMachine).updateStorage(0xc00082d800, 0x3b3b5b6a, 0x32f8ac0)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:672 +0x3d0
github.com/vmware/govmomi/simulator.(*VirtualMachine).updateDiskLayouts(0xc00082d800, 0x23bb040, 0xc00082d800)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:653 +0x726
github.com/vmware/govmomi/simulator.(*VirtualMachine).removeDevice(0xc00082d800, 0xc000af0990, 0xc000140a00, 0x2, 0x10, 0xc000595040, 0xc000140a00, 0x2, 0x10)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:1261 +0x4d7
github.com/vmware/govmomi/simulator.(*VirtualMachine).configureDevices(0xc00082d800, 0xc000af0990, 0xc000653be8, 0x2060645, 0x6)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:1394 +0xa2a
github.com/vmware/govmomi/simulator.(*VirtualMachine).DestroyTask.func1(0xc000824ea0, 0xc000ccbcd8, 0x7, 0x577f55, 0xc00016c180)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:1617 +0x1b6
github.com/vmware/govmomi/simulator.(*Task).Run.func1(0xc000824ea0, 0xc0008f54e8)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/task.go:112 +0x77
created by github.com/vmware/govmomi/simulator.(*Task).Run
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/task.go:110 +0x205
```
It seems that there is a race somewhere which is causing findDatastore to be called before the host is set.
I haven't managed to get it to consistently reproduce yet, but I'm investigating and will hopefully have a PR soon.

**Comment by embano1** [comment]
Thank you! Did you only notice this in v0.25.0? Looping in @theaugy since he had done some work on locking and concurrency recently.

**Comment by yelly** [comment]
We've been running with v0.23.0 for a long time and never ran into this.
We've also been using v0.24.0 for a bit but I wouldn't rely on that too much.

**Comment by theaugy** [comment]
Is this happening during a particular unit test? If not, any sense of what else is going on?
Is this a template or non-template VM?

Simulator tasks were made async in v0.25. When I implemented this, there were a *lot* of places where it was assumed that by the time the task request returned, the task itself was complete. With synchronous tasks, this was always true. With async tasks, you need to .Wait() on the task to be sure it's complete, _but you often get lucky and it's done by the time you make your next request_, so I had to run the unit tests tens of thousands of times to shake out infrequent races.

So my first guess is that whatever code you're running makes this assumption, and gets away with sometimes, but when it doesn't, you hit this (or other weird behavior that may not necessarily result in a panic).

**Comment by yelly** [comment]
Going over the tests with a critical eye revealed a few places where synchronicity was assumed. Waiting for the tasks seems to have solved the problems.
It might be worth considering treating cases like this more gracefully in the simulator since a real vSphere instance won't crash and burn in the same situations. It was also hard to debug since the simulator traceback is disconnected from the actual test that caused the panic.
I'm pretty confident that #2393 is related, but in that case it revealed a real (albeit minor) bug, so I'm leaving it open so we can get that fixed.
Thank you for your help!
