### ISSUE TITLE
ToSoapFault called for fs.PathError

### ISSUE THREAD

**Issue by yelly** [vmware/govmomi#2393]
Since v0.25.0, I have been getting the following panic pretty often (but not always) when running a simulator in tests:
```
panic: interface conversion: error is *fs.PathError, not soap.soapFaultError

goroutine 419 [running]:
github.com/vmware/govmomi/vim25/soap.ToSoapFault(...)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/vim25/soap/error.go:115
github.com/vmware/govmomi/simulator.(*VirtualMachine).RefreshStorageInfo(0xc000ce2000, 0xc000789200, 0x0, 0x4, 0x0)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/virtual_machine.go:779 +0xcfa
github.com/vmware/govmomi/simulator.(*createVM).Run(0xc000cd18c0, 0xc0008f96c0, 0x332a760, 0xc000b32a00, 0x7f0d8b7ea5b8, 0x0)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/folder.go:444 +0x8d1
github.com/vmware/govmomi/simulator.(*Task).Run.func1(0xc0008f96c0, 0xc000c3c378)
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/task.go:112 +0x77
created by github.com/vmware/govmomi/simulator.(*Task).Run
	~/go/pkg/mod/github.com/vmware/govmomi@v0.25.0/simulator/task.go:110 +0x205
```
There is obviously some underlying problem here, but it is being obscured by a bad cast.
I will submit a PR that fixes the bad cast and will hopefully get some visibility into the actual problem after that.

**Comment by yelly** [comment]
Actually I'm not sure what the expected behaviour is here.
Should we just ignore the error in the same manner an os.Stat error is ignored on 774? Or return some fault?

**Comment by yelly** [comment]
Seems the underlying error is:
`readdirent /tmp/govcsim-ha-datacenter-LocalDS_0-661612983/ha-host_VM0: no such file or directory`
Which is confusing since you would expect the Stat to fail.
Might there be a race with another code path that deletes the directory?

**Comment by dougm** [comment]
Indeed, using `ToSoapFault` is not what we should do there, but not sure what's causing it .. could be the recent change to make tasks async.  Something like below should avoid the panic at least.  We should probably make that a func instead of FileManager method.  Do you have a test you can share that reproduces the problem?

```diff
modified   simulator/virtual_machine.go
@@ -776,7 +776,7 @@ func (vm *VirtualMachine) RefreshStorageInfo(ctx *Context, req *types.RefreshSto
 
 		files, err := ioutil.ReadDir(directory)
 		if err != nil {
-			body.Fault_ = soap.ToSoapFault(err)
+			body.Fault_ = Fault("", ctx.Map.FileManager().fault(directory, err, new(types.CannotAccessFile)))
 			return body
 		}
```

**Comment by yelly** [comment]
The following program is failing pretty quickly and consistently for me with this error:
```go
package main

import (
	"context"

	"github.com/vmware/govmomi"
	"github.com/vmware/govmomi/object"
	"github.com/vmware/govmomi/simulator"
)

func main() {
	ctx := context.Background()

	model := simulator.ESX()
	defer model.Remove()
	model.Create()

	s := model.Service.NewServer()
	defer s.Close()

	c, _ := govmomi.NewClient(ctx, s.URL, true)

	svm := simulator.Map.Any("VirtualMachine").(*simulator.VirtualMachine)
	vm := object.NewVirtualMachine(c.Client, svm.Reference())
	vm.CreateSnapshot(ctx, "a", "b", false, true)
	consolidate := true
	vm.RemoveSnapshot(ctx, "a", false, &consolidate)
}
```

**Comment by dougm** [comment]
Thanks, I can reproduce with that, it is due to tasks being async now.  Quick fix is to wait for your tasks to complete:
```go
	task, _ := vm.CreateSnapshot(ctx, "a", "b", false, true)
	_ = task.Wait(ctx)
	consolidate := true
	task, _ = vm.RemoveSnapshot(ctx, "a", false, &consolidate)
	_ = task.Wait(ctx)
```
We should probably have `model.Remove()` also wait for any pending tasks to complete before removing the datastore directories.

**Comment by ditsuke** [comment]
Can we reopen this?

**Comment by ditsuke** [comment]
/remove-lifecycle-stale
?
