### ISSUE TITLE
Remove dep references

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2394]
@dougm do we still need the `dep` related files in the repo? Not seeing them being used anywhere, but wanted to double-check with you before filing a PR.

**Comment by dougm** [comment]
@embano1 we can drop anything dep related.   @akutz had mentioned this a few days ago too.

**Comment by embano1** [comment]
Perfect, will do!

**Comment by akutz** [comment]
Indeed. We can in fact follow the example I provided the other day with how we do it in other projects that follow the upstream model.
