### ISSUE TITLE
host.info printing "Maintenance Mode" without new line

### ISSUE THREAD

**Issue by cpiment** [vmware/govmomi#2398]
I'm using govc version v0.25.0 and when some of the hosts are on maintenance mode, the result of this command:

` govc host.info '/dc/host/cluster/*'`

Reads this way:

```
Name:                           X.company.com
  Path:                         /dc/host/cluster/X.server.company.com
  Manufacturer:                 HPE
  Logical CPUs:                 44 CPUs @ 2095MHz
  Processor type:               Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz
  CPU usage:                    156 MHz (0.2%)
  Memory:                       786084MB
  Memory usage:                 7155 MB (0.9%)
  Boot time:                    2021-04-27 06:09:37.130746 +0000 UTC
  State: Maintenance ModeName:  Y.company.com
  Path:                         /dc/host/cluster/X.server.company.com
  Manufacturer:                 HPE
  Logical CPUs:                 44 CPUs @ 2095MHz
  Processor type:               Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz
  CPU usage:                    40429 MHz (43.9%)
  Memory:                       786084MB
  Memory usage:                 338520 MB (43.1%)
  Boot time:                    2020-08-02 18:03:10.532999 +0000 UTC
  State:                        connected
```
The last line (State) gets mixed with the first line of the next host of the cluster.

I think that the problem is the lack of the new-line character in this line of code:

https://github.com/vmware/govmomi/blob/82b771e4e219cd826d73291913eb2291ff2d8bfd/govc/host/info.go#L156

Which is present in the following line:

https://github.com/vmware/govmomi/blob/82b771e4e219cd826d73291913eb2291ff2d8bfd/govc/host/info.go#L158

Should I open a PR with this change? It feels kind of silly, but is bugging me in my host.info listings 😅

**Comment by dougm** [comment]
Not silly at all, please do open a PR!

**Comment by cpiment** [comment]
Thanks, I have just opened the PR.
