### ISSUE TITLE
How to get paginated results while fetching Virtual Machines summary?

### ISSUE THREAD

**Issue by shghadge** [vmware/govmomi#2409]
```
var vms []mo.VirtualMachine
err = view.Retrieve(ctx, []string{"VirtualMachine"}, []string{"datastore", "network", "resourceConfig", "resourcePool", "config", "summary"}, &vms)
if err != nil {
	return err
}
```
I am trying to fetch info about vms with that many properties. I have about 300 vms in a vCenter and it is taking too much time.
Is there any way to get paginated results?

**Comment by dougm** [comment]
We don't have a concise example, but you can have a look at how `govc object.save` does this. Setting `MaxObjects` here: https://github.com/vmware/govmomi/blob/06a88b327a527a3ae3e009b459dae3ee18bdd8e0/govc/object/save.go#L211-L214

ContainerView in the SpecSet (though you use the code from inside `ContainerView.Retrieve` instead):
https://github.com/vmware/govmomi/blob/06a88b327a527a3ae3e009b459dae3ee18bdd8e0/govc/object/save.go#L255-L267

Then loop using `ContinueRetrievePropertiesEx`:
https://github.com/vmware/govmomi/blob/06a88b327a527a3ae3e009b459dae3ee18bdd8e0/govc/object/save.go#L349-L366

Have also considered adding an option to `ContainerView.Retrieve` to enable this in a generic/simple way, but we don't have that yet.

**Comment by shghadge** [comment]
@dougm Thanks man. I will try this out.

**Comment by embano1** [comment]
Feel free to close this issue then @shghadge
