### ISSUE TITLE
how can  i get information about vcenter HA,vmotion and drs 

### ISSUE THREAD

**Issue by fuluomin** [vmware/govmomi#2419]
i want to get vcenter ha,vmotion,drs information,have this function?thank you

**Comment by embano1** [comment]
There's no cluster.info but you can use this trick: https://github.com/vmware/govmomi/issues/1134#issuecomment-390207365

**Comment by fuluomin** [comment]
> There's no cluster.info but you can use this trick: [#1134 (comment)](https://github.com/vmware/govmomi/issues/1134#issuecomment-390207365)
> 
> ```
> $ govc find / -type c | xargs -n1 govc object.collect -json | jq '.[]|select(.Name=="configuration")|.Val|.DasConfig.Enabled,.DrsConfig.Enabled'
> ```
> 
> Related: [#2267 (comment)](https://github.com/vmware/govmomi/issues/2267#issuecomment-774525131)

DasConfig.Enabled is the enabled information of HA?

**Comment by embano1** [comment]
> DasConfig.Enabled is the enabled information of HA?

Yes
