### ISSUE TITLE
govc events with long listing format doesn't show the username who cause that event

### ISSUE THREAD

**Issue by lihtian285** [vmware/govmomi#2420]
Example of using the ```govc events -l -json``` , the output doesn't show who is the initiator or "who cause the event". 

Is there a way to show the event initiator?

```
}
{
  "Type": "VmMigratedEvent",
  "CreatedTime": "2021-05-07T05:29:08.48Z",
  "Category": "info",
  "Message": "Migration of virtual machine grafana_rh from ipcesxup1m02.mpcmgt1.pc.ecs.hp.com, NL-MgmtDS002 to ipcesxup1m01.mpcmgt1.pc.ecs.hp.com, NL-MgmtDS002 completed"
}
{
  "Type": "VmMigratedEvent",
  "CreatedTime": "2021-05-07T05:48:02.927Z",
  "Category": "info",
  "Message": "Migration of virtual machine grafana_rh1 from ipcesxup1m02.mpcmgt1.pc.ecs.hp.com, NL-MgmtDS002 to ipcesxup1m02.mpcmgt1.pc.ecs.hp.com, SSD-MgmtTemplate1 completed"
}
```

**Comment by embano1** [comment]
Right now, the output from govc events is limited. Definitely a valid question and PR idea :)

You could hack this example https://github.com/vmware/govmomi/tree/master/examples/events.

Alternatively, you could use something like https://vmweventbroker.io [1] for event introspection and automation.

[1]
https://youtu.be/udewtoqfU7I
