### ISSUE TITLE
Link broken in govc readme file

### ISSUE THREAD

**Issue by nikhilkathare** [vmware/govmomi#2421]
https://github.com/vmware/govmomi/tree/master/govc

The link under title "Projects using govc" with name "Kubernetes vSphere Provider" is broken.

**Comment by nikhilkathare** [comment]
Even the link in main readme file is broken : https://github.com/vmware/govmomi

Under Title "Projects using govmomi" link "Kubernetes"

**Comment by nikhilkathare** [comment]
I can file PR.

Looks like it has been deprecated with Deprecation notice.
Ref : https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider

Also : https://github.com/kubernetes/enhancements/issues/670

If I can get the confirmation for removal of link I can raise PR by removing the link at both location ?

**Comment by embano1** [comment]
This projects supersedes the in-tree VCP: https://github.com/kubernetes/cloud-provider-vsphere

**Comment by nikhilkathare** [comment]
Sure.. Got it.. thanks..Will Raise the PR.
