### ISSUE TITLE
"certificate signed by unknown authority" even though browser shows no issue

### ISSUE THREAD

**Issue by galgalesh** [vmware/govmomi#2424]
When running govc it says the certificate of vcenter is signed by an unknown authority even though this is a regular CA known by my operating system.

I confirmed with govc about.cert that govc sees the same certificate as my browser. The CA is trusted by my OS and browser, but not by govc. Is there a way to make govc use the system CA's?

**Comment by galgalesh** [comment]
(version 0.25.0)

**Comment by embano1** [comment]
By default `govc` uses the system certs, e.g. https://golang.org/src/crypto/x509/root_linux.go on Linux or https://golang.org/src/crypto/x509/root_darwin.go on OSX.

Depending on your OS, this is configurable (see comment https://golang.org/pkg/crypto/x509/#SystemCertPool)
If this all does not help, you can tell `govc` to use specific cert files: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md
