### ISSUE TITLE
I use "esxi.Runtime.HealthSystemRuntime.SystemHealthInfo.NumericSensorInfo[i].Name" to get fan's name,but I get   "System Board 1 Fan1 --- Normal" ,"System Board 1 Fan Redundancy 0 - Fully redundant"

### ISSUE THREAD

**Issue by fuluomin** [vmware/govmomi#2429]
i get "System Board 1 Fan1 --- Normal" ,i only want to get "system board 1 fan1",what's the rule of this string,  fan's name --- statue? or  "System Board 1 Fan Redundancy 0 - Fully redundant"    fan's name - Fully redundant? have any other string rules?

**Comment by dougm** [comment]
https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.host.NumericSensorInfo.html

> The name of the physical element associated with the sensor It consists of a string of the form: "description --- state/identifer".

**Comment by fuluomin** [comment]
> https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.host.NumericSensorInfo.html
> 
> > The name of the physical element associated with the sensor It consists of a string of the form: "description --- state/identifer".

but I get one name is "System Board 1 Fan Redundancy 0 - Fully redundant",this is only "-" not "---",that's why
