### ISSUE TITLE
how can i get vcenter entity,Datacenter upper level entity

### ISSUE THREAD

**Issue by fuluomin** [vmware/govmomi#2430]

**Comment by dougm** [comment]
I don't understand the question, can you elaborate?

**Comment by erik-telesoftas** [comment]
I would guess the question here (and we encountered the same):

Once one finds Virtual Machine and retrieved it's properties - how it would be possible to know what Datacenter it belongs to?

Currently they only way we see is to start listing machines by Datacenter.

**Comment by dougm** [comment]
I see, thanks @erik-telesoftas . Yes, that works and we could probably add a helper function to make it simpler.

**Comment by fuluomin** [comment]
> I would guess the question here (and we encountered the same):
> 
> Once one finds Virtual Machine and retrieved it's properties - how it would be possible to know what Datacenter it belongs to?
> 
> We found this solution which seems to work for us: #1334

ok,thank you

**Comment by embano1** [comment]
@fuluomin is this issue resolved?
