### ISSUE TITLE
http: panic serving 127.0.0.1:48122: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shyamala0713** [vmware/govmomi#2440]
I am not able to access PerfCounterInfo of an entity using Performance Manager for vcsim. Please find below the logs. I am using go version go1.15.5 linux/amd64 .Any help is much appreciated.

goroutine 98 [running]:
net/http.(*conn).serve.func1(0xc0013a40a0)
        /usr/lib/golang/src/net/http/server.go:1801 +0x147
panic(0xdb4700, 0x17ced70)
        /usr/lib/golang/src/runtime/panic.go:975 +0x47a
github.com/vmware/govmomi/simulator.(*PerformanceManager).QueryPerfCounter(0xc000262000, 0xc0019bad80, 0xc001373300, 0x0, 0x0)
        /root/go/src/github.com/vmware/govmomi/simulator/performance_manager.go:82 +0x9d
reflect.Value.call(0xf49d80, 0xc000262000, 0xa13, 0xfcb298, 0x4, 0xc001298720, 0x2, 0x2, 0x0, 0x30, ...)
        /usr/lib/golang/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xf49d80, 0xc000262000, 0xa13, 0xc001298720, 0x2, 0x2, 0xc0003b4120, 0x12, 0xc0003271a0)
        /usr/lib/golang/src/reflect/value.go:337 +0xb9
github.com/vmware/govmomi/simulator.(*Service).call.func1()
        /root/go/src/github.com/vmware/govmomi/simulator/simulator.go:216 +0x65
github.com/vmware/govmomi/simulator.(*Registry).WithLock(0xc00026a360, 0x7efd9082e9e8, 0xc000262000, 0xc0019916f8)
        /root/go/src/github.com/vmware/govmomi/simulator/registry.go:589 +0x47
github.com/vmware/govmomi/simulator.(*Service).call(0xc00164cae0, 0xc0019bad80, 0xc0017ea300, 0x200, 0xc0017ea300)
        /root/go/src/github.com/vmware/govmomi/simulator/simulator.go:215 +0x625
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc00164cae0, 0x1163f00, 0xc0013f36c0, 0xc0019aa300)
        /root/go/src/github.com/vmware/govmomi/simulator/simulator.go:472 +0x42c
net/http.HandlerFunc.ServeHTTP(0xc0015667f0, 0x1163f00, 0xc0013f36c0, 0xc0019aa300)
        /usr/lib/golang/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x18832a0, 0x1163f00, 0xc0013f36c0, 0xc0019aa300)
        /usr/lib/golang/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0019dad20, 0x1163f00, 0xc0013f36c0, 0xc0019aa300)
        /usr/lib/golang/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0013a40a0, 0x1165c40, 0xc00116a040)
        /usr/lib/golang/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:2969 +0x36c
2021/05/17 11:00:11 http: panic serving 127.0.0.1:48138: runtime error: invalid memory address or nil pointer dereference
goroutine 123 [running]:
net/http.(*conn).serve.func1(0xc0013a4140)
        /usr/lib/golang/src/net/http/server.go:1801 +0x147
panic(0xdb4700, 0x17ced70)
        /usr/lib/golang/src/runtime/panic.go:975 +0x47a
github.com/vmware/govmomi/simulator.(*PerformanceManager).QueryPerfCounter(0xc000262000, 0xc0019baf30, 0xc001373ec0, 0x0, 0x0)
        /root/go/src/github.com/vmware/govmomi/simulator/performance_manager.go:82 +0x9d
reflect.Value.call(0xf49d80, 0xc000262000, 0xa13, 0xfcb298, 0x4, 0xc001298cf0, 0x2, 0x2, 0x0, 0x30, ...)
        /usr/lib/golang/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xf49d80, 0xc000262000, 0xa13, 0xc001298cf0, 0x2, 0x2, 0xc0003b4120, 0x12, 0xc0003271a0)
        /usr/lib/golang/src/reflect/value.go:337 +0xb9
github.com/vmware/govmomi/simulator.(*Service).call.func1()
        /root/go/src/github.com/vmware/govmomi/simulator/simulator.go:216 +0x65
github.com/vmware/govmomi/simulator.(*Registry).WithLock(0xc00026a360, 0x7efd9082e9e8, 0xc000262000, 0xc001acb6f8)
        /root/go/src/github.com/vmware/govmomi/simulator/registry.go:589 +0x47
github.com/vmware/govmomi/simulator.(*Service).call(0xc00164cae0, 0xc0019baf30, 0xc0017ea500, 0x200, 0xc0017ea500)
        /root/go/src/github.com/vmware/govmomi/simulator/simulator.go:215 +0x625
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc00164cae0, 0x1163f00, 0xc0013f3b20, 0xc0019aab00)
        /root/go/src/github.com/vmware/govmomi/simulator/simulator.go:472 +0x42c
net/http.HandlerFunc.ServeHTTP(0xc0015667f0, 0x1163f00, 0xc0013f3b20, 0xc0019aab00)
        /usr/lib/golang/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x18832a0, 0x1163f00, 0xc0013f3b20, 0xc0019aab00)
        /usr/lib/golang/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0019dad20, 0x1163f00, 0xc0013f3b20, 0xc0019aab00)
        /usr/lib/golang/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0013a4140, 0x1165c40, 0xc001373580)
        /usr/lib/golang/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/lib/golang/src/net/http/server.go:2969 +0x36c

**Comment by dougm** [comment]
@shyamala0713 see #2472

**Comment by shyamala0713** [comment]
@dougm I made the changes to the files performace/manager.go and simulator/performance_manager.go as done and committed by you. But getting the below exception as I faced earlier, when trying to access the QueryPerfCounter method of performace_manager.go file. Please find below the error logs:

62442 [pool-5-thread-2] DEBUG com.vmware.vim25.ws.WSClient  - Caught an IOException. Reading ErrorStream for results.
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at com.vmware.vim25.ws.WSClient.getInputStreamFromConnection(WSClient.java:187)
        at com.vmware.vim25.ws.WSClient.post(WSClient.java:174)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:94)
        at com.vmware.vim25.ws.VimStub.queryPerfCounter(VimStub.java:1437)

Please let me know how to fix this issue.
