### ISSUE TITLE
Keep alive a vCenter session

### ISSUE THREAD

**Issue by Aishwarya2** [vmware/govmomi#2441]
Hello,

Is there a mechanism to keep alive a vCenter session for using VMware guest auth using govmomi ?

Basically, my use case is to execute a long running script on a guest VM in vCenter.

Thanks

**Comment by embano1** [comment]
Yes, take a look at https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/session/keepalive/handler.go

**Comment by aruneshpa** [comment]
@Aishwarya2 , depending on what type of client you want to use (REST, or SOAP), you should be able to specify a keepalive handler when you create the client.  If you do not specify any, govmomi will use the default one ([keepAliveSOAP](https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/session/keepalive/handler.go#L79) or [keepAliveREST](https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/session/keepalive/handler.go#L85)). 

You can also provide your custom handler function if you want to perform certain actions in specific scenarios (e.g., if the connection to vCenter server is down long enough that it causes your session to expire, you might choose to log the client back in).

When you login the client, the keepalive handlers will start (until you call `Logout`).

For example:

```go
import	(
    "github.com/vmware/govmomi/vapi/rest"
    "github.com/vmware/govmomi/session/keepalive"
)

func (c *vim25.Client) {
    restClient := rest.NewClient(c)
    restClient.Transport = keepalive.NewHandlerREST(restClient, idleTime, func() error {
        // Your custom logic for the handler
    })

    // To start the handler:
    restClient.Login(...)
}
```
