### ISSUE TITLE
[Question] Is there a way to detect a client device cdrom on a VM?

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2444]
Hi, I was wondering if there's a way to detect the a cdrom client device in passthrough mode? I was trying to use the backing type to do this like in the code snippet below, but it only detects a cdrom client device in emulate cdrom mode. Is there another way I can go about checking for a passthrough cdrom client device like I can in the UI?![Screen Shot 2021-05-18 at 12 07 59 PM](https://user-images.githubusercontent.com/47097484/118709411-c66cd080-b7d1-11eb-8f46-9e55bb24d84e.png)

```
devices := object.VirtualDeviceList(vmProps.Config.Hardware.Device)
cds := devices.SelectByType((*types.VirtualCdrom)(nil))
for _, cd := range cds {
    switch cd.GetVirtualDevice().Backing.(type) {
        // I was trying to use this to detect a CDRom in client device mode, but this only works when the mode is Emulate CD-Rom, not Passthrough CD-Rom
        case *types.VirtualCdromRemoteAtapiBackingInfo:
            ...
    }
}
```

**Comment by chardch** [comment]
Sorry I didn't mean to add the feature label, but can't remove it

**Comment by dougm** [comment]
Looks like you could check for [VirtualCdromRemotePassthroughBackingInfo]( https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.device.VirtualCdrom.RemotePassthroughBackingInfo.html)

**Comment by chardch** [comment]
Got it, that worked!

On another note, if we add an iso as cdrom as the secondary IDE device (e.g. IDE(0:1) or IDE(1:1)), it won't show up in the vm. Is that expected?

**Comment by chardch** [comment]
Also, another question. How do we know if it should be `VirtualCdromRemotePassthroughBackingInfo` vs `VirtualCdromPassthroughBackingInfo`?

**Comment by dougm** [comment]
I don't know of an issue with secondary device, are both set to `Connected`?
Not sure what you mean in the second question.   Haven't used passthrough cdrom myself either.
btw, you can see the cdrom device config as Go code using:

```go
// % govc device.info -vm $vm -dump cdrom-*                                                                                               
device.infoDevice{
    Name:              "cdrom-3000",
    Type:              "VirtualCdrom",
    BaseVirtualDevice: &types.VirtualCdrom{
        VirtualDevice: types.VirtualDevice{
            Key:        3000,
            DeviceInfo: &types.Description{
                Label:   "CD/DVD drive 1",
                Summary: "Remote device",
            },
            Backing: &types.VirtualCdromRemotePassthroughBackingInfo{
                VirtualDeviceRemoteDeviceBackingInfo: types.VirtualDeviceRemoteDeviceBackingInfo{
                    VirtualDeviceBackingInfo: types.VirtualDeviceBackingInfo{},
                    DeviceName:               "",
                    UseAutoDetect:            types.NewBool(false),
                },
                Exclusive: false,
            },
            Connectable: &types.VirtualDeviceConnectInfo{
                MigrateConnect:    "",
                StartConnected:    false,
                AllowGuestControl: true,
                Connected:         false,
                Status:            "ok",
            },
            SlotInfo:      nil,
            ControllerKey: 200,
            UnitNumber:    types.NewInt32(0),
        },
    },
}
```

**Comment by chardch** [comment]
Thanks for the info. 
Both are set to connected, but for some reason the secondary drive on any IDE (`IDE(0:1)`, `IDE(1:1)`) doesn't show up inside the VM
