### ISSUE TITLE
Possible to use toolbox instead of vmware-rpctool?

### ISSUE THREAD

**Issue by robertkaelin** [vmware/govmomi#2450]
Hi, I have found this repo after looking for a golang implementation of `vmware-rpctool`.
One quick Question which I was not able to really figure out after looking at the code.

Would it be possible to programatically run the command `vmware-rpctool info-get guestinfo.userdata` inside a VM by using toolbox (or another lib in this repo)?
The goal would be to get the information, but actually not rely on `vmware-rpctool`, just use a golang-executable in the end which has this `info-get` functionality.

Many thanks for any help or pointers.

**Comment by dougm** [comment]
Yes, govmomi/toolbox not needed for this, you can use vmw-guestinfo directly from Go, example here: https://github.com/vmware/vmw-guestinfo/blob/687661b8bd8e72a55ac988ecdb2a1cdef76fa78d/examples/main.go#L68

**Comment by robertkaelin** [comment]
Awesome, this is exactly what I was looking for.
Thank you very much @dougm! :)
