### ISSUE TITLE
How I can do run code in vm, without govc ?

### ISSUE THREAD

**Issue by ahmtxonly** [vmware/govmomi#2458]
How can I run the following code on the virtual machine, without using govc?

`echo "linuxpassword" | passwd --stdin linuxuser`
or
`./runscipt.sh`

I'm stuck on this

I'm trying to learn the logic of using govc commands outside.

**Comment by embano1** [comment]
Just to understand: you don't (can't) want to use govc and are looking for a programmatic approach using the govmomi SDK?

**Comment by ahmtxonly** [comment]
Yes I don't want to use govc, I want make a managed virtual server system with control panel

**Comment by embano1** [comment]
Please check out https://github.com/vmware/govmomi/tree/v0.25.0/toolbox and https://github.com/vmware/govmomi/blob/master/guest/process_manager.go then.

**Comment by ahmtxonly** [comment]
Thank you so much for this;

Any chance to provide a very small code sample for me? in order to progress in a healthy way @embano1 
I did a lot of research and couldn't find any helpful resources.

**Comment by dougm** [comment]
@ahmtxonly example of Clone here: https://github.com/vmware/govmomi/blob/fcc3c80e551b01569a50c7473dcf30282b1702c1/object/example_test.go#L227

And changing network settings via Customize here: https://github.com/vmware/govmomi/blob/fcc3c80e551b01569a50c7473dcf30282b1702c1/object/example_test.go#L97

Example of running guest commands in the `govc guest.run` source: https://github.com/vmware/govmomi/blob/fcc3c80e551b01569a50c7473dcf30282b1702c1/govc/vm/guest/run.go#L75-L99

**Comment by ahmtxonly** [comment]
> Example of running guest commands in the `govc guest.run` source:
> 
> https://github.com/vmware/govmomi/blob/fcc3c80e551b01569a50c7473dcf30282b1702c1/govc/vm/guest/run.go#L75-L99

![image](https://user-images.githubusercontent.com/36918073/119411114-90a87a00-bcf2-11eb-9c3c-fc3e731278d2.png)

I could not start it
