### ISSUE TITLE
govmomi returning empty string for virtual machine hardware version 

### ISSUE THREAD

**Issue by abhaygupta97** [vmware/govmomi#2465]
I am trying to determine virtual machine hardware version. I have a vm := *vmwar.govmomi.vim25.mo.VirtualMachine object. When I do:
1. vm.Config.Version
2. vm.Summary.Config.HwVersion

I am getting empty strings as output. I am on ESXi version 6.5.0. How can I determine virtual machine hardware version using VirtualMachine object?

**Comment by dougm** [comment]
You need to use the PropertyCollector to get this fields, there's an example here which includes the `Config.Version` property: https://pkg.go.dev/github.com/vmware/govmomi/property#example-Collector.RetrieveOne

**Comment by abhaygupta97** [comment]
It worked. Thanks Doug!!
