### ISSUE TITLE
Add govc commands to patch the vCenter Server Appliance (VCSA)

### ISSUE THREAD

**Issue by fxl90** [vmware/govmomi#2486]
**Is your feature request related to a problem? Please describe.**
I would like to use govc to patch the vCenter Server Appliance. The manual steps and the rest calls needed are listed in the following documentation: 

- https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vcenter.upgrade.doc/GUID-E2E359B1-5834-4BFF-AEFE-6CEBFC8CC3D5.html
- https://developer.vmware.com/docs/vsphere-automation/latest/appliance/update/

**Describe the solution you'd like**
I would like to run commands like the following to perform patching steps:

- govc vcsa.update.list
- govc vcsa.update.get {version}
- govc vcsa.update.stage {version}
- govc vcsa.update.precheck {version}
- govc vcsa.update.install {version}
- govc vcsa.update.validate {version}
- govc vcsa.update.staged.status
- govc vcsa.update.staged.delete {version}

**Describe alternatives you've considered**
I have considered writing this in go and python using the rest apis. The manual method in the doc listed above also works.

**Additional context**

**Comment by embano1** [comment]
Thx @fxl90 ! Are you interested in writing a PR for this?

**Comment by pradeep288** [comment]
@embano1 am interested to work on this.

**Comment by embano1** [comment]
@pradeep288 awesome, go for it!
