### ISSUE TITLE
extraconfig does not handle large content

### ISSUE THREAD

**Issue by briner** [vmware/govmomi#2488]
**Describe the bug**

We are trying to use govc to load some heavy data. This works well through the html5 webui.  The content is 394'888 caracter long

**To Reproduce**

```bash
# generate a very long extraconfig
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 394888  | head -n 1 > long_extraconfig
# try to use it
govc vm.change -vm soca-lab-govc-test -e test.extraconfig.with.long.extraconfig=$(long_extraconfig)
  # -bash: /home/beef/bin/govc: Argument list too long
```

As you can see, we got an error from the bash, as the extraconfig is way too long

**Expected behavior**
It could be a good idea to provide this lengthy content through a file instead of using the shell to do so
```bash
govc vm.change -vm soca-lab-govc-test -extraconfig-file test.extraconfig.with.long.extraconfig=./long_extravars
```
**Affected version**
```bash
govc version
  # govc 0.25.0
```

**Comment by fortinj66** [comment]
Same issue loading large ignite files for Fedora CoreOS

**Comment by dougm** [comment]
Good suggestion @briner , we can add a `-extraconfig-file` flag.  Just need to use a different `flag.Value`
 interface impl. 
 The current one is here: https://github.com/vmware/govmomi/blob/5dace8100c85cafd69ac7f4148549aaa6cf4ea76/govc/vm/change.go#L37-L44

**Comment by dougm** [comment]
@tanayk2610 existing tests here: https://github.com/vmware/govmomi/blob/5dace8100c85cafd69ac7f4148549aaa6cf4ea76/govc/test/vm.bats#L87

**Comment by Okeanos** [comment]
I also just ran into this problem. The root cause is the `ARG_MAX` definition (see [here](https://www.in-ulm.de/~mascheck/various/argmax/) for more details) which varies wildly between different operating systems. macOS for example has a generous `getconf ARG_MAX` value of `262144 bytes` whereas Windows stops at a lousy `32000 bytes`.

Being able to load from file would be a huge blessing and make this way more robust and reproducible across platforms.

**Comment by RyanMillerC** [comment]
Also hitting this with large base64 encoded files that upload fine through HTML5 GUI but fail with `Argument list too long` due to `ARG_MAX` through govc.

**Comment by Okeanos** [comment]
I don't want to sound annoying but could we get some information on when this change might be expected?

**Comment by embano1** [comment]
@tanayk2610 would you be willing to look into this for the next release?
