### ISSUE TITLE
[BUG] govmomi connection successfully but still popup errors showing password error

### ISSUE THREAD

**Issue by jenningsloy318** [vmware/govmomi#2498]
**Describe the bug**
```

func NewVMClient(context context.Context, vcHost string, username string, password string) *VMClient {

	vcURL, err := soap.ParseURL(fmt.Sprintf("https://%s", vcHost))

	if err != nil {
		log.Errorf("error when parsing the vCenter URL, %v", err)
		return nil
	}

	vcURL.User = url.UserPassword(username, password)

	newVcClient, err := govmomi.NewClient(context, vcURL, true)

	if err != nil {
		log.Errorf("error when creating new vCenter client, %v", err)
		return nil
	}

	err = newVcClient.Login(context, vcURL.User)
	if err != nil {
		log.Errorf("error when trying to login on vCenter, %v", err)
       
	}
	return &VMClient{
		ctx:           context,
		govmomiClient: newVcClient,
	}
}
```

I used this code to create a new connection to my vsphere environment, everytime it always pop error at 
```
	err = newVcClient.Login(context, vcURL.User)
```
error is :
```
error when trying to login on vCenter, ServerFaultCode: Cannot complete login due to an incorrect user name or password.  
```

normally here I need to `return nil` to terminate the excution, but accidently I found that,  by removing  `return nil` statement, just return this client, and this client is still working 

**To Reproduce**
beside the error above, I used the client to get vcenter HOSTS/VM/datastore 
 all the info can be retrieved

code can be found at https://github.com/jenningsloy318/vsphere_exporter/tree/main/vmware 

**Expected behavior**
no error as it can be succedd.

**Affected version**
in my go.mod, the config is 
```
github.com/vmware/govmomi v0.26.0
```
**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

vcenter is deployed as VCSA 6.7

**Comment by dougm** [comment]
`govmomi.NewClient` already called `Login()`and vCenter returns that error when you call `Login` the 2nd time with a valid session cookie: https://github.com/vmware/govmomi/blob/66b9538af589335e414a59ac8f046801947a64ff/client.go#L76-L77

If you leave `vcURL.User` as `nil`, then `govmomi.NewClient` will not call Login.

**Comment by jenningsloy318** [comment]
@dougm thank you pointing out this , I didn't notice that.
