### ISSUE TITLE
[Question]: Code to get the vm status hosted on Vcenter Version 6.X & 7.X

### ISSUE THREAD

**Issue by Imboncy** [vmware/govmomi#2500]
**Getting the VM status using go sdk for vmware:**

-  Hi, I wanted to perform some operations like getting the vm status hosted on Vcenter using go sdk but could not find the guide/docs for the functions that i can use. It'll be helpful if someone can guide me through the code - how to establish the connetion and get the vm status using go sdk.
Thanks!

**Comment by embano1** [comment]
Hi @Imboncy, please take a look at the examples provided here: https://github.com/vmware/govmomi/tree/master/examples
