### ISSUE TITLE
govc log in virtual machine

### ISSUE THREAD

**Issue by lihuawei321** [vmware/govmomi#2504]
Can govc log in to the virtual machine on vSphere(Vcenter) without a username and password?

**Comment by embano1** [comment]
Can you please provide an example what you tried and how/whether it failed?

**Comment by lihuawei321** [comment]
```

		tools, err := toolbox.NewClient(ctx, c, vm, &types.NamePasswordAuthentication{
			Username: "user",
			Password: "pass",
		})

```
here~ 
If I don't use username and password, how can I log in?

**Comment by embano1** [comment]
> If I don't use username and password, how can I log in?

Do you mean empty user/password or a different auth scheme, i.e. != user/pass auth?

**Comment by dougm** [comment]
As mentioned here: https://github.com/vmware/govmomi/issues/2374#issuecomment-822968948
vmware-tools requires a valid username+password for guest operations, there isn't anything govmomi can do to workaround that.

**Comment by steakknife** [comment]
If you don't care about security at all, the following allows vmtools to impersonate any user on a Linux box without a password.

On guest VM: `echo 'account required pam_permit.so' | sudo tee /etc/pam.d/vmtoolsd >/dev/null` 

On admin console: `govc guest.ls -vm yourbox.host.name -l root: /`
