### ISSUE TITLE
[BUG] 500 server error when deploying a VM from an OVF in Content Library

### ISSUE THREAD

**Issue by eraserpencil** [vmware/govmomi#2508]
I get this error `./govc: POST https://customdomain.com/rest/com/vmware/vcenter/ovf/library-item/id:3337eac0-d49c-4cf8-be7b-0a3a67e39301?~action=deploy: 500 Server Error` when executing this command: `./govc library.deploy -options=json_store/pgsql_base.json /Content_Library/base_img pgsql_base`
 where `json_store/pgsql_base.json` is:
 
    {
        "DiskProvisioning": "thick",
        "IPAllocationPolicy": "dhcpPolicy",
        "IPProtocol": "IPv4",
        "PropertyMapping": [
            {
                "Key": "instance-id",
                "Value": "id-ovf"
            },
            {
                "Key": "hostname",
                "Value": ""
            },
            {
                "Key": "seedfrom",
                "Value": ""
            },
            {
                "Key": "public-keys",
                "Value": ""
            },
            {
                "Key": "user-data",
                "Value": "some base64 data"
            },
            {
                "Key": "password",
                "Value": ""
            }
        ],
        "NetworkMapping": [
            {
                "Name": "VM Network",
                "Network": "Test Network"
            }
        ],
        "MarkAsTemplate": false,
        "PowerOn": true,
        "InjectOvfEnv": false,
        "WaitForIP": false,
        "Name": "pgsql_base"
    }

`/Content_Library/base_img` is an OVF template I generated and stored in `/Content_Library` with:

First creating a VM, 
`./govc library.deploy -options=json_store/base.json /Content_Library/ubuntu-18.04-server-cloudimg-release-20210623-amd64 base_img`
Followed by cloning that VM to an OVF format into `/Content_Library`
`./govc library.clone -ovf -vm base_img /Content_Library base_img`

The difference in `json_store/base.json` and `json_store/pgsql_base.json` is the base64 data and the `Name`. Everything else remains the same.

**Expected behavior**
Well, I had hoped to create a VM.

**Affected version**
v0.26.0

**Additional context**
The VM pgsql_base was created for a moment before the error was printed out.
There might be a link to https://github.com/hashicorp/terraform-provider-vsphere/issues/1345, but I am unsure how to resolve it.

The base_img is powered on to run some setup scripts, create users, setup the network etc, before being powered down and the pgsql_base steps continue. I did have one run where no VMs were powered on (meaning no setup scripts were executed) and cloned. The pgsql_base image had no issue being created then, but the resultant VM isn't what I was looking for.

**Comment by dougm** [comment]
@eraserpencil not sure what the issue is, can you reproduce and include the output of library.deploy with the `-trace` flag?
That will give us more detail on the client request, but with a 500 error would likely need to look in the vCenter logs if you can.
Content Libary's should be at: `/var/log/vmware/content-library/cls.log`

**Comment by dougm** [comment]
Just noticed:
```json
"NetworkMapping": [
        {
            "Name": "VM Network",
            "Network": "Test Network"
        }
    ],
```

This could be the issue: https://github.com/vmware/govmomi/issues/1561#issuecomment-582092466
If that is the case, we can add validation to `library.deploy` as we did for `import.ovf` here: https://github.com/vmware/govmomi/pull/2359/commits/cdf3ace63a9b8360fcdd54a42af6d4c3935dfad8

**Comment by eraserpencil** [comment]
I'm not sure I get it. I edited that field to remove the actual name. But I believe it works as I was able to create the `base_img` VM with a similar json file (differences being the user_data field)

**Comment by tenthirtyam** [comment]
Related downstream issue in the Terraform provider for vSphere: https://github.com/hashicorp/terraform-provider-vsphere/issues/1345

/remove-lifecycle stale
