### ISSUE TITLE
govc seems inconsistant

### ISSUE THREAD

**Issue by manningcarl** [vmware/govmomi#251]
I'm trying to get govc to deploy to vmware vsphere 6. I have had minimal success getting govc to connect correctly, at first i thought i had a syntax error in the command however the dump below shows the same command recieved success only once a few seconds apart. For nearly all of my commands i receive a NoPermission error and i cannot reproduce with any consistancy.

login as: root
root@10.21.10.114's password:
Last login: Fri Apr 24 11:24:29 2015 from 10.20.14.178
[root@localhost ~]# export GOVC_URL='cmanning\@vsphere.local:Carl\-Manning1@10.21.15.100'
[root@localhost ~]#  govc about -debug --u=cmanning\@vsphere\.local:Carl-Manning1@10.21.15.100 --k=true
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        2559267
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx
UUID:         8f3f2c90-e66b-46dc-a132-601e1d809887
[root@localhost ~]#  govc about -debug --u=cmanning\@vsphere\.local:Carl-Manning1@10.21.15.100 --k=true
Error: NoPermission
[root@localhost ~]# export GOVC_URL='cmanning\@vsphere.local:Carl\-Manning1@10.21.15.100'
[root@localhost ~]#  govc about -debug --u=cmanning\@vsphere\.local:Carl-Manning1@10.21.15.100 --k=true
Error: NoPermission

**Comment by pietern** [comment]
Can't reproduce with the exact same vCenter build. Running about many times in a row and don't see the NoPermission error. Do you use the embedded identity server or a separate SSO appliance?

```
$ govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        2559267
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx
UUID:         412b2a77-3ce7-486b-a323-3e3e0beff124
```

**Comment by jamiemoore** [comment]
I seem to see the same issue with 5.5.  Only seems to work once for an account. Then you receive the Error: NoPermission.

Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        2183111
OS type:      linux-x64
API type:     VirtualCenter
API version:  5.5
Product ID:   vpx

**Comment by manningcarl** [comment]
HI pietern, thanks for the quick response, we use SSO.

thanks

Carl

**Comment by pietern** [comment]
Thanks for the confirmation. I haven't tested govc against the SSO appliance yet, so it must be related. govc persists sessions on disk to it doesn't have to authenticate for every call (this saves a couple of round trips to the server, so makes every execution a little bit quicker). It appears this is what's causing the problem. Can you check if you can make another call after removing `~/.govmomi/sessions`? This is where govc stores the session information. If it is not present, it will re-authenticate. If you can confirm this fixing the issue we know where to look.

**Comment by jamiemoore** [comment]
Seems to fix the issue for me.  Well until a new session file is created.  

```bash
$govc about
Error: NoPermission
$rm -rf ~/.govmomi/sessions
$govc about                                                                                                                                                                               
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        2183111
OS type:      linux-x64
API type:     VirtualCenter
API version:  5.5
Product ID:   vpx
$govc about
Error: NoPermission
$rm -rf ~/.govmomi/sessions
$govc about                                                                                                                                                                               
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        2183111
OS type:      linux-x64
API type:     VirtualCenter
API version:  5.5
Product ID:   vpx
```

Though Carl has already said it, thanks pietern for your amazingly fast response on this issue.

Cheers,
Jamie

**Comment by manningcarl** [comment]
Hi pietern & Jamie, 

yes that temporarily solves it.

thanks

Carl

**Comment by manningcarl** [comment]
For a "temporary" dirty fix this can be resolved with a little bit of bash.

`mv /usr/local/bin/govc /usr/local/bin/govc2`

 create a bashscript at `/usr/local/bin/govc` and put the following in:

`#!/bin/bash`
`rm -Rf ~/.govmomi/sessions/ && govc2 $1`

This will wipe the sessions everytime govc is called.

**Comment by pietern** [comment]
@manningcarl In lieu of a proper solution, I added a flag to govc that allows you to disable persisting the session to disk, which should solve this issue without using a shell wrapper.

You can find binaries with this feature here: https://github.com/vmware/govmomi/releases/tag/head

Then either call govc like this:
```
govc about -persist=false
```

Or set the corresponding environment variable to disable it transparently:
```
export GOVC_PERSIST_SESSION=0
```

**Comment by manningcarl** [comment]
Great thanks Pieten, ill give it a go.

**Comment by pietern** [comment]
FYI, I had to rename the flag in #262.

**Comment by kpettijohn** [comment]
Just hit the same issue. I need to delete `~/.govmomi/sessions` in order to run commands successfully. From what I have seen I only get one successful command to run then every command after fails with the error `Error: NoPermission`. 

```
govc vm.info jenkins
Error: NoPermission
```
```
rm -rf ~/.govmomi/sessions; govc vm.info jenkins
Name:           jenkins
  UUID:         420a0c3e-c823-ecbb-b8b6-24a656f3dbe6
  Guest name:   Ubuntu Linux (64-bit)
  Memory:       6144MB
  CPU:          1 vCPU(s)
  Power state:  poweredOn
  Boot time:    2015-04-20 20:20:08.978191 +0000 UTC
  IP address:
```

```
rm -rf ~/.govmomi/sessions; govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        2183111
OS type:      win32-x64
API type:     VirtualCenter
API version:  5.5
Product ID:   vpx
UUID:         10C6B6D4-049C-44F1-96E9-0006BACF885A
```

Let me know if you would like any additional details. 

`govc v0.1.0`
Running govc on OS X 10.10.3.

**Comment by pietern** [comment]
@kpettijohn Thanks for the report! Running with `GOVC_PERSIST_SESSION=false` is effectively the same as prefixing commands with `rm -rf ~/.govmomi/sessions;`, so it doesn't solve the underlying problem.

Can you let me know what user you're connecting as? Are you using the separate SSO appliance as well?

**Comment by skuzye** [comment]
I can confirm this as well, though I don't know how much help I can give debugging. What info do you need?

**Comment by pietern** [comment]
@skuzye Thanks for the offer. Could you send me the debug output in `~/.govmomi/debug` after running the command twice (once to successfully log in, and the second time to trigger the permission error)? Please redact your password as it will be present in plain text in one or more files.

For example (paraphrased, don't know the actual output):
```
$ govc about -debug
...
$ govc about -debug
Error: NoPermission
```

**Comment by skuzye** [comment]
There about 15 files. What's the best way to post? Anyone specific you need?

```
./2015-08-18T15-01-59.421778333/1-0002.res.xml
./2015-08-18T15-01-59.421778333/1-0001.res.headers
./2015-08-18T15-01-59.421778333/1-0002.req.xml
./2015-08-18T15-01-59.421778333/1-0001.req.headers
./2015-08-18T15-01-59.421778333/1-0001.req.xml
./2015-08-18T15-01-59.421778333/1-0002.req.headers
./2015-08-18T15-01-59.421778333/1-0001.res.xml
./2015-08-18T15-01-59.421778333/1-client.log
./2015-08-18T15-01-59.421778333/1-0002.res.headers
./2015-08-18T15-02-01.014123004/1-0001.res.headers
./2015-08-18T15-02-01.014123004/1-0001.req.headers
./2015-08-18T15-02-01.014123004/.1-0001.res.xml.un~
./2015-08-18T15-02-01.014123004/1-0001.req.xml
./2015-08-18T15-02-01.014123004/1-0001.res.xml
./2015-08-18T15-02-01.014123004/1-client.log
```

**Comment by pietern** [comment]
Can you zip all of them and send me an email at pnoordhuis@vmware.com?

Hopefully these logs contain a clue.

By the way, in the mean time you can still use `-persist-session=false`, or set the associated environment variable to skip persisting the session altogether and re-authenticate for every `govc` invocation.

**Comment by skuzye** [comment]
Check your email.

I'm already using that, thank you!
