### ISSUE TITLE
Cannot set `version` in `WaitForUpdates()`

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2516]
As a user I would like to specify a `version` in the property collector `WaitX()` methods so that I can start retrieving updates from a specific point in time.

This is currently not possible:
https://github.com/vmware/govmomi/blob/5dace8100c85cafd69ac7f4148549aaa6cf4ea76/property/wait.go#L106

**Comment by dougm** [comment]
`property.WaitForUpdates` creates its own `PropertyCollector` internally and Version would only apply to that pc instance.
`property.Collector.WaitForUpdates` can be used with Version however as it does not create another pc instance underneath.

**Comment by embano1** [comment]
Thx, makes sense. Will close and keep this for documentation purposes here.
