### ISSUE TITLE
What are the minimum privileges or permission needed on vCenter to use VMware guest auth using govmomi ?

### ISSUE THREAD

**Issue by Aishwarya2** [vmware/govmomi#2520]
What are the minimum privileges or permission needed on vCenter to use VMware guest auth using govmomi ?

**Comment by Aishwarya2** [comment]
Hi. Following up to see if there are any updates on this one ?

**Comment by dougm** [comment]
vCenter docs should be able to answer this: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-6A952214-0E5E-4CCF-9D2A-90948FF643EC.html
