### ISSUE TITLE
`SessionIdleTimeout` should be hidden behind a function or method

### ISSUE THREAD

**Issue by protochron** [vmware/govmomi#2522]
**Describe the bug**
I was writing tests for a custom keepalive handler that we can handle logging back into vCenter. In order to exercise that code, I needed to override `SessionIdleTimeout` so simulate the connection terminated or the session ended, just like what is done in the example code. The problem is that `SessionIdleTimeout` is an exported package variable that is referenced by [simulator.SessionIdleWatch](https://github.com/vmware/govmomi/blob/7822b34eb5d359ddae2f93d356c78c5ea05784d5/simulator/session_manager.go#L324-L342), so changing that value directly leads to a data race if you run `go test -race`.

A quick fix is fairly straightforward: make the variable private and provide a function to change the value that looks something like:

```go
func SetSessionIdleTimeout(d *time.Duration) {
   idleTimeoutMutex.Lock() // would need to add this to the simulator package
   sessionIdleTimeout = d
   idleTimeoutMutex.Unlock()
}
```

Alternatively, swapping the value using the `atomic` package should work if performance is an issue (I think this works, haven't tested it):
```go
newValue := *int64(d)
ptr := unsafe.Pointer(&simulator.sessionIdleTimeout)
atomic.StorePointer(&ptr, unsafe.Pointer(newValue))
```

**To Reproduce**
1. Write some code that changes `simulator.SessionIdleTimeout`more than once in a test:
```go
simulator.SessionIdleTimeout = 1 * time.Second
//... do some things
simulator.SessionIdleTimeout = 0
```

2. Run `go test -race ./...`

**Expected behavior**
Not have a race condition

**Affected version**
v0.26.0

**Comment by dougm** [comment]
Using a func w/ mutex sounds good to me.  Would also need the mutex to read the value.  We could have two funcs or just one that can do both get+set, similar to: https://github.com/vmware/govmomi/blob/af7458910e2a4a5f6a5a3cd043d777e9a2e5dcfa/vapi/rest/client.go#L70-L78
