### ISSUE TITLE
[BUG] GOVC fails with passords with special chars

### ISSUE THREAD

**Issue by MaxRink** [vmware/govmomi#2523]
**Describe the bug**
We currently have an service user with an pwd formal like `z&z9^!$ZZZZZZzzzZZ*Zz`
This works fine in cluster-api-provider-vsphere ( which uses govmomi) and the normal vsphere UI, but not in GOVC.
Neither through env vars with various escaping nor through direct url reference.
We tried escaping basically every special char, in various configurations.
Its correctly loaded in env
```
env | grep "GOVC_PASS"
GOVC_PASSWORD=z&z9^!$ZZZZZZzzzZZ*Zz
```

but govc still fails
```
govc find -type n
govc: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

**To Reproduce**

1. Set that password for an vSphere User
2. Try to login trough GOVC

**Expected behavior**
Login works 
**Affected version**
v0.26.0
**Screenshots/Debug Output**

**Additional context**

**Comment by MaxRink** [comment]
Addendum: in debug logs the pwd is blanked out, is there any way to get that in cleartext to aid debugging?

**Comment by embano1** [comment]
I tried to reproduce this with `vcsim` and there it works:

```console
docker run -p 8989:8989 vmware/vcsim /vcsim -l :8989 -username admin -password 'z&z9^!$ZZZZZZzzzZZ*Zz'
export GOVC_URL=https://admin:z&z9%5E%21$ZZZZZZzzzZZ%2AZz@172.17.0.2:8989/sdk GOVC_SIM_PID=1

govc env
GOVC_USERNAME=admin
GOVC_PASSWORD=z&z9^!$ZZZZZZzzzZZ*Zz
GOVC_URL=127.0.0.1:8989
GOVC_INSECURE=true

govc find -type n
/DC0/network/VM Network
/DC0/network/DVS0-DVUplinks-9
/DC0/network/DC0_DVPG0
```

**Comment by dougm** [comment]
@MaxRink does the password also look correct with `govc env`?  You'd have to recompile to view the password in debug logs, I suppose we could add a runtime option for that.
```diff
modified   vim25/debug/debug.go
@@ -69,5 +69,5 @@ func Flush() {
 }
 
 func Scrub(in []byte) []byte {
-	return scrubPassword.ReplaceAll(in, []byte(`<password>********</password>`))
+	return in
 }
```
