### ISSUE TITLE
[GOVC] Add a new command to support move host from datacenter to cluster

### ISSUE THREAD

**Issue by li-kai-yuan** [vmware/govmomi#2524]
**Is your feature request related to a problem? Please describe.**
I'd like to use to govc to move a host from datacenter to cluster, have tried to use object.mv option but failed as cluster is not a folder

**Describe the solution you'd like**
Could you help add a new command option to wrapper around MoveInto function in here https://github.com/vmware/govmomi/blob/master/object/cluster_compute_resource.go#L72

The command can help move a host from datacenter to cluster

**Comment by adamfowleruk** [comment]
Note that this function not being implemented today results in it not being possible to successfully execute the hashicorp vsphere terraform provider against vcsim when spinning up an entirely new vSphere cluster using only terraform commands to update vcsim. You have to preset vcsim with the right hosts in the right clusters.
