### ISSUE TITLE
[BUG] Using PowerCLI 12.3 to create new VM generates error about invalid memory range

### ISSUE THREAD

**Issue by 39Delta** [vmware/govmomi#2531]
**Describe the bug**
Not sure if the PowerCLI cmd New-VM is supported but I get an invalid memory range when using PowerCLI 12.3 to create new VMs.   I may be just doing something wrong but I was not able to find any info on this error and I wanted to confirm that what I am doing is possible at this time.  If I execute `Get-VM ha-host_VM0 | new-vm -name test4` then it create the VM without issue so I assume it may be a parameter type issue?  

```
new-vm -VMHost localhost -Name test -Datastore LocalDS_0 -DiskGB 30 -DiskStorageFormat Thick -MemoryMB 2048
new-vm : 8/1/2021 10:04:07 AM   New-VM          The valid range for VM memory size is between 4 MB and 0 MB.
At line:1 char:1
+ new-vm -VMHost localhost -Name test -Datastore LocalDS_0 -DiskGB 30 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-VM], InvalidArgument
    + FullyQualifiedErrorId : ViCore_VMServiceImpl_TryValidateVmMemorySize_InvalidMemorySize,VMware.VimAutomation.ViCo
   re.Cmdlets.Commands.NewVM
```

**To Reproduce**

1.  .\vcsim.exe -esx -standalone-host 1 -l localhost:443 -api-version 7 (windows x64)
2. Connect-VIServer -Server localhost
3.  new-vm -VMHost localhost -Name test -Datastore LocalDS_0 -DiskGB 30 -DiskStorageFormat Thick -MemoryMB 2048

**Expected behavior**
I expected the command to create a VM in the vcsim environment

**Affected version**
Release v0.26.0

**Screenshots/Debug Output**
```
new-vm : 8/1/2021 10:04:07 AM   New-VM          The valid range for VM memory size is between 4 MB and 0 MB.
At line:1 char:1
+ new-vm -VMHost localhost -Name test -Datastore LocalDS_0 -DiskGB 30 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-VM], InvalidArgument
    + FullyQualifiedErrorId : ViCore_VMServiceImpl_TryValidateVmMemorySize_InvalidMemorySize,VMware.VimAutomation.ViCo
   re.Cmdlets.Commands.NewVM
```

**Additional context**

**Comment by embano1** [comment]
Before I dig deeper, just to doublecheck: this error does not happen against a real vC with that PCLI version?

**Comment by yaazer** [comment]
Confirmed, it doesn't happen against a real vC.
