### ISSUE TITLE
How to set guestos and guestos version of a vm deployed using "govc import.ova"?

### ISSUE THREAD

**Issue by koteswara-kelam** [vmware/govmomi#2534]
**Is your feature request related to a problem? Please describe.**
I deployed a vm by "govc import.ova" but its Guest OS and Version is "Other Linux". I want to set it to specific OS say "CentOS 8". Is it possible to set guestOS using govc?

**Describe the solution you'd like**
Searching for some option for govc to set guestos of a vm.

**Describe alternatives you've considered**
from vcenter, vm edit settings, I am able to change Guest OS.

**Comment by dougm** [comment]
You can use `govc vm.change -vm $vm_name -g $guest_id`
