### ISSUE TITLE
CreateEthernetCard may generate a device with positive key

### ISSUE THREAD

**Issue by Syuparn** [vmware/govmomi#2536]
I have a question about `CreateEthernetCard`.

`VirtualDeviceList#CreateEthernetCard()` generates a new device with random key not to duplicate existing keys (commit msg reference: https://github.com/vmware/govmomi/commit/ff575977b0b638aaa124d2851fc093be803eeeda).

- CreateEthernetCard
https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/object/virtual_device_list.go#L729

- key generation logic
https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/object/virtual_device_list.go#L71

Negative integer keys will not collide with existing keys, which are positive. (https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.device.VirtualDevice.html)

But the current implementation may also generate positive key because the most significant bit in `uint32` is converted to sign in `int32`.

```go
var n uint32 = 1 << 32 - 1
fmt.Println(n) // 4294967295
fmt.Println(int32(n)) // -1 (sign changed)
```

Is this intentional or a bug? If this should be fixed, I will make a PR later.

**To Reproduce**

```go
// simple way to generate a device with positive key
l := object.VirtualDeviceList{&types.VirtualE1000{}}
var b types.BaseVirtualDeviceBackingInfo = nil
c, _ := l.CreateEthernetCard("", b)
fmt.Println(c.GetVirtualDevice().Key) // 1697971134
```

**Comment by dougm** [comment]
@Syuparn sorry for the mix up with another PR closing this.

This sounds like a bug, please do open a PR if you have a fix in mind, thanks!

**Comment by Syuparn** [comment]
@dougm
Thank you for checking. Then I will make a PR later.
