### ISSUE TITLE
rename VM but name of VM folder and files inside unchanged

### ISSUE THREAD

**Issue by jackalensu** [vmware/govmomi#2537]
Hi,
I am trying to rename an exist VM using following code:
```go
	spec := &types.VirtualMachineConfigSpec{
		Name:       newName,
	}

	task, err := c.vm.Reconfigure(ctx, *spec)
	if err != nil {
		return err
	}
```
But results in only VM name changed but name of VM folder in datastore and files inside it remain old name.
Is there any feature to update them once or suggestions for this situation?

Thanks.

**Comment by lukasluecke** [comment]
The same issue occurs when using the vSphere web client, or any other means to rename the VM. See https://kb.vmware.com/s/article/1029513 for some potential solutions (although personally I haven't yet found something satisfactory).
