### ISSUE TITLE
[BUG] Error processing attribute "type" with value when the vm name has a colon

### ISSUE THREAD

**Issue by gtmtnbiker** [vmware/govmomi#2538]
**Describe the bug**
When running 
./govc fields.set  TemplateName foobar bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20:36:15Z

I get the output:
./govc: ServerFaultCode: 
Error processing attribute "type" with value "bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20"

But this works fine:
./govc fields.set -add -type VirtualMachine TemplateName foobar vm-rstjean

**To Reproduce**

1.  govc fields.add -type VirtualMachine TemplateName
1. Create a virtual machine named bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20:36:15Z
1. .govc fields.set  TemplateName foobar bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20:36:15Z

**Expected behavior**
It should not produce an error and set the field TemplateName to foobar for the vm  bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20:36:15Z

**Affected version**
v0.24.0, v0.26.0

**Screenshots/Debug Output**
```
centos76-clearcase-bsmith(bsmith): ./govc fields.set -verbose=true TemplateName foobar bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20:36:15Z
RetrieveProperties(propertyCollector, []types.PropertyFilterSpec)...
...CustomFieldsManager field: `govc object.collect -dump CustomFieldsManager:CustomFieldsManager field`

RetrieveProperties(propertyCollector, []types.PropertyFilterSpec)...
...group-d1 name: Datacenters

RetrieveProperties(propertyCollector, []types.PropertyFilterSpec)...
...datacenter-900399 name: Marlborough vRA
...datacenter-21     name: BedfordESX

SetField(CustomFieldsManager, bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20:36:15Z, 5307, foobar)...
&soap.Fault{
    XMLName: xml.Name{Space:"http://schemas.xmlsoap.org/soap/envelope/", Local:"Fault"},
    Code:    "ServerFaultCode",
    String:  "\nError processing attribute \"type\" with value \"bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20\"\n\nwhile parsing MoRef for ManagedObject of type vim.ManagedEntity\nat line 2, column 155\n\nwhile parsing call information for method SetField\nat line 2, column 66\n\nwhile parsing SOAP body\nat line 2, column 60\n\nwhile parsing SOAP envelope\nat line 2, column 0\n\nwhile parsing HTTP request for method setField\non object of type vim.CustomFieldsManager\nat line 1, column 0",
}
./govc: ServerFaultCode: 
Error processing attribute "type" with value "bsmithadm-LINUX-oeiac_ds6-2-2021-08-04T20"

while parsing MoRef for ManagedObject of type vim.ManagedEntity
at line 2, column 155

while parsing call information for method SetField
at line 2, column 66

while parsing SOAP body
at line 2, column 60

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method setField
on object of type vim.CustomFieldsManager
at line 1, column 0
centos76-clearcase-bsmith(bsmith):
```

**Additional context**

**Comment by embano1** [comment]
@dougm your proposal seems to do the trick, thx!

I just have two questions related to the PR I created based on your proposal:

1) It seems we don't have to touch the same method on `*PermissionsFlag` (see below), IMHO this code is still fine with that change
1) If the provided argument is not of type `MoRef`, `elements, err := finder.ManagedObjectList(ctx, arg)` is used which returns multiple MoRefs for the same object (e.g. ref from `host` folder and ref from `vm` folder) making the action take unnecessarily long. Assuming this is a known "issue" and could be handled inside the finder code with deduplication logic?

`ManagedObjects()` on `*PermissionsFlag`

```go
func (f *PermissionFlag) ManagedObjects(ctx context.Context, args []string) ([]types.ManagedObjectReference, error) {
	if !f.asRef {
		return f.DatacenterFlag.ManagedObjects(ctx, args)
	}

	var refs []types.ManagedObjectReference

	for _, arg := range args {
		var ref types.ManagedObjectReference
		if ref.FromString(arg) {
			refs = append(refs, ref)
		} else {
			return nil, fmt.Errorf("invalid moref: %s", arg)
		}
	}

	return refs, nil
}
```
