### ISSUE TITLE
[BUG] Device label 'scsi0:7' is invalid when adding 6th device to VM

### ISSUE THREAD

**Issue by rawstorage** [vmware/govmomi#2539]
**Describe the bug**
Unable to add 6th RDM device using GOVC.  

**To Reproduce**

1. Create a new VM with hard disk attached/
2. Provision san storage to esxi 
3. Rescan for new storage
4. for each newly added device on ESXI run govc vm.rdm.attach -device "/vmfs/devices/disks/naa.60000970000xxxxxxxx33030334435" -vm=govc_test
5. First 5 RDM will attach fine, but when the 6th one is to be added get the error govc: error adding device {VirtualDevice:{DynamicData:{} Key:0 DeviceInfo:<nil> Backing:0xc0001f6340 Connectable:<nil> SlotInfo:<nil> ControllerKey:1000 UnitNumber:0xc000497c2c} CapacityInKB:0 CapacityInBytes:0 Shares:<nil> StorageIOAllocation:<nil> DiskObjectId: VFlashCacheConfigInfo:<nil> Iofilter:[] VDiskId:<nil> NativeUnmanagedLinkedClone:<nil>}
 with backing {VirtualDeviceFileBackingInfo:{VirtualDeviceBackingInfo:{DynamicData:{}} FileName: Datastore:<nil> BackingObjectId:} LunUuid:vml.02002a000060000970000xxxxxxxx3303034463153594d4d4554 DeviceName:/vmfs/devices/disks/naa.60000970000xxxxxxx33030344631 CompatibilityMode:physicalMode DiskMode: Uuid: ContentId: ChangeId: Parent:<nil> DeltaDiskFormat: DeltaGrainSize:0 Sharing:}
Logged Item:  Device label 'scsi0:7' is invalid.

I've anonymized serial of my array from output.

**Expected behavior**
Expectation is that I should be able to add up to max number of devices or specify different label to get around the error/

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.

govc about
FullName:     VMware vCenter Server 7.0.2 build-17920168
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      7.0.2
Build:        17920168
OS type:      linux-x64
API type:     VirtualCenter
API version:  7.0.2.0
Product ID:   vpx
UUID:         65e7e232-f200-4898-b1d5-9955bcfd5c13

**Additional context**

**Comment by rawstorage** [comment]
Seems that 7 is not a valid number for SCSI controller which is why this fails..
according to documents for ansible - 
https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_disk_module.html

unit_number integer / required 
Disk Unit Number.Valid value range from 0 to 15, except 7 for SCSI Controller.
Valid value range from 0 to 29 for SATA controller.
Valid value range from 0 to 14 for NVME controller.

change line 118 in attach.go to if free && u != 7 and rebuild of binary seems to have fixed the issue for me in my lab environment.  I've created corresponding pull request and proof points of this working locally.

**Comment by Syuparn** [comment]
Pull Request https://github.com/vmware/govmomi/pull/2541 seems to relate to this issue, but https://github.com/vmware/govmomi/issues/2536 is closed instead.

**Comment by dougm** [comment]
Fixed by #2541
