### ISSUE TITLE
Support eager zeroed thick virtual disk in CreateDisk()

### ISSUE THREAD

**Issue by tkak** [vmware/govmomi#254]
I think current CreateDisk() function just creates thin provisioned virtual disk. I would appreciate it if you could support eager zeroed thick virtual disk.

References: 

- https://github.com/vmware/govmomi/blob/master/object/virtual_device_list.go#L334

Thanks,

**Comment by pietern** [comment]
@tkak The level of parameterization of the disk is pretty large. I would rather add a function that takes a VirtualDisk type and adds that to the virtual disk list, so that you can customize however you want, instead of only whether or not you want the disk to be zeroed.

@dougm What do you think?

**Comment by dougm** [comment]
Already possible to append a VirtualDisk constructed elsewhere to the list.  You could also customize by modifying the return value of CreateDisk().  For example, see: https://github.com/vmware/govmomi/blob/master/govc/vm/disk/attach.go#L76-L93

**Comment by tkak** [comment]
@pietern @dougm  Thank you for your advice. I could create eager zeroed thick virtual disk! This is my code snippet.

```go
...
	vm, err := finder.VirtualMachine(context.TODO(), "test-01")
	if err != nil {
		log.Printf("[ERROR] Error setting up client: %s", err)
	}
	log.Printf("[DEBUG] %#v\n", vm)

	devices, err := vm.Device(context.TODO())
	if err != nil {
		log.Printf("[ERROR] Error setting up client: %s", err)
	}
	log.Printf("[DEBUG] %#v\n", devices)

	controller, err := devices.FindDiskController("scsi")
	if err != nil {
		log.Printf("[ERROR] Error setting up client: %s", err)
	}
	log.Printf("[DEBUG] %#v\n", controller)

	disk := devices.CreateDisk(controller, "")

	existing := devices.SelectByBackingInfo(disk.Backing)
	log.Printf("[DEBUG] %#v\n", existing)

	if len(existing) == 0 {
		log.Printf("Creating disk\n")
		disk.CapacityInKB = 1048576
	} else {
		log.Printf("Disk already present\n")
	}

	backing := disk.Backing.(*types.VirtualDiskFlatVer2BackingInfo)
	log.Printf("[DEBUG] %#v\n", backing)

	// eager zeroed thick virtual disk
	backing.ThinProvisioned = types.NewBool(false)
	backing.EagerlyScrub = types.NewBool(true)

	vm.AddDevice(context.TODO(), disk)
...
```

**Comment by pietern** [comment]
Nice :)

Closing the issue.
