### ISSUE TITLE
How to get NasDatastoreInfo from []mo.Datastore?

### ISSUE THREAD

**Issue by rishu2403** [vmware/govmomi#2543]
I am trying to get [NAS](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.host.NasDatastoreInfo.html#field_detail) . 
ERROR: `panic: reflect.Set: value of type mo.Datastore is not assignable to type main.DatastoreV2`
I see that datastore of type `[]mo.Datastore` has Info field of type `types.BaseDatastoreInfo` . However I need to implement Info field of type `types.BaseDatastoreInfo` which inherits BaseDatastoreInfo + NAS field. After implementing my modiefied struct `[]DatastoreV2`  and running it I am getting an error ` types.BaseDatastoreInfo `. My guess is i am getting an error from v.Retrieve func. Looking for some guidance here 

`var vms []DatastoreV2

	err = v.Retrieve(ctx, []string{"Datastore"}, []string{"summary", "host", "vm", "info"}, &vms)
	timenow := time.Now()
	if err != nil {
		log.Println("debug2")
		log.Println(err)
	}`

**Comment by rishu2403** [comment]
My DatastoreV2 is of type 

type DatastoreV2 struct {
	mo.ManagedEntity
	Info              types.NasDatastoreInfo         `mo:"info"`
	Summary           types.DatastoreSummary         `mo:"summary"`
	Host              []types.DatastoreHostMount     `mo:"host"`
	Vm                []types.ManagedObjectReference `mo:"vm"`
	Browser           types.ManagedObjectReference   `mo:"browser"`
	Capability        types.DatastoreCapability      `mo:"capability"`
	IormConfiguration *types.StorageIORMInfo         `mo:"iormConfiguration"`
}

**Comment by HakanSunay** [comment]
Can't you just cast the `BaseDatastoreInfo` interface to `NasDatastoreInfo`?

```
ds := someCodeToGetDS()
nas, ok := ds.Info.(*types.NasDatastoreInfo)
if !ok {
	return
}
// you have the nas
```

**Comment by rishu2403** [comment]
Thanks for the reply, errored out  the inbuilt []mo.Datastore has Info of type `panic: interface conversion: types.BaseDatastoreInfo is *types.LocalDatastoreInfo, not *types.NasDatastoreInfo`. Shouldnt there be some relation where BaseDatastoreInfo extends NasDatastoreinfo ?

**Comment by rishu2403** [comment]
@HakanSunay  Sorry i was confused , I got it working thank you so much. Closing the question.
