### ISSUE TITLE
consult set maintenance mode for ESX host 

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2548]
I have one question for ESX maintenance mode, does the evacuate means that if it is false, then the VM will not migrate to other ESX hosts,right? and what is parameter spec used for? and does timeout is the second? if I set the timeout as 0, whether it means it won't timeout while set ESX maintenance.

func (h HostSystem) EnterMaintenanceMode(ctx context.Context, timeout int32, evacuate bool, spec *types.HostMaintenanceSpec) (*Task, error) {
	req := types.EnterMaintenanceMode_Task{
		This:                  h.Reference(),
		Timeout:               timeout,
		EvacuatePoweredOffVms: types.NewBool(evacuate),
		MaintenanceSpec:       spec,
	}

	res, err := methods.EnterMaintenanceMode_Task(ctx, h.c, &req)
	if err != nil {
		return nil, err
	}

	return NewTask(h.c, res.Returnval), nil
}

**Comment by HakanSunay** [comment]
Have a look at the docs for a detailed description of each field:

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/b525fb12-61bb-4ede-b9e3-c4a1f8171510/99ba073a-60e9-4933-8690-149860ce8754/doc/vim.HostSystem.html#enterMaintenanceMode

**Comment by leoxucn822** [comment]
thank you very much
