### ISSUE TITLE
How to connect a vm to network?

### ISSUE THREAD

**Issue by githubuser00** [vmware/govmomi#2549]
Following command changed the network but it does not connect it:
govc vm.network.change -vm=/SDDC-Datacenter/vm/Workloads/folder1/testvm1 -net=/SDDC-Datacenter/network/testnet1 ethernet-0
![image](https://user-images.githubusercontent.com/7738909/129276491-fd95a63e-2139-476d-95ec-588917f37577.png)

**Comment by githubuser00** [comment]
found a work around using dcli:
dcli +server 10.20.30.40 +skip-server-verification com vmware vcenter vm hardware ethernet update --vm vm-1234 --nic 4000 --backing-network network-o1234 --backing-type OPAQUE_NETWORK --start-connected true

**Comment by dougm** [comment]
I haven't tried to reproduce this yet, but you should also be able to workaround using:
```console
% govc device.connect -vm $name ethernet-0
```
