### ISSUE TITLE
[BUG] event.FullFormattedMessage prints the format itself rather than correct message

### ISSUE THREAD

**Issue by sameermahajan** [vmware/govmomi#2559]
**Describe the bug**
When FullFormattedMessage from event is printed it prints the format (e.g. {vm.name} on  {host.name} in {datacenter.name} is stopping) rather than something like

foo on bar in blah is stopping

**To Reproduce**

1. run the following code:

```
package main

import (
        "context"
        "fmt"
        "net/url"
        "os"
        "reflect"

        "github.com/vmware/govmomi"
        "github.com/vmware/govmomi/event"
        "github.com/vmware/govmomi/find"
        "github.com/vmware/govmomi/vim25/types"
)

var lastProcessedEventKey int32 = 0

func handleEvent(ref types.ManagedObjectReference, events []types.BaseEvent) (err error) {

        event.Sort(events)

        for _, event := range events {

                eventType := reflect.TypeOf(event).String()

                fmt.Printf("Event found of type %s, key: %d, event.vm: %+v message: %s\n",
                        eventType, event.GetEvent().Key, event.GetEvent().Vm, event.GetEvent().FullFormattedMessage)
        }

        return nil
}

func main() {

        fmt.Fprintf(os.Stdout, "vCenter event handler starting \n")

        // Creating a connection context
        ctx, cancel := context.WithCancel(context.Background())
        defer cancel()

        urlStr := fmt.Sprintf("https://%s:%s@%s:8989/sdk", "user", "pass", "127.0.0.1")

        // Parsing URL
        url, err := url.Parse(urlStr)
        if err != nil {
                fmt.Fprintf(os.Stderr, "Error: %s\n", err)
                os.Exit(1)
        }

        // Connecting to vCenter
        client, err := govmomi.NewClient(ctx, url, true)
        if err != nil {
                fmt.Fprintf(os.Stderr, "Error: %s\n", err)
                os.Exit(1)
        }

        // Selecting default datacenter
        finder := find.NewFinder(client.Client, true)
        dc, err := finder.DefaultDatacenter(ctx)
        if err != nil {
                fmt.Fprintf(os.Stderr, "Error: %s\n", err)
                os.Exit(1)
        }
        refs := []types.ManagedObjectReference{dc.Reference()}

        // Setting up the event manager
        eventManager := event.NewManager(client.Client)

        //      for i := 0; ; i++ {
        err = eventManager.Events(ctx, refs, 10, true, false, handleEvent)

        if err != nil {
                fmt.Fprintf(os.Stderr, "Error: %s\n", err)
                os.Exit(1)
        }

        fmt.Fprintf(os.Stdout, "vCenter event handler stopped \n")

}
```

2. start vcenter simulator on localhost (alternatively you can point above code to real vcenter)
3. fire a vcenter event (e.g. a VM power off)
3. lookup the output of above program

**Expected behavior**
It should print a message like

foo on bar in blah is stopping

**Affected version**
v0.26.0

**Screenshots/Debug Output**
the program incorrectly outputs something like:
Event found of type *types.VmStoppingEvent, key: 15, event.vm: &{EntityEventArgument:{EventArgument:{DynamicData:{}} Name:tkg-cluster-01-md-0-67b69c558f-bdb4j} Vm:VirtualMachine:vm-1099} message: {vm.name} on  {host.name} in {datacenter.name} is stopping

**Additional context**
FullFormattedMessage property of event  is printing format like output rather than formatted message.

**Comment by sameermahajan** [comment]
@embano1 with vcsim version v0.26.1 as well as latest, the issue still repros for  me. vcsim version prints blank version but that is another bug in vcsim I believe.

**Comment by embano1** [comment]
`vcsim` version blank might be due to missing compiler injection if you build it your own (should not happen if using official bits/docker images from the releases).

Which Go version are you using? The above output is from your exact code example using `go version go1.16.6 darwin/amd64`

**Comment by sameermahajan** [comment]
I did not build vcsim myself but only installed it from the repo.

My go version is

go version go1.16.4 linux/amd64

I can also repro it on my windows laptop.

**Comment by embano1** [comment]
For installation guidance please see here: https://github.com/vmware/govmomi/tree/master/vcsim

Can you please try to repro this with our Docker release?
