### ISSUE TITLE
event does not have UUID

### ISSUE THREAD

**Issue by sameermahajan** [vmware/govmomi#2560]
**Is your feature request related to a problem? Please describe.**
Currently event does not have UUID field for objects (e.g. VM) in it.

**Describe the solution you'd like**
I would like to have UUID field for objects in it.

**Describe alternatives you've considered**
Alternatives that I have considered is to go back to vCenter after receiving an event, query it for UUID and enrich the event with UUID.

**Additional context**
There are no UUID fields for objects (e.g. VM) in an event.

**Comment by embano1** [comment]
This is a restriction imposed by the schema of that particular event (see https://vdc-download.vmware.com/vmwb-repository/dcr-public/8946c1b6-2861-4c12-a45f-f14ae0d3b1b9/a5b8094c-c222-4307-9399-3b606a04af55/vim.event.Event.html for details).

You might want to address this with the approach we've taken for alarms: https://github.com/embano1/vsphere-alarm-server

Let me know if it's ok to close this issue.

**Comment by sameermahajan** [comment]
@embano1 can you please elaborate on how alarm server gets UUIDs for various objects in an event?

**Comment by sameermahajan** [comment]
@embano1 can you please elaborate on how alarm server gets UUIDs for various objects in an event?

**Comment by embano1** [comment]
The alarm server was just an example of a flow/design how to inject/enrich events if there's missing (meta)data in the event schema. In case of the alarm server, it retrieves additional alarm details (not UUID) and injects this into an `AlarmEvent`. You can follow a similar approach here which gives you some additional benefits, e.g. decoupling, filtering and caching.
