### ISSUE TITLE
how do i know if the cluster enable the vsan

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2563]
anyone can give me a hint, which package should I make a reference?

**Comment by embano1** [comment]
Is this a `govc` or govmomi (library) related question?

**Comment by leoxucn822** [comment]
@embano1 yeah, I checked govc foder,  I am not sure if cluster/stretch.go is working fine, I see the comments that transfer the vsan cluster to stretched cluster,  I am not sure if this will impact our production environment, btw, is it possible that I can get the property from cluster layer

**Comment by embano1** [comment]
This is included in `govc` on the master branch - or you wait until the next release (see https://github.com/vmware/govmomi/pull/2432)
