### ISSUE TITLE
How to find a HostSystem by FQDN or IP address?

### ISSUE THREAD

**Issue by lucasepe** [vmware/govmomi#2578]
Hello! I have a question about this great package.

It is possible to find a HostSytem by FQDN (or address)?
 
To find a HostSytem by it's ID this works great:

```go
func HostSytemByID(client *govmomi.Client, id string) (*object.HostSystem, error) {
    finder := find.NewFinder(client.Client, false)

    ref := types.ManagedObjectReference{
        Type:  "HostSystem",
        Value: id,
    }

    hs, err := finder.ObjectReference(ctx, ref)
    if err != nil {
         return nil, err
    }
	
    return hs.(*object.HostSystem), nil
}
```

How to find a HostSystem by it's FQDN or IP address?

```go
func HostSytemByFQDN(client *govmomi.Client, fqdn string) (*object.HostSystem, error) {  
   finder := find.NewFinder(client.Client, false)

  //...
}
```

Thank you in advance.

**Comment by leoxucn822** [comment]
with this func you can find the esx host by IP address:

func FindHostByIp(ctx context.Context, c *vim25.Client, ip string) {
	searchIndex := object.NewSearchIndex(c)

	reference, _ := searchIndex.FindByIp(ctx, nil, ip, false)
	if reference == nil {
		fmt.Println("ESXI not found")
	}

	host := object.NewHostSystem(c, reference.Reference())
	serverName, _ := host.ObjectName(ctx)
	fmt.Println(serverName)
}

**Comment by lucasepe** [comment]
Thank you very much!
