### ISSUE TITLE
Get & Set CPU affinity attributes

### ISSUE THREAD

**Issue by ciroiriarte** [vmware/govmomi#2581]
**Is your feature request related to a problem? Please describe.**
I can not set or query the value for advanced CPU configuration like:
"sched.cpu.affinity"
"numa.nodeAffinity"

**Describe the solution you'd like**
I would like to be able to query through govc the value of those parameters. Specific support for each possible value is not needed, as long as I can define the name and a value for the "set" operation and a name for the "get"

**Describe alternatives you've considered**
Tried querying with "vm.info -e", I cannot find the info there.

**Additional context**
vSphere 7.0 + govc v0.26.1

**Comment by dougm** [comment]
Sorry for the delay.. the following works for me:

```console
# set
% govc vm.change -vm $vm -e numa.nodeAffinity=1

# get
% govc vm.info -e $vm | grep numa
    numa.nodeAffinity:             1
```
