### ISSUE TITLE
vcsim support for TenantManager API

### ISSUE THREAD

**Issue by nikhaild** [vmware/govmomi#2587]
vSphere 6.9 API introduced TenantManager to support protection for system user (service provider) owned objects in a tenant's inventory tree. Adding support for TenantManager API (mark/unmark/retrieve "service provider" object) in vcsim would help develop components that make use of TenantManager API functionality.

TenantManager currently supports 3 APIs:
https://vdc-download.vmware.com/vmwb-repository/dcr-public/4b836a92-c980-497d-809e-e1bf168d551c/8de7abfc-8ad9-42cb-b15f-ae5228324a6e/vim.tenant.TenantManager.html
* MarkServiceProviderEntities
* RetrieveServiceProviderEntities
* UnmarkServiceProviderEntities

An initial bare-bones implementation would be implementation of above APIs to accepts objects as input through the mark API, track them in vcsim state, allow retrieval of currently marked objects, remove them from the tracking state through unmark API.

An advanced implementation would be
* to support actual protection to the marked objects depending on the caller (e.g. a non-system user caller cannot manipulate marked objects)
* to support only system user callers to invoke TenantManager APIs

Currently there's no alternative to simulate TenantManager API for providing protection for service provider objects.

**Comment by nikhaild** [comment]
I have a patch for first part (initial barebones implementation for TenantManager API) that I'll post soon.
However I would need some guidance and help regarding the advanced portion (e.g. does vcsim support making a distinction between API callers - a system vs non-system users, modeling permissions and tracking changes, propagating them etc.).

**Comment by nikhaild** [comment]
Here's a pull request for a basic TenantManager implementation in vcsim:
https://github.com/vmware/govmomi/pull/2590

**Comment by dougm** [comment]
Closed by #2590
