### ISSUE TITLE
How to use Govmomi to create a  virtual machine from zero

### ISSUE THREAD

**Issue by waibizi** [vmware/govmomi#2592]
Hello, may I ask how can I get through https://github.com/vmware/govmomi/blob/f4c5c4a58e445ba31393795c7e678fa05fb3452a/object/folder.go#L152  to create a virtual machine.
I started by reading the following unit test code.
https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/simulator/virtual_machine_test.go#L36
But the virtual machine I created was not available, did not select an OS image, since the field of VirtualMachineConfigSpec does not have relevant comments, so I would like to ask, how should I create a working virtual machine

**Comment by embano1** [comment]
You could take a look at how `govc` does it: https://github.com/vmware/govmomi/blob/f4c5c4a58e445ba31393795c7e678fa05fb3452a/govc/vm/create.go#L340

The documentation of `VmConfigSpec` for vSphere 7.x can be found here: https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.ConfigSpec.html#field_detail

**Comment by waibizi** [comment]
Thank you so much for your prompt reply, which is very helpful to me

**Comment by embano1** [comment]
You're welcome, hope you enjoy the SDK and its helpful. Can we close this issue then?

**Comment by waibizi** [comment]
Of course. Thanks again for your prompt reply
