### ISSUE TITLE
ServerFaultCode: A specified parameter was not correct: type

### ISSUE THREAD

**Issue by wanglong001** [vmware/govmomi#2595]
**Describe the bug**
Need to get the value of HostNetworkSystem Use the CreateContainerView method, but return an error [=ServerFaultCode: A specified parameter was not correct: type] 

**To Reproduce**
https://code.vmware.com/docs/4206/vsphere-web-services-api-reference/doc/vim.host.NetworkSystem.html

```golang
service := "HostNetworkSystem" // or vim.host.NetworkSystem
m := view.NewManager(c.cli)
v, err := m.CreateContainerView(ctx, c.cli.ServiceContent.RootFolder, []string{service}, true)
```

**Expected behavior**
Expected err == nil

**Affected version**
github.com/vmware/govmomi v0.26.1
![image](https://user-images.githubusercontent.com/14817376/134653494-3c24efeb-97b9-43dc-b50b-d818117a81ac.png)

**Screenshots/Debug Output**
 err = ServerFaultCode: A specified parameter was not correct: type

**Comment by wanglong001** [comment]
If there is a problem with my usage, please let me know, thank you
The document is not well understood

**Comment by embano1** [comment]
@wanglong001 the supported `types` for `CreateContainerView` are: 

`[]string{"ComputeResource", "Datacenter", "Datastore", "DistributedVirtualSwitch", "Folder", "HostSystem", "Network", "ResourcePool", "VirtualMachine"}`

You can retrieve the `HostNetworkSystem` property of the `HostConfigManager` property in a `HostSystem` via this example code:

```go
	// Create a view of HostSystem objects
	m := view.NewManager(c)

	v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"HostSystem"}, true)
	if err != nil {
		return err
	}

	defer v.Destroy(ctx)

	// Retrieve summary property for all hosts
	// Reference: http://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/vim.HostSystem.html
	var hss []mo.HostSystem
	err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"configManager"}, &hss)
	if err != nil {
		return err
	}

	for _, h := range hss {
		pretty.Printf("%+v\n", h.ConfigManager.NetworkSystem)

		var hns []mo.HostNetworkSystem
		property.DefaultCollector(c).RetrieveOne(ctx, *h.ConfigManager.NetworkSystem, nil, &hns)

		for _, ns := range hns {
			pretty.Printf("%+v\n", ns)
		}
	}
```

Perhaps @dougm has a more efficient way though.

**Comment by dougm** [comment]
lgtm, I would just limit the HostSystem props further to `configManager.networkSystem` and collect the `[]mo.HostNetworkSystem` list in one call:
```go
		m := view.NewManager(c)

		v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"HostSystem"}, true)
		if err != nil {
			log.Fatal(err)
		}

		defer v.Destroy(ctx)

		var hss []mo.HostSystem

		err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"configManager.networkSystem"}, &hss)
		if err != nil {
			return err
		}

		refs := make([]types.ManagedObjectReference, len(hss))
		for i := range hss {
			refs[i] = *hss[i].ConfigManager.NetworkSystem
		}

		var hns []mo.HostNetworkSystem
		err = property.DefaultCollector(c).Retrieve(ctx, refs, nil, &hns)
		if err != nil {
			return err
		}

		pretty.Printf("%# v\n", hns)
```

**Comment by wanglong001** [comment]
ths，  and  Closed
