### ISSUE TITLE
govc vm.clone and disk provision type

### ISSUE THREAD

**Issue by jakegatsby** [vmware/govmomi#2619]
Is it possible to set the disk provision type (thick/thin) with `govc vm.clone`?  I am able to do this using the vsphere web client, but cannot figure out how to set the disk to thin provisioned when cloning using govc.

From googling, I'm wondering if I first need to create a named customization specification through the vsphere web client?

Thanks a lot for any suggestions you might have.

**Comment by jakegatsby** [comment]
embano1, thanks so much for the fast reply.  I'm hesitant to make a suggestion since I'm not a usability expert or anything, but I'm wondering if something as simple as `govc vm.clone -disk.thin-provisioned` would work?  This would follow the `host.foo` and `net.bar` convention.  My only concern is in the case of multiple disks, but from my experience so far, govc tends to keep things simple and straight-forward, so perhaps it's ok that `-disk.thin-provisioned` applies to all disks?

This would also work for possible future options such as `govc vm.clone -disk.eagerly-scrub`?

Other tools like Terraform or Pulumi support more complicated configurations, but again, I'm not sure that's the goal of govc?  [Here are the similar config options in Terraform](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#eagerly_scrub).

Again, thanks so much for looking at this issue, and looking forward to your feedback.

**Comment by jakegatsby** [comment]
Apologies for bumping the ticket, but just wondering if there are any updates on this issue?  Thanks a lot.

**Comment by embano1** [comment]
I would need some advice from @dougm how to approach this one as the `RelocateSpec` handling is a bit complex from my basic understanding.
