### ISSUE TITLE
How to get disk uuid

### ISSUE THREAD

**Issue by imrushi** [vmware/govmomi#2620]
Hi, I am trying to get disk uuid from vm.Config.Hardware.Device using for loop.

```
	m := view.NewManager(c.Client)
	v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"VirtualMachine"}, true)
	if err != nil {
		exit(err)
	}
	defer v.Destroy(ctx)
        var vmt []mo.VirtualMachine
	err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"summary", "config", "guest"}, &vmt)
	if err != nil {
		exit(err)
	}
        for _, vm := range vmt {
                for _, tt := range vm.Config.Hardware.Device {
			disk, ok := tt.(*types.VirtualDisk)
			if !ok {
				continue
			}
			fmt.Printf("%v\n", disk.Backing)
		}
        }
```
It giving following Output
```
&{{{{}} [datastore] testvm/testvm.vmdk Datastore:datastore-12 } persistent 0xc00040197f 0xc000401995 0xc0004019d5 <nil> 6000C29e-8208-f378-656a-61434e2e9698 d4cc6a688fd7d1eff366dd4ffc05b4f1  <nil>  0xc000401a29 0  sharingNone <nil>}
```
From above Output how should I get the uuid because **disk.Backing** has GetVirtualDeviceBackingInfo() method which giving the error of segmentation and it has .DynamicData. I don't know how to use DynamicData.

Any help will be appreciated...

**Comment by dougm** [comment]
Hi @imrushi , you'll want to type assert the Backing type, as not all have a Uuid field, for example:
```go
			for _, tt := range vm.Config.Hardware.Device {
				disk, ok := tt.(*types.VirtualDisk)
				if !ok {
					continue
				}
				switch backing := disk.Backing.(type) {
				case *types.VirtualDiskFlatVer2BackingInfo:
					fmt.Printf("uuid=%s\n", backing.Uuid)
				}
			}
```

**Comment by embano1** [comment]
Just to explain how one can understand/retrieve the type class in such cases:

1) Go to the property definition for the specific vSphere API version, e.g. [`VirtualDeviceBackingInfo`](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.device.VirtualDevice.BackingInfo.html)
1) If "abstract" (dynamic) type -> pick one sub-type, e.g. [`VirtualDeviceFileBackingInfo`](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.device.VirtualDevice.FileBackingInfo.html)
1) If this type is further extended -> pick the concrete sub-type in question, e.g. [`VirtualDiskFlatVer2BackingInfo`](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.device.VirtualDisk.FlatVer2BackingInfo.html)
1) Use properties (also note the comment in each type which properties are inherited from upper classes
