### ISSUE TITLE
vm.change command needs -sync-time-with-host-allowed flag

### ISSUE THREAD

**Issue by weakcamel** [vmware/govmomi#2631]
**Is your feature request related to a problem? Please describe.**

Current (vSphere v7) VMs have 2 options related to  VMWare Tools time sync:

* SyncTimeWithHost
* SyncTimeWithHostAllowed

See https://vdc-download.vmware.com/vmwb-repository/dcr-public/8e6af87a-b054-416d-8b61-aa9fba096944/617db479-aee6-4717-a94c-8bddd19785b9/vim.vm.ToolsConfigInfo.html

> Flag to specify whether or not the tools program will periodically synchronize guest time with host time. Periodical synchronization is only allowed if vim.vm.ToolsConfigInfo#syncTimeWithHostAllowed is not set to false.
>
> Since VI API 2.5

You can set  the former with the following command:

```
govc vm.change -vm $vm -sync-time-with-host
```

however `govc` doesn't give you a way to set the latter

however if SyncTimeWithHostAllowed is set to false, this will still have no effect. From that perspective, this could be treated as a bug

**Describe the solution you'd like**

I'd love to see an option for vm.change command, e.g. 

```
govc vm.change -vm $vm -sync-time-with-host-allowed
```

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by dougm** [comment]
Untested, but the patch below should do the trick. Can you test it out and/or open a PR?
```diff
modified   govc/vm/change.go
@@ -151,6 +151,7 @@ func (cmd *change) Register(ctx context.Context, f *flag.FlagSet) {
 	f.Var(flags.NewOptionalBool(&cmd.NestedHVEnabled), "nested-hv-enabled", "Enable nested hardware-assisted virtualization")
 	cmd.Tools = &types.ToolsConfigInfo{}
 	f.Var(flags.NewOptionalBool(&cmd.Tools.SyncTimeWithHost), "sync-time-with-host", "Enable SyncTimeWithHost")
+	f.Var(flags.NewOptionalBool(&cmd.Tools.SyncTimeWithHostAllowed), "sync-time-with-host-allowed", "Enable SyncTimeWithHostAllowed")
 	f.Var(flags.NewOptionalBool(&cmd.VPMCEnabled), "vpmc-enabled", "Enable CPU performance counters")
 	f.Var(flags.NewOptionalBool(&cmd.MemoryHotAddEnabled), "memory-hot-add-enabled", "Enable memory hot add")
 	f.Var(flags.NewOptionalBool(&cmd.MemoryReservationLockedToMax), "memory-pin", "Reserve all guest memory")
```

**Comment by gothicx** [comment]
It would be nice to implement this.

**Comment by jmal22** [comment]
it would be nice to implement indeed
