### ISSUE TITLE
Support: HostDiskManager object

### ISSUE THREAD

**Issue by abbbi** [vmware/govmomi#2640]
hi,

the implementation seems to define types named "HostDiskMappingInfo". According to the documentation they could be
used to:

>Data Object Description
> The HostDiskMappingInfo data object type describes a virtual disk mapping to a host disk. 

but i fail to see how one can request them from a esx host, are there any examples available or ones
that can be easily modified to query this information via the vsphere api?

**Comment by embano1** [comment]
Can you please point to the VMware API docs where `HostDiskManager` is defined?

**Comment by abbbi** [comment]
hi, i think its not the HostDiskManager object, but its the `AcquireLeaseExt` Object, no documentation to be found for this anywhere. Sending a requests outlined as in the example responds with a propper information about the virtual machine vmdk mapping on the vmfs file system, but its not documented anywhere.
