### ISSUE TITLE
[BUG] Terraform cannot create VMs with vApp config against VCSIM

### ISSUE THREAD

**Issue by nma** [vmware/govmomi#2642]
**Describe the bug**
When running terraform with the `vApp.properties` field I get an error with `this VM lacks a vApp configuration` from Terraform. (see [sample terraform](https://gist.github.com/nma/62ad47dec38fb9987366fd69a01da252#file-main-tf))

```
vsphere_virtual_machine.vm: Creating...
╷
│ Error: error reconfiguring virtual machine: error in virtual machine configuration: this VM lacks a vApp configuration and cannot have vApp properties set on it
│
│   with vsphere_virtual_machine.vm,
│   on main.tf line 48, in resource "vsphere_virtual_machine" "vm":
│   48: resource "vsphere_virtual_machine" "vm" {
│
```

Upon inspecting the VCSIM created VMs I note that all VMs do not have any vApp properties regardless of how I create them.

```
govc vm.info -vm.ipath=/DC0/vm/DC0_H0_VM0 -json | jq -r '.VirtualMachines[0].Config'
```
See output https://gist.github.com/nma/62ad47dec38fb9987366fd69a01da252#file-sample_govc_output-json

**To Reproduce**

1.  Use the sample terraform provided https://gist.github.com/nma/62ad47dec38fb9987366fd69a01da252
1. `terraform init`, `terraform apply`
1. Receive errors regarding `this VM lacks a vApp configuration`
1. Remove Vapp config section on terraform 
1. See that the `terraform apply` passes.

**Expected behavior**
Expected the terraform VM creation can use `vApp` configs to setup SSH keys and user scripts in VCSIM for testing.

**Affected version**

`github.com/vmware/govmomi v0.23.1`

**Additional notes**

I've read through the simulator code and it looks like vApp is not set in the `type VirtualMachineConfigInfo struct` for the simulator. https://github.com/vmware/govmomi/blob/master/simulator/virtual_machine.go#L76.

Was there a reason this was omitted, would it be an easy fix to include vApp settings?

**Comment by dougm** [comment]
We need to add vcsim support for vApp config, @aruneshpa was starting to look at doing this.
