### ISSUE TITLE
Add flags in vm.upgrade for scheduling

### ISSUE THREAD

**Issue by mdechiaro** [vmware/govmomi#2647]
**Is your feature request related to a problem? Please describe.**
There is an option to schedule a VM hardware upgrade, so it upgrades when the system is rebooted. It would be a useful feature to have in govc, especially when you need to automate the upgrade of VMs so that they upgrade themselves during a scheduled patch cycle.

**Describe the solution you'd like**
govc vm.upgrade -vm $VM -scheduled -policy < always | never | onSoftPowerOff >

**Describe alternatives you've considered**
Currently the VM needs to be powered off, upgraded, then powered on. It's more efficient, especially when dealing with many VMs, to schedule this during a patch cycle and reboot.

**Additional context**
API docs I can find about it:

https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.ScheduledHardwareUpgradeInfo.HardwareUpgradeStatus.html

https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.ScheduledHardwareUpgradeInfo.html

https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.ScheduledHardwareUpgradeInfo.HardwareUpgradePolicy.html

**Comment by dougm** [comment]
Hi @mdechiaro , just catching up here I see some commits in your fork referencing this issue.. do you want to open a PR against the govmomi repo so we can review and merge your changes?

**Comment by mdechiaro** [comment]
@dougm Thanks for the reminder about this. I had to re-prioritize my workload last month and then took a long vacation. I plan revisiting this within the next two weeks and will submit a PR.
