### ISSUE TITLE
VM power state consult

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2659]
type VirtualMachineRuntimeInfo struct {
	DynamicData

	Device                    []VirtualMachineDeviceRuntimeInfo            `xml:"device,omitempty"`
	Host                      *ManagedObjectReference                      `xml:"host,omitempty"`
	ConnectionState           VirtualMachineConnectionState                `xml:"connectionState"`
	PowerState                VirtualMachinePowerState                     `xml:"powerState"`
	FaultToleranceState       VirtualMachineFaultToleranceState            `xml:"faultToleranceState,omitempty"`
	DasVmProtection           *VirtualMachineRuntimeInfoDasProtectionState `xml:"dasVmProtection,omitempty"`
	ToolsInstallerMounted     bool                                         `xml:"toolsInstallerMounted"`
	SuspendTime               *time.Time                                   `xml:"suspendTime"`
	BootTime                  *time.Time                                   `xml:"bootTime"`
	SuspendInterval           int64                                        `xml:"suspendInterval,omitempty"`
	Question                  *VirtualMachineQuestionInfo                  `xml:"question,omitempty"`
	MemoryOverhead            int64                                        `xml:"memoryOverhead,omitempty"`
	MaxCpuUsage               int32                                        `xml:"maxCpuUsage,omitempty"`
	MaxMemoryUsage            int32                                        `xml:"maxMemoryUsage,omitempty"`
	NumMksConnections         int32                                        `xml:"numMksConnections"`
	RecordReplayState         VirtualMachineRecordReplayState              `xml:"recordReplayState,omitempty"`
	CleanPowerOff             *bool                                        `xml:"cleanPowerOff"`
	NeedSecondaryReason       string                                       `xml:"needSecondaryReason,omitempty"`
	OnlineStandby             *bool                                        `xml:"onlineStandby"`
	MinRequiredEVCModeKey     string                                       `xml:"minRequiredEVCModeKey,omitempty"`
	ConsolidationNeeded       *bool                                        `xml:"consolidationNeeded"`
	OfflineFeatureRequirement []VirtualMachineFeatureRequirement           `xml:"offlineFeatureRequirement,omitempty"`
	FeatureRequirement        []VirtualMachineFeatureRequirement           `xml:"featureRequirement,omitempty"`
	FeatureMask               []HostFeatureMask                            `xml:"featureMask,omitempty"`
	VFlashCacheAllocation     int64                                        `xml:"vFlashCacheAllocation,omitempty"`
	Paused                    *bool                                        `xml:"paused"`
	SnapshotInBackground      *bool                                        `xml:"snapshotInBackground"`
	QuiescedForkParent        *bool                                        `xml:"quiescedForkParent"`
	InstantCloneFrozen        *bool                                        `xml:"instantCloneFrozen"`
	CryptoState               string                                       `xml:"cryptoState,omitempty"`
}

as the powerstate is define in type VirtualMachinePowerState string

I tried to shutdown guestOS normally, if failed, then execute force power off.

I transfer the VirtualMachinePowerState type to string, then compares with it's value, but in vcenter, I can see even if the VM is shutdown guest os successfully, but still will execute the poweroff operation, would u pls tell me why?

here is my code:
if string(vmName[vmIndex].Summary.Runtime.PowerState) == "poweredOn" {
									poweroff.PoweroffVMForce(ctx, dcname[index], vmName[vmIndex].Name, c)
								}

**Comment by embano1** [comment]
See this example of how to use power states: https://github.com/embano1/vsphere-preemption/blob/main/activities.go#L171-L207

**Comment by leoxucn822** [comment]
@embano1 I update my code, I will test if it is working. many thanks for your hint.

**Comment by leoxucn822** [comment]
@embano1 I checked the running log, the program still execute the power off ops after shutdown guest os.
if vmName[vmIndex].Summary.Runtime.PowerState == types.VirtualMachinePowerStatePoweredOn, my program will always think this condition is false.

**Comment by embano1** [comment]
Please post the full code to further debug your issue.

**Comment by leoxucn822** [comment]
```
for vmIndex := range vmName {
	if vmName[vmIndex].Summary.Runtime.PowerState == types.VirtualMachinePowerStatePoweredOn {
		poweroff.PoweroffVMForce(ctx, dcname[index], vmName[vmIndex].Name, c)
	}
}
```

**Comment by embano1** [comment]
This is likely due to the fact that the properties you're using, here `PowerState` are stale. You need to fetch the properties again after a power operation.

**Comment by leoxucn822** [comment]
@embano1 many thanks for your help, I will update the code and test for the next operation.

**Comment by embano1** [comment]
No worries. Did the change work and can we close this issue then?

**Comment by leoxucn822** [comment]
@embano1 I retrieve the power state  after the VM power operation. but still the program will force power again.
```
pc := property.DefaultCollector(c)
for vmIndex := range vmName {
  poweroff.PoweroffVM(ctx, dcname[index], vmName[vmIndex].Name, c)
}

err = pc.Retrieve(ctx, host.Vm, []string{"summary.runtime.powerState"}, &vmName)

for vmIndex := range vmName {
	if vmName[vmIndex].Summary.Runtime.PowerState == types.VirtualMachinePowerStatePoweredOn {
		poweroff.PoweroffVMForce(ctx, dcname[index], vmName[vmIndex].Name, c)
	}
}
```

**Comment by embano1** [comment]
Can you please dump the full source code here so I can see the imports you're using?

This code shows using the `PowerOff` method and that it returns a task and error. You need to at least wait for the task to complete successfully before checking the power state since those operations are performed asynchronously: https://github.com/vmware/govmomi/blob/13c63036eaea8f73d25f83f4c5585f8db5b1aa12/govc/vm/power.go#L170

**Comment by leoxucn822** [comment]
@embano1 because my code is so long, it is not easy to push all the code here, let me share some function of power off part.
```
package poweroff

import (
	"context"
	"fmt"

	"github.com/vmware/govmomi/find"
	"github.com/vmware/govmomi/vim25"
)

func PoweroffVM(ctx context.Context, dcname string, vmname string, c *vim25.Client) {
	finder := find.NewFinder(c)
	dc, _ := finder.Datacenter(ctx, dcname)
	//if err != nil {
	//	return err
	//}
	finder = finder.SetDatacenter(dc)
	obj, _ := finder.VirtualMachine(ctx, vmname)
	err := obj.ShutdownGuest(ctx)
	if err != nil {
		//return error
		fmt.Printf("Error: server %s shutdown os failed, %v\n", vmname, err)
	}
	//return nil
}

func PoweroffVMForce(ctx context.Context, dcname string, vmname string, c *vim25.Client) {
	finder := find.NewFinder(c)
	dc, _ := finder.Datacenter(ctx, dcname)
	//if err != nil {
	//	return err
	//}
	finder = finder.SetDatacenter(dc)
	obj, _ := finder.VirtualMachine(ctx, vmname)
	_, err := obj.PowerOff(ctx)
	if err != nil {
		//return error
		fmt.Printf("Error: server %s poweroff os failed, %v\n", vmname, err)
	}
	//return nil
}

here is part of main power off function:
```
import(
	"github.com/vmware/govmomi/find"
	"github.com/vmware/govmomi/property"
	"github.com/vmware/govmomi/vim25"
	"github.com/vmware/govmomi/vim25/mo"
	"github.com/vmware/govmomi/vim25/types"
)
for index := range dcname {
					finder := find.NewFinder(c)
					dc, err := finder.Datacenter(ctx, dcname[index])
					if err != nil {
						return err
					}
					finder = finder.SetDatacenter(dc)
					pc := property.DefaultCollector(c)
					obj, err := finder.HostSystem(ctx, hostnamefqdn)
					if err != nil {
						continue
					}

					var host mo.HostSystem
					err = pc.RetrieveOne(ctx, obj.Reference(), []string{"vm"}, &host)
					if err != nil {
						return err
					}

					var vmName []mo.VirtualMachine
					err = pc.Retrieve(ctx, host.Vm, []string{"name"}, &vmName)
					if err != nil {
						continue
					} else {
						for vmIndex := range vmName {
                                                      poweroff.PoweroffVM(ctx, dcname[index], vmName[vmIndex].Name, c)
                                                }
                                         }
}
fmt.Println("pls wait for 1mins that all the VMs in " + hostname[i] + " to shut down guestOS!")
time.Sleep(60 * time.Second)
err = pc.Retrieve(ctx, host.Vm, []string{"summary.runtime.powerState"}, &vmName)

for vmIndex := range vmName {
	if vmName[vmIndex].Summary.Runtime.PowerState == types.VirtualMachinePowerStatePoweredOn {
		poweroff.PoweroffVMForce(ctx, dcname[index], vmName[vmIndex].Name, c)
	}
}

```

**Comment by leoxucn822** [comment]
@embano1 it should working now. I test in environment, and it won't execute the power off function after shutdown guest os successfully.

**Comment by embano1** [comment]
Glad to hear, so we can close this issue then?

**Comment by leoxucn822** [comment]
@embano1 yeah, I will close this. many thanks!
