### ISSUE TITLE
Creating a Netwok

### ISSUE THREAD

**Issue by abhinand5** [vmware/govmomi#2660]
How to create a network? Like the default "VM Network" that comes with vcsim. I want to create my own. I am not sure how to do that with `govc`. 

In the help it shows we need to input a switchname/portgroup
`$ govc vm.network.add -vm $vm -net SwitchName/PortgroupName`

I went ahead and created a dvs switch
`$ govc dvs.create -dc=DC0 dswitch`

Then I created a portgroup
`$ govc dvs.portgroup.add -dc=DC0 -dvs=dswitch -nports 16 mynetwork`

Now when adding the network to my VM it says `govc: *types.InvalidArgument` but I don't know which argument is invalid
`$ govc vm.network.add -dc=DC0 -vm ubuntu-bionic-18.04 -net "dswitch/mynetwork"`

**Comment by dougm** [comment]
If you look at vcsim's stderr output, the `InvalidArgument` here correlates to this log message:
```
DC0_H0 is not a member of VDS dswitch
```
You just need to add hosts to the DVS like so:
```console
% govc dvs.add -dvs dswitch $(govc find / -type h)
adding 4 hosts to dvs /DC0/network/dswitch... OK
```
