### ISSUE TITLE
Create Network Protocol Profiles

### ISSUE THREAD

**Issue by braunsonm** [vmware/govmomi#2661]
**Is your feature request related to a problem? Please describe.**
I would like to be able to create/edit network protocol profiles. There doesn't seem to be any supported commands to do this. Even with `object.collect`

**Describe the solution you'd like**
A command in `govc` to create/edit/delete NPP's

**Describe alternatives you've considered**
As far as I know there is no alternative. The vSphere Terraform provider also does not support them.

**Additional context**
[Add any other context or screenshots about the feature request here.](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-D24DBAA0-68BD-49B9-9744-C06AE754972A.html)
https://github.com/hashicorp/terraform-provider-vsphere/issues/1258

**Comment by braunsonm** [comment]
Bump

**Comment by djpbessems** [comment]
I am also interested in this as a feature; right now my only somewhat viable option is to use PowerCLI; but installing PowerCLI is really something I would like to avoid in my bootstrap VM (distributed as an OVA, so I want to keep it small!)

**Comment by djpbessems** [comment]
@braunsonm  Do you have any idea what the ManagedObjectReference ID for a Network Protocol Profile would look like (if there even is a moref assigned)?

By doing a `govc find . | xargs -I {} govc object.collect -json {} | grep 'FooBar' -B20` (FooBar being the name I gave to my test profile, to make it stand out when searching for it) I've managed to find *one* mention of a `recentTask` mentioning `"IpPoolName": "FooBar"`

Then when I do a `govc object.collect -s -dump | grep 'IpPool' -B50` I can see a ManagedObjectReference Type of `IpPoolManager`; but then the trail went cold, leaving me to think that there really isn't any way to interact with these IpPools through govc :(

**Comment by braunsonm** [comment]
@djpbessems that's why this issue exists

**Comment by djpbessems** [comment]
Yeah obviously, I was just thinking that you might have some more insight that could still lead me to a hack to achieve this anyway ;)

**Comment by braunsonm** [comment]
Still relevant

**Comment by djpbessems** [comment]
I've been trying to figure this out (so I can get rid of PowerCLI in my stack), and am getting really close...

With the following code:
```go
	request := &types.CreateIpPool{
		This: *clt.ServiceContent.IpPoolManager,
		Dc:   dc.Reference(),
		Pool: types.IpPool{
			Name:          "ippool-" + (uuid.New().String()),
			DnsDomain:     "<placeholderfqdn>",
			DnsSearchPath: "<placeholderfqdn>",
			// NetworkAssociation: []types.IpPoolAssociation{{
			// 	// This currently generates the error 'cannot use nw.Reference() (value of type types.ManagedObjectReference) as type *types.ManagedObjectReference in struct literal'
			// 	Network:     nw.Reference(),
			// 	NetworkName: network,
			// },
			// },
		},
	}

	response, err := methods.CreateIpPool(ctx, clt.RoundTripper, request)
	if err != nil {
		log.Fatalf("Bar: %s", err)
	}
```
I can successfully generate a new Network Protocol Profile. I'll have to work on actually providing all the required fields with sane values *and* figure out how to associate it to an actual network.

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump
