### ISSUE TITLE
Auto-register VAPI Simulator endpoints to prevent `404 Not Found`

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2663]
**Is your feature request related to a problem? Please describe.**
When writing unit tests for a 3rd party project using `simulator.Run()` (and related) functionality, one has to manually `_` import the VAPI simulator endpoints, otherwise tests against the VAPI REST API will fail with `POST https://127.0.0.1:<port>/rest/com/vmware/cis/session: 404 Not Found`.

**Describe the solution you'd like**
When I use `simulator.Run()` auto-register VAPI API simulator endpoints.

**Describe alternatives you've considered**
Manually import the required package so that `init()` runs: 

```go
  _ "github.com/vmware/govmomi/vapi/simulator"
```

**Additional context**
Not an easy one to troubleshoot if one is not familiar how the internal code base of the simulator works when troubleshooting such REST API `404` errors.

**Comment by codegold79** [comment]
> Not an easy one to troubleshoot if one is not familiar how the internal code base of the simulator works when troubleshooting such REST API 404 errors.

Thank you @embano1! I came across this problem and had no idea how to fix it. Thank you for finding the workaround.
