### ISSUE TITLE
How to get Datastore disk info using Govmomi

### ISSUE THREAD

**Issue by imrushi** [vmware/govmomi#2680]
We were able to manage to get below information using pyvmomi but couldn't get the same information using govmomi.
Could you please help me with how to get below information?

{
"lun_name": "Local DELL Disk (xxx.xxxxxxxxxxx)",
"storage_disk_type": "HDD",
"sr_type": "VMFS 6",
}

**Comment by embano1** [comment]
An example of how to do this is here in the `govc` `datastore.info` command: https://github.com/vmware/govmomi/blob/afc67f589a3d1bcb066ac2a0724a1cace1b3f4a9/govc/datastore/info.go#L173

You need to use the `propertyCollector` to retrieve properties for a managed object.

**Comment by imrushi** [comment]
Hi @embano1,

Thanks for example. I am getting the information from `govc host.storage.info -host=1x.xx.xx.xx` 

Can you please tell me how should I retrieve the same information in my code using govmomi package?

**Comment by embano1** [comment]
The link I pasted above to `info.go` has details on how to use the `propertyCollector` to do this via `govmomi`. In general, inpecting the `govc` code base is useful to understand how the underlying library is used.

**Comment by imrushi** [comment]
Thank you for your help @embano1.

Here is the solution to get Datastore disk info 

```go

var dst []mo.HostSystem
err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"summary", "hardware", "capability", "configManager", "config", "datastore", "network"}, &dst)
if err != nil {
	exit(err)
}

for _, a := range dst[i].Config.StorageDevice.ScsiLun {
		lun_name = a.GetScsiLun().DisplayName
		disk_type = a.GetScsiLun().LunType
}
```

for Datastore type and version.

```go
var hst []mo.Datastore
err = v.Retrieve(ctx, []string{"Datastore"}, []string{"summary", "parent", "host", "vm", "info", "capability", "iormConfiguration"}, &hst)
if err != nil {
	exit(err)
}

for _, hs := range hst {
        vmfs := hs.Summary.Type
        vmfs_version := hs.Info.(*types.VmfsDatastoreInfo).Vmfs.MajorVersion
}
```
