### ISSUE TITLE
Simulator to support VM Migration events

### ISSUE THREAD

**Issue by sudhiaithal** [vmware/govmomi#2681]
**Is your feature request related to a problem? Please describe.**
If we a trigger Relocate VM api on simulator, I see that we just update the internal DB to relocate VM to new destination VM. It will be nice if we can post an event to who ever is subscribing to these events, to mock the same behavior as real Vcenter.
Today, it seems like we simulator only support object CRUDs via WaitForUpdatesEx, but events are not supported. 

**Describe the solution you'd like**
I am not sure whether we have Events dispatch framework in simulator, if that is there we can piggy back to that, but browsing in simulator directory, I did not find this.

**Describe alternatives you've considered**

**Additional context**

**Comment by embano1** [comment]
True, there's currently no framework and these events have to be manually injected. Here's an example for a powerOn operation: https://github.com/vmware/govmomi/blob/84c00db1694d705aaffc00e3e3e44932b2a00a55/simulator/virtual_machine.go#L1508

**Comment by dougm** [comment]
vcsim's `RelocateVM_Task` method does emit a `VmMigratedEvent` (recently added in #2627), which version of govmomi/vcsim are you using?

See: https://github.com/vmware/govmomi/blob/59582c4b15bd063898fa424101b10db1030dc463/simulator/virtual_machine.go#L1932-L1937

**Comment by sudhiaithal** [comment]
Thanks @dougm , this is good but still I wanted VmBeingHotMigratedEvent, configurable delay and then VmMigratedEvent sent. Optionally with some parameter, VmMigrationFailedEvent as well if we want to simulate failure.
