### ISSUE TITLE
[BUG] Calling SetCustomValue adds a duplicate key instead of updating the value

### ISSUE THREAD

**Issue by nilsanderselde** [vmware/govmomi#2687]
**Describe the bug**
Calling `SetCustomValue` (for a VM, but presumably everything else) for the same key repeatedly does not have the expected effect of updating the existing key, but rather adds a duplicate key with the new value. The code in question which merely appends the new value is here: https://github.com/vmware/govmomi/blob/10046a02daec375b12624e2e46fd555c28e8fd6c/simulator/custom_fields_manager.go#L186-L195

**To Reproduce**

1. Call `SetCustomValue` on an `*object.VirtualMachine`
1. Check the length of the custom values slice.
1. Call `SetCustomValue` with a different value for the same key
1. Check the length of the custom values slice. There will be one additional value.
1. Examine the contents of the custom values slice. You will see two entries for the same key, one with each value.

**Expected behavior**
I expect the value of the custom field to be updated, not to have a duplicate appended.

**Affected version**
Current `master` (10046a02daec375b12624e2e46fd555c28e8fd6c)

**Screenshots/Debug Output**
Example log output below. The number after the text "custom values" is the slice index.
```
{"msg":"custom values #0:","Name":"key","Value":"some_value","Key":2}
{"msg":"custom values #1:","Name":"key","Value":"new_value","Key":2}
```

**Additional context**
I was able to get this working in a fork: https://github.com/nilsanderselde/govmomi/pull/1/files?diff=split&w=1

I removed the old values before adding the new ones.

**Comment by dougm** [comment]
Thanks @nilsanderselde , can you open your PR against the govmomi repo so we can review and merge?

**Comment by nilsanderselde** [comment]
@dougm Opened https://github.com/vmware/govmomi/pull/2700
