### ISSUE TITLE
"ServerFaultCode: A specified parameter was not correct:"

### ISSUE THREAD

**Issue by arnegroskurth** [vmware/govmomi#2689]
**Description**

Multiple methods interacting with the VMware guest tools on any tried VM yield the error `ServerFaultCode: A specified parameter was not correct: `. The error shows up for the commands `guest.run`, `guest.ps`, `guest.ls`, `guest.mkdir`, `guest.touch`. From the tried `guest.*` commands, only `guest.df` works as expected.

Last entry when starting with `guest.mkdir -verbose -vm ... /tmp/test`:

```
...

ChangeFileAttributesInGuest(guestOperationsFileManager, VirtualMachine:vm-51, *types.NamePasswordAuthentication, /tmp/test, *types.GuestFileAttributes)...
&soap.Fault{
    XMLName: xml.Name{Space:"http://schemas.xmlsoap.org/soap/envelope/", Local:"Fault"},
    Code:    "ServerFaultCode",
    String:  "A specified parameter was not correct: ",
}
govc: ServerFaultCode: A specified parameter was not correct: 
```

From `vmware.log` of that VM:

```
...

2021-12-23T09:59:07.221Z| vmx| I125: VigorTransportProcessClientPayload: opID=6c2c2bbe-1a-fff3 seq=23663285: Receiving GuestOps.SetFileAttributes request.
2021-12-23T09:59:07.320Z| vcpu-4| I125: VigorTransport_ServerSendResponse opID=6c2c2bbe-1a-fff3 seq=23663285: Completed GuestOps request with messages.
```

I'm not sure what other logs could be interesting here.

**How to reproduce**

E.g.: `GOVC_URL=... GOVC_INSECURE=true govc guest.touch -vm ... /tmp/test`

**Affected versions**

The error can be reproduced with govc 0.27.0 and 0.27.2 running against a vSphere Client version 6.7.0.50000.
The problem does not seem to be related to a VM as it can be re-produced with multiple VMs running different versions of Linux.
It can also be reproduced both with the Linux binaries from the GitHub releases page as well as with the `vmware/govc` docker container version.

**Similar issues**

https://github.com/vmware/govmomi/issues/2054

**Comment by arnegroskurth** [comment]
Just found in vmware tools log `/var/log/vmware-vmsvc-root.log` within vm:

```
[2021-12-23T10:07:52.693Z] [ message] [vix] VixTools_ProcessVixCommand: command 183
[2021-12-23T10:07:52.693Z] [ warning] [VCGA] Empty Username
[2021-12-23T10:07:52.693Z] [ warning] [vix] VixToolsImpersonateUser: impersonation failed (3)
[2021-12-23T10:07:52.693Z] [ message] [vix] VixToolsSetFileAttributes: opcode 183 returning 3
[2021-12-23T10:07:52.693Z] [ message] [vix] ToolsDaemonTcloReceiveVixCommand: command 183, additionalError = 2
```

**Comment by arnegroskurth** [comment]
Found the solution: You have to also specify a guest vm login like `user:pass` via `-l=: Guest VM credentials [GOVC_GUEST_LOGIN]`.

Seems to be like govc could be improved by always requiring the login or at least hint at the missing login when the request fails.

**Comment by dougm** [comment]
If we defaulted the `-l` flag to a non-empty value (such as the patch below), the API/govc would return the following if `-l` is not specified:
```
govc: ServerFaultCode: Failed to authenticate with the guest operating system using the supplied credentials.
```

I'd lean toward that vs having govc check that `-l` is specified, as guest auth can be optional if using [govmomi/toolbox](https://github.com/vmware/govmomi/tree/master/toolbox#readme) instead of standard vmware-tools.  What do you think?

```diff
modified   govc/vm/guest/auth.go
@@ -54,6 +54,9 @@ func (flag *AuthFlag) Set(s string) error {
 func (flag *AuthFlag) Register(ctx context.Context, f *flag.FlagSet) {
 	env := "GOVC_GUEST_LOGIN"
 	value := os.Getenv(env)
+	if value == "" {
+		value = "root"
+	}
 	err := flag.Set(value)
 	if err != nil {
 		fmt.Printf("couldn't set guest login values: %v", err)
```
