### ISSUE TITLE
govc - support supervisor services creation

### ISSUE THREAD

**Issue by rikatz** [vmware/govmomi#2690]
**Is your feature request related to a problem? Please describe.**
govc supports partially the WCP API to manage namespaces. It needs some support for the recently added supervisor services as well, allowing VC Admins to publish a new cluster service (operator) and deploy them

**Describe the solution you'd like**
Add a new `govc.service.*` subset of commands to support creating  new supervisor services.

**Describe alternatives you've considered**
Using dcli or vcui for this

**Additional context**
 This issue does not cover yet deploying a version of a service to a cluster

**Comment by dougm** [comment]
Added in #2668 , thanks again @rikatz
