### ISSUE TITLE
Set `User-Agent` in `http.Client` used in govmomi lib

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2693]
**Is your feature request related to a problem? Please describe.**
Set a default value for `User-Agent` in `http.Client` when using the library (`govc` already allows this) to identify requests coming from `govmomi` SDK (currently it only shows a generic Go client in stats). Useful for debugging, statistics, etc.

**Describe the solution you'd like**
Set a default value for `User-Agent` in `http.Client`
https://github.com/vmware/govmomi/blob/59582c4b15bd063898fa424101b10db1030dc463/vim25/soap/client.go#L75

**Describe alternatives you've considered**
Keep as is

**Additional context**
Should not be considered a breaking change IMHO?

**Comment by embano1** [comment]
Example (adopted from `aws-sdk-go`): 

```go
// file: version.go
package govmomi

// SDKName is the name of this library
const LibraryName = "govmomi"

// SDKVersion is the version of the library
const LibraryVersion = "0.28.0"
```
Source: https://github.com/aws/aws-sdk-go/blob/main/aws/version.go

**Comment by dougm** [comment]
When/how would the automation update the `LibraryVersion` ?

Another option might be to update `LibraryVersion` manually and automate creating the tag from that?

But I'm good with adopting a common pattern from what other projects are doing these days.

**Comment by embano1** [comment]
> When/how would the automation update the LibraryVersion ?

My idea: create a `dispatch` Github Actions workflow which is triggered before creating a release by a maintainer. It will patch the `version` based on user input (all within Github UI) and automatically create a PR for review. I would also update the `release` workflow to check whether the `tag` matches `version` and fail a release if not.

> Another option might be to update LibraryVersion manually and automate creating the tag from that?

Thought about manual way too, but this would require someone to file a PR (since we don't directly push to `master`). The above would not require this.

**Comment by dougm** [comment]
> > When/how would the automation update the LibraryVersion ?
> 
> My idea: create a `dispatch` Github Actions workflow which is triggered before creating a release by a maintainer. It will patch the `version` based on user input (all within Github UI) and automatically create a PR for review. I would also update the `release` workflow to check whether the `tag` matches `version` and fail a release if not.

That sounds cool.  Maybe someday I'll learn more about GH Actions, in the meantime thanks for all your efforts around this!

> > Another option might be to update LibraryVersion manually and automate creating the tag from that?
> 
> Thought about manual way too, but this would require someone to file a PR (since we don't directly push to `master`). The above would not require this.

True, in the old days I would bump the const version as part of the PR for release docs update (usage, changelog, contributors, etc). Would be much better to automate the version bump.

**Comment by atc0005** [comment]
Question (likely from ignorance):

Once this feature is developed/implemented, will it block setting a more specific user agent?

Snippet from a project where I'm using this library:

```golang
	c, err := govmomi.NewClient(ctx, u, trustCert)
	if err != nil {
		return nil, err
	}

	// Override default user agent
	c.Client.UserAgent = userAgent

	// provide credentials *after* we create the client so that the desired
	// User Agent value can be set before logging in.
	u.User = url.UserPassword(username, password)

	// Login, supplying our custom user agent in place of the default
	authErr := c.Login(ctx, u.User)
	if authErr != nil {
		return nil, authErr
	}
```

where:

- `trustCert` is a user-specified choice of whether they wish to trust the cert
- `userAgent` is a project specific name/version string (based on git tag)
  - intended to identify the source of the tool logging into a vSphere environment

**Comment by embano1** [comment]
Thx for the great feedback @atc0005 ! This is really useful and my plan was to definitely allow for customization/overwriting the `agent`, and providing a meaningful default value when not.
