### ISSUE TITLE
SDK crashed on fetching of DistributedVirtualPortgroup.

### ISSUE THREAD

**Issue by Harish-Kumar-S** [vmware/govmomi#2694]
**Describe the bug**
```
v, err := vcc.manager.CreateContainerView(ctx, container, kind, true)
  if err != nil {
    return nil, err
  }

var DVSPortGroupList []mo.DistributedVirtualPortgroup
 ps := []string{"key", "config"}
 err = v.Retrieve(ctx, []string{"DistributedVirtualPortgroup"}, ps, &DVSPortGroupList)
```
This works fine if the Traffic filtering and marking are Turned OFF for the portgroup.
**Error log:**
`panic(0x2d38e40, 0x3b88400)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
reflect.Value.Addr(0x2f97a40, 0xc00cf8cdc0, 0x16, 0x3cd2300, 0x2ff86e0, 0x16)
        /usr/local/go/src/reflect/value.go:271 +0x85
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2ff86e0, 0xc005973b80, 0x194, 0xc005973b40, 0xc005973b80, 0x194)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:347 +0x2d25
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2c9acc0, 0xc00f600028, 0x197, 0xc005973b40, 0xc00f600028, 0x197)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x2373
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc009049020, 0x34d6780, 0xc00f600000, 0x199, 0x0, 0x0, 0x0, 0xc005973b40, 0x1, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x34d6780, 0xc00f600000, 0x199, 0xc005973800, 0xc00f600000, 0x199)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2c9ca40, 0xc0059735e0, 0x197, 0xc005973800, 0xc0059735e0, 0x197)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x2373
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc009048e80, 0x33c3800, 0xc0059735c0, 0x199, 0x0, 0x0, 0x0, 0xc005973800, 0xc005973501, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2ecf2c0, 0xc00e2608f0, 0x196, 0xc005973580, 0xc00e2608f0, 0x196)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc009048c00, 0x3175b80, 0xc00e2608a0, 0x199, 0x0, 0x0, 0x0, 0xc005973580, 0x1, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x3175b80, 0xc00e2608a0, 0x199, 0xc005973240, 0x199, 0x3175b80)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2ff8660, 0xc005973280, 0x194, 0xc005973240, 0xc005973280, 0x194)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:335 +0x2c9b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2c9ac80, 0xc00cf8c968, 0x197, 0xc005973240, 0xc00cf8c968, 0x197)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x2373
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc001c1a3a0, 0x3174fa0, 0xc00cf8c960, 0x199, 0x0, 0x0, 0x0, 0xc005973240, 0xc005973001, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2f97540, 0xc00e3056b0, 0x196, 0xc0059730c0, 0xc00e3056b0, 0x196)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc001d072c0, 0x3579420, 0xc00e305680, 0x199, 0x0, 0x0, 0x0, 0xc0059730c0, 0x1, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x3579420, 0xc00e305680, 0x199, 0xc0057b31c0, 0x199, 0x3579420)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2fc6d60, 0xc008e8aff0, 0x194, 0xc0057b31c0, 0xc008e8aff0, 0x194)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:335 +0x2c9b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc001d06fe0, 0x3638f80, 0xc008e8afc0, 0x199, 0x0, 0x0, 0x0, 0xc0057b31c0, 0x1, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x3638f80, 0xc008e8afc0, 0x199, 0xc0057b2dc0, 0x199, 0x3638f80)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2f62860, 0xc00e305610, 0x194, 0xc0057b2dc0, 0xc00e305610, 0x194)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:335 +0x2c9b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc0001a3c00, 0x3175fe0, 0xc00e305600, 0x199, 0x0, 0x0, 0x0, 0xc0057b2dc0, 0xc00ee46201, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x3175fe0, 0xc00e305600, 0x199, 0xc0057b2c40, 0xc00e305600, 0x199)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2c9cb40, 0xc00f2dfa20, 0x197, 0xc0057b2c40, 0xc00f2dfa20, 0x197)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x2373
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc0001a2680, 0x33275a0, 0xc00f2dfa00, 0x199, 0x0, 0x0, 0x0, 0xc0057b2c40, 0x1, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x33275a0, 0xc00f2dfa00, 0x199, 0xc0057b2a40, 0xc00f2dfa00, 0x199)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2ca0000, 0xc00d905e20, 0x197, 0xc0057b2a40, 0xc00d905e20, 0x197)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:442 +0x2373
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc0001a25c0, 0x309fc00, 0xc00d905e20, 0x199, 0x0, 0x0, 0x0, 0xc0057b2a40, 0xc00cce6001, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2c38240, 0xc00d90e3c8, 0x196, 0xc00cce6180, 0xc00d90e3c8, 0x196)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc000355860, 0x3253d00, 0xc00d90e3c0, 0x199, 0x0, 0x0, 0x0, 0xc00cce6180, 0xc00ccdbf80, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x2e9cc00, 0xc00cce28e8, 0x194, 0xc00cce6040, 0xc00cce28e8, 0x194)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc0089f8300, 0xc000dd1f20, 0x3256040, 0xc00cce28c0, 0x199, 0x0, 0x0, 0x0, 0xc00cce6040, 0x0, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:716 +0x585
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc0089f8300, 0x3256040, 0xc00cce28c0, 0x199, 0xc00ccdbf40, 0x199, 0x0)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:547 +0xfb1
github.com/vmware/govmomi/vim25/xml.(*Decoder).DecodeElement(0xc0089f8300, 0x2c10040, 0xc00cce28c0, 0x0, 0xc00ccdbc80, 0x22a30b0f01db5dbb)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:133 +0x12b
github.com/vmware/govmomi/vim25/xml.(*Decoder).Decode(...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/xml/read.go:121
github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip.func1(0xc002a5abd0, 0x536c546582e41, 0x571b840)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/soap/client.go:621 +0xf3
github.com/vmware/govmomi/vim25/soap.(*Client).Do(0xc003e70420, 0x3c97ba0, 0xc00ee46300, 0xc00f58c200, 0xc001db6240, 0x0, 0x0)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/soap/client.go:518 +0x33a
github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip(0xc003e70420, 0x3c97ba0, 0xc0022396e0, 0x3c2ca20, 0xc00d90e3a0, 0x3c2ca20, 0xc00d90e3c0, 0x7faa345fd501, 0xc00d90e3c0)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/soap/client.go:609 +0x8f6
github.com/vmware/govmomi/vim25.(*Client).RoundTrip(0xc001facb00, 0x3c97ba0, 0xc0022396e0, 0x3c2ca20, 0xc00d90e3a0, 0x3c2ca20, 0xc00d90e3c0, 0x40, 0x31958e0)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/client.go:120 +0x82
github.com/vmware/govmomi/vim25/methods.RetrieveProperties(0x3c97ba0, 0xc0022396e0, 0x3c2b560, 0xc001facb00, 0xc00cce2880, 0x0, 0x0, 0xc00ee46150)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/vim25/methods/methods.go:13799 +0xb8
github.com/vmware/govmomi/property.(*Collector).RetrieveProperties(0xc001db65e8, 0x3c97ba0, 0xc0022396e0, 0x0, 0x0, 0x0, 0x0, 0xc00cce2800, 0x1, 0x1, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/property/collector.go:122 +0xf9
github.com/vmware/govmomi/view.ContainerView.Retrieve(0x0, 0x0, 0xc001facb00, 0xc00ebd20e0, 0xd, 0xc00f6fc120, 0x51, 0x3c97ba0, 0xc0022396e0, 0xc001db68b8, ...)
        /tmp/nWvNfhi1wJ/BUILD//vendor/github.com/vmware/govmomi/view/container_view.go:82 +0x5bf`

**To Reproduce**

1. creating a new VM with DistributedVirtualPortgroup with Traffic filtering and marking is Turned ON feature, then code throws panic error 
2. when we have the feature Traffic filtering and marking is Turned ON feature with mac rules added in any of the portgroup, then also we are facing this same issue - 
<img width="1446" alt="Screenshot 2022-01-07 at 1 57 34 PM" src="https://user-images.githubusercontent.com/78196997/148515136-b389c2fb-4f2f-4302-a226-18357377df53.png">

**Expected behavior**
It should return the list of DistributedVirtualPortgroup

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.

**Screenshots/Debug Output**

**Additional context**

**Comment by Harish-Kumar-S** [comment]
@dougm

**Comment by dougm** [comment]
What version of govmomi are you using?  This looks like an issue that has been fixed: https://github.com/vmware/govmomi/pull/2219

**Comment by Harish-Kumar-S** [comment]
govmomi v0.22.1

**Comment by embano1** [comment]
Can you please upgrade to [`latest`](https://github.com/vmware/govmomi/releases/latest) and retry?

**Comment by Harish-Kumar-S** [comment]
Sure @embano1. Will try that. Thanks!
