### ISSUE TITLE
Support: Testing govmomi

### ISSUE THREAD

**Issue by andresmonc** [vmware/govmomi#2697]
Hello! Apologies if this is the worst possible place to look for this help but I can't seem to find many resources. I'm trying to figure out what the best way is for testing code where a vcenter connection is occuring? Is there anyway to mock responses? Are there any testing examples of projects using govmomi?

**Comment by embano1** [comment]
Hi @andresmonc ! No need to excuse :)

`govmomi` provides a (limited) simulator aka [`vcsim`](https://github.com/vmware/govmomi/tree/master/vcsim), which you can run locally. Alternatively, for testing code/contributions programmatically you can use the `simulator` package which is heavily used in unit tests and the [examples](https://github.com/vmware/govmomi/tree/master/examples).

**Comment by andresmonc** [comment]
@embano1  thank you very much! that is exactly what I was looking for and I appreciate the friendliness
