### ISSUE TITLE
vmware sdk connection time out

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2698]
what is the default vmware sdk connection time out. I find my program will prompt no authorization after running some time. anyone can help me on this. thanks in advance!

**Comment by embano1** [comment]
Are you talking about `keep-alive`? If so, there's various ways to add `keep-alive` logic to the vSphere APIs (SOAP/REST). A simple library and example is this one: https://github.com/embano1/vsphere (see package `client`)

**Comment by leoxucn822** [comment]
@embano1 sorry for my late answer, I find our vcenter default time out for SDK connection is 30mins, does this can use keep-alive to reauthorize it?

**Comment by embano1** [comment]
Do you mean with timeout that the session is expired, and you're seeing NotAuthenticated errors? If so, yes please use some of the provided keep-alive mechanisms.

**Comment by leoxucn822** [comment]
@embano1 sorry for the late answer, yes, I seeing notauthentication errors, I will check with that. thank you for your help.
