### ISSUE TITLE
vix error codes = (3016, 0)

### ISSUE THREAD

**Issue by Aishwarya2** [vmware/govmomi#2699]
**Describe the bug**
ServerFaultCode: A general system error occurred: vix error codes = (3016, 0)

**To Reproduce**

We take a dependency on this package for copying files from a linux machine to windows/linux machines and execute commands 

Issue in copying  file from path /opt/amazon/stdDirc7b9299d to C:\Users\adw\adm_mar.fogo\assessmentConnectorWindows

**Comment by dougm** [comment]
Which govc command or govmomi API are you using?

3016 means vmware-tools is not running: https://github.com/vmware/open-vm-tools/blob/42ce53f39be45b7795a9f1adf892af84629b4a19/open-vm-tools/lib/include/vix.h#L151
