### ISSUE TITLE
use task collector couldn't get service item

### ISSUE THREAD

**Issue by wzy531a** [vmware/govmomi#2702]
how to use task manager and collector get service item and detail item
![QQ截图20220112172413](https://user-images.githubusercontent.com/61492156/149102064-8c90cdf6-0cc0-4c9d-86e9-37e5c805de85.png)

**Comment by embano1** [comment]
What did you try? Does this example help: https://github.com/vmware/govmomi/blob/master/examples/tasks/main.go
Here's the data structure definition: https://vdc-download.vmware.com/vmwb-repository/dcr-public/8946c1b6-2861-4c12-a45f-f14ae0d3b1b9/a5b8094c-c222-4307-9399-3b606a04af55/vim.TaskInfo.html
