### ISSUE TITLE
[BUG] tags.GetCategory fails with unrelated error when finding category by name

### ISSUE THREAD

**Issue by r4f4** [vmware/govmomi#2710]
**Describe the bug**
When trying to find a category by name, the current code will list all the category ids, loop over those ids fetching the respective category objects and then loop over those objects trying to find one with a matching name. However, if during the fetching of the objects any of them fails (e.g, it was deleted in the meantime), the whole fetching is "aborted" and no more ids are tried. `GetCategory` then fails even if the category exists and should've been fetched successfully.

**To Reproduce**
How it happens in Openshift:
Cluster A and B were created, and CI starts deleting Cluster A and then Cluster B in parallel.
Cluster A gets a list of category IDs that include [A,B]
Cluster A loops through all category IDs and gets a list of categories that includes [A,B]
Cluster B gets a list of category IDs that include [A,B]
Cluster A deletes category A.
Cluster B fails on the loop for all category IDs because category A is now 404.
Cluster B exits with an error, leaking category B.

**Expected behavior**
All the ids are tried before failing with an error

**Affected version**
Current master 6515e08f2dc566b825606d122c0d694ee9f26399

**Screenshots/Debug Output**
https://bugzilla.redhat.com/show_bug.cgi?id=2021041

**Additional context**
This will probably involve #1639 as well in case all ids were tried and no match was found

**Comment by embano1** [comment]
Thx @r4f4 for reporting this. You're not the first one to hit this, so I'm glad you filed an issue.

Fix would be:

- Check returned `err` in `c.GetCategory` if it's a `403` or `404`
- If `403` ignore and continue
- Add tests
- Document this semantical change in the signature

I might be able to work on this in the next days.

**Comment by embano1** [comment]
@r4f4 fixed in #2746
