### ISSUE TITLE
Precheck-in pipeline should fail if copyright section is not present

### ISSUE THREAD

**Issue by pradeep288** [vmware/govmomi#2713]
**Is your feature request related to a problem? Please describe.**
Currently, the pre-checkin pipeline doesn't complain, when the copyright is not present on the newly added file. this adds burden on the reviewer to ensure the copyright section is present or not

**Describe the solution you'd like**
Precheckin pipeline should fail if copyright section is not present

**Comment by embano1** [comment]
Ref #2749
