### ISSUE TITLE
waitForUpdates retrieves everything in initial output 

### ISSUE THREAD

**Issue by saksham189** [vmware/govmomi#2727]
I was trying the waitForUpdates API call using govmomi.
Initially it returns quite a lot of output with versions 0_1, 0_2,...0_29 and so on.

This happens until it gets to version = 1 where it slows down and actually starts listening for the updates. 

I wanted to know whether the initial output where the versions have underscores is the current state of all the objects for which waitForUpdates is being called. Also, is there any documentation which has more information about this?

**Comment by dougm** [comment]
You can check the `ObjectUpdate.Kind` field. With the initial response, Kind will be `enter`. With subsequent updates Kind will be `modify`, and on removal from inventory `leave`. The generated docs do not mention this that I can see: https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vmodl.query.PropertyCollector.ObjectUpdate.Kind.html

There is some mention, though not clear in this doc: https://developer.vmware.com/docs/14558/vsphere-web-services-sdk-programming-guide--7-0-update-3-/GUID-359DFCEC-0ED5-46CB-A529-C00470B2737A.html

See this test for example:
https://github.com/vmware/govmomi/blob/4f18692d0d956ed6639d17ac5d6e24a8b50eb906/simulator/property_collector_test.go#L379
