### ISSUE TITLE
Host name not present when -json flag is set for govc vm.info

### ISSUE THREAD

**Issue by NlVlN** [vmware/govmomi#2729]
**Describe the bug**
`govc vm.info` returns name of the host within the general summary (without any flag) but not when `-json=true` flag is present.

**To Reproduce**

1. Run `govc vm.info $vm`
2. Run `govc vm.info -json=true $vm`
3. Compare two outputs - no information about host in 2nd one

**Expected behavior**
Information about host should be present in json output.

**Affected version**
0.27.2

**Debug Output**
```
$ govc vm.info vm-name
Name:           vm-name
  Path:         /path/to/vm-name
  UUID:         <UUID>
  Guest name:   Red Hat Enterprise Linux 7 (64-bit)
  Memory:       4096MB
  CPU:          2 vCPU(s)
  Power state:  poweredOn
  Boot time:    2022-02-01 12:16:27.854201 +0000 UTC
  IP address:   
  Host:         esxi1.example.intranet
$
$
$ govc vm.info -json=true vm-name | grep esxi1
$
$ # no output from grep
```

**Comment by embano1** [comment]
Thx for raising this question @NlVlN! 

The reason for this behavior is that you're comparing the optimized human-readable output from `govc <type>.info' commands with the machine-readable formatting which use different code paths internally to print the result.

The actual `VirtualMachine` object retrieved from vCenter does not contain the hostname (if available). And so `-json` just dumps the actual data as retrieved from the API. Using the (default) table output adds special fields, e.g. `Host:` to the output (but omits other fields) and performs look ups to convert the vCenter `moRef` to human-readable names if available.

```console
# print moRef
govc vm.info -json $vm | jq '.VirtualMachines[0].Summary.Runtime.Host'
{
  "Type": "HostSystem",
  "Value": "host-15"
}

# print host
govc host.info -json $host | jq '.HostSystems[0].Summary.Config.Name'
"myhost-01"
```

In your case you would have to perform separate queries to perform the mapping when using `-json` output or use the `govmomi` library to create the desired behavior.
