### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kiransharma2016** [vmware/govmomi#2735]
**Describe the bug**
I was tryin to create vm ( vm.clone), and it failed with a message " no cluster recommendations'. I have created vm this way for long. I tried to even manually to run govc vm.clone -templatevm targetvm, this also failed with same error message.  This is really important for us to get resolved. 

**To Reproduce**

1. 
1.
1.

**Expected behavior**

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by embano1** [comment]
Please provide all the information as per the issue template to help us narrow down the problem. Thank you.
