### ISSUE TITLE
[QUESTION] Does govmomi have support for custom attributes

### ISSUE THREAD

**Issue by srm09** [vmware/govmomi#2743]
I am a CAPV user and was wondering if `govmomi` supports creation of custom attribute keys and setting the custom attribute key-value pairs on VM creation?

**Comment by embano1** [comment]
Yes, that API is supported. For an example which uses this API see [`govc`](https://github.com/vmware/govmomi/blob/master/govc/fields/set.go)

**Comment by srm09** [comment]
Thanks! :)
