### ISSUE TITLE
[FR] - Publish Arm container image for vcsim

### ISSUE THREAD

**Issue by lamw** [vmware/govmomi#2754]
Although there's an Arm deliverable for govc/vcsim, it looks like the Docker image is only available for x86. It would also be great to have this published for Arm since this is currently not possible when using Apple M1

```
docker run --rm -it -p 0.0.0.0:8989:8989 vmware/vcsim:latest                                                         ✔  1m 30s  04:46:26 PM
Unable to find image 'vmware/vcsim:latest' locally
latest: Pulling from vmware/vcsim
692244526cab: Pull complete
d237303da7f0: Pull complete
cd5d2446e8f9: Pull complete
a25e73d99e15: Pull complete
18b65356b3a6: Pull complete
Digest: sha256:3117a5c8e8e230e0d69662aa3fe0139c1d7f9f97d605e4c34232697198d70fce
Status: Downloaded newer image for vmware/vcsim:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by adamfowleruk** [comment]
@billglover and myself encountered this in the past week as an issue when creating a new terraform provider using govmomi and wanting to test against a local vcsim instance. Given VMware pre-sales are being issued M1 MacBook Pros as standard since January 2022, this is an increasing problem.

**Comment by embano1** [comment]
Note: We publish the corresponding Dockerfiles so until this issue is resolved you can always build the image for yourself.

**Comment by lapawa** [comment]
Can we reopen this issue? 
I'm also unable to run the vmware/vcsim image on my recent Mac Book Pro.

**Comment by embano1** [comment]
Since this has been implemented using `docker` and `goreleaser` in this repo, it is now possible to configure `goreleaser` to produce Docker images for different/multiple architectures: https://goreleaser.com/customization/docker/#customization

Alternatively, `ko` can be used but that requires a lot more changes to the way Docker is currently used in this repo.
