### ISSUE TITLE
Support a new prefix for commit message, when PR involves E2E changes (govc+ simulator+doc)

### ISSUE THREAD

**Issue by pradeep288** [vmware/govmomi#2756]
**Is your feature request related to a problem? Please describe.**
Currently, we are supporting the following prefixes for the commit messages:
govc, vcsim, chore, fix, docs, examples. but we don't have any prefix when the PR involves E2E changes. We need to add a new commit message prefix.

Reference
https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md

**Comment by embano1** [comment]
Well, we also don't have a prefix for `api` related changes. For E2E it sounds like it would fall under `chore:` or no prefix at all (as we do with other commits)?

Which prefix would you want to see here?

**Comment by pradeep288** [comment]
I wanted a prefix for PR like this https://github.com/vmware/govmomi/issues/2716 . It has changes for govc+govmomi+doc+simulator. Am ok with `chore`, but I felt the description was not intuitive
`chore: Use for repository-related activities`.

whats your opinion with this prefix `e2e: Use for changes to govc+simulator+govmomi+govc-tests+go-test+ docs`

**Comment by embano1** [comment]
IMHO `E2E` does not warrant a separate prefix because it usually goes with a feature or fix. For simple changes like adding tests to increase coverage I'm actually ok not using a prefix at all as I don't see it a notable change/feature worth highlighting in the CHANGELOG or release notes.

**Comment by embano1** [comment]
As per our discussion we'll add a new `api: ` prefix for API-related changes. In case of multiple changes in a PR, e.g. `api: Add XYZ bindings` and `vcsim: Add XYZ to simulator` these can be put into distinct commits so they're featured in both sections of the `CHANGELOG` and release notes if needed.
