### ISSUE TITLE
Cannot "go get" behind a proxy

### ISSUE THREAD

**Issue by Boran** [vmware/govmomi#276]
HTTP_PROXY=http://proxy.example.ch:80
go get github.com/vmware/govmomi/govc
```
# github.com/vmware/govmomi/vim25/soap
src/go/src/github.com/vmware/govmomi/vim25/soap/client.go:68: unknown net.Dialer field 'KeepAlive' in struct literal
src/go/src/github.com/vmware/govmomi/vim25/soap/client.go:74: c.t.TLSHandshakeTimeout undefined (type *http.Transport has no field or method TLSHandshakeTimeout)
```

I don't quite understand NewClient() in src/go/src/github.com/vmware/govmomi/vim25/soap/client.go, http and https seems to be mixed. Commenting out the two lines mentioned allowed me to proceed.

**Comment by pietern** [comment]
The problem is that you're on a version of Go older than 1.3. The `KeepAlive` field on the `net.Dialer` struct was added in that version. Please try to upgrade to version 1.3 or newer and try again. Otherwise, see the **releases** page here on GitHub to find prebuilt binaries of govc.

Good luck!
