### ISSUE TITLE
Missing `find PCIdevices` in finder.go

### ISSUE THREAD

**Issue by geetikabatra** [vmware/govmomi#2769]
**Is your feature request related to a problem? Please describe.**
I am trying to access PCI devices(specifically GPU), something similar to [finder.Network](https://github.com/vmware/govmomi/blob/master/find/finder.go#L804).
I also see that in [object/virtual_device_list.go](https://github.com/vmware/govmomi/blob/master/object/virtual_device_list.go#L35-L38), only 4 kinds of devices are mentioned i.e `cdrom`, `disk`, `ethernet`, `floppy` . There is no such thing as `GPU` device or `NIC`. Need a way to find a GPU device?

**Describe the solution you'd like**
A method that helps easier access to PCI devices such as GPU and NIC's.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by dougm** [comment]
Finder only applies to inventory objects, but we have the VirtualDeviceList type for finding VM devices.
In the case of finding a specific VM NIC, you can use the Finder to get the network object itself: https://github.com/vmware/govmomi/blob/a41644562f5977dc76f2a385ab77432bfc21c993/object/example_test.go#L501-L502

Then `EthernetCardBackingInfo` to get a device backing for the network: https://github.com/vmware/govmomi/blob/a41644562f5977dc76f2a385ab77432bfc21c993/object/example_test.go#L507-L509

Then `VirtualDeviceList.SelectByBackingInfo` to get the NIC device: https://github.com/vmware/govmomi/blob/a41644562f5977dc76f2a385ab77432bfc21c993/object/example_test.go#L530

As for GPU, see the example added in #2772
