### ISSUE TITLE
add and modify GPU card and GPU profile, for VMs

### ISSUE THREAD

**Issue by danywayGit** [vmware/govmomi#2773]
**Is your feature request related to a problem? Please describe.**
I have not found any wait to manage PCI Passtrough cards, for NVidia shared PCI device, for VMs.
It's look like it should be possible with vm.change -e device.backing.vgpu=grid_m10-2b or -f passthrough-13000=grid.json , but without success for me.

**Describe the solution you'd like**
I would like a feature, to be able to add a GPU card in the hardware of a VM, and be able to define a GPU profile.
maybe in vm.change or in device.add or in device.pci.add

**Describe alternatives you've considered**
I have been able to do it by Powershell or manual in the VSphere web client.

**Additional context**
I have been able to remove an NVidia card with the command :
device.pci.remove vm $vm pcipassthrough-*

but device.pci.add vm $vm pcipassthrough-13000, give me the error :
passthrough-13000 is not found in allowed pci passthrough device list

**Comment by dougm** [comment]
You need to use the device address rather than the name, have you tried that?
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#devicepciadd

**Comment by danywayGit** [comment]
Hello dougm, thank you for you fast answer. Yes I have try with the address, like referenced in the help of the command. I'll retry on monday, and i'll let you know. Do you see another way of adding a grid card with govc, or in python?

**Comment by danywayGit** [comment]
Here is what I get with I try to do device.pci.add :
/soft/govc/govc device.pci.add -vm TestVM01 0000:da:00.0
/soft/govc/govc: 0000:da:00.0 is not found in allowed PCI passthrough device list

I have checked in the VCenter, on witch ESX is this VM, than I have checked in the Configuration/Hardware/Graphic, I have picked one of the GRID card, to get the Address.

**Comment by danywayGit** [comment]
I have checked in the VCenter, when I had a grid card manually through the Vsphere web interface, and I see an **action modified**, for  config.hardware.device, with the previous list of hardware ID, + the new hardware ID (13000)
and another **action added** : with some details about the grid card :
Name : pcipasstrough-13000
Type: VirtualPCIPassthrough
Key: 13000
DeviceInfo : 
  Label : PCI device 0
  Summary : NVIDIA GRID cGPU grid_m10_2b
 Backing : 
 Vgpu : grid_m10_2b
 MigrateSupported : null

**Comment by dougm** [comment]
> I have been able to do it by Powershell

Can you share a doc link and/or example of this?

> Vgpu : grid_m10_2b

Looks like the `device.pci` does not support virtual GPU currently, only physical devices.

**Comment by danywayGit** [comment]
Hello,

Here is the powershell I have tested.
[AddGrid.ps1.log](https://github.com/vmware/govmomi/files/8238003/AddGrid.ps1.log)

I have not integrate in this one, the Reverse All Memory option.

Ref : 
http://www.virtu-al.net/2015/10/26/adding-a-vgpu-for-a-vsphere-6-0-vm-via-powercli/

And I have done a code in Python to be able to do the same, with the option Reserve All Memory, this time.
[add_grid_to_vm.py.log](https://github.com/vmware/govmomi/files/8238005/add_grid_to_vm.py.log)

I have started from : (https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py)

If this something similar can be integrated in GOVC, it would be great.

Have a nice day.

**Comment by gorantornqvist-sr** [comment]
Has anyone managed to do this or found a workaround using linux tools?

We use packer/govc to automate builds/deployment of all templates and since this cant be done we have to manually add the vGPU PCI device / mark-as-template before we can deploy any GPU-VMs ...
