### ISSUE TITLE
[FR] Support retry mechanism in `nfc.Lease#Upload`

### ISSUE THREAD

**Issue by HakanSunay** [vmware/govmomi#2778]
**Is your feature request related to a problem? Please describe.**

I would like to programmatically retry uploads through `nfc.Lease#Upload`. Intermittent network glitches break this call when we are dealing with big files. One such example is trying to upload the contents of a vCenter Server Appliance. Below, you can find the contents of the `.ova` of latest vCenter Server release:

```
-rw-r--r--  1 hhalil mts 201K Jan 19 19:29 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10.ovf
-rw-r--r--  1 hhalil mts  856 Jan 19 19:29 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10.mf
-rw-r--r--  1 hhalil mts 100K Jan 19 19:29 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10.cert
-rw-r--r--  1 hhalil mts  15K Jan 19 19:29 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10-file1.json
-rw-r--r--  1 hhalil mts  87M Jan 19 19:29 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10-file2.rpm
-rw-r--r--  1 hhalil mts 781M Jan 19 19:29 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10-disk1.vmdk
-rw-r--r--  1 hhalil mts 6.6G Jan 19 19:31 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10-disk2.vmdk
-rw-r--r--  1 hhalil mts  71K Jan 19 19:31 VMware-vCenter-Server-Appliance-7.0.3.00300-19234570_OVF10-disk3.vmdk
```
I am also open to different suggestions for handling such uploads (6.6G) using multi-part delivery or any other chunk-based method, as long as we have the retry logic embedded.

**Describe the solution you'd like**

Initially, I would like `nfc.Lease#Upload` to be extended to allow upload retries in case of failures. Naturally, to maintain backward compatibility this could be done with a new method `nfc.Lease#UploadRetry` or any other existing retry-related naming convention could be applied. A nice to have would be to achieve this in the fastest way possible with a multi-part upload.

**Describe alternatives you've considered**

An alternative in my case would be to wrap my calls to `nfc.Lease#Upload` to apply some sort of retries.

**Additional context**

Intermittent network issues with big files result in the following error:
```
Post "https://<redacted_ip>/nfc/<redacted_uuid>/disk-1.vmdk": use of closed network connection
```

**Comment by embano1** [comment]
Notes from an earlier conversation between me and @HakanSunay:

- Retries are possible wrapping the `soap.RoundTripper` (helper methods exist)
- Not all HTTP status code should be retried
- Resuming from a failed upload requires server-side support, e.g. multipart
