### ISSUE TITLE
Add support to update the name for a license

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/govmomi#2788]
**Is your feature request related to a problem? Please describe.**

Currently, govmomi only supports the ability to update license `labels` with the `UpdateLicenseLabel` function. However, these labels are not exposed to the user in the vSphere Client. Instead, it is the `name` attribute, as seen in `LicenseManagerLicenseInfo` that is used for the license name.

```go
type LicenseManagerLicenseInfo struct {
	DynamicData

	LicenseKey string        `xml:"licenseKey"`
	EditionKey string        `xml:"editionKey"`
	Name       string        `xml:"name"`
	Total      int32         `xml:"total"`
	Used       int32         `xml:"used,omitempty"`
	CostUnit   string        `xml:"costUnit"`
	Properties []KeyAnyValue `xml:"properties,omitempty"`
	Labels     []KeyValue    `xml:"labels,omitempty"`
}
```

Or see [vim.LicenseManager.LicenseInfo.html](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.LicenseManager.LicenseInfo.html)

**Describe the solution you'd like**

Provide a method to update the name attached to a license.

e.g. An `UpdateLicenseLabel` function and the required types.

**Describe alternatives you've considered**

Nine at this time.

**Additional context**

Reference: https://github.com/hashicorp/terraform-provider-vsphere/issues/1491

**Comment by dougm** [comment]
You can use this API to update the license display name:

https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.LicenseAssignmentManager.html#updateAssignedLicense

https://github.com/vmware/govmomi/blob/master/license/assignment_manager.go#L56

**Comment by tenthirtyam** [comment]
Awesome, thanks for the pointer! I'll get this implemented downstream in the provider using this - thank you!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
