### ISSUE TITLE
[BUG] govc guest.start /tmp/script.sh failing if script has "sudo" commands on SUSE sles15

### ISSUE THREAD

**Issue by koteswara-kelam** [vmware/govmomi#2804]
**Describe the bug**
I want to assign static IP to my Suse VM with sles 15 OS. I am running a script which is having few commands to do this.
When I execute this script using "govc guest.start", commands with "sudo" in the script are failing.

This is only happening when guest os in vm is sles 15. It worked fine with CentOS as guest OS

#govc guest.start -l user:'Password -vm="seed-sles15" -dc="dc1" /usr/bin/sudo /usr/bin/bash /tmp/ip-configuration.sh

**To Reproduce**

1. Reproducible only on sles15 guest OS vms

**Expected behavior**
It should work sles15 guest os also.

**Affected version**
I tried latest version 
govc 0.27.4

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by embano1** [comment]
Is there any error message when it fails?

**Comment by koteswara-kelam** [comment]
$ govc guest.ps -l user:'Password' -vm="sles15" -dc="dc1" -p 14456 -json -X
{
  "ProcessInfo": [
    {
      "Name": "bash",
      "Pid": 14456,
      "Owner": "user",
      "CmdLine": "\"/usr/bin/bash\" /tmp/ip-configuration2.sh 15.213.212.40 15.213.208.1 255.255.248.0",
      "StartTime": "2022-03-31T08:26:08Z",
      "EndTime": "2022-03-31T08:26:09Z",
      "ExitCode": 0
    }
  ]
}

On sles15 VM:
------------------
#cat /tmp/ip-configuration2.sh
echo "$1: $2: $3" > /tmp/ifcfg-eth1
/usr/bin/sudo /usr/bin/cp /tmp/ifcfg-eth1 /etc/sysconfig/network/ifcfg-eth1

Here first command "echo" works but "sudo cp" is failing

**Comment by koteswara-kelam** [comment]
If I try guest.run, following error I get:
sudo: unable to execute /usr/bin/cp: Permission denied
but "user" has sudo privileges.

**Comment by koteswara-kelam** [comment]
if I login into sles15 vm directly and run then it works fine. Only through govc it is failing.

**Comment by koteswara-kelam** [comment]
> Is there any error message when it fails?

Can you suggest what could be the issue here?

**Comment by koteswara-kelam** [comment]
@embano1 Do you have any idea about this? I tried with powershell  command Invoke-VMScript but same issue:
sudo: unable to execute /usr/bin/cp: Permission denied

**Comment by embano1** [comment]
Hm, that then seems to be OS specific, or at least not a govmomi issue since you were able to reproduce with PCLI (which is great btw 🙏)

**Comment by vemireddy-vaibhav** [comment]
@embano1 Isn't issue with `govc`. I see that PCLI rightly reports that it's unable to execute `sudo` commands. However `govc`, simply reports `exit code = 0` which isn't the right(?)

Not only does it fail to execute `sudo` commands, but also reports in-correct exit code?

**Comment by vemireddy-vaibhav** [comment]
If we were to execute any command with `sudo`, is it necessary to use the root user or any user in `sudoers` group should work?

**Comment by koteswara-kelam** [comment]
setting selinux to permissive mode solved this issue. Thanks.
