### ISSUE TITLE
[BUG] VirtualDisk's capacityInBytes not works for vm.AddDevice

### ISSUE THREAD

**Issue by beorereleverion** [vmware/govmomi#2805]
**Describe the bug**
VirtualDisk's capacityInKB attribute is deprecated in vSphere API 5.5 but without this vm.AddDevice doesn't work

Disk didn't created.

**To Reproduce**
create new disk for vm with funciton like in govc(https://github.com/vmware/govmomi/blob/master/govc/vm/disk/create.go#L166)
but change string 166	disk.CapacityInBytes = int64(cmd.Bytes)

**Expected behavior**
disk created and added to VM

**Affected version**
	github.com/vmware/govmomi v0.27.1

**Comment by beorereleverion** [comment]
https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.device.VirtualDisk.html

**Comment by HakanSunay** [comment]
>  create new disk for vm with funciton like in govc(https://github.com/vmware/govmomi/blob/master/govc/vm/disk/create.go#L166)

Let's clarify one thing - did you use:
```
$ govc vm.disk.create -vm $name -name $name/disk1 -size 10G
```

or you've written code similar to `govc/vm.disk/create.go` and observed that `vm.AddDevice` doesn't work if `capacityInBytes` is not specified?

**Comment by beorereleverion** [comment]
I wrote a code where capacityInBytes is used. That doesn't work.
Then I wrote the code where capacityInKB is used. That's how it worked.
But capacityInKB deprecated - [vmware-doc](https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.device.VirtualDisk.html)
