### ISSUE TITLE
vSAN simulator: VsanPerformanceManager Testability

### ISSUE THREAD

**Issue by schmikei** [vmware/govmomi#2813]
**Is your feature request related to a problem? Please describe.**

- I'm currently trying to write test cases on pieces of code that utilize the [VsanPerformanceManager API](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/b525fb12-61bb-4ede-b9e3-c4a1f8171510/99ba073a-60e9-4933-8690-149860ce8754/doc/vim.cluster.VsanPerformanceManager.html)

- Including the registry in the simulator ends up yielding this error on `VsanPerfQueryPerf(ctx, ref, qs)` => `ServerFaultCode: managed object not found: VsanPerformanceManager:vsan-performance-manager` 

**Describe the solution you'd like**
- I'd like to see this reference included in the simulator or know the preferred way of writing tests around this API.

**Describe alternatives you've considered**
Tried more documentation on if there was an alternative but couldn't find the right direction.

**Additional context**
Test case I was initially using
```go
import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/vmware/govmomi/find"
	"github.com/vmware/govmomi/simulator"
	"github.com/vmware/govmomi/vim25"
	"github.com/vmware/govmomi/vsan"
	_ "github.com/vmware/govmomi/vsan/simulator"
	"github.com/vmware/govmomi/vsan/types"
)

func TestVsanPerformanceManagerInSimulator(t *testing.T) {
	simulator.Test(func(ctx context.Context, c *vim25.Client) {
		vsanClient, err := vsan.NewClient(ctx, c)
		require.NoError(t, err)
		finder := find.NewFinder(c)
		cluster, err := finder.DefaultClusterComputeResource(ctx)
		require.NoError(t, err)

		querySpec := []types.VsanPerfQuerySpec{
			{
				EntityRefId: "virtual-machine:*",
			},
		}
		clusterRef := cluster.Reference()
		csvs, err := vsanClient.VsanPerfQueryPerf(ctx, &clusterRef, querySpec)
		require.NoError(t, err)
		require.NotEmpty(t, csvs)
	})
}
```

**Comment by dougm** [comment]
Hi @schmikei , I hadn't used this API before, but have a WIP here: https://github.com/vmware/govmomi/compare/master...dougm:issue-2813

Any interest in picking this up and adding what you need for your use case(s)?  Also happy to pair/zoom and walk through it if you're interested.
