### ISSUE TITLE
How to list vms by a host?

### ISSUE THREAD

**Issue by EricYT** [vmware/govmomi#283]
I want to list virtual machines in a host.

**Comment by pietern** [comment]
You'll have to find the [HostSystem](http://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/vim.HostSystem.html) for the host you're interested in first (you can use the `find` package to find a compute resource, then the property collector to get the host system(s) that are (part of) the compute resource). Then you can use the property collector to get the list of VMs for that host.

Also see the [datastore example](https://github.com/vmware/govmomi/blob/master/examples/datastores/main.go) for some hints on how to use these packages.
