### ISSUE TITLE
can you add in export.ovf advanced options (extraconfig)

### ISSUE THREAD

**Issue by danywayGit** [vmware/govmomi#2839]
**Is your feature request related to a problem? Please describe.**
There is no option to export advanced options

**Describe the solution you'd like**
I would like a true/false option, like in the VSphere web client, to be able to export a VM with advanced options.

**Describe alternatives you've considered**
all advanced options, or for a selection of options, with [key, value]
There is an existing possibility for a VM already imported in a VCenter, with vm.change -e, but I would like to have it at the export (in the ovf file), this is better compare to add those options for each VM after having them imported in the VCenter.
Maybe it is possible to add an option to modify the exported ovf file. This is what I have done in python.

**Additional context**
![Export-vm-ovf-advanced](https://user-images.githubusercontent.com/35162922/167261545-984175cf-69ad-4db4-a6ee-547dd7a5347c.jpg)

**Comment by embano1** [comment]
@danywayGit this is about `govc` correct?
