### ISSUE TITLE
govc can't upload file to datastore if datacenter is in a folder

### ISSUE THREAD

**Issue by alateas** [vmware/govmomi#285]
I have datacenter "mydc01" inside folder "myfolder" and datastrore "myds01" inside this datacenter
And I have  datacenter "mydc02" at the root of vcenter and datastrore "myds02" inside this datacenter.

When I use command
`govc datastore.upload  --ds=myds02 --dc=mydc02 /path/to/file.iso file.iso`
all looks good `Uploading... OK` and the file appears in datastore

but when
`govc datastore.upload  --ds=myds01 --dc=myfolder/mydc01 /path/to/file.iso file.iso`
we get: `Uploading... Error: 404 Not Found`

obviously wrong datastore:
`govc datastore.upload  --ds=myds01wrong --dc=myfolder/mydc01 /path/to/file.iso file.iso`
`Error: datastore 'myds01wrong' not found`

obviously wrong datacenter:
`govc datastore.upload  --ds=myds01 --dc=myfolder/mydc01wrong /path/to/file.iso file.iso`
`Error: datacenter 'myfolder/mydc01wrong' not found`

So, seems like it is works incorrectly when datacenter is inside a folder.

**Comment by danielcb** [comment]
This seems to be still an issue? I can't access any datacenters in folders. Can anyone confirm this? I just want to rule out misuse as a cause here :)

**Comment by dougm** [comment]
Likely yes, similar issue to #507 where we don't recurse into sub folders.  Planning to fix both in the next release (this week or next).

**Comment by dannc** [comment]
On the Datacenters issue at least, I added pull request #593 to at least be able to have the finder be able to recurse folders to find them.

Still, an issue for me remains in that uploads to a datastore under such a datacenter fail because the datastore URL only specs the dcPath query parameter as the datacenter name.  For me that results in a 404 because I have my datacenter in a folder.

**Comment by danielcb** [comment]
Anything new/planned regarding the folder/recurse issues?

**Comment by dougm** [comment]
#594 has been fixed - so datastore upload/download works if Datacenter is in a folder.  #593 is still open, but that is a separate issue.

**Comment by D3nn** [comment]
Thanks for the fix @dougm.  I'll check out the datastore upload/download when I'm back in the office so I can remove the (ugly) hack I had to do in the vmware-vsphere docker-machine drivers to work around this.
