### ISSUE TITLE
Add API for missing Tanzu namespace management CRUD functionality

### ISSUE THREAD

**Issue by adamfowleruk** [vmware/govmomi#2860]
**Is your feature request related to a problem? Please describe.**
Currently the existing namespace Enable call is missing vSphere networking options as well as the WorkloadNTPServers option. This means the same set up you can create manually is not possible via govmomi API calls today.

In addition there are some other API calls required for a Terraform provider I'm creating that are missing in govmomi:-
- GET https://{api_host}/api/vcenter/namespace-management/clusters/{cluster} - required by resource_cluster readCluster 
  - ListClusters is insufficient due to how terraform determines whether a resource needs updating/deleting/creating
  - Note that Create in terraform is followed by a read.
- PUT https://{api_host}/api/vcenter/namespace-management/clusters/{cluster} - required by resource_cluster updateCluster
  - Used to replace a whole config without a disable/enable loop

Other ancillary calls are likely missing too (E.g. PATCH to add a workload network), but the above are the big ticket items preventing Infrastructure as Code and GitOps approaches being used.

**Describe the solution you'd like**
These API calls added to govmomi/vapi/namespace.go so I can complete my provider.

**Describe alternatives you've considered**
Rolling my own client library, but it seemed excessive, and wouldn't help the broader community.

**Additional context**
I'm happy to implement the feature myself (I work in MAPBU in VMware as a Platform Architect), so this is really just for tracking, unless someone wants to add these pieces themselves in the interim, if its quicker?

**Comment by embano1** [comment]
> I'm happy to implement the feature myself

Go for it, much appreciated!
