### ISSUE TITLE
[BUG] Link to CONTRIBUTION guidelines in Pull Request template is broken

### ISSUE THREAD

**Issue by atc0005** [vmware/govmomi#2884]
**Describe the bug**

**To Reproduce**

1. Open a new pull request
1. Scroll to the `Checklist` section
1. Opt to Preview the GH issue as it currently is
1. Attempt to follow the link to the CONTRIBUTION guidelines

**Expected behavior**

Working link

**Affected version**

https://github.com/vmware/govmomi/blob/06eb50d897338eea7451a2c0ee2ff560f20159dd/.github/PULL_REQUEST_TEMPLATE.md

**Screenshots/Debug Output**

N/A

**Additional context**

N/A

**Comment by embano1** [comment]
Just tried to follow your steps, but can't find a "checklist" section in the issue template?

**Comment by atc0005** [comment]
> @embano1: Did you mean the PR template by chance?

You're right, sorry about that. I think I filled this out while preparing #2885 and wasn't paying as much attention as I should have. I've updated the OP to reflect the correction.

Note: When viewing the PR template directly the relative link works, but once the PR template is used to produce a PR the link no longer works.
