### ISSUE TITLE
vcsim: support host shutdown, standby (and power on?)

### ISSUE THREAD

**Issue by rcw5** [vmware/govmomi#2902]
**Is your feature request related to a problem? Please describe.**

As a continuation of https://github.com/vmware/govmomi/issues/2899 I'd like to extend the simulator to support shutting down, putting into standby and potentially powering on a host.

I'm happy to submit a PR for this, but the implementation is less obvious, so I'd like to get your thoughts on a solution before starting work.

**Describe the solution you'd like**

Shutdown is straightforward: the simulator can support the `ShutdownHost_Task` which would set the `HostSystemPowerState` to `HostSystemPowerStatePoweredOff` if already in maintenance mode or if the `Force` flag is provided. This can be tested via a BATS test for `govc host.shutdown`.

Standby also seems relatively simple: implement `PowerDownHostToStandBy_Task` which would set the PowerState to `HostSystemPowerStateStandBy` (there doesn't seem to be a way to standby a host in `govc` so no BATS test for this).

I can't find a way to power the host back on again though - I guess in the real world someone presses a button on the front of the machine, but in the simulator it might be desirable to power on a host after setting it to poweredOff/standBy. Is there a way for the simulator to support this operation? Any guidance on a solution is appreciated

**Comment by dougm** [comment]
Yes, pressing a button, IPMI or other iLO method to power on, but nothing in the vSphere API that I know of.

I haven't used the host StandBy methods before, but see there is [PowerUpHostFromStandBy_Task](https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere-ws/docs/ReferenceGuide/vim.HostSystem.html#exitStandbyMode)

I think it would be ok to in vcsim if that method sets power state to `HostSystemPowerStatePoweredOn` regardless of current state being `StandBy` or `PoweredOff`. What do you think?
