### ISSUE TITLE
[BUG] SessionManager->UserSession does not return error when NotAuthenticated error is returned from vCenter

### ISSUE THREAD

**Issue by divyenpatel** [vmware/govmomi#2922]
**Describe the bug**
We are using Session Manager -> UserSession function to retrieve user session in the vSphere CSI Driver.
Here is the code - https://github.com/vmware/govmomi/blob/v0.29.0/session/manager.go#L182-L196

```golang
// UserSession retrieves and returns the SessionManager's CurrentSession field.
// Nil is returned if the session is not authenticated.
func (sm *Manager) UserSession(ctx context.Context) (*types.UserSession, error) {
	var mgr mo.SessionManager

	pc := property.DefaultCollector(sm.client)
	err := pc.RetrieveOne(ctx, sm.Reference(), []string{"currentSession"}, &mgr)
	if err != nil {
		// It's OK if we can't retrieve properties because we're not authenticated
		if f, ok := err.(types.HasFault); ok {
			switch f.Fault().(type) {
			case *types.NotAuthenticated:
				return nil, nil
			}
		}

		return nil, err
	}

	return mgr.CurrentSession, nil
}

```

when we observe the current session using which we are attempting to confirm is session is alive, if we get NotAuthenticated session error, we return back nil session with nil error.

This requires explicit handling on the client (for our case vSphere CSI Driver) to check if a nil session returned or valid session is return as we have not received any error.

Can't this be fixed at govmomi to return the error back to caller.

**Expected behavior**

If the session is unauthenticated, we should return a nil session with an error.

**Affected version**
all version of govmomi

**Additional context**
We need special handling in the driver - https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1859

**Comment by dougm** [comment]
We can't change the behavior of this function as it will break other applications that use it and expect as documented:.
> // Nil is returned if the session is not authenticated.

The body of the method is small and uses public methods, you can just copy into your own helper and change the behavior there.
