### ISSUE TITLE
[BUG] Cloned VM is not stored in datastore, only on local disk

### ISSUE THREAD

**Issue by EmmaWrong** [vmware/govmomi#2925]
**Describe the bug**
While cloning a vm we provide a datastore. The VM is cloned, but the datastore is then a local disk of an esx host.
This worked in the past without problems. After a vcenter update, we encounter this behaviour.

**To Reproduce**
govc vm.clone -debug=true -vm=/Templates/OCP-4.10.3.ova -on=false -cluster=de-prod-003 -ds=/datastore/NFS/productionds -folder=/DC/vm/Appliance/cg2/p1 -c=10 -m=65536 -net dvp_de_vlan1234 test

**Expected behavior**
Store the VM in datastore

**Affected version**
govc 0.29.0
FullName:     VMware vCenter Server 6.7.0 build-19832280
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        19832280
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.3
Product ID:   vpx

**Comment by dougm** [comment]
I think the issue is `-cluster=de-prod-003`, in which case the `-ds` argument is ignored as cluster is used for datastore placement.  If you omit the `-cluster` flag (or replace with `-pool=de-prod-003/Resources`), the vm should be placed in the `-ds` you specify.

**Comment by EmmaWrong** [comment]
But the fact is, that it worked before the update. We now have some news, as this is a nutanix cluster, only nutanix nodes are affeced and only two of them. With a non nutanix cluster the problem does not occur. So it seems to be more a vmware problem, than a tool problem. So from my side we can close the ticket
