### ISSUE TITLE
How to set the vCenter's self-signed cert with govc 

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#2926]
I have the vCenter's public cert in PEM format.  With the govmomi APIs. I can set the Transport before Login into vCenter as follows

var transport *http.Transport
var u *url.URL
..."transport" object is created using the vCenter's self-signed (or even well-known) cert
soapClient = soap.NewClient(url,  false) 
soapClient.Transport = transport
vimClient, err := vim25.NewClient(ctx, soapClient)
	if err != nil {
		return nil, err
	}
	client := &govmomi.Client{
		Client:         vimClient,
		SessionManager: session.NewManager(vimClient),
	}
The intent is not use to an insecure/untrusted connection.  The above code ensures that the server is trusted using the cert (set in the http.Transport) or the connection fails, which is correct. 

With govc, I need to provide the certificate (GOVC_CERTIFICATE) as well as GOVC_PRIVATE_KEY, but I only have the vCenter's PEM cert and the login credentials. How do I achieve the same effect as above, given that I do not have the "private key"?

**Comment by dougm** [comment]
`GOVC_CERTIFICATE` and `GOVC_PRIVATE_KEY` are for client authentication. `GOVC_TLS_CA_CERTS` is for adding trusted server CAs: https://github.com/vmware/govmomi/blob/master/govc/README.md#usage

**Comment by kayshavd** [comment]
Thanks Doug. One can always count on you for prompt response. 
The self signed certificate I was using was incorrect and therefore failed to load with the "tls-ca-certs" flag - simple human error.  A simple test utility to validate the cert got me going.
And I completely overlooked the fact that GOVC_CERTIFICATE is for client auth. 
The -tls-ca-certs=/path/to/your/certfile  works correctly and govc is able to validate the cert.
