### ISSUE TITLE
golint target is missing from Makefile

### ISSUE THREAD

**Issue by bruceadowns** [vmware/govmomi#294]
As a matter of completeness, a golint target should be added to the base Makefile.

    golint:
        @echo checking go lint...
        @golint <package list>

Where the package list should (eventually) include every package, dynamically generated. However, to begin, I suggest having a static list and opportunistically add to it.

Here's an example of some of the complaints after some trivlal filtering.

    $ find . -name \*.go -exec golint {} \; | grep -v 'should have comment' | grep -v 'vim25'
    ./client.go:17:1: package comment should be of the form "Package govmomi ..."
    ./client.go:70:6: exported type Client should have comment or be unexported
    ./govc/cli/command.go:106:3: should replace n += 1 with n++
    ./govc/flags/output.go:189:55: exported method ProgressLogger returns unexported type *flags.progressLogger, which can be annoying to use
    ./govc/flags/version.go:26:30: exported func ParseVersion returns unexported type flags.version, which can be annoying to use
    ./govc/host/add.go:158:22: error strings should not end with punctuation
    ./govc/host/autostart/autostart.go:31:6: type name will be used as autostart.AutostartFlag by other packages, and that stutters; consider calling this Flag
    ./govc/host/esxcli/guest_info.go:85:21: func IpAddress should be IPAddress
    ./govc/vm/disk/create.go:92:9: if block ends with a return statement, so drop this else and outdent its block
    ./govc/vm/guest/guest.go:31:6: type name will be used as guest.GuestFlag by other packages, and that stutters; consider calling this Flag
    ./govc/vm/info.go:132:2: struct field VmInfos should be VMInfos
    ./govc/vm/vnc.go:384:12: should omit 2nd value from range; this loop is equivalent to `for port = range ...`
    ./object/customization_spec_manager.go:140:36: func CustomizationSpecItemToXml should be CustomizationSpecItemToXML
    ./object/customization_spec_manager.go:154:36: func XmlToCustomizationSpecItem should be XMLToCustomizationSpecItem
    ./object/datacenter.go:28:2: struct field VmFolder should be VMFolder
    ./object/host_network_system.go:204:28: func UpdateConsoleIpRouteConfig should be UpdateConsoleIPRouteConfig
    ./object/host_network_system.go:219:28: func UpdateDnsConfig should be UpdateDNSConfig
    ./object/host_network_system.go:234:28: func UpdateIpRouteConfig should be UpdateIPRouteConfig
    ./object/host_network_system.go:249:28: func UpdateIpRouteTableConfig should be UpdateIPRouteTableConfig
    ./object/http_nfc_lease.go:31:6: type HttpNfcLease should be HTTPNfcLease
    ./object/http_nfc_lease.go:35:6: func NewHttpNfcLease should be NewHTTPNfcLease
    ./object/http_nfc_lease.go:42:23: func HttpNfcLeaseAbort should be HTTPNfcLeaseAbort
    ./object/http_nfc_lease.go:57:23: func HttpNfcLeaseComplete should be HTTPNfcLeaseComplete
    ./object/http_nfc_lease.go:71:23: func HttpNfcLeaseGetManifest should be HTTPNfcLeaseGetManifest
    ./object/http_nfc_lease.go:85:23: func HttpNfcLeaseProgress should be HTTPNfcLeaseProgress
    ./object/search_index.go:58:22: func FindByDnsName should be FindByDNSName
    ./object/search_index.go:99:22: func FindByIp should be FindByIP
    ./object/search_index.go:122:22: func FindByUuid should be FindByUUID

**Comment by dougm** [comment]
In process of being addressed in PRs #411 and #416
