### ISSUE TITLE
datastore example should use updated environment variables

### ISSUE THREAD

**Issue by bruceadowns** [vmware/govmomi#295]
The datastores example is using defunct environment variables.

Here:
https://github.com/vmware/govmomi/blob/master/examples/datastores/main.go#L89
and here:
https://github.com/vmware/govmomi/blob/master/examples/datastores/main.go#L93

These:

    var urlVar = "GOVMOMI_URL"
    var insecureVar = "GOVMOMI_INSECURE"
should be updated to:

    var urlVar = "GOVC_URL"
    var insecureVar = "GOVC_INSECURE"

And as a bonus, the example should use the optional $GOVC_USERNAME / $GOVC_PASSWORD overrides in case of special characters.

**Comment by pietern** [comment]
Reason for these names being `GOVMOMI_*` is that the example has nothing to do with govc. Agree that the username/password functionality could be added here, but since the purpose of the example is to showcase the finder and property collector functionality I don't see this as critical.

Could you submit a PR for this?

**Comment by bruceadowns** [comment]
> Reason for these names being GOVMOMI_* is that the example has nothing to do with govc.

Ah, right. Makes sense.

> Agree that the username/password functionality could be added here

I believe the implementation should look very similar to what can be found in /govc/flags/client.go.

> Could you submit a PR for this?

I will work on it.

**Comment by pietern** [comment]
@bruceadowns By the way, if you mention something like "Fixes #295" in your commit message then GitHub will automatically close this once the pull request is merged :)

**Comment by bruceadowns** [comment]
@pietern Thanks for the tip and reference link! This new environment takes some getting used to.
