### ISSUE TITLE
[BUG] 404 Not Found on library.import

### ISSUE THREAD

**Issue by payagej** [vmware/govmomi#2958]
**Describe the bug**
I ran the command: `govc library.import -xml=true govc_test INTERNAL_VMWARE_ROCKY8_BASE.ovf`

I tried to import a .ovf file but when I try the command it return
`govc: POST https://[vcenter url]/rest/com/vmware/content/library/item/updatesession/file/id:?~action=add: 404 Not Found`

but when I try to reupload right after 
`/go/bin/govc: 400 Bad Request: {"type":"com.vmware.vapi.std.errors.already_exists","value":{"error_type":"ALREADY_EXISTS","messages":[{"args":["INTERNAL_VMWARE_ROCKY8_BASE","govc_test","9f0ed636-330c-42cf-8a6c-0276424720a5"],"default_message":"Operation is not supported since a library item with the name INTERNAL_VMWARE_ROCKY8_BASE exists in the library 'govc_test' (ID: 9f0ed636-330c-42cf-8a6c-0276424720a5).","id":"com.vmware.vdcs.cls-main.duplicate_item_name_unsupported_in_library"}]}}`

So I can't import my file, but when I retry it tell me that it already exist. When I'm looking into my vCenter web panel I can see the name of the file but with 0B size.

**Comment by antoine-faisandier** [comment]
Hello,
For me it was a permission problem.
https://github.com/aws/eks-anywhere/issues/3518
regards
