### ISSUE TITLE
PhysicalNicEditSpec  enabling SRIOV

### ISSUE THREAD

**Issue by spyroot** [vmware/govmomi#2966]
Hi Folks,

I'm not 100% if this is a new feature or if there are methods to pass this spec in API requests.  
I cross-check VC, and it looks like it expects the following PhysicalNicEditSpec.   If there are existing methods to do so, could you please let me know. ?

```{
    "_type": "com.vmware.vsphere.client.network.PhysicalNicEditSpec",
    "device": "vmnic5",
    "isLinkSpeedChanged": false,
    "sriovConfig": {
        "_type": "com.vmware.vim.binding.vim.host.SriovConfig",
        "sriovEnabled": true,
        "numVirtualFunction": 8,
        "id": "0000:3b:00.1"
    }
}
```

Thank you very much

**Comment by dougm** [comment]
Haven't done anything with sriov myself, but the terraform code linked in #2957 might be helpful. @sunnycarter may also have some pointers.

**Comment by spyroot** [comment]
Thank you very much, folks. Please note it actually enables sriov on pnic itself.       I traced @sunnycarter. I see she added types etc., but I couldn't find the API actually updates PNIC and enables SRIOV.   The spec I've to send is the vCenter Web client sends to VC when you enable SRIOV.    It basically PhysicalNicEditSpec.  I have the spec and can probably add first to types.
