### ISSUE TITLE
Implementation the esx hcl package provided by vSphere lifecycle manager

### ISSUE THREAD

**Issue by dominikzorgnotti** [vmware/govmomi#2972]
**Is your feature request related to a problem? Please describe.**
For all upgrade tasks, e.g. from 7U2 -> 7U3 or 7U3 -> 8, it is a mandatory tasks for all VI admins to check a given ESXi host against the vSphere compatibility guide (VCG). This includes the system itself as well as all IO devices.

This is a tedious task to do it manually for larger deployments, see the steps explained in the [documentation](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere-lifecycle-manager.doc/GUID-925A5711-F2CE-47FF-82CE-A2E100A1F8BC.html).

vSphere LifeCycleManager (vLCM) offers such an automation interface with the [esx hcl package](https://developer.vmware.com/apis/vsphere-automation/latest/esx/hcl/).

However, while the API is available from vLCM it would require a set of manual REST calls since govmomi (and govc) do not have an implementation to work with the API.

**Describe the solution you'd like**
The ideal solution would be to have these tasks available in govmomi.  
For example it would be great to have commands like this in govc (I explained the tasks in a blog, see context):

`lcm.hcldata.update`
`lcm.host.release.get`
`lcm.host.hclcheck.create`
`lcm.host.hclcheck.download`

(I am not sure what makes more sense, if the hclcheck should be submodule of a lcm-type module or a sub-task of `host`)

**Describe alternatives you've considered**
The alternative would be to use govmomi (or govc) to determine the host moref IDs and create an independent program to implement the required rest calls.

**Additional context**
I have written a [blog post](https://why-did-it.fail/blog/2022-05-how-to-query-hcl-api/) about the manual steps using the REST API.

There is also a [cluster-wide check,](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere-lifecycle-manager.doc/GUID-D6DEF92E-7518-4E39-A5DB-AFC26F3A84C6.html) especially relevant for vSAN deployments, but in this initial request I would put it out-of-scope (for now).

**Comment by dougm** [comment]
Haven't used the vLCM APIs myself, @HakanSunay may have some thoughts on this topic.
