### ISSUE TITLE
[BUG] add support for security compliance in content library item API

### ISSUE THREAD

**Issue by ericvmw** [vmware/govmomi#2980]
**Describe the bug**
Security policy support in content library (vSphere 7.0u3) introduced new API fields in the library and library item APIs, some of the APIs are not supported in govmomi content library client.

**To Reproduce**
Call the following API via content library client doesn't show security compliance and certificate info:
- library.NewManager(restClient).GetLibraryItem(...)
references: 
- https://github.com/vmware/govmomi/blob/master/vapi/library/library_item.go

**Expected behavior**
security_compliance and certificate_verification_info should show in item info if set:
https://developer.vmware.com/apis/vsphere-automation/latest/content/api/content/library/item/library_item_id/get/

trusted certificate API should be added to the API client:
https://developer.vmware.com/apis/vsphere-automation/latest/content/content/trusted_certificates/

**Affected version**
content library running on vSphere 7.0u3 and later.

**Screenshots/Debug Output**
compliance API field is not in the library item info output in govc CLI:

$ govc library.info secure-lib/trivial
Name:           trivial
  ID:           7d789e81-9064-478e-8236-7c25ac916d4a
  Path:         /secure-lib/trivial
  Description:
  Type:         ovf
  Size:         486B
  Created:      Mon Oct 31 18:22:33 2022
  Modified:     Mon Oct 31 18:22:39 2022
  Version:      1

**Additional context**

**Comment by dougm** [comment]
@ericvmw sounds like this is what @brakthehack added in #2909 , which was after the current 0.29 release tag.

**Comment by ericvmw** [comment]
> @ericvmw sounds like this is what @brakthehack added in #2909 , which was after the current 0.29 release tag.

Thanks @dougm for the info, I didn't check the latest source code. It looks the latest still misses some APIs on content library security policy: the security_compliance in library item and trust certificate API. I just updated the description of this issue, please let me know if it makes sense.

**Comment by dougm** [comment]
> Thanks @dougm for the info, I didn't check the latest source code. It looks the latest still misses some APIs on content library security policy: the security_compliance & certificate_verification_info in library item and trust certificate API. I just updated the description of this issue, please let me know if it makes sense.

Make sense, thanks @ericvmw . Let me know if I can help you with adding these.
