### ISSUE TITLE
ESX power off module

### ISSUE THREAD

**Issue by leoxucn822** [vmware/govmomi#2981]
Function Description:
if task.wait return with nil, then execute power off function. but I don't know which api module for me can refer to power off esx from vcenter, thank you in advance!

func EnterMaintenance(hostname string, ctx context.Context, finder *find.Finder, pc *property.Collector) {
	obj, _ := finder.HostSystem(ctx, hostname)
	_, err := obj.EnterMaintenanceMode(ctx, 0, false, nil)
	if err != nil {
		fmt.Printf("Error: ESX server %s set maintenance failed, %v\n", hostname, err)
	}
	taskinfo, _ := task.Wait(ctx, obj.Reference(), pc, nil)
	if taskinfo != nil {
		fmt.Println("Set ESX maintenance mode failed. pls check it manually and power off ESX!")
	}
}

**Comment by dougm** [comment]
object.HostSystem doesn't have a wrapper method for it (tho we could add one), but you can use the generated types like so: https://github.com/vmware/govmomi/blob/1f8aadb6a46ef9bc11dea86141e48e04a0aa58bf/govc/host/shutdown.go#L65-L75

**Comment by leoxucn822** [comment]
@dougm can we add the wrapper method for object.HostSystem.
anyway, let me try to test with your method

**Comment by dougm** [comment]
Sure, we can add the wrapper method to object.HostSystem, would you like to make that contribution?

Yes, you probably want `Force: false`, see [the doc](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.HostSystem.html#shutdown):
> Flag to specify whether or not the host should be shut down regardless of whether it is in maintenance mode. If true, the host is shut down, even if there are virtual machines running or other operations in progress.

**Comment by leoxucn822** [comment]
@dougm thanks for the feedback, i will tried to add the wrapper method to object.HostSystem.

**Comment by leoxucn822** [comment]
@dougm I don't know how to push my code to this project. it always refused.

**Comment by dougm** [comment]
> @dougm I don't know how to push my code to this project. it always refused.

See: https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md#contributing-to-govmomi

**Comment by leoxucn822** [comment]
@dougm it reported the following error.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
