### ISSUE TITLE
VCSim does not support QueryVirtualDiskInfo_Task

### ISSUE THREAD

**Issue by namra98** [vmware/govmomi#3000]
**Is your feature request related to a problem? Please describe.**
It is throwing error. `no vmomi type defined for 'QueryVirtualDiskInfo_Task'` when I try to query disk info.
govmomi func call: https://github.com/vmware/govmomi/blob/master/object/virtual_disk_manager_internal.go#L79

**Describe the solution you'd like**
func call: https://github.com/vmware/govmomi/blob/master/object/virtual_disk_manager_internal.go#L79
It should return disk info like it does against real vCenter.
![image](https://user-images.githubusercontent.com/29619495/204286647-6e9dbbaf-ee80-440d-9e5b-abd0d653d88a.png)

**Comment by deas** [comment]
I looked into this a bit and I am trying to fix it. Got it working to the point that I get valid responses for `govc datastore.disk.info`.

However, I feel I must be missing something. Many symbols are not exported and  the filename also hints at "internal". Also, it appears there is no method `QueryVirtualDiskInfo<something>` for `vim.VirtualDiskManager` documented [in the API docs](https://developer.vmware.com/apis/968/vsphere).

Still, clients such as the VSphere Terraform Provider appear to be using this method.

Would be great to get a little guidance. I may be able to contribute the missing bits here.

**Comment by dougm** [comment]
@deas sorry I missed this. I've many incomplete govmomi branches and stashes, just pushed one for this which I had started when #2555 was opened. Let me know if you're still interested on this topic, happy to integrate any further enhancements you may have.
