### ISSUE TITLE
PerfManager requires vmRefs to be passed while collecting historical data

### ISSUE THREAD

**Issue by praveenghuge** [vmware/govmomi#3019]
**Describe the bug**
I am trying to collect vmware historical metrics for vm for a time period similar to example mentioned in https://github.com/vmware/govmomi/blob/main/examples/perfmanager/main.go and passing start and end in PerfQuerySpec

but https://github.com/vmware/govmomi/blob/main/examples/perfmanager/main.go#L76 SampleInfoByName method requires vmRefs object to passed for which we have to get the vmRefs Object using https://github.com/vmware/govmomi/blob/main/examples/perfmanager/main.go#L49 which gives you VMs which are present at the current time and only for those VMs metrics are collected.

**What about the VMs which got the deleted and cannot be fetched using https://github.com/vmware/govmomi/blob/main/examples/perfmanager/main.go#L49, 

As we are passing the start and end in the https://github.com/vmware/govmomi/blob/main/examples/perfmanager/main.go#L69 PerfQuerySpec  can we get metrics for all the vms within this time period instead of passing vmRefs.**

**Comment by dougm** [comment]
I haven't used the API before, but maybe [QueryPerfComposite](https://vdc-download.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.PerformanceManager.html#queryCompositeStats) does what you need?

**Comment by praveenghuge** [comment]
is there any example for using [QueryPerfComposite](https://vdc-download.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.PerformanceManager.html#queryCompositeStats)](https://vdc-download.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.PerformanceManager.html#queryCompositeStats) ?

**Comment by praveenghuge** [comment]
thanks @dougm for helping out
```
hostsRef, err := containerView.Find(ctx, []string{"HostSystem"}, property.Filter{})
	if err != nil {
		panic(err)
	}

spec := types.QueryPerfComposite{ 
           This: *client.ServiceContent.PerfManager,,
           QuerySpec: types.PerfQuerySpec{
                  Entity: hostsRef[0], 
                  MetricId: []types.PerfMetricId{{CounterId: 6, Instance: ""}},
                  IntervalId: 1800, 
                  StartTime: &startTime, 
                  EndTime: &endTime, },
          } 


 res, err := methods.QueryPerfComposite(ctx, client, &spec)
```

this is working example with QueryPerfComposite
