### ISSUE TITLE
[BUG] vcsim - concurrent map iteration and map write

### ISSUE THREAD

**Issue by kselvamaniarkin** [vmware/govmomi#3021]
**Describe the bug**
1. concurrent map iteration and map write
2. occurs when consumed through pyvmomi randomly

**To Reproduce**
1. unable to reproduce. occurs when consumed through pyvmomi randomly
2. simulators works properly, then intermittently 

**Expected behavior**
API should return the response

**Affected version** 
Release v0.30.0
https://github.com/vmware/govmomi/releases 

**Screenshots/Debug Output**
<img width="907" alt="image" src="https://user-images.githubusercontent.com/77379175/210537062-b473c516-92b0-43f3-91fe-ce42d1035939.png">

**Vcsim logs output**
[vc_logs.txt](https://github.com/vmware/govmomi/files/10343446/vc_logs.txt)

**Comment by dougm** [comment]
```
github.com/vmware/govmomi/simulator.(*Session).Get(...)
	/home/sre/go/src/github.com/vmware/govmomi/simulator/session_manager.go:364 ...
```
The crash happens in the `simulator.Session.Get` method, in file session_manager.go, line 364 - which based on git history means the vcsim version here is almost 3 years old. Can you verify the vcsim version?
```console
% ./vcsim version
Build Version: 0.30.0
Build Commit: eabc29ba
Build Date: 2022-12-12T19:12:08Z
```

**Comment by kselvamaniarkin** [comment]
@dougm looks like this command is not supported in the version i'm using

`root@bat-simulator-simulator-site-e2e-lena-vc-5589b49cb-cxlxk:/code# ./vcsim version`
`export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=38`

seems this version is too old

should I update to latest and test once again?

**Comment by dougm** [comment]
@kselvamaniarkin yes, please try again with the current release
