### ISSUE TITLE
How to retrieve a list of VM/Host Groups using govmomi instead of govc command line

### ISSUE THREAD

**Issue by edubois10** [vmware/govmomi#3033]
### Discussed in https://github.com/vmware/govmomi/discussions/3031

<div type='discussions-op-text'>

<sup>Originally posted by **edubois10** January 19, 2023</sup>
Hi There,

I need to create a kubernetes controller that will check for VMs in a given VM Group. If I want to do this using govc I just need to
`govc cluster.group.ls -name <nameOfTheGroup>` and I will get the vms in the group, similarly if I want to add vms I would use the  `govc cluster.group.change` command.

However, I struggle to understand how govc and govmomi are linked in that matter. I tried to retrieve a ClusterComputeResource and from the ClusterComputeResource try to get the vmGroup. But I don't know how to get from the ClusterComputeResource to a vmGroup.

```
func main() {
    example.Run(fun(ctx context.Context, c *vim25.Client) error {

// Create a view of HostSystem objects
		m := view.NewManager(c)

		v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"ClusterComputeResource"}, true)
		if err != nil {
			return err
		}

		defer v.Destroy(ctx)

		var ccrs []mo.ClusterComputeResource
		err = v.Retrieve(ctx, []string{"ClusterComputeResource"}, []string{"configuration"}, &hsss)
		if err != nil {
			return err
		}
		for _, ccr := range ccrs {
			// hs is of type types.BaseComputeResourceSummary
			clusterConfigInfoEx := ccr.Configuration(ctx)
			fmt.Printf("Cluster configuration: %s", clusterConfigInfoEx.Group)
		}

	
		return nil
	})
}
```
 
I am trying to call the Configuration function from the ClusterComputeResource which returns a ClusterConfigInfoEx object.(https://github.com/vmware/govmomi/blob/939e78dc19bf32a5fef077079e9263e058ea5ee3/object/cluster_compute_resource.go).
```
func (c ClusterComputeResource) Configuration(ctx context.Context) (*types.ClusterConfigInfoEx, error) {
	var obj mo.ClusterComputeResource

	err := c.Properties(ctx, c.Reference(), []string{"configurationEx"}, &obj)
	if err != nil {
		return nil, err
	}

	return obj.ConfigurationEx.(*types.ClusterConfigInfoEx), nil
}
`
``

 However I get the error ```invalid operation: cannot call non-function ccr.Configuration (variable of type types.ClusterConfigInfo)`Ì` How do I get a ClusterConputeResource object?

Any help would be appreciated.

**Comment by dougm** [comment]
The govc command uses `Finder`, which returns a higher-level type [object.ClusterComputeResource](https://github.com/vmware/govmomi/blob/vcsim-ipconfig/object/cluster_compute_resource.go#L38). But in your example, ContainerView returns the lower-level `mo.ClusterComputeResource` type.  There is no `Configuration` method for that type, you just access the properties directly. 2 changes to your example, `configurationEx` instead of `configuration`:
```go
err = v.Retrieve(ctx, []string{"ClusterComputeResource"}, []string{"configurationEx"}, &ccrs)
```
And a type assertion instead of `Configuration` method call:
```go
clusterConfigInfoEx := ccr.ConfigurationEx.(*types.ClusterConfigInfoEx)
```

**Comment by edubois10** [comment]
Thank you Dougm for your your input. Yesterday I manage to get the configurationEx of a clusterResource using the `finder method` and getting a `ClusterComputeResourceList`. But with what you suggested I have the feeling that it is easier, since I don't need specify a `path` as I do with the `finder method`.

1. Still, I struggle to navigate through the group when I want to retrieve the Vms list in a group. Indeed a Group is of type
`[]types.BaseClusterGroupInfo` and each element of the list is of type *types.ClusterHostGroup or *types.ClusterVmGroup. 
However, when I try to access the fields of the ClusterVmGroup as it is done in here, https://github.com/vmware/govmomi/blob/939e78dc19bf32a5fef077079e9263e058ea5ee3/govc/cluster/group/info_flag.go#L80 I get `invalid operation: cannot indirect group[i] (variable of type types.BaseClusterGroupInfo)`

Here is what I am doing:
```
var confEx []mo.ClusterComputeResource
err = v.Retrieve(ctx, []string{"ClusterComputeResource"}, []string{"configurationEx"}, &confEx)
if err != nil {
	return err
}
for _, conf := range confEx {

	clusterConfigInfoEx := conf.ConfigurationEx.(*types.ClusterConfigInfoEx)
	fmt.Printf("The type of clusterConfigInfo is: %T \n", clusterConfigInfoEx) // *types.ClusterVmGroup
	group := clusterConfigInfoEx.Group
	fmt.Printf("The type of group is: %T \n", group) // []types.BaseClusterGroupInfo

	for i := range group {
		fmt.Printf("First type check for group[i]: %s\n", reflect.TypeOf(group[i])) // *types.ClusterVmGroup or *types.ClusterHostGroup
		checker := &types.ClusterVmGroup{}
		if fmt.Sprintf("%T", group[i]) == fmt.Sprintf("%T", checker) {
			vmGroup := *group[i] // Error: invalid operation: cannot indirect group[i] (variable of type types.BaseClusterGroupInfo)
			fmt.Printf("The type of group is group[i]: %s \n", vmGroup)

			//fmt.Printf("%s\t%s\n", "VirtualMachine", (*group[i]).Vm) // Error: group[i].Vm undefined (type types.BaseClusterGroupInfo has no field or method Vm)
		}

	}
```

2. Also I would be curious to know how you would proceed to add vms to a given group. Some hints would be highly appreciated.

Thank you for your time.

**Comment by edubois10** [comment]
I mange more forward with point 1. I didn't get that group was an interface and that I had to check the type `vmGroup, ok := group[i].(*types.ClusterVmGroup)` to be able to access the field of a ClusterVmGroup.

Still any input for point 2 will be welcome.

**Comment by dougm** [comment]
This method in cluster-api-provider-vsphere is a good example of adding VMs to a group:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a2c07f718a70c8e86c8f343fae0fc9b37ef07fcd/pkg/services/govmomi/cluster/vmgroup.go#L56-L68
