### ISSUE TITLE
Example for SSO client based applications

### ISSUE THREAD

**Issue by jashanj0tsingh** [vmware/govmomi#3037]
I want to create a rather lite dashboard that will leverage govmomi wrapper backend to interact with the vCenter server, the issue is that when I launch the URL for a VMs web console it asks me for credentials, I would like to reuse the credentials that client was created with and since the action is triggered by the client the authentication should be already taken care of in the first place.

This is what I have so far...

```
func NewSSOClient(ctx context.Context, client *vim25.Client) []byte {

	vSphereUri, err := GetConfiguration()
	LogError(err)

	sc := soap.NewClient(&vSphereUri, true)
	vc, err := vim25.NewClient(ctx, sc)
	LogError(err)

        stsc, err := sts.NewClient(ctx, vc)
	LogError(err)

	return []byte(stsc.URL().RawPath)
}
```

**Comment by kmahyyg** [comment]
The SSO client related examples can be found on `govc/sso/` folder.

**Comment by kmahyyg** [comment]
Comments edited, and updated. Please check on the web page.
