### ISSUE TITLE
[BUG] `ssoadmin.NewClient()` method does NOT inherit transport setting from `c *vim25.Client` passed in.

### ISSUE THREAD

**Issue by kmahyyg** [vmware/govmomi#3039]
**Describe the bug**

`ssoadmin.NewClient()` create a new `*soap.Client` without any reuse of passed in `*vim25.Client`.

**To Reproduce**

1. Set a proxy using `http.Transport` like this `sc.DefaultTransport().Proxy = http.ProxyURL(proxyServerAddr)` when trying to `login` using default `*vim25.Client`
2. Call `ssoadmin.NewClient(ctx context.Context, c *vim25.Client) (*Client, error)` with a proxy-enabled `*vim25.Client` that has been set up using above method.
3. `/go/pkg/mod/github.com/vmware/govmomi@v0.30.0/ssoadmin/client.go:78` created a new `*soap.Client` without any inheritance of the param `c` passed in. Thus, `Proxy` function will not work.

**Expected behavior**

`/go/pkg/mod/github.com/vmware/govmomi@v0.30.0/ssoadmin/client.go:78` should reuse `c *vim25.Client` if possible.

**Affected version**

govmomi@v0.30.0

**Screenshots/Debug Output**

Normally and expected:

![20230128-184146-GoLand-001370@2x](https://user-images.githubusercontent.com/16604643/215262302-4c789a0f-05d1-49ee-8425-debcb67521e9.png)

Unexpected, `proxy` function in transport is not reused:

![20230128-184347-GoLand-001372@2x](https://user-images.githubusercontent.com/16604643/215262398-9fe07570-ce60-4384-98e8-80f1ae1ec9c6.png)

**Additional context**

A temporary solution here might be changing the whole default `Transport` value of `http.Client`, may be related to https://github.com/golang/go/issues/39299 .

**Comment by dougm** [comment]
I don't recall why the entire transport wasn't shared, but the (untested) change below should work. Not sure this is the right fix, but certainly we should include the proxy settings here.
```diff
modified   vim25/soap/client.go
@@ -199,10 +199,7 @@ func (c *Client) NewServiceClient(path string, namespace string) *Client {
 
 	client := NewClient(u, c.k)
 	client.Namespace = "urn:" + namespace
-	client.DefaultTransport().TLSClientConfig = c.DefaultTransport().TLSClientConfig
-	if cert := c.Certificate(); cert != nil {
-		client.SetCertificate(*cert)
-	}
+	client.Client.Transport = c.Client.Transport // or c.Client.Transport.Clone()
 
 	// Copy the trusted thumbprints
 	c.hostsMu.Lock()
```
