### ISSUE TITLE
Support for datastore.cluster.upload

### ISSUE THREAD

**Issue by anbohm** [vmware/govmomi#3043]
Missing upload feature for datastore cluster. It's possible to upload with datastore.upload, but not to a datastore.cluster. 

Hope you can add following "datastore.cluster.upload" that allow to upload files to a cluster. 

Only alternative today is to use powercli with Powershell.

**Comment by dougm** [comment]
@anbohm can you describe what the command would do? And/or share links to powercli/Powershell docs/code?

**Comment by anbohm** [comment]
Sorry for late answer, but issue is that its not possible to point to datastore cluster but only datastore direct.

With PowerCLI its possible to get-item from a datastore cluster: https://kb.vmware.com/s/article/2001041

Think this is more limit in VMware and maybe not ready to be fixed in GOVC
