### ISSUE TITLE
[BUG] Library item description can't be updated if it is set to an empty string in UpdateLibraryItem.

### ISSUE THREAD

**Issue by yi0909** [vmware/govmomi#3048]
**Describe the bug**
The Description field of the library Item should be a string pointer type instead of string. If the new description field of a library item is set to an empty string, UpdateLibraryItem would fail to update its description because it can't distinguish if this field is unset or is set to empty.

**To Reproduce**
1. Create an Item with non-empty description.
2. Update this item using UpdateLibraryItem vAPI, which sets the new description to "".
3. The item still has the old non-empty description.

**Expected behavior**
The item should now have empty description.

**Affected version**
TOT
commit: 20dc95ef926a3dd5692b6b72e3e189269df52e7d

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by dougm** [comment]
Fixed in #3049
