### ISSUE TITLE
vSphere 5.1 compatible

### ISSUE THREAD

**Issue by felixbuenemann** [vmware/govmomi#305]
I've had no trouble using govc with docker-machine to create a machine on a vCenter 5.1 / ESXI 5.1 cluster, so it might be fine to lower the default for GOVC_MIN_API_VERSION to 5.1.

**Comment by dougm** [comment]
Thanks for the report @felixbuenemann 

Will consider this as part of issue #384 - even if we don't change the default, we should be able to override.
