### ISSUE TITLE
Add support for Datasets (both Vphere API and Guest)

### ISSUE THREAD

**Issue by gitirabassi** [vmware/govmomi#3050]
**Is your feature request related to a problem? Please describe.**
Seems like Datasets are enabled by default on Vphere 8 but nor the UI nor the CLI can configure them yet

https://core.vmware.com/resource/vsphere-datasets#section1

**Describe the solution you'd like**
I'd like to setup dataset for machines using the CLI/Terraform

**Comment by dekp** [comment]
@gitirabassi , the ask for API/CLI support seems clear to me, but could you please explain what do you expect as "guest support" for DataSets in govmomi ?

My understanding is the following:
			
DataSets can be accessed from within the VM guest OS via:

- the CLI of VMware tools, i.e. `vmtoolsd --cmd,` as described in the [DataSets blog](https://core.vmware.com/resource/vsphere-datasets)
- the VMware [Guest SDK](https://developer.vmware.com/docs/16962/vmware-guest-sdk-programming-guide/GUID-AEC8BE71-FA22-4A87-8C6F-F4EBE95AA8DE.html)

The govmomi [toolbox](https://github.com/vmware/govmomi/tree/main/toolbox) sub-project is a partial alternative to the VMware tools daemon. However, govmomi does not have an alternative to the VMware tools CLI, nor to the VMware Guest SDK.
