### ISSUE TITLE
[BUG] List Datastore does not return the tag

### ISSUE THREAD

**Issue by kannanvr** [vmware/govmomi#3082]
**Describe the bug**
  Vsphere API for Datastore does not return the tags correspond to the Datastore
**To Reproduce**
    1. Create tag
    2. Attach the tag to the Datastore
    3. Get the Datastore using API. There is a tag parameter on mo.Datastore structure. . It is always returning empty
    
'''
        vc, err := vs.ViewManager.CreateContainerView(ctx, vs.Vim25Client.ServiceContent.RootFolder, []string{"Datastore"}, true)
        if err != nil {
                return nil, fmt.Errorf("error while creating container view: %v", err)
        }
        defer vc.Destroy(ctx)

        var dsList []mo.Datastore
        err = vc.Retrieve(ctx, []string{"Datastore"}, []string{"tag" , "summary"}, &dsList)

        datastores = make([]types.DatastoreSummary, len(dsList))
        for i, ds := range dsList {
                if len(ds.Tag) > 0 {

                fmt.Println("Tag is %+v",ds.Tag)
                }
                datastores[i] = ds.Summary
        }
'''
  With the above code, tag is alwaysd returning empty

**Expected behavior**
   Tag should be returned back for the corresponding Datastore

**Affected version**
Latest version

**Comment by dougm** [comment]
You need to use the tags API rather than the (obsolete) tag property. See this example:
https://github.com/vmware/govmomi/blob/c2cf82e16a6889ea41d53bd4f81514e15a0780bb/vapi/tags/example_test.go#L109
