### ISSUE TITLE
[BUG] Can not reconcile datastore with many cns volumes

### ISSUE THREAD

**Issue by bvv906** [vmware/govmomi#3088]
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa2c3a9]

**To Reproduce**

1. run  govc disk.ls -R -ds [datastore] -dc [datacenter] -verbose
2. wait

**Expected behavior**
successful reconcilation

**Affected version**
govc 0.30.2

**Screenshots/Debug Output**
...
WaitForUpdatesEx(PropertyCollector:session[...], 2, nil)...
DestroyPropertyCollector(PropertyCollector:session[...])...
...void

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa2c3a9]

goroutine 1 [running]:
github.com/vmware/govmomi/govc/flags.(*verbose).updateSet(0xf71de0?, 0xc00000e010?)
        /home/runner/work/govmomi/govmomi/govc/flags/debug.go:350 +0x29
github.com/vmware/govmomi/govc/flags.(*verbose).RoundTrip(0xc0002d26e0, {0x13fa320, 0xc0000a6000}, {0x13f2000?, 0xc0000b1500}, {0x13f2000?, 0xc0000b1518})
        /home/runner/work/govmomi/govmomi/govc/flags/debug.go:454 +0x6d8
github.com/vmware/govmomi/vim25.(*Client).RoundTrip(0x4?, {0x13fa320?, 0xc0000a6000?}, {0x13f2000?, 0xc0000b1500?}, {0x13f2000?, 0xc0000b1518?})
        /home/runner/work/govmomi/govmomi/vim25/client.go:129 +0x46
github.com/vmware/govmomi/vim25/methods.WaitForUpdatesEx({0x13fa320, 0xc0000a6000}, {0x13efbe0, 0xc0000e0840}, 0xc00047ecc0)
        /home/runner/work/govmomi/govmomi/vim25/methods/methods.go:18339 +0xa4
github.com/vmware/govmomi/property.WaitForUpdates({0x13fa320, 0xc0000a6000}, 0x2?, 0xc00030d970, 0xc00030d8d0)
        /home/runner/work/govmomi/govmomi/property/wait.go:112 +0x2f2
github.com/vmware/govmomi/task.Wait({0x13fa320, 0xc0000a6000}, {{0xc0002a3138?, 0xc0002f9bc0?}, {0xc0002a3160?, 0x9?}}, 0xc?, {0x0, 0x0?})
        /home/runner/work/govmomi/govmomi/task/wait.go:129 +0x3bf
github.com/vmware/govmomi/object.(*Task).WaitForResult(0x13ef200?, {0x13fa320?, 0xc0000a6000?}, {0xc000545be8?, 0xc000034e28?, 0x15?})
        /home/runner/work/govmomi/govmomi/object/task.go:57 +0x15e
github.com/vmware/govmomi/object.(*Task).Wait(...)
        /home/runner/work/govmomi/govmomi/object/task.go:47
github.com/vmware/govmomi/govc/disk.(*ls).Run(0xc0000a2480, {0x13fa320, 0xc0000a6000}, 0xc00009e480)
        /home/runner/work/govmomi/govmomi/govc/disk/ls.go:140 +0x24f
github.com/vmware/govmomi/govc/cli.Run({0xc0000a4010, 0x7, 0x7})
        /home/runner/work/govmomi/govmomi/govc/cli/command.go:165 +0x32d
main.main()
        /home/runner/work/govmomi/govmomi/govc/main.go:117 +0x4f

**Additional context**
tried
go version go1.17.7 linux/amd64
go version go1.18.9 linux/amd64

Succesful, if datastore contains ~20 volumes

**Comment by bvv906** [comment]
vSphere version 7.0.1.00200

**Comment by dougm** [comment]
> github.com/vmware/govmomi/govc/flags.(*verbose).updateSet(0xf71de0?, 0xc00000e010?)
/home/runner/work/govmomi/govmomi/govc/flags/debug.go:350 +0x29

Looks like this is an issue with the `-verbose` flag, which we can fix. Does the command work without `-verbose` ?

**Comment by dougm** [comment]
Can you run again using the `-trace` flag instead?  That should provide more detail on the ServerFaultCode, and not panic as `-verbose` currently does.  Sounds like this is an issue on the vCenter side, but with that detail I could find some folks who may be able to help.

**Comment by bvv906** [comment]
[govc reconcile.txt](https://github.com/vmware/govmomi/files/11392859/govc.reconcile.txt)
