### ISSUE TITLE
Use log interface in simulator

### ISSUE THREAD

**Issue by flymop** [vmware/govmomi#3090]
**Is your feature request related to a problem? Please describe.**
The simulator use log function for printing log, which does not support log replacment. While in most unit test cases, it is not necessary to show the detail logs.

**Describe the solution you'd like**
Use an logger interface
```
// assume in `log` package
// create Logging interface
type Logging interface {
	Printf(ctx context.Context, format string, v ...interface{})
}

// use std-lib log package as default, and print to stderr
var Logger Logging

// have an function to replace the default logger
func SetLogger(logger Logger) {
     log.Logger = logger
}
```
call log like this
```
log.Logger.Printf(msg)
```

**Describe alternatives you've considered**
use [slog](https://go.googlesource.com/proposal/+/master/design/56345-structured-logging.md)

which has [SetDefault](https://pkg.go.dev/golang.org/x/exp/slog#SetDefault) for customization

**Additional context**
N/A

**Comment by dougm** [comment]
Hi @flymop ,
> While in most unit test cases, it is not necessary to show the detail logs

Are you just wanting to disable logging in the simulator?  If so, we could just add a flag to the simulator package, where setting `simulator.Verbose = false` would turn off logging.
Or did you have other use cases in mind for the Logging interface?

**Comment by flymop** [comment]
> 

Yes, that would fit my requirement pretty well, I don't have further consideration on other scenarios, thanks!
