### ISSUE TITLE
[BUG] vcsim: viewmanager doesn't return all Datastore types when parent is StoragePod

### ISSUE THREAD

**Issue by BoukeG** [vmware/govmomi#3094]
**Describe the bug**
When using a ContainerView.Retrieve() method, vcsim doesn't return the Datastore managed entities when it's parent is of a StoragePod type.

**To Reproduce**

1. with golang: Create a ContainerView
1. with golang: Execute method ```Retrieve()```
1. When executing to the vCenter: returns all datastore entities
1. When executing to vcsim with a dump (govc save): doesn't return the datastore entities which are in a datastore cluster (storagepod)

**Expected behavior**
I expect all datastore managed entities, also the ones connected to a storagepod (datastore cluster)

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.
Using latest version:
```
Build Version: 0.30.4
Build Commit: 4561966a
Build Date: 2023-03-16T18:15:54Z
```

**Screenshots/Debug Output**
Expected (this output is from vCenter):
![image](https://user-images.githubusercontent.com/8665245/232026170-a1e4de0d-90fe-44cf-ab46-fe70263d325c.png)
Getting (this output is from vcsim):
![image](https://user-images.githubusercontent.com/8665245/232026381-6b4f4d51-4fb7-4bd6-9f03-7157c8ff8caf.png)

**Additional context**
Using get-datastore cmdlet does return the datastores, so the objects are loaded in vcsim, but the viewmanager doesn't return them like a vCenter system does. Also checked with 'govc find -l' doesn't return the datastores which parent is a storagepod.
Output from get-datastore:
![image](https://user-images.githubusercontent.com/8665245/232027461-fa0dd8bb-8dd4-4658-b9e8-57edd97982e1.png)

**Comment by BoukeG** [comment]
Thanks Doug for this fast and good fix! I just checked and it works as it should. Thank you. Looking forward to the completion of the pull request. I don't know if need to close this manually or it automatically closes once the PR is completed.

**Comment by dougm** [comment]
No problem @BoukeG , thanks for testing it out. The issue will auto-close once the PR is approved and merged.
