### ISSUE TITLE
kubernetes cluster on vcloud air

### ISSUE THREAD

**Issue by sameersbn** [vmware/govmomi#310]
I am new to vmware vcloud and/or other vmware products.

The kubernetes on vsphere docs indicate the use of `govc`. I was wondering if this tool can be used to setup a kubernetes cluster on vcloud air.

If possible can you point me to any resource that describes the procedure to setup kubernetes on vcloud air. 

Thanks for your support

**Comment by pietern** [comment]
Hi,

`govc` can only be used with vSphere (vCenter and ESXi), not vCloud Air. I don't know of Kubernetes instructions for vCloud Air. You could start with the vCA [command line client](https://github.com/vmware/vca-cli), start a VM that runs docker, and run the Kubernetes docker images in there, but that's all I can help you with.
