### ISSUE TITLE
import ova,ovf from url

### ISSUE THREAD

**Issue by pandrew** [vmware/govmomi#311]
Would be great if there would be an option to import from url. That way i could upload to a webserver and let me and maybe others to import directly from that address.

**Comment by pietern** [comment]
It is not possible to upload disks in an OVA from some place else as far as I know. This means that even if we were to add an option to import from an URL, we would end up downloading the full archive first, reading the appropriate bits, and then uploading it to vCenter/ESXi. This is not different from asking your users to download the OVA themselves and then importing the local file.

Thanks for the suggestion though :)
