### ISSUE TITLE
[Question] Does template clone support DatastoreCluster 

### ISSUE THREAD

**Issue by zhanggbj** [vmware/govmomi#3138]
I created DatastoreCluster that contains two datastores on vCenter. When using template [Clone](https://github.com/vmware/govmomi/blob/main/object/virtual_machine.go#L197), I would like specify a DatastoreCluster, but it looks like there's only a `datastore` field (check code [here](https://github.com/vmware/govmomi/blob/main/vim25/types/types.go#L54488)), does it mean govmoni doesn't support `DatastoreCluster` yet? or we should also use `datastore` field to specify a DatastoreCluster? Thanks!
```
type VirtualMachineRelocateSpec struct {
	DynamicData

	Service      *ServiceLocator                         `xml:"service,omitempty"`
	Folder       *ManagedObjectReference                 `xml:"folder,omitempty"`
	Datastore    *ManagedObjectReference                 `xml:"datastore,omitempty"`
	DiskMoveType string                                  `xml:"diskMoveType,omitempty"`
	Pool         *ManagedObjectReference                 `xml:"pool,omitempty"`
	Host         *ManagedObjectReference                 `xml:"host,omitempty"`
	Disk         []VirtualMachineRelocateSpecDiskLocator `xml:"disk,omitempty"`
	Transform    VirtualMachineRelocateTransformation    `xml:"transform,omitempty"`
	DeviceChange []BaseVirtualDeviceConfigSpec           `xml:"deviceChange,omitempty,typeattr"`
	Profile      []BaseVirtualMachineProfileSpec         `xml:"profile,omitempty,typeattr"`
	CryptoSpec   BaseCryptoSpec                          `xml:"cryptoSpec,omitempty,typeattr"`
}
```

**Comment by HakanSunay** [comment]
> does it mean govmoni doesn't support DatastoreCluster yet?

What do you mean by "yet"? Do other SDKs (like pyvmomi) or the actual vim API support relocations with datastore clusters?


When I look at the docs:

| NAME | TYPE | DESCRIPTION |
| --------------- | --------------- | --------------- |
| **datastore** | [ManagedObjectReference](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vmodl.ManagedObjectReference.html) to a [Datastore](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vim.Datastore.html) | The datastore where the virtual machine should be located. If not specified, the current datastore is used. |

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vim.vm.RelocateSpec.html

**Comment by BoukeG** [comment]
Sure you can, but you need the StorageManager methods for it. Check: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1ef6c336-7bef-477d-b9bb-caa1767d7e30/82521f49-9d9a-42b7-b19b-9e6cd9b30db1/vim.StorageResourceManager.html#recommendDatastores

**Comment by zhanggbj** [comment]
@HakanSunay I'm asking because vCenter support DatastoreCluster and StoragePolicy, so I assume govmoni should support VM clone using DatastoreCluster instead of specific Datastore to leverage HA, balancing and other features.

**Comment by zhanggbj** [comment]
@BoukeG  thanks for the info, that looks very promising, I'll take a try.

**Comment by dougm** [comment]
You'll find examples of recommendDatastores here: https://github.com/vmware/govmomi/blob/55610386b0e4c1e29a70e39a89383838a70e6447/vslm/object_manager.go#L56

And in govc:
https://github.com/vmware/govmomi/blob/55610386b0e4c1e29a70e39a89383838a70e6447/govc/vm/create.go#L535

https://github.com/vmware/govmomi/blob/55610386b0e4c1e29a70e39a89383838a70e6447/govc/vm/clone.go#L364

**Comment by zhanggbj** [comment]
@dougm thanks for the precise examples. So based on the code vm/clone.go, govmomi is still using a specific datastore which is recommended by `storageResourceManager`. Just out of curiosity, is it possible that only specify a datastorecluster and delegate datastore selection to vCenter, as usually if theres a XXCluster exist, we will use it directly but don't care how the XXCluster behaviors, XXCluster will make the decision to choose one backend.

**Comment by BoukeG** [comment]
It's not that govmomi determines to use a data store. `recommendDatastore` is actually calling the SDRS functionality to determine the proper datastore.

We've got two methods: either the vm/clone method where you get the datastore from `recommendDatastore`. Or you could put the result from `recommendDatastore` into `ApplyStorageDrsRecommendation`-> if you've provided the full clone spec, the deployment will be done by the storage manager.
