### ISSUE TITLE
guest_id.go needs to be updated

### ISSUE THREAD

**Issue by Alvis-pixel** [vmware/govmomi#3140]
We need more modern guest OS IDs like VirtualMachineGuestOsIdentifierWindows2019srv_64Guest.

**Comment by Alvis-pixel** [comment]
I thought this would resolve missing guest IDs, but when I try the following command:

"govc vm.change -g windows2019srv_64Guest -vm DC0_H0_VM0"

I still get the result:

"govc: *types.InvalidArgument"

Using guest ids that was present earlier works.

**Comment by Alvis-pixel** [comment]
I thought this would resolve missing guest IDs, but when I try the following command:

"govc vm.change -g windows2019srv_64Guest -vm DC0_H0_VM0"

I still get the result:

"govc: *types.InvalidArgument"

Using guest ids that was present earlier works.

**Comment by dougm** [comment]
`-g windows2019srv_64Guest` works for me using your change:

```console
% govc about | grep govmomi
FullName:     VMware vCenter Server 6.5.0 build-5973321 (govmomi simulator)

% govc vm.option.info -vm DC0_H0_VM0 | grep 2019
windows2019srv_64Guest      
windows2019srvNext_64Guest  

% govc object.collect -s vm/DC0_H0_VM0 config.guestId
otherGuest

% govc vm.change -trace -g windows2019srv_64Guest -vm DC0_H0_VM0

% govc object.collect -s vm/DC0_H0_VM0 config.guestId
windows2019srv_64Guest
```

**Comment by Alvis-pixel** [comment]
Ok, I see where I was misstaken now. I'll have to wait for the new version, my docker image installs the latest go modules;

"go install github.com/vmware/govmomi/vcsim@latest"
