### ISSUE TITLE
Bump vCenter Server and ESXi versions

### ISSUE THREAD

**Issue by Alvis-pixel** [vmware/govmomi#3152]
With reference to the vCenter Server and ESXi versions following the [VMware Product Lifecycle Matrix](https://lifecycle.vmware.com/)

I think it would be prudent to upgrade the vCenter Server and ESXi versions used in this project to at least 7.0 since general support for the current version ended 2022-10-15.

**Comment by dougm** [comment]
Assuming you are referring to the default simulator values?  govmomi is using the 8.0 API version, so you can use any version with vcsim: https://github.com/vmware/govmomi/wiki/vcsim-features#record-and-playback

We should bump the default vcsim values at some point too, anything had in mind other than the version fields themselves?
