### ISSUE TITLE
govc: no such host 

### ISSUE THREAD

**Issue by jakharpraveen** [vmware/govmomi#3157]
Hello folks.
I'm running these test cases in a docker container. I've stuck with this problem... I'm trying delete vm in vmwarevsphere using govc(in CDS workflow, venom cli test case fails ).

When I run this:

```
# destroyVM
- name: destroyVM
  steps:
  - type: exec
    retry: 3
    delay: 20
    script: |
        export GOVC_URL="{{.API.serviceName}}"
        export GOVC_USERNAME="{{.userName}}"
        export GOVC_PASSWORD="{{.userPass}}"
        export GOVC_DATACENTER="{{.API.serviceName}}_datacenter{{.API.datacenterId}}"
        govc vm.destroy {{.restored_vm_name}}*
    info: "Result status code : {{.result.code}} {{.result}} {{.userName}} {{.userPass}}"
    assertions:
    - result.code ShouldEqual 0
```
      
I am getting following error

`govc: Post "https://pcc-xx-xx-xx-xx/sdk": dial tcp: lookup pcc-xx-xx-xx-xx on xx.xx.xx.xx:53: no such host
`

**Troubleshoot I have done is checked network access**

**Comment by dougm** [comment]
Looks like a dns issue, not a govc issue. Do you see the same with other programs, such as curl:
```console
% curl https://pcc-xx-xx-xx-xx
curl: (6) Could not resolve host: pcc-xx-xx-xx-xx
```
