### ISSUE TITLE
Cross referencing virtual nic and portgroups id with network names ? 

### ISSUE THREAD

**Issue by nipil** [vmware/govmomi#3158]
Hello,

I am using vm.info and dvs.portgroup.info to dump json. Then i get the network interfaces from vminfo (Network key) which provide me with portgroup ids.

Then i want to cross-reference these with the network informations provide from vminfo (Guest key). These provide me with network names.

I cannot seem to find a way to cross reference the network names in Guest to any portgroup ids.

The name field in dvs.portgroup.info is empty, and the portgroup id is not provide in the Guest part of vm.info

Is there any way to do this ?
Of not, could you simplement a way to cross-reference vnics to networks and ip ?

Thanks in advance

**Comment by dougm** [comment]
Network names are included with the `-r` flag, is this not what you need?

```console
% govc vm.info -r $vm | grep Network:
  Network:              VM Network, vm-domain-c9:faa1546d-34a5-4938-b0b9-93df862e156c-vif-default-network-0
```

**Comment by nipil** [comment]
I am using json output, and these flags do not modify the output AFAIK

When using `vm.info -json=True`, you get a `Network` key for any VM (powered on, or off, with or without VMware tools installed and running).

For me with a DVS, it looks like :
`"Network": [ { "Type": "DistributedVirtualPortgroup", Value: "dvportgroup-12345" } ]`

When browsing the VCenter, i can see `FOO` as the portgroup name for the VNIC.
And i can see it _even when the VM is not running_.

But when the vmware tools are not running, `FOO `appears nowhere in the `vm.info` json.
Only when the vmware tools are running, `FOO `appears as part of the `Guest` key information.

**So my question is** : how can i, _using govc_, associate value `dvportgroup-12345` to its network name `FOO` ?

This would allow me to correctly get the PG names for the Vnics, even for powered of vm or guests with no vmware tools installed.

**Comment by dougm** [comment]
ok, right, the `-r` flag does not change the json output.  The VirtualMachine.Network field is a list of managed object references, you can use the object.collect command to get the names:

```console
% govc object.collect -s DistributedVirtualPortgroup:dvportgroup-133 name             
vnet-domain-c9:faa1546d-34a5-4938-b0b9-93df862e156c-test-gc-e2e-demo-ns-b9224-0
```

Using object.collect can also simplify uses of vm.info -json, for example to just collect the network field:

```console
% govc object.collect -s $vm network
DistributedVirtualPortgroup:dvportgroup-133
```

**Comment by nipil** [comment]
> ok, right, the `-r` flag does not change the json output. The VirtualMachine.Network field is a list of managed object references, you can use the object.collect command to get the names:

I had not noticed the object.collect method... Great !
Your feedback just allowed me to do exactly what i was looking for.
Thanks a lot for your time !
