### ISSUE TITLE
Support for new network adapter type 'pvrdma'

### ISSUE THREAD

**Issue by lubronzhan** [vmware/govmomi#3166]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I cannot do X because [...]
Right now supported network adapter types are [here](https://github.com/vmware/govmomi/blob/main/object/virtual_device_list.go#L63-L69) 
```
		&types.VirtualE1000{},
		&types.VirtualE1000e{},
		&types.VirtualVmxnet2{},
		&types.VirtualVmxnet3{},
		&types.VirtualVmxnet3Vrdma{},
		&types.VirtualPCNet32{},
		&types.VirtualSriovEthernetCard{},
```

It doesn't have this type as you can see from vSphere UI. Related document about how to add such adapter from vSphere [here](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-347B822E-5324-4DB3-A228-1F6A7AA871D2.html)
![image](https://github.com/vmware/govmomi/assets/8584193/21a0b384-6796-4b6a-9d60-15d3d1b4a8c4)

A [description](https://blogs.vmware.com/vsphere/2020/10/para-virtual-rdma-support-for-native-endpoints.html) for pvrdma
> RDMA over Converged Ethernet (RoCE) is a network protocol that allows remote direct memory access (RDMA) over an Ethernet network. RDMA between VMs is known as Paravirtual RDMA.

Some VMware customer wants to use Bitfusion with RDMA

**Describe the solution you'd like**
Govc supports adding/configuring/deleting new network adapter type from VM

**Describe alternatives you've considered**

**Additional context**

**Comment by lubronzhan** [comment]
I can try work on it if it's Ok

**Comment by dougm** [comment]
> I can try work on it if it's Ok

Sounds good, not familiar with pvrdma myself, but can try to help if needed.

**Comment by lubronzhan** [comment]
Hm. I think `VirtualVmxnet3Vrdma` is the `pvrdma `. Let me give it a try through govc command

**Comment by lubronzhan** [comment]
Ok confirmed actually the functionality is already there. It's just that I didn't find the correct adapter name. Thanks Doug. Gonna close this
```
govc vm.network.add -vm test -net "port-group-vlan-101" -net.adapter vmxnet3vrdma
```
![image](https://github.com/vmware/govmomi/assets/8584193/f10299d7-f103-4d53-b6cd-8371b8f84b05)

**Comment by lubronzhan** [comment]
It has device protocol option just for this adapter. Maybe I can add that option

**Comment by lubronzhan** [comment]
But looks like VirtualDevice doesn't give you that option, I have to create a `VirtualVmxnet3Vrdma ` device from the generic BaseVirtualDevise so I could modify the device protocol?
https://github.com/vmware/govmomi/blob/main/govc/flags/network.go#L119C1-L123C1

**Comment by dougm** [comment]
Hi @lubronzhan , have not tried this, but maybe something like the patch below would work?
```diff
modified   govc/flags/network.go
@@ -35,6 +35,7 @@ type NetworkFlag struct {
 	net     object.NetworkReference
 	adapter string
 	address string
+	proto   string
 	isset   bool
 }
 
@@ -62,6 +63,7 @@ func (flag *NetworkFlag) Register(ctx context.Context, f *flag.FlagSet) {
 		f.Var(flag, "net", usage)
 		f.StringVar(&flag.adapter, "net.adapter", "e1000", "Network adapter type")
 		f.StringVar(&flag.address, "net.address", "", "Network hardware address")
+		f.StringVar(&flag.proto, "net.protocol", "", "Network adapter protocol")
 	})
 }
 
@@ -131,6 +133,12 @@ func (flag *NetworkFlag) Device() (types.BaseVirtualDevice, error) {
 		card.MacAddress = flag.address
 	}
 
+	if flag.proto != "" {
+		if a, ok := device.(*types.VirtualVmxnet3Vrdma); ok {
+			a.DeviceProtocol = flag.proto
+		}
+	}
+
 	return device, nil
 }
```

**Comment by lubronzhan** [comment]
Oh it works . I was trying to convert from `BaseVirtualEthernetCard` instead of `BaseVirtualDevice` to `VirtualVmxnet3Vrdma` type and it fails. 
Thank you

**Comment by lubronzhan** [comment]
Let me create a new issue https://github.com/vmware/govmomi/issues/3167
