### ISSUE TITLE
[BUG] Build job fail because `replacement` is deprecated in gorelease

### ISSUE THREAD

**Issue by lubronzhan** [vmware/govmomi#3169]
**Describe the bug**
Due to the deprecation of some fields in gorelease, build job in PR will fail, for example: https://github.com/vmware/govmomi/actions/runs/5429621792/jobs/9874764353?pr=3168

The deprecation doc https://goreleaser.com/deprecations/#archivesreplacements

**To Reproduce**

1. open an PR

**Expected behavior**
Build job pass

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by dougm** [comment]
Fixed in #3170
