### ISSUE TITLE
[BUG] Should not panic when New vapi object with nil registry

### ISSUE THREAD

**Issue by lubronzhan** [vmware/govmomi#3178]
**Describe the bug**
CPI simulate vapi in the test, it pass nil for `vim.BaseOptionValue`
https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/vsphere_test.go#L99

Since this PR [vcsim: add ssoadmin user and group management](https://github.com/vmware/govmomi/commit/d46fe80a3a637d681e2586449079924f8759a4ca) Now the New function expect `simulator.Registry` instead of `settings []vim.BaseOptionValue` as parameter. But it didn't check the nil value before it gets `r.SessionManager` out of it.

It should either just pass nil as manager, or error out if right now this sessionManager is required, for backward compatibility.
But now it will panic

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x25152f3]

goroutine 10 [running]:
testing.tRunner.func1.2({0x287fb80, 0x3fea980})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x287fb80, 0x3fea980})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/vmware/govmomi/simulator.(*Registry).Get(0xc65a17dbdf582d4c?, {{0x2c7229b, 0xf}, {0x2c7229b, 0xf}})
	/Users/lzhan/work/pkg/mod/github.com/vmware/govmomi@v0.30.6/simulator/registry.go:193 +0x53
```

**To Reproduce**

1. In test, register vAPI through below commend
```
vapiPath, handler := vapi.New(s.URL, nil)
```

**Expected behavior**
No panic

**Affected version**
0.30.6

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by lubronzhan** [comment]
Tried to workaround with `r := &simulator.Registry{}` but got below error
```
--- FAIL: TestWhichVCandDCByZoneMultiDC (0.48s)
panic: interface conversion: mo.Reference is nil, not *simulator.ServiceInstance [recovered]
	panic: interface conversion: mo.Reference is nil, not *simulator.ServiceInstance
```

Hi @dougm  is there any faster way to workaround this?

**Comment by dougm** [comment]
@lubronzhan sorry we ended up cherry-picking that breaking change into the patch release. Opened a PR: https://github.com/kubernetes/cloud-provider-vsphere/pull/740

**Comment by lubronzhan** [comment]
Thanks for the quick fix!
