### ISSUE TITLE
 Add support for vSphere 8.0U1

### ISSUE THREAD

**Issue by muzi502** [vmware/govmomi#3193]
**Is your feature request related to a problem? Please describe.**

vSphere [8.0U1](https://docs.vmware.com/en/VMware-vSphere/8.0/rn/vsphere-esxi-801-release-notes/index.html) has been released for over a month. pyvmomi has added support for 8.0U1 in version [8.0.1.0.2](https://github.com/vmware/pyvmomi/releases/tag/v8.0.1.0.2) last week. Could govmomi add support for vSphere 8.0U1?

**Describe the solution you'd like**

 Add support for vSphere 8.0U1

**Additional context**

#3006

https://github.com/vmware/pyvmomi/releases

cc @akutz

**Comment by Muy69** [comment]
Is there already progess in that matter, as with vSphere 8.0 U1 also VSAN ESA was introduced with more VSAN Metrics and different Polling Intervals ?

**Comment by muzi502** [comment]
Closed by https://github.com/vmware/govmomi/pull/3232

**Comment by akutz** [comment]
Hi @muzi502,

My apologies for not doing this sooner. I did not see this ticket filed, or else I would have expidited attending to the matter. Thank you for your patience.

**Comment by Muy69** [comment]
@akutz Are you aware when it could be included in a next Release ?

**Comment by akutz** [comment]
I know @dougm wants to do a release pending some loose ends to tie up. Regardless, prior to that we also want to update the release model so that release tags are created on or merged back onto `main`, else the Go module tag will always reflect the last tag on `main`, v0.28.

**Comment by akutz** [comment]
Making sure y'all saw https://github.com/vmware/govmomi/pull/3236 as well :)
