### ISSUE TITLE
[BUG] Panic occurs when invalid port is passed for vcenter login

### ISSUE THREAD

**Issue by HelloWorldMisc** [vmware/govmomi#3197]
**Describe the bug**
When we try to login to vcenter with invalid port, it is giving nil dereference error
runtime error: invalid memory address or nil pointer dereference
goroutine 239 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x113ffa0, 0x1f6c600})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/vmware/govmomi/session.Manager.Reference(...)
	/go/pkg/mod/github.com/vmware/govmomi@v0.30.6/session/manager.go:74
github.com/vmware/govmomi/session.(*Manager).Login(0xc00047bc80, {0x16b0ab8, 0xc000729950}, 0xc0005c71d8)
	/go/pkg/mod/github.com/vmware/govmomi@v0.30.6/session/manager.go:89 +0x5d

**To Reproduce**

1.  Configure the vcenter on any port
1. Try to login with Login() method with any other port (hostname:invalid_port)
1. Error

**Expected behavior**
It should throw an error not crash

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.
v27.4 to v30.6

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by dougm** [comment]
Please share a code snippet to reproduce. Sounds like an earlier error was ignored or client was not properly initialized.
