### ISSUE TITLE
Allow the usage of .iso files from a Content Library with device.cdrom.insert

### ISSUE THREAD

**Issue by Goose29** [vmware/govmomi#3213]
**Is your feature request related to a problem? Please describe.**

In a previous issue found [here](https://github.com/vmware/govmomi/issues/1697) the desired outcome was discussed and proposed, but a [hacky solution](https://github.com/vmware/govmomi/blob/main/govc/USAGE.md#libraryinfo) was chosen (`govc device.cdrom.insert -vm $vm -device cdrom-3000 $(govc library.info -L /lib1/item1/file1)`) and the issue was closed. The solution previously proposed, which was to use library.info -L to get the path does not work for me (which is also the example used with the --help of the command) to mount a .iso from a content library through device.cdrom.insert. This method results in a no media found screen, the file referenced exists, and can be queried through a library.info call with the full path.

**Describe the solution you'd like**

I would like a solution that can reference the .iso file directly within the device.cdrom.insert command, without making a separate call to the datastore to get its path (this call doesn't work in my case). There were excellent proposed ideas in the above linked issue, but in the end I would like it to use the Content Library ISO File native feature.

**Describe alternatives you've considered**

I am not entirely sure what alternatives there are, I have tried the officially stated method to get a iso mounted through vm.create and then device.cdrom.insert which just ends in a no media found screen on boot. And I am not able to figure out what was meant in the last comment on the issue, so his [workaround](https://github.com/vmware/govmomi/issues/1697#issuecomment-716825220) is unknown, I assume he somehow found the absolute path to the datastore itself, and not the datastore path of the .iso file... which I have not been able to find through govc commands.

**Additional context**

N/A

**Comment by Goose29** [comment]
Alternatively, maybe introduce a way to use .iso files from a content library through the `library.deploy` command.

**Comment by dougm** [comment]
Next release will include support for using a `library:` URL, see examples:
https://github.com/vmware/govmomi/blob/main/govc/USAGE.md#devicecdrominsert
https://github.com/vmware/govmomi/blob/main/govc/USAGE.md#vmcreate

This library: URL is resolved using the same code as `library.info -l -L`. But removed the insert example from the doc there:
https://github.com/vmware/govmomi/blob/main/govc/USAGE.md#libraryinfo

The issue you had earlier was likely vm and CL on different datastores (need `-l` to include the datastore)
