### ISSUE TITLE
[BUG] device.info Name / Type not camelCase

### ISSUE THREAD

**Issue by xarem** [vmware/govmomi#3241]
## Description
In v0.31.0, govmomi made big steps into using camelCase, we're currently updating our application to reflect this. We tried to put our findings in separate issues (#3241, #3242, #3243) because not every issue may be a bug.

We found some exceptions in the API, in `device.info` are still some keys (`Name`, `Type`) PascalCased. 

## Steps to reproduce
```
vcsim -api-version 8.0 -dc 0 -l :8989 &
export GOVC_URL=https://user:pass@172.17.0.2:8989/sdk GOVC_SIM_PID=10
export GOVC_INSECURE=true

govc datacenter.create test-dc
govc cluster.create test-cluster
govc cluster.add -hostname test-host -username user -password pass -noverify
govc datastore.create -type local -name test-ds -path /tmp 'test-cluster/*'
govc vm.create -net="VM Network" -m=4096 -c=1 -g=ubuntu -disk=40G -folder=/test-dc/vm test-vm
govc device.info -json -vm test-vm | jq '.Devices[10]'
```

### Result
```json
{
  "Name": "ide-200",
  "Type": "VirtualIDEController",
  "key": 200,
  "deviceInfo": {
    "label": "IDE 0",
    "summary": "IDE 0"
  },
  "busNumber": 0
}
```

## Expected behavior
1. it should be `govc device.info -json -vm test-vm | jq '.devices[10]'` (`devices` camelCase)
2. expected output: 
```json
{
  "name": "ide-200",
  "type": "VirtualIDEController",
  "key": 200,
  "deviceInfo": {
    "label": "IDE 0",
    "summary": "IDE 0"
  },
  "busNumber": 0
}
```

## Affected version
v0.31.0

**Comment by DimitarStefanovMihov** [comment]
Hello, Mr. Xarem
I have started a discussion about ```import.spec ``` since I am not sure if I need to open a new issue - https://github.com/vmware/govmomi/discussions/3244 . I am almost certain that it is connected to the camelCase issue.
