### ISSUE TITLE
Verify Docker Login Github Action keeps failing

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#3251]
For several days, the Docker login verification keeps failing with `Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password`:
https://github.com/vmware/govmomi/actions/runs/6359122659/job/17271991050

This can lead to the next release workflow breaking since it's a step in the release process.

cc/ @dougm

**Comment by dougm** [comment]
Hi @embano1 !  Thanks, we're aware and in the process of fixing. cc @markpeek @akutz
