### ISSUE TITLE
[BUG] eventing for dvs creation does not work

### ISSUE THREAD

**Issue by richardings** [vmware/govmomi#3263]
**Describe the bug**
When using govc to create a dvs on vcsim (for example. `govc dvs.create test_dvs`), no event is posted.
Creating VMs works as expected.

**To Reproduce**

1. create dvs via govc
2. no events show up when polling the eventing infra

**Expected behavior**

We should get events when DVS objects are created and modified.

**Affected version**
vcsim 0.32.0

**Screenshots/Debug Output**

**Additional context**
This might be a feature request... not a bug
I haven't tested this on other versions

**Comment by dougm** [comment]
```console
% govc dvs.create test_dvs
[02-11-23 07:57:43] adding test_dvs to folder /DC0/network... OK
% govc events
[Thu Nov  2 07:57:43 2023] [info] Task: Create a vSphere Distributed Switch (target=Folder network)
[Thu Nov  2 07:57:43 2023] [info] dvPort group test_dvs-DVUplinks-39 in DC0 was added to switch test_dvs.
[Thu Nov  2 07:57:43 2023] [info] A vSphere Distributed Switch test_dvs was created in DC0.
% govc about | grep FullName
FullName:     VMware vCenter Server 7.0.3 build-21958406
```

Or are you referring to vcsim rather than a real vCenter?

**Comment by richardings** [comment]
Sorry that I wasn't clear Doug

This is in reference to vcsim.
I will update the bug

**Comment by dougm** [comment]
np @richardings , thought that might be the case. #3278 emits `DVPortgroupCreatedEvent` and `DvsCreatedEvent`
Were there other related events you need that are missing?

**Comment by richardings** [comment]
Thanks for the fast fix @dougm !

I wrote up another related bug a little while ago related to linkDiscoveryProtocolConfig [#3264](https://github.com/vmware/govmomi/issues/3264)

The lldp config is always unset in the object.
This is probably related?
