### ISSUE TITLE
[BUG] investigate if the vCenter simulated by vcsim is acessible with any credentials

### ISSUE THREAD

**Issue by ivansantiagojr** [vmware/govmomi#3266]
When using the simulated vCenter generated by vcsim, connecting to the given URL with any credentials is possible.

**To Reproduce**

Running the vcsim command:
```
$ vcsim -vm 1
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=8665
````

Consulting the vcenter with govc command line:
```
$ export GOVC_URL=https://user:blablablabla@127.0.0.1:8989/sdk GOVC_SIM_PID=8665
$ govc find -l -k
Folder                       /
Datacenter                   /DC0
Folder                       /DC0/vm
VirtualMachine               /DC0/vm/DC0_H0_VM0
VirtualMachine               /DC0/vm/DC0_C0_RP0_VM0
Folder                       /DC0/host
ComputeResource              /DC0/host/DC0_H0
HostSystem                   /DC0/host/DC0_H0/DC0_H0
ResourcePool                 /DC0/host/DC0_H0/Resources
ClusterComputeResource       /DC0/host/DC0_C0
HostSystem                   /DC0/host/DC0_C0/DC0_C0_H0
HostSystem                   /DC0/host/DC0_C0/DC0_C0_H1
HostSystem                   /DC0/host/DC0_C0/DC0_C0_H2
ResourcePool                 /DC0/host/DC0_C0/Resources
Folder                       /DC0/datastore
Datastore                    /DC0/datastore/LocalDS_0
Folder                       /DC0/network
Network                      /DC0/network/VM Network
DistributedVirtualSwitch     /DC0/network/DVS0
DistributedVirtualPortgroup  /DC0/network/DVS0-DVUplinks-9
DistributedVirtualPortgroup  /DC0/network/DC0_DVPG0
```

**Expected behavior**
When using the wrong credentials, I would expect an error to be returned, this way I could write better tests to my other scripts.

**Additional context**
I also tried consulting the vcsim vCenter with pyVmomi using wrong credentials, and it works as well. Check the screenshot:
![image](https://github.com/vmware/govmomi/assets/65205079/050d73d8-2d2f-4065-a26f-d6f5f892da5c)

In both govc and pyVmomi examples you can see I used an unverified SSL Context, could that be related to the error? Or am I misusing the vcsim tool?

**Comment by dougm** [comment]
We should improve the docs on this use case, but it is possible:

```console
% vcsim -h
...
 -password string
    	Login password for vcsim (any password allowed by default)
...
  -username string
    	Login username for vcsim (any username allowed by default)
...
```
Tests using those flags here:
https://github.com/vmware/govmomi/blob/35b0fff9184dc7d7e0c7ef31c86242d138170f68/govc/test/vcsim.bats#L439

That includes use of `govc sso.user.create` to create additional users, as you'll also see in the test.
