### ISSUE TITLE
[BUG] Tag but no release

### ISSUE THREAD

**Issue by fliiiix** [vmware/govmomi#3274]
There is a tag for v0.33.1 but no release with assets.
Is that on purpose?

![image](https://github.com/vmware/govmomi/assets/1682954/238ad002-f8d2-45cb-832b-b2cb631b5ada)

![image](https://github.com/vmware/govmomi/assets/1682954/638e4ce4-5616-429a-ba27-c355a2be4ad7)

**Comment by dougm** [comment]
There's only [1 commit](https://github.com/vmware/govmomi/compare/v0.33.0...v0.33.1) in the release, which doesn't impact govc or vcsim. So we just did a git tag for [CAPV](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2467#issuecomment-1785925807)

We also have a [docker hub issue](https://github.com/vmware/govmomi/issues/3251) that hasn't been resolved yet, the workaround around for which wasn't worth the trouble in this case.

**Comment by fliiiix** [comment]
fair enough :+1:
