### ISSUE TITLE
No packed releases for govc 0.33.1 in repo, only sources (zip/tgz) available

### ISSUE THREAD

**Issue by Gnanf** [vmware/govmomi#3300]
Hi, govc 0.33.1 is tagged as the latest version here (https://github.com/vmware/govmomi/releases/tag/v0.33.1) but there are only the sources (zip,tgz) in this repo and not the additional packed versions or precompiled files for different operating systems. This is going on now for about 4 weeks and breaks up automation, so we had to pin the govc version to 0.33.0. And I think others will be affected too.
Are these circumstances known? 
And will there be packed releases for govc 0.33.1 for different operating systems and when will packages be published?

Thanks a lot in advance!

**Comment by dougm** [comment]
Hi @Gnanf , see: https://github.com/vmware/govmomi/issues/3274
Was not aware this would impact others, will try to avoid in the future.

**Comment by Gnanf** [comment]
Hi dougm,
thanks for your explanation. But is there a timeline for a new release in the nearer future so we (and I think other too) can un-lock automation pipelines that are pinned to 0.33.0 now, to get newest releases automatically without observing github day by day? I suspect it will take some time until the [docker hub issue](https://github.com/vmware/govmomi/issues/3251) is solved
To understand our concern, the use of latest versions is a management requirement.

Thanks a lot in advance!

**Comment by dougm** [comment]
Understood @Gnanf , new release is available: https://github.com/vmware/govmomi/releases/tag/v0.34.0

**Comment by Gnanf** [comment]
Hi dougm,
thanks a lot for the new release!
