### ISSUE TITLE
[BUG] Missing Tags attribute on tag association unmarshall

### ISSUE THREAD

**Issue by bkmeneguello** [vmware/govmomi#3320]
**Describe the bug**

When unmarshalling a JSON with `AttachedTags` structure, the `Tags` attributes are empty.

**To Reproduce**

Write a JSON with:
```
{
    "_typeName": "AttachedTags",
    "object_id": {
        "_typeName": "AssociatedObject",
        "type": "VirtualMachine",
        "id": "vm-123"
    },
    "tag_ids": [
        "urn:vmomi:InventoryServiceTag:cc0eb57f-72e9-49fc-b11f-946e763af700:GLOBAL"
    ],
    "tags": [
        {
            "_typeName": "Tag",
            "id": "urn:vmomi:InventoryServiceTag:cc0eb57f-72e9-49fc-b11f-946e763af700:GLOBAL",
            "description": "Tag",
            "name": "Value",
            "category_id": "urn:vmomi:InventoryServiceCategory:cc0eb57f-72e9-49fc-b11f-946e763af700:GLOBAL"
        }
    ]
}
```
and try decoding into a `tags.AttachedTags`. The `Tags` attribute is empty.

**Expected behavior**

The `Tags` attribute should be populated.

**Affected version**

v0.34.1

**Additional context**

The following line is the culprit. The `Tags` is missing from the auxiliary struct:
https://github.com/vmware/govmomi/blob/a90161561f4e292e50cd8be8f4b83b3e0976a7f7/vapi/tags/tag_association.go#L331

**Comment by Enterprise2509** [comment]
Good afternoon! Tell me if I understood my difficulties correctly: the `ListTagsAttachedToVStorageObject ` method did not work properly for me - it gave out an empty number of tags, while three were linked. Has this error been fixed now?

Example:
```
AttachTagToVStorageObjectRequestType req;
req.this = GetServiceContent()->vStorageObjectManager;
ID ID;
ID.id = "urn:vmomi:VirtualMachine:vm-54088:3fe5b401-098a-4e8a-8e99-48e1d17be2c2";
req.id = &ID;
req.category = "urn:vmomi:InventoryServiceCategory:b8dd7f1b-caa5-4e9c-98bc-33b679e9f5f6:GLOBAL";
req.tag = "urn:vmomi:InventoryServiceTag:dd4f2f78-ec0b-4769-918b-c617f4e1fe5e:GLOBAL";

AttachTagToVStorageObjectResponse resp;
if(const std::exception& error = Call(&AttachTagToVStorageObject, &req, &resp))
{
   throw error;
}
```
