### ISSUE TITLE
[BUG] vm.network.add vmxnet3

### ISSUE THREAD

**Issue by malvsilva** [vmware/govmomi#3342]
Everytime that I try to use the vm.network.add with -net.adapter vmxnet3 don't work or gives error

I tried several ways:
govc vm.network.add -vm=$vm -net="VDS-NAME/NETWORK_NAME" "-net.adapter"=Vmxnet3
 > unknown ethernet card type '=Vmxnet3'

 govc vm.network.add -vm=$vm -net="VDS-NAME/NETWORK_NAME" -net.adapter=vmxnet3
 > network '.adapter=vmxnet3' not found

And a few more and it add always with E1000 adapter type

govc 0.34.0

Thanks for your help

**Comment by acsezen** [comment]
Have this Bug also.
/remove-lifecycle stale
