### ISSUE TITLE
[BUG] govc: ServerFaultCode: Length of HTTP request body exceeds configured maximum; 107013 > 100000

### ISSUE THREAD

**Issue by Mallkrawler** [vmware/govmomi#3348]
receive the following message when using govc to connect to my esxi instance. 

Command:
govc find -type m -u=https://govc:PASSWORD@ESXIHOST -k=true

Error:
govc: ServerFaultCode: Length of HTTP request body exceeds configured maximum; 107013 > 100000

**Comment by dougm** [comment]
@Mallkrawler can you try with the latest govc release? Possible this is fixed by #3408
If still an issue, can you share your build number?
```console
% govc about | grep FullName
FullName:     VMware vCenter Server 8.0.3 build-23933128
```
And please capture the request:
```
govc find -trace ... 2> trace.log
```
