### ISSUE TITLE
[BUG]  Help Page https://via.vmw.com/GJ98hk is not availbe / Govc 0.35.0

### ISSUE THREAD

**Issue by Muy69** [vmware/govmomi#3374]
**Describe the bug**
The URL https://via.vmw.com/GJ98hk in the latest Govc Version ( Windows ) is not avaible 

**To Reproduce**
If used https://via.vmw.com/GJ98hk you end up in a "Bad Gateway" 

**Expected behavior**
Some kind of working Help / URL

**Affected version**
[Release v0.35.0](https://github.com/vmware/govmomi/compare/v0.34.2...v0.35.0)

**Screenshots/Debug Output**
<img width="1174" alt="image" src="https://github.com/vmware/govmomi/assets/139373673/847003f1-817e-4cd1-ad2e-5b9f4db43ec0">

**Comment by dougm** [comment]
Did you check the Release page? https://github.com/vmware/govmomi/releases

**Comment by tenthirtyam** [comment]
This was related to an issue with the via.vmw.com URL redirect service.

**Comment by rdeavila** [comment]
Hi there!
This problem still happens, but now with a different error. I know this is not a problem with `govc`, but I don't know who is the responsible for this redirect service.
![image](https://github.com/user-attachments/assets/97b29065-c6ba-43cf-887d-3803eff4e8aa)

**Comment by Muy69** [comment]
Its not working for me too , maybe @tenthirtyam give us a direction how to use it correctly ?

**Comment by tenthirtyam** [comment]
The URL shortener service was disabled by Broadcom. If present in the latest release, please open a new issue with information on where this is seen in govc.

**Comment by rdeavila** [comment]
Thanks! But I don't know what URL this shortened address is supposed to redirect to. Does anyone know where it goes?

**Comment by tenthirtyam** [comment]
Based on the context: https://github.com/vmware/govmomi/blob/main/govc/USAGE.md

**Comment by tenthirtyam** [comment]
Resolved in #3583.
