### ISSUE TITLE
[BUG] Fail to create a new VM using PowerCLI integration

### ISSUE THREAD

**Issue by radumgd** [vmware/govmomi#3422]
Hi!

I want to test an automatic deployment of a VM, I can receive data from the inventory, but when I try to create a new one I get a non logical error, saying that  "The valid range for VM memory size is between 4 MB and 0 MB".

PS C:\Users\Administrator> New-VM -Name "TestVM" -VMHost "DC0_H0" -Datastore "LocalDS_0" -MemoryMB 1024 -NumCpu 2 -NetworkName "VM Network" -DiskMB 20000
New-VM : 4/23/2024 9:42:52 AM   New-VM          The valid range for VM memory size is between 4 MB and 0 MB.
At line:1 char:1
+ New-VM -Name "TestVM" -VMHost "DC0_H0" -Datastore "LocalDS_0" -Memory ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-VM], InvalidArgument
    + FullyQualifiedErrorId : ViCore_VMServiceImpl_TryValidateVmMemorySize_InvalidMemorySize,VMware.VimAutomation.ViCore.Cmdlets.Comma
   nds.NewVM

I would appreciate your feedback, maybe there is a workaround that I can apply to get it working.

Regards!

**Comment by tenthirtyam** [comment]
Closing this issue as it's not related to `vmware/govmomi`.
