### ISSUE TITLE
reflect.Set: value of type int32 is not assignable to type int 

### ISSUE THREAD

**Issue by runner-mei** [vmware/govmomi#344]
reflect.Set: value of type int32 is not assignable to type int    c:/go/src/runtime/asm_amd64.s:437 runtime.call32
                    c:/go/src/runtime/panic.go:423 runtime.gopanic
                    c:/go/src/reflect/value.go:2158 reflect.Value.assignTo
                    c:/go/src/reflect/value.go:1327 reflect.Value.Set
                    D:/developing/go/3td/src/github.com/vmware/govmomi/vim25/mo/type_info.go:197 github.com/vmware/govmomi/vim25/mo.assignValue
                    D:/developing/go/3td/src/github.com/vmware/govmomi/vim25/mo/type_info.go:201 github.com/vmware/govmomi/vim25/mo.assignValue
                    D:/developing/go/3td/src/github.com/vmware/govmomi/vim25/mo/type_info.go:201 github.com/vmware/govmomi/vim25/mo.assignValue
                    D:/developing/go/3td/src/github.com/vmware/govmomi/vim25/mo/type_info.go:235 github.com/vmware/govmomi/vim25/mo.(*typeInfo).LoadFromObjectContent
                    D:/developing/go/3td/src/github.com/vmware/govmomi/vim25/mo/retrieve.go:57 github.com/vmware/govmomi/vim25/mo.ObjectContentToType
                    D:/developing/go/3td/src/github.com/vmware/govmomi/vim25/mo/retrieve.go:99 github.com/vmware/govmomi/vim25/mo.LoadRetrievePropertiesResponse

                    D:/developing/go/3td/src/github.com/vmware/govmomi/property/collector.go:167 github.com/vmware/govmomi/property.(*Collector).Retrieve
                    D:/developing/go/3td/src/github.com/vmware/govmomi/property/collector.go:173 github.com/vmware/govmomi/property.(*Collector).RetrieveOne
                    d:/developing/go/3td/src/github.com/vmware/govmomi/client.go:120 github.com/vmware/govmomi.(*Client).RetrieveOne

**Comment by pietern** [comment]
Can you provide some more information? What type of object are you trying to retrieve?

**Comment by dougm** [comment]
@runner-mei any further info on this?

**Comment by afirouzma** [comment]
I faced the same error while trying to retrieve the number of CPUs:
`	this.Client.Retrieve(this.Client.Context, []types.ManagedObjectReference{virtualMachineObject.Reference()},
		[]string{
			"config.hardware.numCPU",
			"config.hardware.memoryMB",
			"guest.net",
			"summary.config.guestFullName",
			"config.hardware.device",
		},
		&vm)`
