### ISSUE TITLE
SSL error "x509: negative serial number"

### ISSUE THREAD

**Issue by dillten** [vmware/govmomi#345]
I think I already know the answer to this, but I'll put it out here for comment.

There is an issue, golang/go#8265 that references [this section](https://github.com/golang/go/blob/7360638da09bed30bb32c183c9264f7f9f0bb8c9/src/crypto/x509/x509.go#L912) of the x509 code. The certificates generated by vCenter (non-appliance versions) seem to have the negative serials referenced in the issue.

Some folks have worked around this by applying fix (see zmap/zgrab@a3d044e), but I was curious as to if this project intends to apply a workaround (or option of one).

**Comment by pietern** [comment]
I was unaware of this issue. Where/how did you generate these certificates? If it is possible to generate new ones that don't have this issue that clearly is preferable over importing the standard library's x509 and subsequently ssl/http packages...

**Comment by dpmitchell** [comment]
I'm also seeing this issue on a Self Signed cert from vSphere. I have no control to generate a new one:

Error: Post https://ldnwvvcent01/sdk: tls: failed to parse certificate from server: x509: negative serial number

Going to attempt the fix, just replying for visibility.

**Comment by dpmitchell** [comment]
Hello,

For those that need a workaround. We simply configured an apache proxy in front of vSphere to handle this problem. 

It's all working now.

**Comment by duesee** [comment]
I also wanted to leave a comment here, since this "issue" is not resolved yet.

We are working on a large set of x509 certificates and found approximately 100000 certificates with a negative serial number -- all of them which can't be processed due to this issue.

Quoting RFC5280, again: "Certificate users SHOULD be prepared to gracefully handle (...) certificates (with a negative serial number)"

So, when we become prepared? As far as I understand the other comments this is not a technical problem, but rather a conflict of opinions?

**Comment by pietern** [comment]
@duesee We're really at mercy of the standard library here. I don't want us to maintain a copy of the x509 package just to fix this issue. Could you leave a comment in golang/go#8265 to confirm you're seeing this issue as well? Looks like they're looking for more instances of this problem before fixing it.

**Comment by pietern** [comment]
This was merged and is lined up for release in Go 1.6. Good news :)

https://go-review.googlesource.com/#/c/17247/

Closing this issue.

**Comment by tkak** [comment]
Good news! Thanks :smile:

**Comment by InfoSec812** [comment]
Will there be a new release packaged using Go 1.6?

**Comment by dougm** [comment]
Released v0.4.0 built with go 1.6: https://github.com/vmware/govmomi/releases/tag/v0.4.0
