### ISSUE TITLE
Virtual Watchdog timer support

### ISSUE THREAD

**Issue by jmal22** [vmware/govmomi#3457]
In company i work in we use govc as an interface for managing our VMs in vSphere environment. For some use cases we need to add virtual watchdog timer (VWDT) to them. It seems that it is not possible with govc so far. I would appreciate if govc supported handling VWDT device for VMs.
So war we use vCenter web GUI for configuring the devices manually when needed. It requires some human effort that we want to avoid when possible.

**Comment by dougm** [comment]
Haven't used this before, can you describe some use-cases? Any pointers to docs/examples/ui screen-shots/etc would also be most helpful.

**Comment by jmal22** [comment]
Thank you very much for checking. We decided to use vSphere API directly for this task.
