### ISSUE TITLE
Add support for "High with Hyperthreading" option for latency_sensitivity

### ISSUE THREAD

**Issue by Guerckan** [vmware/govmomi#3468]
**Is your feature request related to a problem? Please describe.**
As introduced by vSphere 8.0, the "latency sensitivity" virtual machine setting now has a new possible value named "High with Hyperthreading".
See VMWare documentation supporting this statement : (https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-vm-administration/GUID-F5DAC793-7B13-418F-949E-0CD80CEC5D1E.html)

Current implementation in https://github.com/vmware/govmomi/blob/bf28314d9e3287ad1674f80d8a80d2245c0159ae/vim25/types/enum.go#L4846-L4881 does not support this new value and as such projects relying on this library cannot offer this new feature.

See https://github.com/hashicorp/terraform-provider-vsphere/issues/2169 as an example.

**Describe the solution you'd like**
I would like for the "LatencySensitivitySensitivityLevel" type string to support the new value "High with Hyperthreading".

**Describe alternatives you've considered**
Alternative solution right now is to settle for "High" but this setting is particularly interesting for network appliances virtual machines and the new functionality of "high with hyperthreading" offers a way to reduce the computing power footprint of a latency sensitivity "high" setting on the host without sacrificing much of its advantages.

**Additional context**
N/A

**Comment by dougm** [comment]
This enum, along with all the others in vim25, are generated from the [API spec](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.LatencySensitivity.SensitivityLevel.html) and are up-to-date with 8.0U3 in the latest govmomi release.

What is the value when you set this in the UI?
```console
% govc vm.info -json $vm_name | jq .virtualMachines[].config.latencySensitivity.level
"normal"
```

**Comment by datacore-pshetty** [comment]
Hi @Guerckan , Is there a way to change this simultaneousThreads property
I see we can get the property this way as you specified:
`$vm.ExtensionData.Config.Hardware.SimultaneousThreads`

**Comment by datacore-pshetty** [comment]
Thanks @Guerckan , I was able to do the ReconfigVM_Task() function on VM object and I see the "Threads per core" no more as 1.

But in the VM Settings, it still shows as "Normal". So physically the VM has the capability, but in the VM summary, it is not updated.

Thanks again.

**Comment by Guerckan** [comment]
In order for a VM to show-up as "High with HT" there are two pre-requisites :
 - First the "latency sensitivity" must be set to "High"
 - Second the "simultaneousThreads" property must be set to a value > 1.

When this is done the vSphere Console will show the VM as having a latency sensitivity of "High with HT".
Do keep in mind that this is only valid on a VM with hardware version >= 21 on a ESX 8.0+ host.

**Comment by datacore-pshetty** [comment]
Thanks @Guerckan , This worked.

After setting it as "High", I have to reduce the cpu reservation by around 2.

Also is there any upper limit on number of simulataneousThreads. I could not set it to any number above 2, even though I support 40CPU ESXi.

**Comment by Guerckan** [comment]
Your question made me research the subject a little more.

SimultaneousThreads is actually supposed to be set to 1 or 2.
And the number of vCPUs your VM has must be a multiple of simultaneousthreads value.
