### ISSUE TITLE
[BUG] govc 0.37.3 datastore.create cannot add nfs41 storage

### ISSUE THREAD

**Issue by redhat-demo** [vmware/govmomi#3471]
**Describe the bug**
hello
I want to use govc datastore.create to add a nfs v4.1 datastore into a vcenter cluster
I have confirm that storage is worked because i use vcenter web console to add successfully

**To Reproduce**

My NFS Server is 192.168.12.11
My NFS Path is /data/nfs/vsphere
My ESXi Host is 192.168.12.21

the full command line as following: 

govc datastore.create \
  -type NFS41 \
  -name datastore-nfs \
  -remote-host 192.168.12.11 \
  -remote-path /data/nfs/vsphere \
  192.168.12.21

but this command line get a error:
govc: /Datacenter-1/host/Cluster-1/192.168.12.21: ServerFaultCode: A specified parameter was not correct:

there are some cluster information as following

govc ls /Datacenter-1/host/Cluster-1
/Datacenter-1/host/Cluster-1/Resources
/Datacenter-1/host/Cluster-1/VM Network
/Datacenter-1/host/Cluster-1/192.168.12.22
/Datacenter-1/host/Cluster-1/192.168.12.21

**Expected behavior**
Add a NFS v4 datastore into vCenter Cluster and ESXi hosts

**Affected version**
govc version
govc 0.37.3

I have also tried govc 0.37.2, the issue was same

**Comment by dougm** [comment]
The command hasn't been changed in 4+ years, I'm not able to reproduce. Are you able to add it from GUI?
Can you add the `-trace` flag and check the output for more details.
You can also check ESX host logs `govc logs -host 192.168.12.21`
