### ISSUE TITLE
[BUG] Didn't find way to expand datastore capacity

### ISSUE THREAD

**Issue by HaruChebrolu** [vmware/govmomi#3490]
**Describe the bug**
I was unable to find a way to expand datastore capacity using govc. Please let me know if we have govc command to expand or reduce the size of datastore.

**Comment by dougm** [comment]
We don't have that in govc. Sounds like [expandVmfsDatastore](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.host.DatastoreSystem.html#expandVmfsDatastore) or [extendVmfsDatastore](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.host.DatastoreSystem.html#extendVmfsDatastore) could be used and we have the generated govmomi methods. Don't know about reducing.

**Comment by HaruChebrolu** [comment]
When can we expect to include the change on  (https://github.com/vmware/govmomi/commit/3139de3295843e0a96665694b52aa33e45147834) into a new release.

**Comment by dougm** [comment]
@HaruChebrolu your original question was on "expand datastore capacity". But based on your last comment it sounds like you're asking about vmdk capacity, rather than the datastore itself, is that right?
https://github.com/vmware/govmomi/commit/3139de3295843e0a96665694b52aa33e45147834 is included in the 0.39 release.

**Comment by HaruChebrolu** [comment]
@dougm 
I am asking about increase Datastore capacity from created block devices.
<img width="1144" alt="Screenshot 2024-08-12 at 3 50 03 PM" src="https://github.com/user-attachments/assets/9e0108f1-e7ef-4c7a-a64d-922c54eb8c4a">
