### ISSUE TITLE
Unexported unit Field in performance.MetricSeries Struct

### ISSUE THREAD

**Issue by aneesurrehman001** [vmware/govmomi#3494]
Hi,

I encountered an issue while working with the `performance.MetricSeries` type in the package. I noticed that the unit field is unexported, which prevents access to it outside of the package. 

Here's the relevant struct definition:

```
type MetricSeries struct {
    Name     string `json:"name"`
    unit     string
    Instance string  `json:"instance"`
    Value    []int64 `json:"value"`
}
```

Is this design intentional, or could it be considered a bug? Accessing the unit of each metric directly from MetricSeries instances would be very useful for my application. Could you please clarify whether this is by design or if it might be adjusted in future releases?

Thank you!

**Comment by dougm** [comment]
I can't recall why we didn't export it, but don't see a problem with doing so. Do you want to open a PR with that change?

**Comment by aneesurrehman001** [comment]
Sure
