### ISSUE TITLE
govc support for dual-stack vmk with host.vnic.info

### ISSUE THREAD

**Issue by jhg03a** [vmware/govmomi#3495]
**Is your feature request related to a problem? Please describe.**
I'd like to retrieve all the IPs in use for a given host using govc.  When I use the normal `host.vnic.info` command, I only receive the IPv4 address on a dual stack host back.

**Describe the solution you'd like**
I'd like to see the existing `IP address` field support a comma separated list of both IPs if applicable.

**Comment by Alexe1996** [comment]
*******
