### ISSUE TITLE
Implement SessionManager.ImpersonateUser().

### ISSUE THREAD

**Issue by Smithx10** [vmware/govmomi#3507]
It seems like ImpersonateUser() function is missing from SessionManager.

Implement SessionManager.ImpersonateUser().

https://vdc-download.vmware.com/vmwb-repository/dcr-public/8946c1b6-2861-4c12-a45f-f14ae0d3b1b9/a5b8094c-c222-4307-9399-3b606a04af55/vim.SessionManager.html#impersonateUser

**Comment by dougm** [comment]
@Smithx10 added in PR linked above
