### ISSUE TITLE
[BUG] How to provide a size when creating a datastore

### ISSUE THREAD

**Issue by HaruChebrolu** [vmware/govmomi#3519]
**Describe the bug**
I have a disk of size 200G, but I want to create a datastore using only 100G of it. For this, I can specify size while creating datastore. And I don't see an option to provide a size for [datastore.create command ](https://github.com/vmware/govmomi/blob/main/govc/USAGE.md#datastorecreate)

<img width="1158" alt="Screenshot 2024-08-12 at 1 28 27 PM" src="https://github.com/user-attachments/assets/7081ce72-234d-4115-9928-74fef70f348d">

**Comment by dougm** [comment]
Right, govc datastore.create does not provide that option. It uses [QueryVmfsDatastoreCreateOptions](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.host.DatastoreSystem.html#queryVmfsDatastoreCreateOptions) for the [VmfsDatastoreCreateSpec](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.host.VmfsDatastoreCreateSpec.html).
Enhancement PRs are welcome of course.

**Comment by HaruChebrolu** [comment]
Thanks for your quick response @dougm 
I am happy to contribute an enhancement PR. Just a question, inorder to add `datastoreSize` parameter, do I need to add it in VmfsdataStoreCreateSpec or QueryVmfsDatastoreCreateOptionsRequestType

**Comment by dougm** [comment]
Great. I suggest following the doc links above and expect it would be [VmfsDatastoreCreateSpec](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.host.VmfsDatastoreCreateSpec.html) input, but I don't know where. You could also try Developer Center -> Code Capture in vCenter, record the UI operation for your use-case and captured code may provide some hints. There might also be an existing example in another language, using pyvmomi or PowerShell, if so we can port what we need from such an example to Go.
