### ISSUE TITLE
PerfEntityMetric examples?

### ISSUE THREAD

**Issue by codekoala** [vmware/govmomi#352]
I've spent quite a bit of time trying to figure out how exactly to grab performance information from ESX hosts, but I haven't arrived at a complete solution yet. I feel like I'm very close, as in I've got a ``*types.PerfEntityMetric`` out of a call to ``methods.QueryPerf``. But the compiler won't let me build when I try to access the ``SampleInfo`` and/or ``Value`` fields.

I scratched together a gist with what I'm trying to do: https://gist.github.com/codekoala/1a10ed7071a8e50dfcc0

What I have right now is based on what I've already done with pyvmomi. I know it's possible! I think I only need some incantation in Go that I'm not yet familiar with.

Would it be possible to get some official examples for gathering performance metrics with govmomi?

**Comment by dougm** [comment]
We don't have any related examples yet, but I am planning to look at doing so in the near-ish future.

In your gist 'muck' an interface type types.BasePerfEntityMetricBase, you just need to assert *types.PerfEntityMetric like so:

fmt.Printf("SampleInfo: %+v\n", muck.(*types.PerfEntityMetric).SampleInfo)

**Comment by codekoala** [comment]
Thanks, that's exactly what I was missing. I knew it had to be something simple.

**Comment by pietern** [comment]
Cool!
