### ISSUE TITLE
Could govomi follow the freedesktop.org XDG Base Directory Specifications?

### ISSUE THREAD

**Issue by haydonryan** [vmware/govmomi#3532]
**Is your feature request related to a problem? Please describe.**
Govmomi creates a .govmomi directory in the home directory.  According to the freedesktop.org XDG spec this should be in the .config directory: https://specifications.freedesktop.org/basedir-spec/latest/

**Describe the solution you'd like**
 Config files in ~/.config

Data in ~/.local/share

Temp/Non-Essential files in ~/.cache. 

Would this be possible?

**Comment by dougm** [comment]
It is possible to set via env currently:
https://github.com/vmware/govmomi/blob/9090fda3e00bfecb3840eb08e3003f0084e4bd17/govc/flags/client.go#L83

Example:
```console
% export GOVMOMI_HOME=$HOME/.cache/govc
% govc about
...
% find $GOVMOMI_HOME
/home/dougm/.cache/govc
/home/dougm/.cache/govc/sessions
/home/dougm/.cache/govc/sessions/c50b949f61249852686b7597a79b470ceeb1b4b7
```

**Comment by haydonryan** [comment]
Ahh Thanks Doug :)
