### ISSUE TITLE
vSphere 6.x official support

### ISSUE THREAD

**Issue by chrislovecnm** [vmware/govmomi#356]
I am seeing that people are using this with vSphere 6, what is the status on it being officially supported?  Oh and @pietern been a long time since we talked amigo...

Oh and I would be happy to assist btw ...

Thanks

Chris

**Comment by tkak** [comment]
+1

**Comment by pietern** [comment]
@chrislovecnm @tkak Doug generated the vim25 package against the 6.0 API definition, so we should be good on all accounts :) Only thing remaining it mention it in the README (the changelog mentions it for the 0.2.0 release).
