### ISSUE TITLE
govc: automated testing in vSphere 6.0

### ISSUE THREAD

**Issue by higebu** [vmware/govmomi#358]
How to test govc in vSphere 6.0?
VCSIM doesn't work in VCSA 6.0.

**Comment by dougm** [comment]
Indeed.  We can stick with 5.5 for the moment for the VC bats tests, since we're not doing anything specific to 6.0 yet.  The ESXi bats tests work fine against 6.0.  I am hoping to spend some time on this, but may not be for another month or so.

**Comment by dougm** [comment]
We have [vcsim](https://github.com/vmware/govmomi/tree/master/vcsim) now.. not complete, but we can track enhancements as separate issues.
