### ISSUE TITLE
[BUG] some tests fail without docker on linux

### ISSUE THREAD

**Issue by asxe** [vmware/govmomi#3604]
**Describe the bug**
go test is failing on FreeBSD 13 ports repository. Execution of 'make test' is failing. The same results for Go 1.21 & 1.22 from Ports.

**To Reproduce**

1. cd sysutils/govmomi
2. make test

**Expected behavior**
test is PASSed. If platform is unsupported, skip test as unsupported.

**Affected version**
Tested on 0.45.1, 0.44.1, 0.33.0

**Screenshots/Debug Output**
Log is attached.
[govmimo-test.txt](https://github.com/user-attachments/files/17532658/govmimo-test.txt)

**Additional context**
Highly possible, the FAIL result is because Docker isn't well supported. Is any way to skip tests for unsupported platforms?

**Comment by dougm** [comment]
@asxe , yes these were docker related, added check so we skip without docker + linux

**Comment by asxe** [comment]
test is failing on 0.46.0 version.
Is any way to skip tests on unsupported operating systems?

```
--- PASS: Example_runContainer (0.33s)
FAIL
FAIL    github.com/vmware/govmomi/simulator     54.996s
```

**Comment by dougm** [comment]
> test is failing on 0.46.0 version. Is any way to skip tests on unsupported operating systems?
> 
> ```
> --- PASS: Example_runContainer (0.33s)
> FAIL
> FAIL    github.com/vmware/govmomi/simulator     54.996s
> ```

Was that the only output?

That example test should return early:
https://github.com/vmware/govmomi/blob/main/simulator/feature_test.go#L92

Unless run on linux with docker in PATH:
https://github.com/vmware/govmomi/blob/main/test/helper.go#L33-L41
