### ISSUE TITLE
[BUG] Unable to run govc disk.ls or govc disk.ls -R

### ISSUE THREAD

**Issue by jespinosaitrs** [vmware/govmomi#3639]
**Describe the bug**
I am unable to run `govc disk.ls` or `govc disk.ls -R`. Both fail with the same error:

```
$ govc disk.ls
govc: 0b5dfeb3-3b76-44c0-a183-6e082734eba5 not found: use 'disk.ls -R' to reconcile datastore inventory

$ govc disk.ls -R
govc: 0b5dfeb3-3b76-44c0-a183-6e082734eba5 not found: use 'disk.ls -R' to reconcile datastore inventory
```

**To Reproduce**

1. Run `govc disk.ls` or `govc disk-ls -R`.
1. Wait a few moments.
1. The error `govc: 0b5dfeb3-3b76-44c0-a183-6e082734eba5 not found: use 'disk.ls -R' to reconcile datastore inventory` is shown.

**Expected behavior**
The commands should finish without errors and display the disks or reconcile the disks.

**Affected version**
```
$ brew info govc
==> govc: stable 0.46.2 (bottled)
Command-line tool for VMware vSphere
```

**Screenshots/Debug Output**
```
types.RetrieveVStorageObject{
    This: types.ManagedObjectReference{Type:"VcenterVStorageObjectManager", Value:"VStorageObjectManager", ServerGUID:""},
    Id:   types.ID{
        Id: "0b5dfeb3-3b76-44c0-a183-6e082734eba5",
    },
    Datastore:     types.ManagedObjectReference{Type:"Datastore", Value:"datastore-24", ServerGUID:""},
    DiskInfoFlags: nil,
}
&soap.Fault{
    XMLName: xml.Name{Space:"http://schemas.xmlsoap.org/soap/envelope/", Local:"Fault"},
    Code:    "ServerFaultCode",
    String:  "The object or item referred to could not be found.",
    Detail:  struct { Fault types.AnyType "xml:\",any,typeattr\"" }{},
}
```

**Additional context**
There are two other identical issues in the repository that were marked as closed:

- https://github.com/vmware/govmomi/issues/2648
- https://github.com/vmware/govmomi/issues/3143

**Comment by tenthirtyam** [comment]
Please update the title from `"[BUG]"`, please.

**Comment by jespinosaitrs** [comment]
@tenthirtyam Sorry about that, I forgot to put something in it.

**Comment by dougm** [comment]
@jespinosaitrs what is your vCenter version? `govc about | grep FullName`

How are your disks created and managed, CNS Volumes or ?
iirc, there was a bug at some point (since fixed) with the `ReconcileDatastoreInventory` impl. We use that API with the disk.ls `-R` flag.

Either way, we can add a flag to change the error to warning and/or ignored as discussed here:
https://github.com/vmware/govmomi/issues/2648#issuecomment-1011834380

**Comment by dougm** [comment]
@jespinosaitrs please review https://github.com/vmware/govmomi/pull/3659
