### ISSUE TITLE
[BUG] govc: error parsing API version "9.0.0.0.rc1": strconv.Atoi: parsing "rc1": invalid syntax

### ISSUE THREAD

**Issue by yueclaireli** [vmware/govmomi#3643]
**Describe the bug**
Latest 9.0 version string is not supported.
```
$ govc  datastore.ls
govc: error parsing API version "9.0.0.0.rc1": strconv.Atoi: parsing "rc1": invalid syntax
```

**To Reproduce**

1. Deploy VC 9.0 latest build
2. Run govc command to retrieve vc info

**Expected behavior**
govc command completes successfully

**Affected version**
0.46.2

**Screenshots/Debug Output**
```
$ govc  datastore.ls
govc: error parsing API version "9.0.0.0.rc1": strconv.Atoi: parsing "rc1": invalid syntax
```

**Additional context**

**Comment by dougm** [comment]
Haven't seen such rc versioning before. You can disable this version check like so:
```
$ export GOVC_MIN_API_VERSION=-
```
