### ISSUE TITLE
`Error: ServerFaultCode: A specified parameter was not correct. url` when importing vmdk

### ISSUE THREAD

**Issue by jalev** [vmware/govmomi#371]
Hi all,

When I try to upload a VMDK, I get the following error:
```
govc import.vmdk -debug kube.vmdk ./kube/
[04-11-15 15:29:39] Uploading... OK
Error: ServerFaultCode: A specified parameter was not correct.
url
```

The last request from the debug logs are:
```
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><AcquireGenericServiceTicket xmlns="urn:vim25"><_this type="SessionManager">SessionManager</_this><spec xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="SessionManagerHttpServiceRequestSpec"><method>httpPut</method><url>https://10.0.0.11/folder/kube/kube-src.vmdk?dcPath=ha-datacenter&amp;dsName=DevnetVM1</url></spec></AcquireGenericServiceTicket></Body></Envelope>
````

My server is:
```
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        2646482
OS type:      linux-x64
API type:     VirtualCenter
API version:  5.5
Product ID:   vpx
UUID:         114DB37C-63F2-4A4B-A8C4-FB4AA63AE025
```
and the envvars I'm using are...

```
GOVC_NETWORK=10 Network
GOVC_INSECURE=1
GOVC_URL=someusername:somepassword@10.0.0.10
GOVC_DATACENTER=R&D
GOVC_DATASTORE=DNVM1
GOVC_RESOURCE_POOL=DN-C
GOVC_GUEST_LOGIN=kube:kube
```

**Comment by jalev** [comment]
So I just looked at the server that the request is being made to (.23) and noticed it's running on ESXi 5.1. I'm going to look into whether or not we can upgrade our ESXi to match our VSphere version. 

Could the fact we're using two different versions of VSphere/ESXi change the way `govc` is constructing the request?

**Comment by pietern** [comment]
@jalev The version mismatch could be the cause here.. Another thing that comes to mind: can you confirm the datastore is accessible on the target host? If not, that could explain the "specified parameter not being correct".

**Comment by seema-emc** [comment]
Hi Jalev,
Could you ever make it to work ? I have similar issue with similar configuration where ESXi is running 5.1.0 version but vCenter version is 5.5.0

**Comment by jalev** [comment]
Sorry @seema-emc, but I'm still having trouble. This is mainly due to still going through the motions of getting ESXi upgraded.

**Comment by seema-emc** [comment]
Thanks Jalev. I borrowed a ESX 5.5 with vCenter 5.5 and I could download the file without any issue. So it may be worth upgrading the ESX.

**Comment by jalev** [comment]
Thanks for your testing @seema-emc. 
I'll see if I can push this upgrade through on my side ASAP and double-confirm that the version-mismatch is the issue here.

**Comment by jalev** [comment]
Hi all, 

We've finally gotten version parity between our vSphere host and our ESXi host (5.5 for both). I could run the kubernetes `kube-up.sh` command without issue now.
