### ISSUE TITLE
writing and reading metadata to vm's via ExtraConfig

### ISSUE THREAD

**Issue by chrislovecnm** [vmware/govmomi#372]
Just a question on correct api entry points.  

Write:

`var ov []types.BaseOptionValue`
`VirtualMachineConfigSpec.ExtraConfig = ov`

where ov contains your extra config values

Read:
`mvm.Config.ExtraConfig`

where `mvm` is a VirtualMachine object

Having a bit of trouble debugging, and thought I would reach out.

**Comment by pietern** [comment]
@chrislovecnm Looks right to me. I take it you're using the reconfigure VM call?

What's the problem? You don't see values come back in the virtual machine object?

**Comment by chrislovecnm** [comment]
@pietern I am doing this on CreateVM not a reconfigure.  Do I need to reconfigure after the vm is up?

**Comment by chrislovecnm** [comment]
@pietern sorry I am cloning a template with the configSpec

**Comment by chrislovecnm** [comment]
@pietern do you have an integration test for extra configuration data?

**Comment by dougm** [comment]
We are only testing Reconfigure with extra config: https://github.com/vmware/govmomi/blob/master/govc/test/vm.bats#L203-L208

But we are using ExtraConfig in CreateVM in another project, works fine.

**Comment by chrislovecnm** [comment]
Thanks for the info.  My write was working, the read was not.
