### ISSUE TITLE
Question ~ Getting subnet mask from assigned vm ip address

### ISSUE THREAD

**Issue by chrislovecnm** [vmware/govmomi#377]
Any way to get the subnet mask for an ip address?

**Comment by pietern** [comment]
If tools is installed on the VM you can retrieve the guest information in the VM's managed object.

Then you can use the prefix length to compute the mask.

```
$ govc vm.info -json vcsa | jq .VirtualMachines[0].Guest.Net[0].IpConfig.IpAddress
[
  {
    "IpAddress": "10.20.128.218",
    "PrefixLength": 22,
    "Origin": "",
    "State": "preferred",
    "Lifetime": null
  }
]
```

**Comment by chrislovecnm** [comment]
:+1: Thanks amigo.

so in

    func CIDRMask(ones, bits int) IPMask

The `PrefixLength` is `ones`?

**Comment by pietern** [comment]
Yep, see: https://en.wikipedia.org/wiki/Subnetwork ;)

**Comment by chrislovecnm** [comment]
This is me doing a happy dance.  Have a great Thanksgiving!!

**Comment by pietern** [comment]
You too! :chicken: (for lack of a turkey emoji)
