### ISSUE TITLE
Add switch to specify protocol version in SOAPAction header

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#384]
We've twice had to hack a new protocol version into govmomi for use against pre-release code but this could also be useful for backwards compatibility testing.

**Comment by dougm** [comment]
Currently, the version is hardcoded in vim25/soap/client.go

```go
req.Header.Set(`SOAPAction`, `urn:vim25/6.0`)
```

We should add fields to the soap.Client struct used to compose this header value:

- Namespace (default to "urn:vim25")

- Revision (default to "6.0")

And to govc, '-vim-ns' and '-vim-rev' flags which can also be set via GOVC_VIM_NS and GOVC_VIM_REV environment variables.

**Comment by andrewtchin** [comment]
This issue can be closed :-)
