### ISSUE TITLE
Converting a VM to a template

### ISSUE THREAD

**Issue by abrianceau** [vmware/govmomi#388]
Hi,

I use govc to upload an OVA to my vSphere 5.5, but I want to import it as a template instead of a VM. I don't find any option to do this, and I don't find a tool, for example vm.change, to convert a VM to a template.

I saw in the library object/virtual_machine.go that the differenciation between VM and template is done, but does it is into govc ?

Thanks for your help.

**Comment by dougm** [comment]
We don't have that option currently in govc.  I haven't used templates or tested this, but maybe something like this would do the trick?  https://github.com/dougm/govmomi/commit/7fa670f9891e5d4e8d802e8f99c1ce5e00f10b8d
