### ISSUE TITLE
type types.BaseComputeResourceSummary has no field or method TotalCpu

### ISSUE THREAD

**Issue by kc11381** [vmware/govmomi#389]
HI,

I am trying to access TotalCpu on ComputeResource but I get 
"crs_mo.Summary.TotalCpu undefined (type types.BaseComputeResourceSummary has no field or method TotalCpu)"

Here is the code snippet:

var crs_mo mo.ComputeResource
if err = crs[i].Properties(context.TODO(), crs[i].Reference(),[]string{"summary",}, &crs_mo); err != nil {
          return err
}
log.Printf("Total CPU: %#v", crs_mo.Summary.TotalCpu)

Am I missing something or its a bug?
Thank you.

**Comment by dougm** [comment]
ComputeResource.Summary is an interface type.  This interface is implemented by types.ComputeResourceSummary and types.ClusterComputeResourceSummary, try:
```
crs_mo.Summary.GetComputeResourceSummary().TotalCpu
```

**Comment by chrislovecnm** [comment]
@kc11381 does this answer your question?

**Comment by kc11381** [comment]
Hi Dougm and Chris,

Thank you very much. Yes it solves my purpose hre.

**Comment by chrislovecnm** [comment]
:+1:
