### ISSUE TITLE
vmware_soap_session cookie not set

### ISSUE THREAD

**Issue by davidsiefert** [vmware/govmomi#394]
I'm trying to use the ```govc``` command line client.  I'm running into an issue where subsequent requests (after Login) are expecting a cookie ```vmware_soap_session``` to be set, and it is not done by the soap client.  I'm currently trying to figure a way to fix this, the code i'm in that appears to be problematic is:
vim25/soap/client.go:226

        req.Header.Set(`Content-Type`, `text/xml; charset="utf-8"`)
        req.Header.Set(`SOAPAction`, `urn:vim25/6.0`)

**Comment by pietern** [comment]
@davidsiefert This is strange, I have never heard of this before and use govc every day.

Which version are you using? Are you using a proxy? How do you know the cookie isn't set?

**Comment by davidsiefert** [comment]
i'm building off of master. govc about tells me:
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0

i'm currently communicating over an ssh tunnel to the vmware sdk system hosted on windows.
i know the cookie is not set because i can manually send SOAP requests with the cookie set and everything works.  the debug logs from govc show the cookie is not set.  and lastly, the code i'm looking atdoes not set the cookie when making soap requests.

**Comment by pietern** [comment]
The cookie is set implicitly by the login action. The HTTP client used by the SOAP client has a cookie jar that is updated if a response contains a `Set-Cookie` header. We're just piggybacking on the default behavior of Go's HTTP client.

Can you provide a debug log of a login action where you see this behavior (provided you can remove the sensitive information of course)? If so, you can send to pnoordhuis at vmware.

**Comment by davidsiefert** [comment]
interesting! i'm a go newb, did not know that. :smile:
i print the cookie jar before/after each soap request, and I do see in fact that cookie is being carried through, but for some reason not getting set on the outgoing headers.

the debug log shows:
1-0001.res:

    Set-Cookie: vmware_soap_session="***REDACTED***"; Path=/; HttpOnly; Secure;

1-0002.req:

    POST /sdk HTTP/1.1
    Host: localhost:8081
    Content-Type: text/xml; charset="utf-8"
    Soapaction: urn:vim25/6.0

i'm thinking it might have to do with the fact my ssh tunnel is listening on port 8081, and the cookie jar is only showing:

    &{?reflect.Value? {0 0} map[localhost:map[localhost;/;vmware_soap_session:{vmware_soap_session ****REDACTED**** localhost / true true false true {315537897599 0 0x1cd0f40} {63584763911 55449455 0x1cd9b40} {63584763911 409616255 0x1cd9b40} 0}]] 1}

**Comment by davidsiefert** [comment]
by "carried through" i mean the Set-Cookie is getting processed, cookie is set in the cookie jar, and then on the next request the cookie can be seen in the cookie-jar.  the problem is that it's not getting set on the request headers for whatever reason.

**Comment by pietern** [comment]
Ah, the cookie is set to only be sent over secure links. Are you terminating HTTPS on the remote side of the tunnel? If so, and the tunnel just talks unsecured HTTP, the cookie won't be set because it's not a secure link from the perspective of the client.

**Comment by davidsiefert** [comment]
okay that makes sense, my ssh tunnel is working over the 81 port for insecure access.... trying to figure out what ssl port we have on our server so i can tunnel straight to that port instead...

**Comment by davidsiefert** [comment]
:boom::boom::boom::boom::boom::boom::boom::boom::boom::boom::boom::boom::boom::boom:
@pietern you are the man!  Thanks dude!  Not an issue.  Closing!

**Comment by pietern** [comment]
@davidsiefert Happy to help out! :)
