### ISSUE TITLE
Guest.Net does not contain vm ip address(s)

### ISSUE THREAD

**Issue by chrislovecnm** [vmware/govmomi#405]
We are having a challenge getting Guest.Net back with the correct ip addresses.  This code is for terraform provider, and we could use some guidance.

One line https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L448 we are retreiving a vm's information, and are requesting `guest`.  Unfortunately `Guest.Net` is not containing valid ip address / nic information.

If we do a `ip, err := vm.WaitForIP(context.TODO())` we are able to get an ip back and populate it.  Any advice?

Here is the issue https://github.com/hashicorp/terraform/issues/4112, and here is a PR request with the wait https://github.com/hashicorp/terraform/pull/4283.  Should we do a `WaitForIP` before getting the info back?

@tkak @ryanl-ee @jen20 @phinze did I miss anything?

**Comment by pietern** [comment]
Hey Chris, first thing that comes to mind: is the booted all the way (i.e. not 1s after power on)?

WaitForIP is a blocking call: it will wait until is HAS an IP to give back. The call to retrieve properties doesn't wait for anything. So if the machine isn't booted up all the way, then it will return some nils. You could try prefixing the properties call with a WaitForIP call so you know the machine is booted and has its network setup.

**Comment by ryanl-ee** [comment]
@chrislovecnm Nope, that's about it. pietern's explanation makes sense to me. Thank you for doing the research!

**Comment by chrislovecnm** [comment]
We can thank @pietern ;) I added comments on the pull request.

I would like to keep this open till we resolve it on our end.
