### ISSUE TITLE
Add device : invalid configuration for device '0' 

### ISSUE THREAD

**Issue by seema-emc** [vmware/govmomi#409]
When I try to create a virtual disk on a VM for a scsi (0, 0) node, the operation fails with 
"invalid configuration for device '0' "

Since there was no disk on my VM there was no Virtual SCSI controller. I created the scsi controller using CreateSCSIController() and then used this controller to add a new disk. It picked scsi controller '0' and unit number '0' for the newly created virtual disk and it failed.

If I create a disk manually that uses scsi (0,0) port on the controller then subsequent Add disk will succeed because the scsi port that will be used is scsi(0,1) so basically unti number on the scsi controller is 1 here.

Any idea ?

**Comment by dougm** [comment]
Do you have some example code to reproduce?

**Comment by dougm** [comment]
Feel free to reopen with example code to reproduce.

**Comment by mspaulding06** [comment]
I am having a similar problem with the library.  From the documentation and examples it's not clear if there is something I am doing wrong.  In the below example I iterate through devices looking for an existing device with `diskLabel` and then use that information to use the same backing store for the new disk that I want to attach.  I could not find a better way to handle this.  I use a similar technique when extending an existing disk and this works fine.  It is only when attempting to add a disk that I get this failure.

```go
func (v *VirtualMachine) AddDisk(diskLabel string, diskSize string) error {
	diskSizeKB, err := convertSize(diskSize, UnitsKB)
	if err != nil {
		return err
	}
	deviceList, err := v.object.Device(v.ctx)
	if err != nil {
		return err
	}
	diskList := deviceList.SelectByType(&types.VirtualDisk{})
	if len(diskList) < 1 {
		return fmt.Errorf("no disks found attached to VM")
	}
	found := false
	for _, disk := range diskList {
		label := disk.GetVirtualDevice().DeviceInfo.GetDescription().Label
		if label == diskLabel {
			found = true
			virtDisk := disk.(*types.VirtualDisk)
			backing := virtDisk.Backing
			dataStore := strings.Split(backing.(*types.VirtualDiskFlatVer2BackingInfo).FileName, " ")[0]
			backing.(*types.VirtualDiskFlatVer2BackingInfo).FileName = dataStore
			spec := types.VirtualMachineConfigSpec{
				DeviceChange: []types.BaseVirtualDeviceConfigSpec{
					&types.VirtualDeviceConfigSpec{
						FileOperation: types.VirtualDeviceConfigSpecFileOperationCreate,
						Operation:     types.VirtualDeviceConfigSpecOperationAdd,
						Device: &types.VirtualDisk{
							CapacityInKB: diskSizeKB,
							VirtualDevice: types.VirtualDevice{
								Key:        0,
								UnitNumber: new(int32),
								Backing:    backing,
							},
						},
					},
				},
			}
			task, err := v.object.Reconfigure(v.ctx, spec)
			if err != nil {
				return err
			}
			task.Wait(v.ctx)
			return nil
		}
	}
	if !found {
		return fmt.Errorf("no disk found to resize")
	}
	return nil
}
```

**Comment by seema-emc** [comment]
As far as I debugged, the reason of this error is the unit number that is 0.  If unit number is 0, it is skipped from the WSDL that is sent to VMware for adding the device and VMWare does not like it.  I believe if you specify any valid UnitNumber than 0 it should be successful.

**Comment by dougm** [comment]
@seema-emc what version of gomvomi are you using?  We fixed the UnitNumber issue about a year ago in e077bcf - so the value always sent, even when it is '0'.

**Comment by mspaulding06** [comment]
It doesn't seem to matter which value is passed as the UnitNumber or if it is passed at all.  It fails every time.  Is there anything else wrong with the configuration that I am passing?

**Comment by dougm** [comment]
@mspaulding06 looks like yours is a different issue, only the generic error message is the same.  I believe you'd need to either use OperationEdit or remove the old device, as you can't have the .vmdk backing for multiple devices.  It is possible for multiple disk devices to have the same parent .vmdk (linked clones), but the device backing needs to be a delta disk.

**Comment by nilsanderselde** [comment]
@dougm I'm opening a new issue for what I think might be the same problem described by the creator of this incident because I can't reopen this one.
https://github.com/vmware/govmomi/issues/2718
