### ISSUE TITLE
Guest Name is not correct

### ISSUE THREAD

**Issue by liboshi** [vmware/govmomi#436]
Hi,

Recently, I used govc (govc is the latest development version, I used go get to fetch it.) to get vm information with following command:
`govc vm.info $vm_name`
got following output:
> Name:           A-W7-32
>   Path:         /ha-datacenter/vm/A-W7-32
>   UUID:         <hidden>
>   Guest name:   Microsoft Windows 7 (64-bit)
>   Memory:       1500MB
>   CPU:          4 vCPU(s)
>   Power state:  poweredOn
>   Boot time:    2016-02-01 15:12:56.882496 +0000 UTC
>   IP address:   10.117.41.207

you can see the Guest name show (64-bit), but my vm is 32-bit.

-Boush

**Comment by dougm** [comment]
The VM guest id is chosen by the user when the VM is created, govc is simply reporting this value.  You can reconfigure the guest id with the following command:

```bash
govc vm.change -g windows7Guest -vm /ha-datacenter/vm/A-W7-32
```
