### ISSUE TITLE
Question - getting task IDs when performing tasks

### ISSUE THREAD

**Issue by robertlabrie** [vmware/govmomi#443]
Wasn't sure how best to word that. With PowerCLI, when you change a VM config or do a new VM or whatever, it returns a task ID that you can poll the status of. Using govmomi, if I do something like vm.AddDevice(), it fires an async task but I don't know how to get the ID to wait for it to complete.

Unrelated, do you guys have a Google group for this project or something, I feel a little silly using an issue to ask a question.

Thanks,
Rob

**Comment by dougm** [comment]
Sorry for the delayed response.  You can call methods.ReconfigVM_Task directly in this case.  Other wrappers do return a Task type, and govc uses the Task to render progress in several commands.

We don't have a Google group, but would be open to that.  In the meantime, feel free to re-open this and/or other issues.
