### ISSUE TITLE
VirtualMachineFileLayoutExFileInfo shows different size then WebUi

### ISSUE THREAD

**Issue by tpostument** [vmware/govmomi#447]
Hello,
I'm trying to get size of Disk files from VMware server with the next code:

```
for _, file := range vm.LayoutEx.File {
    fmt.Println(file)
}
```

and getting next output:

```
{{} 0 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test.vmx config 2720 2720  0xc20819f86a}
{{} 1 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test.nvram nvram 8684 8684  0xc20819fa8a}
{{} 2 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test.vmsd snapshotList 0 0  0xc20819fbc9}
{{} 3 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test_1.vmdk diskDescriptor 0 0  0xc20819fd49}
{{} 4 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test_1-flat.vmdk diskExtent 1073741824 1073741824  0xc20819fef8}
{{} 5 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test.vmdk diskDescriptor 0 0  0xc208152339}
{{} 6 [datastore1] Ubuntu 14.04 import test/Ubuntu 14.04 import test-flat.vmdk diskExtent 4075814912 4075814912  0xc208152528}
{{} 7 [datastore1] Ubuntu 14.04 import test/vmware-1.log log 658435 658435  0xc208152a5a}
{{} 8 [datastore1] Ubuntu 14.04 import test/vmware.log log 192022 192022  0xc208152c4a}
```

while on the Web-UI I can see different size of the biggest file:
![ubuntu_size](https://cloud.githubusercontent.com/assets/16758615/13016337/c7d4f980-d1c6-11e5-82c8-565604fb4b6b.png)

Most files show the same size, but file _Ubuntu 14.04 import test-flat.vmdk_ size differs: 
**4075814912** vs **17179869184**

**Comment by CoolDuke** [comment]
I also encounter the problem when using SearchDatastoreSubFolders on a datastore. Running GetFileInfo() on a virtual disk file is returning the provisioned size instead of the real file usage in the datastore.

**Comment by CoolDuke** [comment]
After deeper research I found out that if you search a datastore with disabled FileType in the FileQueryFlags the received file sizes differ.

**Comment by kembo91** [comment]
Hi! Any progress on this issue?
I encountered the same thing 5 years later
