### ISSUE TITLE
Setting GOVC_PASSWORD and GOVC_USER won't work for me 

### ISSUE THREAD

**Issue by mreferre** [vmware/govmomi#450]
Hi. 

I am testing a few stuff and I found out that if I use the following variables: 

> export GOVC_PASSWORD=Vmware123!
> export GOVC_USER=administrator@vsphere.local
> export GOVC_INSECURE=1
> export GOVC_URL=192.168.1.12

I am not able to login properly. Example: 

>  govc ls
govc: ServerFaultCode: Cannot complete login due to an incorrect user name or password.

If I set instead the passwords as following, it does work: 

> export GOVC_URL='administrator@vsphere.local:Vmware123!@192.168.1.12'
> export GOVC_INSECURE=1

> govc ls
/Home/vm
/Home/network
/Home/host
/Home/datastore

Thoughts?

**Comment by dougm** [comment]
Try GOVC_USERNAME instead of GOVC_USER:

https://github.com/vmware/govmomi/tree/master/govc#usage
