### ISSUE TITLE
govc '-json' NoPermission error

### ISSUE THREAD

**Issue by remoe** [vmware/govmomi#452]
Hi

I use Win64 (master).

When I call: 
```bash
govc vm.info -json testvm
```

It throws:
```
NoPermission
```

But it works when I call:
```bash
govc vm.info testvm
```

It doesn't help when I use ```-persist-session=false```

**Comment by dougm** [comment]
Can you include version info: govc about
What permissions/role does your login have, Admin or limited?

**Comment by remoe** [comment]
govc about:

```shell
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        2001466
OS type:      win32-x64
API type:     VirtualCenter
API version:  5.5
Product ID:   vpx
```

**Comment by dougm** [comment]
vm.info -json works for me on Windows.  You could try adding the `-debug` flag and see if there is more detail in the xml response.  More info on looking at the debug output here:
https://github.com/vmware/govmomi/issues/470#issuecomment-198533439

Planning to implement something similar within govc, so we don't depend on bash/xmlformat.
