### ISSUE TITLE
how to Creating/Adding a Raw Device Mapping (RDM) to a Virtual Machine by govc

### ISSUE THREAD

**Issue by simsunny22** [vmware/govmomi#453]
i want find something about rdm from govc cli, but i can not find something about rdm, but only the command "vm.disk.attach"

so i type the command as below:
 "govc vm.disk.attach -dc=datacenter1 -ds=datastore1 -disk="/vmfs/devices/disks/naa.600605b009f43ac01ddcd5b50deca4c4" -vm=test-x1"

but i get the error :  "govc: Invalid configuration for device '0'."
so i want know there is some error with my command or govc can not support the rdm

**Comment by bastienbc** [comment]
Hi,

I've  made a pull request (#656) for that exact purpose.
You can use my branch rdmattachment temporary, it add two commands:

- vm.rdm.attach
- vm.rdm.ls

**Comment by dougm** [comment]
#656 is merged

**Comment by raghavanv90** [comment]
I have created rdm on vm1 and I am trying to attach rdm disk to second vm (shared across the host) . I am getting the below error as, 

govc vm.disk.attach -vm test-vm1 -disk test-vm1/shared.vmdk -link=false -sharing sharingNone
govc: Incompatible device backing specified for device '0'.

Could you please help me on this ?
