### ISSUE TITLE
govc: import.ova with -folder argument: folder argument does not resolve to object

### ISSUE THREAD

**Issue by ilackarms** [vmware/govmomi#455]
i have a folder that exists in my datastore, that i can view with 
```
govc datastore.ls
```
however when i run 
```
govc import.ova -json=true -k -u 'https://<u:p@ip>/sdk/' -folder='<my_folder>' -name=unik_id_1 './my.ova'
```
i have tried
```
govc import.ova -json=true -k -u 'https://<u:p@ip>/sdk/' -folder='<my_folder>' -name=unik_id_1 './my.ova'
govc import.ova -json=true -k -u 'https://<u:p@ip>/sdk/' -folder='[datastore1] <my_folder>' -name=unik_id_1 './my.ova'
govc import.ova -json=true -k -u 'https://<u:p@ip>/sdk/' -folder='/<my_folder>' -name=unik_id_1 './my.ova'
govc import.ova -json=true -k -u 'https://<u:p@ip>/sdk/' -folder='[datastore1]/<my_folder>' -name=unik_id_1 './my.ova'
```
none of which work.

i can view the contents of my folder with `datastore.ls <my_folder>`
I think the difference has to do with the way the DatastoreBrowser finds folders vs the way the find.Finder finds folders.

How can i properly specify the folder path so that the Finder can pick it up? Thank you

**Comment by dougm** [comment]
The folder param is an inventory folder, not a folder within the datastore itself.

See: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.ResourcePool.html#importVApp
