### ISSUE TITLE
unable to set network when using govc import.ova

### ISSUE THREAD

**Issue by thelangley** [vmware/govmomi#460]
I've used the `govc ls` command to work out the correct name of the network / host / cluster.

No matter how I do it, I cannot seem to get the import.ova to honour the network selection.

I always get 

`govc: Host did not have any virtual network defined.`

I'd really like it to be able to accept a `-net=blahblah` reference instead of using GOVC_NETWORK=

**Comment by tjim** [comment]
Running into the same issue. Would like to abandon ovftool (which has --net) in favor of govc but can't for this reason.

**Comment by tsugliani** [comment]
:+1:

**Comment by mehrotra-prateek** [comment]
+1 has this been fixed?

**Comment by srbry** [comment]
+1 has this got any progress?

**Comment by srbry** [comment]
Hi all, while it would be nice to have an option to provide a `-network` arg to this command their is a current work around that can be used using the `-options` arg.

You can provide network mappings in an `options.json` file like so:
```
{
  "NetworkMapping": [
    "Name":"<network_name>",
    "Network":"<port_group>"
  ]
}
```

And then run this to deploy your ova:
```
govc import.ova -options=options.json <ova_file_path>
```

You can also do a whole load of extra config using options but it is not well documented, to gather an example file with all the options for your specific ova you can run (for my ova this gave me my NetworkMapping Name that I used above):

```
govc import.spec <ova_file_path>
```

**Comment by dougm** [comment]
Yes, should be fixed by #546 and #549 cc @egorovv

**Comment by egorovv** [comment]
Yes, if the networks defined in the OVA are present in the the target DC it should just work now, and -options can provide the mapping for the rest.

**Comment by dougm** [comment]
Thanks @egorovv , would be great to capture some examples in the wiki and/or .md in the repo.

**Comment by koteswara-kelam** [comment]
even if i specify "myNetwork" which is DVS portgroup, the VM is getting deployed on "VM Network".
 # cat options.json
{
    "DiskProvisioning": "flat",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "InjectOvfEnv": false,
    "MarkAsTemplate": false,
    "Name": null,
    "NetworkMapping": [
        {
            "Name": "myNetwork",
            "Network": "myNetwork"
        }
    ],
    "PowerOn": false,
    "WaitForIP": false
}
# govc import.ova --options=options.json greenlake-centos-7-7-1579580585.ova
[21-01-20 11:28:57] Warning: Line 72: Invalid value 'bridged' for element 'Connection'.
[21-01-20 11:30:01] Uploading greenlake-centos-7-7-disk1.vmdk... OK

**Comment by koteswara-kelam** [comment]
it is working after changing "Name" to ova's network. Thanks @dougm  I didn't read your comment carefully.

**Comment by koteswara-kelam** [comment]
it is working after changing "Name" to ova's network. Thanks @dougm  I didn't read your comment carefully.
{
"Name": "bridged",
"Network": "myNetwork"
}
