### ISSUE TITLE
Retrieve Properties of multiple type of Managed Entities

### ISSUE THREAD

**Issue by cblomart** [vmware/govmomi#462]
I waa trying to get the name of a collection of HostSystem ans VirtualMachines.

i tried to use client.Retrieve but was denied by "object references must have the same type".
This commes from property/collector.go

Basically, it checks that all the object reference passed to the collector are of the same type.

Seems like an "exageration": the property collector can work for VirtualMachines and HostSystems. 

I copied the principle of the code and forced the object type to ManagedEntitites and it works fine.

Basicaly one should check that the destination object type hase the necessary fields to recieve the reauested properties and that the destionation type is assignable from the source object type.

Here, the ManageEntity type has the name attribute i am requesting and is implemented by HostSystem and VirtualMachine (and many other types naturaly).

**Comment by dougm** [comment]
You can use a dst param of pointer to `[]mo.ManagedEntity` or `[]types.ObjectContent` in this case.  Please re-open if this is still an issue for you.
