### ISSUE TITLE
Drone secrets management

### ISSUE THREAD

**Issue by jzt** [vmware/govmomi#475]
We need a centralized place for storage of the Drone secrets file.

Additionally, whenever .drone.yml is changed, the secrets file must be regenerated. I suspect this is why the builds have been failing since build 80: https://ci.vmware.run/vmware/govmomi/80

**Comment by eyz** [comment]
Sorry! ;)

**Comment by jzt** [comment]
Drone secrets file is located here:  https://docs.google.com/document/d/1ZDBnj__FVhWAwvQF8ZCUM7DmLcgRRuBtXR5BX1BFDTA

If you are in the VMware organization and need access to this file, contact me.
