### ISSUE TITLE
Pool destroy recursivity

### ISSUE THREAD

**Issue by cblomart** [vmware/govmomi#479]
Following documentation ManagedObject Destroy_Task and ResourcePool DestroyChilds are recursive.

A "recurse" flag would then not be needed by the pool.destroy command.

Additionnaly the tests "pool destroy" could be greatly simplified.

**Comment by dougm** [comment]
ResourcePool.Destroy deletes the children and the pool itself.
ResourcePool.DestroyChildren only deletes the children, **not** the pool itself.
However, `govc pool.destroy -r`  calls both DestroyChildren and Destroy, rendering the `-r` flag useless.  We could either remove the option or fix it so only DestroyChildren is called.  Renaming the flag may help too: `govc pool.destroy -children`

**Comment by cblomart** [comment]
Would you keep the flag for retro compatibility?

Blomart Cédric
Mobile: +32 497 41 89 05 | Mail: cblomart@gmail.com

Le 28 mars 2016 à 19:55, Doug MacEachern <notifications@github.com> a
écrit :

ResourcePool.Destroy deletes the children and the pool itself.
ResourcePool.DestroyChildren only deletes the children, *not* the pool
itself.
However, govc pool.destroy -r calls both DestroyChildren and Destroy,
rendering the -r flag useless. We could either remove the option or fix it
so only DestroyChildren is called. Renaming the flag may help too: govc
pool.destroy -children

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/vmware/govmomi/issues/479#issuecomment-202507559>

**Comment by dougm** [comment]
I suppose we could just leave the '-r' without renaming it, and just fix it to only call DestroyChildren without calling Destroy.

**Comment by cblomart** [comment]
#482

**Comment by cblomart** [comment]
Thanks.. i suppose the problem is resolved.

**Comment by dougm** [comment]
Indeed, thanks again @cblomart
