### ISSUE TITLE
Can't fetch vm info

### ISSUE THREAD

**Issue by EmilieXu** [vmware/govmomi#483]
Hi,

I have created several VMs on esxi server, but I can't pull the information of VMs.
when I specify vm.ip as vcenter IP, it works, as below.
$ ./govc vm.info -vm.ip=10.33.217.50
Name:           vCenter-Server-Appliance
  Path:         
  UUID:         564d5d7b-73e4-610b-7a56-de31310c9f32
  Guest name:   SUSE Linux Enterprise 11 (64-bit)
  Memory:       8192MB
  CPU:          2 vCPU(s)
  Power state:  poweredOn
  Boot time:    2016-03-22 17:55:31.830071 +0000 UTC
  IP address:   10.33.217.50

But when I specify vm.ip as other VMs, I got resnponse as no such VM, has anyone seen this problem before. I can ping the VM, the VM are created in vsphere client, and up and running.
But I can not get vm.info from govc

 $./govc vm.info -vm.ip=10.33.217.57
./govc: no such VM

**Comment by cblomart** [comment]
Are the vmware tools or open-vm-tools installed in the vms?

This is what allow communication between host and vm.

**Comment by EmilieXu** [comment]
Aha, I see, I forgot to install them, I will try that then, thanks a lot! :)
