### ISSUE TITLE
import.spec should not assume Deployment param always exists for OVA/OVFs

### ISSUE THREAD

**Issue by lamw** [vmware/govmomi#487]
It looks like the **import.spec** always assumes there's a **Deployment Type** param defined which is not always the case. This is something that needs to be inspected by parsing the OVF definition to see what options are available. 

The issue is that if you simply generate the spec and then modify just the OVF params and don't realize this, you'll get an fault when running import.ova command:

```
└─[0] <> govc import.ova -options=vesxi3.json /Volumes/Storage/Images/nested_esxi_appliance_v6.0u2.ova
govc: ServerFaultCode: A specified parameter was not correct: cisp.deploymentOption
```

Here's output of the import.spec:

```
└─[1] <> govc import.spec /Volumes/Storage/Images/nested_esxi_appliance_v6.0u2.ova | python -m json.tool
{
    "Deployment": "small",
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "InjectOvfEnv": false,
    "Name": null,
    "PowerOn": false,
    "PropertyMapping": [
        {
            "Key": "guestinfo.hostname",
            "Value": "esxi-1.primp-industries.com"
        },
        {
            "Key": "guestinfo.ipaddress",
            "Value": "192.168.1.190"
        },
        {
            "Key": "guestinfo.netmask",
            "Value": "255.255.255.0"
        },
        {
            "Key": "guestinfo.gateway",
            "Value": "192.168.1.1"
        },
        {
            "Key": "guestinfo.dns",
            "Value": "192.168.1.1"
        },
        {
            "Key": "guestinfo.domain",
            "Value": "primp-industries.com"
        },
        {
            "Key": "guestinfo.ntp",
            "Value": "192.168.1.1"
        },
        {
            "Key": "guestinfo.syslog",
            "Value": "192.168.1.150"
        },
        {
            "Key": "guestinfo.password",
            "Value": ""
        },
        {
            "Key": "guestinfo.ssh",
            "Value": "true"
        },
        {
            "Key": "guestinfo.createvmfs",
            "Value": "false"
        }
    ],
    "WaitForIP": false
}
```

Here's the OVA that I was using: https://bintray.com/artifact/download/photon-controller/esxi-appliances/nested_esxi_appliance_v6.0u2.ova

**Comment by lamw** [comment]
Forgot to add that **IPAllocationPolicy** & **IPProtocol** may also not be applicable and should be left out of the spec if it's not in the OVA/OVF

**Comment by cblomart** [comment]
Ok looking at the ovf file of vcsa i see an IpAssignmentSection (xml node) in the declared vmw namespace pointing to http://www.vmware.com/schema/ovf. But on the vmware website the url (hoping for a xsd)... but 404 :-(

I would have like to handle extra parameters properly before looking into adding networkmapping:
Adding them to the envelope definition (govomi/ovf/envelope.go).

Currently govc simply adds the mentionned options per default (apparently these comes more from vapp implementation). It doesn't even check if the ovf provides any insight.

PS: also an occasion to check how golang xml unmarshaling handles namespaces.

**Comment by srbry** [comment]
+1, had this issue today, used `import.spec` to generate an `options.json` but it was error when deploying my ova with `import.ova` until I deleted the `Deployment` key.

**Comment by rahulkj** [comment]
Ran into the same issue yesterday and turned out to be the `Deployment` key. Had to remove it to get the deployment going

**Comment by srinarayanant** [comment]
VMware-NSX-Manager-6.2.5-4818372.ova

**Comment by srinarayanant** [comment]
seems the bug is still there, happens for VMware-NSX-Manager-6.2.5-4818372.ova too
