### ISSUE TITLE
Feature Request - Reconfigure VM after OVF/OVA deploy, but prior to power on

### ISSUE THREAD

**Issue by lamw** [vmware/govmomi#490]
For OVF/OVA which require OVF parameters to be properly injected, it would be a nice feature to include as part o the import.ova that allows you to re-size the VM prior to powering on. Basic things like increase number of CPUs, memory and disk capacity. 

Today, the workflow would be to deploy, power on and then shutdown just to re-size the resources. There's also not an option today to increase disk capacity.

**Comment by srbry** [comment]
Is this not possible using `import.ova -options=<file>` file with `"PowerOn":false`? and then using `vm.change` and `vm.power`. Obviously it would be nicer to have this all in one command but a three command workaround could be worse.
