### ISSUE TITLE
invalid MAC addressType after vm.network.change

### ISSUE THREAD

**Issue by lsioctl** [vmware/govmomi#492]
Hello,

Context : Vsphere6, DVS

Reproductible : yes

When using  govc vm.network.change on vm created by govc, it changes the type from
"Assigned" to "Generated".

The MAC address is not changed so you pass your tests, but I you power on/off the VM,
it's MAC address changed to be within the range of "Generated" MAC address.

Example for the same VM :

After creation

---
MAC Address:      00:50:56:xx:yy:zz
  Address type:     assigned
---

After network.change on DVS

---
MAC Address:      00:50:56:xx:yy:zz
  Address type:     generated
---

After power on :

---
MAC Address:      00:0c:29:uu:vv:ww
  Address type:     generated
---

I didn't dig if it's govc or govmomi related, tell me if I could help.

Regards,

**Comment by dougm** [comment]
@lsioctl thanks for the report.  Should be fixed by #493, please re-open if not.
