### ISSUE TITLE
Minor doc issue

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/govmomi#495]
In the - https://github.com/vmware/govmomi/releases page the 4th bullet says

_Move the file to a directory in your $PATH (i.e. mv govc_linux_amd64 /usr/local/bin)_

This needs to be updated to rename the resulting as govc. This is the reference that our install script makes. See the updated line below. 

_Move the file to a directory in your $PATH (i.e. mv govc_linux_amd64 /usr/local/bin/govc)_

**Comment by dougm** [comment]
Updated the existing release doc manually.  The doc change will be included in future releases via 44bb6d0
