### ISSUE TITLE
Where can I find one example json file for parameter  -options when importing ova?

### ISSUE THREAD

**Issue by EmilieXu** [vmware/govmomi#496]
Hi,
I'm trying to import an ova file, it works, but I would like do some more operation, e,g power on VM, after it's created. I wonder where can I find an example json file?
Thanks a lot!

BR
Emilie

**Comment by srbry** [comment]
Hi, you can generate some json based on your ova file using the following: 
```
govc import.spec <ova_file_path>
```

Just add the json to a file, change the bits you want to and target it using the `-options` flag of import.ova. Would be good to have this properly documented somewhere.

**Comment by anfernee** [comment]
I am closing this issue because it's more like a question. For further discussion, there is a slack channel:  https://github.com/vmware/govmomi#discussion Your questions will be answered there.
