### ISSUE TITLE
Feature request - Add dvs.portgroup.configure and dvs.portgroup.remove 

### ISSUE THREAD

**Issue by giminni** [vmware/govmomi#500]
I was able to add a portgroup to a distributed switch using dvs.portgroup.add.

I realized also that there is a flag named nports to define the amount of ports.

What I am missing is a way  to configure at least Security and VLAN of a newly created portgroup?

Can this be implemented in govc ?

**Comment by kmott** [comment]
I'd like to see this as well, would be handy for creating isolated network environments across a cluster automagically.
