### ISSUE TITLE
How to create/rename/delete a VM folder using govc import.ova?

### ISSUE THREAD

**Issue by giminni** [vmware/govmomi#502]
Is there a way to create/rename/delete a VM folder?
If no can this be included in the next version?

**Comment by djockey21** [comment]
Bump. Also how do you move a VM to a new folder using govc?

**Comment by dougm** [comment]
create: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#foldercreate

rename: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectrename

delete: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectdestroy

move: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectmv
