### ISSUE TITLE
Is there a multiple network adapter define/bind function to portgroups using import.xxx commands?

### ISSUE THREAD

**Issue by giminni** [vmware/govmomi#503]
Despite the fact there is a bug in 0.5 in the import.ova. 

I ask how can I define multiple adapter inside an OVA file and after injecting it
to the vSphere Center how can I bind this to a distributed portgroup using differen VLANs?

IMHO this is not possible at the moment. Is there an ETA for that?

**Comment by dougm** [comment]
Similar to #460
I am hoping to spend some time on import.ova improvements next week.  If you can provide an example of how you're doing this with ovftool, that'd be a great help.

**Comment by srbry** [comment]
Hi, we were able to use the config/ workaround I noted in #460 to configure this, we have tested it using v0.8

**Comment by anfernee** [comment]
can this issue be closed now, since it seems there is already a solution.

**Comment by anfernee** [comment]
close this issue. @giminni if it's still a problem, please reopen it.
