### ISSUE TITLE
Getting Datastore from storage pod

### ISSUE THREAD

**Issue by chrislovecnm** [vmware/govmomi#510]
I am working on adding functionality to allow for clustered datastores with Terraform.  In order to find the `StoragePod` I execute the following command:

```go
storagePod, err = finder.DatastoreCluster(context.TODO(), vm.datastore)
```

From there I believe that I need to get to a `Datastore` to create a disk for a virtual machine.  To get the `Datastore` does the following code work with DRS?

```go

sps := types.StoragePlacementSpec{ // redacted code }
srm := object.NewStorageResourceManager(c.Client)
rds, err := srm.RecommendDatastores(context.TODO(), sps)
if err != nil {
	return nil, err
}
spa := rds.Recommendations[0].Action[0].(*types.StoragePlacementAction)
datastore = object.NewDatastore(c.Client, spa.Destination)
```

**Comment by chrislovecnm** [comment]
@dougm @markpeek help ... pretty please

**Comment by dougm** [comment]
Have you looked at the code for the vm.create command?https://github.com/vmware/vic/blob/master/vendor/github.com/vmware/govmomi/govc/vm/create.go#L415-L493

**Comment by chrislovecnm** [comment]
@dougm you are the man!!
