### ISSUE TITLE
TLS handshake timeout with govc and govmomi.NewClient()

### ISSUE THREAD

**Issue by daxgames** [vmware/govmomi#533]
I am missing something but 'govc about' results in: 

```
govc: Post https://['ipaddress]/sdk: net/http: TLS handshake timeout
```

I have the following set in my env:

```
GOVC_URL=[ipaddress]
GOVC_PASSWORD=[password]
GOVC_USERNAME=[username]
GOVC_INSECURE=1
```

I receive the same error trying to use 'govmomi.NewClient' method in code.

https://[ipaddress]/sdk/vimservice.wsdl results in:

```
<!--
   Copyright 2005-2015 VMware, Inc.  All rights reserved.
-->
<definitions targetNamespace="urn:vim25Service"><import location="vim.wsdl" namespace="urn:vim25"/><service name="VimService"><port binding="interface:VimBinding" name="VimPort"><soap:address location="https://localhost/sdk/vimService"/></port></service></definitions>
```

I can log into vsphere web client with the user id and password.

What am I missing?

**Comment by dougm** [comment]
Did you get this resolved?  If not, does it work with`curl --verbose ...`?  Any proxy env vars set?

**Comment by iamthemuffinman** [comment]
I'm having this issue as well.

**Comment by iamthemuffinman** [comment]
Actually, I resolved my issue. I was using the port that the web client was listening on. Removing that fixed it.
