### ISSUE TITLE
Feature Request: add support for creating DRS host affinity

### ISSUE THREAD

**Issue by tommynsong** [vmware/govmomi#535]
Currently the methods are available for PowerCLI cmdlet, ex: http://pastebin.com/S1DdLTZj
And i would like to see those methods available in govmomi so that it can then be constructed or incorporated into Terraform workflow.

**Comment by chrislovecnm** [comment]
@dougm how do we do this?  What part of the api supports this?

Thanks

Chris
cc: @markpeek

**Comment by markpeek** [comment]
I believe govmomi and vim25 have all of the primitives needed to support this use case. I found this [blog](http://vthinkbeyondvm.com/drs-rules-part-i-how-to-create-vm-host-drs-affinity-rule-using-vsphere-api) that discusses how to change it from java. You can find the various types in this [file](https://github.com/vmware/govmomi/blob/master/vim25/types/types.go).

**Comment by tommynsong** [comment]
thank you @markpeek for pointing it out, for some reason, searching for those types didn't return any result in GH, hence i open this feature request.
Seems like it have enough info for me to go by for the time being.
As for submitting PR, is there any guideline that i should follow?

**Comment by chrislovecnm** [comment]
@dougm can you comment on the question about the PR?

**Comment by dougm** [comment]
Sorry for the delayed response.  We have some guidelines here:
https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md

@tommynsong have you looked into implementing this yet?

**Comment by dougm** [comment]
The types and methods were indeed already there, but with the new govc commands #928 there are examples of how to use them.  The powershell script would translate roughly to:

```sh
#!/bin/bash -e

# script values are valid against: vcsim -cluster 2 -host 4 -vm 8 &
export GOVC_URL=https://root:pass@localhost:8989 GOVC_INSECURE=true GOVC_DATACENTER=DC0 GOVC_CLUSTER=DC0_C0

name=example-rule

govc cluster.group.create -name VM-$name -vm DC0_C0_RP0_VM{0,1,2,3}

govc cluster.group.create -name Host-$name -host DC0_C0_H{0,1}

govc cluster.rule.create -name $name -vm-host -enable -mandatory -vm-group VM-$name -host-affine-group Host-$name
```

cc @embano1

**Comment by dougm** [comment]
Closing this with #928 merged.  Happy to provide any pointers and/or refactor some of the new govc related code in to helpers that can also be used by Terraform if needed (cc @vancluever)

**Comment by vancluever** [comment]
Hey @dougm - DRS is something we will be looking at in the next few months so I think for sure we will have some feedback here. DRS rules is actually something that we have had a feature request on, so I think the more helpers here the better - and in general otherwise too :slightly_smiling_face: 

I actually have a few that will need to be contributed back when I have some time to go over things, namely surrounding `EnvironmentBrowser`, which is used in our refactored VM resource which is pending merge.
