### ISSUE TITLE
How to find the tags of a VM

### ISSUE THREAD

**Issue by msepehr** [vmware/govmomi#537]
Hi,
I'm using the govmomi to find VMs. And I must say that it works well!
I'm trying to find the related tags that I have bound to a VM but I can not find it:
`vms, err := f.VirtualMachineList(ctx, envVmFolderPath)`
Then I loop on the vms : each vm.Tag is an empty array.
Any idea?

**Comment by msepehr** [comment]
I also use the following method Retrieve :
err = pc.Retrieve(ctx, refs, []string{"name"}, &vmt)

**Comment by msepehr** [comment]
Found this ticket about the VSphere5.5 which is my current version.
https://communities.vmware.com/message/2409321?tstart=0
Could you confirm that?
Is there any way to add some metadata that can be managed throught govmomi?

**Comment by dougm** [comment]
You'd have to include "tag" in the list of properties to collect:
```go
err = pc.Retrieve(ctx, refs, []string{"name", "tag"}, &vmt)
```
I don't have experience with tags myself, but there is also "custom fields".  Have a look at the govc fields commands and fields.bats for examples.

**Comment by halfa** [comment]
I just tested it, to get tags from the inventory you need to have a vCenter at least in 6.5.0, that would be nice to have in the doc somewhere.
