### ISSUE TITLE
go get github.com\vmware\govmomi does not work for me.

### ISSUE THREAD

**Issue by msepehr** [vmware/govmomi#542]
Hi,

My deployment is stopped because the go get method does not finish properly:

C:\Dev\tmp\go2>go get github.com\vmware\govmomi
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp: lookup golang.org: getaddrinfow: No su
ch host is known.)
C:\Dev\tmp\go2>go get golang.org/x/net/context
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp: lookup golang.org: getaddrinfow: No su
ch host is known.)

I am under a proxy but other github.com packages are downloaded properly.
Any idea?

**Comment by caglar10ur** [comment]
Closing this as it's clearly a network issue on your side.

**Comment by dougm** [comment]
Note that you can download the release version: https://github.com/vmware/govmomi/releases

We may also want to consider vendoring deps.

**Comment by caglar10ur** [comment]
I think you are right, vendoring is a good idea
