### ISSUE TITLE
feature request: VMware prometheus_exporter

### ISSUE THREAD

**Issue by mjtrangoni** [vmware/govmomi#550]
I want to ask if you plan to implement officially a prometheus_exporter for vmware.

See https://prometheus.io/docs/instrumenting/exporters/

**Comment by brandonweeks** [comment]
I've started work on [vsphere_exporter](https://github.com/brandonweeks/vsphere_exporter/). It's still very alpha quality, feedback would be greatly appreciated though.

**Comment by dougm** [comment]
Don't plan on anything specific to prometheus, but happy to include anything generic in support of.  Have you tried @brandonweeks vsphere_exporter?
