### ISSUE TITLE
SCSI device UnitNumber selection

### ISSUE THREAD

**Issue by dkalleg** [vmware/govmomi#552]
When adding 7+ devices to a scsi controller govmomi will encounter an error since slot 7 on scsi controllers is reserved.  

This can be worked around by manually tracking/updating the used/unused slots/UnitNumbers of each virtualDevice attached to a scsi controller and intentionally skipping slot/UnitNumber 7.  But I feel this case should be handled in govmomi.

**Comment by sputnik13** [comment]
There is also an issue of where the unit id will only increment and not reuse any IDs when disks are detached since it's always taking the max of existing IDs and adding 1.
