### ISSUE TITLE
vSphere provider: delete initial scsi controller

### ISSUE THREAD

**Issue by sputnik13** [vmware/govmomi#553]
When a VM resource is created, it usually gets created with some set of default controllers and devices, which includes an LSI parallel SCSI controller.  There is a well known fixed limit (4) on the number of SCSI controllers that a VM can support.  For dynamic attach/detach of disks at run time, only LSI SAS and Paravirtual SCSI controllers work reliably (with paravirtual being the most reliable).  The existence of the initial default LSI parallel SCSI controller effectively limits the number of SCSI disks that can be hot attached to 45, when it should be possible to use 60.

**Comment by dougm** [comment]
How are you creating a VM resource?  govmomi does not add any SCSI controller by default.  The govc vm.create command does add a SCSI controller by default.  You can disable that like so:

```
govc vm.create -disk.controller=ide foo
```

Or choose a different SCSI controller, for example:

```
govc vm.create -disk.controller=pvscsi bar
```
