### ISSUE TITLE
'NoPermission' error on Finder.HostSystemList()

### ISSUE THREAD

**Issue by mkuzmin** [vmware/govmomi#564]
I access vSphere by an account with limited privileges: it does not have admin rights over the whole datacenter, but has permissions over specific hosts, datastores, or VMs.

Calling `finder.HostSystemList(ctx, "*")` and `finder.DefaultHostSystemList(ctx)` always fails with `NoPermission` error.

Does it try to access any particular properties? 
How can I find specific privileges it requires?

Here is a complete example: https://gist.github.com/mkuzmin/7b6345e9693e18d0fa4fc681da90912a

**Comment by dougm** [comment]
The NoPermission fault provides some detail:
http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.fault.NoPermission.html

You can also trace all http/soap traffic by adding the following to your main():
```go
debug.SetProvider(&debug.FileProvider{Path: "."})
```

That will drop a bunch of .xml files in the FileProvider.Path.  A bit easier to read using:

```bash
GOVC_DEBUG_PATH=.. $GOPATH/src/github.com/vmware/govmomi/scripts/debug-xmlformat.sh
```

Note that the `-debug` flag is available for govc commands and these files end up in ~/.govmomi/debug by default.

**Comment by dougm** [comment]
Closing as this hasn't come up since.
