### ISSUE TITLE
no way to set boolean value for ovf property in import.ova command

### ISSUE THREAD

**Issue by iNode** [vmware/govmomi#583]
Part of the ovf property file:

```
     <Property ovf:key="SSHD" ovf:type="boolean" ovf:userConfigurable="true" ovf:value="false">
     <Label>SSH</Label>
     <Description>Enable ssh daemon</Description>
     </Property>
```

Part of the file generated by command govc import.spec path_to.ova > ova.spec

```
    {
        "Key": "SSHD", 
        "Value": "false"
    }, 
```

And error during deployment process (govc is a binary build from the latest git):
govc import.ova -dump=true -debug=true -options=ova.spec path_to.ova
govc: Invalid value 'false' specified for property SSHD.

When trying to set Values as boolean:

```
    {
        "Key": "SSHD", 
        "Value": false
    }, 
```

govc reports an error:
govc: json: cannot unmarshal bool into Go value of type string

**Comment by dougm** [comment]
Looks PropertyMapping only supports Value as string at the moment.

**Comment by dougm** [comment]
@iNode the json value is string only, but you can specify the ovf type by using a `Spec`.  Run `govc import.spec -verbose your.ovf` to see the details on how to specify.  For example:
```json
    {
      "Key": "guestinfo.cis.vmdir.first-instance",
      "Value": "True",
      "Spec": {
        "Type": "boolean",
        "..."
      }
    },
```

Feel free to re-open if this doesn't work for you.
