### ISSUE TITLE
Govc cannot find vmdk when executing vm.create

### ISSUE THREAD

**Issue by garreeoke** [vmware/govmomi#584]
I'm trying to setup kubernetes with the provided kube-up scripts.  The command that is failing in the govc command:

govc vm.create -debug=true -disk=./kube/kube.vmdk -g=debian7_64Guest -link=true kubernetes-master

govc: File /vmfs/volumes/45fa679c-0353fa19/kubernetes-master/kubernetes-master.vmdk was not found

However, the vmdk does exist in that location.  It is an NFS mount.

**Comment by dougm** [comment]
Since you have `-debug` enable, can you run the following:
```
grep -R "was not found" ~/.govmomi/debug | cut -d: -f1 | tail -n1 | xargs xmlformat
```

That should tell us which soap method is complaining.

**Comment by garreeoke** [comment]
See attached.

-Aaron

**Comment by dougm** [comment]
Don't see anything attached.

**Comment by garreeoke** [comment]
Sorry about the attachment.  We figured it out, some issue with how the ESX was configured.  Thanks for the replies.

-Aaron

**Comment by dougm** [comment]
@garreeoke ok good to hear you resolved the issue
