### ISSUE TITLE
Cannot assign network containing a slash in its name

### ISSUE THREAD

**Issue by synthesizerpatel** [vmware/govmomi#592]
Our vswitches are named <network>/<cidr>, which would appear to be a legal name. (Our VMWare admin reports that javascript and powershell scripts can attach them to VMs no problem)

Because of the way govc handles paths, when executing the search in find/finder.go it looks like the incoming strings are split by '/'.

Meaning that a network named 'VLAN 172.16.0.0/8' would result in find/finder looking for a folder named 'VLAN 172.16.0.0' and an object named '8 inside of it.

I tried escaping with no luck using the following forms:

```
172.16.0.0\/8
172.16.0.0\//8
172.16.0.0//8
172.16.0.0%2f8
```

I don't like this naming convention, I wouldn't have named them with slashes in their names, I am not in control of the slashes. This seems like a legit bug to me given that none of the documentation explicitly forbids vSwitch names with slash in them..

**Comment by dougm** [comment]
Haven't run into this before, but legit.  Not sure the best way to deal with it yet, but can offer the quick workaround of using the moref instead of path.  You can list network by moref with:
```
govc ls -i network
```
And use any of the listed morefs as your `-net` path.

**Comment by synthesizerpatel** [comment]
I greatly appreciate the consideration @dougm, unfortunately that didn't seem to work for me. 

Specifically I am trying to assign a network via terraform. It may be failing specifically because it's looking for a label? .. But, might be fixable through a patch to terraform.. I'll dig on that side. Wasn't aware of the '-i' option. Thanks!

Neither of these formats worked for me:

```
  network_interface {
    label              = "Network:network-125"
    ipv4_address       = "10.33.20.254"
    ipv4_prefix_length = "24"
    ipv4_gateway       = "10.33.20.1"
  }


  network_interface {
    label              = "network-125"
    ipv4_address       = "10.33.20.254"
    ipv4_prefix_length = "24"
    ipv4_gateway       = "10.33.20.1"
  }
```

**Comment by dougm** [comment]
Did you apply the linked patch above to terraform and rebuild it?
I haven't tried terraform, only tested this change using `govc vm.create -net ...`.  If having the ':' in a terraform label is somehow an issue, you could try hacking my hack with the change below and using "network-125" in terraform.

```diff
diff --git a/find/finder.go b/find/finder.go
index c737479..a154855 100644
--- a/find/finder.go
+++ b/find/finder.go
@@ -598,7 +598,7 @@ func (f *Finder) NetworkList(ctx context.Context, path string) ([]object.Network
        // Try moref in the form of 'govc ls -i network' output
        if len(es) == 0 {
                var ref types.ManagedObjectReference
-               if ref.FromString(path) {
+               if ref.FromString("Network:" + path) {
                        if e, err := f.Element(ctx, ref); err == nil {
                                es = append(es, *e)
                        }
```

**Comment by forkbomber** [comment]
Seems to be the same issue with `vm.create` when referencing network by name:

```
$ govc vm.create -net='/Test/network/VLAN XXXX - XX.XXX.XXX.X/XX' oh-no
govc: network '/Test/network/VLAN XXXX - XX.XXX.XXX.X/XX' not found
```

**Comment by berchtos** [comment]
Did this get solved somehow?

**Comment by dougm** [comment]
#734 is an option where `/` can be escaped with `%2F`:

```
govc vm.create -net 172.16.0.0%2F8
```

Thoughts?

**Comment by dougm** [comment]
I pushed another commit to #734 as an alternative to escaping, so "/" can be used in the name, but only for leaf objects in the path - which is always the case with network objects.  Any preferences?

cc @synthesizerpatel @forkbomber @berchtos @caseyaedwards
