### ISSUE TITLE
Is there any way to find the **disk attached** to vm 

### ISSUE THREAD

**Issue by sumit-murari** [vmware/govmomi#597]
I was trying to fetch all the details of vm, tried using `govc vm.info`, it gave me details about CPU, Memory but not about disk attached to vm. Is there any way to find the details about the disk attached to virtual machine ?

**Comment by synthesizerpatel** [comment]
Use `govc ls -l -json <path/to/vm>`

That will dump an extensive (50-60kb) json description of the VM and all it's attributes.

The attached drive(s) are enumerated within that structure.

**Comment by sumit-murari** [comment]
Thanks @synthesizerpatel  it worked out, I'm closing the ticket.

**Comment by dougm** [comment]
Also: `govc device.info -vm <path/to/vm>`
