### ISSUE TITLE
Update Soap client to allow for Root CA configuration

### ISSUE THREAD

**Issue by dagnello** [vmware/govmomi#604]
Feature request/client enhancement.  Instead of relying on configuring the host's root CA set in order to verify the server's cert chain and host name.  This would allow the vCenter soap client to be configured with custom CA cert directly.  This is advantageous for scenarios where self signed cert's used and do not want to clutter the host system's CA cert set.

**Comment by dougm** [comment]
There is a recently added `-tls-ca-certs` flag for govc and `soap.Client.SetRootCAs` helper method.  You can also directly modify `soap.Client.Transport.(*http.Transport).TLSClientConfig`, that works with older versions too.  Also recently added thumbprint based verification, need to add some docs, but have a look at host.bats and cli.bats around the use of the `about.cert` command.
