### ISSUE TITLE
Is it possible to recursively list all vm's under a given path ?

### ISSUE THREAD

**Issue by sumit-murari** [vmware/govmomi#615]
Hi Team, 

I've trying to list all the vm's under a given path. I used `govc ls PATH`, to list all the instance under a given path. 

It there any recursive flag like `ls -lr`, where I can list all the vm under a give path including sub-folders ?

**Comment by SciGno** [comment]
Not sure if this helps:

govc ls /*/vm/*

This lists all the VMs under /datacenter/vm

**Comment by sumit-murari** [comment]
Thanks it works like charm :).
Closing the ticket.

**Comment by maxadamo** [comment]
it will not work if there are subfolders. And if you try adding a further wildcard: 
```
govc ls /*/vm/*/*
```
you get the following error:
```
govc: cannot traverse type VirtualMachine
```

**Comment by dougm** [comment]
The `find` command is easier to use for this case, `govc find / -type m` for example.

https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#find

**Comment by ramjigit** [comment]
> Not sure if this helps:
> 
> ```
> govc ls /*/vm/*
> ```
> 
> This lists all the VMs under /datacenter/vm

great
