### ISSUE TITLE
ability to extend disk when cloning

### ISSUE THREAD

**Issue by warroyo** [vmware/govmomi#629]
Is it currently possible to extend the primary disk when using  `govc vm.clone`  ? I cant find an option to do this. 

if this does not exist would it be possible to get this added?

**Comment by warroyo** [comment]
any chance we can get this feature added?

**Comment by dougm** [comment]
PR #658 adds a vm.disk.change command you can use post-clone.

**Comment by dougm** [comment]
PR #658 is merged

**Comment by dncmn** [comment]
how to achieve extend the disk?By using vm.disk.change,A problem Casm across that "No disk found using the given values"
