### ISSUE TITLE
Doing a "storage vmotion" without doing a clone?

### ISSUE THREAD

**Issue by solarce** [vmware/govmomi#639]
From looking through the vSphere API docs and the `govmomi` source code, it seems like the only way I can do something like a "storage vmotion" is with `vm.clone`, due to it supporting https://github.com/vmware/govmomi/blob/master/govc/vm/clone.go#L299-L303

However, a `vm.clone` takes a fair bit longer than if I use the **Migrate wizard...** to change the datastore of the VM via storage vmotion, 23 minutes vs 14 minutes.

Is it possible to use `govc` to initiate the same action that done with the **Migrate...** wizard, when choosing **Change datastore**, like what's shown in http://greg.porter.name/wordpress/?p=1692? 

![image](https://cloud.githubusercontent.com/assets/9660/21036864/cd6fa0f4-bd7d-11e6-873f-de95c88e9ab3.png)

**Comment by dougm** [comment]
Not at the moment, but I have some related work planned soonish, I'll take a look.

**Comment by dougm** [comment]
@solarce there are a pile of other options we could provide by using RelocateVM instead of MigrateVM, but sounds like you just need the Datastore.  Can you give it a try and let me know?

**Comment by solarce** [comment]
@dougm I've built `govc` from your PR and am testing it out now, will let you know it goes

``` bash
14:06:25  ✘  ...vmware/govmomi/govc  🐍 system   issue-639 ✘ ✹ 
$ ./govc vm.migrate -ds=/TravisCI/datastore/EMC-VMAX-1 "/TravisCI/vm/In Progress Base VMs/travis-ci-macos10.12-brandontest-1481155580"
[09-12-16 14:07:29] migrating VirtualMachine:vm-7950261... (37%)
```

**Comment by dougm** [comment]
@solarce great thanks for testing it out
