### ISSUE TITLE
CreateVmfsDatastore error

### ISSUE THREAD

**Issue by yashmankad** [vmware/govmomi#644]
Hi,
I am trying to create a vmfs Datastore out of a fresh disk that has been exposed to a ESX host. I obtained the ```VmfsDatastoreOption``` by invoking ```QueryVmfsDatastoreCreateOptions``` and tried passing the 'spec' to ```CreateVmfsDatastore``` but it complained about various fields not being set in ```HostVmfsSpec```.

So I proceeded by populating this spec with fields like ```Extent, VolumeName and MajorVersion``` but Datastore creation still fails with a mysterious error-

```
ServerFaultCode: A specified parameter was not correct:
panic: runtime error: invalid memory address or nil pointer dereference
```

My code looks something like this:

```
// Query for DS options
dsCreateOptions, err = ds.QueryVmfsDatastoreCreateOptions(ctx, devicePath)
dsCreateSpec := dsCreateOptions[0].Spec
dsSpec := dsCreateSpec.GetVmfsDatastoreSpec()

extent := types.HostScsiDiskPartition{
        DiskName:  "naa.6589cfc000000ceb29c81c0512ed18dc",
        Partition: 1,
}

vmfsSpec := types.HostVmfsSpec{
        Extent:       extent,
        VolumeName:   "vmfs",
        MajorVersion: 5,
 }

vmfsDatastoreCreateSpec := types.VmfsDatastoreCreateSpec{
        VmfsDatastoreSpec: *dsSpec,
        Vmfs: vmfsSpec,
} 
```

I think I should be able to extract the needed spec from the ```QueryVmfsDatastoreCreateOptions ``` query but I'm lost how to do that. 

Appreciate your help.

**Comment by dougm** [comment]
Have you looked at the govc datastore.create command for reference?  https://github.com/vmware/govmomi/blob/4fa7b32ae55649cd700182a2a19abd7b42f9b0bc/govc/datastore/create.go#L245

**Comment by yashmankad** [comment]
Great! That ref. fixed my problem. Thanks @dougm 
But since I'm new to Go, I'm struggling to understand what line 288 is doing-

``` spec := *option.Spec.(*types.VmfsDatastoreCreateSpec)```

Something about applying reflection on an interface? Got to read up on that concept!

**Comment by dougm** [comment]
ok glad that helped.  No reflection going on, that's all in the `reflect` package.  The `Spec` field here is an interface and we are asserting the concrete type is`*types.VmfsDatastoreCreateSpec` in this case.  See: https://golang.org/doc/effective_go.html#interface_conversions
