### ISSUE TITLE
Does it support SSO and any plan to support vSphere6.5?

### ISSUE THREAD

**Issue by esharkwang** [vmware/govmomi#649]
I am a new user of this project. Does it support SSO and guest operation? We will use some vSphere 6.5 features. So there is any plan or schedule to add support of vSphere6.5 APIs?

**Comment by dougm** [comment]
Yes, 6.5 is supported as of commit 757a2d6.  Guest operations are supported.  There is not any SSO specific support yet.

Also recently created a Slack channel for discussion: https://github.com/vmware/govmomi#discussion

**Comment by esharkwang** [comment]
I am glad to hear from you. If we want to add SSO by ourselves, could you help to share some tools to integrate the SSO(STM service) SOAP with golang?
