### ISSUE TITLE
waitForNetIp to take arguments allowing to wait for specific nic(s)

### ISSUE THREAD

**Issue by rickardrosen** [vmware/govmomi#653]
We are experiencing the following [issue](https://github.com/hashicorp/terraform/issues/7479) when using terraform to provision vsphere virtual machines.

If we add multiple NIC to a host, and the additional nics do not receive an IP address, terraform will not complete provisioning as it calls the waitForNetIp function.

In our scenario we're provisioning hosts that will use additional nics as bridge interfaces, and as such will have a mac address, but no IP.

To temporarily solve this I made this update to the waitForNetIp:

```
		for _, ips := range macs {
			if len(ips) > 0 {
				return true
			}
		}

		return false
```

It would be great if the WaitForNetIp could receive an array of nic# to specifically wait for.

This way we could mark one (or more) NIC as "management" in terraform and waitForNetIp could disregard the others.

Does it make sense?

**Comment by dougm** [comment]
@rickardrosen can you review #660 and let me know if that does what you need?
