### ISSUE TITLE
CreateVirtualDisk on a VSAN datastore fails

### ISSUE THREAD

**Issue by rickardrosen** [vmware/govmomi#654]
I'm trying to create disks using terraform on a VSAN datastore but it fails:

`A general system error occurred: Function not implemented`

Diskspec sent is: `Disk spec: &{{{} eagerZeroedThick lsiLogic} 10485760 []}`

How can I create a disk on a VSAN datastore using govmomi?

**Comment by dougm** [comment]
What is the value of the CreateVirtualDisk() name param in this case?  On vSAN, you can't create files at the top-level of the datastore, for example this will fail: `[vsanDatastore] foo.vmdk`

However, you can within a directory (aka vSAN namespace):  `[vsanDatastore] foo/bar.vmdk`

You'll need to create the 'foo' directory in this case if it doesn't already exist.

**Comment by dougm** [comment]
Verified this while working on PR #672
