### ISSUE TITLE
How to run command with arguments on Windows VM

### ISSUE THREAD

**Issue by liboshi** [vmware/govmomi#662]
Hi

Use the latest development version.

**Precondition:**
An installer on target VM (windows7 x86). 

**Test Steps:**
Use `govc guest.start` to install it with silent mode
Command: `govc guest.start /the-path-to/installer.exe /s /v/qn`

**Actual result:**
PID return successfully, but just usage window pop-up and the installation process terminate here

**Question here:** how to pass arguments to that installer with `guest.start`

Thanks in advance.

**Comment by dougm** [comment]
Command syntax looks right.  Does it work when run from a shell within the VM?

**Comment by liboshi** [comment]
Thanks for your reply.
Yes, it works in windows cmd.

It works with following actions:
`script=$(govc guest.mktemp -s=.bat)`
`echo $script`
`govc guest.upload -f - "$script" << 'EOF'`
`@echo off`
`c:\temp\installer.exe /s /v/qn`
`EOF`
`govc guest.start $script`

**Comment by dougm** [comment]
Not sure.  I don't have any Windows VM at the moment to try with.  But I recall in the past (using vmrun), having to use cmd.exe to run a .bat script.  Something like:
`govc guest.start cmd.exe /c $script`

**Comment by liboshi** [comment]
I have tried the steps which I mentioned in my second comments.
It works well.

Thanks again. I will close this issue.

**Comment by dougm** [comment]
Ah ok, glad you have it working.
