### ISSUE TITLE
govc vm.destroy marks the vm orphaned, then vm.unregister doesn't work

### ISSUE THREAD

**Issue by ronakg** [vmware/govmomi#668]
I'm trying to use govc to automate some of the VM deployment processes we have.

I'm connecting directly to the ESXi host. 

I want to make sure there are no existing vms (in any state) with same name before deploying the ova. 

So following are the steps I'm trying to follow:

1. Check if the vm exists using `vm.info`
2. Power off the vm using `vm.power -off=true -force=true`
3. Destroy the vm using `vm.destroy`

At this point the vm becomes orphaned. Now when I run `vm.unregister`, it can't find the vm itself. vm needs to be unregistered from the vcenter UI.

Any ideas?

**Comment by dougm** [comment]
Why not connect to the VC server with govc?  You won't be able to remove the VM from VC's inventory when connected to an ESX host.

**Comment by ronakg** [comment]
Because the VC server has multiple hosts belonging to different teams. I'd have to take the VC server as well as the host as argument to my script, which makes user experience slightly worse.

Actually, I just did some more testing and found out that orphaned VMs are not an issue. When I import the ova using same name as orphaned VM, it gets overwritten. 

So this is a non-issue.
