### ISSUE TITLE
Issues with OVF and OVAs....

### ISSUE THREAD

**Issue by Texiwill** [vmware/govmomi#670]
Hello,

I am trying to import several OVF and OVA files.... I get mixed results... running on Linux...

$ govc import.spec VMware-BigDataExtensions-2.3.1.2402-3694787_OVF10.ova
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4c6f3a]

goroutine 1 [running]:
panic(0xb80e20, 0xc420010130)
	/usr/local/golang-go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/govmomi/govc/importx.(*spec).Map(0xc420011910, 0xc420194a80, 0x5, 0xc420194a80, 0x0)
	/home/dougm/release/src/github.com/vmware/govmomi/govc/importx/spec.go:95 +0x6a
github.com/vmware/govmomi/govc/importx.(*spec).Spec(0xc420011910, 0xd72c8c, 0x5, 0x4, 0xd73e01)
	/home/dougm/release/src/github.com/vmware/govmomi/govc/importx/spec.go:156 +0x488
github.com/vmware/govmomi/govc/importx.(*spec).Run(0xc420011910, 0x12a1bc0, 0xc420010320, 0xc42005a840, 0x0, 0x0)
	/home/dougm/release/src/github.com/vmware/govmomi/govc/importx/spec.go:87 +0x7a
github.com/vmware/govmomi/govc/cli.Run(0xc42000c250, 0x2, 0x2, 0xc4200001a0)
	/home/dougm/release/src/github.com/vmware/govmomi/govc/cli/command.go:149 +0x586
main.main()
	/home/dougm/release/src/github.com/vmware/govmomi/govc/main.go:74 +0x66
No JSON object could be decoded

$ govc import.ovf -options import.json vMA-6.5.0.0-4569350

or

$ govc import.ova -options import.json h5ngcVA-3.4.0.0-5070500_OVF10.ova
govc import.ova -options j h5ngcVA-3.4.0.0-5070500_OVF10.ova 
[22-02-17 10:15:35] Warning: Line 143: Invalid value 'Network 1' for element 'Connection'.
govc: Invalid network  in property vami.gateway.vSphere_Web_Client_Appliance.

This happens whether the import script has a gateway specified under PropertyMapping or the following json:
{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "InjectOvfEnv": false,
    "Name": null,
    "NetworkMapping": [
        {
            "Name": "vSwitch0",
            "Network": "VMNetwork"
        }
    ],
    "PowerOn": false,
    "PropertyMapping": [
    ],
    "WaitForIP": false
}

The only fix I have found is to modify the ovf by unpacking the ova and then using something like the following:

sed "s/Network 1/VMNetwork/g" *.ovf > new.ovf

**Comment by anfernee** [comment]
There are several bugs reported in this issue. 

- [ ]  import.spec panic
- [ ]  import.ova/import.ovf error

**Comment by anfernee** [comment]
I tried the latest govc, both not an issue for me anymore.

First issue:
```
$ govc import.spec ~/Downloads/VMware-BigDataExtensions-2.3.1.2402-3694787_OVF10.ova 
{"Deployment":"small","DiskProvisioning":"thin","IPAllocationPolicy":"dhcpPolicy","IPProtocol":"IPv4","NetworkMapping":[{"Name":"Management Server Network 1","Network":""},{"Name":"Management Server Network 2","Network":""}],"PowerOn":false,"InjectOvfEnv":false,"WaitForIP":false,"Name":null}
```

Second issue:
```
$ govc import.ova -options ./import.json -ds datastore3 ~/Downloads/VMware-vCenter-Server-Appliance-6.5.0.5100-4602587_OVF10.ova 
[18-10-17 15:17:09] Warning: Line 1,509: Invalid value 'Network 1' for element 'Connection'.
[18-10-17 15:17:54] Uploading VMware-vCenter-Server-Appliance-6.5.0.5100-4602587_OVF10-disk1.vmdk... OK
[18-10-17 15:19:25] Uploading VMware-vCenter-Server-Appliance-6.5.0.5100-4602587_OVF10-disk2.vmdk... OK

```

**Comment by dougm** [comment]
Closing as resolved based on @anfernee 's comments.

**Comment by koteswara-kelam** [comment]
even if i specify "myNetwork", the VM is getting deployed on "VM Network".
 # cat options.json
{
    "DiskProvisioning": "flat",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "InjectOvfEnv": false,
    "MarkAsTemplate": false,
    "Name": null,
    "NetworkMapping": [
        {
            "Name": "myNetwork",
            "Network": "myNetwork"
        }
    ],
    "PowerOn": false,
    "WaitForIP": false
}
# govc import.ova --options=options.json greenlake-centos-7-7-1579580585.ova
[21-01-20 11:28:57] Warning: Line 72: Invalid value 'bridged' for element 'Connection'.
[21-01-20 11:30:01] Uploading greenlake-centos-7-7-disk1.vmdk... OK

**Comment by koteswara-kelam** [comment]
"myNetwork" is DVS portgroup

**Comment by koteswara-kelam** [comment]
It is working after changing "Name" to ova's network:
{
"Name": "bridged",
"Network": "myNetwork"
}
