### ISSUE TITLE
Feature request: ability to mount vmware-tools iso

### ISSUE THREAD

**Issue by marema31** [vmware/govmomi#674]
Hello,

I did not find a way with govc/govmomi to mount the vmware tools iso on a vm, like the vim-cmd vmsvc/tools.install CLI commands. 

May I'm looking for the wrong way to achieves that.

**Comment by dougm** [comment]
@marema31 we don't but if you can verify #676 does what you need then we will :)

**Comment by marema31** [comment]
It seems to be what I was looking for.
I'll try to compile this at work tomorrow and verify it.
Thanks.
