### ISSUE TITLE
Invalid configuration for device '0'

### ISSUE THREAD

**Issue by thesraid** [vmware/govmomi#681]
I'm trying to connect an existing disk to a running VM. 

This is the syntax I'm using

govc vm.disk.attach -ds=AWC-004 -disk=Sensor-.0.34-2017-03-07/USMA_Sensor-6.0.34-2017-03-07.vmdk -vm=sensor-download -controller=scsi

I believe the syntax is correct. 

When I run the command I get the error

govc: Invalid configuration for device '0'.

**Comment by dougm** [comment]
Double check the path is correct:
`govc datastore.ls -ds AWC-004 Sensor-.0.34-2017-03-07/USMA_Sensor-6.0.34-2017-03-07.vmdk`

Depending on the type of disk, you may need to use the `-link=false` option.

**Comment by dougm** [comment]
@thesraid did you end up finding out what the issue was here?

**Comment by thesraid** [comment]
Sorry I should have gotten back to you. The VMDK I was using was part of an OVF. I had to convert the OVF to a VM and then this command worked.

**Comment by dougm** [comment]
As of 596e51a , `import.vmdk` checks for proper disk type before importing.
