### ISSUE TITLE
govc: No disk found using the given values

### ISSUE THREAD

**Issue by dncmn** [vmware/govmomi#685]
I add a new hard disk,now,I want to change it and make it bigger.but I come across  a problem that "govc: No disk found using the given values"? Is there anything wrong about my query statement  like "govc vm.disk.change -dc=ha-datacenter -vm=centos7_test_mn -disk.filePath=centos7_test_mn/disk1  -size=100G" 
 Is there anyone who can help me out???

**Comment by dougm** [comment]
Try adding '.vmdk' to the disk.filePath.  You can check the paths using: `govc device.info -vm $vm disk-*`

**Comment by dncmn** [comment]
Thank you very much!The problem has been sovled.

**Comment by dncmn** [comment]
But hard disk can only get bigger???
