### ISSUE TITLE
Is it possible to collect Alarms from VCenter using govc

### ISSUE THREAD

**Issue by findneville** [vmware/govmomi#695]
I see that there is a govc events available to collect events associated with a particular entity in VCenter. 

Is there anything similar to collect alarms from within VCenter?

The alarms do not show up in VCenter events so (afaik) no way to collect alarms unless we are specifically looking for it. 

Any help appreciated.

**Comment by dougm** [comment]
Not currently, but have been planning to add some alarm commands.  Any suggestions on the format you'd like to see?

In the meantime, you can use object.collect to get the raw data.  For example:

`$ govc object.collect -json /dc1/host/cluster1 triggeredAlarmState | jq .`

```
$ govc object.collect -json /dc1/host/cluster1 triggeredAlarmState | jq -r .[].Val.AlarmState[].Alarm.Value | xargs -n1 -I% govc object.collect -s Alarm:% info.name                                                                      
Virtual SAN Health Alarm 'Virtual SAN HCL DB up-to-date'
Virtual SAN Health Service Alarm for Overall Health Summary
Virtual SAN Health Alarm 'SCSI Controller on Virtual SAN HCL'
Virtual SAN Health Alarm 'Controller Release Support'
Virtual SAN Health Alarm 'Stats DB object'
Virtual SAN Health Alarm 'Virtual SAN HCL health'
Virtual SAN Health Alarm 'Controller Driver'
Virtual SAN Health Alarm 'Virtual SAN Performance Service health'
```

**Comment by findneville** [comment]
@dougm Thx for that info. I checked out the object.collect 

This seems to work. And I can loop through to get the actual alarm name
govc object.collect -json '/path/to/object' triggeredAlarmState | jq '[.[].Val.AlarmState[] | {Alarm: .Alarm.Value, Time: .Time, Status: .OverallStatus}]' 

As for formatting, I think the output similar to that of what the govc logs provides today would suffice. Something like vvvv
[Time Stamp] [Object] [Status] [Name]

**Comment by findneville** [comment]
Just wanted to provide an update for anyone looking to collect alarms super quick with govc, simply use the following command. 

govc object.collect -json '/path' triggeredAlarmState | jq '.[].Val.AlarmState[]? | [(.Entity.Type + ":" + .Entity.Value), ("Alarm:" + .Alarm.Value), .Time, .OverallStatus]|join(" ")' -r | while read l; do read h a t s <<<$l; object=`govc object.collect -s $h name`; alarm=`govc object.collect -s $a info.name`; echo $object,$alarm,$t,$s; done

**Comment by semora81** [comment]
Hi dougm, 

I have a question related to this triggeredAlarmState, can it also be cleared by a similar use of object.method or object.destroy?

**Comment by dougm** [comment]
@semora81 sounds like you are looking for the [ClearTriggeredAlarms](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.alarm.AlarmManager.html#clearTriggeredAlarms) method? https://github.com/vmware/govmomi/issues/1748#issuecomment-602221325
