### ISSUE TITLE
import.ova with multiple datastores?

### ISSUE THREAD

**Issue by eoinmiller-r7** [vmware/govmomi#697]
In attempting to import an OVA to vSphere that has multiple datastores, this error is thrown:
```
govc import.ova -options=vm.json ~/Desktop/ova/vm.ova 
govc: default datastore resolves to multiple instances, please specify
```
How do you specify a datastore for the OVA to be imported into?

**Comment by chinmayb** [comment]
Have you done this ?
`export GOVC_DATASTORE=<>`

**Comment by dougm** [comment]
`govc import.ova -h` also lists the `-ds` option: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#importova
