### ISSUE TITLE
how to get host_info

### ISSUE THREAD

**Issue by dncmn** [vmware/govmomi#703]
I'd like to get the host info  but I　don't know which method I will use In the program。What's more I can't find the struct of host. I can't find out the fileds of the host

**Comment by dougm** [comment]
HostSystem doc: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.HostSystem.html

Example using govmomi: https://github.com/vmware/govmomi/blob/master/govc/host/info.go
