### ISSUE TITLE
There is no CPU load metric available

### ISSUE THREAD

**Issue by mkleina** [vmware/govmomi#705]
Hello!

Maybe I'm wrong, but there is no CPU load metric in vSphere API. Is there any way to retrieve CPU load for host? I don't need CPU usage (like cpu.usage.average), but load value like in `top` / `esxtop` tools (for 1, 5 or 15 minutes, doesn't matter). Something like that:
```
top - 17:31:22 up  5:54,  2 users,  load average: 0,16, 0,26, 0,24
```

I hope somebody can answer me, or if there is no answer, maybe it is worth to implement that.

Thanks in advance.

**Comment by dougm** [comment]
Haven't gone through this all yet, but if it has the data you need, it could certainly be ported to Go: http://www.virtuallyghetto.com/2017/02/using-the-vsphere-api-in-vcenter-server-to-collect-esxtop-vscsistats-metrics.html

**Comment by dougm** [comment]
Closing as stale.
