### ISSUE TITLE
GOVC_RESOURCE_POOL does not work in MSYS2 environment (Windows)

### ISSUE THREAD

**Issue by Tatsh** [vmware/govmomi#712]
In this environment, a command like:

```sh
env \
    GOVC_INSECURE=1 \
    GOVC_URL=xxxx \
    GOVC_USERNAME=xxx \
    GOVC_PASSWORD=xxx \
    GOVC_DATASTORE=xxx \
    GOVC_NETWORK=xing \
    GOVC_RESOURCE_POOL='/QA/host/NGEN/Resources' \
    govc import.ovf some.ovf
```

gives:

```
C:\tools\msys64\home\audarve\usr\bin\govc.exe: resource pool 'C:/tools/msys64/QA/host/NGEN/Resources' not found
```

On Linux this does not happen nor does a similar error.

**Comment by dougm** [comment]
Weird.  Not sure if its Go's or MSYS2's fault, but the same happens with this standalone program:
```go
func main() {
	fmt.Println(os.Getenv("GOVC_RESOURCE_POOL"))
}
```

You can workaround by using a path relative to the datacenter:
```
GOVC_DATACENTER=QA GOVC_RESOURCE_POOL=NGEN/Resources
```

**Comment by hickeng** [comment]
@Tatsh @dougm 
That's msys attempting to correct *nix paths to paths suited for the windows binary: http://www.mingw.org/wiki/Posix_path_conversion

The heuristic to leverage is:
> An argument starting with 2 or more / is considered an escaped Windows style switch and will be passed with the leading / removed and all \ changed to /.
Except that if there is a / following the leading block of /, the argument is considered to be a UNC path and the leading / is not removed.

If you cannot use @dougm suggestion for a non-absolute path then use the following to avoid the translation (note the \'s):
`GOVC_RESOURCE_POOL='//QA\host\NGEN\Resources'`

**Comment by dougm** [comment]
Add a readme note in #732
