### ISSUE TITLE
Error when create vm with command govc vm.create

### ISSUE THREAD

**Issue by liboshi** [vmware/govmomi#721]
Hi,
When I used govc to create a vm, there is an error pop-up.

`govc version`

> govc 0.14.0

`govc about`

> Name:         VMware ESXi
> Vendor:       VMware, Inc.
> Version:      5.5.0
> Build:        2068190
> OS type:      vmnix-x86
> API type:     HostAgent
> API version:  5.5
> Product ID:   embeddedEsx
> UUID:         
> 

`govc vm.create -ds='datastore1 (3)' -iso=ubuntu-14.04.3-server-amd64.iso -link=false -net=VM Network -on=false c-ubuntu-test`

> govc: The device '2' is referring to a nonexisting controller '-,202'.

Thanks in advance.

**Comment by dougm** [comment]
We may have broken something with 5.5.  Do you have version 6.0 or 6.5 you can try with?

**Comment by liboshi** [comment]
I will update my ESXi to 6.0+ and then give a try.

Thanks for your reply.

**Comment by liboshi** [comment]
Cannot hit this issue on ESXi 6.0+, so close it.
