### ISSUE TITLE
govc vm.vnc not functionnal in esxi 6.5

### ISSUE THREAD

**Issue by marema31** [vmware/govmomi#724]
I'm working on a plugin for packer using govc but I have difficulty with my new test environment (Esxi 6.5), the following command:

$  govc vm.vnc -enable /ha-datacenter/vm/redhat
redhat: vnc://:@192.168.9.58:5941

Seems to work but the port is not available:
$ govc host.esxcli network ip connection list |grep 5940
give no answer.

I'm using govc 0.14.0 on linux 64 bit.

**Comment by dougm** [comment]
@marema31 vm.vnc outputs port 5941, but you grep for 5940?  The command does not check firewall rules, so you may need to open it up or specify a port that is open.  Also note that the vmx is only listening if the VM is powered on.

check with: `govc firewall.ruleset.find -direction inbound -port 5490`

**Comment by marema31** [comment]
@dougm, the discrepedency between my two commands was only a typo.

My bad, I was thinking this command will also open the port on the firewall.
Is there any mean to use govc to open/close a port on the firewall. 

Before trying to create the packer plugin I scp to the esxi XML file (/etc/vmware/firewall/packer_vnc.xml) and reload the firewall configuration. is there a way to do it only with govc?

**Comment by dougm** [comment]
The firewall.ruleset.find command above will list existing rules that match, you can enable those rules or disable the firewall.  Examples here: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#hostesxcli

But there isn't a command to open a specific port, just to enable and disable existing firewall rules.

**Comment by marema31** [comment]
I was already using this hostesxcli command, but using scp to provides the correct XML for services. Is there a way to use govc to replace the scp (datastore.upload will not be the correct choice because it needs to be positionned in /etc/). 

Since you've already answer to my initial request, I close this issue.

**Comment by dougm** [comment]
@marema31 one more note, it is possible to create a .vib that contains the firewall config and use govc esxcli to install/uninstall the vib.  That would avoid the need for scp.  There's a docker container for vibtool that may simplify things if you go that route.
