### ISSUE TITLE
Support at-most-once event collection and consistent ordering

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#730]
Current event handling leaves tracking and elimination of already seen events to the caller, and also requires the caller to have knowledge of the mixed ordering of event pages (oldest first) vs events in pages (newest first).

This is a request for a simple means to consume events that normalizes the event ordering irrespective of page size and ensures events are not seen multiple times even in the case of client re-connection.
This does not cover ensuring that no events are missed, only that the same event is not delivered twice.

This could be simple changes to the existing call mechanism, or could be a change to provide an event channel that hides the underling pagination/connection/ordering quirks completely.

The client side workaround currently in use is in: https://github.com/vmware/vic/pull/5350

**Comment by dougm** [comment]
Going through some old issues.. I think the proper solution here is to use EventHistoryCollector:
https://code.vmware.com/apis/704/vsphere/vim.HistoryCollector.html

However, it only works against vCenter, not ESX.

**Comment by hickeng** [comment]
I think your [comment|https://github.com/vmware/vic/pull/5350/files#r120012202] is a reasonable approach for pure ESX. Odds of multiple events with the same timestamp much reduced in that circumstance.
