### ISSUE TITLE
import.ova with ambiguous resource pool name fails

### ISSUE THREAD

**Issue by theozaurus** [vmware/govmomi#733]
Hi,

We've been using govc to provision VM's. We have a setup where resource pools are not uniquely named across different Cluster Compute Resource's. When we use the command:

```
govc import.ova -options spec.json -ds DATASTORE -pool RESOURCEPOOL VMNAME
```

We get the error:

```
path 'RESOURCEPOOL' resolves to multiple resource pools
```

We've tried using the resource pools MOID which should be unique, but then we get:

```
resource pool 'ResourcePool:resgroup-19097' not found
```

Is it possible to specify the cluster that the OVA is imported into so that the resource pool's name is no longer ambiguous?

Thanks,

Theo

**Comment by dougm** [comment]
@theozaurus you can use the full inventory path, for example: `-pool /dc/host/cluster1/Resources` or relative to dc `-pool cluster1/Resources`

**Comment by theozaurus** [comment]
@dougm That works brilliantly. Thank you.
