### ISSUE TITLE
vm.clone: add support for 'Content Library' as template source?

### ISSUE THREAD

**Issue by cwegener** [vmware/govmomi#735]
Hi,

I literally just found out about a feature that has been added in vCenter 6.0 called 'Content Library', because one of the environments I work in started adapting this new feature for exclusively storing their VM templates in.

How much effort would be involved to support a 'Content Library' as a template source for cloning new VMs?

I haven't done any research yet on this topic, and I don't know how many administrators have adapted this feature. But I thought I'd put the word out and see what other people think.

**Comment by dougm** [comment]
Not sure, haven't used the content library myself.  Feel free to drop any pointers in here.

**Comment by cwegener** [comment]
Alright, I managed to collect some information from the SDK docs.

## Introduction

- [Content Library Overview](http://pubs.vmware.com/vsphere-65/topic/com.vmware.vapi.progguide.doc/GUID-A63746AD-24BB-4045-9C05-B36BEE14AB39.html)
- [VM Templates and vApp Templates in a Content Library](http://pubs.vmware.com/vsphere-65/topic/com.vmware.vsphere.vm_admin.doc/GUID-F7BF0E6B-7C4F-4E46-8BBF-76229AEA7220.html)

## Interact with Content Libraries

- [List Content Libraries](http://pubs.vmware.com/vsphere-65/topic/com.vmware.vapi.progguide.doc/GUID-8E40C702-FD19-48BF-B53D-EBC4D4ED1B83.html)
- [List Items in a Content Library](http://pubs.vmware.com/vsphere-65/topic/com.vmware.vapi.progguide.doc/GUID-F17AD9C0-AD2F-4286-8F16-EB0E89EC0851.html)
- [Working with Items in a Library](http://pubs.vmware.com/vsphere-65/topic/com.vmware.vsphere.vm_admin.doc/GUID-D3DD122F-16A5-4F36-8467-97994A854B16.html)

**Comment by cwegener** [comment]
Also, in terms of how a VM Template deploymen from a Content Library is supposed to work, I believe that there is a two-stage process going on when using this feature from the vSphere Web Client. The first stage is logged as 'Deploy OVF package from Content Library to Resource Pool', which seems to be some sort of file copy activity. The second stage is logged as 'Deploy OVF template'.

**Comment by ryancurrah** [comment]
We just finished a VMWare image building and testing pipeline that utilizes Packer, test-kitchen and Jenkins. We to we’re pleasantly surprised to find out vSphere has this little known feature called content libraries. The biggest advantage to it for us is remote content library support. This means we can manage images/templates on one vSphere instance and all the others can use it. Instead of having to upload the image to all instances. It would be a great addition for us.

**Comment by dougm** [comment]
Thanks Ryan, I didn't know about the remote support (still yet to use content library myself), but can see how that'd be a big win.

**Comment by cathode911** [comment]
Hey! Almost 10 months passed since issue was open, i am interested if there is any progress.
This issue affects Terraform's ability to provision VMs from content libraries (see above), which kind of blocks its usage in environments where legacy snapshots are forbidden (security etc.)

**Comment by rayabueg** [comment]
I'm curious how many others in the community are interested in this. We're trying to automate a workaround by using a powerCLI to deploy an VM then convert to a template, but would much rather access content library directly

**Comment by antaln** [comment]
The API used for deployment from Content Libraries is [vSphere Automation API](https://code.vmware.com/apis/191/vsphere-automation), a REST API separate from the vSphere SOAP API that govmomi implements.

Details of OVF deploy operation endpoint are described [here](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html).

Operation requires library item ID for the OVF to deploy from, so you'd also need to list [library](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/index.html#PKG_com.vmware.content.library) and [library items](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/index.html#PKG_com.vmware.content.library.item).

**Comment by antaln** [comment]
@rayabueg :+1:  definitely interested.

**Comment by Arderos** [comment]
Interested for sure

**Comment by antaln** [comment]
Content Library operations are predicated on use of a different API, so it seems that this is not something that should incorporated into govmomi's Clone(). I think what we really need are Go bindings for VSphere Automation API.

AFAIK govmomi is supposed to be a Go binding for vSphere SOAP API, so maybe the discussion should be pivoted to whether govmomi should also host bindings for vSphere Automation API, or if these bindings should be hosted in a different repository. Thoughts?

**Comment by dougm** [comment]
We recently added bindings for the tags API and plan to include content library bindings there too: https://github.com/vmware/govmomi/blob/master/vapi/doc.go

**Comment by antaln** [comment]
@dougm That resolves the dilemma, thanks! Is there a timeline for addition of the content library bindings? Can we contribute somehow?

**Comment by dougm** [comment]
@antaln thanks, happy to have folks contribute.  I still have yet to use content library at all myself.. it would be a great help to capture the workflow here.  GUI screenshots and/or PowerCLI examples that include:

- Creating a content library

- Adding a library item

- Any steps I'm missing

- Clone vm from library item

Mapping those workflows to the rest API docs would be bonus: https://code.vmware.com/apis/366/vsphere-automation

Then I think we can start by addressing this issue of for this particular issue of `vm.clone` from a library item.

We should probably open separate issues for managing the content library itself and just focus on clone source to start with.

**Comment by markpeek** [comment]
BTW, I have some initial code for content library support in progress. Over the weekend I'll see if I can get a PR put together with a working subset of functionality.

**Comment by kraihn** [comment]
> BTW, I have some initial code for content library support in progress. Over the weekend I'll see if I can get a PR put together with a working subset of functionality.

Hey Mark, what are your additions capable of so far? I'd love to see (and help if I can) content library support in place.

**Comment by akutz** [comment]
Hi @markpeek,

I'm currently blocked by lack of content library support in `govc`. I've been looking at [this blog post](http://blog.spinhirne.com/2017/04/vcenter-rest-api-and-content-library.html) that describes what I need to do via `curl`, which may be a path forward. However, I'd prefer to be able to do this natively with `govc`. I have some questions about your [WiP](https://github.com/markpeek/govmomi/commits/markpeek-contentlibrary) that you're hopefully able to answer:

1. Are you actively working on the PR?
2. If so, do you have an ETA?
3. Are the following workflows supported?
    * Import OVA to content library
    * Deploy VM from OVA in content library
    * Export VM to OVF via the content library
4. If you think you may not have the time to work on this PR in the near future, are you opposed to me or someone else taking it over?

Finally, I just wanted to offer my thanks to you for working on this.

**Comment by markpeek** [comment]
My apologies for the delay on this issue due to travel and other things coming up. Over the break I was finally able to get some time to work on the PR. @dougm and I will be going over the code next week to discuss some implementation questions and needed tweaks but hope to get it PR'd soon. Feel free to check out my WIP branch ([here](https://github.com/markpeek/govmomi/tree/markpeek-contentlibrary)). 

The workflow currently looks like this:
```
# Create a new content library
$ govc library.create main
6f887200-9ace-4bcc-b945-ab8a437f4c23

# Upload an OVA into the CL as a template
$ govc library.ova main photon-custom-hw11-2.0-304b817.ova
Found OVF file: photon-ova.ovf
Found OVF file reference: photon-ova-disk1.vmdk
Library item id: 3f88ef46-0c4f-4fae-8e85-4ed1e1e793db
Update session: e8c935ad-7050-4d36-9b2b-d5686a79bcc2:e3c1d243-b6ca-4df4-a780-0762f8fc3b5f
Uploading photon-ova.ovf from photon-custom-hw11-2.0-304b817.ova
Uploading photon-ova-disk1.vmdk from photon-custom-hw11-2.0-304b817.ova

# Deploy a CL template to a new VM
$ govc vcenter.deploy main photon-custom-hw11-2.0-304b817.ova photonvm
Using datastore ID datastore-11
Using pool ID resgroup-8
Found OVA for deployment: Photon OS
Deploy succeeded: vm-53

# List of new govc commands implemented
$ govc -h 2>&1 | grep -e library -e vcenter
  library.create
  library.info
  library.item.create
  library.item.file.info
  library.item.info
  library.item.ls
  library.item.rm
  library.item.update.cancel
  library.item.update.complete
  library.item.update.create
  library.item.update.fail
  library.item.update.get
  library.item.update.keepalive
  library.item.update.ls
  library.item.update.rm
  library.item.upload
  library.ls
  library.ova
  library.rm
  vcenter.deploy
```

**Comment by figo** [comment]
@markpeek thank you for the great work, i try to integrate your patch with the CI, one thing i noticed is: `vcenter.deploy` does not support customize resource pool, network, datastore, folder.

i think this is a common use case: ova been uploaded to content library (in a certain datastore), 
then VM been deployed to different resource pool and datastore.

Thanks

**Comment by akutz** [comment]
Hi All,

I'll be filing a PR against @markpeek's PR with some additional work I've been doing at https://github.com/akutz/simple-k8s-test-env/blob/feature/sk8-app/pkg/app/vsphere_library.go. It currently supports the following workflow:

1. Finds or creates a content library
2. Finds or creates a content library item
3. Finds or uploads an OVA to the content library item from a remote URI
4. Deploys a VM using the OVF from the content library

For example:

```shell
$ go test -v -run TestDeployOVF
=== RUN   TestDeployOVF
finding library...not found
creating library...success!
finding library item...not found
creating library item...success!
finding ovf...not found
uploading ova........success!
deploying ovf..............success!
--- PASS: TestDeployOVF (54.67s)
    vsphere_library_test.go:129: vm name=sk8-TestDeployOVF uuid=42304268-0299-c54a-f7cc-24f43c744d0a
PASS
ok      github.com/vmware/sk8/pkg/app    54.826s
```

![image](https://user-images.githubusercontent.com/101085/52311459-997fb100-296c-11e9-9578-ff8e3dc0497e.png)
