### ISSUE TITLE
Creating bare disk(vmdk) on datastore cluster

### ISSUE THREAD

**Issue by sudhirnir** [vmware/govmomi#740]
My use case is creating disk on datastore(a standalone vmdk not connected to any vm). How can I specify datastore cluster while creating bare vmdk? Is this possible? Thanks in advance for help :)

**Comment by dougm** [comment]
You can manually choose a datastore from within the cluster.

Not sure if SRM supports placement for that case, have you looked at
http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.StorageResourceManager.html ?

If this standalone vmdk is to be used for linked clones, you may want/need to copy it to all datastores in the cluster anyhow.  Is that your use case or something else?

**Comment by sudhirnir** [comment]
My use case is,

1) Create virtual disk of given size on datastore cluster. Though I can choose any datastore from the datastore cluster, but I don't want to do that just because I don't want to device my own algorithm of choosing best fit datastore for virtual disk that I am going to create. I thought, DRS will do it for me(Create Virtual Disk API).  
And then,

2) I want to attach this virtual disk to existing VM.

Isn't #1 possible? From other posts, I know that CreateVM can take DRS recommendations. Is there similar mechanism available for Create Virtual Disk?

**Comment by dougm** [comment]
I don't see anything that would prevent you from using StorageResourceManager for this case, but again not sure as I haven't tried myself. 
 Have you looked at this? https://github.com/vmware/govmomi/blob/master/govc/vm/create.go#L429
While it uses a VM spec as part of requesting a placement recommendation, it doesn't create a VM.

**Comment by sudhirnir** [comment]
Right, I looked at the example. Only after invoking ApplyStorageDrsRecommendation_Task, VM will be created. I was wondering, whether same is there for Create Disk. But haven't found anything for it.  recommendDatastore method supports create, clone, relocate, reconfigure "type" of operations, but those are for VM. I want similar for creating virtual disk, which would take virtual disk specs and datastore cluster ref, and return recommendations.

Do you expect, recommendDatastore to work for virtual disk too? which will take virtual disk specs and datastore cluster ref?

**Comment by dougm** [comment]
Like I said, haven't tried it myself, but looks like it should work for your case.

**Comment by sudhirnir** [comment]
@dougm Thanks.

**Comment by sudhirnir** [comment]
@dougm Sorry, I have not tried it yet. Will let you know once I give it a try.

**Comment by anukul-mohil** [comment]
@sudhirnir @dougm Did you have any success trying this?
I want to do something similar to this, but the ``ApplyStorageDrsRecommendation_Task`` requires recommended datastores using ``storageResourceManager.RecommendDatastores`` method which only operates on these [types](https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.storageDrs.StoragePlacementSpec.PlacementType.html) for StoragePlacementSpec. Therefore it seems one can only use this an existing VM.

**Comment by sudhirnir** [comment]
@anukul-mohil My use case was adding(create+attach) disks to existing VM. I used RecommendDatastores method which gave me recommendation. But ApplyStorageDrsRecommendation_Task is failing with error. "The request refers to an unexpected or unknown type.". Any clue @dougm @anukul-mohil ?

**Comment by sudhirnir** [comment]
Hi @harsh-px I was able to successfully create disk on given datastore cluster. Following is the flow 
1) Populate PodDiskLocator with disk specifications.
2) Populate VmPodConfigForPlacement with PodDiskLocator & StoragePod(i.e. datastore cluster reference).
3) Populate StorageDrsPodSelectionSpec.initialVmConfig with VmPodConfigForPlacement(added in vector)
4) Finally populate StoragePlacementSpec with vm reconfig spec & podSelectionSpec & specify operation as "reconfigure".
5) Call RecommendDatastores on StorageResourceManager giving input as  StoragePlacementSpec.
6) If there is no DRS fault generated, then get the recommendations & create ApplySDRSRecommendation task by giving any of the recommendation generated(i choose first one from  recommendations array).

**Comment by harsh-px** [comment]
@sudhirnir thanks, that worked !

**Comment by emocharnik** [comment]
@sudhirnir hi! I faced the same issue, but while I'm trying to clone new virtual machine from template and want to put new disks to different storage pods. API version 6.0

**Comment by prbobba** [comment]
> Hi @harsh-px I was able to successfully create disk on given datastore cluster. Following is the flow
> 
> 1. Populate PodDiskLocator with disk specifications.
> 2. Populate VmPodConfigForPlacement with PodDiskLocator & StoragePod(i.e. datastore cluster reference).
> 3. Populate StorageDrsPodSelectionSpec.initialVmConfig with VmPodConfigForPlacement(added in vector)
> 4. Finally populate StoragePlacementSpec with vm reconfig spec & podSelectionSpec & specify operation as "reconfigure".
> 5. Call RecommendDatastores on StorageResourceManager giving input as  StoragePlacementSpec.
> 6. If there is no DRS fault generated, then get the recommendations & create ApplySDRSRecommendation task by giving any of the recommendation generated(i choose first one from  recommendations array).

What will be the 'vm reconfig spec' in case of an independent disk?

**Comment by dougm** [comment]
Using VirtualDeviceList to build the spec will take care of this for you: https://github.com/vmware/govmomi/blob/b16d17160b3c9c4d6cd11b0cd44476d35c8bfb48/object/virtual_device_list.go#L919-L930

Example use: https://github.com/vmware/govmomi/blob/b16d17160b3c9c4d6cd11b0cd44476d35c8bfb48/govc/vm/disk/attach.go#L104-L129
