### ISSUE TITLE
Network info

### ISSUE THREAD

**Issue by anmakaro** [vmware/govmomi#742]
Hi guys.
I need getting all network's name and ID.  I tried get it via host, datacenter, vm. But i dont get anything except ID network.

**Comment by dougm** [comment]
Here's an example: https://github.com/vmware/govmomi/blob/master/examples/networks/main.go

**Comment by anmakaro** [comment]
Thanks for the link.
My thought was not complete. I mean getting all inform for network's witch CLI, in python. I writing code for console output from govc. But i don't get inform for network witch govc, becouse no command(example: govc network.info <nameNetwork>).  What to do?

**Comment by dougm** [comment]
```
govc find -type n | xargs -d '\n' -n1 govc object.collect
```
You can collect specific properties, see: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectcollect

**Comment by anmakaro** [comment]
Thank you!
Please tell me how to get the properties of any object selectively. For example "Name"

**Comment by dougm** [comment]
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#objectcollect

More examples:
```shell
% govc object.collect /dc1/network/my-network name

# specific property for all networks
% govc find -type n | xargs -d '\n' -I% govc object.collect -s % name                      
VM Network

# specific property for all resource pools
% govc find -type p | xargs -d '\n' -I% govc object.collect -s % name                      
Resources
dougm-vch
```

**Comment by anmakaro** [comment]
Thank!!!
