### ISSUE TITLE
Add optional "operationID" to vmomi calls

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#749]
Follow on from vmware/vic#2739

We've been needing to add a cross boundary correlation ID for some time - turns out that @derekbeard had noted the solution in the above issue but I'd not come back it since.
Please can this be added via optional `context.WithValue` - preferably with a runtime bound key so that we can easily couple the vic trace package and govmomi without having to hardcode the same key.

Original from derek:
> I tracked this down a bit more. I spoke with Kira on our team about how VCQE is able to log the opid. It turns out, that VC supports client-generated OpIDs, so VCQE generates it and passes it as an “operationID” SOAP element in the SOAP header. My guess is that we could update the govmomi SOAP client (https://github.com/vmware/govmomi/tree/master/vim25/soap) to pass an OPID generated upstream.

**Comment by dougm** [comment]
We can certainly do that.  Any pointers to the header name, value format we'd need to use?

**Comment by hickeng** [comment]
"operationID" was quoted in the email, so maybe it's as simple as that - if not I'd have to dig it up out of code which automatically makes it deferred until we actually start addressing the operation logging in the VIC side of things.
