### ISSUE TITLE
How to filter the received data?

### ISSUE THREAD

**Issue by anmakaro** [vmware/govmomi#751]
Hello. I'm writing a console application on a python and I need to filter the data it receives. For this purpose I used https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#find. But for some reason, I can not filter the data by the pool resource names (Example: govc find. -type m -resourcePool.name name). Tell me how to solve this problem? Thank you.

**Comment by dougm** [comment]
The resourcePool property is a ManagedObjectReference.. you can use another govc command to get the reference by name, such as `govc ls -i` or `govc find -i`:

```
govc find . -type m -resourcePool $(govc ls -i host/DC0_C0/Resources)
govc find . -type m -resourcePool $(govc find -i host/DC0_C0 -name Resources) 
```

**Comment by anmakaro** [comment]
Thanks you.
