### ISSUE TITLE
Filtering by resourcePool for vm

### ISSUE THREAD

**Issue by anmakaro** [vmware/govmomi#756]
Hi. I get a list of resource pools. I scroll through them, and at each iteration I try to get a list of virtual machine names filtered by the name of the current pool resource. But as a result, I get all the virtual machines.
I'm trying to implement with:

https://github.com/vmware/govmomi/issues/751
 govc find . -type m -resourcePool $(govc find -i /host/test -name RP123)
This command does not work correctly.

How do I get the names of virtual machines for the current pool resource?

Please, tell me the solution

**Comment by dougm** [comment]
Can you share some detail, what is the output of the 2 commands?  `/host/test` is not a valid inventory path, you'd need to use `host/cluster-name` or `/datacenter-name/host/cluster-name`.  Or just the root folder `/`

**Comment by anmakaro** [comment]
I get all VirtualMachines. Regardless of the binding to the ResourcePool. But if I specify the full path, everything works. Thank you!
