### ISSUE TITLE
Specifying host cluster instead of individual host when getting Host System returns error: "... resolves to multiple hosts".

### ISSUE THREAD

**Issue by jamesjmurtagh** [vmware/govmomi#758]
Assuming the cluster, "MyHostCluster", contains 2 hosts, "10.0.0.5" and "10.0.0.6":

`myHost, err := myFinder.HostSystem(ctx, "MyHostCluster")`
`
	if err != nil {
		return err
	}`

The above would return the error, whereas replacing the second argument with "MyHostCluster/10.0.0.5" would not. Is there any way to use the cluster instead of specifying the individual host? Various functions that I need to use within Govmomi require an "object.HostSystem" argument (for example, resourcepool.ImportVApp( ) ).

Edit: I should specify that the Cluster does have DRS & HA set up.

**Comment by dougm** [comment]
In the case of ImportVApp, the host param is optional.  So if you use 'nil', then vCenter will choose a host.  Likewise for any other method where the SDK documents a HostSystem type as optional - and its left up to vCenter to choose a host.

**Comment by jamesjmurtagh** [comment]
Thanks for the reply!

If I were to leave the host param nil, how would I be able to specify which host cluster it should be using?
It sounds like this solution would mean users are unable to specify a cluster, in a situation where multiple Host Clusters exist within the Datacenter.

**Comment by dougm** [comment]
You'd use the ResourcePool param to specify a cluster.

**Comment by jamesjmurtagh** [comment]
Oh, gotcha! Thank you so much.
