### ISSUE TITLE
Using govc guest.ps to monitor one installation process's status, error pop-up: ServerFaultCode: A general system error occurred: vix error codes = (3016, 0)

### ISSUE THREAD

**Issue by liboshi** [vmware/govmomi#759]
govc version: v0.15.0
Binary downloaded from govc release page.

`govc about`
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        3634794
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx

Detailed steps:

- Upload a batch script which is used to install some software to windows 7 x64 vm.
- Run command: `pid=$(govc guest.start -vm=vmNmae 'C:\Users\Public\install.bat')`
- Run command: `govc guest.ps -vm=vmName -p "pid" -X`

Waiting for while, there is an error pop-up:

> govc: ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).

I know that this error code means guest tool is not running. During execute above steps, I keep my eyes on the status of guest tools, it is running in whole process. As your reference.

Thanks in advance.

**Comment by dougm** [comment]
Any info in the VM's vmware.log file?

Does this happen without using the ps '-X' flag?  If so, possible that the command polls to often, you could try increasing the interval: https://github.com/vmware/govmomi/tree/master/toolbox#guestfilemanager-object

**Comment by liboshi** [comment]
I didn't use guest.ps without '-X' flag. So I cannot give a useful feedback now. I can give a try later.

part plain text of vmware.log:

> 2017-06-26T03:46:51.724Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=7312d631-20-afcc seq=8927: Completed GuestOps request.
> 2017-06-26T03:46:52.165Z| vmx| I120: VigorTransportProcessClientPayload: opID=db88a4-15-afd4 seq=8941: Receiving GuestOps.ListProcesses request.
> 2017-06-26T03:46:52.286Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=db88a4-15-afd4 seq=8941: Completed GuestOps request.
> 2017-06-26T03:46:52.635Z| vmx| I120: VigorTransportProcessClientPayload: opID=32a9f3b8-9a-afdb seq=8955: Receiving GuestOps.ListProcesses request.
> **2017-06-26T03:47:02.322Z| vmx| I120: GuestRpcSendTimedOut: message to toolbox timed out.**
> 2017-06-26T03:47:08.155Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=32a9f3b8-9a-afdb seq=8955: Completed GuestOps request.
> 2017-06-26T03:47:08.493Z| vmx| I120: VigorTransportProcessClientPayload: opID=585747e2-a1-b01a seq=9009: Receiving GuestOps.ListProcesses request.
> 2017-06-26T03:47:08.595Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=585747e2-a1-b01a seq=9009: Completed GuestOps request.
> 2017-06-26T03:47:08.908Z| vmx| I120: VigorTransportProcessClientPayload: opID=3a07bd04-9f-b021 seq=9023: Receiving GuestOps.ListProcesses request.
> 2017-06-26T03:47:09.169Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=3a07bd04-9f-b021 seq=9023: Completed GuestOps request.
> 2017-06-26T03:47:09.524Z| vmx| I120: VigorTransportProcessClientPayload: opID=48b25e80-87-b02d seq=9037: Receiving GuestOps.ListProcesses request.
> 2017-06-26T03:47:09.637Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=48b25e80-87-b02d seq=9037: Completed GuestOps request.
> 2017-06-26T03:47:09.913Z| vmx| I120: VigorTransportProcessClientPayload: opID=295c7bb5-7f-b034 seq=9051: Receiving GuestOps.ListProcesses request.
> 2017-06-26T03:47:09.995Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=295c7bb5-7f-b034 seq=9051: Completed GuestOps request.
> 2017-06-26T03:47:10.391Z| vmx| I120: VigorTransportProcessClientPayload: opID=13db53f9-b4-b03c seq=9065: Receiving GuestOps.ListProcesses request.
> 2017-06-26T03:47:10.486Z| vcpu-0| I120: VigorTransport_ServerSendResponse opID=13db53f9-b4-b03c seq=9065: Completed GuestOps request.

I mark failed step as blod.

**Comment by liboshi** [comment]
I used guest.ps without '-X' flag, cannot hit this issue. As the the interval is larger than default value with '-X' flag.
