### ISSUE TITLE
Find VM by UUID?

### ISSUE THREAD

**Issue by luomiao** [vmware/govmomi#764]
Hi there.
I saw there is a function with finder struct so we can get a VM by its name:
func (f *Finder) VirtualMachine(ctx context.Context, path string) (*object.VirtualMachine, error)

Is it possible to have similar function but the input is the UUID of a VM?
Or is there already a function to do so?

Thanks!

**Comment by dougm** [comment]
Hi @luomiao , yes, `SearchIndex.FindByUuid`: https://github.com/vmware/govmomi/blob/master/object/search_index.go#L123
