### ISSUE TITLE
Report maintenance mode in host.info command

### ISSUE THREAD

**Issue by zeisss** [vmware/govmomi#771]
It would be nice if the `host.info` command could also report, whether a host is in maintenance mode. As far as I can tell there are only commands to SET the maintenance mode (`host.maintenance.{enter,exit}`) but none to check for maintenance mode.

**Comment by dougm** [comment]
You can use the `-json` flag to see all the HostSystem properties:

```bash
govc host.info -json /ha-datacenter/host/esxbox.localdomain/esxbox.localdomain | jq .HostSystems[].Runtime.InMaintenanceMode
```

Another option:

```bash
govc object.collect -s /ha-datacenter/host/esxbox.localdomain/esxbox.localdomain runtime.inMaintenanceMode
```
