### ISSUE TITLE
govc vm.info -waitip=true vm.ip=<VM IP> fails with "no such vm"

### ISSUE THREAD

**Issue by govint** [vmware/govmomi#780]
I'm running a test where a VM is suspended and then resumed, immediately after its resumed I'm executing the command _govc vm.info -waitip=true vm.ip=< VM IP >_. Almost four times out of five I get the error "govc: no such vm".

Isn't the _-waitip=true_ supposed to wait for the VM to acquire an IP and then return VM data?

**Comment by dougm** [comment]
That's expected as a VM does not have any IP address property unless it is powered on:
 
```
% govc vm.info -vm.ip 192.168.2.174
Name:           govc-test-vm
  Path:         /ha-datacenter/vm/govc-test-vm
  UUID:         564d0fc6-ca2e-5a07-f553-46f54c8fc2ea
  Guest name:   Other (32-bit)
  Memory:       32MB
  CPU:          1 vCPU(s)
  Power state:  poweredOn
  Boot time:    2017-07-13 13:56:58.06374 +0000 UTC
  IP address:   192.168.2.174
  Host:         dougm-esxbox.localdomain

% govc vm.info -json -vm.ip 192.168.2.174 | jq . | grep 192.168.2.174 | wc -l                                                               
4

% govc vm.power -suspend -vm.ip 192.168.2.174
Suspend VirtualMachine:301... OK

% govc vm.info -json -vm.ip 192.168.2.174 | grep 192.168.2.174
govc: no such VM
                                                         
% govc vm.info -json /ha-datacenter/vm/govc-test-vm | grep 192.168.2.174 | wc -l                                                            
0
```

**Comment by govint** [comment]
@dougm, the VM is first resumed and then govc command is issued. Plus waitip option was provided.

Since the VM resume has already been initiated shouldn't govc have waited for the VM to get an IP?

**Comment by dougm** [comment]
It can't find the vm to wait for, since you used the `-vm.ip` flag and SearchIndex returns no results unless the vm is powered on.  If you were to use `-vm.uuid` or `-vm`, those flags work regardless of the power state.

**Comment by govint** [comment]
@dougm, thanks I'll try that. 👍
