### ISSUE TITLE
ContainerView is not returning up-to-date results

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#781]
We are seeing behaviour where the results from a ResourcePool backed view are not updated to reflect newly created VMs in that pool. The call is [here](https://github.com/vmware/vic/blob/69119f3de854f5c38d0c0eecf6d32d7c023b2235/pkg/vsphere/disk/disk_manager.go#L532).
In the failure case we would see logs of us checking the endpointVM which existed when the view was created. @jzt has mentioned that he sometimes saw the current code succeed and provide the data for the new VM, but I did not over the course of 20 or so attempts.

We currently have a work around whereby we create a new view for each call; that works as desired but is heavy on the control plane.

**Comment by dougm** [comment]
VC/ESX build numbers?  The example below works as expected for, seeing container VMs come and go with docker run/rm against a VCH.


```go
package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/vmware/govmomi/examples"
	"github.com/vmware/govmomi/property"
	"github.com/vmware/govmomi/view"
	"github.com/vmware/govmomi/vim25/mo"
)

func main() {
	ctx := context.Background()

	c, err := examples.NewClient(ctx)
	if err != nil {
		log.Fatal(err)
	}

	defer c.Logout(ctx)

	m := view.NewManager(c.Client)

	v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"ResourcePool"}, true)
	if err != nil {
		log.Fatal(err)
	}

	var pool []mo.ResourcePool

	err = v.RetrieveWithFilter(ctx, []string{"ResourcePool"}, []string{"name"}, &pool, property.Filter{"name": "*-vch"})
	if err != nil {
		log.Fatal(err)
	}

	v.Destroy(ctx)

	v, err = m.CreateContainerView(ctx, pool[0].Reference(), []string{"VirtualMachine"}, true)
	if err != nil {
		log.Fatal(err)
	}

	defer v.Destroy(ctx)

	for {
		var vms []mo.VirtualMachine

		err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms)
		if err != nil {
			log.Fatal(err)
		}

		for _, vm := range vms {
			fmt.Printf("%s: %s\n", vm.Summary.Config.Name, vm.Summary.Config.GuestFullName)
		}

		fmt.Println(strings.Repeat("-", 50))
		<-time.After(time.Second * 5)
	}
}
```

**Comment by hickeng** [comment]
@dougm I was running against ESX6.5 GA - don't have build number to hand.

**Comment by dougm** [comment]
ok, my tests were against ESX 6.5d (build 5310538).  I'll look into it some more against older versions too.

**Comment by hickeng** [comment]
We can switch the vmware/vic code back to the failing style and go from there if need be. @caglar10ur we'll need to track this down one way or another before release.

**Comment by dougm** [comment]
Looking into this issue led to some refactoring + govc features in #787

**Comment by dougm** [comment]
The test above works for me too against 6.5 GA (build 4564106).

**Comment by dougm** [comment]
Closing stale issues, feel free to open with more info.
