### ISSUE TITLE
govc vm.disk.create only adds disks with 10GB Size

### ISSUE THREAD

**Issue by claudekenni** [vmware/govmomi#783]
I'm trying to use govc to add a new disk to a VM and everytime the Disksize is just 10GB 
I tried via the parameter
-size= 
-> 20
-> 20G
-> 20GB
-> 20.0GB
-> 20.0G
and all the same without the '=' but every time the Disks gets created with 10GB size

Like this example:
govc vm.disk.create -vm.dns=$vm -name=$next_disk_name -ds=$ds_path -size $size

**Comment by dougm** [comment]
Does the example below work for you?

```console
% id=$(uuidgen)
% govc vm.create $id
% govc vm.disk.create -vm $id -name $id/data.vmdk -size 24GB                                                                                                                                                                                    
% govc device.info -vm $id disk-*                                                                                                                                                                                                               
Name:           disk-1000-0
  Type:         VirtualDisk
  Label:        Hard disk 1
  Summary:      25,165,824 KB
  Key:          2000
  Controller:   lsilogic-1000
  Unit number:  0
  File:         [datastore1] 8ede7b86-3d8f-4c0d-9853-962ed58fca06/data.vmdk
```

**Comment by claudekenni** [comment]
Doing it manually works
I'm using the following Script via Rundeck to add the Disk with looking at what the next disk number is

`#!/bin/bash 

export GOVC_URL='https://@option.vcenter@/sdk'
export GOVC_USERNAME="@option.username@"
export GOVC_PASSWORD='@option.password@'
export GOVC_INSECURE=1


vm="@option.hostname@"
size="20GB"

# Get the VM Path from the DNS Name
vm_path=$(govc vm.info -vm.dns=$vm | grep Path | awk '{print $2}')
echo $vm_path
# Get the VM JSON Parameters
vm_json=$(govc vm.info -vm.ipath=$vm_path -json=true)

# Get the number of attached disks
disk_num=$(echo $vm_json | jq .VirtualMachines[0].Layout.Disk[].DiskFile[0] | awk '{print $2}' | wc -l)

# Get the last disk number
next_disk_num=$((disk_num - 1))

# Get the base disk path/name
base_disk=$(echo $vm_json | jq -r .VirtualMachines[0].Layout.Disk[].DiskFile[0] | awk '{print $2}' | head -1 | sed 's/.vmdk//')

# Get the next disk name
next_disk_name=$base_disk\_$next_disk_num
echo $next_disk_name

#### DS
# Get the Datastore
ds=$(echo $vm_json | jq -r .VirtualMachines[0].Layout.Disk[].DiskFile[0] | head -1 | awk '{print $1}' | tr -d '[]')
echo $ds

# Get the Datastore Path
ds_path=$(govc ls -t datastore '*/*' | grep $ds)
echo $ds_path

# Add disk
govc vm.disk.create -vm.dns=${vm} -name={$next_disk_name} -ds=${ds_path} -size ${size}`

**Comment by claudekenni** [comment]
Just found the error. That Datastore Matches two so the size parameter is on a new line.

**Comment by maxadamo** [comment]
@claudekenni I am a bit puzzled by this:
`next_disk_num=$((disk_num - 1))`
is it a typo? Should it be `+` instead of `-` ?
