### ISSUE TITLE
How to obtain/set pciPassthroughSystem?

### ISSUE THREAD

**Issue by howels** [vmware/govmomi#788]
How can one access and manipulate the underlying Managed Objects, and is this possible for items that do not have an 'object' entry?

I've been searching for a while on this and can't see a clear answer. For advanced operations in PowerCLI and RbVmomi there was a way to get the underlying managed objects but I can't see how to get there with GoVmomi.

many thanks

**Comment by howels** [comment]
Found the route using property collectors I think.

**Comment by dougm** [comment]
Most of the examples for invoking managed object methods are in the various helpers here: https://github.com/vmware/govmomi/tree/master/object

You can also use the generated code directory without adding more of these helpers.  Here's an example to get you started:

```go
package main

import (
	"context"
	"log"

	"github.com/vmware/govmomi/examples"
	"github.com/vmware/govmomi/view"
	"github.com/vmware/govmomi/vim25/methods"
	"github.com/vmware/govmomi/vim25/mo"
	"github.com/vmware/govmomi/vim25/types"
)

func main() {
	ctx := context.Background()

	c, err := examples.NewClient(ctx)
	if err != nil {
		log.Fatal(err)
	}

	defer c.Logout(ctx)

	m := view.NewManager(c.Client)

	v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"HostSystem"}, true)
	if err != nil {
		log.Fatal(err)
	}

	defer v.Destroy(ctx)

	var hosts []mo.HostSystem
	err = v.Retrieve(ctx, []string{"HostSystem"}, []string{"configManager.pciPassthruSystem"}, &hosts)
	if err != nil {
		log.Fatal(err)
	}

	for _, host := range hosts {
		req := types.UpdatePassthruConfig{
			This: host.Self,
			Config: []types.BaseHostPciPassthruConfig{
				&types.HostPciPassthruConfig{
					Id:              "TODO: the id",
					PassthruEnabled: true,
				},
			},
		}

		_, err = methods.UpdatePassthruConfig(ctx, c.Client, &req)
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

**Comment by howels** [comment]
Thanks for posting the example, I found out how to access the managed objects in the end. Maybe there should be examples in the  top-level examples directory? I've managed to wrap my head around it now but having to call the methods apart from the managed objects which they are usually 'attached' to is not immediately obvious.
