### ISSUE TITLE
Add existing HDD to VM

### ISSUE THREAD

**Issue by byumov** [vmware/govmomi#790]
Hi! Sorry for i am asking here =\

I want to add existind HDD from one VM to another.

I am trying something like this. Get disks:

```
for _, device := range devices {
        currentDeviceLabel := device.GetVirtualDevice().DeviceInfo.GetDescription().Label
        if strings.Contains(strings.ToLower(currentDeviceLabel), "hard disk"){
        disks = append(disks, device)
    }    
return disks
```

And try connect received disk to another VM:
```
func addDisk(vm *object.VirtualMachine, disk types.BaseVirtualDevice) {

    ctx, cancel := context.WithCancel(context.Background())
    defer cancel()

    spec := types.VirtualMachineConfigSpec{

        DeviceChange : []types.BaseVirtualDeviceConfigSpec {

            &types.VirtualDeviceConfigSpec{

                Operation: types.VirtualDeviceConfigSpecOperationAdd,
                FileOperation: types.VirtualDeviceConfigSpecFileOperationCreate,
                Device: disk,
            },

        },
    }

    result, err := vm.Reconfigure(ctx, spec)
    if err != nil {
        log.Fatal(fmt.Sprintf("err: %s", err.Error()))

    }
```

I get error: `Cannot complete the operation because the file or folder [xxxxxx] xxxxxx/xxxxxx.vmdk already exists`
How i can add existing disk? Thanks!

**Comment by dougm** [comment]
Just don't specify FileOperation if the disk already exists.

The govc vm.disk.attach command does this using the VirtualDeviceList helpers: https://github.com/vmware/govmomi/blob/toolbox-archive/govc/vm/disk/attach.go#L64

In that command, CapacityInKB == 0, but in vm.disk.create CapacityInKB > 0:
https://github.com/vmware/govmomi/blob/master/object/virtual_machine.go#L390

**Comment by byumov** [comment]
@dougm, it helped, thank you!
