### ISSUE TITLE
Panic if object.VirtualMachine.Properties() attribute is 'Unset' on vCenter.

### ISSUE THREAD

**Issue by jamesjmurtagh** [vmware/govmomi#795]
EDIT: This was partly my mistake. I attempted to get 'guest.hostName', which was not set on my VM. The result was that 'o.Guest' came back nil - which I overlooked as I was trying to access 'o.Guest.HostName'. Problem solved - but I do wonder if the return value in this situation should contain NIL pointers?

Assuming 'instance' is of the type *object.VirtualMachine:
```
var o mo.VirtualMachine
err = instance.Properties(s.ctx, instance.Reference(), []string{"guest.hostName"}, &o)
if err != nil {`
	s.debug(fmt.Sprint(err))
	continue
}
```

The following code will cause a panic if the targeted VirtualMachine's 'hostName' is listed as 'Unset' on the ManagedObjectBrowser. Is this expected behaviour, or should an error be returned instead?

Thanks!

**Comment by dougm** [comment]
It isn't an error as far as the vsphere PropertyCollector is concerned.  It is expected and up to the caller to check.  I'll leave this open for now as we should document it at least.

**Comment by jamesjmurtagh** [comment]
Sounds good - thanks for the response :+1:
