### ISSUE TITLE
manager.Decode() method doesn't return Labels for license

### ISSUE THREAD

**Issue by girishramnani** [vmware/govmomi#797]
I am trying to fetch information about a key from the server using `Decode` method, but the 
info returned does not contain the Labels.
this is the code I have used.

```go

infos, _ := manager.List(context.TODO())

	for _, info := range infos {
		log.Println(info.Labels)
		in, _ := manager.Decode(context.TODO(), info.LicenseKey)
		log.Println(in.Labels)
	}

```

Output : 

```

2017/07/24 15:44:44 [{{} VpxClientLicenseLabel Girish Ramnan} {{} helloWorld slkdjfslkdfj}]
2017/07/24 15:44:44 []
2017/07/24 15:44:44 [{{} sdfsdf Sdfsd} {{} helloWorld slkdjfslkdfj}]
2017/07/24 15:44:44 []
2017/07/24 15:44:44 [{{} VpxClientLicenseLabel Sdfssdfdsd} {{} helloWorld slkdjfslkdfj}]
2017/07/24 15:44:44 []
2017/07/24 15:44:44 [{{} VpxClientLicenseLabel Hello World1} {{} TestTitle FooBar} {{} helloWorld slkdjfslkdfj}]
2017/07/24 15:44:44 []

```

VSPHERE edition - Version 5.5.0 Build 4063694

**Comment by dougm** [comment]
Are the labels included in the soap response?  You can use the vim25/debug package or something like:
```go
type RoundTripFunc func(*http.Request) (*http.Response, error)

func (rt RoundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return rt(r)
}

func main() {
        ctx := context.Background()
	c, err := examples.NewClient(ctx)
	if err != nil {
		log.Fatal(err)
	}

	defer c.Logout(ctx)

	t := c.Client.Transport
	c.Client.Transport = RoundTripFunc(func(req *http.Request) (*http.Response, error) {
		res, err := t.RoundTrip(req)
		b, _ := httputil.DumpResponse(res, true)
		os.Stderr.Write(b)
		return res, err
	})

```

**Comment by girishramnani** [comment]
Hi, the labels are not showing up in the decode license response.

**Comment by girishramnani** [comment]
following are the two responses 

1) add license response - https://gist.github.com/girishramnani/31d1cd9ff458191056f260ddf8ef5838
2) decode license response - https://gist.github.com/girishramnani/8f4a4fd1ca2583ad631774e5ea561014

**Comment by dougm** [comment]
Spent a little time with license labels recently.  This is expected, the labels are not encoded in the license key, just metadata stored in vCenter.  The `List()` method can be used to get the license labels, `Decode()` cannot.
