### ISSUE TITLE
vcsim: Deploy of OVA always fails

### ISSUE THREAD

**Issue by pdellaert** [vmware/govmomi#799]
When deploying an OVA using ovftool in a vcsim, it fails (not sure this is supported, would be useful at some level):

In vCenter mode:
```
$ ovftool --noSSLVerify --acceptAllEulas -ds=LocalDS_0 -n=TEST "--net:Nuage-VM-PG1=VM Network" Downloads/YVM-TEMPLATE.ova "vc://localhost:8989/DC0/host/DC0_C0"
Opening OVA source: Downloads/YVM-TEMPLATE.ova
Opening VMX target: vc://localhost:8989/DC0/host/DC0_C0
Error: Failed to create disk: vc://localhost:8989/DC0/host/DC0_C0/TEST.vmwarevm//TEST-disk1.vmdk. Reason: The system cannot find the file specified
Deleting directory tree below: vc:
Completed with errors
```

In ESXi mode:
```
$ ovftool --noSSLVerify --acceptAllEulas -ds=LocalDS_0 -n=TEST "--net:Nuage-VM-PG1=VM Network" Downloads/YVM-TEMPLATE.ova "vc://localhost:8989/ha-datacenter/host/localhost.localdomain"
Opening OVA source: Downloads/YVM-TEMPLATE.ova
Opening VMX target: vc://localhost:8989/ha-datacenter/host/localhost.localdomain
Error: Failed to create disk: vc://localhost:8989/ha-datacenter/host/localhost.vmwarevm//localhost-disk1.vmdk. Reason: The system cannot find the file specified
Deleting directory tree below: vc:
Completed with errors
```

ovftool version: 
```
$ ovftool -v
VMware ovftool 4.2.0 (build-4586971)
```

**Comment by dougm** [comment]
Right, ovf import isn't implemented by vcsim yet.

**Comment by pdellaert** [comment]
Thanks for the update, i guess this becomes a feature request then (it isn't a high priority, but definitely a nice to have)

**Comment by sivel** [comment]
Is there any chance of getting priority assigned to this feature request?  We'll be blocked in ansible merging a PR until after this functionality exists so that we can test effectively.

**Comment by remoe** [comment]
Does anyone have a workaround to put a template reference without upload the image? Currently I have the following error on terraform/vcsim:
```
data.vsphere_virtual_machine.template: error fetching virtual machine: vm '/DC0/host/example.com/template_coreos_production' not found
```

My goal is to run a server provisioning on vcsim without an error.

**Comment by dougm** [comment]
@remoe your path is using the `/host/` folder, but all VMs are underneath the `/vm/` folder.

**Comment by dougm** [comment]
@pdellaert @sivel finally added OVF manager support to vcsim, interested to hear if it works for your case(s).
