### ISSUE TITLE
unable to connect to VC when https port is not 443

### ISSUE THREAD

**Issue by divyenpatel** [vmware/govmomi#802]
As per GOVC documentation, we do not require to specify the PORT number in the GOVC URL.

https://github.com/vmware/govmomi/tree/master/govc
```
GOVC_URL: URL of ESXi or vCenter instance to connect to.

    The URL scheme defaults to https and the URL path defaults to /sdk. This means that specifying user:pass@host is equivalent to https://user:pass@host/sdk.

    If password include special characters like # or : you can use GOVC_USERNAME and GOVC_PASSWORD to have a simple GOVC_URL

    When using govc against VMware Workstation, GOVC_URL can be set to "localhost" without a user or pass, in which case local ticket based authentication is used.

GOVC_USERNAME: USERNAME to use if not specified in GOVC_URL.

GOVC_PASSWORD: PASSWORD to use if not specified in GOVC_URL.
```

I have a vCenter Port Configured to 7443

```
$ GOVC_USERNAME='Administrator@vsphere.local'
$ GOVC_PASSWORD='Admin!23'
$ GOVC_URL=10.192.58.44
```

govc ls is timing out, as it is trying to connect to 443

```
$ govc ls
govc: Post https://10.192.58.44/sdk: dial tcp 10.192.58.44:443: getsockopt: operation timed out
```

Version: 
```
$ govc version
govc 0.15.0
```

when tried to connect with following GOVC URL, I am able to connect to the vCenter.
```
$ export GOVC_URL='https://Administrator@vsphere.local:Admin!23@10.192.58.44:7443/sdk'
$ govc ls
/Datacenter/vm
/Datacenter/network
/Datacenter/host
/Datacenter/datastore
```

Do we need to update GOVC documentation?
Is this behavior recently changed?

@luomiao @BaluDontu @tusharnt

**Comment by dougm** [comment]
You just need to specify the 'http' scheme, otherwise it defaults to 'https'.
```
export GOVC_URL=http://10.192.58.44
```

**Comment by divyenpatel** [comment]
Its giving 404
```
$ export GOVC_USERNAME=Administrator@vsphere.local
$ export GOVC_PASSWORD='Admin!23'
$ export GOVC_URL=http://10.192.58.44
$ export GOVC_INSECURE=1
$ govc ls
govc: 404 Not Found
```

**Comment by divyenpatel** [comment]
We made a fix sometimes before in Kubernetes and removed port number from the VC URL.
Here is the PR: https://github.com/kubernetes/kubernetes/pull/42024/files

If we do not specify port then the default configured port was automatically getting picked up.
but recently we observed automatic redirection to configured port is not happening.

Anything related to this behavior changed in the govmomi recently?

**Comment by dougm** [comment]
No, govmomi hasn't changed any thing related.  Via the Go http client, it defaults port *80* for *http* and port *443* for *https*.  And "/sdk"
 is the default path: https://github.com/vmware/govmomi/blame/master/vim25/soap/client.go#L86

If you specify a different port, it'll use it (see below).  If VC or ESX sends a redirect response, the Go http client will follow the redirect.  The "404 Not Found" error is not a govmomi issue.

```console
% vcsim
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=3219

% govc about -u https://user:pass@127.0.0.1:8989/sdk
Name:         VMware vCenter Server (govmomi simulator)
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        3634794
OS type:      linux-amd64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx
UUID:         8e7597d6-f720-4b5c-b9fc-3412faf07d99

% vcsim -tls=false
export GOVC_URL=http://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=3254

% govc about -u http://user:pass@127.0.0.1:8989/sdk
Name:         VMware vCenter Server (govmomi simulator)
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        3634794
OS type:      linux-amd64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx
UUID:         8e7597d6-f720-4b5c-b9fc-3412faf07d99
```
