### ISSUE TITLE
'govc pool.create' does not work with flags with 0 or no flags specified

### ISSUE THREAD

**Issue by amandafeng001** [vmware/govmomi#804]
`govc pool.create .../mypool` or 
`govc pool.create -cpu.expandable=true -cpu.limit=0 -cpu.reservation=0 -cpu.shares=normal -mem.expandable=true -mem.limit=0 -mem.reservation=0 -mem.shares=normal .../mypool` returns this error:
govc: ServerFaultCode: A specified parameter was not correct:

As Doug mentioned, a workaround can be `govc pool.create -cpu.limit=-1 -cpu.reservation=1 -mem.limit=-1 -mem.reservation=1 /.../mypool`

**Comment by dougm** [comment]
Note that this is only an issue against vCenter, works as expected against ESX.
