### ISSUE TITLE
Need to create a vCenter user using govmomi or GOVC

### ISSUE THREAD

**Issue by divyenpatel** [vmware/govmomi#807]
I see `govc host.account.create` allows creating new ESXi user on the host.

I could not find anything to create new user on vCenter server. Is it possible to create a new vCenter user using govmomi or govc?

@SandeepPissay @tusharnt @dougm

**Comment by dougm** [comment]
There is no public API that I'm aware of.  Last I heard, dir-cli was the only option:

http://www.virtuallyghetto.com/2015/05/vcenter-server-6-0-tidbits-part-9-creating-managing-sso-users-using-dir-cli.html

**Comment by divyenpatel** [comment]
Thank you @dougm for the information.

**Comment by dougm** [comment]
Also need this for testing in #1064

**Comment by dougm** [comment]
@divyenpatel can you share your use case(s)?

**Comment by tthayer** [comment]
I have a use case where we have a lab vSphere instance that isn't tied to our SSO system and we get infrequent requests to create new users in the system as part of an "intro to devops" onboarding. I think being able to add things via `govc vc.sso.user.add -id 'testuser' -domain 'domain.local' -password 'whatever' -groups 'limitedusers,devgroup'` would be extremely helpful in this regard. I recognize group membership is a two-part so doing that via a second command after the account has been created wouldn't be too bad since the intent is to have this automated.

**Comment by divyenpatel** [comment]
@dougm while developing automation for [Enabling vSphere Cloud Provider](https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/README.md), we had a requirement to create a new VC user and assign required roles and privileges to this new user created by automation. 

If automation creates a new user and assign system generated password, it's kind of more secure than what we are doing currently - Asking user to specify username and password of existing user in the configuration file.

**Comment by lubronzhan** [comment]
@dougm  

Hi.

I tried to used the `govc sso.user.create`  with govc binary generated on the master branch. 

So I run it against vsphere 6.5 U1. and with correct `GOVC_USERNAME` and `GOVC_PASSWORD`, but I keep getting `govc: ServerFaultCode: NotAuthenticated`. Do you know what could be the problem

**Comment by dougm** [comment]
@lubronzhan the ssoadmin endpoint has its own Login method that requires a SAML token.  Planning to address this before the next release so it is transparent, but for now you need to set the `GOVC_LOGIN_TOKEN` var.  For example:

``` console
% GOVC_LOGIN_TOKEN=$(govc session.login -issue) govc sso.user.create ...
```

**Comment by apalcloud** [comment]
hello @dougm can govmomi create a vCenter user or not now?
If not, do you have any link/sample to create a vCenter user by govc?
Thanks.

**Comment by dougm** [comment]
hello @apalcloud in general, if govc can do it, then so can govmomi.

govc usage: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#ssousercreate

source for the command: https://github.com/vmware/govmomi/blob/a0562d0215a1b98ba4a6695cc48bcc57faf3b0cd/govc/sso/user/create.go#L157

**Comment by apalcloud** [comment]
Thanks @dougm. govc works for me. But I didn't find the way to list user/role assignment in govc, are you aware of anything like this to list the role/permission grant?

**Comment by apalcloud** [comment]
Well I take it back, role.usage works for me. Thanks @dougm !!

**Comment by apalcloud** [comment]
Hi @dougm I found "govc cluster.group.ls" doesn't return any groups, though there're many groups when I run "sso.user.id". Is there a clue how to list and assign user/group memberships in govc?

**Comment by dougm** [comment]
@apalcloud cluster groups are not related to users.  We could probably add an `sso.group.ls` and related commands, can you open a new issue for that?

**Comment by apalcloud** [comment]
@dougm https://github.com/vmware/govmomi/issues/1483.
It would be really nice to have all sso suports in govc. Now we have to jump between govc and dir-cli to manage sso objects which is painful.
