### ISSUE TITLE
govc vm.info doesn't show all network interfaces/ip address

### ISSUE THREAD

**Issue by pathcl** [vmware/govmomi#812]
Let's say I have this vm with 3 ip address (can be aliases or network interfaces)

{'annotation': '.',
 'datacenter': '',
 'dns': '',
 'host': 'somehost.domain.tld',
 'instanceuuid': '5011e380-38ae-8719-2348-2369bdece5c3',
 'ipaddr': '172.30.10.31 172.30.10.30 172.30.10.29',
 'name': 'somevm',
 'numcpu': 2,
 'numdisks': 2,
 'numethernet': 1,
 'os': 'Ubuntu Linux (64-bit)',
 'pathname': '[VMFS-01] '
             'some/some.vmx',
 'powerstate': 'poweredOn',
 'ram': 2048,
 'resourcepool': 'Resources',
 'toolsstatus': 'toolsOk',
 'totalhd': 80,
 'vdc': ''}

If I do 'govc vm.info vm' it will only show 1 nic:

Name:           somevm
  Path:         /some/path
  UUID:         42111bd9-7527-c91e-398c-314651e75541
  Guest name:   Ubuntu Linux (64-bit)
  Memory:       2048MB
  CPU:          2 vCPU(s)
  Power state:  poweredOn
  Boot time:    <nil>
  IP address:   172.30.10.29
  Host:         somehost

I was able to iterate through 'virtual_machine.guest.net' to get all ip address on pyvmomi so it should be easy doing this on govmomi. I tried two cases: multiple ip aliases and more than one network interface. Results are the same.

**Comment by dougm** [comment]
You can use `govc vm.ip -a` to list all IPs. There are also examples in the doc on how you could use `vm.info -json`: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#vmip

**Comment by pathcl** [comment]
@dougm that is neat! thank you. I should've had done rtfm before.

**Comment by linit01** [comment]
What-if I do not have the VM name and only the IP?  For example I have an Ansible host file with IPs and the IP in the host file is on the 2nd or 3rd interface.  Since the vm.info only shows the 1st interface I cannot search for the VM name using the IP in the host file.  I cannot use vm.ip -a since it only give IPs as a result.

**Comment by doublespaces** [comment]
> What-if I do not have the VM name and only the IP? For example I have an Ansible host file with IPs and the IP in the host file is on the 2nd or 3rd interface. Since the vm.info only shows the 1st interface I cannot search for the VM name using the IP in the host file. I cannot use vm.ip -a since it only give IPs as a result.

For people that have this question, you may search by secondary IP this way:

govc vm.info -vm.ip=1.2.3.4
