### ISSUE TITLE
TLS handshake timeout error

### ISSUE THREAD

**Issue by jramacha** [vmware/govmomi#814]
Hi, I wanted to start using govmomi for managing our inventory, I tried to do a test but getting this error any help is appreciated.
root@xxxx:~/work/src/github.com/vmware/govmomi/examples/datastores# go run main.go -url https://domain\user:password@xxxx.yyy.zzzz.com -insecure true

2017/08/16 15:12:19 Post https://xxxx.yyyy.zzzz.com/sdk: net/http: TLS handshake timeout
exit status 1
I also don't understand how the /sdk got appended to my virtual center url.
My go version is
root@xxxx:~/work/src/github.com/user/hello# go version
go version go1.8 linux/amd64

Thanks

**Comment by dougm** [comment]
"/sdk" is the default path: https://github.com/vmware/govmomi/blob/2cad15190b417804d82edb4981e7b3e62907c4ee/vim25/soap/client.go#L102-L105

Are you able to connect with curl?

```
% curl --verbose -k -X POST https://xxxx.yyyy.zzzz.com/sdk
```

**Comment by jramacha** [comment]
Thanks, got return code 200. Do you know what could be the issue?
 `curl --verbose -k -X POST https://domain/user:password@xxxx.yyyy.zzzz.com/sdk
*   Trying xx.xx.xx.xx...
* Connected to .... port .. (#0)
* Establish HTTP proxy tunnel to xxxx.yyyy.zzzz.com:443
* Server auth using Basic with user 'domainuser'
> CONNECT xxxx.yyyy.zzzz.com:443 HTTP/1.1
> Host: xxxx.yyyy.zzzz.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* found 179 certificates in /etc/ssl/certs/ca-certificates.crt
* found 716 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
`
^C

**Comment by dougm** [comment]
You've connected to a proxy, which must be set in your environment.  Looks like you didn't get a response after making the proxy connection with curl either.. if you hadn't ^C'd, curl would have also timed out.

**Comment by jramacha** [comment]
Thanks, I tried again without cancelling it got an exception .. so I guess I have look into the firewall?
Aslo tried with --insecure in curl
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: xxxx.yyyy.zzzz.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=..,ST=xx,L=xxxx,O=xxxxxx,OU=xxx,CN= xxxx.yyyy.zzzz.com
*        start date: Mon, 17 Jul 2017 15:13:24 GMT
*        expire date: Fri, 15 Sep 2017 15:13:24 GMT
*        issuer: C=..,ST=xx,L=xxx,O=xxx,OU=xxx,CN=xxxxxx
*        compression: NULL
* ALPN, server did not agree to a protocol

...
< HTTP/1.1 503 Service Unavailable
< Cache-Control: no-cache

**Comment by jramacha** [comment]
Interestingly I am able to connect using pyvmomi from the same machine . Could it be something else?
`/work/src/github.com/user/hello# python                                                                                    Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyVim
>>> from pyVim.connect import SmartConnect, Disconnect
>>> from pyVmomi import vmodl
>>> import pyVmomi
>>> import ssl
>>> ssl._create_default_https_context=ssl._create_unverified_context
>>> host="xxxx.yyyy.zzzz.com"
>>> user='domain\user'
>>> pwd='xxxx'
>>> SmartConnect(host=host,
...                               user=user,
...                               pwd=pwd,
...                               port=443)
'vim.ServiceInstance:ServiceInstance'
`

**Comment by dougm** [comment]
You had already turned off ssl verify using the `-insecure` flag.

Any details on your proxy and what version of vCenter?

Can you connect using httpstat?  https://github.com/davecheney/httpstat/releases/tag/v1.0.0

```
httpstat -k -L -X POST -d - https://xxxx.yyyy.zzzz.com/sdk
```

**Comment by jramacha** [comment]
Will figure out.
Thanks

**Comment by dougm** [comment]
@jramacha did you figure it out?

**Comment by jramacha** [comment]
Nope :( 
httpstat -k -L -X POST -d - https://VC.domain.xxxx.com/sdk
Connected to xx.xx.xx.xx:443 from yy.yy.yy.yy:PORT

HTTP/1.1 500 Internal Server Error
Date: Tue, 3 Oct 2017 18:27:38 GMT
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: text/xml; charset=utf-8
X-Frame-Options: DENY
Content-Length: 552

Body stored in: /tmp/tmpFeGe89

  DNS Lookup   TCP Connection   Server Processing   Content Transfer
[     4ms    |       2ms      |        3ms        |        0ms       ]
             |                |                   |                  |
    namelookup:4ms            |                   |                  |
                        connect:6ms               |                  |
                                      starttransfer:313ms            |
                                                                 total:313ms

**Comment by jramacha** [comment]
I am going to look into our proxy setup.

**Comment by jramacha** [comment]
It was the proxy. I am getting a repose from vCenter now.

**Comment by jramacha** [comment]
Thanks for your input on this

**Comment by dougm** [comment]
@jramacha ok glad you got it resolved
