### ISSUE TITLE
vm.clone -on switch issue

### ISSUE THREAD

**Issue by cseeger-epages** [vmware/govmomi#816]
The -on switch for vm.clone is a bool an can not be set to false since the default is true.
If i use vm.clone without on switch it will poweron by default.
If i use vm.clone with on switch it will poweron by using the on flag.
There is no possibility to set it to false.

**Comment by dougm** [comment]
Use: `-on=false`

**Comment by cseeger-epages** [comment]
thanks this worked :+1:  . I tried it without `=` since i use all parameters without it but for -on switch a `-on false` seems not to work. Thanks, i will close this issue.
