### ISSUE TITLE
Unable to add license 

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#818]
When trying to add Licence using govcsim, we get following error 

```
# govc license.add 00000-00000-00000-00000-00001
govc: ServerFaultCode: LicenseManager:LicenseManager does not implement: AddLicense
```

**Comment by Akasurde** [comment]
@dougm Any news on this ?

**Comment by anfernee** [comment]
@Akasurde I will be working on this first. stay tuned.

**Comment by Akasurde** [comment]
@anfernee Thanks.

**Comment by Akasurde** [comment]
@anfernee @dougm Thanks for your help and time.
