### ISSUE TITLE
Deploy a new virtual machine based on a snapshot of a powered-on VM

### ISSUE THREAD

**Issue by angystardust** [vmware/govmomi#825]
Using **PowerCLI**, i can deploy a new vm based on a snapshot of a powered-on VM using the following command:
`New-VM -Name <new_vm_name> -VM <name_of_VM_with_snapshot> -Datastore <LUN_to_deploy_new_VM> -VMHost <Host_where_to_deploy_new_VM> -clone -ReferenceSnapshot <display_name_of_the_open_snapshot>`

It would be great if **govc** can also implement this useful feature.

Reference: http://www.running-system.com/deploy-vm-based-on-snapshot-of-powered-on-vm/

**Comment by dougm** [comment]
Sounds like this is in PR #762 

I plan to review soon, if you could do that would be great.

**Comment by dougm** [comment]
This is supported now via #762 and #877 
```
govc vm.clone -vm template-vm -snapshot s-name new-vm
```
