### ISSUE TITLE
json output does not work with "govc find"

### ISSUE THREAD

**Issue by acortiana** [vmware/govmomi#826]
It seems that the json output is not implemented for the "find" function.
The help command says that the json output option is available:

./govc find --help
Usage: ./govc find [OPTIONS] [ROOT] [KEY VAL]...
[...]
Options:
  -cert=                          Certificate [GOVC_CERTIFICATE]
[...]
  -json=false                     Enable JSON output

But it doesn't work.

**Comment by dougm** [comment]
Yeah, the `-json` flag has snuck into more places than it is supported, since `OutputFlag` was added to `DatacenterFlag`.  We could add support for it though to the find command.

**Comment by acortiana** [comment]
Yes, it can be useful.
`govc find` is the only way to extract all VMs on a vcenter and can be useful to have json option implemented.
