### ISSUE TITLE
Is it possible to call RefreshStorageSystem?

### ISSUE THREAD

**Issue by acortiana** [vmware/govmomi#827]
I need to issue the RefreshStorageSystem call on the vcenter using govc.
Is it possible?
This call is needed when, for example, you change something via esxcli directly on the host and you want the vcenter to refresh storage information.

**Comment by dougm** [comment]
Would `govc host.storage.info -rescan` work for you in this case?
https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#hoststorageinfo

It is possible to call the refresh method:
```go
	ss, err := host.ConfigManager().StorageSystem(ctx)
	if err != nil {
		return err
	}

	req := types.RefreshStorageSystem{
		This: ss.Reference(),
	}

	_, err = methods.RefreshStorageSystem(ctx, ss.Client(), &req)
```

If you're wanting to do that from govc, we could add a `-refresh` option to the command above.

**Comment by acortiana** [comment]
`govc host.storage.info -rescan` does not call the RefreshStorageSystem method.
IMHO is needed a refresh option, as you suggest.
