### ISSUE TITLE
Issue with trying to insert an img to a  floppy drive

### ISSUE THREAD

**Issue by rzubin** [vmware/govmomi#831]
I am trying to insert an img to a floppy drive. The img is in a datastore.
I have tried the following
`govc device.floppy.insert -vm windows-minimal-vm --device floppy-842356020680 -ds datastore-1 vmware-win-2016-core.img`

I moved the img to the VM directory and then tried 
`govc device.floppy.insert -vm windows-minimal-vm windows-minimal-vm/vmware-win-2016-core.img`

But every time I power on the VM I get the below error 
`Could not connect to floopy drive. Correct the configuration and then connect to virtual floppy drive` 

Is there something I am missing?

Thanks

Zubin

**Comment by dougm** [comment]
`floppy-842356020680` looks like the device **Summary** rather than the **Name**.

Can you verify the image is in the right location:
`govc datastore.ls windows-minimal-vm/vmware-win-2016-core.img`

Is the "Could not connect to floopy drive..." message from govc or something else?

**Comment by rzubin** [comment]
hey @dougm, I did try without the --device and still the same result. There is only 1 floppy drive attached to the Vm
```
govc device.floppy.insert -vm windows-minimal-vm  -ds datastore-1 vmware-win-2016-core.img
```
Below is the datastore.ls output
```
govc datastore.ls -ds=datastore-1 -R=true
[c05n08.local.bo1] windows-minimal-vm/:
windows-minimal-vm.vmdk
vmware-win-2016-core.img
windows-minimal-vm.nvram
windows-minimal-vm.vmsd
vmware-3.log
vmware-2.log
vmware-1.log
windows-minimal-vm-flat.vmdk
vmware.log
vmware-5.log
vmware-4.log
windows-minimal-vm.vmx
```
```
govc datastore.ls -ds datastore-1  windows-minimal-vm/vmware-win-2016-core.img
vmware-win-2016-core.img
```
The "Could not connect to floopy drive"  is a message in the vsphere events tab.

Thanks

Zubin

**Comment by rzubin** [comment]
Hey @dougm 
Just some playing around and this seemed to work 
```
govc device.floppy.insert -vm windows-minimal-vm -ds datastore-1  windows-minimal-vm/vmware-win-2016-core.img
```

**Comment by dougm** [comment]
ok great @rzubin !
