### ISSUE TITLE
datastore.upload broken pipe

### ISSUE THREAD

**Issue by cseeger-epages** [vmware/govmomi#832]
when i try to upload an iso image to a datastore i get a 
```
govc datastore.upload -dc datacenter -ds iso_images centos-7-vmware.iso isos/centos-7-vmware.iso
govc: Put https://<vcenterurl>/folder/isos/centos-7-vmware.iso?dcPath=%2Fdatacenter&dsName=iso_images: write tcp <sourceip>:<sourceport>-><destip>:443: write: broken pipe
```
error. The iso file is only an ipxe kickstart file with 1M size.

**Comment by dougm** [comment]
Is the file created at all in the datastore?  Any errors in `govc logs` ?  You can also specify a `-host` param to datastore.upload and `govc logs -host ...` to see the hostd logs.

**Comment by cseeger-epages** [comment]
@dougm Yes the files are there and should be overwritten on upload. I use the following code:
```
for iso in dist/ipxe/builds/*.iso;       
do         
  govc datastore.upload -dc datacenter -ds iso_images $iso isos/$(basename $iso);         sleep 2;       
done
```
The first one or two isos sometimes work and then i mostly get the broken pipe error, and sometimes (dont know if there is a ratelimiting or some kind of evasive sth) a 401 Unauthorized.

I dont see anything in the logs what indicates an error (or even has sth to do with the upload)

can you explain how the host param works ? i tried `host <fqdn>`, `host <ip>`, `host=<fqdn>` and `host=<ip>` and i always get
```
govc: flag provided but not defined: -host
```

**Comment by dougm** [comment]
`-host` can be the HostSystem name or inventory path.  You can get a list of hosts that have the datastore mounted using:
```
govc find . -type h -datastore $(govc find -i ./datastore -name iso_images)
```

**Comment by dougm** [comment]
Closing stale issues, feel free to open with more info.
