### ISSUE TITLE
Add support to generate VMRC link

### ISSUE THREAD

**Issue by T4cC0re** [vmware/govmomi#833]
Hi,

in the vSphere Web Client (v5.5.0) you have the option to open a VM in VMWare Remote Console (VMRC) via an application link (e.g. `vmrc://clone:LONGSTRING@VCENTER:443/?params`).
It would be totally awesome if we could generate such a link via govmomi/govc.

Is this feature possible to implement?

**Comment by dougm** [comment]
Yes, we could do that, I'll try to take a look soon.  We already have `vm.vnc` and I've been meaning to add `vm.screen` to generate the screen capture (currently in govc.el only).

**Comment by T4cC0re** [comment]
I confirm that #840 adds it in the desired way :)
