### ISSUE TITLE
Removing CPU reservations does not work with sending 0

### ISSUE THREAD

**Issue by X4mp** [vmware/govmomi#836]
It is not possible to clear (set 0) any preset CPU reservations. Setting the reservation to 0 in the `ResourceAllocationInfo` will remove the field from the xml body since it is marked as `omitempty`.
[types.go](https://github.com/vmware/govmomi/blob/master/vim25/types/types.go)

By removing `omitempty` from the reservation field in `ResourceAllocationInfo` this can be solved immediately.

**Comment by dougm** [comment]
Yes, we need to change the fields to pointers.

Related: #804 #741

**Comment by X4mp** [comment]
Awesome! Any chance to get this into upstream asap?

**Comment by dougm** [comment]
@X4mp if you could review the PR that'd be great, thanks.
