### ISSUE TITLE
Support Application monitor in toolbox

### ISSUE THREAD

**Issue by emlin** [vmware/govmomi#837]
Need to have application monitor function works in toolbox, so that VIC engine could integrate docker health check with vSphere HA
Searched the vSphere 6.5 SDK, application monitor is still there.

**Comment by dougm** [comment]
Link to the SDK doc?

Link to the VIC issue?

Any examples of how this works with standard vm guest tools?

**Comment by emlin** [comment]
is working on the health check feature decomposition right now. 
https://github.com/vmware/vic/issues/6333 relies on this issue

https://docs.vmware.com/en/VMware-vSphere/6.5/vsphere-esxi-vcenter-server-65-availability-guide.pdf is the document described application HA, but what I found for the API is written in C, so does not help on your code.

**Comment by emlin** [comment]
https://vdc-download.vmware.com/vmwb-repository/dcr-public/4ac029aa-34ad-46b1-9b60-d2603b426d6e/62af2377-9649-4707-88a7-6e4b3df5376d/vsphere-guest-ha-monitoring-sdk-65-programming-guide.pdf
this is what I found

**Comment by dougm** [comment]
When I had started too look at this back then, didn't look like toolbox changes were required.

**Comment by emlin** [comment]
@dougm hmm... didn't check this issue for quite some time. Could you please help to elaborate a little bit on it?

**Comment by dougm** [comment]
@emlin app HA is provided in the GuestSDK, not by guest tools.
