### ISSUE TITLE
Finder/fields with slashes unmarshaling issue

### ISSUE THREAD

**Issue by vancluever** [vmware/govmomi#844]
Hey all,

This is kind of a continuation of #734 and possibly even more. It looks like the slash matching that was added with this commit is not working 100%, main reason being is that paths are fetched URL escaped.

Example: A network named `my-net/work` actually shows up as `my-net%2fwork`, illustrated by this debug log message I put into `recurser.go`:

```
2017/09/19 20:06:12 [DEBUG] could not find path: port/group, trying to locate against /hashi-dc/network/port%2fgroup
```

Unescaping the string fixes this, but I think this opens another whole can of worms here as the object is not only coming back with an escaped name here, but also seemingly in other fields such as the actual name of the network, etc:

```
2017/09/19 20:24:57 [DEBUG] mvm.Guest.Net - []types.GuestNicInfo{types.GuestNicInfo{DynamicData:types.DynamicData{}, Network:"port%2fgroup", IpAddress:[]string{"172.16.1.150", "fe80::250:56ff:fe94:e26c"}, MacAddress:"00:50:56:94:e2:6c", Connected:true, DeviceConfigId:4000, DnsConfig:(*types.NetDnsConfigInfo)(nil), IpConfig:(*types.NetIpConfigInfo)(0xc420521830), NetBIOSConfig:types.BaseNetBIOSConfigInfo(nil)}}
```

I wonder if this is a deeper thing where fields with slashes in certain respects are being escaped in the API and will need to be unescaped on unmarshaling or something. Thoughts?

Related: terraform-providers/terraform-provider-vsphere#165

**Comment by dougm** [comment]
How did you create the network?  We have a test here:
https://github.com/vmware/govmomi/blob/master/govc/test/vm.bats#L665-L671

Maybe the UI escapes '/' when creating?

**Comment by vancluever** [comment]
Hey @dougm - this indeed was added through the web client - I will try again with govc later on today.

Is there an easy path for someone (me, you) to submit a bug for the web client for this then?

**Comment by dougm** [comment]
ok, that might be as-designed and my bad for only testing with the API and not the UI.  Though I had expected the API to validate the name doesn't include a '/' if that was the case.  I'll look into it today.

**Comment by dougm** [comment]
Using 6.5U1, the ESX UI does not encode '/', but the vCenter HTML5 UI does.  I created a DVPG named "dougm/net".  Confirming what you see:

```console
% govc find / -type n                                                                                                                       
/dc1/network/dougm%2fnet
/dc1/network/InternalNetwork
/dc1/network/PublicNetwork
/dc1/network/DSwitch-DVUplinks-9
/dc1/network/VM Network

% govc vm.create -net dougm%2fnet dougm-test

% govc vm.info -r dougm-test
Name:                   dougm-test
  Path:                 /dc1/vm/dougm-test
...
  Storage:              vsanDatastore
  Network:              dougm%2fnet
```
Will look at this more later, but the workaround of using network name with the encoded slash (%2f) as input should work fine.

**Comment by ooOOJavaOOoo** [comment]
Is there a special branch that I need to build for the / to work?  I've tried passing my/network and my%2fnetwork and both return "network not found"

**Comment by dougm** [comment]
What is the name as printed by the command above (`govc find / -type n`) ?

Which command is returning "network not found" ?

Related changes are in the master branch, if the network was created by the API or ESX UI with a "/" in the name.

But we still don't do anything special yet if network was created by the vCenter UI (which escapes "/" to "%2f").

**Comment by ooOOJavaOOoo** [comment]
I am actually running Terraform Apply on a set of plans where I fed in "my/network".  If I create the port group using Terraform everything works fine, but if someone else made the port group through the API I cannot use the /, it returns "network xxxxx not found"
