### ISSUE TITLE
vm.info uuid query don't work with vm templates

### ISSUE THREAD

**Issue by acortiana** [vmware/govmomi#848]
vm.info uuid query don't work with vm templates.
the same operation works fine with standard, non-template VMs.
I'm using the latest govc binary compiled from source.

`# ./govc vm.info -vm.ipath=/RMT/vm/Templates/VM_TEMPLATE_123456`
Name:           VM_TEMPLATE_123456
  Path:         /RMT/vm/Templates/VM_TEMPLATE_123456
  UUID:         4204883e-484b-8f3c-c33d-126a997a5a4b
  Guest name:   CentOS 4/5/6/7 (64-bit)
  Memory:       4096MB
  CPU:          4 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:   
  Host:         host.esx

`# ./govc vm.info -vm.uuid=4204883e-484b-8f3c-c33d-126a997a5a4b`
./govc: no such VM

**Comment by dougm** [comment]
Don't know why it wouldn't, the script below works for me, does it for you?
How was your template created?

```bash
#!/bin/bash -xe

govc vm.create -on=false -net "VM Network" foo

uuid=$(govc vm.info -json foo | jq -r .VirtualMachines[].Config.Uuid)

govc vm.info -vm.uuid $uuid

govc vm.markastemplate foo

govc vm.info -vm.uuid $uuid
```

**Comment by acortiana** [comment]
I have the problem using your script (./govc: no such VM)
The only problem I see is that the vcenter version I'm using is 5.1 (that is formally not supported by govc, right?)

**Comment by dougm** [comment]
We don't test against 5.1, but not sure there's much we can do if the issue is specific to that version anyhow.  Our use of SearchIndex for the `vm.uuid` flag is just using the documented API.  You can try using the find command like so:

```
% govc find / -type m -config.uuid 4204883e-484b-8f3c-c33d-126a997a5a4b | xargs govc vm.info
# or
% govc find / -type m -config.instanceUuid 4204883e-484b-8f3c-c33d-126a997a5a4b | xargs govc vm.info
```

**Comment by dougm** [comment]
Any luck using the find command?

**Comment by acortiana** [comment]
Yes, it worked, thanks!
