### ISSUE TITLE
Find custom field definition by key

### ISSUE THREAD

**Issue by joaodrp** [vmware/govmomi#854]
Hi,

There is a [FindKey](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/custom_fields_manager.go#L116) function for the `CustomFieldManager` that returns only the key of a custom field (if found). What’s the purpose of returning the key of the field, if you already have that key? Wouldn’t it be better to return a found/not found flag?

Nevertheless, wouldn’t it be useful to have another method that could locate and return the whole custom field definition by key instead of returning just the key attribute (e.g. something like `FindByKey`)? I can’t find a way to do it currently (without having to iterate over the list of custom fields “manually”). If this makes sense I’ll implement it.

**Comment by dougm** [comment]
Hi @joaodrp , I think it is just a poorly named param, 'key' should have been called 'name' as the helper is mean to map a name to key:
https://github.com/vmware/govmomi/blob/de0725fdaff9f17551a17d86826fe1ac5b4f4a85/object/custom_fields_manager.go#L123

Yes, I think it would be fine to add a `Find` method that returns the `*CustomFieldDef`.

**Comment by joaodrp** [comment]
@dougm thanks for your comment. 

Regarding the param `key`, is it ok if I open another issue (or use this one) and submit a pull request to change it to `name`?

About the `Find` method, I'll create a pull request for it. 

I assume you are thinking about a single `Find` method that would be able to search by the value of `Key` (int32), `Name`  (string) or `Value` (string) attributes?  Or independent `FindByKey`, `FindByName` and `FindByValue` methods?

**Comment by dougm** [comment]
We could change CustomFieldsManager.Field to return a type where we can attach these methods to find entries.

For an example, see: https://github.com/vmware/govmomi/blob/de0725fdaff9f17551a17d86826fe1ac5b4f4a85/object/authorization_manager.go#L40-L71

And:
https://github.com/vmware/govmomi/blob/de0725fdaff9f17551a17d86826fe1ac5b4f4a85/object/host_firewall_system.go#L70-L181

This way there's 1 method to fetch the property, and the other find/search methods can be used without having to re-fetch the property.

**Comment by joaodrp** [comment]
@dougm that sounds like a good idea 👍 

So, it would be something like this:

```go
// object/custom_fields_manager.go
//...
type CustomFieldDefList []types.CustomFieldDef

// func (m CustomFieldsManager) Field(ctx context.Context) ([]types.CustomFieldDef, error) {
func (m CustomFieldsManager) Field(ctx context.Context) (CustomFieldDefList, error) {
	var fm mo.CustomFieldsManager

	err := m.Properties(ctx, m.Reference(), []string{"field"}, &fm)
	if err != nil {
		return nil, err
	}

	return fm.Field, nil
}

func (l CustomFieldDefList) ByKey(key int32) *types.CustomFieldDef {
	for _, def := range l {
		if def.Key == key {
			return &def
		}
	}
	return nil
}
//...
```

And would be used like this:

```go
package main

import (
	"context"
	"net/url"

	"github.com/davecgh/go-spew/spew"
	"github.com/vmware/govmomi"
	"github.com/vmware/govmomi/object"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	u, _ := url.Parse("https://user:pass@localhost:8989/sdk")
	c, _ := govmomi.NewClient(ctx, u, true)

	defer cancel()
	defer c.Logout(ctx)

	m, _ := object.GetCustomFieldsManager(c.Client)
	l, _ := m.Field(ctx)
	def := l.ByKey(1)

	spew.Dump(def)
}
```

With sample output:

```sh
$ go run main.go
(*types.CustomFieldDef)(0xc4202b2000)({
   DynamicData: (types.DynamicData) {},
   Key: (int32) 1,
   Name: (string) (len=6) "foo",
   Type: (string) "",
   ManagedObjectType: (string) "",
   FieldDefPrivileges: (*types.PrivilegePolicyDef)(<nil>),
   FieldInstancePrivileges: (*types.PrivilegePolicyDef)(<nil>)
})
```

What do you think?

**Comment by dougm** [comment]
@joaodrp yes, looks good to me :+1:
