### ISSUE TITLE
vcsim: AuthorizationManager support

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#860]
Unable to create role using `govc` and latest `govcsim`

```
$ govc role.ls
govc: ServerFaultCode: ManagedObjectNotFound

$ govc role.create MyRole
govc: ServerFaultCode: ManagedObjectNotFound
```

**Comment by dougm** [comment]
I was discussing the lack of vcsim authz support with @lcastellano yesterday.  I'll open a PR that adds the properties for now, so the queries will work.  We can look at implementing the methods in separate PRs.
