### ISSUE TITLE
How do I vm.unregister a template?

### ISSUE THREAD

**Issue by johnjelinek** [vmware/govmomi#878]
```
$ govc vm.unregister -vm.ipath=packer-templates/base
govc: no such VM
```

![vsphere_web_client](https://user-images.githubusercontent.com/873610/31569577-67a62ae2-b041-11e7-8c13-7ca6afaa7070.png)

why you lyin' to me `govc`?

**Comment by dougm** [comment]
`-vm.ipath` uses the SearchIndex, which requires an absolute inventory path (including /datacenter-name/vm/).

You can use a relative path like so: `govc vm.unregister packer-templates/base`

**Comment by johnjelinek** [comment]
sweet, that worked!
