### ISSUE TITLE
"No network device found" cloning from a template without network adapter and govc

### ISSUE THREAD

**Issue by jorgelon** [vmware/govmomi#880]
Every time i try to clone a vm from a template using govc I get "No network device found". The original template has not network device. I dont know if it is correct or there is another workaround for that operacion. Basically I am trying to do a "deploy from template"

**Comment by anfernee** [comment]
Thanks @jorgelon for reporting the issue. Can you provide a reproducing steps and expected outcome, then it will very helpful for us to understand and fix the issue.

**Comment by jorgelon** [comment]
I have a template without network interface. If I use vm.clone from that template i get the error "No network device found". I get this error with and without using -net and -net.adpater parameters.

If i use vm.clone from a vm with network interface it works.
