### ISSUE TITLE
vcsim doesn't generate moref for VirtualMachine

### ISSUE THREAD

**Issue by xavierl1** [vmware/govmomi#888]
Hi,

We use moref internally to track the uniqueness of an object like VM or Host. A VC has info like "VirtualMachine:vm-15195". It will be much useful if vcsim has this info generated.

Thanks,
Xavier

**Comment by anfernee** [comment]
@xavierl1 in vcsim, we also generate moref internally. This is the way we refer to other objects internally. Just like to the regular user of vc, you might not see this weird moref value, but it is used everywhere.

**Comment by xavierl1** [comment]
@anfernee From a real VC, I can get VM info like:
{{} VirtualMachine:vm-16299 {{} [{{} 0xc4202e53e0 4000}] HostSystem:host-10 connected poweredOn

But the info from a vcsim is like the following. The moref field is missing. Since we use moref as a unique ID for an object like VM, we need this field. 
{{} <nil> {{} [] HostSystem:hostsystem-21 connected poweredOff

Thanks,
Xavier

**Comment by anfernee** [comment]
It looks like output from a go program. Can you share the snippet?

**Comment by xavierl1** [comment]
Yes. It is basically the VM example. 

package main

import (
	"context"
	"fmt"
	"log"

	"github.com/vmware/govmomi/examples"
	"github.com/vmware/govmomi/view"
	"github.com/vmware/govmomi/vim25/mo"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Connect and login to ESX or vCenter
	c, err := examples.NewClient(ctx)
	if err != nil {
		log.Fatal(err)
	}

	defer c.Logout(ctx)

	// Create view of VirtualMachine objects
	m := view.NewManager(c.Client)

	v, err := m.CreateContainerView(ctx, c.ServiceContent.RootFolder, []string{"VirtualMachine"}, true)
	if err != nil {
		log.Fatal(err)
		fmt.Println(err)
	}

	defer v.Destroy(ctx)

	// Retrieve summary property for all machines
	// Reference: http://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/vim.VirtualMachine.html
	var vms []mo.VirtualMachine
	err = v.Retrieve(ctx, []string{"VirtualMachine"}, []string{"summary"}, &vms)

	if err != nil {
		log.Fatal(err)
		fmt.Println(err)
	}

	// Print summary per vm (see also: govc/vm/info.go)

	for _, vm := range vms {
		fmt.Println(vm.Summary)
	}
}
