### ISSUE TITLE
vcsim generate Host moref different from a VC

### ISSUE THREAD

**Issue by xavierl1** [vmware/govmomi#889]
Hi,

A VC has Host moref like the following.
HostSystem:host-10

Vcsim generates this info slightly different.
HostSystem:hostsystem-52

It will be ideal if vcsim generates Host moref in the same format as a VC. 

Thanks,
Xavier

**Comment by anfernee** [comment]
@xavierl1 thanks for reporting the issue. Is there any use case where you require the moref to be like `host-xx` instead of `hostsystem-xx`? to my best knowledge, the value of moref is opaque, which shouldn't be interpreted in any way. Though current version of VC gives you `host-10` doesn't guarantee it will give you the same format in future releases. To be safe, I don't recommend hacking on this value.

**Comment by xavierl1** [comment]
@anfernee Thanks for the quick response. We are developing an appliance that retrieves moref from all versions of VCs. So far, all host moref is like "host-xxx". Since vcsim is a simulator, we prefer the look and feel is the same as a real VC. Internally, we use moref retrieved directly from a VC.

**Comment by anfernee** [comment]
@xavierl1 this is an incomplete list but it should cover the most popular cases. https://github.com/vmware/govmomi/pull/894/files#diff-49c8099fdee914770c183c1c73c03f57R32 Is it good for you now, or should I add more into it? Let me know.

**Comment by xavierl1** [comment]
@anfernee Currently we are using the following morefs. 

 datacenter-2
 domain-c299
 domain-s206
 group-d1
 group-h4
 group-v10338
 host-101
 resgroup-312
 vm-10218

Thanks,
Xavier

**Comment by xavierl1** [comment]
There is another one:

 resgroup-v502362

Thanks,
Xavier

**Comment by anfernee** [comment]
@xavierl1 are you okay with `group-11` instead of `group-d11`? I think in VC, `group-d` means folder for datacenter, `group-h` means folder for host, etc. For vcsim, it's hard to know what the folder is used for. It should look similar.

**Comment by xavierl1** [comment]
@anfernee I am OK with it.
