### ISSUE TITLE
object: VirtualDeviceList.CreateDisk should not require a ManagedObjectReference

### ISSUE THREAD

**Issue by vancluever** [vmware/govmomi#893]
https://github.com/vmware/govmomi/blob/bfed5eea1ab6e9b69e24c934792ad5b5aac8d2e4/object/virtual_device_list.go#L436

Looks like this function takes a non-pointer `types.ManagedObjectReference` right now, even though that parameter is not necessary in `VirtualDiskFlatVer2BackingInfo`. I'd like to be able to supply `nil` to this function to tell vShpere to create the backing in the same datastore as the virtual machine, assuming that's what this does (will amend the issue or just close it if that's not the case).

**Comment by dougm** [comment]
Not sure how we ended up with ds being a mandatory param to `CreateDisk()`, other than that it was related to adding datastore cluster support.  We could either break the method signature, or change to check `if ds.Value == "" { // derive ds.Value from the name param }`.

**Comment by vancluever** [comment]
Yeah not a huge deal right now, as I'm just zeroing out this value after the fact (as in the new VM code for TF there's a lot of other device options that need to be set anyway).

I think a zero-value check on either the whole moref or at least on `Value` would be the least breaking change and would be fine, it could then either be called:

```go
l.CreateDisk(c, types.ManagedObjectReference{}, "")
```

Or how I currently have it in the new refactor:

https://github.com/terraform-providers/terraform-provider-vsphere/blob/bec997c3dd1c104121da93246294fab32a02f13f/vsphere/virtual_machine_disk_subresource.go#L369

And then I would just need to drop the latter zeroing out of the datastore ref. I'd probably refactor it after to just pass in the datastore ID, even if it was blank.
