### ISSUE TITLE
govcsim: pyvmomi fails to get portgroups on a newly created DVS in govcsim

### ISSUE THREAD

**Issue by pdellaert** [vmware/govmomi#904]
I was using Ansible together with the govcsim to test changes to a module, and ran into the below error. 

My playbook first creates a DVS, and then creates a new portgroup on that dvs:
```
- name: add distributed vSwitch
  vmware_dvswitch:
    validate_certs: False
    hostname: "{{ vcsim }}"
    username: "{{ vcsim_instance['json']['username'] }}"
    password: "{{ vcsim_instance['json']['password'] }}"
    datacenter_name: "{{ item | basename }}"
    state: present
    switch_name: dvswitch_0001
    mtu: 9000
    uplink_quantity: 2
    discovery_proto: lldp
    discovery_operation: both
  register: dvs_result_0001
  with_items:
    - "{{ datacenters['json'] }}"

# Testcase 0001: Add basic portgroup
- name: create basic portgroup
  vmware_dvs_portgroup:
    validate_certs: False
    hostname: "{{ vcsim }}"
    username: "{{ vcsim_instance['json']['username'] }}"
    password: "{{ vcsim_instance['json']['password'] }}"
    switch_name: dvswitch_0001
    portgroup_name: "basic"
    vlan_id: 0
    num_ports: 32
    portgroup_type: earlyBinding
    state: present
  register: dvs_pg_result_0001
```

This is the error
```
The full traceback is:
  File "/tmp/ansible_d60JOg/ansible_module_vmware_dvs_portgroup.py", line 167, in process_state
    dvspg_states[self.state][self.check_dvspg_state()]()
  File "/tmp/ansible_d60JOg/ansible_module_vmware_dvs_portgroup.py", line 247, in check_dvspg_state
    self.dvs_portgroup = find_dvspg_by_name(self.dv_switch, self.portgroup_name)
  File "/tmp/ansible_d60JOg/ansible_modlib.zip/ansible/module_utils/vmware.py", line 85, in find_dvspg_by_name
    portgroups = dv_switch.portgroup
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 43, in InvokeAccessor
    objectContent = result.objects[0]
```
The relevant part seems to be in pyvmomi lines (last 3 file mentions). It seems that on a `DistributedVirtualSwitch` object, calling the `portgroup` object will fail in pyvmomi with `list index out of range`.  

I'm guessing that govcsim doesn't automatically add a uplink portgroup to the DVS, causing the DVS not to have any portgroups at all (which is not in line with the API, as this always creates an uplink port group)

**Comment by dougm** [comment]
@pdellaert does this solution apply here too? https://github.com/vmware/govmomi/issues/879#issuecomment-337074322

**Comment by anfernee** [comment]
To add some context, the problem of this `list index out of range` is due to the `vmware_dvswitch` module tries to find dvs with type `VmwareDistributedVirtualSwitch`, while all the dvs created in vcsim is of type `DistributedVirtualSwitch`. so the result object list is empty.

**Comment by pdellaert** [comment]
@dougm,yes, as @anfernee seems to suggest, that might be the case. However, why do we have two different types? I assume in an actual vCenter they behave the same?

**Comment by dougm** [comment]
Yes, it is the case that vcsim uses the base type `DistributedVirtualSwitch`.

The `VmwareDistributedVirtualSwitch` extends that type, adding a `lacpGroupSpec` field and a method to update that field: http://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.wssdk.apiref.doc/vim.dvs.VmwareDistributedVirtualSwitch.html

Unless you need do to something specific to `lacpGroupSpec`, stick with the base type.  ContainerView with the base type works the same against real vCenter.

**Comment by pdellaert** [comment]
@dougm , thanks... It does seem that during startup of vcsim, it creates a `VmwareDistributedVirtualSwitch`, because when i try to add a portgroup to the existing DVS (DVS01), it works perfectly. The issue comes when i first try to create a DVS (using https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_dvswitch.py) , that i can't add a portgroup to it, because it gives that `list index out of range` issue...

On vCenter it does work as expected. So i'm just curious on where the behavioural difference is. Perhaps we should update the vmware_dvswitch code so it creates the correct type?

**Comment by dougm** [comment]
Hmm, if you're seeing a `VmwareDistributedVirtualSwitch` at startup, you should update to the latest.  With the latest, you should see:
```console
% govc ls -l /... | grep DVS
/DC0/network/DVS0 (DistributedVirtualSwitch)
```
Rather than `Vmware`:
```console
% govc ls -l /... | grep DVS
/DC0/network/DVS0 (VmwareDistributedVirtualSwitch)
```

**Comment by dougm** [comment]
@pdellaert were you able to work this out?  Feel free to open with more info if there are still issues.
