### ISSUE TITLE
VirtualDeviceList, PCI devices, and reserved unit numbers

### ISSUE THREAD

**Issue by vancluever** [vmware/govmomi#907]
I think there might be a bit of an issue with working with device unit numbers and PCI devices.

Consider the following scenario where we add a SCSI controller, a disk, and a virtual NIC, working off a base device list fetched from the environment browser. We follow the same workflow for all of the devices, namely create the device, assign it to a controller using `AssignController` (except for the SCSI controller), and connect it (although the 3rd step is not necessarily relevant to this issue).

* SCSI controller gets created, no action on connecting this device is undertaken by VirtualDeviceList (assuming because it's a bus unto itself).
* Disk gets created and correctly assigned unit 0 on the new SCSI controller.
* Ethernet controller gets created, connected to the PCI controller, and assigned a unit number of 1 because 0 is already taken by the video card.

However, what ultimately shows up in vSphere is a different story:

* The SCSI controller gets connected to the PCI bus and assigned a unit number of 3
* The network controller's unit number is changed to 7
* The other two devices connected by default from EnvironmentBrowser on the PCI bus retain their unit numbers, namely the video card at unit 0 and the VMCI controller at unit number 17.

Is there a reliable convention for unit number assignment here that's carried out by vSphere? What I'm trying to do is get a stable assignment for network devices in TF in a way that we can track their state across the entire lifecycle, and keep device assignment operations atomic. Since keys are not necessarily stable until at least one create operation has been carried out, I figured that a combination of controller type, bus number, and unit number might be a good idea. This works great for disks but not so much for network interfaces, due to the issues above.

If there is can we possibly throw that into `VirtualDeviceList` so that the results it returns are stable across operations?

It almost seems like there's some convention here, but I'm taking a shot in the dark here:

* 0-2: Video card and other system-level devices
* 3-6: SCSI controllers
* 7-16: NICs and other devices
* 17: VMCI

**Comment by caglar10ur** [comment]
@vancluever maybe https://kb.vmware.com/s/article/2047927?language=en_US and http://d.hatena.ne.jp/incarose86/20150117/1421509639 could help

**Comment by vancluever** [comment]
Hey @caglar10ur, that's definitely useful, but not necessarily covering what I'm referring to here - I'm more referring to the parameters of the `VirtualDevice` object in the API - as seen here: https://pubs.vmware.com/vsphere-6-5/topic/com.vmware.wssdk.apiref.doc/vim.vm.device.VirtualDevice.html

Funny enough out of curiosity I did take a look at an VMX file from one of our acceptance tests and don't really see any connection between any of the device unit data and what shows up in the VMX file.

**Comment by dougm** [comment]
Haven't had a chance to take a close look at this myself yet, will try to do that in the next day or two.

**Comment by vancluever** [comment]
Thanks @dougm, for now I have my own logic local to the vSphere TF provider that assigns the unit numbers in the 7-16 range for NIC devices and that seems to be stable. We aren't managing any devices on the PCI bus otherwise, or at least in a way that we need to worry about unit numbers (ie: we aren't tracking unit numbers on SCSI devices for example).
