### ISSUE TITLE
ServiceManager help

### ISSUE THREAD

**Issue by danofa** [vmware/govmomi#912]
Hi,

I am unable to find a way to utilise the ServiceManager -> https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.ServiceManager.html

Could anyone point me in the right direction ? I've done some digging and I'm not even sure its implemented (like Perfmanager) is this correct ?

Cheers

**Comment by dougm** [comment]
It's there in the generated code: https://github.com/vmware/govmomi/blob/master/vim25/mo/mo.go#L1467-L1471

But there are no helpers around it.  You may want to look at HostServiceSystem as an example: https://github.com/vmware/govmomi/blob/master/object/host_service_system.go#L32
And the govc host.service commands: https://github.com/vmware/govmomi/tree/master/govc/host/service

You can also access its properties via:
```console
% govc object.collect -json $(govc object.collect -s - content.serviceManager) service | jq .
[
  {
    "Name": "service",
    "Op": "assign",
    "Val": {
      "ServiceManagerServiceInfo": [
        {
          "ServiceName": "Esxtop",
          "Location": null,
          "Service": {
            "Type": "SimpleCommand",
            "Value": "52f6b5b6-bb4e-2df3-1fd6-539af945afdd"
          },
          "Description": "Pack esxtop data"
        },
        {
          "ServiceName": "VscsiStats",
          "Location": null,
          "Service": {
            "Type": "SimpleCommand",
            "Value": "52f07bcb-7560-7c6b-0218-b27a98cc115c"
          },
          "Description": "Pack vscsiStats data"
        }
      ]
    }
  }
]
```

**Comment by dougm** [comment]
Did you find what you need @danofa ?

**Comment by danofa** [comment]
Hi @dougm, no I gave up trying to implement the needed helpers, but thanks for the information.
