### ISSUE TITLE
vcsim: PropertyFilters not destroyed when Session is closed

### ISSUE THREAD

**Issue by ausevj** [vmware/govmomi#923]
PropertyFilters are not being destroyed when user terminates the session (e.g. login, logout).

**Steps to reproduce:**
1) Login
2) CreateFilter
3) Call WaitForUpdatesEx with empty version (returns a set of filters that user created)
4) Logout
5) Login
6) CreateFilter
7) Call WaitForUpdatesEx with empty version

**Results**
Executing these steps on vcsim server, second WaitForUpdatesEx returns UpdateSet containing 2 filters

**Expected Results**
Executing these steps on real VCenter, second WaitForUpdatesEx returns UpdateSet containing 1 filter

**Comment by dougm** [comment]
While vcsim's SesionManager.Login returns a session key, we don't currently track it across requests.  So the managed objects that should be per-session (such as PropertyFilter, ContainerView, ListView), are not currently associated with a session.
