### ISSUE TITLE
method DefaultDatacenter err

### ISSUE THREAD

**Issue by huyujie** [vmware/govmomi#941]
I can't understand,
```
func (f *Finder) Datacenter(ctx context.Context, path string) (*object.Datacenter, error) {
	dcs, err := f.DatacenterList(ctx, path)
	if err != nil {
		return nil, err
	}

	if len(dcs) > 1 {
		return nil, &MultipleFoundError{"datacenter", path}
	}

	return dcs[0], nil
}
```
Most of the time,len(dcs)>1,so it will return err for us in most of the time.

**Comment by dougm** [comment]
Use the `path` param to specify a specific datacenter name or path.  For example `DC1`, `/DC1`, `/FolderName/DC1`.

**Comment by dougm** [comment]
Please re-open if you're still having issues with this method.
