### ISSUE TITLE
Inflate Disk

### ISSUE THREAD

**Issue by johnjelinek** [vmware/govmomi#942]
I have a template and I'd like to inflate it. I can do this with `vmkfstools --inflatedisk *.vmdk` -- but I'd really like to use `govc`. Is this currently possible?

**Comment by dougm** [comment]
@johnjelinek possible with PR #943

I hadn't used it before, but both `vmkfstools --inflatedisk` and  `govc datastore.disk.inflate` look to have the same results.  Disk created with type `thin` results in `eagerZeroedThick` and zeroed to capacity.
