### ISSUE TITLE
Remove orphan templates

### ISSUE THREAD

**Issue by johnjelinek** [vmware/govmomi#944]
In my case, the files associated with a template has already been removed from the disk. If I run: `govc vm.unregister packer-templates/base` it says:
```
govc: vm 'packer-templates/base' not found
```
and the orphan remains. How can I remove it from the inventory? It doesn't have a `vmid` anymore. It doesn't even show up in `/etc/vmware/hostd/vmInventory.xml`.

**Comment by johnjelinek** [comment]
It's an inventory folder

**Comment by dougm** [comment]
What about `ls` and `find` question?  If it doesn't show up there, you can just use `datastore.rm` to remove any files left behind.

**Comment by josdotso** [comment]
This worked for a template which was showing "(orphaned)" on its name:

```
govc vm.destroy /$datacenterName/vm/$nameOfTemplate
```

**Comment by dougm** [comment]
@johnjelinek still having this issue?

**Comment by johnjelinek** [comment]
No, I think I'm good now.
