### ISSUE TITLE
govc: Another task is already in progress

### ISSUE THREAD

**Issue by faridlahdiri** [vmware/govmomi#953]
Hi,
We have been deploying VMs using the govmomi / govc cli. It works great. Lately we have seen some errors in our CI lab (We use ansible roles to deploy a bunch of VMs) related essentially to adding or inserting a cdrom into a VM. 
Thanks in advance
/Farid

Here is one of the errors
/usr/local/bin/govc device.cdrom.insert -vm=vm1 -ds=datastore1 vm1/vm1.iso
"stderr": "/usr/local/bin/govc: Another task is already in progress."

#govc version
govc 0.14.0

# govc about
Name:         VMware ESXi
Vendor:       VMware, Inc.
Version:      5.5.0
Build:        3568722
OS type:      vmnix-x86
API type:     HostAgent
API version:  5.5
Product ID:   embeddedEsx
UUID:

**Comment by anfernee** [comment]
Hey @faridlahdiri  this is a ESX error. Basically when you do concurrent operations (tasks) on the same object (vm), you will have that error. You can use `govc tasks` to check the tasks running on the target.

**Comment by dougm** [comment]
Closing as stale - feel free to reopen if this is still an issue.
