### ISSUE TITLE
vcsim: does not support 'NestedHVSupported' Property

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#956]
I am unable to set 'NestedHVSupported' property of virtual machine using govc and vcsim.

```
# govc vm.info -json DC0_H0_VM5 | jq '.[][0].Capability.NestedHVSupported'
null

# govc vm.change -nested-hv-enabled=True -vm DC0_H0_VM5

# echo $?
0

# govc vm.info -json DC0_H0_VM5 | jq '.[][0].Capability.NestedHVSupported'
null
```

**Comment by anfernee** [comment]
@Akasurde your `vm.change` command here `govc vm.change -nested-hv-enabled=True -vm DC0_H0_VM5` won't affect `Capability.NestedHVSupported`. It should change `Config.NestedHVEnabled` but it hasn't. The PR will fix that.
