### ISSUE TITLE
Manage tags with govc

### ISSUE THREAD

**Issue by angystardust** [vmware/govmomi#957]
Is it possible to add support for creating/managing and assign tags with govc?
It would be great to have the same feature available via PowerCLI:
https://blogs.vmware.com/PowerCLI/2014/03/using-vsphere-tags-powercli.html

**Comment by dougm** [comment]
Not yet.  This api and content library (#735) are only available in the REST api, so they aren't included in the wsdl generated code in govmomi.

Have been considering adding just this subset of the REST api to govmomi, we have the start of tags here: https://github.com/vmware/vic/tree/master/pkg/vsphere/tags

**Comment by dougm** [comment]
Closing with initial functionality complete, we'll consider the govc tags command set finalized for the 0.19 release when #1180 is closed.
