### ISSUE TITLE
govc vm.clone -net.address doesn't work, silently does nothing?

### ISSUE THREAD

**Issue by bradfitz** [vmware/govmomi#960]
I'm trying to set an explicit MAC address for a cloned VM. If I do this:

```
govc vm.destroy --persist-session=false cloned_vm || true
govc vm.clone -vm frozenbasevm -c=2 -m=2048 -net=Untrusted -net.address=00:50:56:bb:ae:51 -on=true -link=true -ds=nfs_ds916 cloned_vm
```

... and it clones & boots and everything works, except the VM comes up with a random MAC address.

I get no error that my `-net.address` was wrong or otherwise ignored.

I'd expect it to either work, or fail and tell me why it won't work.

How can I help debug?

**Comment by dougm** [comment]
iirc you can't use the VMW OUI  `00:50:56` for static mac addresses, but can't recall why it just ignores you rather than fail.  Can you use a different OUI?  `00:00:0f` is the NeXT OUI use in this test:

https://github.com/vmware/govmomi/blob/master/govc/test/network.bats#L138

**Comment by bradfitz** [comment]
I only picked `00:50:56` because it was used by one of my cloned VMs and I saw it was owned by VMware, so figured it was safe to use.

I'll try other OUIs. I didn't know vSphere cared. Thanks!

Oh, and I found https://networkengineering.stackexchange.com/questions/18747/differentiating-oui-mac-addresses-from-random-mac-addresses with hints on how to generate locally-assigned MAC addrs.

It'd be nice to keep this bug open about making govc return an error on `00:50:56`, though.

**Comment by bradfitz** [comment]
Actually, I just hit this bug again, even with non-VMware OUIs.

It appears that `govc vm.clone` just always ignores `-net.address`. Maybe the network modification is done at the wrong time? That is, maybe it's set too early and it gets overridden by other API calls?

My workaround is I have to call `vm.clone -power=off` and then change the MAC after:

```
$ govc vm.clone -vm ubuntu1604 -ds=ss2_ssd -net=k8s -power=off worker_2
-net.address=00:16:3E:E1:AA:70
$ govc vm.network.change  -net.address=00:16:3E:E1:AA:70 -vm=worker_2 -net=k8s ethernet-0
$ govc vm.power -on worker_2
```

(The first `-net.address` up there doesn't seem to matter, present or absent.)

Am I holding it wrong?
