### ISSUE TITLE
vcsim: support importing an OVF

### ISSUE THREAD

**Issue by sivel** [vmware/govmomi#963]
It does not appear as though vcsim supports importing an OVF, resulting in the following error:

```
2017/12/13 11:31:29 managed object not found: OvfManager:OvfManager
```

A trace from my interactions trying to deploy an OVF: https://gist.github.com/sivel/4da863d7ff35955f7aaf0196a69bdd2b

Command:

```
govc import.ovf -pool DC0_C0_RP1 centos-7.4-x86_64.ovf
```

**Comment by dougm** [comment]
We don't yet, but planning to add a some point.
Closing a dup of #799
