### ISSUE TITLE
Get AntiAffinityRule key

### ISSUE THREAD

**Issue by jnahelou** [vmware/govmomi#980]
Hi,

While trying to automate anti-affinity rules, I was not able to find properly the key generated by vCenter for my rule(s).

I create rules like :

``` main.go
	var ruleSpecs []types.ClusterRuleSpec
	aaRule := &types.ClusterAntiAffinityRuleSpec{}
	aaRule.Name = "foo"
	aaRule.Mandatory = boolPtr(false)
	aaRule.Enabled = boolPtr(true)
	aaRule.Vm = refVMs
	spec := types.ClusterRuleSpec{}
	spec.Operation = types.ArrayUpdateOperationAdd
	spec.Info = aaRule
	ruleSpecs = append(ruleSpecs, spec)
	clusterSpec := &types.ClusterConfigSpecEx{RulesSpec: ruleSpecs}

	task, err := cluster.Reconfigure(ctx, clusterSpec, true)
	info, err := task.WaitForResult(ctx, nil)
	if err != nil {
		log.Fatalf("error waiting for aaRule creation to complete: %s", err)
	}
```

The result provided by the ```Reconfigure()``` method is null :

```
&{DynamicData:{} Key:task-7354 Task:Task:task-7354 Description:<nil> Name:ReconfigureComputeResource_Task DescriptionId:ClusterComputeResource.reconfigureEx Entity:ClusterComputeResource:domain-c7 EntityName:XXXXX Locked:[] State:success Cancelled:false Cancelable:false Error:<nil> Result:<nil> Progress:0 Reason:0xc420294510 QueueTime:2018-01-02 07:48:42.71794 +0000 UTC StartTime:2018-01-02 07:48:42.72325 +0000 UTC CompleteTime:2018-01-02 07:48:42.737038 +0000 UTC EventChainId:2046597 ChangeTag: ParentTaskKey: RootTaskKey: ActivationId:}
```

There 2 way I found to get the ```rule.Key``` and ```rule.Uuid``` :
 -  using event manager as bellow to parse logs....

``` main.go
	events, err := manager.QueryEvents(ctx, types.EventFilterSpec{EventChainId: info.EventChainId})
	if err != nil {
		log.Fatalf("Error QueryEvents: %s", err)
	}

	log.Printf("%+v", events)
	for _, event := range events {
		log.Printf("Event <<<%+v>>>\n", event.GetEvent().FullFormattedMessage)
	}
```

- or by listing all rules and looking for same name & vms :
``` main.go
	clusterInfo, err := finder.ClusterComputeResource(ctx, clname)
	cluserConfig, err := clusterInfo.Configuration(ctx)
	for _, crule := range cluserConfig.Rule {
		info := crule.GetClusterRuleInfo()
		log.Printf("Key : %v, Name : %v, ruleUuid : %v\n", info.Key, info.Name, info.RuleUuid)
	}
```

I think it's not an issue because vCenter task refer to event too.. Is there an other way more safe as previous ? 

Thanks for your help.

**Config**
vSpherev : version 6.5.0 build 4598948 
Hosts : VMware ESXi, 5.5.0, 2068190

**Comment by dougm** [comment]
Right, the `ReconfigureComputeResource_Task` API does not return any value.  Using the Configuration properties is the best way that I know of.

btw, we recently added govc commands to manage cluster rules: https://github.com/vmware/govmomi/tree/master/govc/cluster/rule

**Comment by jnahelou** [comment]
As I understand, ```rule package``` lookup the ```key``` using ```name``` property, but ```name``` is not unique in vCenter. In some cases, user can create first manually a rule with the same name but different VMs... By this way the cli will modify the wrong rule right ? 
Tracking the event log seems my only solution if I want to ensure the good rule :'(

``` info_flag.go
func (f *InfoFlag) Rule(ctx context.Context) (*ClusterRuleInfo, error) {
	rules, err := f.Rules(ctx)
	if err != nil {
		return nil, err
	}

	for _, rule := range rules {
		if rule.GetClusterRuleInfo().Name != f.name {
			continue
		}

		r := &ClusterRuleInfo{info: rule}

		switch info := rule.(type) {
		case *types.ClusterAffinityRuleSpec:
			r.refs = &info.Vm
			r.kind = "VirtualMachine"
		case *types.ClusterAntiAffinityRuleSpec:
			r.refs = &info.Vm
			r.kind = "VirtualMachine"
		}

		return r, nil
	}

	return nil, fmt.Errorf("rule %q not found", f.name)
}
```

Thanks for you tips.

**Comment by dougm** [comment]
I hadn't considered duplicate names in this case.  Maybe for the govc command we could error if name is not unique and add a flag to use the key instead.

**Comment by anukul-mohil** [comment]
You can actually have two different rules with same name and same set of vms. Only distinguishing factor is the ruleUuid and key associated with the rule which forces us to make redundant calls to the vcenter which could have been easily avoided if task.result would have returned a rule.Uuid.
