### ISSUE TITLE
CustomizationSpec management API wanted in govc CLI

### ISSUE THREAD

**Issue by stainboy** [vmware/govmomi#984]
This issue will probably be a duplication of #616, but it explains the use case in a different way.

When using `govc vm.clone`, there is no way to pass dynamic `CustomizationSpec`. govc will always retrieve an existing spec from esxi/vcenter and try to use it, via `--customization` args.

Details can be found in the following code,

govc/vm/clone.go

```go
// check if customization specification requested
if len(cmd.customization) > 0 {
	// get the customization spec manager
	customizationSpecManager := object.NewCustomizationSpecManager(cmd.Client)
	// check if customization specification exists
	exists, err := customizationSpecManager.DoesCustomizationSpecExist(ctx, cmd.customization)
	if err != nil {
		return nil, err
	}
	if exists == false {
		return nil, fmt.Errorf("Customization specification %s does not exists.", cmd.customization)
	}
	// get the customization specification
	customSpecItem, err := customizationSpecManager.GetCustomizationSpec(ctx, cmd.customization)
	if err != nil {
		return nil, err
	}
	customSpec := customSpecItem.Spec
	// set the customization
	cloneSpec.Customization = &customSpec
}
```

But there is no `CustomizationSpec` management API exposed by govc CLI, which means there is no way to dynamically create customSpec and then clone vm via the new created spec.

That's why I hope govc can have this nice feature in the future.

**Comment by dougm** [comment]
Yes, I like the idea of a `vm.customize` command: https://github.com/vmware/govmomi/issues/616#issuecomment-336944682

I still have yet to use customizations myself, any pointers would be appreciated, such as:
- Simple OS template to test with (ideally automated via packer for example)
- Any GUI screenshots that shows the manual workflow to define / apply customizations

**Comment by mylesagray** [comment]
@dougm - I am using the Ubuntu cloud images OVAs for testing (16.04 as 18.04 has a cloud-init bug):

https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64.ova

```sh
govc import.spec ~/Downloads/ubuntu-16.04-server-cloudimg-amd64.ova | python -m json.tool > ubuntu.json
```

I customise the OVF spec as below, editing `public-keys`, `Network` and `Name`:

```sh
$ cat ubuntu.json
{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "PropertyMapping": [
        {
            "Key": "instance-id",
            "Value": "id-ovf"
        },
        {
            "Key": "hostname",
            "Value": "ubuntuguest"
        },
        {
            "Key": "seedfrom",
            "Value": ""
        },
        {
            "Key": "public-keys",
            "Value": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB[[[[[MY PUBLIC KEY]]]]3OEWMRM4/PsqPS2t/VAL993OdSshHGtT30AP86G+vuHuecw== mylesg@vmware.com"
        },
        {
            "Key": "user-data",
            "Value": ""
        },
        {
            "Key": "password",
            "Value": ""
        }
    ],
    "NetworkMapping": [
        {
            "Name": "VM Network",
            "Network": "VM Network"
        }
    ],
    "MarkAsTemplate": false,
    "PowerOn": false,
    "InjectOvfEnv": false,
    "WaitForIP": false,
    "Name": "Ubuntu1604Template"
}
```

From there, import the OVA and mark as a template:

```sh
govc import.ova -options=ubuntu.json ~/Downloads/ubuntu-16.04-server-cloudimg-amd64.ova
govc vm.markastemplate Ubuntu1604Template
```

In VC I have a customisation spec created as below:

![VM Spec1](http://dl.dropboxusercontent.com/s/gvspaz0ho8poh9b/Screenshot%202019-01-25%2019.44.09.png)

![VM Spec2](http://dl.dropboxusercontent.com/s/5i7p4z0xsoy4t6d/Screenshot%202019-01-25%2019.44.15.png)

![VM Spec3](http://dl.dropboxusercontent.com/s/7agpetkvkrf9ywm/Screenshot%202019-01-25%2019.44.22.png)

![VM Spec4](http://dl.dropboxusercontent.com/s/dmbq2x9nl96pohn/Screenshot%202019-01-25%2019.44.29.png)

![VM Spec5](http://dl.dropboxusercontent.com/s/wicb6s0159qjpss/Screenshot%202019-01-25%2019.44.38.png)

![VM Spec6](http://dl.dropboxusercontent.com/s/desbqn6ftj37nnu/Screenshot%202019-01-25%2019.44.46.png)

![VM Spec7](http://dl.dropboxusercontent.com/s/rtze5gara2niiua/Screenshot%202019-01-25%2019.44.54.png)

Then to apply the customisation spec, you deploy a new VM from Template -> enable "Guest OS Customisation" and pick the Customisation Spec, from there it will prompt for any manually required inputs:

![Deploy Template1](http://dl.dropboxusercontent.com/s/n41ra1i19x8mgmu/Screenshot%202019-01-25%2019.45.39.png)

![Deploy Template2](http://dl.dropboxusercontent.com/s/r1ltr5xv7rga6y7/Screenshot%202019-01-25%2019.45.45.png)

**Comment by DanyC97** [comment]
would be very nice to have this feature in
