### ISSUE TITLE
govc: reading/writing metadata about VMs

### ISSUE THREAD

**Issue by Boran** [vmware/govmomi#985]
Hi, looking to understand how to read and write metadata on Vms.

a) When creating a VM, there is "-annotation=" option. Where can the value be read from the vCenter UI? It is not under "Notes". How can one set a value in the Notes with govc?

b) Fields/custom attributes.
These can be set with  "govc fields.set Key Value Vmname"
They are visible in the vCenter UI. How can they be read with govc? 
"govc vm.info Vmname" does not show them.

c) How does one assign rights to users to allow them to write Fields?
There are roles+rights which can be assigned to folders, datastores, networks etc. but how to assign rights on fields?

d) Is does not seem to be possible to write any Notes or Fields to Templates. Is there a way to stored meta infos (e.g. creation time, description) for a template?

**Comment by dougm** [comment]
a) yes, `-annotation` is displayed in the GUI "Notes" section.  You should also see it here, when set from govc or the GUI:
```console
% govc vm.info -json vm-name | jq .VirtualMachines[].Config.Annotation
"My vm Notes"
```
b)
```console
% key=$(govc vm.info -json vm-name | jq '.VirtualMachines[].AvailableField[] | select(.Name == "MyField") | .Key')
% govc vm.info -json vm-name | jq ".VirtualMachines[].CustomValue[] | select(.Key == $key) | .Value"
"my-value"
```

c) Don't know, but there should be docs and examples in other languages on that.  I can help convert to govc commands if you can find some pointers.

d) Don't know, have you tried using guestinfo with a template?  Or maybe the tags API (#957) can do that?

**Comment by Boran** [comment]
a)+b): thanks very much.

c) "How does one assign rights to users to allow them to write Fields"
Found a solution: In vCenter v6.5, one creates a Role with the right "Global > Set custom attribute"

d) In fact, after fixing the rights, fields.set works just fine (even if it cannot be done from the UI)
