### ISSUE TITLE
datastore.mv won't rename directory

### ISSUE THREAD

**Issue by johnjelinek** [vmware/govmomi#993]
```
$ govc datastore.ls
base_1
base
```
```
$ govc datastore.mv base base_2
govc: Cannot complete the operation because the file or folder [DS_3] base_2 already exists
```
... `base_2` does not already exist.

**Comment by johnjelinek** [comment]
I think maybe since this is an NFS datastore, it's maybe not showing the latest state. Is this common? Does it need to be re-mounted?

**Comment by dougm** [comment]
Don't think I've seen this issue before.  Did base_2 used to exist?  If so, how much time between it being deleted and trying to do the rename?  Are you able to rename other directories, such as below?

```console
% govc datastore.mkdir foo
% govc datastore.mv foo bar
```

**Comment by johnjelinek** [comment]
this is getting weird:
```
ls -lah /vmfs/volumes/DS_3/
total 24
drwx------    1 root     root        8.0K Feb 16  2016 .
dr-xr--r-x    1 root     root           0 Feb 16  2016 .iorm.sf
-rwxr-xr-x    1 root     root       16.1K Jan 11 00:23 .iormstats.sf
-rwxrwxr-x    1 root     root          84 Jan 11 00:23 .lck-030000006ce87f64
drwx------    1 root     root           0 Feb 16  2016 .vSphere-HA
dr-xr--r-x    1 root     root           0 Dec  2 01:00 base_1
dr-xr--r-x    1 root     root           0 Dec  2 01:00 base_1
```
yes, I think `base_2` used to exist. There was about 15 minutes between it was deleted vs trying to rename. I can rename other directories.

**Comment by johnjelinek** [comment]
I think this issue is exposed by NFS mounts. I'm avoiding that messed up datastore for now, I'll update if I see this again.
