### ISSUE TITLE
How to clone disk in govc, like vmkfstool -i ?

### ISSUE THREAD

**Issue by philzyk** [vmware/govmomi#999]
Hello!
govc is a great tool, much better, then abandoned rvc, but...
I need to clone vmdk-disk (both vmk and flat.vmdk files).
Vmkfstools do it very well, but i can't call it from govc.
So, i've tried to copy files and change link to -flat.vmdk-file, but it's a crazy coding 
# Extent description
RW 67108864 VMFS "tmpl_en_windows_10_multi-edition_vl_version_1709_updated_sept_2017_x64-flat.vmdk"
Any ideas?
Thank you.

**Comment by dougm** [comment]
@philzyk can you try the new `datastore.disk.cp` command?

**Comment by philzyk** [comment]
Thank You!
GREAT JOB!
But i'am using govc as binary.
Shell i need to build it from sources?

**Comment by dougm** [comment]
PR #1036 removes `datastore.disk.cp` and fixes `datastore.cp` to properly clone a .vmdk using VirtualDiskManager.

**Comment by remoe** [comment]
@dougm I try to copy a disk which are attached to a running VM. It throws the error ```Error: Unable to access file```:

```
govc datastore.cp -ds=abc -ds-target=xyz disks/test.vmdk disks/test.vmdk
```

Is this generally not possible, or is there any way to do it?

Thanks.

**Comment by dougm** [comment]
@remoe don't think that's possible with datastore.cp (`VirtualDiskManager`).  I would try `vm.clone`, if that's able to clone a running VM, you could then just detach the disk backed by the vmdk you're trying to copy and destroy the cloned vm.

**Comment by reski-rukmantiyo** [comment]
Hi @dougm, just wondering, is this clone methods works with CBT algorithm?
